### ISSUE TITLE
定义字段验证规则

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#1000]
https://help.salesforce.com/articleView?id=fields_about_field_validation.htm&type=5

**Comment by baozhoutao** [comment]
在before trigger 之后执行。 代码入口位置为：object.ts -> callAdapter 函数

**Comment by sunhaolin** [comment]
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_validationformulas.htm @孙浩林 验证规则表结构参考这里
