### ISSUE TITLE
【意见规则调整】

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1003]
1 第N+1此来到此步骤时，如果没有填写意见，提交时，保留原来显示的意见(可能是多条)
2 如果填写了意见，则显示最新意见，原来的意见不显示。无需考虑用户是否手动开启过意见 。 此处添加系统级开关，用于控制是否保留上次意见，默认保留。提交新意见后，原来显示中的意见不自动关闭。
3 不想显示任何意见：打开签批意见，手动关闭目前显示中的意见
4 默认意见：如果此步骤上填写过意见，且本次没填写意见，继续显示上次意见。(应该无需调整代码)

- [x] 标准平台
- [x] 秦皇岛港

**Comment by sunhaolin** [comment]
"hideLastSignApproveDescription": true的配置下，下方的意见不会显示 上一次的意见；而 点“签批”出来的意见栏 里，还有有上一次的 意见 。这个要修改为不显示
