### ISSUE TITLE
零代码，累计汇总，选择要聚合的字段，缺少公式字段（数值格式）

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1014]
![图片已粘贴至2020-10-22 17-32](https://user-images.githubusercontent.com/7553007/96854791-7a052080-148e-11eb-8aa7-bc5307442e09.png)
例如图中，没有 订单明细 的 价格（公式：单价*数量）

**Comment by yinlianghui** [comment]
已处理，要聚合的字段为公式或汇总字段时都支持
