### ISSUE TITLE
ios客户端访问，登录页点击输入登录信息时，页面会自动拉到底下

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#1023]
![image](https://user-images.githubusercontent.com/15027092/97127765-7cf55f00-1775-11eb-8664-a077fc5e267b.png)

**Comment by yinlianghui** [comment]
已处理，是ios14.x版本的bug，已经通过css禁用手机上input标签以外其他所有标签的长按选择功能。
