### ISSUE TITLE
零代码，对象自定义字段，新增汇总字段，过滤器设置无效

### ISSUE THREAD

**Issue by TroySu** [steedos/steedos-platform#1029]
查数据库发现，汇总字段的过滤器字段名是filters，应该改为summary_filters

**Comment by yinlianghui** [comment]
已处理，规则：
- 字段、运算符、值不能为空
- "number", "currency", "percent"类型，输入的值会转换为数值进行过滤，不能转换为数值时报错
- "boolean"类型，输入'1/true/True/TRUE/真'表示真，或输入'0/false/False/FALSE/假'表示假，其他值均报错
- "date"类型，输入内容转换为按utc的0点时间值来过滤，实测输入2020-02-12,结果按2020-02-12T00:00:00.000Z过滤
- "datetime"类型，输入内容转换为按utc时间值来过滤，实测输入2020-02-12 12:00,结果按2020-02-12T04:00:00.000Z过滤
- 公式和汇总按其data_type类型以上述规则一样处理。
