### ISSUE TITLE
部署模式优化

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#1034]
https://github.com/mingdaocom/private-deployment/wiki/%E5%8D%95%E6%9C%BA%E6%A8%A1%E5%BC%8F%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85

部署模式可以参考明道云，我们现在的步骤太复杂
首先要提供 build 好的 docker 
然后还可以提供阿里云的模版
1.22 发布之后这一整套都要做。

**Comment by hotlong** [comment]
暂时标准的 docker 可以基于 CRM 项目的模版。

**Comment by hotlong** [comment]
明道云只提供了 docker 模式的部署，也是一个方案。开发人员编写代码完全可以通过 codeserver 来完成。这样部署就标准化了，本地也不用安装一大堆。

**Comment by hotlong** [comment]
标准化部署docker，加入 minio。

**Comment by sunhaolin** [comment]
整理一下这个项目 https://github.com/steedos/steedos-project-oa ，通过插件的方式引用标准的 crm 和合同

**Comment by sunhaolin** [comment]
1、docker-compose.yml （mongodb、steedos（image包含codeserver）、nginx、minio、）；第一版（mongodb、steedos）
2、提供虚拟机（vmware）模版文件
3、aliyun模版、腾讯模板
