### ISSUE TITLE
工作流操作：支持通知notifications

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1062]

**Comment by marchtian** [comment]
能否优先处理下？

**Comment by hotlong** [comment]
就是加一种通知类型的自动化操作，通知的标题和正文都可以写公式。

**Comment by sunhaolin** [comment]
- [ ] 工作流操作菜单下，字段更新 同层级增加 发送通知表：workflow_notifications
- [ ] 发送通知表结构设计：
- object_name: 对象，lookup
- title：标题，textarea，内容可写公式，执行公式函数：computeFormula
- body: 正文，textarea，内容可写公式
- name：apiname
- to：分组，包含 指定相关用户数组字段（优先支持）、指定人员数组字段（优先支持）、指定部门数组字段、指定角色数组字段、指定岗位数组字段
