### ISSUE TITLE
项目启动不了

### ISSUE THREAD

**Issue by CharlieLau** [steedos/steedos-platform#1067]
按照DEVELOPING.md 的说明流程
node v12.18.2
yarn  v1.22.4
macos 10.15.6
mongo 4.4.1
整了半个小时项目起不来，说mongo有重复的文档。能梳理下DEVELOPING.md 么？

**Comment by CharlieLau** [comment]
error message:  You are using the default secret "secret" which is not secure.
Please change it with a strong random token.
steedos_logger server.coffee:192 Instances_Statistics -> UserCostTime ➔ error Miss settings: instances_stat.schedule

**Comment by baozhoutao** [comment]
请参考此文档：https://www.steedos.com/help/deploy/deploy_mac

**Comment by CharlieLau** [comment]
折腾起来了 node版本的问题应该是 thx
