### ISSUE TITLE
sf中字段更新操作中支持“字段更改后重新评估工作流规则”开关

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1107]
我们目前是没有的，是否考虑跟进。

**Comment by baozhoutao** [comment]
字段更新添加字段：reevaluateOnChange
设置为true时，如果字段更新更改了字段的值，则将重新评估关联对象上的所有工作流程规则。由于字段值更改而满足其条件的任何工作流程规则都将被触发。
如果任何触发的工作流程规则导致另一个字段更新也启用了工作流程规则重新评估，则将产生多米诺骨牌效应，并且由于新触发的字段更新，可以重新评估更多工作流程规则。在启动工作流规则之后，这种级联的工作流规则重新评估和触发操作最多可以发生五次。

**Comment by baozhoutao** [comment]
需要确认过程中如果出现异常时，sf是如何处理数据的。

**Comment by yinlianghui** [comment]
该任务已处理，关联任务：工作流规则支持触发关联公式字段执行并支持重新评估和触发相关对象的工作流规则 #1272



> 需要确认过程中如果出现异常时，sf是如何处理数据的。

跟sf一样了，如果是跨对象上的字段更新，勾选这个属性直接报类似的错误信息。
![image](https://user-images.githubusercontent.com/6219465/105826506-ca46ce00-5ffb-11eb-8275-0a1f7885d0ec.png)
