### ISSUE TITLE
公式字段如果设置为必填，导致不能新建，始终提示必填

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1114]

**Comment by yinlianghui** [comment]
- 类似：【零代码】公式如何设置了默认值，导致新建异常，比如公式的数据类型为金额， 默认值0.00，始终提醒公式字段必须为数字 #1115
- sf那边对于公式与汇总字段都不让设置为必填。

**Comment by lizhenghotoa** [comment]
目前公式字段必填属性隐藏，数据新建时公式字段隐藏，编辑时字段公式显示，提示”在保存时，计算此字段“
