### ISSUE TITLE
所有公式填写的输入框应该显示为多行输入框

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1126]
- 统一显示为3行
- 除了公式字段外，流程自动化中的验证规则、工作流规则、批准过程等中的公式输入框一样要改。
![image](https://user-images.githubusercontent.com/6219465/99238431-ae24f480-2834-11eb-9443-5bf832216517.png)

**Comment by lizhenghotoa** [comment]
已修正
