### ISSUE TITLE
零代码，前台页面修改列表视图（增加过滤）后保存，设置中，再编辑列表视图，报错

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1128]
![图片已粘贴至2020-11-18 09-04](https://user-images.githubusercontent.com/7553007/99469242-3f06e780-297d-11eb-9e7f-acee90e6b1b2.png)
![图片已粘贴至2020-11-18 09-02](https://user-images.githubusercontent.com/7553007/99469255-44643200-297d-11eb-83bf-fcefc0cdb070.png)

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/994
