### ISSUE TITLE
生成的邀请链接无效

### ISSUE THREAD

**Issue by nuan1989** [steedos/steedos-platform#1150]
http://121.37.193.108:8000/accounts/a/#/signup?invite_token=p9pFvdCsWdHG2sHCa

这是生成的链接. 打开页面是空白的.

**Comment by baozhoutao** [comment]
请检查项目根路径的steedos-config.yml中tenant节点下是否配置了_id 属性，如果配置了_id 且是指向环境变量的，方案1：请在.env.local中给此环境变量赋值，值可以从设置-公司设置-许可证-复制魔方ID（右上角）获取。方案2：删除tenant下的_id属性。
