### ISSUE TITLE
设置表：_settings 结尾

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1163]
1 _settings 结尾的表标识是设置表
2 每个工作区仅能有一条记录
3 打开时直接进入详细页面，而非列表页面
4 yml:  *.settings.yml

使用方式：
1 需要先创建 xxx_settings 对象及字段
2 添加xxx.settings.yml 指定属性值

限制：参考sf
1 *_settings 表权限：
2 odata、graphql 不需要 *_settings 表？

**Comment by hotlong** [comment]
1、_settings 表应该只有管理员才可以修改。
2、odata、graphql 接口开放问题不大
