### ISSUE TITLE
自定义权限集用户无法使用对象中的附件功能 

### ISSUE THREAD

**Issue by Ruizhijian** [steedos/steedos-platform#1175]
我创建了一个对象，添加了几个字段，有日期和相关表。然后添加了一个权限集，授权了一个新建的应用，新建应用里加入了刚才创建的对象。之后在对象里添加了一个刚才创建的权限集。最后在共享规则里创建了一个规则让非记录所有人可以查看。

在对象里的权限中有对应角色，除了查看所有，都开了。但是开了查看所有，也显示不了附件上传的功能

管理员可以上传文件，其他用户显示不出来。再有就是，如果其他用户创建了记录，会闪一个红色叹号在右上角，没有文字。pm2 logs 没有报错

**Comment by baozhoutao** [comment]
新建对象权限时已可以选择“附件”对象。请更新到1.23.20版本
