### ISSUE TITLE
华炎私有云登录界面无法创建账户，Cannot read property 'trim' of null

### ISSUE THREAD

**Issue by pukaijiang** [steedos/steedos-platform#1215]
![image](https://user-images.githubusercontent.com/75662064/102161122-b323a500-3ec1-11eb-879c-89c11344d3bc.png)

可以重现，规则是：在登录页面输入了账户，然后点击创建就报错了。

**Comment by yinlianghui** [comment]
这个问题现在又不能重现了，估计是随机的，是从试用平台点击购买许可证按钮，然后点击私有云登录界面底下的创建账户按钮发现这个问题的。初步判断是可能是网络很慢的时候会偶发这个问题，可以尝试把电脑网络搞慢来重现看看？
