### ISSUE TITLE
在对象权限页面新建权限集会报错，但是在权限集页面新建权限集就没这个问题

### ISSUE THREAD

**Issue by dukong** [steedos/steedos-platform#1224]
版本1.22.1
报错信息为：users must be an array
![图片](https://user-images.githubusercontent.com/11550593/102321117-30c9dc80-3fb8-11eb-861e-5be9d094bf44.png)
![图片](https://user-images.githubusercontent.com/11550593/102321214-4d661480-3fb8-11eb-8fe5-4f01cf7400ac.png)

**Comment by hotlong** [comment]
![image](https://user-images.githubusercontent.com/50353452/102320018-b64c8d00-3fb6-11eb-8bc5-d23f2adce019.png)
