### ISSUE TITLE
新建功能：文档库

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1232]
设计目标：
● 有个总入口，能看到华炎魔方中所有的附件清单，包括：由我所有、最近查看、全部 。
● 附件清单，默认过滤字段包括：对象
● 可以创建文档库，对象记录的附件，可以归档到文档库；文档库中的附件和记录的附件，是同一个文件
● 同一个附件，可以添加到不同的文档库

SalesForce关于文档库的基本逻辑对象包括：
●  文档库ContentWorkspace
●  文件夹ContentFolder
●  文件ContentDocument
●  文件夹的文件项ContentFolderItem

华炎魔方拟类比简化如下实现
●  【新建】文档库cms_workspace
●  【现有】附件cms_files

1、 【对象】文档库content_workspace
【字段】
name	名称
description	描述	多行文本
members	相关表（用户） 多选
【列表视图】
我的：显示owner为本人的文档库
所有：显示members包含本人的文档库（改代码）
最近：最近访问的文档库
【相关子表】
● 查询文档库content_workspace对应cms_files记录
【控制】
● 删除文档库记录时，弹出对话框、告知会移除所有文件、确定后删除
● 仅管理员能创建文档库

2、【对象】附件cms_files
【增加字段】
object_name	对象名	
content_workspaces	 相关表（文档库）多选
【列表视图】
由我所有：显示owner为本人的文件；
最近查看：最近访问的文件
全部：全部能访问的文件

3、【应用】文档库
【桌面主菜单】文档库、附件

**Comment by TroySu** [comment]
1、文档库下，无法查看子表附件的数据，需要改内核代码；
2、附件其他人分配的，通过members字段过滤。
