### ISSUE TITLE
cli中执行steedos i18n en会报错Error: Can't wait without a fiber

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1235]
![image](https://user-images.githubusercontent.com/6219465/102583305-6cdb7980-413f-11eb-9cf7-fed630059cd1.png)

参考文档：https://github.com/steedos/steedos-platform/tree/1.22/packages/cli
跑的项目：https://github.com/steedos/project-management-app
环境：Mac 10.15.7 

文档中的steedos i18n en 及`开发环境运行方式`都试过，前者直接报错，后者报run指令不存在

**Comment by baozhoutao** [comment]
重复任务 https://github.com/steedos/steedos-platform/issues/1239
