### ISSUE TITLE
修改子表记录时，因为不是主表记录的owner，会不让修改

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1249]
![image](https://user-images.githubusercontent.com/7553007/102856988-9871a300-4462-11eb-81ea-a5c17a2c124f.png)

**Comment by marchtian** [comment]
https://github.com/steedos/steedos-platform/issues/1130

**Comment by yinlianghui** [comment]
> #1130

已在#1130提供方案了，设置write_requires_master_read属性即可

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/104532790-0701e500-564c-11eb-8048-2fda8ecd3917.png)
如上配置即可
