### ISSUE TITLE
以项目记录为例，如何限定本项目的成员才能看到这条项目记录？

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1251]
目前的变通方法是，权限设置为 用户能看到所有记录。
项目经理 为 项目记录的owner，所以项目经理的“我的项目”是他自己的这一部分。
项目组成员，只能从“所有项目”中看到 所有的项目。

**Comment by marchtian** [comment]
能否优先处理下？

**Comment by hotlong** [comment]
这个要等共享规则优化，需要研究salesforce的数据共享体系。

**Comment by hotlong** [comment]
这个最快排到1.24
