### ISSUE TITLE
creator meteor内核升级到1.9

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#1256]
- 主要目的升级node版本从8-》12

**Comment by baozhoutao** [comment]
tmeasday:check-npm-versions: updating npm dependencies -- semver...
steedos:oauth2-server: updating npm dependencies -- cookies, express, body-parser, oauth2-server, unpipe...
/Users/sunhaolin/.meteor/packages/meteor-tool/.1.9.3.1l11cm9.1kwr++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/fibers.js:90
                                        return fn.apply(this, arguments);
                                                  ^

SyntaxError: Unexpected token u in JSON at position 1

此问题是由于creator 的node modules 中有 steedos-server 导致 meteor 的 watcher file 异常。临时解决方案为 手动删除 steedos-server。解决方案为：修改steedos-app-crm 中 node package 的依赖项

**Comment by baozhoutao** [comment]
meteor 版本升级到了1.9.3

**Comment by baozhoutao** [comment]
已测试确认：
1 手机APP 热更新正常
2 手机APP 显示正常
3 由于升级了@steedos/react 的immer , @steedos/react 正常。
