### ISSUE TITLE
权限集，自定义按钮，点击后会丢失对象权限？

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1264]
例如，project-management-app 的代码里已有“项目管理员”这个权限集，需要拉人进权限集
![image](https://user-images.githubusercontent.com/7553007/103114939-aa8a5600-469b-11eb-8d6f-d360ec0aeed5.png)
这这时需要点击“自定义”
点击后，对象权限就不显示了
![image](https://user-images.githubusercontent.com/7553007/103114992-e02f3f00-469b-11eb-9449-7f7c9bf07a74.png)
到具体对象里查对象权限，如图
![image](https://user-images.githubusercontent.com/7553007/103115105-4c11a780-469c-11eb-8e46-68eb4bd5afc3.png)
项目管理员的像是还在、又多出条 none的记录
点击“project_manager”,显示 对象权限都在
![image](https://user-images.githubusercontent.com/7553007/103115187-96932400-469c-11eb-9e35-52a45354fc03.png)
点击 “none”，报错
![image](https://user-images.githubusercontent.com/7553007/103115215-af9bd500-469c-11eb-8e97-d52e208f4b89.png)

**Comment by baozhoutao** [comment]
自定义的权限集看不到对象权限的问题出在 非默认内置的4个简档时
