### ISSUE TITLE
工作流操作-字段更新触发公式、trigger的执行

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1270]
此改动存在 死循环风险，如果服务死循环，需要先修改数据库相关脚本，并重启服务。

**Comment by sunhaolin** [comment]
91e865264a570498bd9f0de87839c35f1e15f657

**Comment by sunhaolin** [comment]
f2721df4e3a94020088da561e2ff4d563fa99a76  revert

**Comment by baozhoutao** [comment]
此改动不可行
