### ISSUE TITLE
工作流规则支持触发关联公式字段执行并支持重新评估和触发相关对象的工作流规则

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1272]
- [x] 字段更新执行后，也要执行对象公式和汇总相关计算。
- [x] 当前对象的工作流规则触发后，需要触发相关对象的工作流规则（最多5层）

**Comment by yinlianghui** [comment]
功能【字段更新执行后，也要执行对象公式和汇总相关计算。】测试要点：
- [ ] 配置一个工作流规则及字段更新，同时配置一个公式字段引用该字段更新更新的字段（公式字段一定要配置在工作流规则关联对象以外的其他对象上，因为编辑记录本身就会触发该记录上的公式重算），测试字段更新后是否会触发公式重新计算。
- [ ] 配置一个工作流规则及字段更新，同时配置一个汇总字段，该字段更新更新的字段正好要是汇总字段的子表上的字段，测试字段更新后是否会触发汇总字段重新计算。

功能【当前对象的工作流规则触发后，需要触发相关对象的工作流规则（最多5层）】测试要点：
- [ ] 在同一个对象上配置两个工作流规则及字段更新，字段更新更新的都是本对象上的字段且它们相互更新对方，同时勾选两个字段更新上的“字段更改后重新评估工作流规则”选项，测试是否正常并且不会死循环。
- [ ] 在同一个对象上配置两个工作流规则及字段更新，其中一个字段更新A执行后正好满足另一个工作流规则M，测试勾选与不勾选字段更新A上的“字段更改后重新评估工作流规则”选项的区别，正确的结果是勾选上的话，界面上一次编辑就能同时触发两个流程规则执行其字段更新操作，反之就只会触发一个。
- [ ] 配置三个对象A、B、C，它们之间为父-子-孙关系，并配置相关工作流规则和字段更新，测试C上的字段更新无论其“字段更改后重新评估工作流规则”选项是否勾选都否级联触发B和C上的所有工作流规则重新评估。
- [ ] 配置三个对象A、B、C，它们之间为父-子-孙关系，并配置相关工作流规则和字段更新，测试跨对象级联字段更新时，工作流规则上三种“评估条件”是不是在级联触发时这三种“评估条件”的意思永远没变，比如C对象上的工作流规则评估条件“新建时，或编辑数据导致条件成立”与级联触发的B对象上的工作流规则评估条件“新建时，或编辑数据导致条件成立”是一样的规则（即编辑时如果字段值原来满足评估条件，保存后也满足评估条件是不会触发字段重新操作重新执行的，只有编辑前不满足条件，保存后才满足条件的情况才会触发执行字段更新操作）。【这点是重点要测试的，因为我没有把三种评估条件选项都测试完，特别是第三种选项】

**Comment by marchtian** [comment]
功能【字段更新执行后，也要执行对象公式和汇总相关计算。】测试：

- [x]  配置一个工作流规则及字段更新，同时配置一个公式字段引用该字段更新更新的字段（公式字段一定要配置在工作流规则关联对象以外的其他对象上，因为编辑记录本身就会触发该记录上的公式重算），测试字段更新后是否会触发公式重新计算。

- [x]  配置一个工作流规则及字段更新，同时配置一个汇总字段，该字段更新更新的字段正好要是汇总字段的子表上的字段，测试字段更新后是否会触发汇总字段重新计算。

**Comment by marchtian** [comment]
第3种评估条件选项“新建时，或编辑数据导致条件成立”有问题。 https://github.com/steedos/steedos-platform/issues/1348

**Comment by marchtian** [comment]
功能【当前对象的工作流规则触发后，需要触发相关对象的工作流规则】测试：
（1）配置三个对象A、B、C，它们之间为父-子-孙关系，三个对象上各有1条工作流规则，并且C->B、B->A都有级联字段更新链条连着，测试C上的字段更新是否会级联触发B和C上的所有工作流规则重新评估。： 可以级联触发
