### ISSUE TITLE
零代码，选“主表/子表“字段类型时”引用对象“属性应该必填

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1274]
![image](https://user-images.githubusercontent.com/6219465/103248662-95b50780-49a6-11eb-8dfa-e21010d56730.png)

**Comment by baozhoutao** [comment]
master_detail的引用对象为必填， 选择项函数隐藏

**Comment by yinlianghui** [comment]
不处理，因为”引用对象“属性可能不是必须的，可以通过定义function来表示对应的引用对象，该问题应该改公式优化错误提示信息：在公式中引用“相关表”和“主表/子表“类型字段”时，如果其引用对象“属性未填写或为function时应该优化下错误提示 #1276
