### ISSUE TITLE
验证规则，疑似不支持字段引用，形如key_result__c.last_updated_date__c

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1277]
形如key_result__c.last_updated_date__c，新建记录时 会报公式错
![image](https://user-images.githubusercontent.com/7553007/103262351-afbf0c00-49df-11eb-8618-62a1c6fa0cdd.png)
同样的公式，如果配为本对象的某字段的公式，则能得到正确的 true/false

**Comment by marchtian** [comment]
工作流规则的规则条件，可能也有此问题

**Comment by yinlianghui** [comment]
经讨论已无法重现
