### ISSUE TITLE
批准过程无法使用跨对象字段更新

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1298]
sf原话：[Approval processes can't use cross-object field update actions.](https://help.salesforce.com/articleView?id=workflow_field_update_considerations.htm&type=5)

需要确认下我们目前是不是可以在批准过程中引用跨对象字段更新，另外测试下sf那边是什么规则，然后再讨论是否跟进。

**Comment by yinlianghui** [comment]
请 @TroySu 帮测试确认下这块规则

**Comment by marchtian** [comment]
（1）华炎魔方的批准过程，可以引用跨对象字段更新
（2）sf 的批准过程，不可以引用跨对象字段更新，选字段更新时，仅可选更新本对象的
