### ISSUE TITLE
批准过程中的字段更新是否应该触发工作流规则重新评估、公式及累计汇总呢？

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1299]
Field updates that are executed as approval actions don’t trigger workflow rules or entitlement processes.

An approval process can specify a field update action that reevaluates workflow rules for the updated object. If, however, the re-evaluated workflow rules include a cross-object field update, those cross-object field updates are ignored.

上面两句文档出处：[Considerations for Field Update Actions](https://help.salesforce.com/articleView?id=workflow_field_update_considerations.htm&type=5)

意思好像正好相反，需要上sf测试确认下。

**Comment by marchtian** [comment]
上述英文的对应的sf中文如下：
导致字段值更改的跨对象字段更新，不会触发相关对象上的工作流规则重新评估。
批准过程可以指定重新评估更新对象的工作流规则的字段更新操作。但是，如果重新评估工作流规则包含一个跨对象字段更新，则忽略其他跨对象字段更新。

**Comment by marchtian** [comment]
SF的测试结果：
（1）批准过程，设置时选不到跨对象的字段更新。
（2）批准过程，执行本对象的字段更新后。只要此字段更新勾选了“重新评估”，则会重新评估工作流规则。执行工作流规则下的操作时，跨对象的字段更新会被忽略、其他字段更新会执行。
