### ISSUE TITLE
字段更新记录详细界面“指定新字段值”显示格式化

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1304]
目前这个字段是字段的text类型，如果要更新的是boolean,datatime等类型应该格式化显示出来。

可以考虑写个beforeView脚本来处理该问题。

![image](https://user-images.githubusercontent.com/6219465/103867999-39b75500-5103-11eb-8d16-9a02148151c7.png)

**Comment by hotlong** [comment]
不处理
