### ISSUE TITLE
开放数据导入menu菜单，并整理文档

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1306]

**Comment by sunhaolin** [comment]
好像是 （1）加条记录，配上映射关系，即excel 从左到右每一列 对应的字段 （2）加个附件 ，即excel（3）执行导入

**Comment by sunhaolin** [comment]
表：queue_import

**Comment by sunhaolin** [comment]
lookup类型，在excel里是对应的name 值 ，即可导入。无需 转换 为 对应的 id
