### ISSUE TITLE
[Feature] 新建简档时，应从现有简档复制

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1314]
例如，自助注册（为自建简档）后，设置里，
![image](https://user-images.githubusercontent.com/7553007/104145040-8bf8be80-5400-11eb-92a6-5fec2ae5c165.png)

**Comment by marchtian** [comment]
https://github.com/steedos/steedos-platform/issues/1316

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/104145947-ea736c00-5403-11eb-8a18-3dea213181c4.png)
以上是 简档user对应的内置对象的权限，应要逐一测试

**Comment by hotlong** [comment]
利用简档复制功能实现

**Comment by hotlong** [comment]
![image](https://user-images.githubusercontent.com/50353452/170403870-9fbf368e-32dc-43e1-8670-4bd6afd181da.png)

**Comment by sunhaolin** [comment]
- 通过复制现有的权限集创建新权限集
- 除了权限集记录外，把权限集绑定的对象权限、字段权限、共享规则、限制规则全部一起复制

**Comment by sunhaolin** [comment]
- [ ] 在事务中处理，保证数据一致性

**Comment by sunhaolin** [comment]
- [ ] 调整 15.permission_objects.observe.object.js 通过复制简档创建的权限对象，不需要重置字段权限
- [ ] 调整 13.permission_fields.observe.object.js 通过复制简档创建的字段权限，使用objectql.registerPermissionFields.mregister批量注册到redis
