### ISSUE TITLE
非chrome浏览器，普通用户个人设置里，修改语言、保存后，页面显示异常

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1317]
http://。。。:5000/app/admin/space_users/view/6gWzeCJd6xq8rLHWT?ref=users

![image](https://user-images.githubusercontent.com/7553007/104148250-7e493600-540c-11eb-88c4-a3772b18d52d.png)

**Comment by yinlianghui** [comment]
是在360浏览器极速模式发现的问题，按【测试确认浏览器兼容情况，不兼容的浏览器应该直接跳转到不支持该浏览器提醒界面 #1334】来处理。
