### ISSUE TITLE
npm 编译问题

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#1340]
node 12.x 需要重新编译 node-expat，弹出各种错误。
查看 yarn.lock， 
- node-expat 被 xml2json 引用
- xml2json 被 @steedos/plugin-qywx 引用

删除 @steedos/plugin-qywx ，则 yarn 安装恢复正常

**Comment by hotlong** [comment]
https://github.com/buglabs/node-xml2json 这个项目官方已经不维护了。

**Comment by chenzhipei** [comment]
@steedos/plugin-qywx已移除xml2json，并重新发包
