### ISSUE TITLE
字段更新，要更新的对象里显示的不是 父对象名

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1346]
![image](https://user-images.githubusercontent.com/7553007/104863804-147fdd80-5972-11eb-85e6-10a0ce82b36f.png)
如上图，显示的是“B的记录”，这是“测试-C”的字段名，而不是 这个主表/子表字段对应的对象名“测试-B” 。

@ "steedos-server": "^1.23.0-alpha.18"

**Comment by yinlianghui** [comment]
已处理，还是保持原来一样选项保存为字段名，但是选项label显示为关联到的对象名
