### ISSUE TITLE
子表有时不能正常加载数据，控制台报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1387]
![chrome_rzdzct8edz](https://user-images.githubusercontent.com/6194462/105008105-c5ba6c80-5a73-11eb-8348-4e8caf7baa32.png)
![chrome_JxR5Y8dwEh](https://user-images.githubusercontent.com/6194462/105008118-c7843000-5a73-11eb-9ba4-24f0d5f1eb0a.png)

**Comment by yinlianghui** [comment]
已处理，打开某个对象的详细界面，然后管理员变更这个界面下某个子表对象的信息（比如变更字段排序号）后就能重现这个问题，修正后，可以看到当管理员把界面上对象的某个“主表-子表”关系移除或添加新的子表关系时能正常显示结果。
