### ISSUE TITLE
新加的两种默认简档未翻译为中文显示

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1398]
代码中的简档、权限集 的label 如何国际化, 此问题属于record国际化。

<img width="435" alt="image" src="https://user-images.githubusercontent.com/6219465/105272910-40e76400-5bd5-11eb-83ca-a3fe0b67c71f.png">

**Comment by yinlianghui** [comment]
翻译为供应商和客户

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/1399

**Comment by baozhoutao** [comment]
此问题不是没有国际化，是国际化未能生效。
