### ISSUE TITLE
通过GraphQL API新增数据的时候，需要加上space参数，否则显示插入成功，但实际并未插入成功

### ISSUE THREAD

**Issue by ylpmikasa** [steedos/steedos-platform#1440]
https://www.steedos.com/developer/api/graphql_add

**Comment by baozhoutao** [comment]
如果没有指定space,则insert的记录在数据库中的space是错误的

**Comment by yinlianghui** [comment]
那边部分测试结果：
- 修改和删除数据也都可以不带space，能成功执行
- 可以直接修改变更一条记录的space值

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/1186
