### ISSUE TITLE
项目下定义的 customize.css 不生效

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#1463]
可能是优先加载了某个插件中对应的文件。

**Comment by yinlianghui** [comment]
关联任务：/creator 中 customize.css 中的内容是必须的样式，不应该被项目覆盖。 #1464

#1464未解决，需要在#1463中让项目中的customize.css文件生效且不会覆盖creator的public下定义的customize.css文件（比如可以累加内容，让它们都生效）
