### ISSUE TITLE
/creator 中 customize.css 中的内容是必须的样式，不应该被项目覆盖。

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#1464]

**Comment by yinlianghui** [comment]
未解决，因为把creator中的customize.css文件迁移到内核后，会被外面引用的assets样式文件覆盖。
暂时先把项目中customize.css文件移除（需要清除浏览器缓存才能看到效果），修改了以下两个项目：
- apps/steedos-app-project
- apps/steedos-project-template

**Comment by yinlianghui** [comment]
不处理，在#1463解决该问题，即目前项目中还是不允许定义customize.css文件！
