### ISSUE TITLE
GraphQL 改造

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#1496]
查询记录

```graphql
query (
  contracts (filters, top, user) {
     _id
     name
     select
     account // 相关表类型，返回ID
     account__expand // 相关表类型，返回对象 
     ...
     _display { //如果值为空，均返回空字符串
       _id
       name
       select // select 类型，返回Label
       account // lookup 类型，返回Name
       date // 返回格式化的日期
       boolean // 如果是，返回一个勾，返回空。
       ...
    }
    _related_tasks // 返回相关任务
    _related_files // 返回相关文件
    _related_approvals // 返回相关审批历史
    _related_payments_contract // 返回子表数据，子表名称_子表中相关字段名
  }
)
```
## {field_name}
查询字段值

## {field_name}__expanded
对于相关表（lookup & master-detail）数据，expand下一级字段值

## _related_objectname_fieldname

查询子表数据。如果子表中有lookup, master detail字段指向当前表，则可以查询子表中对应的列表数据。

考虑到子表中可能有多个lookup字段指向主表，因此查询时需要带上字段名: ${object_name}__${field_name} 。查询语法与普通对象相同，只是自动加上子表过滤条件。

## _display.{field_name}

返回字段的显示值。

**Comment by sunhaolin** [comment]
- [ ] 旧的graphql接口改为 /graphql/v1
