### ISSUE TITLE
error: "_.findIndex is not a function" state: "FAILURE"

### ISSUE THREAD

**Issue by daiweishu** [steedos/steedos-platform#1526]
https://salesforce.trial.steedos.com:8443/api/v4/process/approve/process_instance_history/wcDedNmihTfLJLrok

**Comment by baozhoutao** [comment]
此任务和1527没关系

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-app-crm/commit/dc7977b6156e0df5f0ad6bafb86f5ad7bcde3078
