### ISSUE TITLE
Why not use the reactiveVar of the meteor?

### ISSUE THREAD

**Issue by snowyu** [steedos/steedos-platform#1577]
It's a cool feature in the meteor. So why not use it?

**Comment by snowyu** [comment]
The fields value cannot be updated automatically even with workflow notifications.

**Comment by hotlong** [comment]
meter is not good for big project, we are moving our server to pure node project. and client code to pure react project.

**Comment by snowyu** [comment]
Indeed, the reactive var would consume a large amount of server resources. But it's good at some realtime situations. Maybe this decision can be left to the user: let the user select certain fields individually to become responsive.

It's Great to sperate client from server. I'm reading your source recently on my free time.

@hotlong  留意到你们在提issue用的是中文,但是又看到你们似乎正在做international努力,那么后续建议和问题,我是该用E还是中文好些?
BTW, 我本人是中国人.

**Comment by hotlong** [comment]
都可
