### ISSUE TITLE
批准过程审批界面，提交人显示错误，目前显示的是上一步处理人

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#1616]

**Comment by yinlianghui** [comment]
- 这个问题我直接显示为process_instance的`created_by`字段值关联的用户名了。
- 另外“批准过程，在最终批准和最终拒绝时，发起人没有收到通知 #1654”这个任务也用到了发起人，使用的也是process_instance的`created_by`字段。
