### ISSUE TITLE
通过批准过程的字段更新，不能触发相应的累计汇总字段重新计算

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#1647]
关联任务：
- 批准过程中的字段更新是否应该触发工作流规则重新评估、公式及累计汇总呢？ #1299
- 工作流规则支持触发关联公式字段执行并支持重新评估和触发相关对象的工作流规则 #1272

**Comment by yinlianghui** [comment]
是因为原来没支持汇总字段过滤条件中的字段值变更时也触发汇总字段重新计算，已处理

**Comment by yinlianghui** [comment]
已同步在2.0分支修改了该部分代码
