### ISSUE TITLE
公司设置-登录页-logo和背景图未生效

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#1725]

**Comment by hotlong** [comment]
需要配置 steedos-config https://www.steedos.com/help/deploy/steedos-config#%E7%99%BB%E5%BD%95%E8%A7%84%E5%88%99

**Comment by JAVPHP** [comment]
请问这个问题如何解决，谢谢

> 需要配置 steedos-config https://www.steedos.com/help/deploy/steedos-config#%E7%99%BB%E5%BD%95%E8%A7%84%E5%88%99

您给的链接打不开呀，请问这个问题如何解决，谢谢

**Comment by yinlianghui** [comment]
> 

登录页面logo如何进行修改 #2501
