### ISSUE TITLE
objectql update语句报错： cannot read property ‘owner’ of null

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#1759]
报错文件：@steedos/standard-objects 下 base.masterDetail.trigger.js
报错代码段
```js
    afterUpdate:async function () {
         /* Master-Detail 规则确认 #189 */
         const { object_name, id, previousDoc} = this;
         const dbDoc = await objectql.getObject(object_name).findOne(id);
         let docOwner = dbDoc.owner;

```

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/1764

**Comment by lizhenghotoa** [comment]
对象详情页编辑数据报错，控制台报500错误；编辑器终端报TypeError: Cannot read property 'owner' of null
    at Object.afterUpdate (/Users/huayan/Documents/GitHub/steedos-project-pcmes/node_modules/@steedos/standard-objects/base.masterDetail.trigger.js:81:39)错误
![image](https://user-images.githubusercontent.com/26241897/122712469-8ef0b880-d296-11eb-8f3a-f0a8530c0a89.png)
