### ISSUE TITLE
执行FlowRouter.Reload() 页面数据未刷新

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#1766]

**Comment by baozhoutao** [comment]
详细页面的记录有 60秒缓存

**Comment by sunhaolin** [comment]
场景： 
详细页面；
自定义按钮调用修改数据接口后执行 FlowRouter.Reload()

**Comment by yinlianghui** [comment]
已处理，脚本中额外调用以下脚本即可：
`SteedosUI.reloadRecord("quote", "60bdd8a46765c41fcdc238bb")`

实际上本次修改未打包前，可以先用以下脚本代替，效果是一样的，上述函数就有执行的下面的代码：
`window.stores.Objects.getObject("quote").getRecord("60bdd8a46765c41fcdc238bb").loadRecord()`
