### ISSUE TITLE
管理员需要替别人创建流程委托，现在委托人姓名没法更改

### ISSUE THREAD

**Issue by TroySu** [steedos/steedos-platform#1772]
![image](https://user-images.githubusercontent.com/20942182/122857102-8bb70480-d34a-11eb-8a76-fecd5e3b04ac.png)

**Comment by TroySu** [comment]
反馈，之前是可以普通用户自己设置流程委托，管理员可以帮其他人设置流程委托（通过修改委托人姓名）

**Comment by chenzhipei** [comment]
和尹科长沟通过，保留原来的逻辑，普通用户可以自己设置流程委托

**Comment by lizhenghotoa** [comment]
普通用户可以自己设置流程委托，管理员暂时无法设置委托
