### ISSUE TITLE
windows上新建2.0项目，The 'redlock' package is missing. If you want to enable cache lock, please install it with 'npm install redlock --save' command.

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#1778]
![image](https://user-images.githubusercontent.com/7553007/123192487-9b168900-d4d5-11eb-8743-69917e2e38ed.png)

**Comment by hotlong** [comment]
mongodb 是什么版本

**Comment by marchtian** [comment]
有个 WARN  steedos-project-template/CACHER: The 'redlock' package is missing. If you want to enable cache lock, please install it with 'npm install redlock --save' command.
