### ISSUE TITLE
什么情况下调这个界面？

### ISSUE THREAD

**Issue by 20907437** [steedos/steedos-platform#1816]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/66851599/124347178-c4da5900-dc15-11eb-8d38-260b76ad974c.png">

**Comment by baozhoutao** [comment]
第一次登录或者清理过浏览器缓存时会进入这个选择页面。
可以通过修改配置文件steedos-config.yml，来指定工作区tenant._id。
https://www.steedos.com/developer/steedos_config#%E7%99%BB%E5%BD%95%E7%95%8C%E9%9D%A2%E9%85%8D%E7%BD%AE

**修改后需要重启服务**
