### ISSUE TITLE
[] 的遍历受到污染

### ISSUE THREAD

**Issue by endlesstravel** [steedos/steedos-platform#1873]
当在 steedos-platform 启动的项目下运行如下代码，将会发现 [] 的 key 不为空。
```js
for (let key in []) console.log(key);
```
前端：
![image](https://user-images.githubusercontent.com/10757838/125433652-0d44abe5-11f4-4504-b0ad-b6e8f5172540.png)
后台：
![image](https://user-images.githubusercontent.com/10757838/125433710-bb264586-9883-4c59-8049-9c8d4633d483.png)

这将可能导致外部包工作异常：比如 https://github.com/godaddy/kubernetes-client
详见issue ： https://github.com/kubernetes-client/javascript/issues/643
在没有隐藏掉这些key之前， kubernetes-client 无法正常工作。
k8s工程在1.xx 版本我可以在 项目 启动后使这些key隐藏，使其不可遍历：
![image](https://user-images.githubusercontent.com/10757838/125434174-e333dbc8-c55a-4d25-8581-bc2b4b1c0962.png)
![image](https://user-images.githubusercontent.com/10757838/125434209-a0394c97-6e0e-4978-bd7d-4b338d6f9f7f.png)

在迁移到2.00版本时，同样遇到这个问题，故记录下来。

推测bug文件在：
`creator\packages\steedos-base\lib\steedos_util.js`
`server\bundle\programs\server\packages\steedos_base.js`
![image](https://user-images.githubusercontent.com/10757838/125434532-38a9abdd-0836-4888-a1a6-b6f4ca210749.png)

**Comment by hotlong** [comment]
应该删除 Array.prototype 下的所有自定函数

**Comment by hotlong** [comment]
重新写个类，原来引用这些函数的地方都迁移过去
