### ISSUE TITLE
对象字段类型支持时间（增加时间类型字段，不带日期前缀）

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1907]
参考 sf看看那边有没有这个类型，目前我们内置有一个“工作时间”对象，里面的时间字段用的是text类型，目前没有专门的时间类型字段

https://procomponents.ant.design/components/field
https://ant.design/components/time-picker/

**Comment by yinlianghui** [comment]
sf有时间类型：
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/6219465/163390506-178281d7-1bde-4038-ac5a-3a393278d706.png">

**Comment by hotlong** [comment]
我们肯定是选择

**Comment by hotlong** [comment]
保存到数据库时，自动加上 '1970-01-01' 前缀，以日期时间格式保存在数据库中。
例如 
moment('1970-01-01 13:30:56')

**Comment by yinlianghui** [comment]
已处理，规则如下：
- 数据库中保存的是datetime类型值，值的日期部分固定为`1970-01-01`
- 值存的是utc时间，要求给控件传入值时必须也是utc时间，包括默认值
- 数据导入时间必须把数据库中的时候存为1970年1月1号的日期时间值，且时间部分取的是utc时间
- 字段的默认值可以是一个moment或date但是必须是utc时间，也可以是格式为`HH:mm:ss`的字符串。

目前剩余问题：
- 时间类型默认值不生效 #3050
- 时间类型支持数据导入导出功能 #3051
