### ISSUE TITLE
@steedos包依赖指定固定版本

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#1913]
- 例如：由"^2.0.42"调整为"2.0.42"

**Comment by sunhaolin** [comment]
- yarn ver的时候 找出所有的版本依赖项 修改

**Comment by baozhoutao** [comment]
先临时改动下yarn ver命令，加上 skip-git。否则会自动提交的：`lerna version --skip-git --force-publish`

**Comment by baozhoutao** [comment]
需要修改命令： ver 添加参数： `--exact` 。`lerna version --force-publish`
