### ISSUE TITLE
新建字段时，如果选择了多行文本， 未显示 多行文本行数的默认值

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1918]

**Comment by yinlianghui** [comment]
- 配置`defaultValue: "{{formData.type === 'textarea' ? 3 : 0}}"`就行了，`defaultValue: "{{formData.type === 'textarea' ? 3 : undefined}}"`不行，因为服务端会判断这个字段的类型，报错rows must be a Number
- 1.23未配置默认值
