### ISSUE TITLE
顶部导航栏支持tabs功能

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#1923]
- 对象和tabs二取一就行，整个导航栏要显示哪些tabs直接从新接口中获取，该接口会自动计算当前要返回哪些objects或tabs导航菜单
- 新接口代码在这里：services/service-metadata-apps/src/actionsHandler.ts
- tabs表原来有一个字段新加一个字段mobile表示在手机上显示，另外加一个字段desktop表示在桌面端显示，要修改上面的接口

**Comment by hotlong** [comment]
另外加一个字段desktop表示在桌面端显示
