### ISSUE TITLE
企业微信工作流消息通知链接打不开

### ISSUE THREAD

**Issue by wangyingcheng** [steedos/steedos-platform#1932]
企业微信对接后，公告和审批在企业微信通知能打开系统，工作流通知打开提示链接服务器地址错误，服务器连接127.0.0.1:3000
![企业微信截图_20210803143709](https://user-images.githubusercontent.com/87563180/127969326-778ae1f9-576b-4521-9ee6-c44338a0a4ee.png)
![企业微信截图_20210803143354](https://user-images.githubusercontent.com/87563180/127969328-210a4105-5c5f-44d4-9302-7f8bcfa84ca0.png)

**Comment by lizhenghotoa** [comment]
设置环境变量中的ROOT_URL为外边访问的地址
