### ISSUE TITLE
bug: 设置中  对象 过滤条件为中文时无返回结果

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#1934]
1、过滤条件： **中文** 异常：
![image](https://user-images.githubusercontent.com/41402189/127988679-d75cc964-cf04-4d02-9b44-6da5e295a434.png)
---
2、过滤条件： **字母** 正常：

![image](https://user-images.githubusercontent.com/41402189/127989190-790293e7-2457-4c8c-974b-65cfa354dc6d.png)

**Comment by Flyingliao** [comment]
和包老师确认了： 原数据不支持中文过滤，  新建的对象支持。此issue可以关闭了。

**Comment by baozhoutao** [comment]
通过代码定义的元数据目前是不支持搜索的。和中文没关系
