### ISSUE TITLE
bug: tabs对象改为2.0表单，任意一个输入框内输入  global  会导致含有visible_on的字段全部显示出来

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#1947]
![image](https://user-images.githubusercontent.com/41402189/128158617-96b9eae5-844f-480d-a9f9-c58b10b78d9f.png)

**Comment by yinlianghui** [comment]
已处理，是表单公式表达式formData中有global字眼时会替换错了。
