### ISSUE TITLE
华炎手机APP登录后一片空白

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2009]

**Comment by baozhoutao** [comment]
此问题是由于部分React代码在运行时，document.body 为null导致
相关文件：
1 @steedos\builder-page\src\services\url.ts: `document.body.appendChild(link);`
2 @steedos\builder-page\src\lib\calculateTextWidth.ts: `document.body.appendChild(canvas);`
3 @ant-design\pro-form\es\layouts\QueryFilter\index.js: `var defaultWidth = isBrowser() ? document.body.clientWidth : 1024;`

**Comment by baozhoutao** [comment]
手机app上 document.body 为null的原因是由于meteor 内核包boilerplate-generator，在处理script标签时
浏览器上会将script 放到body中. 所以浏览器是正常的
手机app会将script 放到head中. 所以js文件加载时document.body 会为 null

**Comment by baozhoutao** [comment]
解决方案：
1 builder-page中document.body.appendChild优化，将其放到函数中
2 ant-design query filter 由于无法修改代码，在builder-community的index中添加代码段，零时添加document.body 渲染完成后remove.
```
if(!document.body){
    var tempBody = document.createElement("body");
    document.body = tempBody;
    document.addEventListener('DOMContentLoaded', (event) => {
        tempBody.remove()
    });
}
```
