### ISSUE TITLE
2.1.2自建对象编辑视图报错

### ISSUE THREAD

**Issue by wangyingcheng** [steedos/steedos-platform#2020]
![image](https://user-images.githubusercontent.com/87563180/130539645-14cd1ce4-8437-4621-8415-3f1e8dcb2441.png)

**Comment by lizhenghotoa** [comment]
列表视图对象升级到2.0版本后，统一测试确认

**Comment by lizhenghotoa** [comment]
2.1.3版本此问题已修复
