### ISSUE TITLE
项目增加甘特图功能

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2026]

**Comment by hotlong** [comment]
甘特图控件 
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Gantt/Overview/jQuery/Light/

**Comment by hotlong** [comment]
https://github.com/neuronetio/gantt-schedule-timeline-calendar

**Comment by hotlong** [comment]
https://dhtmlx.com/docs/products/dhtmlxGantt/
