### ISSUE TITLE
2.0.61版本新建的应用，菜单显示不出来

### ISSUE THREAD

**Issue by cheany8** [steedos/steedos-platform#2029]
2.0.61版本新建的应用，应用菜单显示不出来

**Comment by lizhenghotoa** [comment]
内部确认新建应用正常，请确认新建应用时是否配置选项卡或主菜单；配置完成后刷新浏览器即可看到相应的新增的应用。
![image](https://user-images.githubusercontent.com/26241897/130722427-a9b42edb-37d5-4ba2-ad4d-51aa1dd3f360.png)
