### ISSUE TITLE
零代码/低代码列表视图字段换行（wrap）功能失效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2045]
同时低代码中width字段也是无效的；规则按照官网文档如下：
- width: 字段宽度，不填写为自动宽度。
- wrap: 显示此字段时是否自动换行，默认为不换行，超出部分显示为... 。

**Comment by yinlianghui** [comment]
width功能失效问题已处理，相关规则为：
- 未配置宽度时，自动适应宽度
- 如果配置了宽度，则以配置的宽度为准，且最小宽度等于配置的宽度（即用户无法拖动来变更宽度为小于最小宽度的值）
- 如果配置了is_wide，则视配置的宽度默认值为300，该配置值适用上面提到的规则，也适用【用户无法拖动来变更宽度为小于300的值】规则。
