### ISSUE TITLE
对象数据导入功能梳理

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2052]
- 确认目前对象导入逻辑
- 确认目前错误数据处理方式
- 考虑功能改进重点，一起讨论
- 导入数据中有关联表的字段，导入失败，报fail at 0

**Comment by huangyiirene** [comment]
导入数据中有关联表的字段，导入失败，报fail at 0

**Comment by lizhenghotoa** [comment]
目前导入情况如下：

- lookup类型字段导入需要设置关联的key，根据excel中的值对应对象的key进行匹配；
- 选择框类型字段目前需要在excel中维护value值，正常对于用户操作应该只需要维护label值即可；
- 关联失败时保存key功能觉得是找不到lookup对象值时会创建一条记录，目前测试下来不会自动创建记录，还需要确认该功能；
- 测试导入功能大体正常，可以正常进行数据导入。

建议优化如下：

- 数据执行导入后，页面自动刷新；目前只能手动刷新页面查看导入情况；
- 设置完导入字段映射后，自动生成导入模版，用户下载填写导入数据即可；
- 目前导入错误信息显示在一个文本框字段中，难免混乱，可以考虑优化显示错误信息；
![image](https://user-images.githubusercontent.com/26241897/131291593-47c8087d-7e53-4f87-ab0c-ccc628bbfd89.png)
