### ISSUE TITLE
人员信息界面简档字段显示异常

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2062]
![image](https://user-images.githubusercontent.com/26241897/131280290-9cb6b776-c82e-4c26-8bc9-a65c94486a65.png)

**Comment by lizhenghotoa** [comment]
解决方案参考：space_users对象如果放开version:2.0走新表单，记录详细界面只读时简档字段会显示所有记录的label，而不是显示字段值对应的label https://github.com/steedos/app-builder/issues/163

**Comment by Flyingliao** [comment]
再次记录下排查结果：**接口返回的数据错误**。
![image](https://user-images.githubusercontent.com/41402189/133037390-96bfa2d2-a792-47d4-81f5-cb8c3cda881d.png)
![image](https://user-images.githubusercontent.com/41402189/133037478-2ddc356a-00cd-4cd7-bcee-44c6568ca2de.png)
