### ISSUE TITLE
设置企业微信事件订阅  不成功 steedos-project-community:2.1.2

### ISSUE THREAD

**Issue by fanbin8592** [steedos/steedos-platform#2086]
按照官方技术文档，设置后不成功。

设置企业微信事件订阅#
请在企业微信后台，选择管理工具，点击“通讯录同步” 开启API接口同步进行相关配置。

同步方式：API接口

权限：API编辑通讯录

Secret: 查看或者重新获取，需要配置到华炎魔方系统-设置-公司设置-企业微信-Secret

设置接收事件服务器：Token和EncodingAESKey随机获取后，需要配置到华炎魔方系统-设置-公司设置-企业微信中；URL设置前请先确保已经将Token和EncodingAESKey配置到华炎魔方系统中，然后再配置华炎魔方服务的域名地址加上api/qiyeweixin/listen后缀，比如https://www.test-qiyeweixin.com/api/qiyeweixin/listen，一定要配置公网域名访问地址。
![image](https://user-images.githubusercontent.com/52906215/131787371-024d48a4-e5a6-4e2f-974a-e5c6a46b801b.png)

**Comment by chenzhipei** [comment]
2.2测试没有问题
