### ISSUE TITLE
审批王，修改流程后，流程编辑器打开不了这个流程

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#2087]
![image](https://user-images.githubusercontent.com/7553007/131791119-27d0f293-ff55-4955-afa2-d4c695852b3a.png)

![image](https://user-images.githubusercontent.com/7553007/131791063-5a1f624b-62bb-4296-b02a-69acecc44ce0.png)

**Comment by sunhaolin** [comment]
经测试，当 action的 visible 属性值为boolean类型且值为false时不生效
