### ISSUE TITLE
内核字段(例如owner)配置的label不生效

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2102]

**Comment by baozhoutao** [comment]
如果需要修改内置字段的label，请使用国际化文件进行配置。

**Comment by hotlong** [comment]
用国际化文件配置我们没问题，对第三方开发人员来说会觉得很奇怪，这个不急，我先放到2.2，但总要解决。

**Comment by hotlong** [comment]
先删除内核字段的国际化配置？

**Comment by baozhoutao** [comment]
方案: 从未继承base 的原对象定义中抽取默认对象国际化模板作,再与对象的国际化合并后,生产最终的国际化文件.
