### ISSUE TITLE
整理字段编辑页面，不常用的配置放到高级等分组中

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2104]

**Comment by lizhenghotoa** [comment]
- [ ] 部门表字段调整
![image](https://user-images.githubusercontent.com/26241897/132174184-57118a0d-9f44-4253-a85f-cd92c0c78988.png)
- [ ] 人员字段调整
![image](https://user-images.githubusercontent.com/26241897/132174648-e891188d-452d-4f28-9c74-1f7d36021579.png)
- [ ] 对象字段调整；同时启动增强查找功能默认开启。
![image](https://user-images.githubusercontent.com/26241897/132176348-1f7d49fd-ad58-4fc5-ad8d-6d6dfa6d8125.png)
