### ISSUE TITLE
对象详细界面字段列表需要在表格上设置排序号等字段

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2105]

**Comment by lizhenghotoa** [comment]
延伸为对象字段列表字段可以直接双击编辑
![image](https://user-images.githubusercontent.com/26241897/133099437-2cd2e2b6-f2eb-40b8-92a0-58f09c8652ed.png)

**Comment by lizhenghotoa** [comment]
- [ ] 对象字段列表可双击编辑；
- [ ] 主表objects对象更新到2.0表单

**Comment by baozhoutao** [comment]
此任务先不处理：目前不能编辑是禁用了单个字段的编辑功能，防止用户修改了字段类型后，其他属性未补充的情况。
