### ISSUE TITLE
如果用代码定义了 reference_to_field，删除之后 deploy，数据库中的未删除

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2107]
导致再次 retrieve 的时候，属性又下来了。

**Comment by baozhoutao** [comment]
此任务处理方案：
deploy 一条元数据记录时，在写入库之前，先retrieve 下当前记录，如果能获取到记录，则进行对比，新的记录中如果少数了属性，则使用$unset 更新数据

**Comment by hotlong** [comment]
感觉是这个意思
