### ISSUE TITLE
手机端：lookup类型字段值无法选中

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2117]
![image](https://user-images.githubusercontent.com/26241897/132191272-932fccbf-7c49-45b4-a462-266cb697d1c3.png)

**Comment by Flyingliao** [comment]
华炎魔方 手机端测试结果3个警告：
headerCheckboxSelection is not supported for Infinite Row Model
AG Grid: Grid API function setSideBarVisible() cannot be called as the grid has been destroyed.
                     Please don't call grid API functions on destroyed grids - as a matter of fact you shouldn't
                     be keeping the API reference, your application has a memory leak! Remove the API reference
                     when the grid is destroyed.
Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'AnonymousModel', Path upon death: '/items/lookup-contracts-contract_type-contract_types', Subpath: '', Action: '/items/lookup-contracts-contract_type-contract_types.getSelectedRowKeys()'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.

 - [ ] 手机端默认的弹出框选项换成下拉框选项。
