### ISSUE TITLE
服务启动日志不需要显示以下信息

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2119]
WARNING: npm peer requirements (for steedos:creator) not installed:
 - node-xlsx@0.16.1 installed, node-xlsx@^0.12.0 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

**Comment by baozhoutao** [comment]
steedos-platform\creator\packages\steedos-creator\checkNpm.js

checkNpmVersions: "node-xlsx": "^0.12.0"
