### ISSUE TITLE
附件详情页功能菜单放开在列表显示

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2136]
![image](https://user-images.githubusercontent.com/26241897/132304078-34b90314-9920-43ac-9f07-6f52b6689980.png)
![image](https://user-images.githubusercontent.com/26241897/132304130-b6528963-d13b-4cbd-a525-8b7ace0d7315.png)

**Comment by yinlianghui** [comment]
重复：2.0附件相关问题修正后更新到2.1分支，2.1分支附件列表中下拉操作菜单空了 #2146
