### ISSUE TITLE
审批--点击关联文件报“当前工作区不能使用此功能”，不应出现此提示

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#2142]
![image](https://user-images.githubusercontent.com/7665279/132325072-1c989d95-405f-4c4a-b0a2-818a8108b896.png)

**Comment by lizhenghotoa** [comment]
关联任务：云平台用户去掉许可证限制，服务申请完成后，自动生成相应licesne https://github.com/steedos/steedos-project-k8s/issues/93
