### ISSUE TITLE
隐藏钉钉/企业微信同步勾选框字段

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2145]
![image](https://user-images.githubusercontent.com/26241897/132452222-b08d6653-3223-408d-a2aa-2e6f6b890c1d.png)

**Comment by Flyingliao** [comment]
已修改， issue 未加上，故放图注明
![image](https://user-images.githubusercontent.com/41402189/132456571-df9a6f6c-2493-4875-9d12-26682555ad04.png)
