### ISSUE TITLE
对象删除后，并未从数据库表中真实删除，导致无法api_name添加同名的对象

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2152]

**Comment by lizhenghotoa** [comment]
目前对象中有个状态字段来记录对象是否删除，是否考虑去掉该字段，直接删除数据库中相关对象。
![image](https://user-images.githubusercontent.com/26241897/133094869-a47c39ad-9217-4955-87db-5c70f709e331.png)

**Comment by lizhenghotoa** [comment]
判断重名的时候不考虑已删除对象就可以

**Comment by yinlianghui** [comment]
经讨论，考虑给已删除对象增加“彻底删除”按钮，“还原”按钮也可以考虑加上，不急，延后处理。
