### ISSUE TITLE
设置-审批王--流程 在具体流程页面点击“流程设计器”后未显示已有的流程，从流程列表页点击“流程设计器”可以看到流程

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#2159]
![1631259847(1)](https://user-images.githubusercontent.com/7665279/132818884-af5b2fe4-7c08-4c21-af94-dfc3673cc5d6.png)

**Comment by lizhenghotoa** [comment]
未重现，更新环境后再次确认下问题
