### ISSUE TITLE
主表显示页，修改子表后，主表信息有时滞后

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#2163]
![image](https://user-images.githubusercontent.com/7553007/132938860-9d463c08-91e3-446b-be31-897c1cbaffef.png)

修改子表的支付状态

![image](https://user-images.githubusercontent.com/7553007/132938871-c329b767-fa93-43aa-b736-60131c27851e.png)

主表的累计字段未及时刷新

**Comment by yinlianghui** [comment]
哪个版本，最新版本的2.1应该没这个问题了。

**Comment by marchtian** [comment]
2.1.10还有类似问题

**Comment by yinlianghui** [comment]
我本地按上面一样配置了一个状态字段用于汇总过滤，一样无法重现该问题。
![image](https://user-images.githubusercontent.com/6219465/133055384-f2b9b5ff-c3b4-4d6e-a804-327ec3eabeca.png)

**Comment by yinlianghui** [comment]
关联任务：有时详细界面新建子表记录保存后，界面上累计汇总字段未显示最新值，需要刷新浏览器 #1841
