### ISSUE TITLE
对象设置中修改了字段类型，前台刷新浏览器未生效

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2170]
重新启动服务也未生效，系统还是以代码中定义的字段类型为准。

**Comment by lizhenghotoa** [comment]
同理，前端新增了字段后，也需要刷新浏览器才能生效

**Comment by baozhoutao** [comment]
“新增了字段后，也需要刷新浏览器才能生效” 是这个任务处理的，与此任务无关https://github.com/steedos/app-builder/issues/240
