### ISSUE TITLE
新建字段时，如果是主表/子表类型字段，引用对象属性应该显示必填星号，现在前端未校验必填，后端有校验

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2176]
相关表类型字段引用对象属性并不是必填所以不需要显示必填星号（因为允许设置选择项函数代替引用对象）。
![image](https://user-images.githubusercontent.com/6219465/133011921-e28d74b2-f7a3-407c-a044-b8cc87b7a937.png)

**Comment by lizhenghotoa** [comment]
主子表类型字段：引用对象字段必填；
