### ISSUE TITLE
零代码界面上编辑汇总字段的过滤条件时，各种字段类型未显示为对应的字段控件

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2179]
比如下拉框字段未显示为下拉列表，lookup字段未显示为相关表字段控件，创建时间字段未显示为时间控件

![image](https://user-images.githubusercontent.com/6219465/133051278-3030bb28-514b-4728-9805-16ed21eecd16.png)

**Comment by hotlong** [comment]
这个在目前的框架下实现不了吧？

**Comment by yinlianghui** [comment]
> 这个在目前的框架下实现不了吧？

大概看了下，现在调用的也是`ProField`，不清楚为什么没显示为对应的字段控件，需要调式看看。
