### ISSUE TITLE
公司对象字段调整

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2190]
- [ ] 登陆界面分组移到企业微信分组前
       企业微信、钉钉 两个分组是扩展的，sort_no 设置不了分组后移。
- [ ] 切换至2.0表单
       子分类和父分类两个字段找不到。
![image](https://user-images.githubusercontent.com/26241897/133211188-243539b1-4ccc-42f4-94c9-88491d7c61e4.png)

**Comment by hotlong** [comment]
重复
