### ISSUE TITLE
设置《系统对象，新增字段、后又删除，前台仍显示、新增时也有

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#2200]
steedos-apps下测试
系统内置对象（项目），新增字段，后又删除，前台的显示、增加页面仍然有这个字段
设置里已没有了
![image](https://user-images.githubusercontent.com/7553007/133353160-036fd763-d27c-4b76-b9c7-3722bb14668a.png)
前台还有
![image](https://user-images.githubusercontent.com/7553007/133353184-aaf43674-aa13-4f34-970e-5f82d3588ce3.png)

**Comment by marchtian** [comment]
重启服务后再看，显示、新增等没有这个 已删除字段了

**Comment by lizhenghotoa** [comment]
关联任务：对象设置中修改了字段类型，前台刷新浏览器未生效 https://github.com/steedos/steedos-platform/issues/2170
