### ISSUE TITLE
设置《系统对象，列表视图 未显示全

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#2201]
steedos-apps下测试
系统内置对象（项目），列表视图，缺 所有、最近访问等
![image](https://user-images.githubusercontent.com/7553007/133354007-16a53dfc-39c1-4aa1-9762-a42a5a7b0d24.png)

**Comment by lizhenghotoa** [comment]
数据库中列表视图有数据后，其他对象前台显示代码总的列表视图就会有问题。
- 数据库中没有列表视图数据，页面显示正常
![image](https://user-images.githubusercontent.com/26241897/133407524-19ab6b24-a74d-4ed1-b4b4-269e38c9ea03.png)
- 页面创建其他对象列表视图后，数据库中有列表视图数据，页面显示不正常
![image](https://user-images.githubusercontent.com/26241897/133407631-232e289c-591e-42ab-a3f3-9f10f694d141.png)
