### ISSUE TITLE
详情页相关表记录菜单点击后迟钝

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2207]
- [ ] 部分电脑点击菜单后无效
- [ ] 大部分电脑点击菜单后需要反应一秒弹出菜单
![image](https://user-images.githubusercontent.com/26241897/133363283-353d9590-473a-4df3-ad45-037c887d0185.png)

**Comment by hotlong** [comment]
是最后一行的横向滚动条挡住了，导致各种点击延迟问题。

**Comment by hotlong** [comment]
升级到 "27.2.1" 已解决 https://github.com/steedos/steedos-frontend/issues/359
