### ISSUE TITLE
新增了字段后，也需要刷新浏览器才能生效

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2213]
- 修改字段类型也有类似问题已被处理，见：对象设置中修改了字段类型，前台刷新浏览器未生效 #2170
- 说是#2170跟这个任务没关系，要确认下是不是跟 https://github.com/steedos/app-builder/issues/240 这个问题有关。

**Comment by yinlianghui** [comment]
已无法重现该问题。

**Comment by lizhenghotoa** [comment]
新增字段后过两秒，相应对象会刷新列表页，再次新建数据时，新增字段就出现在新建页面了
