### ISSUE TITLE
用户权限设置了viewAllFiles=false后，用户还是能看到所有附件

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#2217]

**Comment by yinlianghui** [comment]
这个是已知未完成问题，需要改OData接口，原始issue见（分到2.3了，原则上不需要优先处理了）：【扩展增加附件相关权限属性，允许单独配置业务对象的附件增删改查权限，而不需要跟主记录的编辑权限关联 #1707】

**Comment by yinlianghui** [comment]
重复任务，如果要优先处理，请安排处理 #1707
