### ISSUE TITLE
设置，对象的页面布局，相关子表，显示的字段，调整先后顺序不便

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#2232]
![image](https://user-images.githubusercontent.com/7553007/133883020-868cd629-ac48-4854-9945-2fed8de7f3f9.png)
例如想把其中一个字段的位置调整下

**Comment by marchtian** [comment]
有时，设置里的顺序和前台正相反
![image](https://user-images.githubusercontent.com/7553007/133884327-5e850088-ae8f-4c70-b00e-3f5da0761551.png)
![image](https://user-images.githubusercontent.com/7553007/133884364-69a7c35f-2515-4ec8-a561-e2064d4638ef.png)

**Comment by baozhoutao** [comment]
问题1：lookup组件多选时，应支持拖动排序
问题2：lookup组件多选时，显示的值顺序与存储的values顺序不一致。
