### ISSUE TITLE
设置，对象的页面布局，相关子表，操作按钮不生效/可选项缩小范围

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#2234]
设置
![image](https://user-images.githubusercontent.com/7553007/133883437-8f2ba104-9d9e-4018-a39d-64f551393b39.png)
不生效，前台还是“新建”按钮
![image](https://user-images.githubusercontent.com/7553007/133883487-07d61e12-c57f-4f4a-a7ad-a9508a547e7b.png)
另外，这些可选项，应该多了，部分按钮 放在子表处并不合适
![image](https://user-images.githubusercontent.com/7553007/133883496-b4873a96-c962-407a-b080-718cde053759.png)

**Comment by hotlong** [comment]
相关表配置功能下一步使用 amis 实现
