### ISSUE TITLE
设置，对象的默认列表视图，修改显示名称，无效

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#2236]
![image](https://user-images.githubusercontent.com/7553007/133885042-1e98a390-ba89-48c4-b3d8-48170b49fa5b.png)

![image](https://user-images.githubusercontent.com/7553007/133885045-06d1dcee-5a55-4f5b-a90f-4ae63c96cc01.png)

**Comment by baozhoutao** [comment]
国际化优先
项目的视图是配置了国际化文件的。

**Comment by baozhoutao** [comment]
如果需要修改显示名称，只能修改国际化文件

**Comment by marchtian** [comment]
所以，如果买了标准的应用，想要在页面上修改这个显示名称，没有办法 ？
