### ISSUE TITLE
enable_tree的树对象，当记录中parent属性配置的值为自己本身时会造成数据显示不出来

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2248]
- 应该写触发器禁止parent字段值配置为自己本身，包括新建记录和修改记录
- 在这个问题解决前请特别注意下，不要把记录指向自己，否则只能去数据库中改数据修正了

![image](https://user-images.githubusercontent.com/6219465/134635620-7f78739c-6960-45e2-90e8-8362d6281d90.png)

**Comment by lizhenghotoa** [comment]
目前提交数据会校验父级数据
![image](https://user-images.githubusercontent.com/26241897/140038273-1cdf5f9e-2656-4b04-861c-f744c2875da9.png)
