### ISSUE TITLE
页面布局可视化配置页面优化 （amis)

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2256]
- 支持多选字段
- 新增字段时，应自动带入字段所属分组名称
- 配置页面布局后列表批量删除按钮消失 #2319
- 设置，对象的页面布局，按钮》新建，可选项不应为所有按钮 #2279
- 对象设置界面点击页面布局标题会报错，但是不影响使用 https://github.com/steedos/steedos-platform/issues/3148

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/issues/2800

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/issues/2279  设置，对象的页面布局，按钮》新建，可选项不应为所有按钮 #2279

**Comment by hotlong** [comment]
对象设置界面点击页面布局标题会报错，但是不影响使用 #3148

**Comment by yinlianghui** [comment]
页面布局支持分组 #3743
