### ISSUE TITLE
华炎魔方tree对象列表，搜索功能异常

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2258]
- 会报错：`list_wrapper.coffee:450 Uncaught TypeError: $(...).dxTreeList is not a function`
- app-builder中该搜索功能正常
![image](https://user-images.githubusercontent.com/6219465/134813025-54d73290-bad6-4b2e-b624-286011cc14a7.png)

**Comment by yinlianghui** [comment]
根据报错信息搜索下相关代码，并改为执行grid组件的搜索函数就行。
可以参考普通的非tree列表是如何实现搜索功能的

**Comment by hotlong** [comment]
部门列表顶部搜索框搜索功能坏了 #2879

**Comment by hotlong** [comment]
计划用 amis 重构列表页
