### ISSUE TITLE
应用下所有对象都没有权限则不显示这个应用

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2259]
![image](https://user-images.githubusercontent.com/26241897/134851976-d841e6d3-00f3-406a-a249-1d65d116e6fd.png)

**Comment by hotlong** [comment]
这个规则太复杂，应该配置应用的权限来限制应用的显示。

**Comment by hotlong** [comment]
应用下不只有对象，还有选项卡
