### ISSUE TITLE
列表新建记录窗口中缺少保存并新建按钮功能

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2260]
![image](https://user-images.githubusercontent.com/6219465/134862245-92ca673b-e871-46d7-bf4b-2666a3eace44.png)
![image](https://user-images.githubusercontent.com/6219465/134862420-574a756e-25ac-4a36-b8a0-eb21f6484c9d.png)

**Comment by hotlong** [comment]
只需要支持 2.0 表单
