### ISSUE TITLE
附件版本对象目前只能通过手动输入URL配置其对象权限

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2263]
关联任务：[customer简档用户创建新纪录附件类型字段一直加载](https://github.com/steedos/steedos-platform/issues/2246) 

目前附件版本对象权限为空，只能手动新建其相关简档权限，并没有像其它对象一样列出user、admin简档权限。
![image](https://user-images.githubusercontent.com/41402189/135015748-28350372-ebcc-4ce3-80bc-9b1e304e24b4.png)

**Comment by lizhenghotoa** [comment]
除了附件版本、审计日志等相关系统标准对象，是否考虑放出这些对象在对象列表中？
