### ISSUE TITLE
新建批准过程的页面，在字段更新下拉框中点击新建字段更新保存后，字段更新未生效；单独在字段更新列表新建的字段更新，在批准过程中选择是生效的

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#2313]
字段值存错了，应该存的name实际存的_id

**Comment by yinlianghui** [comment]
- 这个是老的lookup字段在支持reference_to_field功能上有bug，新版本的lookup没这个问题。
- 此问题准备直接升级相关对象到2.0版本的表单避开相关问题
- 准备升级的对象包括：批准过程、工作流规则、字段更新（非必须但是准备一起升级）
- 另外本次准备一起升级流程自动化相关的其他对象为2.0表单
![image](https://user-images.githubusercontent.com/6219465/137074510-685d73ba-829b-4109-b110-bea4bade5d36.png)
