### ISSUE TITLE
字段更新记录中对象字段显示“无记录”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2332]
- [x] 字段更新列表页面
- [x] "新字段值类型"字段： 原因其optionsFunction中依赖了 “要更新的字段”、“对象”、“要更新的对象”三个字段的值作为条件。（"新字段值类型" 依赖 “要更新的字段”的值， “要更新的字段”依赖了“对象”、“要更新的对象”的值 ） 
解决方案： 直接在depend_on中补充完其所需的 字段。 当某个节点改变，其下依赖的所有节点都应该被清空。
![image](https://user-images.githubusercontent.com/26241897/137463669-f1d41781-f8c5-4df2-ad41-165403879493.png)
- [x] 列表视图编辑页面
![image](https://user-images.githubusercontent.com/26241897/137469266-1b06bde0-467f-45ef-999a-2a61ff8dd18c.png)

**Comment by Flyingliao** [comment]
![image](https://user-images.githubusercontent.com/41402189/137617953-8741730a-035f-4d02-8116-f97b894ff068.png)
