### ISSUE TITLE
[Feature]目前界面上不支持配置字段唯一性索引，需要支持

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2346]
yml中可以通过字段上配置unique: true实现

**Comment by Flyingliao** [comment]
该功能依赖了 @steedos/service-fields-indexs 软件包。
但是 该软件包启用后显示了启用成功，但是列表中依旧显示 ”启动中"
![image](https://user-images.githubusercontent.com/41402189/161984430-392cd6ab-bef1-4f23-8036-1c67857bcfc5.png)

**Comment by hotlong** [comment]
如题，应该支持在字段上配置

**Comment by hotlong** [comment]
@steedos/service-fields-indexs 是系统软件包，不需要单独启动，这个问题是因为需要配置定时任务创建索引，需要更新文档

**Comment by hotlong** [comment]
如果是定时创建，字段上应该有提示

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/5650
