### ISSUE TITLE
用户注册页面，姓名必填

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#2362]

**Comment by lizhenghotoa** [comment]
最新版本用户页面注册或者企业邀请链接注册页面，姓名都没有设置必填
![image](https://user-images.githubusercontent.com/26241897/139524412-33d8c4f5-2158-4a3b-990f-da8c856fc502.png)

**Comment by lizhenghotoa** [comment]
用户提交时会校验名称字段是否填写
