### ISSUE TITLE
tree对象直接清空parent字段值时，未重新计算原parent记录对应的children字段值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2380]
在`trigger.js`后缀文件的触发器语法中不可以通过`this.doc.parent`字段值是否为空来parent字段值是否被修改（也就是说不可以用之前meteor mongo的modifier.$set.parent这种思路来判断）。

**Comment by lizhenghotoa** [comment]
数据库原parent记录对应的children字段清空为null
