### ISSUE TITLE
人员对象权限默认存在“无此记录”权限集

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2385]
![image](https://user-images.githubusercontent.com/26241897/139193873-e2e3ec8b-cbdd-4141-8143-b24d21277006.png)
记录对应详情页
![image](https://user-images.githubusercontent.com/26241897/139193907-fbeb9a2e-6e8d-484e-a7ac-c3c1054d6ab0.png)

**Comment by Flyingliao** [comment]
重新新建下对应的organization_admin权限集即可。
