### ISSUE TITLE
高级设置中“打印模版”菜单先隐藏

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2399]
![image](https://user-images.githubusercontent.com/26241897/139625649-a7736291-93e5-44a3-ad4b-eebdb72e468b.png)

ldx排查结果：全局搜索 object_name: word_templates， creator外的word_templates已被注释，其内存在一个，但是其路径很特别，而且注释内部后 “打印模板”就正常消失，但是Git上没有改变后的记录。

已解决：该对象是个插件对象，在引用的地方注释就行。

**Comment by yinlianghui** [comment]
操作按钮对象上已去掉word_templates类型选项，见：
c2335dfd57ac068d87d621f02e23dbe55ce91ea6
84e5437f751bad4a1870fe59ad0932ac952bcefd
