### ISSUE TITLE
普通用户自己修改自己密码时，如果密码本身为空，不应该要求输入原密码，而是允许直接修改密码

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2404]
管理员始终允许直接修改密码，不用原密码

**Comment by lizhenghotoa** [comment]
目前测试普通用户修改密码没有加上原密码校验功能
![用户修改密码](https://user-images.githubusercontent.com/26241897/140000566-968ca230-c6b6-4b52-8469-f9882e7d3a96.gif)
