### ISSUE TITLE
流程配置配置了审批岗位后，retrieve异常

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#2405]

**Comment by lizhenghotoa** [comment]
目前貌似所有新增的流程都reteive不到代码了：新创建了一条流程，插件中flow目录下更新找不到。
![流程无法retrive](https://user-images.githubusercontent.com/26241897/140000192-cee267e9-d262-42f3-bc49-e0312d1b6e09.gif)

**Comment by baozhoutao** [comment]
只有配置了api name的flow 才可以reteive
