### ISSUE TITLE
选择框类型字段增加date_type属性，可以选择保存到数据库中为文本、数值还是布尔类型

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2408]

**Comment by yinlianghui** [comment]
规则：
- 支持options中的value值用文本类型表达数值，比如"10.50"和10.5等效
- 支持options中的value值用文本类型表达布尔值，比如"true"和true等效，为字符串时，只有等于"true"才表示true，其他都是false
- 如果是配置的optionsFunction，不支持用文本类型表达数值和布尔值类型，返回的选项value需要与data_type配置一致
- 列表视图单元格的过滤功能也支持select类型的data_type配置
- 列表视图单元格的编辑功能也支持select类型的data_type配置
- 列表视图单元格的复制粘贴功能也支持select类型的data_type配置

**Comment by yinlianghui** [comment]
剩余问题另外建issue了：选择框类型字段data_type配置为boolean时，列表视图界面右侧过滤器中按该字段过滤无效 #2459
