### ISSUE TITLE
user/supplier/customer普通用户进入人员对象后左侧组织树显示“ 没有要显示的数据”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2412]
![user用户人员左侧树不显示](https://user-images.githubusercontent.com/26241897/140007202-a43e3c85-057f-416a-8f99-5b200aee0b5a.gif)

**Comment by Flyingliao** [comment]
user 是正常的， 配置supplier/customer这两个的相关权限即可。
