### ISSUE TITLE
软件包自带的应用，停用后不生效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2414]

**Comment by baozhoutao** [comment]
重现方式：在应用详细页面点击自定义后，停用应用。页面还是能看到已停用的应用

**Comment by lizhenghotoa** [comment]
重现方式：
- 软件包停用后，软件包对应的应用没有停用；
- 然后，自定义到数据库中停用应用后，九宫格还是可以看到应用，但是应用点不进。
