### ISSUE TITLE
列表页相关表类型字段数据撑满时无法双击编辑数据

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2451]
- [ ] 点击尾部...应该可以编辑字段
- [ ] 点击尾部...应该展示字段详细信息（类似多行文本）
![image](https://user-images.githubusercontent.com/26241897/141440125-ca239b7c-3899-46e6-b505-4a0a6a318135.png)

**Comment by Flyingliao** [comment]
点击首部可以双击编辑数据。
![image](https://user-images.githubusercontent.com/41402189/143522532-a859ec51-003a-4161-90e6-51e3a34a13ca.png)
