### ISSUE TITLE
选择框类型字段data_type配置为boolean时，列表视图界面右侧过滤器中按该字段过滤无效

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2459]
- 是因为会先自动转为字符串参考过滤，这个是老版本的lookup控件问题，不好处理。
- 列表视图表头上的过滤功能是正常的，会按boolean类型值参与过滤。
- data_type配置为number或text时，不存在类似问题。

经讨论该问题不着急，暂时没有客户用到boolean类型的select字段。

**Comment by hotlong** [comment]
右侧面板改动暂停，计划重新开发
