### ISSUE TITLE
模板项目默认安装常用node modules

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#2463]
- [x] Mysql
- [x] SqlServer
- [x] Postgres
- [x] Oracle

**Comment by baozhoutao** [comment]
关系型数据库driver层使用了typeorm ，由于typeorm 无法支持动态schema。所以也无法支持微服务架构。
需要使用其他ORM，比如https://github.com/mikro-orm/mikro-orm

**Comment by baozhoutao** [comment]
如果继续使用typeorm ，则每次对象变更，整个database必须重建。

**Comment by yinlianghui** [comment]
用Mysql数据库测试下来会报错：
```
Error: TestFieldTypesForMySql is not exist or not registered in the connect
    at SteedosMySqlDriver.<anonymous> (/Users/yinlianghui/Documents/GitHub/steedos-platform-2-1/packages/objectql/lib/typeorm/driver.js:341:35)
```
因为dataSource在initTypeORM时无法拿到objects元数据，所以无法registerEntities，本质原因如上面@baozhoutao所述， 微服务架构不支持动态schema，typeOrm不能多次registerEntities

**Comment by yinlianghui** [comment]
name字段配置问题见issue：当对象没有配置is_name字段时，会出现对象列表界面报错等异常 #2487

**Comment by yinlianghui** [comment]
ac514be068f92930e4c928c428c84fb3a31946a8
727cd6f074e6fccdb2e196446a2f406a58f38d45
2e5d839d3b81baccf2f2071947c2fb3fc8b65d5a

**Comment by yinlianghui** [comment]
第三方数据源，列表视图每条记录右侧未显示编辑删除下拉菜单 #2492

**Comment by yinlianghui** [comment]
- Oracle数据库因为要本地安装客户端环境，配置可能比较复杂（原来写过文档见：[node连接oracle数据库准备条件](https://github.com/steedos/steedos-platform/blob/c6d5131c1bc46ac128716ba0e28a350259f8f985/packages/objectql/test/unit/driver/oracle/README.md)），暂时先放放，不过已经在模板项目中加上了最新版本的oracle驱动。
- 其他的数据库类型都可以正常使用了
