### ISSUE TITLE
公式计算：computeFormula函数不需要强制依赖object name

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#2473]

**Comment by yinlianghui** [comment]
改了公式内核，改动不大，已实现，规则如下：
- 语法：`objectql.computeFormula(formula, null, data, currentUserId, spaceId, options)`
- 第二个参数就是object name传入空值表示执行简单公式计算
- 跟原来的规则一样currentUserId, spaceId, options参数可以不传入，但是要用$user时，必须传入currentUserId, spaceId
- 当传入第二个参数为空时，同时传入currentUserId，也是支持$user全局变量功能的

为简化函数使用，额外增加了新的内核函数`objectql.computeSimpleFormula`，该函数就是computeFormula函数移除第二个参数的效果，功能不变，语法为：`objectql.computeFormula(formula, data, currentUserId, spaceId, options)`
