### ISSUE TITLE
在graphql中查询子表数据时，如果相关的主表子表字段被删除，依旧可以查询到数据。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2491]
图中红框中是已经被删除的三个主表子表字段，但是这里依旧存在， 刷新页面也存在； 目前测试只有重启服务和刷新页面 后这三个主表子表字段信息才会消失。

![image](https://user-images.githubusercontent.com/41402189/142985714-a85e34cb-49f3-416c-b519-c11ff24d871a.png)

**Comment by baozhoutao** [comment]
补全关系键清理

**Comment by baozhoutao** [comment]
此问题在  #2517 任务中 已处理
