### ISSUE TITLE
累计汇总类型字段编辑时隐藏

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2498]
![image](https://user-images.githubusercontent.com/26241897/144406809-9dbf6c39-70fa-4113-a101-546fc26a6ca1.png)

**Comment by Flyingliao** [comment]
已在最新版本克隆项目中测试到效果了。

**Comment by yinlianghui** [comment]
已按sf规则处理，公式和累计汇总字段始终在编辑的时候会显示其值。
