### ISSUE TITLE
登录页面版权信息和隐私是否能够进行设置

### ISSUE THREAD

**Issue by JAVPHP** [steedos/steedos-platform#2502]
![1638021448(1)](https://user-images.githubusercontent.com/48326762/143684477-2254c7fe-0241-481a-bd5d-273f6d6390fd.png)
您好，请问登录页面的版权信息和隐私是否能够修改或设置，如果可以请问该如何修改谢谢

**Comment by lizhenghotoa** [comment]
华炎魔方暂时不支持修改相关版权及隐私设置信息
