### ISSUE TITLE
GraphQL控制台无法进入

### ISSUE THREAD

**Issue by 20907437** [steedos/steedos-platform#2508]
在配置JSReport的时候，需要用到GraphQL控制台，单在访问的时候无法访问，报500错误。
当前版本2.1.50，群里提示重新部署环境试试。
通过npx create-steedos-app dw-edu命令，重新下载环境，并且指向一个新的数据库。问题依旧存在。还是报500错误。
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/66851599/143963420-5023aacf-d7dc-4232-b862-f5a600099e0c.png">

**Comment by yinlianghui** [comment]
如果是换空库也还是会报错的话，如果没有明确的重现规则，这种情况应该是您那边低代码配置的yml对象或字段配置有问题，请先自行检查下相关对象及字段配置。

**Comment by yinlianghui** [comment]
我这里用`npx create-steedos-app dw-edu`指定测试下来并没有发现GraphQL有问题

**Comment by 20907437** [comment]
我换了空库，并未做任何配置。直接启动http://localhost:3000/graphql地址访问。是不是需要在steedos-config.yml文件做什么配置呢？
提示500 Internal Server Error错误。后台报的错误，如下：
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/66851599/143972783-b78e23d7-c416-4203-84f4-5144d1286852.png">

**Comment by 20907437** [comment]
到应用商店下载项目管理应用。涉及到其它应用对象，就会出现错误。暂时无法解决。
