### ISSUE TITLE
在文件夹中右键执行deploy指令时报错需要steedos source:config，疑似METADATA_APIKEY未合并到环境变量STEEDOS_CLOUD_SPACE_ID

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2515]
因为执行`steedos source:config`时会要求输入METADATA_APIKEY值，然后会自动在环境变量中加上环境变量METADATA_APIKEY配置。
![image](https://user-images.githubusercontent.com/6219465/144214708-6f0a1bc0-958d-4eb5-94cf-084970909b25.png)

![image](https://user-images.githubusercontent.com/6219465/144214881-a12b8f75-6d21-43d5-8f01-2be1ca6cbede.png)

**Comment by baozhoutao** [comment]
这2个环境变量不是一回事。无法合并
