### ISSUE TITLE
新建了一个查询，然后vscode下载同步为代码，再重启服务，出现了两个名称相同的查询

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2533]
新出现的同名查询是yml代码中的，不可以编辑，原来的查询还是可以编辑的，是数据库中的记录。
![image](https://user-images.githubusercontent.com/6219465/144436956-2fd94a25-c166-4484-a909-f202d6c5f6d7.png)

**Comment by yinlianghui** [comment]
另外列表上出会有一些空白记录，比如下图，从network请求中可以看到count是27条数据，但是实际只返回了20条，少掉的数量7应该是低代码中有7条同名的yml文件的元数据，与数据库中的同名了。
![image](https://user-images.githubusercontent.com/6219465/144750132-ced5f016-cb1d-4288-833f-00e273a0dd2f.png)

**Comment by baozhoutao** [comment]
重复任务
