### ISSUE TITLE
stimulsoft数据源字段类型没有自动匹配

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2538]
目前数据源字段都是文本类型
![image](https://user-images.githubusercontent.com/26241897/144570244-9202ef7d-1fbd-4010-a8de-c00e856a8813.png)

**Comment by lizhenghotoa** [comment]
对应查询脚本：
{
    "collection": "poc_business_opportunity__c",
    "aggregate": [
        {
            "$lookup": {
                "from": "poc_income__c",
                "localField": "_id",
                "foreignField": "business_opportunity__c",
                "as": "poc_income__c"
            }
        },
        {
            "$lookup": {
                "from": "poc_external_department_revenue__c",
                "localField": "_id",
                "foreignField": "business_opportunity__c",
                "as": "poc_external_department_revenue__c"
            }
        },
        {
            "$lookup": {
                "from": "poc_industry_first_classification__c",
                "localField": "industry_first_classification__c",
                "foreignField": "_id",
                "as": "poc_industry_first_classification__c"
            }
        },
        {
            "$lookup": {
                "from": "poc_industry_second_classification__c",
                "localField": "industry_second_classification__c",
                "foreignField": "_id",
                "as": "poc_industry_second_classification__c"
            }
        },
        {
            "$lookup": {
                "from": "poc_area__c",
                "localField": "area__c",
                "foreignField": "_id",
                "as": "poc_area__c"
            }
        },
        {
            "$unwind": {
                "path": "$poc_income__c",
                "preserveNullAndEmptyArrays": true
            }
        },
        {
            "$unwind": {
                "path": "$poc_external_department_revenue__c",
                "preserveNullAndEmptyArrays": true
            }
        },
        {
            "$unwind": {
                "path": "$poc_industry_first_classification__c",
                "preserveNullAndEmptyArrays": true
            }
        },
        {
            "$unwind": {
                "path": "$poc_industry_second_classification__c",
                "preserveNullAndEmptyArrays": true
            }
        },
        {
            "$unwind": {
                "path": "$poc_area__c",
                "preserveNullAndEmptyArrays": true
            }
        },
        {
            "$addFields": {
                "poc_income__c_name": "$poc_income__c.name",
                "poc_income__c_period__c": "$poc_income__c.period__c",
                "poc_income__c_estimated_income_amount__c": "$poc_income__c.estimated_income_amount__c",
                "poc_income__c_estimated_income_date__c": "$poc_income__c.estimated_income_date__c",
                "poc_income__c_estimated_transaction_date__c": "$poc_income__c.estimated_transaction_date__c"
            }
        },
        {
            "$addFields": {
                "poc_external_department_revenue__c_name": "$poc_external_department_revenue__c.name",
                "poc_external_department_revenue__c_amount__c": "$poc_external_department_revenue__c.amount__c",
                "poc_external_department_revenue__c_area__c": "$poc_external_department_revenue__c.area__c",
                "poc_external_department_revenue__c_estimated_income_amount_2021_q4__c": "$poc_external_department_revenue__c.estimated_income_amount_2021_q4__c",
                "poc_external_department_revenue__c_estimated_income_amount_2022_q1__c": "$poc_external_department_revenue__c.estimated_income_amount_2022_q1__c",
                "poc_external_department_revenue__c_estimated_income_amount_2022_q2__c": "$poc_external_department_revenue__c.estimated_income_amount_2022_q2__c",
                "poc_external_department_revenue__c_estimated_income_amount_2022_q3__c": "$poc_external_department_revenue__c.estimated_income_amount_2022_q3__c",
                "poc_external_department_revenue__c_estimated_income_amount_2022_q4__c": "$poc_external_department_revenue__c.estimated_income_amount_2022_q4__c",
                "poc_external_department_revenue__c_estimated_missing_amount__c": "$poc_external_department_revenue__c.estimated_missing_amount__c",
                "poc_external_department_revenue__c_finished_amount__c": "$poc_external_department_revenue__c.finished_amount__c",
                "poc_external_department_revenue__c_industry_first_classification__c": "$poc_external_department_revenue__c.industry_first_classification__c",
                "poc_external_department_revenue__c_industry_second_classification__c": "$poc_external_department_revenue__c.industry_second_classification__c",
                "poc_external_department_revenue__c_missing_amount__c": "$poc_external_department_revenue__c.missing_amount__c",
                "poc_external_department_revenue__c_target_amount__c": "$poc_external_department_revenue__c.target_amount__c",
                "poc_external_department_revenue__c_type__c": "$poc_external_department_revenue__c.type__c"
            }
        },
        {
            "$addFields": {
                "poc_industry_first_classification__c_name": "$poc_industry_first_classification__c.name"
            }
        },
        {
            "$addFields": {
                "poc_industry_second_classification__c_name": "$poc_industry_second_classification__c.name"
            }
        },
        {
            "$addFields": {
                "poc_area__c_name": "$poc_area__c.name"
            }
        },
        {
            "$project": {
                "poc_income__c": 0,
                "poc_external_department_revenue__c": 0,
                "poc_industry_first_classification__c": 0,
                "poc_industry_second_classification__c": 0,
                "poc_area__c": 0
            }  
        }

    ]
}

**Comment by baozhoutao** [comment]
问题原因：传入的类型未生效
![image](https://user-images.githubusercontent.com/6194462/144575962-e99ce286-f347-4a80-80c8-96965fc3a14a.png)
