### ISSUE TITLE
在界面新建一个对象，然后在选项卡中引用该对象，选项卡只读界面显示了 [无此记录]

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2550]
有可能重启服务能好，未确认。
![image](https://user-images.githubusercontent.com/6219465/144811595-cf53642f-7d8d-4f54-9fd2-304644c13dab.png)

**Comment by yinlianghui** [comment]
这个对象上只配置了一个金额类型和自动编号类型的字段，很简单的。

**Comment by Flyingliao** [comment]
原因：该字段配置了reference_to 和optionsFunction属性，但是optionsFunction中value保存的是name，并不是_id.
