### ISSUE TITLE
queries元数据deploy到数据库后，页面出现重复数据

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2554]
![image](https://user-images.githubusercontent.com/26241897/145013064-40cfb491-71f0-4ff8-b838-c5d32ff0ce14.png)

**Comment by lizhenghotoa** [comment]
- 页面加载代码端charts对象数据，会显示空行
![image](https://user-images.githubusercontent.com/26241897/149435627-10eaa5bd-02b2-42c0-bed9-e73e2f4d7026.png)

**Comment by lizhenghotoa** [comment]
尝试安装的软件包通过deploy到数据库来验证问题，发现目前最新版本2.1.81版本代码和数据库记录并存问题还是存在：
- 查询：
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/154601878-ef963d2f-befc-4403-ab57-61b4eef9844b.png">

- 图表
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/154601924-e1f66afe-65a1-4454-8a69-bb82f98b2288.png">

- 页面
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/154601990-4f25652d-6daf-4453-a85b-9c3b5c6f86ea.png">

**Comment by baozhoutao** [comment]
还未发版本

**Comment by lizhenghotoa** [comment]
2.1.85版本：查询、图表数据deploy后正常，页面deploy后列表还是显示错误数据
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/26241897/155077873-a227d524-54f2-4426-9e5a-b3d1fdfbfa60.png">

**Comment by lizhenghotoa** [comment]
2.2.52-beta.1版本元数据同步正常，页面记录显示正常
