### ISSUE TITLE
默认数据源，不显示‘测试链接’按钮

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2565]
![wecom-temp-046166e7bea76429c8e663c6dde615ff](https://user-images.githubusercontent.com/6219465/145376381-575e5d27-abba-4be6-917b-b3823358e24a.png)

**Comment by yinlianghui** [comment]
服务 不会死，只是服务端报错，刷新浏览器界面就正常了，报错信息：
```
TypeError: Cannot read property 'close' of undefined
    at SteedosDataSourceType.<anonymous> (/Users/yinlianghui/Documents/GitHub/steedos-apps/node_modules/@steedos/objectql/src/types/datasource.ts:521:27)
```

**Comment by Flyingliao** [comment]
```
doc: {
  _id: 'default',
  name: 'default_M6x6ddKvpj9ddcYYm_default__test',
  label: 'Default data source'
}
```
![image](https://user-images.githubusercontent.com/41402189/145672811-3059cfbd-b395-4237-ae01-12f7d8113e6f.png)
