### ISSUE TITLE
软件包记录详细界面 创建时间、创建人等字段值是空的

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2568]
当时想到这个问题的初衷是想看看某个软件包是什么时候安装的。
![image](https://user-images.githubusercontent.com/6219465/145929254-5c4c921d-0daa-42b4-bb71-ea39fc38cbff.png)

**Comment by baozhoutao** [comment]
目前是以文件形式存储的软件包安装信息，创建时间、创家人无需记录，也记录不了。
不做处理
