### ISSUE TITLE
累计汇总deploy数据源报错：字段未填写:summary_filters

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2584]
![image](https://user-images.githubusercontent.com/41402189/146879558-865a9f8c-885a-4ca8-84c3-45bc9feac357.png)

**Comment by lizhenghotoa** [comment]
升级到2.1.61版本数据同步还是提示相同问题
![image](https://user-images.githubusercontent.com/26241897/147555397-2889c18e-c722-4974-8460-3ed8dc4a4419.png)

**Comment by baozhoutao** [comment]
重新安装下steedos cli

**Comment by lizhenghotoa** [comment]
云环境同步更新到最新版本后测试通过
