### ISSUE TITLE
从业务对象，一键生成审批流程

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2587]
- 创建流程时，选择对象。
- 在流程设置界面增加按钮，添加字段，可以从对象中选择字段。如果字段已存在则更新，如果不存在则创建。
- 在流程设置界面增加按钮，添加子表，可以从对象中选择子表。如果子表已存在则更新，如果不存在则创建。

以上都要考虑
- lookup字段自动生成 odata 相关配置
- 字段映射关系自动生成

**Comment by sunhaolin** [comment]
- 流程添加字段： 绑定对象、审批单字段（grid）、审批单子表（grid）；放入分组‘流程绑定对象’；
 - 流程增加按钮：‘更新审批单’，将 审批单字段（grid）、审批单子表（grid） 最新内容同步至表单
   - 一种情况是修改了对象的下拉框字段选项，不需要修改审批单字段（grid）、审批单子表（grid），则需要点击按钮
   - 二种情况是修改了审批单字段（grid）、审批单子表（grid），则应自动同步至表单
 - 规则：
   - 生成的表单字段完全来自于 对象 （审批单字段（grid）、审批单子表（grid））
   - 如果选择了 绑定对象则禁用 ‘表单设计器 ’按钮；及流程设计器中的‘表单设计器’；
 - 对象流程映射添加字段： 同步方向（sync_direction select）：双向同步、审批单至对象、对象至审批单 （默认值 双向同步，考虑历史数据）；
 - 测试点：
   - 流程导入导出
   - 元数据同步

**Comment by lizhenghotoa** [comment]
功能优化：

- [ ] 流程绑定对象后初始化将对象非系统字段（name字段除外）初始化到审批王表单中（主子/相关表暂时不考虑），流程对象映射初始化完成；
- [ ] 流程绑定对象确认后，不需要跳转到审批王流程设计器，直接进如流程详情页面即可；
- [ ] 流程对象映射初始化时，“附件同步方式”目前为不同步，需要调整为同步最新版本；
- [ ] 初始化的审批王开始节点字段权限默认全部勾选可编辑；
- [ ] 流程详情页，流程绑定对象分组显示顺序提前，提到模版分组上；
- [ ] “添加字段”按钮点击后，字段过滤出非系统字段（name字段除外）可供添加选择，保持现在单选即可；
- [ ] “同步审批单”按钮：“添加字段”功能确认后，直接同步审批单字段以及对象流程映射关系，无需再点击“同步审批单”按钮，进行重复操作；
- [ ] BUG：odata字段审批王表单无法选择；
- [ ] BUG：配置完成后，流程详情页出现字段不见情况 #2822

**Comment by lizhenghotoa** [comment]
测试情况如下：

- [ ] 针对“流程绑定对象后初始化将对象非系统字段（name字段除外）初始化到审批王表单中（主子/相关表暂时不考虑）”，是不初始化对象相关表/子表数据，对象的主子/相关表字段还是需要初始化的；
- [ ] 添加字段—选择申请单子表后，保存数据服务端报错
TypeError: fieldNames is not iterable
    at Object.exports.getObjectFieldsByNames (/workspace/steedos-project-template/node_modules/@steedos/workflow/src/designerManager.js:602:25)
    at /workspace/steedos-project-template/node_modules/@steedos/workflow/src/designerRouter.js:1116:47
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
- [ ] 添加字段后，审批王对应字段开始节点默认可编辑（可能是因为相关表没做默认同步导致，可和第一个问题合并）
- [ ] 百分比、密码类型字段同步到审批王表单带了浏览器填充的默认值；

**Comment by sunhaolin** [comment]
百分比、密码类型字段同步到审批王表单带了浏览器填充的默认值，需要调整浏览器的设置
