### ISSUE TITLE
手动安装软件包，url和认证信息字段会浏览器自动填充

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2615]
![image](https://user-images.githubusercontent.com/26241897/147735813-138362ee-82ae-43ad-b785-5d042d263ec0.png)

**Comment by yinlianghui** [comment]
重复任务：https://github.com/steedos/steedos-apps/issues/245

**Comment by lizhenghotoa** [comment]
127.0.0.1访问服务会出现这个问题

**Comment by lizhenghotoa** [comment]
gitpod环境安装软件包ye h也会自动填充
![image](https://user-images.githubusercontent.com/26241897/148905541-efaf2481-0f37-4e99-b346-79b6e90758e4.png)

**Comment by Flyingliao** [comment]
任何一个对象中如果有相邻的一个在前的文本字段和一个在后的密码字段，那么编辑该对象字段时这两个字段会自动填充当前用户账号和密码。
