### ISSUE TITLE
界面上卸载、停用软件包需要重启服务才能生效。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2617]
软件包停用、卸载后， 在九宫格中仍然可以看到对应的应用，进入应用可以修改对象的记录。  重启服务后 被停用、卸载的软件包在九宫格中才看不到了。

**Comment by baozhoutao** [comment]
未重现。软件包中的对象是否点击过自定义？

**Comment by baozhoutao** [comment]
49d11c41eca89e142895f036dd66c7f5a1a843b7
