### ISSUE TITLE
Gitpod远程运行platform源码跑Creator项目时有时会报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2618]
- 并不是每次都会报错，有时看睐一切正常，什么错都没有
-  是在chrome上运行Gitpod发现的，本地vscode远程并没有试过

```
Error: stream unexpectedly closed
W20211231-15:29:10.414(0)? (STDERR)     at Socket.onClose (packages/shell-server/shell-server.js:383:12)
W20211231-15:29:10.414(0)? (STDERR)     at Socket.emit (events.js:323:22)
W20211231-15:29:10.414(0)? (STDERR)     at Socket.EventEmitter.emit (domain.js:482:12)
W20211231-15:29:10.415(0)? (STDERR)     at TCP.<anonymous> (net.js:668:12)
```
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/6219465/147830686-285174b7-b7a4-49f0-a701-68ae3ed93dfa.png">

**Comment by sunhaolin** [comment]
最新meteor 2.5.3创建新项目启动 也报此错，由meteor 内核 shell-server包打印此信息

**Comment by yinlianghui** [comment]
> 最新meteor 2.5.3创建新项目启动 也报此错，由meteor 内核 shell-server包打印此信息

但是为什么本地跑Creator项目不会打印此错误信息呢？

**Comment by sunhaolin** [comment]
跑rocketchat也出现此信息

**Comment by hotlong** [comment]
如果用 chrome 访问呢？而不是这个 simple browser，会报错吗？

**Comment by sunhaolin** [comment]
服务是可以正常访问的

**Comment by sunhaolin** [comment]
已报issue：
https://github.com/gitpod-io/gitpod/issues/7455
https://github.com/meteor/meteor/issues/11834
