### ISSUE TITLE
Gitpod远程运行模板项目新开命令行窗口运行项目的话，列表视图数据会是空的

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2620]
- 如果不是手动新开的命令行窗口，而是刚进入Gitpod时自动打开的命令行窗口的话，手动运行yarn start是好的
- 如果是手动新开的命令行窗口，手动运行yarn start是坏的。
- 只在模板项目中试过该问题，估计platform源码也是一样的。
- 只在chrome浏览器上远程运行Gitpod项目时试过该问题，本地的vscode运行远程Gitpod项目没试过，但是估计也是一样有问题。

<img width="621" alt="image" src="https://user-images.githubusercontent.com/6219465/147831168-d7dc8264-1972-4362-9725-1ad646a843b6.png">

**Comment by sunhaolin** [comment]
处理方案： 增加初始化脚本，拷贝.env文件为.env.local，替换 ROOT_URL和METADATA_SERVER值
