### ISSUE TITLE
Chrome上运行Gitpod项目，无法在vscode扩展市场上搜索到steedos插件

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2621]
使用本地vscode打开远程Gitpod项目，是可以正常搜索和安装steedos插件的，且测试过双向同步功能都是正常的。
<img width="976" alt="image" src="https://user-images.githubusercontent.com/6219465/147831355-68d63c7c-8a76-4f0d-b5a0-b708ffd982f0.png">

**Comment by yinlianghui** [comment]
Chrome运行Gitpod时虽然市场上搜索不到，但是应该可以把 vs code 插件在 open vsx 平台也发布一次，然后在vsx中安装：https://github.com/microsoft/vscode/issues/108147

<img width="638" alt="image" src="https://user-images.githubusercontent.com/6219465/147831815-a506baf8-5504-4f75-878c-fc95f6b73c2d.png">

**Comment by sunhaolin** [comment]
已无此问题
