### ISSUE TITLE
docker 运行后提示： ls: cannot access '/dev/disk/by-id/': No such file or directory

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2624]
以下链接运行也报错 https://gitpod.io/#https://github.com/steedos/steedos-platform

**Comment by sunhaolin** [comment]
systeminformation 包 `const disksById = execSync('ls -1 /dev/disk/by-id/').toString();` 导致
最新版本 5.9.17 已解决 `const disksById = execSync('ls -1 /dev/disk/by-id/ 2>/dev/null').toString();`

- [ ] 解决方案：使用systeminformation@5.9.17
