### ISSUE TITLE
从对象权限点进权限集，权限集应用显示为空记录

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2632]
![image](https://user-images.githubusercontent.com/26241897/148026625-8b9d4879-d147-4316-b7eb-da35f245cba3.png)

**Comment by Flyingliao** [comment]
排查结果：
 1、该版本请升级下。类别是简档时才会出现 密码策略 等分组字段。
 2、未能重现 授权应用字段 为空。
