### ISSUE TITLE
页面布局中没有配置权限集字段权限中的字段，用户页面显示该字段只读

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2641]
- 字段权限
![image](https://user-images.githubusercontent.com/26241897/148158735-79f4060c-08ba-417a-8b28-60b6e4ffddd2.png)
- 页面布局
![image](https://user-images.githubusercontent.com/26241897/148158767-041b8bfa-4e7d-4ee2-86fc-55229007e0df.png)
- 用户页面
![image](https://user-images.githubusercontent.com/26241897/148158767-041b8bfa-4e7d-4ee2-86fc-55229007e0df.png)

**Comment by baozhoutao** [comment]
所属分部字段
