### ISSUE TITLE
拓展标准对象的标准操作按钮设置隐藏无效。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2652]
具体情况：在新创建的项目中对人员对象列表上的 ”新建“、 （创建的记录详情页上）”相关任务“ 按钮设置隐藏。 管理员账号依旧可以看到”新建“按钮，普通用户两者都看不到。

注意：is_enable、visible 、standard_new.button.js中的visibleFunction返回值都设置false。

-------
将以下文件中的action调整为标准格式：
- [x] company.object.js
- [x] object_workflows.object.js
- [x] space_users.object.js

base.object.js 经测试不用调整。

**Comment by Flyingliao** [comment]
最终测试结果：列表上的标准按钮不能拓展修改。

**Comment by baozhoutao** [comment]
1 普通用户无法看到 “相关任务” 是redis 问题，清理下redis缓存
2 space_users的standard_new action 无法重写问题原因是 space_users 的actions 写法不规范导致，见 1102行 。packages\standard-objects\space_users.object.js 
请查找standard-objects中所有不规范的actions定义，并调整为标准格式。
主要是看是否有在.object.js中定义actions
