### ISSUE TITLE
GitLab上运行模板项目不能启动debug调试模式、没有默认安装steedos插件。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2664]
Github上运行模板项目： steedos插件默认安装并生效了、debug模式正常。
Gitlab上运行模板项目： 没有默认安装steedos插件、debug模式无效。

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/148878372-0ebab4dd-1871-4604-896d-4ea7d92be39f.png)
