### ISSUE TITLE
weixin-pay 引用包错误 MD5 （不应该大写），导致使用淘宝源安装时，提示MD5包找不到

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2666]
weixin-pay@1.1.7:
  version "1.1.7"
  resolved "https://registry.yarnpkg.com/weixin-pay/-/weixin-pay-1.1.7.tgz#ce9b9d331bba8952f5ef961ecdc913705aeb2652"
  integrity sha1-zpudMxu6iVL175YezckTcFrrJlI=
  dependencies:
    MD5 "^1.2.1"
    request "^2.54.0"
    xml2js "^0.4.6"

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-apps/commit/ce12c0b4216acd845831d86db381cbfdff54ce89
