### ISSUE TITLE
新建编辑记录时，表单上有必填字段时提示不明显，因为必填字段可能隐藏到滚动条界面外了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2675]
方案1：提交时滚动条自动跳转到必填字段位置让用户看到哪个字段有错误
方案2：表单上加个总的错误提示信息

salesforce测试地址：https://www.salesforce.com/ap/form/conf/howto-playlist/    ==》  右侧 try for free
![image](https://user-images.githubusercontent.com/41402189/149250536-49df6846-18d3-438e-b40f-b8223ffa4eb0.png)

![image](https://user-images.githubusercontent.com/41402189/149250126-ce4e96e4-b887-450a-9c87-6d2f4a5ed450.png)

**Comment by hotlong** [comment]
看看 salesforce 怎么处理的
