### ISSUE TITLE
环境变量中redis如何配置带安全认证的链接？

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2677]
论坛询问链接：[redis 链接问题](http://community.steedos.cn/t/topic/90)

官方文档中应该补充该问题内容。

**Comment by 20907437** [comment]
请问，这个问题解决了吗？

**Comment by yinlianghui** [comment]
测试过一，通过redis cli使用config set requirepass 123456设置密码为123456的话，配置以下环境变量可以正常使用redis服务：
```
TRANSPORTER=redis://a:123456@127.0.0.1:6379
CACHER=redis://a:123456@127.0.0.1:6379/1
```
