### ISSUE TITLE
gitpod跑平台creator源码的时候会报错：please add package.service.js in Plugin @steedos/steedos-plugin-workflow

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2700]
![image](https://user-images.githubusercontent.com/6219465/149467895-78ee5c16-6e4e-4bea-af39-651b961c48dc.png)

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/149476581-4487f7ab-7088-4e53-9060-703f72549f2e.png)

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/commit/2169a693873fb380a5990023fcd915cd9be7765f
