### ISSUE TITLE
业务伙伴对象添加管理员简档时报错：‘can not read property length of undefined’

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#2716]
![image](https://user-images.githubusercontent.com/15027092/149752350-6a10c716-6226-4461-a001-97361cbed603.png)

**Comment by Flyingliao** [comment]
1、错误”Cannot read property 'length' of undefined“没有重现。

2、报错”同一个对象、简档只能有一条记录“找到原因：如果配置了多个页面布局，而且拥有”管理员“简档的页面布局超过1个就会报错。
目前定制的规则是每种简档只能拥有一个页面布局。

正常创建多个拥有同样简档的页面布局时，点击”提交“按钮会报错。
