### ISSUE TITLE
字段visible_on 表达式中 依赖多个字段，显示控制失败

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#2717]
![image](https://user-images.githubusercontent.com/6194896/149754178-34222101-3f74-41ac-82c4-e9f9393cfe9f.png)

**Comment by lizhenghotoa** [comment]
visible_on: >-
  {{ formData.xft_xxr_overtime_allowed__c  === true   &&
  formData.xft_xxr_not_count_overtime__c  === true ? true: false }}

**Comment by Flyingliao** [comment]
测试结果是正常的。
