### ISSUE TITLE
公式字段联动选择框类型字段报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2721]
错误信息：The field formula "xft_travel__c.xft_type__c" with params "{"xft_travel__c.xft_type__c"false{"type"false"literal","value"false"单程","dataType"false"picklist"}}" should return a string type result but got a picklist type value '单程'.
![image](https://user-images.githubusercontent.com/26241897/150058743-b3dfe173-39e2-4644-92ee-48d9a9bb505d.png)

**Comment by yinlianghui** [comment]
需要使用TEXT函数转换 `TEXT(xft_travel__c.xft_type__c)`。
参考文档：https://www.steedos.com/docs/admin/formula#%E4%BD%BF%E7%94%A8%E9%80%89%E9%A1%B9%E5%88%97%E8%A1%A8%E5%85%AC%E5%BC%8F%E5%AD%97%E6%AE%B5%E7%9A%84%E6%8F%90%E7%A4%BA
