### ISSUE TITLE
远程启动服务如果服务端控制台报错，无法点击错误信息自动跳转到node_modules中对应的代码位置上

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2725]
记得之前在本地是能正常点击跳转过去的。
![wecom-temp-f96c0e5ffc8ebef3cf46b4dab3bbb437](https://user-images.githubusercontent.com/6219465/150269761-83f05660-a406-47e5-99fe-f5a51fe41c8e.png)

**Comment by hotlong** [comment]
Gitpod问题不处理

**Comment by hotlong** [comment]
可以尝试用vscode客户端 打开工作区
