### ISSUE TITLE
GitLab远程启动模板项目启动成功后，并没有自动安装好元数据同步和mongo插件

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2727]
- gitpod.io上的模板项目是正常的
- vscode.steedos.cn上模板项目是坏的，但是我之前迁移过去的qsy项目即是正常的

**Comment by hotlong** [comment]
右下角应该会提示你安装插件。

**Comment by yinlianghui** [comment]
后面我又试了一次vscode.steedos.cn上的qsy项目，发现这次坏了，也就是说看起来是不稳定：
![image](https://user-images.githubusercontent.com/6219465/150293678-c9392245-980c-49a1-89bb-3c26f2866b8d.png)
