### ISSUE TITLE
对象设置中把字段设置只读时，初始值和默认值不能保存到数据库。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2728]
原因：对象的uSchema接口中该字段的omi属性返回为true了。

只有把字段权限中“允许编辑”功能放开，才能让该字段的omit属性变回正常的omit为false。

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/150311757-4d2aa766-adc3-458b-952b-75e32a11a431.png)
