### ISSUE TITLE
设置应用详细界面图标字段显示成“无此记录”了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2747]
![image](https://user-images.githubusercontent.com/6219465/150931213-ba098829-f27d-4d50-a2f3-b3a684cb6280.png)

ldx: 排查结果
creator/packages/steedos-objects/lib/resources.coffee
在_STANDARD_SPRITE_IDS里面添加 settings 应该就可以了。
![image](https://user-images.githubusercontent.com/41402189/151107907-8fb28a31-2cd0-4dea-8cb8-8d4be120fd1f.png)

**Comment by Flyingliao** [comment]
模板项目中测试修改的内容有效果了，不是“无此记录”了
