### ISSUE TITLE
用户停用的时候，对应的 user 和 space_users 记录，手机号和邮箱都清空

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2748]

**Comment by yinlianghui** [comment]
经讨论username也一并清除

**Comment by lizhenghotoa** [comment]
隐患：
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/153981392-cbcb8ec5-8833-43fb-9a99-08ba14ff30a1.png">
