### ISSUE TITLE
服务启动慢

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#2753]
require allServerScripts：7秒，主要原因是 object.js中的创建索引部分
startupHooks：12秒，主要原因是创建索引部分
datasource.init: 0.5秒左右，但是调用次数多，而且从reids中获取的数据量大
loadPackageMetadatas：一个软件包少量的元数据就需要1.5秒左右
setInlineScriptsAllowed：4秒，meteor内核函数，看提交记录是为了解决手机app报错问题
cacher 慢：当元数据服务和软件包再同一个进程中启动时，有时一个cacher查询耗时需要7秒左右。但是redis并不慢，都是1毫秒左右返回数据

优化内容：
- [ ] 启动服务时，不再自动创建索引， 单独提供一个软件包创建索引，并将_ensureIndex相关代码迁移到service-fields-indexs软件包中

**Comment by baozhoutao** [comment]
812f27f42c2b29b0391e03e55ab7459dfc9ce5e3

**Comment by baozhoutao** [comment]
测试点：
1 新增对象、对象字段、按钮、列表视图等是否正常
2 安装软件包是否正常，包括软件包下的对象、字段、应用、触发器
3 停用软件包是否正常，包括软件包下的对象、字段、应用、触发器
以上几个测试点，每个测试完后，都看下graphql接口是否正常，新增、卸载的对象是否可以查询

**Comment by Flyingliao** [comment]
测试结果：
1、新增对象、字段、按钮、列表视图、页面布局正常。
2、安装软件包后，相关应用程序需要手动刷新浏览器才会显示出来，安装后测试正常。
3、停用软件包后，相关应用程序不会自动消失，此时可以继续对软件包中的对象记录进行添加， 如果手动刷新浏览器，相关应用程序和对象才会消失。
4、卸载软件包后，界面上相关应用程序不会自动消失，此时可以继续对软件包中的对象记录进行添加， 如果手动刷新浏览器，相关应用程序和对象才会消失。
5、对象删除后，需要手动刷新浏览器，应用程序中的对象菜单才会消失。
