### ISSUE TITLE
steedos-config.yml文件中设置enable_register: true， 登录界面的注册按钮没有显示出来。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2754]
![image](https://user-images.githubusercontent.com/41402189/151099434-aa4c2198-57f9-479e-9f33-691d23feabda.png)

**Comment by lizhenghotoa** [comment]
enable_create_tenant参数设置为true

**Comment by baozhoutao** [comment]
设置-公司-登录页面中启用注册功能。
