### ISSUE TITLE
对象设置中点击进入对象的列表视图详细界面，删除该视图，返回到的界面不对

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2757]
- 正确的是返回到对象设置详细界面，目前返回到`/app/admin/object_listviews/grid/all`了，这是所有列表视图列表界面
![image](https://user-images.githubusercontent.com/6219465/151140003-09ca7d54-4cc8-4c29-949f-68a503a0f516.png)
- 用户较常要使用删除视图功能的场景是：在内置对象的列表视图界面点击“自定义”按钮来修改视图，然后又想删除该视图看看“自定义”前的效果。

**Comment by hotlong** [comment]
计划用 amis 重构对象定义页面
