### ISSUE TITLE
软件包卸载后列表上依然显示该软件包为已启用

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2763]
有可能是因为该软件包是从应用市场中购买安装的，私有部署的软件包之前应该是好的，近期没测试过。
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6219465/151651261-aed2884a-663d-4deb-b3a9-303533a323bc.png">

**Comment by yinlianghui** [comment]
刷新浏览器没有，但是重启服务后可以看到卸载掉的软件包不显示在列表上了。

**Comment by lizhenghotoa** [comment]
关联任务：
-  #2741

**Comment by baozhoutao** [comment]
请在2.1.85+版本上确认
