### ISSUE TITLE
会议应用，把代码copy到模板项目，deploy到界面，然后不知道什么时候新建会议记录几个字段的默认值就异常了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2764]
未找到具体的重现规则，有遇到两次了，应该是有bug。
有可能是deploy后再下载到本地，整个过程没改过一行代码，就是一直做deploy或下载元数据操作。
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/6219465/151654644-65c41564-80c5-415b-a8cd-99fa87b01e52.png">
请廖同学先帮忙测试确认下准确的重现规则。

**Comment by yinlianghui** [comment]
我把本地会议软件包全部删除后重新从apps中copy过来，比对可以看到是之前元数据操作（左侧）把默认值函数中的`!<tag:yaml.org,2002:js/function>`给移除了。
<img width="1133" alt="wecom-temp-1bf50a23e1e3c1b489d043cdc0950c5d" src="https://user-images.githubusercontent.com/6219465/151655227-a8aa3952-b88e-4cd8-9f21-74530801a2c2.png">

**Comment by Flyingliao** [comment]
deploy元数据后默认值就失效了， 重启服务器能恢复正常；  下载元数据，其默认值中的 <tag:yaml.org,2002:js/function> 或 !!js/function 会被移除，也会导致默认值失效。

**Comment by Flyingliao** [comment]
高版本的yml解析器已经不支持defaultValue属性值为 函数时 旧的写法。
defaultValue 属性值为函数时最新写法： [字段默认值公式](steedos.cn/docs/developer/getting-started#字段默认值公式)
```
defaultValue: |-
  {{
    (function() {
        var now, reValue;
        now = new Date();
        reValue = new Date(now.getTime() + 1 * 60 * 60 * 1000);
        reValue.setMinutes(0);
        reValue.setSeconds(0);
        return reValue;  
    })()
  }}
```

**Comment by baozhoutao** [comment]
问题原因：2.0 form 未处理defalutValue 为 string function 的情况 。 相关任务https://github.com/steedos/steedos-platform/issues/2773
