### ISSUE TITLE
对象设置界面上为自定义对象添加自定义按钮无法生效，没有在前台界面上显示该按钮

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2766]
- 内核版本2.1.76
- 配置为“显示在记录查看页右上角”和“显示在列表右上角”都没效果
![image](https://user-images.githubusercontent.com/6219465/152755063-8fa69c2f-1d66-4ac9-9e16-2895ac8e20c3.png)

**Comment by yinlianghui** [comment]
请 @Flyingliao 先测试看看最新版本是不是有这个问题，还是说我配置的方法不对。

**Comment by Flyingliao** [comment]
2.1.76测试正常，  最新版2.1.78也测试正常。
原因：页面布局没有添加自定义按钮。
