### ISSUE TITLE
flows对象升级到version: 2

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#2779]

**Comment by Flyingliao** [comment]
- [ ] 1、流程 点击 新建按钮 显示的是1.0表单。
 - [ ] 2、grid下设置了hidden、omit： true的字段升级后依旧显示出来了。 _id ,  此步骤分发时可选的流程范围 , 创建时间 , 修改时间.
 - [ ] 3、type: object的字段分组无效。
 - [ ] 4、创建人字段type: lookup , reference_to: users。  1.0表单该字段显示的是时间， 2.0表单无值
 - [ ] 5、修改人字段type: lookup , reference_to: users。  1.0表单该字段显示的是 姓名 + 时间， 2.0表单显示 姓名。
