### ISSUE TITLE
gitpod环境：不能正常停用软件包

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2781]
- 停用后刷新的页面如下：
![image](https://user-images.githubusercontent.com/26241897/153356530-2c3e6115-e581-4008-91e7-dca216166351.png)
- 再次点击重新加载按钮，提示报错信息
![image](https://user-images.githubusercontent.com/26241897/153356723-63ad0cdc-336d-4e0b-a331-4ef59314d0ed.png)

**Comment by baozhoutao** [comment]
2.1.85版本已正常
