### ISSUE TITLE
gitpod环境：项目启动后，对象的列表视图提示“未找到符合查询条件的集合”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2784]
环境地址：https://steedos-steedosapps-b7e6tfj0oq4.ws-us31.gitpod.io/
登陆账号、密码私聊

**Comment by yinlianghui** [comment]
已处理，修改了以下项目的`gitpod.yml`文件：
- github上的模板项目master分支
- gitlab上的模板项目master分支
- github上的apps项目main分支
- github上的platform项目2.1分支

本次测试验证方法：
- 正常跑起一个新的gitpod项目
- 激活并登录系统
- 把env.local文件中rootURL故意改成错的
- 在gitpod的workspace列表页面找到启动的服务，下拉菜单中点击Stop按钮停掉服务
- 在gitpod的workspace列表页面找到刚停掉的服务，下拉菜单中点击Open按钮重新打开项目
- 看到env.local中的rootURL被自动修正了

**Comment by lizhenghotoa** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/155248837-4b3fe7fa-ec65-46ae-b614-192cd90a8072.png">
