### ISSUE TITLE
customer简档用户附件字段，上传报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2798]
- customer简档配置的对象权限是增改查，页面布局附件字段是默认允许编辑的没有勾只读
- 管理员是能够看到customer用户上传的附件记录的
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/153818964-b3613f60-2c56-4087-87f3-c18f0cd16051.png">

**Comment by Flyingliao** [comment]
关联任务： customer简档用户创建新纪录附件类型字段一直加载 #2246
处理方法在评论中： cfs_files_filerecord附件版本对象也要配置相应的customer简档权限，customer简档用户才能在记录中成功上传附件

**Comment by lizhenghotoa** [comment]
附件对象增加customer简档权限
