### ISSUE TITLE
批准过程提交审批报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2803]
- 错误信息：
Catch an error "Syntax error." while eval formula "请处理" with paramsfalse "{}" for "{"objectName"false"service_application__c"}"
![提请批准报错](https://user-images.githubusercontent.com/26241897/153975851-4f4ec4ba-70e6-4505-a7f4-0974ee2a8b15.gif)

**Comment by baozhoutao** [comment]
此问题是由于工作流通知的 标题公式、正文公式格式不准确导致。 文本常量需要用引号引起来。
