### ISSUE TITLE
对象字段grid列表，超过一百行字段后，显示重复行记录

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2815]
<img width="1599" alt="image" src="https://user-images.githubusercontent.com/26241897/154894873-187ed46c-db5c-419e-9860-5ea2dc12ddc4.png">
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/26241897/154894912-8900e4e2-9227-48b0-befd-b84e336cca0f.png">

**Comment by hotlong** [comment]
对象有一个开关，禁用翻页。

**Comment by hotlong** [comment]
需要确认前台

**Comment by yinlianghui** [comment]
- 测试下来大概总字段数在110个左右会出问题
- 当出问题的时候创建人创建时间等内置字段就没显示在列表上，同时出现了前面重复的字段

通过下面的脚本可以给自定义对象批量添加字段，把i变量改为不同的数值时可以生效不同数量的字段：
```
for(var i = 20;i < 90;i++){
    Creator.odata.insert("object_fields", {label: `名称${i}`,
_name: `name${i}`,
object: "test_many100__c",
owner: "6256492d343d3328b2f15f0b",
sort_no: 110+i,
type: "text"}, function(result, error){
    console.log(result);
});
}
```

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/3128
