### ISSUE TITLE
amis: 相关表控件优化

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2820]
- 根据权限，显示标准按钮
- 显示自定义按钮
- 参考sf, 如果有记录，最下面显示查看所有

![image](https://user-images.githubusercontent.com/50353452/166660629-fb7cfb0a-d01b-4da4-9371-2fe119e7e62c.png)

**Comment by hotlong** [comment]
正在用 amis 重构界面，愿界面停止修改
