### ISSUE TITLE
流程分类-所属应用字段显示异常

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2824]
- [x] 选项异常
 - [x] 表格中只读异常
![流程分类所属应用显示异常](https://user-images.githubusercontent.com/26241897/155069791-e49ba985-102f-4619-93a8-8780f4faf501.gif)
-----
 - [x] 详细页面显示异常： 流程分类表单升级到2.0就正常了。
![image](https://user-images.githubusercontent.com/41402189/155918058-c3869769-3fa6-43bf-bddc-92fa20740cfe.png)

![image](https://user-images.githubusercontent.com/41402189/155921059-5b0e42ee-61f9-40fa-be58-7bf65e2ffe27.png)

**Comment by Flyingliao** [comment]
原因： 同时配置了 reference_to: apps 和 optionsFunction。
数据库中没有 审批王、设置、办公、项目、主数据、合同等。
只读时按 保存的值去数据库里搜索， 编辑时 按optionsFunction获取数据。
