### ISSUE TITLE
账户注册相关参数优化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#283]
新增参数
  - enable_bind_email: 注册时，发送邮件验证码。暂时不开发强制绑定邮箱的功能。

保留参数：

  - enable_register: 启用用户注册功能
  - enable_password_login: 启用密码登录，默认启用。
  - enable_create_tenant: 启用创建工作区功能
  - enable_bind_mobile: 强制绑定手机号，登录后检测到用户手机号未验证，强制进入手机验证界面。
  - enable_forget_password 使用验证码登录

作废参数：

- enable_mobile: 启用手机端界面，此开关作废。
- disable_email_register: 禁止邮箱注册，此开关作废。必要时可以启用强制绑定手机号代替。
- enable_mobile_code_login: 启用手机号 + 验证码登录

## 登录
  - 如果启用了 enable_password_login，默认进入使用密码登录界面。
  - 否则默认进入使用验证码登录界面。

使用密码登录 enable_password_login
  - 显示手机、邮箱、用户名+密码登录界面。
  - 如果配置了 enable_forget_password，底部显示验证码登录链接。

使用验证码登录 enable_forget_password
  - 显示手机、邮箱验证码登录界面。
  - 用户点击获取验证码时，如果短信服务/SMTP服务未配置，提示报错。

## 注册
  - 如果未启用 enable_register，报错
  - 如果配置了 enable_bind_mobile，自动进入手机号注册界面。
  - 否则进入邮箱注册界面。

用户邮箱注册流程
  - 用户输入邮箱，点下一步。
  - 如果启用邮箱验证 enable_bind_email，则给用户发送邮件验证码。
  - 如果未启用，则进入用户初始化界面，输入姓名、密码后，创建用户。

用户手机注册流程
  - 用户输入手机号，点下一步。
  - 如果启用手机验证 enable_bind_mobile，则给用户发送手机验证码。
  - 如果未启用，则进入用户初始化界面，输入姓名、密码后，创建用户。

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-accounts/commit/075e3bdfe0d57b6507b78cabe82d1671bea6099f

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-accounts/commit/205e4942ee02bbd98fac3c728593ae9506018177
