### ISSUE TITLE
工作流通知“指定对象的用户字段”选不到数据

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2846]
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/26241897/156124229-8aba16ed-ea1a-4e2f-9c28-e73038b70f68.png">

**Comment by Flyingliao** [comment]
请检查指定的对象中是否含有 类型为 相关表/主表子表，属性 omit  != true , 属性 reference_to === 'users'。 只有同时符合这三者的字段才有数据提供选择。
![image](https://user-images.githubusercontent.com/41402189/156328965-27f87e19-1294-40c1-b9c9-eda826495d94.png)
