### ISSUE TITLE
流程引擎改造

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2855]
- [ ] 流程对象新增子表：用于存储 指定步骤上发起工作流通知、及通知哪些人(已处理过的指定步骤处理人或者特定的上级？)。
- [ ] 工作流通知增强：支持外部直接指定通知人员（函数也需要增强）、支持指定角色。
- [ ] 支持在指定节点后，调用工作流通知，并将要通知的人写进instances的cc数组中。
- [ ]  instances 支持beforeSubmit、afterSubmit等trigger。workflowTrigger.js 规范：https://low-code-protocol.com/docs/flow-trigger

**Comment by sunhaolin** [comment]
xxx.workflowTrigger.js
