### ISSUE TITLE
新增软件包：steedos-hr-package

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2857]
- [ ] 新增花名册对象：hr_employee

- [ ] space_users 添加 hr_employee_id 字段，space_users 配置为花名册的子表。

- [ ] instances新增afterSubmit trigger: 如果当前处理人在hr_employee中存在多个space_users，且其他user记录也是当前步骤的处理人，则将其他user记录的approve也处理掉。
- [ ] workflowflowTrigger.js 规范：https://low-code-protocol.com/docs/flow-trigger

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/2855
