### ISSUE TITLE
公司员工使用私人手机号注册华炎魔方客户门户账户，这个手机号又激活部署过若干私有部署项目，后续该员工离职怎么办

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2859]
就是有人注册了华炎魔方门户账户，并且用这个账户的手机号去激活和部署过私有部署项目，然后这个人离职了怎么办，能不能有什么方便的操作入口来处理这种情况。
目前可以操作的流程是：
1.先把激活部署过的私有部署项目下的管理员手机号、姓名等换掉。
2.再进入华炎魔方客户门户，用离职人员手机号登录后，在个人设置->我的资料中把手机号、姓名等换掉
3.在华炎魔方客户门户，进入管理控制台后找到离职人员建的“我的魔方”记录修改管理员的手机号、姓名等信息
现在的问题有两个：
1.上述流程第三步做不到，因为手机号和姓名改不了。
2.上述流程有没有可能优化下，找到更方便合理的处理类似情况的操作方法。
3.有没有其他需要额外处理的逻辑，比如魔方ID和APIKEY方面的逻辑。
我能想到的最简单的办法是，当用户在console平台修改手机号和姓名时，把其对应的“我的魔方”的手机号和姓名一起自动改掉。
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/6219465/156379452-0b620868-efea-49ae-97bc-516840036152.png">

社区论坛贴子：https://community.steedos.cn/t/topic/172

**Comment by hotlong** [comment]
管理员在后台协助处理就可以
