### ISSUE TITLE
在 project-template/package.json 中，指定 nodejs 版本区间？

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2862]

**Comment by yinlianghui** [comment]
已把github和gitlab上的模板项目都改为：
```
  "engines": {
    "node": "^12.22.0"
  },
```
后续对14,16测试通过后可用`||`分开扩展。
<img width="722" alt="image" src="https://user-images.githubusercontent.com/6219465/156530485-5263b7de-cc4d-451d-9b8c-a297a42bece0.png">
