### ISSUE TITLE
涉及到自定义 简档时，工作流规则、批准过程功能异常，不会触发字段更新和工作流通知

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2870]
有客户提出遇到的问题，我们本地先重现模清楚规则。

**Comment by yinlianghui** [comment]
说是自定义简档时啥都干不了，包括记录自动锁定功能也是坏的。

**Comment by lizhenghotoa** [comment]
- [ ] 批准过程审批步骤中处理人有自定义简档用户（岗位绑定自定义简档用户）不会收到通知；

- [ ] 工作流通知自定义简档用户收不到通知；

- [ ] 自定义简档人员创建记录能够正常触发工作流通知、字段更新、

- [ ] 自定义简档人员数据*详情页系统默认子表不显示（附件、审批过程.....）*

- [ ] 提请批准按钮重复显示

![image](https://user-images.githubusercontent.com/26241897/157172400-a1489073-61c0-4197-aa18-dba656c2e831.png)

- [ ] 批准过程审批人为普通用户没办法打开“审批细节”数据情况；

![image](https://user-images.githubusercontent.com/26241897/157172599-0f970bb4-ada4-42ab-a56e-dc6b459c103f.png)

- [ ] 记录提交后，记录数据不会被锁定。
