### ISSUE TITLE
部门列表顶部搜索框搜索功能坏了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2879]
- 没有触发请求
- 应该是tree对象都坏了
![image](https://user-images.githubusercontent.com/6219465/157608850-c6ca9f0e-e0ab-4171-8b81-4cd7d9c24ce2.png)

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/157609090-60f9e3f4-a8f2-4f66-9e30-5f979f5040d2.png)

**Comment by hotlong** [comment]
重复
