### ISSUE TITLE
使用最新版本v2.2.3源码无法正常运行

### ISSUE THREAD

**Issue by arenaswan** [steedos/steedos-platform#2884]
操作步骤：
1、下载源码v2.2.3，并解压；
2、在根目录下执行：tyarn  ；
3、修改/steedos-platform/steedos-projects下.env中STEEDOS_CLOUD_API_KEY以及STEEDOS_CLOUD_SPACE_ID；
4、在根目录下执行yarn run compile
5、在根目录下执行yarn run start
上述步骤都能正常运行
然后通过浏览器访问：http://localhost:5000，页面会一直redirect，地址栏也一直增长：http://localhost:5000/accounts/a/#/login?redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Faccounts%2Fa%2F%23%2Flogin%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5000%252Faccounts………………

**Comment by baozhoutao** [comment]
请参考这个文档：https://github.com/steedos/steedos-platform/blob/master/CONTRIBUTING.md#prepare-for-development

缺少了 `yarn bootstrap` 、`yarn build`
