### ISSUE TITLE
清理length-stream依赖，没有地方在使用，且会从github上安装依赖。

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#2895]

**Comment by hotlong** [comment]
meteor cfs packages 中有引用

**Comment by hotlong** [comment]
根源是 
pass-stream@~0.1.0:
  version "0.1.5"
  resolved "https://registry.npm.taobao.org/pass-stream/download/pass-stream-0.1.5.tgz#9e3afa4d5825cdd1376075bdb56de36dfb33649f"
  integrity sha1-njr6TVglzdE3YHW9tW3jbfszZJ8=
  dependencies:
    readable-stream "https://github.com/jeffbski/readable-stream/archive/v1.0.2-object-transform2-ret-self.tar.gz"

**Comment by hotlong** [comment]
有可能锁定 readable-stream 的版本可以解决，需要测试

**Comment by sunhaolin** [comment]
pass-stream 固定版本为 1.0.0： "**/pass-stream": "1.0.0"

**Comment by hotlong** [comment]
作废 resolutions，需要修改 cfs 内核，删除对两个包的引用。相关代码复制到cfs中
