### ISSUE TITLE
外部数据源相关表显示问题

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#2922]
使用外部数据源做相关表时，对应字段使用reference_to_field可以进行绑定，但是在预览时候，会显示无此记录。如何配置可以默认显示某个字段。
![image](https://user-images.githubusercontent.com/34770813/160612422-249ee89d-43a2-408f-ae02-5bb9da5e8528.png)

**Comment by yinlianghui** [comment]
这个问题是因为我们lookup字段请求相关表数据的时候始终额外请求了_id字段
![wecom-temp-b98791be8bd8fd3e22f955f2495865f5](https://user-images.githubusercontent.com/6219465/160735688-d1548cde-edbd-44fd-b0ab-33b6db819e68.png)

**Comment by yinlianghui** [comment]
已处理，前端判断到是外部数据源的时候，不自动强制把_id加到要搜索的字段中，因为外部数据源不存在_id主键字段。
