### ISSUE TITLE
外部数据源是mongoDB的对象同步元数据时， datasource 属性没有同步下来, 新建记录后报错。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#2925]
前提： 外部数据源是mongoDB。   其它类型数据源没有测试。
 - [ ] datasource 属性没有同步下来。
 - [ ] 新建记录后报错。
![image](https://user-images.githubusercontent.com/41402189/160749619-242b5aac-48c7-4a08-8500-0a923cdf471f.png)

**Comment by yinlianghui** [comment]
因为外部数据源的规则是不会自动在记录中设置space属性，所以接口没查到记录造成的。
![image](https://user-images.githubusercontent.com/6219465/160989769-360df08c-8ba3-4e60-972a-6b8dbe917140.png)

**Comment by yinlianghui** [comment]
实测只要执行下面的语句把该数据源下对象都加上space属性值就可以正常显示了：
```
db.m1.updateMany({}, {$set:{
  "space": "615ffbf0726ca50030255d41"
}});
db.m1.find({  });
```
