### ISSUE TITLE
对象的单条flowRoles元数据加载到页面会显示两条重复记录

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2932]
元数据：
<img width="838" alt="image" src="https://user-images.githubusercontent.com/26241897/161014440-2ad9e29b-5a62-4018-be6b-8cfa920b28f1.png">
页面数据：
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/26241897/161014509-0534ca75-3f88-408b-b18d-39751522ac51.png">

**Comment by baozhoutao** [comment]
2.1, 2.2未重现

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/2945
