### ISSUE TITLE
软件包加载导入的流程节点没办法关联页面设置的岗位

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2933]
重现规则：导入的岗位数据是没用分部信息的，同时导入的流程（页面创建的流程正常）节点只能选择到没有这部分的岗位记录，页面新建的岗位记录都选择不上。

**Comment by baozhoutao** [comment]
规则:
1 流程没有分部,选择岗位时, 只能选择没有设置分部的岗位.
2 流程有分部,选择岗位时：只能选择分部 为空的，或者分部与流程相等的
