### ISSUE TITLE
审计日志中字段值新增新增值字段没有值

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#2940]
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/26241897/161359825-02dfa059-be27-4709-b09c-b36bfed82bd6.png">

textarea、code、html、markdown、grid 五个字段类型无新值、旧值。
经过包、殷老师和廖讨论暂时放开 textarea、code、html、markdown 这四个。

**Comment by Flyingliao** [comment]
关联任务：字段修改历史（审计日志）中部分字段不能显示其新、旧值 #2277
