### ISSUE TITLE
文档：字段权限

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2943]
## 调整方向

服务端接口返回字段时， 根据用户字段权限自动计算readonly属性。如果没有配置字段级权限，根据字段的 hidden，readonly 属性计算字段级权限的默认值。

### 不可查看
- 定义：配置了字段权限且不可查看; 没有配置字段权限，字段的hidden为true
- 接口不返回字段定义
- 在客户端表单、列表始终不显示

### 可查看不可编辑
- 定义：配置了字段权限可查看不可编辑; 没有配置字段权限 字段的hidden 为false 且字段的readonly为true
- 接口返回 hidden=false； readonly=true； omit 以字段配置为准
- omit 字段，始终不显示。
- 非 omit 字段，在客户端表单的只读状态和修改状态中始终显示，但不可编辑
- 非 omit 字段，在客户端列表，配置了则显示。

### 可查看可编辑
- 定义：配置了字段权限可查看可编辑; 没有配置字段权限 字段的hidden 为false 且字段的readonly为false。
- 接口返回 hidden=false； readonly=false；omit 以字段配置为准。
- omit 字段，始终不显示。
- 非 omit 字段，在客户端表单的只读状态和修改状态中始终显示，可编辑。
- 非 omit 字段，在客户端列表，配置了则显示。

## 对象设置调整

- 字段设置界面去掉 omit、readonly、 hidden 属性。历史代码中的属性仍然有效，按照上面的规则计算。
- base 中大部分字段的 omit 属性要去掉。

**Comment by hotlong** [comment]
<img width="899" alt="企业微信截图_561ca4c1-d8a6-4c3c-9fe8-ce87bfab2612" src="https://user-images.githubusercontent.com/50353452/161388542-c0b098bc-10f0-46f0-ba29-3bb000f69df1.png">

**Comment by yinlianghui** [comment]
默认值相关issue: https://github.com/steedos/steedos-frontend/issues?q=is%3Aissue+omit+is%3Aclosed
初步看起来本次变更不影响默认值规则。

**Comment by yinlianghui** [comment]
加两条规则：
omit的字段在列表、记录详细、新建/修改记录窗口中都不显示。
hidden（包括字段上配置的hidden属性和字段权限中配置的不可见属性）的字段在列表、记录详细、新建/修改记录窗口中都不显示。

**Comment by yinlianghui** [comment]
如果omit字段有问题，请去掉omit属性，改为配置字段的`visible_on`属性，参考：https://github.com/steedos/steedos-platform/issues/3141
