### ISSUE TITLE
a公式字段，其中应用了b公式字段，记录保存后a字段没计算，编辑后再保存字段计算

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#2946]
例子，港口能源付款记录中的付款比例字段

**Comment by yinlianghui** [comment]
- 是新建记录时保存后，a公式字段引用的另一个公式字段b中的值没带到a字段的计算结果中，编辑后会重新计算a公式字段值才正常。
- 只有a公式字段中引用的另一个公式字段是当前对象自身的另一个公式字段才有问题，如果引用的是另一个对象上的公式字段的话没有这个问题。
