### ISSUE TITLE
自动编号字段支持编辑

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2947]
- [x] 把公式引擎加到自动编号功能中，主要是为了支持写if else等逻辑，最终返回自动编号规则
- [ ] 如果公式中引用了其他字段值，相关字段值变更后不会重新更新自动编号值
- [ ] 自动编号字段之前是完全只读的，改为可以通过字段权限配置出可编辑效果
- [ ] 用户手动填写的编号值在保存时只校验值唯一性，允许输入和保存为不符合编号规则的值
- [ ] 服务端计算自动编号值时，需要校验字段值的唯一性
- [ ] 服务端计算自动编号值时需要支持跳号规则，比如按规则算到的编号值需要在库里查一次是否被占用，占用后按规则自动计算下一个编号值（需要考虑性能问题）
- [ ] 因为用户手动填写的编号值允许不符合编号规则，所以手动填写的值不在跳号规则中占位（即使输入的是符合编号规则的值），且单独标记为手动编号的值
- [ ] 新建记录时不显示自动编号字段，只有编辑记录时才显示为文本输入框
- [ ] 手动填写编号值时，不允许输入空值
- [ ] 高级设置中的自动编号设置功能依然生效，且当出现大批量的手动插入的自动编号值时，可以通过这种配置功能避免性能问题
- [ ] 自动编号不应该允许配置为必填，就算配置为必填了也不能识别为必填，避免新建记录时报错

**Comment by hotlong** [comment]
写一个具体的例子，怎么通过公式判断根据不同条件返回不同编码规则。

**Comment by yinlianghui** [comment]
自动编号上一代功能任务： 支持自动编号类型字段，第一步实现流水号 #102
