### ISSUE TITLE
开关和复选框两种字段类型应该忽略必填属性

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#2948]
- 目前是有客户说必填后会报错，且保存后值不是false而是undefined
- 解决方案可以是强制加上默认值为false逻辑

**Comment by Flyingliao** [comment]
测试正常，值都是  true  或  false 。
未出现报错现象。

必填后报错， 目前就报： 该字段必填。
解决方案强制加上默认值为 false  ， 我觉得不需要， 不设置必填不就行了？
或者直接设置默认值为true。

请提供具体的系统版本！

**Comment by yinlianghui** [comment]
其实是两个问题：
1.当没有配置必填时，用户没有勾选过该字段值时数据库中不应该保存为undefined或null，而应该保存为false
2.当配置为必填时，不应该强制要求用户勾选操作一次该字段才允许保存记录，不应该让用户去设置默认值，而应该平台自动处理这两种字段类型的默认值。
