### ISSUE TITLE
删除对象是软删除，但是再次新增同样名称和api的对象时，会报对象已存在。

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#2971]
新建一个对象test、删除对象test、再次新建对象test

**Comment by baozhoutao** [comment]
直接做真删除

**Comment by baozhoutao** [comment]
删除对象后: 相关表记录也自动删除?
- [ ] 字段、
- [ ] 按钮、
- [ ] 列表视图、
- [ ] 对象权限、
- [ ] 对象权限、
- [ ] 对象流程映射、
- [ ] 对象验证规则、
- [ ] 限制规则、
- [ ] 共享规则、
- [ ] 开放流程
