### ISSUE TITLE
“新建 流程”时UI界面无“名称”字段输入框

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#2987]
1. 通过docker compose启动模板项目。
2. 新建一个对象
3. 新建“对象流程映射”，在该页面尝试“新建 流程”
4. 打开如下页面：
<img width="1251" alt="Screen Shot 2022-04-10 at 21 49 12" src="https://user-images.githubusercontent.com/5885946/162623087-e038be31-445f-4960-ad08-83f809f17fb7.png">

5. 输入Api Name，注意：（1）Api Name没有正确翻译 （2）无输入名称的字段
6. 点击提交，提示错误“必需填写流程名”。

**Comment by hotlong** [comment]
请升级到最新版试一下，或提供错误发生的版本号。

**Comment by kemen209** [comment]
v2.2.25中已修复
