### ISSUE TITLE
客户端访问时，点击附件链接，自动下载并打开。（类似审批王）

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#2990]
检测到桌面客户端运行环境，重写这个函数。
SteedosUI.downloadFile({download_url, file_name, file_size, object_name, record_id, file_id})
SteedosUI.previewFile({download_url, file_name, file_size, object_name, record_id, file_id})

frontend 项目提供这个函数的默认版本，始终调用这个函数。

https://www.delftstack.com/howto/javascript/javascript-download/

**Comment by Flyingliao** [comment]
[039a35620dce890bb9958a258d09f8038b618485](https://github.com/steedos/steedos-frontend/commit/039a35620dce890bb9958a258d09f8038b618485)
