### ISSUE TITLE
系统页面水印功能

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3018]
- 华炎魔方列表、详情页、审批王表单页面
- 水印格式：例如部门+人员+当前时间，动态显示
- 按照开发工作量最小思路确认实现方案

**Comment by yinlianghui** [comment]
大致方案是先把文字转为data urls，然后用css的background显示为背景图。
#### 文字转data urls
https://stackoverflow.com/questions/12328714/convert-text-to-image-using-javascript
https://www.google.com.hk/search?q=javascript+convert+text+to+image+for+background&newwindow=1&ei=IJpWYvrMDI6fkPIPlr2f4Ao&ved=0ahUKEwj63JeK35D3AhWOD0QIHZbeB6wQ4dUDCA4&uact=5&oq=javascript+convert+text+to+image+for+background&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQtk5Y7Wtgs21oAXABeACAAeoDiAGOFpIBBzItNS4zLjGYAQCgAQHIAQrAAQE&sclient=gws-wiz

#### data urls 显示为css背景
https://css-tricks.com/data-uris/

**Comment by yinlianghui** [comment]
> 大致方案是先把文字转为data urls，然后用css的background显示为背景图。
> 
> #### 文字转data urls
> https://stackoverflow.com/questions/12328714/convert-text-to-image-using-javascript https://www.google.com.hk/search?q=javascript+convert+text+to+image+for+background&newwindow=1&ei=IJpWYvrMDI6fkPIPlr2f4Ao&ved=0ahUKEwj63JeK35D3AhWOD0QIHZbeB6wQ4dUDCA4&uact=5&oq=javascript+convert+text+to+image+for+background&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQtk5Y7Wtgs21oAXABeACAAeoDiAGOFpIBBzItNS4zLjGYAQCgAQHIAQrAAQE&sclient=gws-wiz
> 
> #### data urls 显示为css背景
> https://css-tricks.com/data-uris/

参考上述文档，经测试以下代码输出的dataurl加到div的css background属性中可以显示出来。
```
var tCtx = document.getElementById('textCanvas').getContext('2d');
var text = "上海华炎软件特技有限公司";
tCtx.canvas.width = tCtx.measureText(text).width;
tCtx.fillText(text, 0, 10);
var dataURL = tCtx.canvas.toDataURL();
console.log(dataURL);
```

**Comment by yinlianghui** [comment]
要满屏的话，只能找到每个页面具体的区域，定位相关div的背景了，具体有以下界面要对：
- 列表表格
- 记录详细界面表单
- 记录详细界面子表
- 审批王界面表单及列表
- 如果统一的顶部也要加背景的话也要单独处理

**Comment by hotlong** [comment]
这个不应该改具体的页面，否则页面调整还要改水印。应该单独加在一个铺满全屏的div 上。

**Comment by hotlong** [comment]
用这个就行 https://github.com/saucxs/watermark-dom
<img width="1422" alt="企业微信截图_11504347-e364-4aea-90bd-8d7822e5c78d" src="https://user-images.githubusercontent.com/50353452/163307689-aa3619eb-9a00-4df4-8418-91fd790ae631.png">
