### ISSUE TITLE
对象API名称更改，该对象原有的数据都查看不到了

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3039]

**Comment by hotlong** [comment]
Salesforce 对象改名后，虽然有各种问题，但原来的数据还都在。

**Comment by sunhaolin** [comment]
- [ ] 对象本身的数据迁移
- [ ] 对象相关子表的数据迁移：

**Comment by yinlianghui** [comment]
sf规则见：对象改名规则设计 #3068
关于相关表数据迁移：
- 数据库中相关表/子表记录的字段名没变化的，要处理的是元数据的reference_to属性改为新的名称。
- 不过有一种情况下要迁移lookup/mater_detail字段在记录中的数据，那就是reference_to本身是数组的时候，就像任务对象的"相关项"属性一样，字段值中记录了对象名称。
