### ISSUE TITLE
在线预览PDF文件、Office文件

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#304]
附件链接旁边增加一个预览按钮，包括审批王和creator

PDF 用 https://github.com/mozilla/pdf.js
PDF.js 可以考虑上传到 oss
Office文件用 https://view.officeapps.live.com/op/view.aspx?src={url}
私有云环境可以考虑用Office Online Server

写一个在线预览服务的接口，根据 steedos-config.yml 中配置，跳转到对应的URL

**Comment by chenzhipei** [comment]
#513 类似任务
