### ISSUE TITLE
列表视图排序问题

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#3086]
如图，
![image](https://user-images.githubusercontent.com/34770813/163973918-9dabb3f4-3d27-46a5-85af-7f40fb800d7a.png)

设置根据显示序号升序，当升序序号字段在该列表视图中显示时候，无bug。
![image](https://user-images.githubusercontent.com/34770813/163974107-5c5cc419-d698-4e06-b5ca-a1258685fdd9.png)

当升序序号字段在该列表视图中隐藏时候，无法排序。
![image](https://user-images.githubusercontent.com/34770813/163974262-465f74a8-3248-4a1e-a8ed-53e6b9b6b170.png)

**Comment by yinlianghui** [comment]
说是隐藏后没有触发排序功能条件。
![wecom-temp-fc0c19a907ff1d2572e887bd58fa70de](https://user-images.githubusercontent.com/6219465/163990513-1fe42284-b655-46a7-a795-f8cf31b3a37e.png)

**Comment by Flyingliao** [comment]
sf 在界面上除了点击列表头进行排序，没有对列字段进行设置排序。

**Comment by hotlong** [comment]
这个问题转给 @baozhoutao 下周处理

**Comment by baozhoutao** [comment]
方案:
如果从组件上获取到了排序规则,则使用组件的排序规则
如果没有获取到,则使用listview的排序规则
