### ISSUE TITLE
导入数据模块，相关表字段选择关联对象的key为文本时，导入到Excel对应列填写为纯数字，无法导入

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#3095]
如题，该情形下，会报错:无法查找到相关表数据，实际是mongodb数字作为条件查询时返回结果为空
![1729f1db442496bfdc54e3926c1a8b5](https://user-images.githubusercontent.com/62589030/164018407-5bc62d2a-03b7-4342-a861-6731f5d29fc0.png)
建议修改如下：
![image](https://user-images.githubusercontent.com/62589030/164018565-53acdde9-305c-4027-b9f4-5d69679d8c7d.png)

**Comment by hotlong** [comment]
方便的话，可以提交 pull request 的

**Comment by CarlWhite2020** [comment]
> 方便的话，可以提交 pull request 的

已经移交pull request。
