### ISSUE TITLE
2.2版本 列表视图中自动编号（name）字段不显示

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3107]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/26241897/164187186-01b1e3a0-645a-4d79-9823-74ac628906d4.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26241897/164187340-1595ff6f-546d-484a-82c4-9b950d5e98ae.png">

**Comment by Flyingliao** [comment]
正常测试是正常的，
<img width="974" alt="image" src="https://user-images.githubusercontent.com/41402189/164238864-fdfb78e4-55df-4364-8ef4-146b07385d4c.png">

**Comment by lizhenghotoa** [comment]
是的，2.1版本上调整过name字段。那么历史的name字段升级到2.2版本后如何处理？

**Comment by yinlianghui** [comment]
初步排查下来是字段权限的问题，uiSchema接口没有返回相关字段的定义，不只是自动编号字段没显示，而且给列表视图加一个“创建人”字段也没有显示出来。
等以下字段权限相关问题处理完成后再来测试确认下这个问题：
- 自定义对象的字段权限列表出现很多重复记录了 #3246
- 低代码对象的对象设置界面上的对象权限子表上的序号点击进去不对，始终进了物料类型这个对象的对象权限界面 #3244
