### ISSUE TITLE
@steedos-labs/sensitive-words-scan软件包校验敏感信息错误

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3122]
![image](https://user-images.githubusercontent.com/26241897/164467694-d0e6df04-1d37-4366-9cec-57422f3b52e6.png)
![image](https://user-images.githubusercontent.com/26241897/164467936-649e87f5-7c58-4d53-b27d-5d6cc85fcab4.png)

**Comment by baozhoutao** [comment]
类似问题均是由提供的词库导致
