### ISSUE TITLE
service中的resetaction卸载未生效

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#3125]
- 场景： 页面升级软件包后，软件包中的service.js里定义的actions未按照新的代码逻辑生效。
- 推测：软件包停用时软件包里的xxx.service.js服务没销毁、require 缓存

**Comment by baozhoutao** [comment]
问题原因: broker.loadService(servicePath) 函数存在缓存问题, 其加载文件时, 使用了require, 且未清理缓存

mo 只在热启动时,会清理require缓存: clearRequireCache(filename);

**Comment by baozhoutao** [comment]
objectql 新增函数: 
- clearRequireCache(filename): 清理require.cache;
- loadService(broker, filename): 清理require.cache, return broker.loadService(filename);
