### ISSUE TITLE
gitlab上默认master分支steedos-project-template项目gitpod启动不了

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3129]
![image](https://user-images.githubusercontent.com/26241897/164611352-af520aa4-3d40-4539-9eee-efff827437ca.png)

**Comment by hotlong** [comment]
哪个分支？

**Comment by hotlong** [comment]
优先的任务请加到：华炎优先任务看板 项目

**Comment by hotlong** [comment]
我刚开的项目没问题
