### ISSUE TITLE
对象权限配置界面的字段权限子表中点击字段名称链接会报错，进不了详细界面

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3149]
2.1和2.2都有这个问题
![image](https://user-images.githubusercontent.com/6219465/164969531-b3e6cda6-ddd9-49e6-be1a-14e0b4d136d7.png)

**Comment by Flyingliao** [comment]
因为在字段权限中 字段 保存的是name， 所以该链接肯定是无效的。
<img width="430" alt="image" src="https://user-images.githubusercontent.com/41402189/165452165-6e2ae7bb-ca79-435a-9b1d-559eb01d80f3.png">
