### ISSUE TITLE
合同管理-》无法上传合同附件

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#3152]
步骤：
内部系统（即大家在用的办公系统）-》合同管理-》新建一条合同-》选择所建的合同，上传附件

测试问题：
无法上传，界面报错

![上传附件报错](https://user-images.githubusercontent.com/92509428/164973178-dca101e7-c124-4ba3-ba35-ead1cf6f95ba.png)

**Comment by hotlong** [comment]
需提供浏览器或服务端控制台的具体报错信息。

**Comment by hotlong** [comment]
刚测试了，可以上传
