### ISSUE TITLE
需要增加base级别的beforeInsert触发器给字段赋默认值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3166]
- 只需要beforeInsert，不需要beforeUpdate触发器，因为默认值只跟新建记录有关，编辑记录时不管默认值
- 不强求object或gird类型的字段中的子字段默认值
- 默认值公式尽量兼容老的`{user}`语法，包括前端表单公式比如`{{global.user.name}}`
- 默认值公式只需要支持引用当前用户信息就行，不需要像公式字段一样支持引用表单上的字段
- 不支持配置为function的默认值，以前配置为function的地方手动改为公式字段那种公式格式

**Comment by baozhoutao** [comment]
- [ ] 非关系数据库对象的默认值
- [ ] 关系数据库对象的默认值

**Comment by yinlianghui** [comment]
因为内核对象，即meteorMongo数据源的对象上的字段如果配置了默认值，那么会在服务端赋值，所以只能先作废原来的服务端默认值，关联issue: 服务端默认值功能完全作废 #1940

**Comment by yinlianghui** [comment]
默认值已添加base触发器并按以下规则处理：
1.不支持function，会被忽略
2.已兼容大部分老的{user}语法，包括前端表单公式比如{{global.user.name}}，但是复杂的语法无法兼容
3.object或gird类型字段中写的默认值会被忽略
4.默认值公式中支持的全局变量只有$user，跟公式字段是一样的，指向了space_user
5.遇到代码写的非字符串默认值时会把默认值直接保存到记录中，而不是运行公式引擎，包括boolean、数值、数组
6.需要注意的事，默认值公式与公式字段一样不支持返回类型为数组的值
7.公式字段中还没有支持time类型，但是默认值中已经支持了，写法为TIMEVALUE(xxx)

**Comment by yinlianghui** [comment]
外部数据源如果是mongoDB的话，已经处理并测试通过了，关系型数据库未测试确认。

**Comment by yinlianghui** [comment]
总结：现在字段默认值分前端和后台两种公式写法，如果字段只读则只能配置后台字段公式那种语法，因为前端不会把只读字段提交到服务端，如果字段非只读应该配置为前端表单公式这种语法。

后续会把整个默认值迁移到服务端运行，相关issue：参考sf字段默认值计算迁移到服务端按公式处理 #3164
