### ISSUE TITLE
记录详细界面删除记录时控制台会报错，似乎不影响使用

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3168]
![image](https://user-images.githubusercontent.com/6219465/165217863-35a33eb8-6c1f-4a4e-8302-e0bc70cd3420.png)

**Comment by Flyingliao** [comment]
没排查到哪块代码导致的。
原因：删除记录后有地方又查询了此记录导致报错
![image](https://user-images.githubusercontent.com/41402189/165534962-9dd5f0ee-fac1-4db2-b430-1942f9dfc3d8.png)

**Comment by yinlianghui** [comment]
无法重现了
