### ISSUE TITLE
列表视图用代码配置filters为函数时deploy会报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3176]
- 2.1版本估计就有这个问题，需要确认下2.1和2.2最新版本是不是有问题
- 该问题是社区群中客户发现的，他因为deploy报错，所以尝试改为filtersFunction，但是我们目前列表视图完全不支持filtersFunction属性
<img width="548" alt="image" src="https://user-images.githubusercontent.com/6219465/165433200-a34a15fe-2278-4ef6-b32a-f4fd7a31cb80.png">

**Comment by baozhoutao** [comment]
deploy 时, 不支持 filters 为 Function. deploy 对此属性做了特殊判断.
deploy Function后, 列表右侧过滤面板无法识别Function格式, 也无法编辑.

**Comment by yinlianghui** [comment]
以后有遇到需要deploy的需求再说，没有细问那边为什么需要deploy。

**Comment by yinlianghui** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6219465/167826638-51471dd7-8e8c-44c4-b126-4d67896278dc.png">
