### ISSUE TITLE
user简档权限调整

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3177]
- [x] 权限集：目前可以查看自己创建的和查看所有记录，调整为删掉user权限；
- [x] 共享/限制规则：目前为增删改查自己创建的记录，调整为删掉user权限；
- [x] 公告：增删改查自己的创建的记录、还可以查所有记录，需要结合创建公告时的发布对象进行权限调整；
- [ ] 附件：增删改查自己创建的记录、查所有记录，权限调整需讨论；
- [ ] 附件版本：删查自己创建的记录、查所有记录，权限调整需讨论；

**Comment by hotlong** [comment]
关于附件的问题，目前我们有一些需求是需要匿名下载附件的，比如我们的官网显示图片。

**Comment by baozhoutao** [comment]
公告对象权限调整: 
新建:  保持现状(profile == user | admin 可以新建)
查看:  现状时可查看所有, 调整为可查看自己创建及 在发布对象中的记录.
编辑、删除: 保持现状(profile == user 可编辑; 删除自己的 profile == admin 可编辑、删除所有 )

**Comment by baozhoutao** [comment]
附件、附件版本 权限暂不调整
