### ISSUE TITLE
跑apps下的contracts项目，部门页面进入不了流程设计器

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#319]
（1）设置》流程，点右上按钮“流程设计器”报错
（2）设置》流程，点具体某个流程最右侧的“流程设计器”报错
（3）设置》流程，点进具体某个流程的详情页，右上的“流程设计器”点击正常
（4）收件箱/发件箱等处，流程图，点击也有类似报错

**Comment by yinlianghui** [comment]
经排查，是platform项目中的server/bundle中有个lib文件夹被github忽略造成的（里面有jquery-1.11.2.min.js文件），以后流程设计器在项目中用就行，不处理
