### ISSUE TITLE
外部数据源为关系型数据库时默认值公式相关功能确认

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3190]
关联issue:需要增加base级别的beforeInsert触发器给字段赋默认值 #3166

**Comment by sunhaolin** [comment]
使用绑定mysql数据源对象测试：
- [x] 字段默认值配置为 `{{global.user.name}}` 
- [x] 字段默认值配置为 `CASE($user.name,​​ "1", "1", "2", "2", "xxx")`， 且字段权限配置不可编辑
