### ISSUE TITLE
软件包清单的显示规则是什么？内置软件包不应该显示

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3196]
![image](https://user-images.githubusercontent.com/50353452/166220238-76a1d77c-28ae-404a-9ca7-5b7e45cf00ab.png)

**Comment by baozhoutao** [comment]
mixins @steedos/service-package-loader 的 service 默认会显示在软件包列表.
可通过设置 service settings.packageInfo.isPackage = false 控制将其不显示在软件包列表.

**Comment by hotlong** [comment]
有参数就可以，就用这个参数好了。
