### ISSUE TITLE
记录详细界面的子表列表过滤条件应该只包含主表记录id的过滤条件，而不应该把子表关联对象的all视图中配置的过滤条件也带上

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3203]
### sf的规则：
给主表对象记录详细界面配置Lighting应用程序，把子表拖进去，实测保存后前台记录详细界面上并不会把子表关联对象的all视图中配置的过滤条件也带上。

### 华炎2.2分支现状
- 两个自定义对象A和B，B为A的子表，给B的all视图配置过滤条件后，可以在主表对象A的记录详细界面的network请求中看到B子表的过滤条件额外带上了all视图的过滤条件。
- 主表A对象下的“任务”子表列表上可以看到network请求中并没有带上“任务”对象all视图的过滤条件，这跟自定义对象B子表表现不一样。

**Comment by hotlong** [comment]
不改变现状
