### ISSUE TITLE
odata 改造 graphql 问题汇总

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3219]
- [x] - 点击进入自定义页面详情页，控制台报错：message: "Cannot query field \"is_system\" on type \"page_versions\"."
- [x] - 报错信息应该在界面右上角弹出
- [x] - 点击进入图表详情页，控制台未报错，界面显示：似乎出现了一个问题。
- [x] 我们无法找到您尝试访问的记录。此记录可能已被其他用户删除，或您没有此记录的访问权限，也可能发生了系统错误。请向您的管理员寻求帮助。
- [x] - 部门管理，部门列表未显示
- [x] - 新增部门，选择上级部门时显示为ID

**Comment by baozhoutao** [comment]
bbdf469c97b4cbebf4dd7335d438b3000d1a0749
