### ISSUE TITLE
graphql 优化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3232]
- 生产环境 disable IntrospectionQuery: https://www.apollographql.com/blog/graphql/security/why-you-should-disable-graphql-introspection-in-production/
- 生产环境禁用 extensions: tracing，目前每个graphql接口都会返回很多数据。

**Comment by sunhaolin** [comment]
生产环境 disable IntrospectionQuery 由于frontend中使用此接口用于校验对象查询shcema（如列表视图中存在已删除的字段）故暂不移除；待后期优化uiShema接口
