### ISSUE TITLE
国际化，Meteor.Error修正

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#324]
throw new Meteor.Error(400, "space_users_error_user_exists");
应改为
throw new Meteor.Error(400, t("space_users_error_user_exists"));

否则
![image](https://user-images.githubusercontent.com/7553007/82192122-219d8600-9926-11ea-8e93-b1b3048e2efb.png)

**Comment by yinlianghui** [comment]
无法重现了，可能当时电脑卡吧
