### ISSUE TITLE
低代码对象的对象设置界面上的对象权限子表上的序号点击进去不对，始终进了物料类型这个对象的对象权限界面

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3244]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/6219465/167558057-eef96272-80e8-471c-b552-3b628df350ff.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/6219465/167558440-e35cf7e7-58ed-4cc5-8afa-d1075a3ce1ec.png">

**Comment by yinlianghui** [comment]
我跑的是platform的2.2分支最新代码

**Comment by yinlianghui** [comment]
发现自定义对象没有这个问题，应该是内置对象都有这个问题

**Comment by Flyingliao** [comment]
1、只有内置对象 才有这个问题。
2、接口返回有误；显示更是错了。 下图中所属对象 是 物料类型。
<img width="936" alt="image" src="https://user-images.githubusercontent.com/41402189/167569843-a5005d84-1819-4c95-989f-7e896b8a01f4.png">

**Comment by baozhoutao** [comment]
排查所有元数据对象的trigger, 调整为使用metadata driver 处理数据
