### ISSUE TITLE
新建“角色”后再编辑时“上级角色”不可以选中当前角色

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3245]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/41402189/167559430-b84a440e-26bd-4c24-9ff7-17bface7ce7f.png">

可以参照 部门 对象中的“上级部门”字段。

**Comment by hotlong** [comment]
服务端加一个触发器校验一下，包括避免循环引用
