### ISSUE TITLE
自定义对象的字段权限列表出现很多重复记录了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3246]
跑的是platform2.2分支最新代码。
<img width="771" alt="image" src="https://user-images.githubusercontent.com/6219465/167559653-637225a2-2870-451c-98e2-6e60e5f4ef5c.png">

**Comment by Flyingliao** [comment]
之前 请求的是 permission_fields，  现在是 graphql .

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/41402189/167561908-851874c3-9eaf-446b-9f52-221975be25fe.png">
