### ISSUE TITLE
树形对象，创建记录时默认的children字段不应该显示

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3247]
![image](https://user-images.githubusercontent.com/26241897/167571600-37425cb8-d09e-4f8c-83eb-b1159fe95dd8.png)

**Comment by yinlianghui** [comment]
这个测试确认下最新代码就行，已经修正过了

**Comment by Flyingliao** [comment]
该字段只读/编辑都设置隐藏了。
位置：object.tree.js
