### ISSUE TITLE
应用选项卡编辑时默认为空记录

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3250]
![image](https://user-images.githubusercontent.com/26241897/167582713-f364d4b6-b4f3-4010-93aa-2d76c9acbdb4.png)

**Comment by Flyingliao** [comment]
1、2.2分支最新版本无此bug。
2、原因：lookup字段，多选， 数据库中保存null造成的，清空保存 或 升级到最新版本即可。
