### ISSUE TITLE
用户users表中对guest_users权限集显示“无此记录”

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#3274]
版本：
v2.2.31，通过gitpod运行template项目，通过管理员登录。

在用户users表中的详情页的“对象权限”显示了一条“无此记录”的记录：
<img width="1248" alt="Screen Shot 2022-05-15 at 13 01 43" src="https://user-images.githubusercontent.com/5885946/168458117-c0e7dbd7-61c6-4636-9bd6-0b22fcb8ba7a.png">

（1） 点击["无此记录"]显示：
<img width="1140" alt="Screen Shot 2022-05-15 at 13 07 37" src="https://user-images.githubusercontent.com/5885946/168458129-3c141a9c-ee83-4308-9bdc-396e78a30e9e.png">

（2）点击数字1，显示：
<img width="1281" alt="Screen Shot 2022-05-15 at 13 01 56" src="https://user-images.githubusercontent.com/5885946/168458056-819f55cb-fd45-4cdf-bd34-75a0dd193729.png">

**Comment by hotlong** [comment]
平台中已无此权限集
