### ISSUE TITLE
审批王页面没有正确显示日期

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#3275]
版本： v2.2.31

本地系统的语言为English

在审批页面显示：
<img width="680" alt="Screen Shot 2022-05-15 at 22 30 46" src="https://user-images.githubusercontent.com/5885946/168478449-7fec2dbb-ad35-4266-97fa-1cf0cf7cd838.png">

在列表页面能够正确显示：
<img width="375" alt="Screen Shot 2022-05-15 at 22 39 58" src="https://user-images.githubusercontent.com/5885946/168478570-4d921046-64de-47ef-90bd-975d7a66f771.png">

**Comment by hotlong** [comment]
这两个字段是从对象同步过来的吗？

**Comment by kemen209** [comment]
@hotlong 是的。
