### ISSUE TITLE
无法单独编辑对象权限

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#3276]
版本：v2.2.31

（1）
单独编辑对象权限会提示“权限集不能为空”
<img width="1113" alt="Screen Shot 2022-05-15 at 22 41 42" src="https://user-images.githubusercontent.com/5885946/168478745-66f96994-f749-4f08-8c96-faf2ccf2f7de.png">

（2）通过列表编辑时成功：
<img width="1113" alt="Screen Shot 2022-05-15 at 22 41 42" src="https://user-images.githubusercontent.com/5885946/168478786-00aff983-1837-4714-bde5-e335e6146b76.png">

**Comment by hotlong** [comment]
考虑改为禁止快速编辑

**Comment by baozhoutao** [comment]
程序bug , 已修复. 可以继续使用单字段编辑功能.
