### ISSUE TITLE
部分内置对象的触发器无法扩展

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3279]
- 只有通过重启软件包才能让触发器生效，而且生效后再次重启服务又会失效
- 测试的是beforeInsert/beforeUpdate触发器
- 版本是2.1.107

**Comment by baozhoutao** [comment]
需要将 Creator.Objects['xxx'].triggers = {...} 调整为 Creator.Objects['xxx'].triggers = Object.assign({}, Creator.Objects['xxx'].triggers, {...})
