### ISSUE TITLE
2.2分支 样式bug：配置仪表盘页面两个按钮看不到

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3285]
**只读界面：**
之前： 鼠标移到右上角位置 出现 三个点 的按钮
现在：不会出现，但是点击该位置功能正常，疑似样式问题
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/41402189/168729601-bad52be2-6cda-4d9b-bfae-beecd80be6f9.png">

**编辑界面：**
之前：鼠标移到右上角左边位置 出现 三个点 的按钮； 右上角位置一直有 关闭 按钮。
现在： 都不显示，但是点击该位置功能正常，疑似样式问题
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/41402189/168729807-3a6c12e1-497f-4e35-bd6e-8b3e29dd0619.png">

**Comment by hotlong** [comment]
仪表盘不再维护
