### ISSUE TITLE
避免跨站脚本攻击（xss）

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#3291]
跨站脚本（Cross Site Scripting）攻击是指在远程WEB页面的HTML代码中手插入恶意的JavaScript、VBScript、ActiveX、HTML或Flash等脚本，窃取浏览此页面的用户的隐私，改变用户的设置，破坏用户的数据。跨站脚本攻击在多数情况下不会对服务器和WEB程序的运行造成影响，但对客户端的安全构成严重的威胁。
漏洞位置：
https://test.trial.steedos.com:8443/app/admin/web_forms/grid/all
https://test.trial.steedos.com:8443/app/admin/space_users/grid/all
https://test.trial.steedos.com:8443/app/-/project_task/view/627cc71df3df2416e43e7e22

<img width="321" alt="image" src="https://user-images.githubusercontent.com/15027092/169033676-72efdf6e-dc64-4f04-b1cd-5b36f182f5b5.png">

<img width="321" alt="image" src="https://user-images.githubusercontent.com/15027092/169033702-254d7709-1b04-4b4c-8a49-b5cc9a8d3f2a.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/15027092/169033754-b4014ca7-9e26-48bb-b61e-d58df6f0519b.png">

1、设置选项，在高级设置处，选择在线表单，新建表单，名称和返回地址中插入<img src=""onerror="alert('xss')">
2、创建人员处，选择部门处，部门设置名称插入<img src=""onerror="alert('xss')">，选中此部门，可触发xss弹窗
3、在项目应用程序，项目任务当中，选择一项项目任务，在留言处插入<img src=""onerror="alert('xss')">

**Comment by hotlong** [comment]
黑名单关键词库新增 onerror, alert(
