### ISSUE TITLE
敏感文件泄露

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#3292]
web应用的程序文件、配置文件、日志文件、备份文件及数据库文件泄漏。
漏洞位置：
https://test.trial.steedos.com:8443/unpkg.com/axios/package.json

<img width="322" alt="image" src="https://user-images.githubusercontent.com/15027092/169034187-015c5f53-78da-4658-96a5-d2d108e891c9.png">

修复建议：
1）控制敏感文件的访问权限；
2）删除不必要的测试文件、备份文件等。

**Comment by hotlong** [comment]
unpkg.com/axios/package.json 下都是 npm 公开发布的软件包，不存在泄露
