### ISSUE TITLE
上传图片格式不对，导致服务器停止

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#3293]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/15027092/169034466-48f88ded-70dc-467d-ba48-71f06e36d888.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/15027092/169034498-d0b7c99f-87f6-4c08-8af9-7c9d59fd72df.png">
上传空白内容png，格式不对导致服务停止

修复建议：
1）将文件上传目录直接设置为不可执行，对于Linux而言，撤销其目录的'x'权限； 
2）文件类型检查：强烈推荐白名单方式，结合MIME Type、后缀检查等方式（即只允许允许的文件类型进行上传）；此外对于图片的处理可以使用压缩函数或resize函数，处理图片的同时破坏其包含的HTML代码；
3）使用随机数改写文件名和文件路径，使得用户不能轻易访问自己上传的文件；
4）单独设置文件服务器的域名。

**Comment by hotlong** [comment]
测试确认具体报错

**Comment by chenzhipei** [comment]
```
Error: FS.Collection insert: file does not pass collection filters
    at Object.FS.Utility.handleError (meteor://💻app/packages/steedos:cfs-base-package/base-common.js:130:33)
    at checkAndInsert (packages/steedos_cfs-collection.js:287:25)
    at FS.Collection.insert (packages/steedos_cfs-collection.js:323:12)
    at next (meteor://💻app/packages/steedos_creator/server/routes/s3.coffee:125:16)
    at meteor://💻app/packages/steedos_api/parse_files.coffee:36:5
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sunhaolin** [comment]
上传接口重写后已无此问题
