### ISSUE TITLE
任意文件上传

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#3294]
任意文件上传漏洞是指用户上传了一个可执行的脚本文件，并通过此脚本文件获得了执行服务器端命令的能力。
漏洞位置：
https://test.trial.steedos.com:8443/app/contracts/contracts/grid/all
https://test.trial.steedos.com:8443/app/contracts/accounts/grid/all
https://test.trial.steedos.com:8443/app/contracts/tasks/grid/all
https://test.trial.steedos.com:8443/app/projects/project_program/grid/all
https://test.trial.steedos.com:8443/app/projects/project/grid/all
https://test.trial.steedos.com:8443/app/projects/project_milestone/grid/all

<img width="313" alt="image" src="https://user-images.githubusercontent.com/15027092/169034822-28b805d0-2739-4cc1-8dad-582b8c3c5786.png">

修复建议：
1）将文件上传目录直接设置为不可执行，对于Linux而言，撤销其目录的'x'权限； 
2）文件类型检查：强烈推荐白名单方式，结合MIME Type、后缀检查等方式（即只允许允许的文件类型进行上传）；此外对于图片的处理可以使用压缩函数或resize函数，处理图片的同时破坏其包含的HTML代码；
3）使用随机数改写文件名和文件路径，使得用户不能轻易访问自己上传的文件；
单独设置文件服务器的域名。

**Comment by hotlong** [comment]
配置文件保存在s3服务可以避免此问题
