### ISSUE TITLE
页面布局中，“操作”显示条件中表单公式抛出异常

### ISSUE THREAD

**Issue by kemen209** [steedos/steedos-platform#3302]
页面布局，“操作”显示条件中表单公式抛出异常，但“字段”对应的显示条件中的表单公式工作正常。

版本：v2.2.31，通过gitpod启动的template project；
     v2.2.34，本地docker环境；

（1）相同公式设置
<img width="1313" alt="Screen Shot 2022-05-19 at 10 46 16" src="https://user-images.githubusercontent.com/5885946/169310346-7e08302d-e0b2-4005-a73a-98c3d60ea990.png">

（2）浏览器端输出，“操作”部分抛出了Unexceptd token异常，“字段”部分正常输出：
<img width="1529" alt="Screen Shot 2022-05-19 at 10 46 03" src="https://user-images.githubusercontent.com/5885946/169310206-f09477d3-bc4b-4c38-b6f8-268f5363b6a7.png">

**Comment by yinlianghui** [comment]
重复任务：https://github.com/steedos/steedos-platform/issues/3340
