### ISSUE TITLE
对象一建生成流程后启用流程页面报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3306]
![image](https://user-images.githubusercontent.com/26241897/169459457-a8a3547c-9025-4a94-b5e5-a4796b337941.png)

![image](https://user-images.githubusercontent.com/26241897/169459497-1fc64de5-3179-4ea7-85be-47e99740675a.png)

**Comment by sunhaolin** [comment]
`Service '@responsible_area__c%7D' is not registered.`
decodeURIComponent("%7D") 后得到 "}"
对象名为 `responsible_area__c}`  ？
