### ISSUE TITLE
自定义主页及redash的page等界面没有识别url上的hidden_header参数隐藏界面顶部的功能

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3307]
目前只有列表视图界面识别了hidden_header会隐藏界面顶部。
还有以下界面需要支持该功能：

- [ ] 自定义主页
- [ ] 自定义page，包括amins和redash等类型

<img width="730" alt="image" src="https://user-images.githubusercontent.com/6219465/169467539-6a45494a-e878-4ea2-896b-e6bccd592318.png">

<img width="844" alt="image" src="https://user-images.githubusercontent.com/6219465/169467213-c7bb2e26-a24c-4ce7-89af-34f3650fca90.png">

**Comment by hotlong** [comment]
不处理
