### ISSUE TITLE
有客户提到自定义简档下的用户无法创建自定义的视图

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3311]
他们应该用的是2.1的，所以2.1上应该也有这个问题。
![wecom-temp-4fa358e807f320ef5f189dbbcf06d178](https://user-images.githubusercontent.com/6219465/169525440-2bfda0a0-2777-4334-b59f-0d2dd93c6de2.png)

**Comment by hotlong** [comment]
应该是没有配置对象权限，这个有相关任务
