### ISSUE TITLE
手机端页面优化：列表视图、表单详情

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3317]

**Comment by yinlianghui** [comment]
手机端列表视图组件暂停开发，无法集成原来的手机端List组件到amins中，因为它依赖了redux store。
ant design 用List 组件可以参考 https://ant.design/components/list-cn/ ，有一个示例是调用的 https://github.com/ankeetmaini/react-infinite-scroll-component 组件，这个组件说是支持上拉刷新下拉加载更多。
