### ISSUE TITLE
使用 amis 配置工作台，替代现有首页

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3321]
- 待审核文件（审批王）
- 应用清单
- 待审核文件（批准过程）
- 公告通知
- 待办任务
- 今日日程

**Comment by Flyingliao** [comment]
1、样式覆盖
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/41402189/172360522-039c92a7-d09d-4b4c-8f61-3c14ed0589ea.png">

**Comment by Flyingliao** [comment]
这个界面上调不了
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/41402189/172755473-cda34c7d-1845-4611-8c8c-0fbde39219a0.png">
