### ISSUE TITLE
公式字段配置相关表的选择框或者数值类型字段，新建数据时报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3324]
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/26241897/169931017-ed41867d-a836-465f-87ba-3f412e785127.png">

**Comment by yinlianghui** [comment]
需要进行数值转换，比如下拉框需要使用TEXT函数转换 TEXT(xft_travel__c.xft_type__c)。
参考文档：https://www.steedos.com/docs/admin/formula#%E4%BD%BF%E7%94%A8%E9%80%89%E9%A1%B9%E5%88%97%E8%A1%A8%E5%85%AC%E5%BC%8F%E5%AD%97%E6%AE%B5%E7%9A%84%E6%8F%90%E7%A4%BA
