### ISSUE TITLE
删除对象现在是真删除，删除后服务端会出现一些错误日志

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3325]
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/6219465/169935204-9a3c1314-9789-4ae9-bb72-004c04dc92c1.png">

**Comment by hotlong** [comment]
emoveObject test__c
(node:5951) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'permission_set_id' of undefined
    at Service.<anonymous> (/workspace/steedos-platform/services/service-metadata-server/src/permissionFieldsService.ts:45:97)
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/steedos-platform/node_modules/tslib/tslib.js:115:62)
    at /workspace/steedos-platform/node_modules/meteor-promise/fiber_pool.js:43:39
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:5951) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 12)
(node:5951) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'permission_set_id' of undefined
    at Service.<anonymous> (/workspace/steedos-platform/services/service-metadata-server/src/permissionFieldsService.ts:45:97)
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/steedos-platform/node_modules/tslib/tslib.js:115:62)
    at /workspace/steedos-platform/node_modules/meteor-promise/fiber_pool.js:43:39
(node:5951) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
warn: Not loaded. Invalid custom permission_objects ->  test.用户 test__c
warn: Not loaded. Invalid custom permission_objects ->  test.管理员 test__c

**Comment by sunhaolin** [comment]
2.3.0-beta.5 已无此问题
