### ISSUE TITLE
选择框类型字段在列表数据导出应该为显示值

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#3328]
现在的导出功能直接导出数据库中的值，有选择框这类的导出，无法匹配对应显示名称。
![微信图片_20220525103418](https://user-images.githubusercontent.com/34770813/170167786-52e44800-acd7-47df-b6a6-9a4576813e33.png)
![微信图片_20220525103427](https://user-images.githubusercontent.com/34770813/170167796-13de4399-41e5-431a-8de8-183da8f1d6ba.png)

**Comment by lizhenghotoa** [comment]
- 还可以延伸为主子表、相关表类型字段导出是否也要显示name值，而不是存到数据库的id；
- 是否需要加开关处理，还是统一默认导出为显示名称；

**Comment by hotlong** [comment]
salesforce 只有报表有导出功能，普通列表倒是不支持导出。

**Comment by hotlong** [comment]
列表视图导出的话，导出的内容应该和界面上看到的显示效果一样
