### ISSUE TITLE
审批栏文字大小不一致

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#333]
![image](https://user-images.githubusercontent.com/6194462/82729052-f6040c80-9d26-11ea-9308-3dbaed3ebab7.png)

问题平台: cn.steedos.com

**Comment by yinlianghui** [comment]
重复：申请单的审批栏文字大小不统一 #490

**Comment by hotlong** [comment]
没有考虑多人审批 
![image](https://user-images.githubusercontent.com/50353452/87216034-56e6b300-c36e-11ea-9475-5389d29993d1.png)

**Comment by hotlong** [comment]
需要测试手机、电脑、safari和chrome

**Comment by yinlianghui** [comment]
> 需要测试手机、电脑、safari和chrome

测试了手机客户端，华信客户端，chrome，safari，未发现字体大小异常问题了
