### ISSUE TITLE
参考sf在手机上记录详细界面子表不显示数据，点击进去后再跳转路由显示单独的子表

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3332]
![image](https://user-images.githubusercontent.com/6219465/170401836-d974dd51-2aec-4546-b893-065c8f92bec9.png)

**Comment by hotlong** [comment]
不考虑 amis 自定义页面

**Comment by hotlong** [comment]
计划 amis 重构手机端
