### ISSUE TITLE
审批王选择框类型字段应支持配置显示名称

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#3336]
配置界面，设置选项时，value和key写在一起，用`:`隔开

- 热:hot
- 冷:cool

显示界面识别一下

**Comment by yinlianghui** [comment]
测试要点：
- 单选和多选的下拉框字段类型，整体测试下审批王支持下拉框类型字段label配置的相关功能，包括暂存和申请单流转。
- 最好测试确认下流程与对象同步相关功能，看看字段值是不是能正常保存。
- 新建流程时绑定对象的话，需要测试下流程详细界面的“添加字段”按钮相关功能，看看给运行中的申请单添加一个下拉框类型的字段后，相关功能是否正常。
 
第三点有bug（2.2分支 流程对象中的“添加字段”按钮功能全坏了 #3580），待其修正后再测试。
