### ISSUE TITLE
选组控件参考目前原来老版本的选组写死了普通用户查看部门数据的权限，应该识别当前登录用户配置的对象权限来而不是写死

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3357]
选人控件也要确认下相关规则。
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/6219465/171348956-b699f371-0612-44c9-b4c7-4b25b55b8e4e.png">

**Comment by hotlong** [comment]
选部门控件去掉筛选，通过给组织配置限制规则来实现只查看本分部下的部门

**Comment by yinlianghui** [comment]
### 选组 

#### 改动说明：

移除了前端选组控件权限相关控制代码，只保留了`["hidden", "!=", true]`的过滤条件。
![image](https://user-images.githubusercontent.com/6219465/173474126-e9f83f8a-648a-4cb2-bd22-9beb628bcb7b.png)


#### 默认权限配置

原来 yml文件中的权限配置保持原样，表示默认情况下普通用户可以查看所有组织。
![image](https://user-images.githubusercontent.com/6219465/173474474-215725df-ded0-4a87-95d0-eef97f050298.png)

#### 改后如何通过权限配置实现原来前端组件一样的效果

前端改动后，现在默认是普通用户能看到所有部门数据，需要给部门对象配置限制规则来实现之前一样的效果：

- 指定条目条件：`{{$user.roles.indexOf('user') > -1}}`
- 记录过滤器:`{{[["_id", "=", $user.companies.map(function(n){return n.organization;})], "or", ["parents", "=",$user.companies.map(function(n){return n.organization;})]]}}`

### 选人 

#### 改动说明：

移除了前端选人控件权限相关控制代码，只保留了`["user_accepted", "=", true]`的过滤条件。
![image](https://user-images.githubusercontent.com/6219465/173475645-07bc662d-e6ff-4170-b16d-1f795a455108.png)

#### 默认权限配置

原来 yml文件中的权限配置保持原样，表示默认情况下普通用户只可以查看自己所属分部下的人员（且不能查看自己所属分部的子分部下的人员）。

![image](https://user-images.githubusercontent.com/6219465/173475980-b90932f1-0f5d-4888-a2b9-523ac244ceed.png)

#### 改后如何通过权限配置实现原来前端组件一样的效果

前端改动后，现在默认是普通用户只能看到自己所属分部下的人员，但是不能查看自己所属分部的子分部下的人员，需要给人员对象配置共享规则来实现之前一样的效果：

- 指定条目条件：`{{$user.roles.indexOf('user') > -1}}`
- 记录过滤器:`{{[["organizations_parents", "=", $user.companies.map(function(n){return n.organization;})]]}}`
