### ISSUE TITLE
页面: 应该把name字段显示为链接, 而不是 api_name

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3360]
估计是这个对象下的名称字段错了。
<img width="773" alt="image" src="https://user-images.githubusercontent.com/6219465/171540051-9d0577fe-14b3-4407-abbf-a20e61544bc8.png">

**Comment by Flyingliao** [comment]
和殷老师、庄总讨论结果： salesforce page是没有name的，  暂不修改。
