### ISSUE TITLE
在脚本中弹出ObjectForm，传入objectSchema属性时相关功能有bug

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3389]
#### 问题1：如果同时传入了objectApiName和objectSchema属性的话，把某个字段的hidden属性设置为true的话不生效，因为会取字段权限。
-  这是目前是会抓取objectApiName对应的schema并与传入的objectSchema拼接起来，而且是优先取了objectApiName对应的schema
- 讨论下来不应该拼接，而应该直接使用传入的objectSchema，需要确认来原来为什么要拼接而不是覆盖

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/6219465/172351682-493eb503-bba8-4285-b41e-b0f9a16b883f.png">

#### 问题2：如果同时传入了objectApiName和objectSchema属性的话，把某个字段的hidden属性设置为true的话不生效，因为会取字段权限。

- 这是因为目前如果传入了objectApiName的话，始终走objectApiName对应的字段权限了。
- 应该改为只要传入了objectSchema，就不额外走字段权限判断函数了，直接以传入的schema为准。
- 传入了objectApiName的话，不需要考虑recordId对应的记录级权限，始终以传入的schema为准，如果有记录级权限需求应该在传入objectSchema时处理，不在ObjectForm组件中处理。

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/6219465/172351893-70ba2325-fb31-455d-afc6-f089fcbbcec8.png">

#### 问题3：当传入了objectApiName和objectSchema属性，同时也传入了recordId属性的话规则如何？
待确认，拟定只要传入objectApiName就支持取recordId对应的record值，否则不抓取record记录值。

#### 问题4：不传入objectApiName，只传入objectSchema属性的话，点击保存按钮不会请求保存接口
拟定只有传入了objectApiName属性才让保存按钮功能生效，否则需要自己写onFinished函数代码实现保存记录功能。

**Comment by hotlong** [comment]
有哪个内核用到这些功能吗？

**Comment by hotlong** [comment]
原则上，后续类似的自定义功能可以利用 amis 表单实现。
