### ISSUE TITLE
列表记录进入详情页页面一直加载，控制台报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3415]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/173521202-89f6e342-d804-410b-94df-5319fbb23669.png">

**Comment by yinlianghui** [comment]
是缺少了依赖的软件包 `@steedos-labs/merchant`，安装上就行了。

**Comment by yinlianghui** [comment]
已经优化过相关代码会打出具体的找不到的对象api名称方便排查问题
