### ISSUE TITLE
项目启动时，很多不必要的提示，尽量都去掉

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#342]
(node:95232) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:95232) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
WARNING: npm peer requirements (for steedos:cfs-data-man) not installed:
 - mime@1.4.1 installed, mime@^2.0.2 needed

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

WARNING: npm peer requirements (for steedos:api) not installed:
 - huawei-push@>=0.0.6-0 not installed.

Read more about installing npm peer dependencies:
  http://guide.meteor.com/using-packages.html#peer-npm-dependencies

WARNING: not found plugin.config.yml /Users/steedos/Documents/GitHub/steedos-app-purchase/node_modules/@steedos/accounts/plugin.config.yml

You are using the default secret "secret" which is not secure.
Please change it with a strong random token.
WARNING: not found plugin.config.yml /Users/steedos/Documents/GitHub/steedos-app-purchase/node_modules/@steedos/accounts/plugin.config.yml

You are using the default secret "secret" which is not secure.
Please change it with a strong random token.
(node:95232) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.

**Comment by hotlong** [comment]
yarn debug 的提示，建议也只保留最后两行。

[nodemon] files triggering change check: src/purchase/purchase_quotations.object.yml
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] delaying restart for 3000ms
[nodemon] files triggering change check: src/purchase/purchase_quotations.zh-CN.i18n.yml
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] delaying restart for 3000ms
[nodemon] files triggering change check: src/purchase/purchase_requisitions.object.yml
[nodemon] matched rule: **/*.*
[nodemon] changes after filters (before/after): 1/1
[nodemon] delaying restart for 3000ms
[nodemon] restarting due to changes...
[nodemon] src/purchase/purchase_requisitions.object.yml

**Comment by sunhaolin** [comment]
DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
和
DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
是meteor1.8内核代码， 最新的meteor devel分支依然没有调整
