### ISSUE TITLE
新增环境变量，控制华炎魔方初始化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3445]
- [x] 初始化
- [x] 开发版初始化
- [ ] 升级企业版

## 初始化

```shell
- STEEDOS_TENANT_ENABLE_ACTIVATION=true # 显示初始化向导，默认不显示
- STEEDOS_TENANT_ENABLE_CREATE_TENANT=true # 允许自助创建企业
- STEEDOS_TENANT_ENABLE_REGISTER=true # 默认允许自助注册用户
```

- 无企业时，始终允许自助创建企业
- 无企业时，始终允许自助注册用户
- 服务端 tenant._id, 自动取第一个创建的企业
- 激活向导改为初始化向导

## 开发版初始化

```shell
- STEEDOS_TENANT_ENABLE_ACTIVATION=true 
```

使用云端账户自动初始化开发环境

## 升级企业版

- 运行企业版时，如果本地没有许可证，则提示用户注册许可证
- 客户注册云服务账户
- 输入本地魔方ID，创建我的魔方
- 在线购买企业版许可证
- 可申请企业版试用版许可证，1个月
- 复制激活码
- 本地激活企业版

## 与云服务绑定

如果有以下变量，表示与云服务绑定

```
- STEEDOS_CLOUD_SPACE_ID=
- STEEDOS_CLOUD_API_KEY=
```

- 如果未配置，不连私有NPM仓库

## 软件包初始化

```
STEEDOS_INITIAL_PACKAGES=@steedos-labs/oa@2.1,@steedos-labs/project # 系统启动时自动安装的软件包
STEEDOS_CLOUD_SYNC_PACKAGES=true # 是否从云端同步已购买软件包，安装最新版
```

## 企业版功能限制

- 前端判断
- 后端判断

**Comment by hotlong** [comment]
最新版 steedos-config.yml 
https://github.com/steedos/docker/blob/main/steedos-community/2.2/steedos-config.yml

tenant 相关环境变量还是来自配置文件

**Comment by hotlong** [comment]
按照最新的规则，以下变量已经失效了
```
STEEDOS_TENANT_ENABLE_REGISTER=true # 无企业时始终可以创建，有企业时已数据库中记录为准
STEEDOS_TENANT_ENABLE_FORGET_PASSWORD=true.  # 改为使用验证码登录
```

**Comment by sunhaolin** [comment]
企业版功能汇总 #3466
