### ISSUE TITLE
新增 build 脚本，更新对象的国际化文件

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3457]

**Comment by yinlianghui** [comment]
关联： 2.2 版本 steedos i18n命令无法正常使用 #3481

**Comment by yinlianghui** [comment]
需要参考软件包 `services/service-pages`的i18n命令，编写其他软件包的i18n命令并执行该命令生成翻译内容，主要包括以下软件包：
- `services/**`
- `steedos-packages/**`
- `packages/standard-objects`

**Comment by yinlianghui** [comment]
先关闭，自动化脚本暂时意义不大，以后再说
