### ISSUE TITLE
内核extend对象deploy后控制台报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3504]
- 页面字段无名称
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/26241897/175475279-dbaef5bf-9e68-491c-9b21-0bb908c96a53.png">

- deploy时的报错
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/26241897/175475124-7eb0bcab-f360-44db-ad5d-1c8c2573d2a3.png">

- 重启后对象报错
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/26241897/175475200-3607f69b-3e20-484b-8164-0a894d141f95.png">

**Comment by baozhoutao** [comment]
目前不支持extend对象deploy
