### ISSUE TITLE
graphql _display 同步现有所有字段类型

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#3508]
- [x] 图片，支持display和expand，见：graphql未能支持图片类型的expand和_display，但是附件类型支持 #3514
- [x] 附件，支持display和expand
- [x] 下拉框字段类型的data_type是否支持数值、boolean类型的情况，需要确认下【经确认是正常的】
- [x] 时间类型
- [x] 其他字段类型确认，比如lookup、master_detail？

**Comment by Flyingliao** [comment]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/41402189/176580686-ae54357c-cd40-4fdd-b48c-cbbfbfd35c32.png">

**Comment by Flyingliao** [comment]
```
"select_multiple__c": ["a","b"],
"file_multiple__c": [
          "62bd12d6b71984488975dedc",
          "62bd12d9b71984488975dedd"
]

_display:
"select_multiple__c": "apple,banana",
"file_multiple__c": "temp.js,temp.json",
```
