### ISSUE TITLE
新建记录确认按钮样式异常

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3523]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/176344613-15cc6259-e067-4e09-a25c-e63308a4d5cc.png">

**Comment by lizhenghotoa** [comment]
- 附件字段显示也有问题
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/176347128-7417fa6d-a911-45e6-a79a-0fafd9cd7787.png">

**Comment by Flyingliao** [comment]
最新代码无法重现
