### ISSUE TITLE
流程删除报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3525]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/176363639-7e69dd39-c8ef-4aba-a0c9-09d93cee00ca.png">

**Comment by Flyingliao** [comment]
**.object.yml
```
actions:
  test:
    label: test
    visible: true
    'on': record
    todo: !<tag:yaml.org,2002:js/function> |-
      function(){
        var a= $('body').length;
        console.log('list==>',a)
      }
```
在列表上点击按钮代码中识别不了'$',  在详细记录页点击按钮代码中能识别。

1、简单处理方法：在'$'前面添加window.  。 

2、统一处理方法： 彻底解决为什么在列表上点击按钮时代码中识别不了'$'. 

界面上配置的按钮 也识别不了'$'；  'alert' 也识别不了。
