### ISSUE TITLE
文档 补充 reddash mongodb 查询语法

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3532]
https://redash.io/help/data-sources/querying/mongodb

**Comment by Flyingliao** [comment]
查询下添加： MongoDB数据库查询语句请参考[redash-MongoDB文档](https://redash.io/help/data-sources/querying/mongodb)和[MongoDB文档](https://www.mongodb.com/docs/manual/reference/)。
<img width="769" alt="image" src="https://user-images.githubusercontent.com/41402189/177524102-49035b8e-c9e1-42ce-af53-ff14a22fc5cf.png">
