### ISSUE TITLE
自定义简档后，分配到用户该简档的用户在设置应用看不到任何菜单

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3534]
- 正常应该至少能看到自己的个人设置菜单才对
- 给该简档配置了人员对象的修改所有权限也不行

<img width="557" alt="image" src="https://user-images.githubusercontent.com/6219465/176706448-30920b6d-932c-44a2-9509-8404a7ce6db5.png">

**Comment by hotlong** [comment]
有相关任务，简档应该复制不是新增。
