### ISSUE TITLE
新增启动命令 steedos start， 替代 moleculer-runner

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3541]
- [x] 识别 steedos.config.js
- [x] 调整项目模版
- [x] 内核提供默认的 steedos.config.js，与项目中的steedos.config.js合并之后再加载。
- [x] 作废 steedos-config.yml

**Comment by baozhoutao** [comment]
steedos.config.js 合并规则:
"created", "started", "stopped" 在`内置config`的对应函数之后执行.
其他属性使用defaultsDeep合并
