### ISSUE TITLE
最新版本不显示“分部”菜单

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3556]
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/26241897/177245813-191a906b-7607-448d-959c-c65378f0fec1.png">

**Comment by yinlianghui** [comment]
是因为`@steedos/plugin-enterprise`这个软件包没有自动加载，他测试过手动安装这个软件包后能正常显示出来。

**Comment by baozhoutao** [comment]
原因是: @steedos/plugin-enterprise 对象定义丢失
