### ISSUE TITLE
platform最新代码安装合同应用后，为合同对象新建流程报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3564]
跑的是platform，远程开发环境
<img width="904" alt="image" src="https://user-images.githubusercontent.com/6219465/177351968-f48690cf-53d4-45be-b477-0babbc297827.png">

**Comment by yinlianghui** [comment]
实测新建流程时绑定到自定义对象没有这个问题。

**Comment by hotlong** [comment]
npx create-steedos-app@next 一样报错

**Comment by hotlong** [comment]
接口报错 Service '@currency.getNameFieldKey' is not found.

**Comment by hotlong** [comment]
安装主数据模块就好了

**Comment by hotlong** [comment]
需要确认 $.ajax 的error函数中，是不是取不到 jqXHR 了

**Comment by Flyingliao** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/41402189/177475872-f4c804bf-395a-484c-b4e8-197b4dd93712.png">

**Comment by yinlianghui** [comment]
> <img alt="image" width="839" src="https://user-images.githubusercontent.com/41402189/177475872-f4c804bf-395a-484c-b4e8-197b4dd93712.png">
-  jqXHR的错误是变量写错了。
- 需要尝试在前端错误日志中显示具体的错误信息
