### ISSUE TITLE
安装软件包时，同时安装并加载依赖的软件包

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3566]
必要的话，可以改 package.service.js

**Comment by baozhoutao** [comment]
启动软件包时, 读取软件包package.json文件, 如果有steedosDependencies, 则自动安装, 自动加载steedosDependencies中的软件包, 判断依据,跟路径是否存在package.service.js

**Comment by hotlong** [comment]
测试未通过
- 运行企业版 https://github.com/steedos/steedos-examples/tree/main/project-template-ee，
- 版本号改为 next
- 安装软件包 @steedos-lab/cost-ee

问题：
- lodash 被识别为软件包
- @steedos-lab/cost-ee 依赖了 @steedos-lab/contract，@steedos-lab/contract 依赖了 @steedos-lab/master，但是未能自动加载 @steedos-lab/master
