### ISSUE TITLE
详情页amis设计后, 编辑单个字段后无法保存

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3579]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/177713134-29e4b9a7-810e-49ff-9c53-dfef239af7af.png">

**Comment by yinlianghui** [comment]
- 已处理，给ObjectForm保存后逻辑中加了一段，自动设置表单mode为read变更为只读界面效果。
- 我们记录详细界面目前是执行的FlowRouter.reload();刷新整个界面，如果需要的话，用户可以自行配置afterUpdatent属性来达到刷新界面效果
