### ISSUE TITLE
长城宽带 无法访问 https://npm.elemecdn.com/@steedos-builder/fiddle@0.0.5/dist/builder-fiddle.umd.js

### ISSUE THREAD

**Issue by Blame4** [steedos/steedos-platform#3612]
其实是可以连接，响应
<Error>
<Code>AccessDenied</Code>
<Message>You have no right to access this object because of bucket acl.</Message>
<RequestId>62CD918C9F8B3239338AD289</RequestId>
<HostId>fe-static-zbprod-zb1-oss-3.oss-cn-zhangjiakou.aliyuncs.com</HostId>
</Error>

只有连接长城宽带的设备(电脑，手机)有这个现象，电信就没有这个问题

最新版是抛弃了CDN，但是这个还有残留

**Comment by hotlong** [comment]
2.2.54-beta.1

**Comment by hotlong** [comment]
重复
