### ISSUE TITLE
ROOT_URL地址 如果以符号`/`结尾，自动替换一下

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3614]
ROOT_URL地址也不应该以符号`/`结尾，比如配置为 `http://192.168.0.95:5000/` 或 `https://xxx.steedos.cn/` 是错的

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/blob/641c4ee349482e4f14a7bad7be42185c4496a43a/packages/meteor-bundle-runner/index.js#L74

**Comment by hotlong** [comment]
现在就没问题是吧
