### ISSUE TITLE
gitpod环境访问设计器会出现跨域错误，无法保存设计后的内容

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3615]
本地是正常的。
![image](https://user-images.githubusercontent.com/6219465/178642637-967a2bcf-778a-4834-8261-22a6041e7a0a.png)

**Comment by hotlong** [comment]
运行 [examples](https://github.com/steedos/steedos-examples/tree/main/project-template) 项目没有报错
