### ISSUE TITLE
用户界面配置一个amis应用，拖动一个华炎魔方列表视图进去，访问应用时显示Loading object ...，也没报错信息

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3617]
跟filters资产包没关系，因为廖同学那边的也测试到这个问题。

![image](https://user-images.githubusercontent.com/6219465/178648218-d4ad4e0f-fea6-45ca-a9cd-e3434aa839ea.png)

**Comment by hotlong** [comment]
重复 amis 自定义页面不能正常显示 #3616
