### ISSUE TITLE
左上角Logo不要限制方形；

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#362]
因为很多公司的Logo就是长方形的。
我设想方形Logo和长方形Logo各设置一个字段。
优先长方形

**Comment by yinlianghui** [comment]
已处理。
- 是否显示工作区名称，这个不加开关，设置了长方形LOGO就不显示工作区名称了。
- 手机上不会显示顶部bar，不受该任务影响，它依然只识别正方形LOGO。
