### ISSUE TITLE
页面报错：Cannot read properties of undefined (reading 'formatFiltersToODataQuery')

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3626]
gitpod问题环境请私聊。
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/178890968-865405c3-52ae-4e35-b196-f78e2ec62222.png">

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/issues/3625
