### ISSUE TITLE
审批王，查看分发审批单显示的内容有遗留，且样式需优化

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#3630]
![1657780874807](https://user-images.githubusercontent.com/7665279/178917847-4c39a611-70b7-4ecd-8693-29de2451340e.png)

![1657780779132](https://user-images.githubusercontent.com/7665279/178917709-8193d6cd-9a14-4a0b-bc26-a7c45437e8b4.png)

**Comment by yinlianghui** [comment]
### 关于“内容有遗留”
- 指的是多行文本字段，在执行`marked.parse`的时候报错，服务端未安装marked包造成的
- 修正后现在creator中服务端安装上了这个包已经正常解决了这个问题。
- 但是creator build后跑根目录又报错`marked.parse is not a function`，原因是跟目录nodel_modules安装了低版本的marked包

**Comment by yinlianghui** [comment]
点击签核签核历程中的审批状态，弹出的窗口样式问题已经在另一个issue中处理过了，点击“查看分发后申请单”按钮弹出 的窗口样式丢失问题是远程开发环境特有的网络问题，本地环境是好的。
