### ISSUE TITLE
postgres外部数据源问题清单

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3638]
准备工作：
连接外部数据源mysql的对象， 主键设置为 id ,  数据表中提前创建各种类型字段。

问题：
 - [x] 界面上创建一条记录，报错： {message: "Cannot read property 'id' of undefined", code: 500, error: 500}，   但是该记录创建成功了。关联任务：#3660
 - [x] 创建记录后接口报错。关联任务：#3661
 - [x] 自增字段不应该可编辑。 关联任务： #3662
 - [x] time字段报错： Incorrect time valuefalse '1970-01-01T13false52false00.000Z' for column 'time' at row 1
     - [x] 解决方案：字段类型设置为`timestamp with time zone`
 - [x] autonumber字段公式不生效。关联任务：#3677
 - [x] 下拉框保存的值为boolean时，只读不显示，编辑只显示value，不显示label。mysql数据库保存boolean的值分别对应 1 和 0 。
     - [x] pg库存的是boolean，显示正常
 - [x] 图片、附件多选字段保存有值时不会保存数组格式。关联任务：#3710
 - [x] 列表的（批量）删除按钮点击报错： standard_delete_many is not defined
 - [x] 列表页，先勾选一个记录，再点击新建按钮报错； id为主键， out_one为当前对象名。【报错信息显示 主键值重复，是正常报错】
<img width="665" alt="image" src="https://user-images.githubusercontent.com/41402189/179176836-023a8a7d-19e7-4ebd-a4d6-04fda6b4da85.png">

   

 - [x] 导出Excel 报错：{"error":{"message":"this._adapter.aggregate is not a function","code":500,"error":500}}

**Comment by sunhaolin** [comment]
外部数据源对象 配置 选择框(select)类型字段后 启动报错：
```bash
error TypeError: Cannot read property 'multiple' of undefined
    at getDBType (/workspace/steedos-examples/with-postgresql/node_modules/@steedos/service-metadata-objects/src/objects/fields/index.ts:27:22)
    at /workspace/steedos-examples/with-postgresql/node_modules/@steedos/service-metadata-objects/src/objects/index.ts:264:50
    at /workspace/steedos-examples/with-postgresql/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/workspace/steedos-examples/with-postgresql/node_modules/lodash/lodash.js:3032:24)
    at /workspace/steedos-examples/with-postgresql/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/workspace/steedos-examples/with-postgresql/node_modules/lodash/lodash.js:9410:14)
    at /workspace/steedos-examples/with-postgresql/node_modules/@steedos/service-metadata-objects/src/objects/index.ts:247:7
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/steedos-examples/with-postgresql/node_modules/tslib/tslib.js:115:62)
    at /workspace/steedos-examples/with-postgresql/node_modules/meteor-promise/fiber_pool.js:43:39
```

**Comment by sunhaolin** [comment]
- [ ] postgres数据源 自增主键 在列表不应可编辑
