### ISSUE TITLE
新建微页面时，选择类型为记录页面，然后切换渲染器为Redash，再改回为amis后，必填的对象属性被隐藏了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3641]
而且可以新建成功，新建后的微页面记录缺少必填的“对象”属性值。
![image](https://user-images.githubusercontent.com/6219465/179184223-c92eaa40-67c9-4227-a019-afa22ba5c6c8.png)

**Comment by hotlong** [comment]
redash 拟作废
