### ISSUE TITLE
登录页增加自定义字段，可配置为必填

### ISSUE THREAD

**Issue by Blame4** [steedos/steedos-platform#3647]

**Comment by hotlong** [comment]
我们正在写例子，用 nextauth 开发自定义登录页。https://github.com/steedos/steedos-platform/tree/master/examples/with-nextjs-nextauth

**Comment by hotlong** [comment]
keycloak 也是可选方案 https://github.com/steedos/steedos-examples/tree/main/with-oidc-keycloak
