### ISSUE TITLE
访问统计：改为通过软件包加载

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3656]
并可通过环境变量配置 
- STEEDOS_PUBLIC_ANALYTICS_BAIDU_ID： 启用 百度分析

项目模版中删除相关代码

下一步开发：
- STEEDOS_PUBLIC_ANALYTICS_GOOGLE_ID： 启用 Google 分析

**Comment by yinlianghui** [comment]
已增加软件包 `@steedos/service-analytics` 实现了以下产品分析配置：
- 百度：STEEDOS_PUBLIC_ANALYTICS_BAIDU_ID
- posthost #3673: STEEDOS_PUBLIC_ANALYTICS_POSTHOG_ID,STEEDOS_PUBLIC_ANALYTICS_POSTHOG_API_HOST

google的没有处理，另外以上分析脚本目前只支持登录后的界面分析，匿名访问并不会执行分析脚本。
