### ISSUE TITLE
项目模版：单包开发简易项目模版

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3659]
https://github.com/steedos/steedos-examples/tree/main/project-template

项目启动时，检测到根目录下有 package.service.js 时，认定为简易模版
- 自动加载 package.json 作为软件包
- 元数据同步默认同步到 ./main/default

**Comment by baozhoutao** [comment]
此开发作废. 简易模式存在问题, package.json中的内容无法区分是project的还是package的.
