### ISSUE TITLE
外部数据源自增字段设置为只读状态

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3662]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/41402189/179877971-943d50d4-4a20-4bcf-aeec-e2d7a2f60132.png">

**Comment by yinlianghui** [comment]
讨论后定的方案：修改uiSchema接口，返回对象定义时，判断到有自动的主键字段，弹出把该字段设置为readonly，并配置visiable_on属性，在新建的时候不显示该字段

**Comment by baozhoutao** [comment]
文件:`packages/objectql/src/types/object.ts ` 函数 `getRecordView`

**Comment by Flyingliao** [comment]
自增字段移除设置的omit属性，添加visible_on属性。
