### ISSUE TITLE
amis markdown组件可预览 发布后 转圈

### ISSUE THREAD

**Issue by Blame4** [steedos/steedos-platform#3663]
![image](https://user-images.githubusercontent.com/40301148/179903753-0acdf21a-aef8-454f-8272-0ac71fb3f4f8.png)
markdown组件可在页面设计器预览，发布后内容消失，转圈，

**Comment by hotlong** [comment]
应该是前端没引入amis的markdown包

**Comment by hotlong** [comment]
相关任务 https://github.com/steedos/steedos-platform/issues/3664

**Comment by hotlong** [comment]
已创建相关任务
