### ISSUE TITLE
在选择相关表的时候没有搜索选项，比如相关表是用户，用户多的时候需要一个一个找

### ISSUE THREAD

**Issue by Blame4** [steedos/steedos-platform#3675]
- 在选择相关表的时候没有搜索选项，比如相关表是用户，用户多的时候需要一个一个找
- 如果是多选，没有全选的选项，比如选择整个分部的人

**Comment by hotlong** [comment]
表格标头区域可以点查找按钮，不过确实不明显。

界面正在设计amis重构，相关改进暂停。
