### ISSUE TITLE
外部数据源对象支持autonumber、formula类型字段

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3677]

**Comment by sunhaolin** [comment]
- [ ] 公式计算时spaceId来源不依赖于记录，而是从userSession获取

**Comment by yinlianghui** [comment]
关于“computeFormula，computeSimpleFormula函数合并userSession参数”改动后测试：
- 简单测试了公式字段相关功能，其中引用$user相关功能正常
- 简单测试了自动编号字段功能，编写公式字段格式的公式能正常运算和显示出字段值
- 简单测试了批准过程字段更新相关功能，字段更新中设置要更新字段值为公式时功能正常
- 简单测试了字段默认值相关功能，配置为只读的字段，默认值设置为公式字段公式格式时功能正常
- stimulsoft报表功能因为最新代码有其它bug无法正常使用，所以暂时无法测试
