### ISSUE TITLE
外部数据源示例 examples/with-postgresql

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3685]
- 配置外部数据源，连接 keycloak 数据库
- 在华炎魔方中查看和管理keycloak的用户、客户端

**Comment by hotlong** [comment]
之前测试的相关问题参考

- 是指外部数据源右上角的测试连接按钮点击后一直显示loading界面
- 是用docker安装和启动的，mysql正常，postgres11和postgres14都有问题

经调式，后台接口在执行driver.init时数据库连接信息正常。
<img width="693" alt="image" src="https://user-images.githubusercontent.com/6219465/180804860-d842b493-c208-4437-93a7-49daf622d4bd.png">

作为对比，mysql执行driver.init时数据库连接信息为：
```
{
  type: 'mysql',
  url: undefined,
  name: '1658760064857',
  entities: [],
  host: '127.0.0.1',
  port: 3306,
  username: 'root',
  password: 'example',
  database: 'mysql',
  timezone: undefined,
  logging: false
}
```
