### ISSUE TITLE
审批王子表中，选择框类型字段应支持配置显示名称

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#3689]
![1658799351675](https://user-images.githubusercontent.com/7665279/180903655-cf7803fc-d5e1-4c1a-83a6-017317041fe2.png)
![1658799368642](https://user-images.githubusercontent.com/7665279/180903683-a7b59bcc-8b68-49dd-b6b0-bbc97b5024ac.png)
![1658799384164](https://user-images.githubusercontent.com/7665279/180903712-e1a20705-f172-44d6-947b-eff3cd394bfc.png)

**Comment by hotlong** [comment]
审批王选择框类型字段应支持配置显示名称 #3336

**Comment by yinlianghui** [comment]
> 审批王选择框类型字段应支持配置显示名称 #3336

相关代码提交到 #3336 了，涉及到单选、多选、Radio三种字段，功能要点：
- 在草稿待审批文件中编辑状态下，能正常下拉显示为label，保存为value
- 在草稿待审批文件中只读状态下，能正常显示为label而不是value
- 转发时相关字段值能正常保存为value和显示为label
- 分发时相关字段值能正常保存为value和显示为label，包括点击“查看分发后申请单”按钮时显示的只读界面
- 表格以及分组字段中的相关字段值能正常保存为value和显示为label，包括转发和分发过程
- 审批单打印界面上上述情况都能正常显示为字段label
