### ISSUE TITLE
新建流程-》从表单设计器创建流程的字段，创建完成后走该审批流程，字段的权限为只读，无法进行编辑。

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#3694]
操作步骤：
1. 流程-》新建一流程-》保存-》点击右上角“表单设计器”-》拖入字段-》编辑完字段名-》保存
2. 审批王-》新建-》选择刚才建的流程-》编辑

问题描述：
无法对字段内容进行编辑。

**Comment by hotlong** [comment]
需要配置字段权限
