### ISSUE TITLE
设置-公司设置-许可证菜单 有时不显示

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#3698]
版本:2.2.54

**Comment by sunhaolin** [comment]
运行 steedos-project-template 2.2.54 可正常显示
运行 platform 2.2分支最新代码 可正常显示

**Comment by sunhaolin** [comment]
运行 steedos-project-template 2.2.54 可正常显示
运行 platform 2.2分支最新代码 可正常显示
