### ISSUE TITLE
累计汇总字段过滤条件无法选择对象内置的“审批状态”字段

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3704]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/181671141-b62d6597-2aaa-486b-ae2b-714c9547fc19.png">

**Comment by Flyingliao** [comment]
原因：该字段设置了hidden: true ,   Creator.getObject().fields 就获取不到该字段属性。
解决方案： 去掉hidden: true,    改为 visible_on: "{{false}}"。
