### ISSUE TITLE
表单批准经常性不加载,需要刷新几次才有

### ISSUE THREAD

**Issue by huoxiangdong** [steedos/steedos-platform#3706]
批准历史明细和提请批准按钮
首次进入页面经常性的不现实，需要刷新后才回出现
希望优化下

![5201659075236_ pic](https://user-images.githubusercontent.com/18095882/181698687-ad9582ae-7c67-4f80-9b0b-21f86c524cde.jpg)
![5211659075245_ pic](https://user-images.githubusercontent.com/18095882/181698688-59b97a03-4b56-49d0-951e-5673eac8f331.jpg)

版本： 2.2.54

**Comment by sunhaolin** [comment]
最新版 2.2.55-beta.20 显示正常，未能还原此问题，请尝试使用新版 @huoxiangdong
