### ISSUE TITLE
使用环境变量初始化，会创建两条同名apikey记录

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3707]
在`高级设置->apikey`列表界面可以看到两条同名apikey记录。

**Comment by sunhaolin** [comment]
如，使用以下环境变量初始化：
STEEDOS_INITIAL_USERNAME=xxx
STEEDOS_INITIAL_PASSWORD=123456
STEEDOS_INITIAL_API_KEY=KhbqdF85HqVRQqIJdB4hpZO0vkPzeJw6ZL3PjBUbC7C

会出现两条名为`KhbqdF85HqVRQqIJdB4hpZO0vkPzeJw6ZL3PjBUbC7C`的apikey
