### ISSUE TITLE
相关表字段编辑时，下拉框模式下，也可以新建

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#3715]

**Comment by Flyingliao** [comment]
https://github.com/steedos/steedos-frontend/commit/02f663e8548f92a200bf253aed7ba4d0fe3d47a4

**Comment by Flyingliao** [comment]
- 下拉模式下的“新建”按钮 由权限 allowCreate 和 该字段上 create属性一起控制，都为true时才显示“新建”按钮。（create 在组件中默认设置为true）
 - 如果弹出窗口模式和下拉模式都设置了，优先取 弹出窗口模式。

**Comment by Flyingliao** [comment]
fix bug of tree：链接 https://github.com/steedos/steedos-frontend/commit/1c81910b409912708abeba794fef3a8a060b33bd
