### ISSUE TITLE
 附件下载时未找到时服务端报错：TypeError: Cannot read property 'db' of undefined

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#3723]
附件下载时未找到时服务端报错

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/commit/6311c982370d3145fbf473ace96293d1354f81c3

**Comment by sunhaolin** [comment]
测试确认点：
申请单上传下载附件
对象记录上传下载附件
对象记录附件字段上传、查看
上传附件后，附件删除后下载服务端是否报 `TypeError: Cannot read property 'db' of undefined `

**Comment by Flyingliao** [comment]
申请单上传下载附件。   正常
对象记录上传下载附件。  正常
对象记录附件字段上传、查看。 上传下载正常，  查看：无。
头像是否可正常设置。 正常

上传附件后，附件删除后下载服务端是否报错，待测试（服务端删除附件）

其它额外测试： 
1、附件子表， 图片的预览 无效， 打开一个空白页面。
原因：链接尾端多了图片名

2、mongodb连接不上，报错：Unable to connect: getaddrinfo ENOTFOUND mongodb

**Comment by Flyingliao** [comment]
附件字段上传附件后，附件在服务端被删除， 前端界面上该字段只读和编辑都无值显示（根据id找不到对应的附件信息）
