### ISSUE TITLE
windows环境启动后页面一直存在断线重连信息闪烁

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#3725]
本地克隆template项目或者通过npx命令行创建项目启动后，登录完成进入系统后，始终频繁闪烁等待连接，0s后重试提示，多浏览器测试均有问题，node后台无报错
系统版本：2.2.54(master分支最新版本代码)
系统版本：windwos10 企业版 1809
node版本：14.19.3
浏览器后台频繁刷新页面如下：
![image](https://user-images.githubusercontent.com/62589030/182656949-a66513b4-52b0-4a03-bb89-b61dbc9c03dd.png)
![image](https://user-images.githubusercontent.com/62589030/182656971-c7179ece-5922-45b3-a544-b277459d0b09.png)

**Comment by Flyingliao** [comment]
测试结果：
本地克隆template项目 **运行正常**
系统版本：2.2.54(master分支最新版本代码)
系统版本：windwos10 专业版 21H2
node版本：14.19.3

运行方法：
1、完全使用docker （会自带启动redis、mongodb、nodejs等） 运行项目，最后根据配置的 steedos_root_url || http://localhost:3000 打开系统登录页面。
2、先运行docker启动redis、mongodb， 再执行 yarn 、yarn start 运行项目。 （此过程中如果遇到 fibers 包报错，请重新安装nodejs, 安装过程中有个自动安装相关插件的设置要勾上，当前步骤设置完成后，会自动进入cmd命令窗口安装相关插件，最后安装完成后会提示 按enter退出。  重启下电脑，重新运行项目试试）

**Comment by CarlWhite2020** [comment]
> 测试结果： 本地克隆template项目 **运行正常** 系统版本：2.2.54(master分支最新版本代码) 系统版本：windwos10 专业版 21H2 node版本：14.19.3
> 
> 运行方法： 1、完全使用docker （会自带启动redis、mongodb、nodejs等，也包括steedos也在Docker中运行） 运行项目，最后根据配置的 steedos_root_url || http://localhost:3000 打开系统登录页面。 2、先运行docker启动redis、mongodb， 再执行 yarn 、yarn start 运行项目。 （此过程中如果遇到 fibers 包报错，请重新安装nodejs, 安装过程中有个自动安装相关插件的设置要勾上，当前步骤设置完成后，会自动进入cmd命令窗口安装相关插件，最后安装完成后会提示 按enter退出。 重启下电脑，重新运行项目试试）

我的使用场景不在docker内，而是直接在windows环境使用。目前使用虚拟机安装了官方版的win10系统运行项目依然会存在这个问题
