### ISSUE TITLE
相关子表页的新建按钮也应该执行 visibleOn 函数并判断权限

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#3735]
平台性问题： 审计日志子表右侧没有新建按键，但点击“审计日志”可进到日志的列表界面，此时点新建按钮，弹出的界面显示不全。

操作步骤（以合同为例）：
合同-》合同-》选任意合同进入-》审计日志-》新建
![image](https://user-images.githubusercontent.com/92509428/183032802-52e4acd5-ace0-49d6-8def-e9d3dbe98b11.png)

测试结果：
界面显示不全
![image](https://user-images.githubusercontent.com/92509428/183032548-955a1228-690a-4334-b137-041c6ef5191d.png)

**Comment by hotlong** [comment]
amis 版本重新测试
