### ISSUE TITLE
查找权限bug

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#3750]
魔方版本：2.2.52
![image](https://user-images.githubusercontent.com/34770813/184618098-c2bd2596-7f2f-48e9-ba71-8d59f30f76c1.png)
在lookup表中，如果没有编辑权限，页面上不允许搜索，只有有编辑权限的情况下才可以搜索

**Comment by yinlianghui** [comment]
关联issue： 2.3.0-beta.5 自定义对象只读字段在列表界面有时搜索功能异常，有时显示为可编辑状态了 #3752
需要确认2.2的最新版本是否正常。

**Comment by hotlong** [comment]
合并 列表页，如果列只读，顶部搜索输入框也变为只读了，只有有编辑权限的情况下才可以搜索 #3752
