### ISSUE TITLE
列表页，如果列只读，顶部搜索输入框也变为只读了，只有有编辑权限的情况下才可以搜索

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3752]
系统对象：抽取 文本、相关表、选择框三种类型字段设置只读，列表页三种类型字段是只读状态、搜索框正常。

自定义对象：抽取 文本、相关表、选择框三种类型字段设置只读，列表页 相关表类型字段是只读状态，搜索框禁用； 文本、选择框两种类型字段 可编辑，搜索框正常。

<img width="834" alt="image" src="https://user-images.githubusercontent.com/41402189/184624840-355015e4-f60c-4647-8d55-85e1ac69a4de.png">

**Comment by yinlianghui** [comment]
只读字段显示为可编辑状态时，编辑后能保存成功，说明不只是前端显示问题，后台接口在保存只读字段时也有问题。

**Comment by Flyingliao** [comment]
- [ ] 1、html字段 不能添加到列表视图上。 [这是定的规则嘛？]
- [ ] 2、code字段，列表顶部搜索无效（输入内容后不会进行筛选）。
- [ ] 3、time字段，列表顶部搜索在确认时间后点击“此刻”/“确认”按钮后，界面上的筛选时间被清空了。【不过数据确实筛选出来了】
