### ISSUE TITLE
类型为表单的amis微页面，设计好后在前台使用时，如果有服务端报错不会提示错误消息且窗口自动关闭了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3754]
比如新建列表视图或页面布局记录时，如果输入的是之前已经存在的api名称，服务端会报错：`Error: 该 API 名称 已存在或先前已使用过。请选择其他名称。`，但是该错误信息并没有提示出来而是直接关闭了窗口。

**Comment by hotlong** [comment]
开发人员直接看控制台消息即可
