### ISSUE TITLE
amis微页面拖动标题面板到页面设计器时报错：渲染发生错误，详细错误信息请查看控制台输出。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3767]
- 版本为2.3，2.2未确认
- 本地和远程开发环境都有问题

### 重现步骤：
- 新建一个类型为列表的微页面并打开页面设计器
- 拖动华炎魔方容器组件到右侧面板
- 拖动标题面板到之前添加到面板的华炎魔方容器组件内

![image](https://user-images.githubusercontent.com/6219465/186091029-a62c4a9c-8cc4-4f78-8512-3a0eb344a071.png)

![image](https://user-images.githubusercontent.com/6219465/186092569-695306a1-fa7b-4982-b305-0b911b922cd6.png)

**Comment by Flyingliao** [comment]
列表视图也会报错， 原理基本一样， 设计器没有识别 ```${context.rootUrl}、${objectName}```等变量。
<img width="868" alt="image" src="https://user-images.githubusercontent.com/41402189/186799542-93ddf0b3-163e-48e6-91ae-bc4cd488b776.png">
