### ISSUE TITLE
Example: with-amis-custom-components

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3773]
@steedos-examples/with-amis-custom-components

**Comment by yinlianghui** [comment]
示例已经提交到 https://github.com/steedos/steedos-examples/tree/main/with-amis-custom-components
直接运行该功能即可看到hello world自定义组件效果了。

**Comment by yinlianghui** [comment]
示例依赖的资产包已经发包，其源码在项目 https://github.com/steedos/steedos-widgets/tree/master/packages/example

**Comment by hotlong** [comment]
缺少基本的README
