### ISSUE TITLE
微页面配置多资产包时，自定义资产包中的组件有一定概率报错： 找不到对应的渲染器

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3780]
#### 报错信息
Error: Can only have one anonymous define call per script file

看下来是自定义资产包还没来得急注册到amis中界面就开始渲染了造成这个问题。

#### 参考

- https://github.com/microsoft/monaco-editor/issues/2283
- https://blog.csdn.net/m0_38050352/article/details/109378179
- https://requirejs.org/docs/errors.html

<img width="730" alt="image" src="https://user-images.githubusercontent.com/6219465/187026402-61bc73da-4920-4576-8c4e-ada6b54f1220.png">

**Comment by hotlong** [comment]
新版nextjs界面处理资产包时确保不报错就行
