### ISSUE TITLE
name字段如何实现自动编号

### ISSUE THREAD

**Issue by hmily3913** [steedos/steedos-platform#3786]
现在做了个报价单表，name字段自动产生，无法修改删除。想设置为类似自动编号，或者删除，如何操作？

**Comment by hotlong** [comment]
可以配置为自动编号类型的字段

**Comment by hotlong** [comment]
https://www.steedos.cn/docs/admin/field_type#%E8%87%AA%E5%8A%A8%E7%BC%96%E5%8F%B7%E5%AD%97%E6%AE%B5%E7%B1%BB%E5%9E%8B
