### ISSUE TITLE
各字段类型在列表顶部搜索功能测试清单

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3789]
- [ ] 1、html字段 不能添加到列表视图上。 [这是定的规则嘛？]
- [ ] 2、code字段，列表顶部搜索无效（输入内容后不会进行筛选）。
- [ ] 3、time字段，列表顶部搜索在确认时间后点击“此刻”/“确认”按钮后，界面上的筛选时间被清空了。（不过数据确实筛选出来了）。
- [ ] 4、image/file字段，列表顶部搜索 是上传图片/附件，无搜索功能。（file字段只读时，无筛选输入框） 【需要讨论这两种字段是否支持搜索，搜索的内容是什么？等等】
- [ ] 5、url字段，列表顶部搜索无效，输入内容后自动填充为“ [object Object] ”。

**Comment by hotlong** [comment]
ag-grid 已作废
