### ISSUE TITLE
记录详情页点击最底部子表菜单后，页面出现两个滚动条

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#3798]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/187857889-09845084-eca1-494d-953c-8451e5684e2f.png">

**Comment by Flyingliao** [comment]
统一问题：当弹窗高度小于当前按钮位置与底部距离时就会产生该问题。

<img width="422" alt="image" src="https://user-images.githubusercontent.com/41402189/189059207-523e75b7-a5be-4d4e-9091-84298b71613b.png">

**Comment by Flyingliao** [comment]
通过调整“菜单弹出位置”无效
https://ant.design/components/dropdown-cn/#API
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/41402189/189594183-7877a984-0dec-488f-a9c6-6f9033a3d64c.png">
