### ISSUE TITLE
部门隐藏后在部门设置中应该还是显示，目前不显示，且通过筛选也不显示，只有通过分部可追溯到

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#3802]
![1662359166430](https://user-images.githubusercontent.com/7665279/188374250-f4211ce7-c1f6-49c6-a683-24e8116aa4e3.png)

![1662359110607](https://user-images.githubusercontent.com/7665279/188374070-5de24b88-6360-44dc-b782-743c9ba9ef96.png)
![image](https://user-images.githubusercontent.com/7665279/188374145-52e52449-b234-468b-b939-2bdeeba5a406.png)

**Comment by yinlianghui** [comment]
2.3和2.4大管理员以及分部管理员账户中都无法重现。
