### ISSUE TITLE
确认下共享规则的过滤条件是否不支持 in或=操作符接数组值进行过滤的情况

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#3807]
depart__c字段为绑定部门的相关表
设置分部管理员权限可以观看自己所属部门集合内的所有记录。
![image](https://user-images.githubusercontent.com/34770813/188830011-28f39b6a-65b4-4daf-b780-626338d6ff18.png)

如图，设置制定类目条件为{{$user.roles.indexOf("organization_admin") > -1}}可以制定为分部管理员
在记录过滤器中，{{[ ["depart__c", "=",$user.organization._id]]}}可以实现该描述。
然而，在$user.organizations中去找时，{{[ ["depart__c", "in",$user.organizations.map((n)=>{return n._id})]]}}
或者{{[ ["depart__c", "=",$user.organizations.map((n)=>{return n._id})]]}}都无法控制

版本为2.2.51

**Comment by Flyingliao** [comment]
原因：记录过滤器中暂不支持es6语法，请用原生 function(n){ return xx } 语法。

https://steedos.com/docs/admin/permission_set#%E5%85%B1%E4%BA%AB/%E9%99%90%E5%88%B6%E8%A7%84%E5%88%99
<img width="929" alt="image" src="https://user-images.githubusercontent.com/41402189/189794597-da2d547b-2d1e-4891-869e-25ca2c8f461b.png">
