### ISSUE TITLE
添加简档，选择授权应用时应用选项数据异常

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#3810]
![wecom-temp-4813de84d6ade06429272cbc2d58e8d3](https://user-images.githubusercontent.com/6194896/189299871-d29b9cb0-0c9d-44f1-aae9-60c111da8bbe.png)

只有第一个是手动新建的，其他的不知道哪里来的

**Comment by Flyingliao** [comment]
2.1 以来就存在该问题
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/41402189/189787341-6458d0ca-df0a-4584-8117-1a8116c5bd0f.png">
