### ISSUE TITLE
lookup多对象下拉框字段详情页值显示无此记录

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3824]
- [ ] 旧版页面详情页显示无此记录；
<img width="984" alt="image" src="https://user-images.githubusercontent.com/26241897/191420026-fc574737-4ce4-431b-9e02-35207ce38605.png">
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/26241897/191420218-8b2f4904-a75e-4a80-91d7-3de2ea4b0e10.png">

- [ ] 新版页面，点击对象菜单后，显示一片空白
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/191420256-240b0df6-f01f-44ee-9047-a5e982473fbe.png">

**Comment by baozhoutao** [comment]
旧版react 组件问题不处理.
新版已支持 lookup 多实体选择
