### ISSUE TITLE
平台软件包初始化报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3830]
2.2.55版本：
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/26241897/192487327-2ea6c028-05ca-4380-a697-e9160abb70d7.png">
2.3版本：
<img width="934" alt="image" src="https://user-images.githubusercontent.com/26241897/192487326-134a68cd-a817-4a9a-836e-b709dae0a3fa.png">
同时2.3版本通过steedos id初始化完成后，还会出现被登出情况，还需要重新登录。
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/26241897/192488719-a0a2e9f4-09c8-40cc-a529-137908264f35.png">

**Comment by sunhaolin** [comment]
steedos-project-template 2.3.0-beta.25 测试已正常
