### ISSUE TITLE
@steedos-labs/experience 服务启动控制台报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3833]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/192676164-b4971cc0-5411-4504-b499-d36c82036dec.png">

**Comment by baozhoutao** [comment]
此问题不是启动服务报错. 
是访问3100端口时,报错.  是@steedos-labs/experience模块集成异常导致.
