### ISSUE TITLE
代码加载的页面布局、列表视图可由管理员自定义修改

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3846]
页面布局、列表视图 添加 自定义 按钮

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/2036

**Comment by lizhenghotoa** [comment]
- [ ] 列表视图记录自定义后记录还是不可以修改
![无此记录情况自定义报错](https://user-images.githubusercontent.com/26241897/199411698-8ea038ba-dce5-42a0-94c2-bc0e68190d89.gif)
