### ISSUE TITLE
deploy Steedos docker Image on ARM64 server

### ISSUE THREAD

**Issue by TarekMahran** [steedos/steedos-platform#3867]
Is it possible to deploy Steedos docker Image on ARM64 server?
是否可以在 ARM64 服務器上部署 Steedos docker Image？

**Comment by hotlong** [comment]
We have enabled the platforms: linux/amd64, linux/arm64 parameters when packaging the latest version of the docker image, you can try. 

https://hub.docker.com/repository/docker/steedos/steedos-enterprise/tags?page=1&ordering=last_updated

**Comment by TarekMahran** [comment]
Thanks @hotlong. I will try the new image and give you the feedback.
