### ISSUE TITLE
lookup字段上相关列表的新建按钮未能弹出amis设计的对象表单

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3872]
魔方版本：2.3.0-beta.31
如图，来源管理对象已经配置了amis对象表单，其主列表上新建记录时能正常弹出来，但是lookup字段上的新建按钮弹出的还是老表单。
<img width="911" alt="image" src="https://user-images.githubusercontent.com/6219465/197332703-24ba92d8-60b9-470b-a368-dc4b0773ac23.png">

**Comment by hotlong** [comment]
前端问题原则上只处理 amis 界面
