### ISSUE TITLE
树形结构查找问题

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#3886]
树形结构的数据，使用右上方查找的功能会失效。以及不能通过父级去找所有的子级

**Comment by RussellMao** [comment]
图为点击查找后，没有对应的graphql请求
![image](https://user-images.githubusercontent.com/34770813/197731411-78ae0805-acaf-46d0-9367-82ab6d0b0d77.png)

**Comment by yinlianghui** [comment]
已处理，应该是因为dx控件库后面有升级过造成的。
