### ISSUE TITLE
手机端子表的附件列表，点击标题应该直接下载

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#389]
- 还需要测试手机App弹出显示附件内容的逻辑

**Comment by yinlianghui** [comment]
最后规则：
1.点击列表不直接下载，还保持为进入详细界面
2.详细界面手机上优先显示下载按钮，其他按钮显示在底下折叠按钮列表中

**Comment by yinlianghui** [comment]
测试过手机上ios/androd下载图片/doc/js/html/pdf等都正常
