### ISSUE TITLE
标准 SaaS ：通过环境变量 STEEDOS_TENANT_ENABLE_SAAS  启用多租户运行模式

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#3909]
第一版:
暂不支持创建对象、字段、按钮、列表视图
支持配置权限集
支持创建页面布局

**Comment by baozhoutao** [comment]
新增: examples/project-saas . https://github.com/steedos/steedos-platform/blob/65f1109b183dd1522dfb571f962d5837ca8ee703/examples/project-saas/package.json

**Comment by hotlong** [comment]
目前的 SAAS 需要单独打 docker，还是应该在 service-community 和 service-enterprise 中直接判断环境变量 STEEDOS_TENANT_ENABLE_SAAS
