### ISSUE TITLE
审批王，手机版，业务伙伴修改图片类型字段，修改不了

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#3915]

**Comment by sunhaolin** [comment]
经测试，手机端 图片类型字段、附件类型字段 上传报错

**Comment by sunhaolin** [comment]
![image](https://user-images.githubusercontent.com/6194896/201619362-af5419bf-d810-4a23-9dc6-8dc73bfae173.png)

**Comment by hotlong** [comment]
在 2.4 中处理
