### ISSUE TITLE
审批王子表通过按钮发起无法点击新增一行

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#3919]
版本2.2.58
点击发起审批按钮：
![image](https://user-images.githubusercontent.com/34770813/201597082-c92bb633-4da7-4693-99cb-1a75234860fb.png)
审批王表单内的子表新增一行按钮失效。
![image](https://user-images.githubusercontent.com/34770813/201597253-fc6b19d6-5f53-486b-9a9a-1ec52d1c7163.png)
点击F5刷新或者从审批王进入无此问题。按钮会出现该问题。系统windows 浏览器版本chrome 107.0.5304.107

**Comment by hotlong** [comment]
2.5 版本升级为 amis 表单
