### ISSUE TITLE
新版客户端，点审批单打印，问题很多

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#392]

**Comment by chenzhipei** [comment]
已处理，需要重新打包客户端，签名证书已过期

**Comment by yinlianghui** [comment]
尝试过了，window.open函数所有参数测试下来不能解决弹出窗口没有关闭按钮的问题。
等后续任务：相关记录的链接，不要弹出新窗口 #461 处理完后，新窗口问题就不那么严重，先放放！
