### ISSUE TITLE
bug 2.2 2.3 amis的dashbord 调用 ~packages-@steedos/service-charts/queries/xxxx/results结果不刷新，一直是旧结果，需要

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#3931]
![image](https://user-images.githubusercontent.com/25192306/202388878-12229708-1f07-4b92-93c5-ceeda1549eef.png)

到query的设计器页面，重新执行一遍后，才能大屏数据才刷新

添加、修改对象数据后，大屏数据不变（已经设置了每个10s刷新），刷新浏览器页面，也不会刷新数据，上面的明细表数据通过graphql查询，每次进入报表页面可以实时刷新
![image](https://user-images.githubusercontent.com/25192306/202389315-c46f2da8-cf9b-4f4d-a2ef-8d9bab48e7d8.png)

**Comment by baozhoutao** [comment]
请提供请求参数

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/202845513-08d7ee04-2b40-4c11-bb19-777b9bf7c108.png)

@hwzero 请在查询设计器中配置查询结果的刷新频率.   页面刷新并不会强制刷新查询结果缓存.
