### ISSUE TITLE
手机app:  内部官网系统首页和部分对象列表异常

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#3936]
url地址：https://huayan.steedos.cn
版本号：2.3.0

异常截图：首页报错、列表视图加载不出来
<img width="754" alt="image" src="https://user-images.githubusercontent.com/41402189/202951296-5bd5bdbe-d163-43b6-b677-e5d916b004de.png">

**Comment by chenzhipei** [comment]
app连接最新的服务下载资源文件报错
server：2.3.2-beta.12

![image](https://user-images.githubusercontent.com/15027092/204207084-1cf374a9-37fd-4442-8b71-929a475e250f.png)

gitpod新开的环境也是一样：
![image](https://user-images.githubusercontent.com/15027092/204207162-8e5225b7-0293-4ac8-83ce-0e52ad2b27dc.png)

**Comment by chenzhipei** [comment]
更新到最新版后解决
