### ISSUE TITLE
amis button设置气泡提示发布后没有效果

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3938]
- 设计器中预览是好的，但是发布后看不到气泡提示
- 可能是样式问题

![image](https://user-images.githubusercontent.com/6219465/202986321-f0311ef0-c4d2-4f59-b536-f51d25f6de61.png)

![image](https://user-images.githubusercontent.com/6219465/202986174-fbf6d1cc-8803-427c-9f0a-11474012c0ba.png)

**Comment by baozhoutao** [comment]
- [ ] creator
- [ ] nextjs

**Comment by baozhoutao** [comment]
- [ ] creator
- [ ] nextjs
