### ISSUE TITLE
列表视图弹出的编辑表单中未支持配置列宽

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3947]
原来还有一个列是否换行的属性，现在也不能配置了，估计是不支持了，我们官网写是支持的，后续是否要支持？https://www.steedos.com/docs/admin/listview#%E5%A6%82%E4%BD%95%E5%88%9B%E5%BB%BA%E5%88%97%E8%A1%A8%E8%A7%86%E5%9B%BE。
![企业微信截图_59e7be1c-0087-4c59-8738-d573e365ff63](https://user-images.githubusercontent.com/6219465/203456399-493e6216-1b97-4022-bb09-c085fb87b058.png)

**Comment by hotlong** [comment]
未来应该通过拖拉的方式实现
