### ISSUE TITLE
新建页面布局时，默认只增加 master/detail 类型

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3948]
默认加上了53个子表行，一个一个删除也很累。
![image](https://user-images.githubusercontent.com/6219465/203457049-e1866df2-8bfa-4795-b231-63258aa7ac8b.png)
![image](https://user-images.githubusercontent.com/6219465/203457277-9fe11854-8a12-4bc4-94e1-ea62cabcb7fa.png)

**Comment by hotlong** [comment]
是不是应该默认只加载 master/detail 类型的？
