### ISSUE TITLE
应用设置中手机是否显示开关无效，未启用情况下手机端还是会显示应用（nextjs & meteor)

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3951]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/203466781-6baf1eac-ca3b-4702-bbda-a8ee1b671a37.png">

**Comment by Flyingliao** [comment]
nextjs中暂未找到合适的判断是否是手机端函数 或 参数， 暂不处理nextjs项目中的该问题
<img width="811" alt="image" src="https://user-images.githubusercontent.com/41402189/210307583-ad5629a7-839b-4400-be82-8398d20f438c.png">
