### ISSUE TITLE
community:2.3.0 审批王要如何实现2个列表联动效果？

### ISSUE THREAD

**Issue by Taoja** [steedos/steedos-platform#3954]
我的审批表单里需要选择（合同）及其关联子表（款项）
用odata渲染出2个表单以后，要如何实现选择合同以后 款项选择器只能选择该合同下的选项？
<img src="https://web.gztianhong.top:4433/issue1.png" />

**Comment by sunhaolin** [comment]
所属款项的 过滤条件 增加如下脚本：
```js
function(所属合同字段名){
  if(!所属合同字段名){
     return "(_id eq '-1')";
  }
   return "(contract eq '" + 所属合同字段名._id + "')"
}
```

字段名根据你的表单替换

**Comment by sunhaolin** [comment]
![图片已粘贴至2022-11-24 09-28](https://user-images.githubusercontent.com/6194896/203675259-9cb9660c-f88d-4b83-8832-8601cf284bd9.png)
