### ISSUE TITLE
新建对象设置图标时搜索po页面会闪退

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#3974]
![闪退](https://user-images.githubusercontent.com/26241897/204686063-af4ae41d-6c31-4ed7-b48d-69f380a9f498.gif)

**Comment by hotlong** [comment]
此问题替换为 amis 资产包后再处理

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/issues/3988
