### ISSUE TITLE
记录详细界面子表支持添加自定义按钮

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3978]
原始需求：子表上表头的列上不支持加问号提示语提示字段的含义描述，故希望能在子表右上角加一个自定义按钮来实现提示字段含义的功能。

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/6219465/204719825-8d2ef552-3a1c-4017-944f-199a6d13bc12.png">

**Comment by yinlianghui** [comment]
按原始需求，最理想的是在子表表头实现自定义问号提示文字功能。

**Comment by hotlong** [comment]
amis 改造版支持

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/issues/3988
