### ISSUE TITLE
【审批王】表单设计器/模板 要怎么实现根据odata选项渲染相关表格

### ISSUE THREAD

**Issue by Taoja** [steedos/steedos-platform#3989]
需求如题
如果选择的项目有关联的表格就显示，没有的话就不显示下方表格
<img src="https://web.gztianhong.top:4433/wenti2.jpg" />

**Comment by hotlong** [comment]
amis 版本发布后会支持，否则只能尝试用原生的 jquery语法，控制隐藏显示dom元素。
