### ISSUE TITLE
BUG：对象字段修改之后， 列表视图无法查看到新增的字段

### ISSUE THREAD

**Issue by choose6** [steedos/steedos-platform#3992]
首先列表视图的编辑入口有两种
1. 点击记录项目右侧的下拉菜单的编辑按钮
一种是点击记录右侧下拉菜单的编辑按钮或者进入到记录详情的右上角的编辑按钮
![编辑1](https://user-images.githubusercontent.com/61673908/205416009-b9e3406e-ef97-48f6-a3c9-e1c2e0df1005.png)
![编辑2](https://user-images.githubusercontent.com/61673908/205416017-9942715b-45ca-4205-a148-ba025df99de9.png)
这种方式我这里就叫做弹窗模式。

还有一种方式是点击记录详情页的小铅笔✏️按钮， 直接编辑。
![截图3](https://user-images.githubusercontent.com/61673908/205416230-953abfdd-81fb-4f8a-876b-647fca18bef0.png)

我这里先总结一下编辑模式：
1. 弹窗模式
2. 直接编辑模式

故障具体描述：
1. 修改对象字段之后，弹窗模式可以看到新增的字段， 但是提交修改之后其实是无效的。修改之后在记录详情当中看到的新增的字段会变为【无此记录】
2. 如果使用直接编辑模式， 无法看到新增的对象字段。

**Comment by hotlong** [comment]
在 amis 表单改造需求中测试。 https://github.com/steedos/steedos-platform/issues/3988
