### ISSUE TITLE
自定义amis页面， 窗口无法弹出

### ISSUE THREAD

**Issue by choose6** [steedos/steedos-platform#3993]
在对象的列表视图页面，如果先点了新建按钮， 表单窗口是可以弹出的。 但是如果再去点击记录右侧下拉菜单的编辑按钮， 编辑表单是弹不出来的。相反如果先点编辑， 表单窗口可以弹出， 但是如果再去点击新建按钮， 表单窗口是无法弹出的。

**Comment by choose6** [comment]
https://user-images.githubusercontent.com/61673908/205492258-df6d87fa-b6b6-4ac1-ae81-01321cf8f028.mp4

**Comment by hotlong** [comment]
在新版 amis 界面中测试确认 https://github.com/steedos/steedos-platform/issues/3988

**Comment by choose6** [comment]
这个问题是被关闭了吗? 我目前的解决方案只能在 object.yml下的action 重新定义新建和编辑按钮的行为, 我觉得应该是 `react` 渲染元素出现了问题, 以下是我临时的解决方案
actions:
  standard_new:
    label: 新建
    visible: true
    'on': list
    todo:  !!js/function |
      function(objectName, recordId) {
        const newComp = window.$('#steedos-page-modal-root-purchase_in_storage__c-standard_edit')[0];
        if (newComp) newComp.remove();
        Creator.executeAction(objectName, {todo: 'standard_new'}, recordId);
      }
  standard_edit:
    label: 编辑
    visible: true
    'on': record
    todo: !!js/function |
      function(objectName, recordId) {
        const newComp = window.$('#steedos-page-modal-root-purchase_in_storage__c-standard_new')[0];
        if (newComp) newComp.remove();
        Creator.executeAction(objectName, {todo: 'standard_edit'}, recordId);
      }
