### ISSUE TITLE
页面布局隐藏字段有时会失败

### ISSUE THREAD

**Issue by choose6** [steedos/steedos-platform#4003]
![a1](https://user-images.githubusercontent.com/61673908/206102071-0194c261-cb8f-47e9-aa45-13490b17d2d2.png)
![a2](https://user-images.githubusercontent.com/61673908/206102087-953da01c-03f6-47ec-beb7-6d690900eea3.png)

更换过浏览器也清除过缓存， 非缓存问题。
该对象这有这一个默认布局。

**Comment by lizhenghotoa** [comment]
显示条件写法有误，请参考相关显示条件写法文档
