### ISSUE TITLE
私有化部署后，换域名部分系统功能接口报跨域问题

### ISSUE THREAD

**Issue by Taoja** [steedos/steedos-platform#4012]
**版本**：steedos-community:2.3.0
**问题描述**：之前我用的是web.gzhuayi.top这个域名，后面换成了web.gztianhong.top来进行访问
大部分功能正常，系统自带的部分amis页面报跨域问题。
**问题图片**: 
<img src="https://web.gztianhong.top:4433/issue3.png">

**Comment by hotlong** [comment]
确认一下 ROOT_URL 环境变量是否对应修改
