### ISSUE TITLE
自建service如何监听所有服务都已启动？

### ISSUE THREAD

**Issue by Taoja** [steedos/steedos-platform#4015]
问题：按照Moleculer文档设置了监听$broker.started，但是启动后并未触发回调
代码：
```js
/**
   * Events
   */
  events: {
    '$broker.started': {
      handler() {
        console.log('$broker.started')
      }
    }
  },
```

截图：
![image](https://user-images.githubusercontent.com/16242008/206997506-399e0dab-b653-4e58-9f44-b5488a0e93cb.png)

**Comment by hotlong** [comment]
service 可以依赖，但没有监听所有都启动的功能。
https://moleculer.services/docs/0.14/services.html#Dependencies
