### ISSUE TITLE
steedos启动能否增加--inspect调试模式

### ISSUE THREAD

**Issue by Taoja** [steedos/steedos-platform#4018]
后端开发时，挺多api，service，全局对象和方法都没有文档指引。
一条条console眼花缭乱，能否增加inspect模式支持devtool调试

**Comment by hotlong** [comment]
参考 https://github.com/steedos/steedos-platform/blob/ba886804705dae308a5bccb8f62b7f6c78e18974/examples/project-ee/package.json
