### ISSUE TITLE
dev --hot模式下，steedos-package下自建服务无法发现

### ISSUE THREAD

**Issue by Taoja** [steedos/steedos-platform#4020]
/steedos-packages/qywx/package.service.js 注册了一个叫做~packages-qywx的服务
但是通过this.broker.call('~packages-qywx/sendMessage')进行服务调用时报：
Service '~packages-qywx/sendMessage' is not registered.

**截图：**

![image](https://user-images.githubusercontent.com/16242008/207284632-6641583d-431c-48b7-b91f-27c0e1df76a9.png)

![image](https://user-images.githubusercontent.com/16242008/207284817-b31eecd3-2f33-4cd3-8cdb-827645d07b1c.png)

**Comment by baozhoutao** [comment]
@Taoja  call action 的语法是 : `call("服务名称.action名称")`  不是 `/`

**Comment by Taoja** [comment]
> @Taoja call action 的语法是 : `call("服务名称.action名称")` 不是 `/`

谢谢已解决
