### ISSUE TITLE
对象中使用相关表关联了人员对象，使用5000项目新增记录无异常，3000上新增记录，列表中无法展示人员记录

### ISSUE THREAD

**Issue by ferrymo** [steedos/steedos-platform#4035]
标题描述为纯对象操作，未使用自定义。
![列表详情展示新增案例](https://user-images.githubusercontent.com/52627295/208372442-01a169d6-175c-4d95-a1d9-1b99271a2ebc.png)

字段配置
![字段配置](https://user-images.githubusercontent.com/52627295/208372557-79aa3409-d1df-4955-991a-2990d2d04996.png)

操作介绍，进来都有数据
![操作介绍](https://user-images.githubusercontent.com/52627295/208372680-6aa93004-e24c-4430-98e9-96f9518a5a67.png)

初步排查两边接口数据一样，调接口形式不一样，然后userid也不一样
`
"mutation{record: ms_project_members__c__insert(doc: \"{\\\"ms_research_center_id__c\\\":[\\\"639a9770c9d4b113f070eba0\\\"],\\\"ms_project_id__c\\\":\\\"63993d44a57d122c58c72734\\\",\\\"user_id__c\\\":\\\"tTXpYoeshwazc4vqe\\\",\\\"permission_set_id__c\\\":[\\\"63997cb02d737e3e5470d544\\\",\\\"63997ccd2d737e3e5470d545\\\",\\\"63997d3f2d737e3e5470d54a\\\"]}\"){_id}}"
`

**Comment by sunhaolin** [comment]
初步判断： 引用对象是人员（space_users）时，5000存的是space_users._id，3000存的是users._id ；数据不一致导致
