### ISSUE TITLE
树状结构对象新建记录时父字段选不到值

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4056]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/210716221-1cb411d4-8bdd-486c-9266-75ef6c4b02cc.png">

**Comment by yinlianghui** [comment]
2.3上父字段显示的是下拉tree模式时，需要刷新浏览器才能选到刚新建的值，2.4没有这个问题，无论是下拉模式（显示为普通的下拉框了）还是弹出窗口模式都是正常的。
