### ISSUE TITLE
(紧急)在字段文件中设置的只读属性 5000项目正常生效，3000项目未生效

### ISSUE THREAD

**Issue by ferrymo** [steedos/steedos-platform#4057]
设置方式
![企业微信截图_16729006699768](https://user-images.githubusercontent.com/52627295/210723242-619660a2-e961-402a-bd13-f8f114d8fd69.png)

5000项目正常
![企业微信截图_16729006052473](https://user-images.githubusercontent.com/52627295/210723298-7dc905e3-c020-4610-b813-e563fa4f30eb.png)

3000项目无效
![企业微信截图_16729005917697](https://user-images.githubusercontent.com/52627295/210723348-01b460d0-f232-425a-bd22-8d9fadbe5b6b.png)

**Comment by yinlianghui** [comment]
测试下来没有问题，master_detail字段类型，在5000/3000端口项目都是正常的。

**Comment by lizhenghotoa** [comment]
@ferrymo 问题重现方式单独和殷老师演示确认。
