### ISSUE TITLE
version2.2.59 人员不能停用

### ISSUE THREAD

**Issue by Serena1117** [steedos/steedos-platform#4059]
<img width="1119" alt="WechatIMG2338" src="https://user-images.githubusercontent.com/69805326/206611552-3cfea7f2-bdbc-489a-a87d-b3b543e2efa8.png">

**Comment by yinlianghui** [comment]
需要确认下2.2最新版本是不是坏了，客户用的是2.2版本

**Comment by yinlianghui** [comment]
2.2和2.3最新版本都有这个问题，停用和启用都可能会报错，但是有时是正常的有时是坏的。
![image](https://user-images.githubusercontent.com/6219465/210742853-bde23996-3f2f-4b85-94ba-1546f31a421f.png)

**Comment by Flyingliao** [comment]
2.2最新代码 除了简档为user的用户可以停用，其它的会报错。
2.3最新代码貌似都在报错。

排查到db.**.update(x)出问题了。
正常停用情况下， result返回1； 而目前的报错主要有两个：一个是请求接口报错，另一个是 this.logger 为 undefined 导致右上角显示的提示报错。
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/41402189/210751609-a48c137d-ddcc-4f15-9efb-abed53022546.png">
