### ISSUE TITLE
绑定华炎云账户参数初始化报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4062]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/210944996-14655203-1db1-422e-97c3-8461d4f289c5.png">

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/211444901-c1adc730-cdae-4743-b413-9bf30182c3cb.png)
功能正常, 报错就是错误信息的字面意思, “初始化参数错误“
