### ISSUE TITLE
主表/子表类型的字段无法限制编辑权限,必填字段, 强制可编辑

### ISSUE THREAD

**Issue by choose6** [steedos/steedos-platform#4064]
已排除权限集叠加的问题, 设定去掉了对象字段的权限, 主表/子表 类型的字段依然处于可编辑状态。

**Comment by yinlianghui** [comment]
请提供版本号，测试下来2.3最新版本源码运行时是正常的，请注意：如果字段设置为必填的话，会强制认为字段是可编辑的，其优先级最高。

**Comment by choose6** [comment]
有点 困惑, 为什么用户如果没权限, 但是字段是必填的,  就要认是强制可编辑的?

**Comment by hotlong** [comment]
必填字段, 强制可编辑，是按照 salesforce 的规则设计的，可能是为了避免触发器中的代码引用到必填字段？
