### ISSUE TITLE
新流程引擎，新建审批，选择流程，疑似流程不全

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4071]
1. 疑似流程未显示全
2. 按流程分类显示，乱了
3. 无 星标流程
4. 之前的版本是 默认按分类折叠的
![image](https://user-images.githubusercontent.com/7553007/211478919-3b7b8f5e-9819-4639-8297-8b2f316d2ed8.png)

**Comment by marchtian** [comment]
42.46 平台仍然不全。
而且不同账户，可选的流程是一样的，推断这个的判断不对。

**Comment by baozhoutao** [comment]
任务重复, https://github.com/steedos/steedos-platform/issues/4092
