### ISSUE TITLE
新流程引擎，列表上的流程过滤，换成新的流程选择控件

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4072]
1. 多出空白
![image](https://user-images.githubusercontent.com/7553007/211479584-cc4d3749-0170-4e7b-baa7-c1eaf091463f.png)

2. 点击分类，流程未显示
![image](https://user-images.githubusercontent.com/7553007/211479679-71e95994-9722-4164-9188-dac3bb39f879.png)

**Comment by baozhoutao** [comment]
貌似不是最新代码, 请更新2.4对象版本重新确认. 最新效果如图
![image](https://user-images.githubusercontent.com/6194462/211972631-31870c71-1668-4a8c-a842-bea054d732e1.png)

**Comment by marchtian** [comment]
最新版本，尚未替换。
是指这里的：
![图片已粘贴至2023-1-13 10-02](https://user-images.githubusercontent.com/7553007/212867805-35f0c478-9579-44a4-9efb-3bdf2961217e.png)

**Comment by marchtian** [comment]
还有查找按钮里的
![image](https://user-images.githubusercontent.com/7553007/212869840-ec866668-dc40-4eac-b3d0-52d66f5cc38c.png)

**Comment by baozhoutao** [comment]
任务重复 https://github.com/steedos/steedos-platform/issues/4092
