### ISSUE TITLE
vscode同步插件-对象 deploy同步问题

### ISSUE THREAD

**Issue by ferrymo** [steedos/steedos-platform#4075]
在Object中针对启动一个对象目录进行deploy ，把代码部署到数据库中，提示成功，但实际为成功。
后续排查问题为，由于切换数据库环境，导致METADATA_APIKEY配置错误，但进行deploy时无相关提示，排查该问题浪费时间，希望进行改进，增加相关提示！

**Comment by lizhenghotoa** [comment]
METADATA_APIKEY错误的情况下deploy同步元数据后台会提示配置相关同步参数，不会出现同步成功的情况。任务先关闭，后续问题重现再确认。
<img width="1586" alt="image" src="https://user-images.githubusercontent.com/26241897/211509451-bb42a6bb-5e76-4378-b940-6c0d906fcc44.png">
