### ISSUE TITLE
2.4 在记录详细界面新建子表记录时，如果主子表字段是只读的，没有默认带上关联主表字段值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4079]
主子表可编辑时是正常的。

![image](https://user-images.githubusercontent.com/6219465/211707058-9ac687a3-b90c-4b87-b981-da9b77bba56f.png)

**Comment by hotlong** [comment]
字段配置问题，如果需要默认值，不能配置为只读
