### ISSUE TITLE
如何禁止掉列表视图的快捷编辑

### ISSUE THREAD

**Issue by choose6** [steedos/steedos-platform#4085]
版本号2.3

![image](https://user-images.githubusercontent.com/61673908/211969538-c9daf311-3753-4c70-88d0-1e160016e59a.png)
这些记录审核过后是不允许编辑的,  我可以隐藏掉编辑按钮, 但是不能禁止列表视图的快捷编辑。
虽然说我可以通过触发器来禁止编辑, 但是不太直观。有没有办法在UI层就反馈给用户禁止编辑, 比如禁止掉这个列表视图的快捷编辑功能?

**Comment by hotlong** [comment]
对象上有一个开关：允许编辑单个字段
