### ISSUE TITLE
amis自定义表单的软件包部署到服务器后, amis的静态数据`context.rootUrl`不会修改

### ISSUE THREAD

**Issue by aundis** [steedos/steedos-platform#4086]
amis自定义表单的软件包部署到服务器后, amis的静态数据`context.rootUrl`不会修改, 导致amis表单请求数据失败.

使用版本: `"@steedos/service-community": "^2.3"`

**Comment by hotlong** [comment]
请提供重现规则

**Comment by choose6** [comment]
创建表单类型的amis自定义页面, 做成软件包,  部署到新的服务器上(ip或域名不同), 就能重现这个问题。

**Comment by hotlong** [comment]
2.4 已修正
