### ISSUE TITLE
2.4 公告正文样式待改进，目前显示了编辑状态的内容 (markdown 字段类型没有可视化编辑界面)

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4090]
2.3
![1673510202758](https://user-images.githubusercontent.com/7665279/212009954-ca20ea73-cb8f-41e8-9962-1c36cd8651e5.png)
2.4
![1673510246470](https://user-images.githubusercontent.com/7665279/212010038-342369a7-e070-4bcf-afa8-24ec74e5f7c1.png)

**Comment by hotlong** [comment]
相关 https://github.com/steedos/steedos-platform/issues/3664
