### ISSUE TITLE
2.4 对象列表视图，字段宽度设置后，实际数据展现时有重叠

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4094]
宽度已分，但字段内容仍然全部展示，与相邻字段重叠

**Comment by hotlong** [comment]
需要重现规则和截图

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/212583154-f7aaeeb1-a6c6-48c7-ad91-38cb539cc549.png)

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/212584372-7dd1d721-fa14-487a-b188-e43bb9a6e812.png)
