### ISSUE TITLE
2.4 选人、选部门控件，未按排序号排序

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4096]

**Comment by yinlianghui** [comment]
https://gitlab.steedos.cn/steedos/steedos-webapp-nextjs/-/commit/6fc147c963bd73830e6fcf4ef9bbc655f92268f9
https://gitlab.steedos.cn/steedos/steedos-webapp-nextjs/-/commit/90d82fa32382f918c35b0fe751b941cc3108ce36
https://gitlab.steedos.cn/steedos/steedos-webapp-nextjs/-/commit/0eeb09ece87d8ce6f0e877350843bd22dfe57729

**Comment by yinlianghui** [comment]
已按以下规则处理：
- lookup组件弹出picker窗口列表使用关联对象all视图排序
- 选人组件左侧组织树及右侧人员列表使用关联对象all视图排序
- 选部门组件使用关联对象all视图排序【同lookup弹出窗口排序，不用特意处理】
- lookup 下拉模式时，如果有关联对象则按关联对象all视图排序属性排序

**Comment by marchtian** [comment]
最新版，已看到改进效果
