### ISSUE TITLE
新建字段时，根据不同的字段类型，切换不同的默认值输入框

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4114]
额外的
 - [x] 如果字段是lookup， 显示 reference_to_field （引用的对象的字段，按照此字段去查找相关记录）属性, 默认值设置 _id。

【'text','textarea','html','code','markdown','boolean','toggle','date','datetime','time','number','currency','percent','password','url','email','select','lookup'】: 对应各自的字段类型.

【'autonumber','image','file','formula','summary'】: 对应text .
1、表单只读、编辑调用同一个schema：
        表单只读时字段不设置只读状态，这样字段就是编辑状态，显示正常。
        表单只读时字段设置只读状态，这样部分字段无法从_display中获取数据，显示为空值。

**Comment by yinlianghui** [comment]
#### 规则总结

- [ ] 总体规则：支持输入静态字段值和公式表达式，界面上可以通过开关切换
- [ ] 字段类型：`'text','textarea','html','code','markdown','boolean','toggle','date','datetime','time','number','currency','percent','password','url','email','select','lookup'`在静态字段值模式时，会显示为其各自对应的amis控件效果。
- [ ] 如果字段是lookup， 显示 reference_to_field （引用的对象的字段，按照此字段去查找相关记录）属性, 默认值设置 _id。
- [ ] 字段类型'autonumber','formula','summary'应该不允许输入字段默认值，即隐藏默认值属性。
- [ ] 字段类型'image','file'，如果好处理，应该显示为附件上传控件，并识别单选和多选，如果不好处理就按不支持配置默认值配置处理，即隐藏默认值属性。

#### 遗留问题

- [ ] 字段类型'autonumber','image','file','formula','summary'未处理，目前依旧显示的是普通文本框，保持了本次修改前的效果，需要按上述规则清单改进。
- [ ] 并未达到amis原厂设计器中配置字段默认值时的界面效果，即静态字段值和公式表达式两种默认值输入模式在界面上切换效果不完善。

**Comment by Flyingliao** [comment]
已测试清单：
 -  [ ] 1、同时设置了静态默认值 和 只读， 
      新建记录时会报错的字段： Catch an error "Syntax error." while eval formula ${默认值内容} with paramsfalse "{}" for "undefined"
        ----富文本、颜色、日期、日期时间、时间、相关表、主/子表、网址、邮件地址、
        ----文本、长文本、代码、markdown : 静态默认值手动加引号就恢复正常了
      新建记录不报错，但是无值的字段：
      ----选择框、地理位置
      新建记录正常的字段：
      ----复选框、开关、数值、金额、百分比、密码、
  - [ ] 2、新建选择框类型字段时，选择框 默认值 选择选项，最后一个选项显示空白；编辑状态时，选项都正常。
  - [ ] 3、字段类型改变时自动清空默认值:
  
  未详细测试清单：
 - [ ] 1、各类型字段公式默认值：amis日期公式需要转换成我们的保存格式

**Comment by yinlianghui** [comment]
关于默认值配置为公式时，日期、时间类型存在以下问题（日期时间类型字段没问题），其它类型的字段按amis规范写公式即可，不需要特别关注：
- [Bug]: 日期类型字段，配置默认值使用公式TODAY()，保存的值并不符合魔方平台规范 #6512
- [Bug]: 时间字段默认值配置为公式NOW()时保存的字段值不符合魔方平台中的time类型规范 #6509
