### ISSUE TITLE
steedos filters 在查询值包括特殊字符%时异常

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4124]
`["a", "=", "%"]`或`["a", "contains", "%"]`都有问题。

<img width="884" alt="image" src="https://user-images.githubusercontent.com/6219465/212607169-9cf88c16-5ecb-4513-9581-ae4812913bd5.png">

之前处理特殊符号issue之一:https://github.com/steedos/steedos-platform/issues/1656

**Comment by yinlianghui** [comment]
应该是%符号当时没考虑进去。

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/4084

**Comment by yinlianghui** [comment]
2.3和2.4都处理了这个问题，支持的特殊字符包括`/?:@&=+$,#%`和`^$()*+?.\|[]{}`，已补上单元测试，之前关联的issue都测试过没问题。

**Comment by baozhoutao** [comment]
此问题导致了 自动编号功能异常.

https://github.com/steedos/steedos-platform/issues/4209
