### ISSUE TITLE
前端数据导入时，选择数据导入模板，excel无法下载

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4137]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/212629777-1c0f6638-cbf1-450f-9747-d467d90181ba.png">

**Comment by yinlianghui** [comment]
2.4上5000是坏的（指向3000端口nextjs项目的asset-dev.json了），但是nextjs项目本身是好的，两边amis的sdk版本号也是一样的。
![image](https://user-images.githubusercontent.com/6219465/215692421-196d8a46-2dc9-4194-bd58-8674af02f121.png)

**Comment by yinlianghui** [comment]
只要给链接加上`target="_self"`属性就可以解决这个问题。
但是原来用的是amis的markdown组件，markdown本身不支持为a标签添加target属性，所以只能写原生的html代码。
但是这个markdown组件不支持渲染直接写的html，如图：
![image](https://user-images.githubusercontent.com/6219465/215696926-fb6f1f0a-dee6-4f57-af63-4ef9d66548fe.png)
amis官网中的markdown是支持直接写html代码的，如图：
![image](https://user-images.githubusercontent.com/6219465/215697911-afb152e2-525e-4a45-9b5e-81b20e8f4288.png)

所以最后换成使用amis的tpl组件来渲染下拉链接，不使用markdown组件了，处理后nextjs项目和platform项目都正常。
