### ISSUE TITLE
对象字段设置中过滤条件无法选择数据进行设置

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4143]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/212636562-c42e21f5-6ecf-45b7-afe9-0879ec8f9e03.png">

**Comment by hotlong** [comment]
对象字段设置中过滤条件历史设置的条件无法查看 #4142

**Comment by lizhenghotoa** [comment]
2.4.0-beta.24版本可以根据选择的对象现实出对应的过滤字段和运算符
