### ISSUE TITLE
长文本字段保存后没有换行显示

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4144]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/212637553-44636811-c095-4732-ba4e-aa800ab88cdb.png">

**Comment by hotlong** [comment]
convertData.tpl = `<%=(data.${field.name} || '').split('\n').join('<br>')%>`;

**Comment by baozhoutao** [comment]
详细页面已处理. 剩余 列表页面多行文本导致行太高

**Comment by baozhoutao** [comment]
此问题可尝试使用样式来处理 `whitespace-pre-wrap`

**Comment by hotlong** [comment]
列表页面多行文本导致行太高，不处理
