### ISSUE TITLE
设置》流程，步骤、权限等内容未显示，权限需要编辑

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4153]
与2.3相较
![image](https://user-images.githubusercontent.com/7553007/212863645-a27d1843-610b-46d8-a014-59440b4e69de.png)
步骤、权限等内容未显示

**Comment by baozhoutao** [comment]
权限已可以编辑: https://github.com/steedos/steedos-webapp-nextjs/commit/64f1ee45a1c4505d9ac471f1690250f46463c94c

**Comment by baozhoutao** [comment]
权限已可以编辑: https://github.com/steedos/steedos-webapp-nextjs/commit/64f1ee45a1c4505d9ac471f1690250f46463c94c
