### ISSUE TITLE
对象详情页每次进入大概要加载半分钟时间，有几个接口很慢

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4168]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215240747-4812f84a-f0e2-4f36-812a-f45a2a6e8efe.png">

**Comment by baozhoutao** [comment]
此问题在于objects 查询慢导致

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/216893502-989a6386-edb5-4784-b3bd-97d694a32059.png)
_display 下的 object 时, 多次查询了objects 记录. 此记录的`afterFind` 触发器存在性能问题.
