### ISSUE TITLE
人员字段只读时不显示值，只在界面上配置引用对象为人员而不是用户时才有问题

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4178]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/26241897/215250557-0d65f0b1-9db4-434a-a80f-1247ff2ba9ce.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215250568-d69a3df1-6aab-415c-9908-773fe83263f1.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215250474-96e6283f-4ff2-4250-bb89-3d890ee3c7f5.png">

**Comment by yinlianghui** [comment]
跟多选没关系，是界面上配置了reference_to为人员，但是不可以配置reference_to_fied，我们只需要支持人员字段保存为user._id的情况，不需要支持保存为space_user._id的情况，方案待定

**Comment by yinlianghui** [comment]
使用方案2处理了，改的GraphQL接口，以后不再支持选人字段保存为space_users._id的情况，强制保存为user._id。

**Comment by yinlianghui** [comment]
还原了GraphQL接口的改动，改前端，在识别到未配置`reference_to_field === "user"`时就不走选人组件编辑字段值，而是使用普通的lookup控件。
