### ISSUE TITLE
增加开关启用通讯录权限，限制选人控件的可见规则

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4184]
- 组织树，所有的所属组织作为根结点，并显示所有的下级节点
- 组织树共享规则，可以限制某个节点可以查看其他节点，这些节点也添加到组织选择的根节点
- 搜索找人时也需要在此范围内

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/224593239-ba3f9392-9ac6-48cc-a40b-6fadaa68039d.png)


![image](https://user-images.githubusercontent.com/7553007/224593144-1229f5f5-f22a-4b69-ae95-bfce1cac3358.png)

**Comment by marchtian** [comment]
原来的机制，设置保存在表 space_settings 中
{
    "_id" : "***",
    "space" : "***",
    "key" : "contacts_view_limits",
    "values" : [ 
        {
            "froms" : [ 
                "593b***"
            ],
            "tos" : []
        }, 
        {
            "froms" : [ 
                "DsoJ***"
            ],
            "tos" : [ 
                "Ggqw***", 
                "Kps2***", 
                "o6sm****"
            ]
        },
    "is_public" : false
}

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/226240110-8b26e6e5-c31c-4a78-a705-05f6a7fe9f1b.png)

**Comment by marchtian** [comment]
新增对象：通讯录权限 orgnizations_shared
字段：部门orgnizations（多选lookup，orgnizations），可查看read_orgnizations（多选lookup，orgnizations）, 启用status（checkbox），备注note（text）

**Comment by hotlong** [comment]
此功能使用共享规则和限制规则实现
