### ISSUE TITLE
开关类型字段，在有编辑权限时该字段还是不可以编辑

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4185]
- 未配置页面布局，字段权限也是可编辑的，uiSchema接口也返回的非只读
- 弹出的新建和编辑窗口该字段未显示出来
![image](https://user-images.githubusercontent.com/6219465/215310991-f030e8c0-0841-442b-ac90-897f611e4e83.png)

**Comment by Flyingliao** [comment]
测试正常
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/41402189/216251692-d4a3e230-7900-423e-8912-efcd10de81c8.png">

**Comment by Flyingliao** [comment]
可能是新建的字段，同时设置了amis表单，表单此时需要重新生成
