### ISSUE TITLE
amis自定义列表页后前台访问对象报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4188]
<img width="1812" alt="image" src="https://user-images.githubusercontent.com/26241897/215317220-91db1c6a-a6a0-449f-9c94-4291531a446d.png">
<img width="1913" alt="image" src="https://user-images.githubusercontent.com/26241897/215317242-f7ffa6a0-d223-426f-956c-45f81d011ba1.png">

**Comment by hotlong** [comment]
未能重现
