### ISSUE TITLE
lookup关联对象为树对象时，编辑字段时如果是下拉模式未显示为tree形式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4195]
显示为普通的下拉框列表了。
![image](https://user-images.githubusercontent.com/6219465/215380236-dcf69a00-f445-492e-9623-d200b2036e3c.png)

弹出窗口模式时能正常显示为tree形式。
![image](https://user-images.githubusercontent.com/6219465/215380614-450541ad-80e7-4d05-b9d6-aebd37b12256.png)

**Comment by Flyingliao** [comment]
排查结果：
 - [ ] 生成的字段类型是select， 在nextjs项目的getAmisStaticFieldType函数中查看。
 - [ ] 选项返回的值需要children属性。
<img width="712" alt="image" src="https://user-images.githubusercontent.com/41402189/218923090-8c744d28-6be6-47d2-a026-d72aef2dc724.png">
