### ISSUE TITLE
amis自定义页面列表视图相关问题

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4203]
- [x] 翻页配置不生效【是top配置后就不生效，这是规则，列表视图不再显示这个配置了】
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215987787-e5f77fa0-2385-4dbe-a7ec-e1bf5c98d99d.png">

- [ ] 每次点击列表视图后，相应配置项中对象和列表视图加载慢，需要大概加载5s【未能重现，请确认是不是gitpod上的网络问题】
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215988974-99e04df8-6afd-4ad3-80f0-1b659458acd6.png">

- [ ] 列表页表头按钮无法自定义【先不处理类似问题】
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215989185-47b11b8f-aca2-426e-816b-632cf800ae30.png">

- [ ] 前台会出现列表视图加载不出情况【需要重现规则】
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215996300-a83f76f7-fb7c-4876-b808-d65cfee5ac96.png">

**Comment by Flyingliao** [comment]
前台会出现列表视图加载不出情况：根据截图来看，是没有找到当前视图，请排查下是否删除了那个列表视图。
