### ISSUE TITLE
amis自定义详情页-默认组件，前台相关表页面数据加载不出

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4206]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215998411-0a217dc8-d5c9-4036-b09a-2b85685d26a8.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/215998564-25430589-b8a4-46aa-a474-d83551803a57.png">

**Comment by hotlong** [comment]
已处理
