### ISSUE TITLE
自动编号字段，自动赋值异常

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4209]
![image](https://user-images.githubusercontent.com/7553007/216207379-594726ff-8f8b-471e-8a5f-6ae0dd2f5f20.png)

近期生成的编号不对
![image](https://user-images.githubusercontent.com/7553007/216208229-71d17495-fd29-4273-b6ac-7088354249e3.png)

**Comment by baozhoutao** [comment]
此问题是由于filters改动导致
