### ISSUE TITLE
微页面设计器中按钮边距等样式需要优化

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4211]
![image](https://user-images.githubusercontent.com/6219465/216242485-74caf721-cf5f-4b65-9437-ce965e157d7d.png)

![image](https://user-images.githubusercontent.com/6219465/216242258-759a526f-3795-40cb-863b-dac1ca201f9a.png)

**Comment by hotlong** [comment]
beta.builder.steedos.com
