### ISSUE TITLE
安卓真机-左侧菜单栏一直显示不能隐藏，页面无法操作

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4215]
![WechatIMG431](https://user-images.githubusercontent.com/26241897/216268569-2163eaad-d25a-4bea-8258-bc98d2450964.jpeg)

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/216500007-00712276-008b-4709-9685-ca81671818e6.png)

css `translate` 提示错误 `invalid property value`
尝试给了多种css value,都不支持

**Comment by baozhoutao** [comment]
三星手机的自带浏览器能重现此问题
三星手机安装的edge浏览器未能重现

**Comment by baozhoutao** [comment]
小米自带浏览器也能重现

**Comment by baozhoutao** [comment]
手机端只考虑chrome浏览器和我们的手机客户端、企业微信客户端、钉钉客户端

**Comment by lizhenghotoa** [comment]
小米手机谷歌浏览器访问显示正常，任务先关闭
