### ISSUE TITLE
内部系统，考勤中的申请单进入查看会提示删除，实际审批单并未删除

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#4220]
操作步骤：

考勤-》加班-》任选一记录打开-》点击右上方的查看审批单按钮

测试现象：
![image](https://user-images.githubusercontent.com/92509428/216509317-2b79d2af-a078-42c2-b532-7e8acade3921.png)

**Comment by hotlong** [comment]
查一下错误日志

**Comment by chenzhipei** [comment]
![image](https://user-images.githubusercontent.com/15027092/216923451-732c68ac-5b35-4d87-9e19-db2f50b77325.png)
