### ISSUE TITLE
对象选择下拉框字段搜索功能无效

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4227]
![image](https://user-images.githubusercontent.com/6219465/216770633-167c94a2-577e-42c0-bbe1-363305a6e588.png)

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/216770759-196ba92f-69f2-4926-ae26-10df20f4b101.png)
滚动条滚动到目标值时有高亮显示效果。

**Comment by baozhoutao** [comment]
此问题是由于amis select组件不支持前台搜索可选项. 
解决方案为: 删除字段的optionsFunction ,并添加 `reference_to: objects.  reference_to_field: name`

**Comment by Flyingliao** [comment]
剩余搜索功能无效的字段清单：https://github.com/steedos/steedos-platform/issues/4298
