### ISSUE TITLE
列表视图组件未支持对象数组格式的过滤条件

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4229]
比如 项目应用里程碑对象“待完成的里程碑”视图报错，里面就是用的对象数组格式，这种格式是之前老版本列表视图右侧过滤器上保存的格式，不兼容的话，就要一个一个改掉，改成数组包裹数组的格式。

![image](https://user-images.githubusercontent.com/6219465/216771334-f631d7a1-7b66-4f14-911e-4fd69ce8bd2a.png)

**Comment by lizhenghotoa** [comment]
列表视图配置文件中看起来没有问题
<img width="928" alt="image" src="https://user-images.githubusercontent.com/26241897/216869323-1331a9a1-00cd-47a7-bfa3-7a1d0f76d29a.png">

**Comment by yinlianghui** [comment]
后续客户可能从2.3升级到2.4，如果是这种情况的列表视图，就算改好列表组件兼容这种格式，列表视图设置界面的过滤器（amis 过滤器设计器）也要兼容转换下才能支持在后台设置列表视图过滤条件。

![image](https://user-images.githubusercontent.com/6219465/216874492-04df6fdb-827d-42a2-b5b6-baa06b3eaa8b.png)
