### ISSUE TITLE
为对象的all视图自定义的微页面会影响到该对象作为子表时的显示效果

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4233]
- 子表目前是使用的对象的all视图取要显示的列及其过滤条件这是规则。
- 造成这个bug的原因见issue：清理前端相关表组件代码，不应该调用列表视图getListSchema函数 #4226
![image](https://user-images.githubusercontent.com/6219465/216773175-b41c186e-6fae-448c-9626-09fd4585befe.png)

![image](https://user-images.githubusercontent.com/6219465/216773136-b02e48bc-194a-46cc-8ec8-9160c6ebb463.png)

**Comment by hotlong** [comment]
在相关任务中测试确认
