### ISSUE TITLE
对象页面筛选搜索关闭后搜索条件未清空，加一个重置按钮

### ISSUE THREAD

**Issue by zhoudake** [steedos/steedos-platform#4239]
对象页面有个BUG,就是如果设置了搜索选项搜索了一次,然后在把搜索选项全部去掉的话这个页面就一直是这个筛选条件了
这是原始表单
![image](https://user-images.githubusercontent.com/38929839/216918662-9e6bb69c-8309-48c1-9b75-f03dea82db2f.png)
这是加了条件搜索之后的
![image](https://user-images.githubusercontent.com/38929839/216918734-f4597237-56fe-48c5-931f-42bf13b69388.png)
这是删除了条件刷新后的页面
![image](https://user-images.githubusercontent.com/38929839/216918817-7a22a6e2-00e7-469c-911a-df39a585798b.png)

**Comment by hotlong** [comment]
搜索条件会自动记录，不过应该加一个搜索重置的按钮

**Comment by zhoudake** [comment]
> 搜索条件会自动记录，不过应该加一个搜索重置的按钮
那么页面至少应该在关闭搜索后展示全部数据吧,否则容易让用户产生误解认为是一个BUG

**Comment by hotlong** [comment]
相关任务 列表搜索功能添加重置搜索条件功能 #4242
