### ISSUE TITLE
选人控件已选择值在编辑时显示成了id

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4244]
![image](https://user-images.githubusercontent.com/6194462/217210243-f08e90f5-a686-4c12-a423-fb7f7b017b53.png)
![image](https://user-images.githubusercontent.com/6194462/217210302-81010cc3-2fc8-46a2-b86a-419b5ca74d69.png)

**Comment by yinlianghui** [comment]
是Object字段类型子字段为选人字段时才有问题，已经包选人组件之前复杂的逻辑代码全部移除，通过增加ObjectForm组件的hiddenOn脚本，只在表单初始化完成后（包括新建和编辑）才显示amis form。

**Comment by yinlianghui** [comment]
新建时暂时请求一个返回空值的GraphQL接口，后续处理字段默认值时再补上请求真实的表单字段值初始化功能接口。
