### ISSUE TITLE
3000设置中查看任意人员信息有报错

### ISSUE THREAD

**Issue by xiaokedou5951** [steedos/steedos-platform#4250]
![image](https://user-images.githubusercontent.com/61674418/217473512-2edd811a-8a97-4d86-80d6-bd577a1547a0.png)
![企业微信截图_16758249705976](https://user-images.githubusercontent.com/61674418/217473557-86079bc2-d687-4d66-bcff-d19c6e4e2354.png)

前端代码版本：当前最新
后端代码版本：2.3.5

**Comment by hotlong** [comment]
服务端需要升级到 2.4.0 beta 版

**Comment by xiaokedou5951** [comment]
使用2.4.0-beta.19版本，仍然有错
