### ISSUE TITLE
新增微页面-关于，显示魔方系统信息和版本号

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4256]

**Comment by hotlong** [comment]
暂时在前端输入 Builder.settings 可以查看

**Comment by yinlianghui** [comment]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/6219465/226228697-10f87f64-d20a-4358-8519-9bd5950f05eb.png">

**Comment by tujiajun** [comment]
资产包，amis版本号，CDN服务器,rootUrl,魔方版本号
