### ISSUE TITLE
3000设置查看人员仍然有错，后台代码已升到2.4.0-beta.19

### ISSUE THREAD

**Issue by xiaokedou5951** [steedos/steedos-platform#4257]
https://github.com/steedos/steedos-platform/issues/4250#issue-1575684788

补充：
![image](https://user-images.githubusercontent.com/61674418/217708494-c8a616d5-405f-4c26-86d8-f5b1020e4635.png)
人员上有业务字段，特此说明

人员对象字段：
![image](https://user-images.githubusercontent.com/61674418/217709032-84e80eaa-cd36-4fd7-8ad1-c90b678a67aa.png)

**Comment by hotlong** [comment]
![image](https://user-images.githubusercontent.com/50353452/217712904-96ed3e86-2e6e-4318-a68d-01f76cc9bdc3.png)

**Comment by yinlianghui** [comment]
2.3和2.4都在上述报错的地方增加的空值判断，由于我们没有重现这个问题，请在新版本发出后自行测试。
