### ISSUE TITLE
记录类型微页面设计器中拖动单个相关表发布后有bug

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4258]
- [x] 相关表标题未显示记录数量
- [x] 相关表记录中部分字段显示了脚本源码

![image](https://user-images.githubusercontent.com/6219465/217712274-665052da-d7de-4838-bf82-2fa7e61caaa6.png)
![image](https://user-images.githubusercontent.com/6219465/217712392-3e56f291-ed34-4421-bba5-c4fa6ae84d3a.png)

**Comment by yinlianghui** [comment]
lookup字段是单独的问题，见：多选lookup字段只读状态都坏了 #4272

**Comment by Flyingliao** [comment]
- [x] 相关表标题未显示记录数量：https://gitlab.steedos.cn/steedos/steedos-webapp-nextjs/-/commit/860ad661f4af9b72abe5bc085e1cd2b0a00f16f1
