### ISSUE TITLE
审批王的按钮被遮挡

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4259]
![ffcbe6bdd30a96c8505e0e3e8064348](https://user-images.githubusercontent.com/7665279/217725785-97e7dd22-d797-4adf-905e-130d15b2b1f7.png)
![cbc30970a53cd7696e2698f13c1c6a2](https://user-images.githubusercontent.com/7665279/217725963-3dbe7193-06b2-4adf-ba4c-f5f0c12fee67.png)

**Comment by hotlong** [comment]
[](url)
