### ISSUE TITLE
在记录详细页面新建“相关子表”对象时，显示的列字段功能有bug，非常不好用

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4266]
1.如果一进入表单，先在“显示的列”添加一列，这时再切换“相关对象”时，“显示的列”的“字段”选项没有级联变更，而且只能删除“显示的列”行重新 设置才行。
2.“显示的列”列表右侧操作按钮，点击x的话，整个显示的列全被清空了。

问题1的方案应该是在“相关对象”字段未填写时，先不要显示“显示的列”字段。

![image](https://user-images.githubusercontent.com/6219465/217781256-c5112402-9846-42ec-9757-177280a06e55.png)

**Comment by baozhoutao** [comment]
不应该出现此页面
