### ISSUE TITLE
Creator.odata.update 执行慢

### ISSUE THREAD

**Issue by aundis** [steedos/steedos-platform#4268]
![image](https://user-images.githubusercontent.com/61673908/217981011-788ed65a-6d42-46ed-a197-cc7bc7b09a97.png)

**Comment by choose6** [comment]
![image](https://user-images.githubusercontent.com/61673908/217985708-86632bcc-ff67-44bb-9af0-af77fd91316e.png)
使用 graphql 性能有所提高, 修改5条耗时800ms左右.

但是在批量修改的时候, 这个性能还是不够用

**Comment by choose6** [comment]
![image](https://user-images.githubusercontent.com/61673908/217987546-ad0a6c2c-8430-46b5-82bf-9daf12ddf29c.png)
这个是没有触发器的对象, 修改了5条数据  耗时 450ms 左右
但是在批量修改的时候, 这个性能还是不够用
