### ISSUE TITLE
触发器发送邮件时调用ObjectQL对象进行数据操作报错

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#4274]
如题，在触发器中，发送邮件前需要查询创建人相关信息，调用ObjectQL对象进行查询操作，调用邮件发送方法时报错。如果不调用ObjectQL对象进行数据库操作，直接发送一封邮件不报错，且邮件发送成功。
测试环境:windows10+mongodb4.4+node14.20.0
![微信图片_20230210122958](https://user-images.githubusercontent.com/62589030/218001122-5e9d1f5c-4303-4c74-a777-3269dd48b59a.png)

![微信图片_20230210123002](https://user-images.githubusercontent.com/62589030/218001135-dfbd56da-5875-4193-bfc9-cfffba6f4da1.png)

**Comment by sunhaolin** [comment]
在Fiber中运行`Email.send(options)`
```js
Fiber(function () {
  Email.send(options)
}).run();
```
