### ISSUE TITLE
设置--人员查看界面希望可恢复按部门查看人员模式

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4275]
2.4
![1676007085567](https://user-images.githubusercontent.com/7665279/218008930-a617af53-7d3c-4614-810c-59161b3024f1.png)
原界面
![1676007157079](https://user-images.githubusercontent.com/7665279/218009105-390896b1-5e2f-48dd-a137-aacf5226b1a6.png)

**Comment by tujiajun** [comment]
platfrom的内容在_#4275_add_organizations_in_space_users_list分支上，widgets上的内容在data组件调整分支上
