### ISSUE TITLE
列表页微页面点过预览设计器页面就坏了

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4296]
控制台报错信息：
Failed to load resource: the server responded with a status of 404 ()
beta.builder.steedos.com/graphql:1          Failed to load resource: the server responded with a status of 404 ()
76-308587666769544e.js:1 Error: 接口报错："<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Method>POST</Method><ResourceType>OBJECT</ResourceType><RequestId>9BFVHKYQ0X5ZBAKZ</RequestId><HostId>H/EF67DihwtY9ZXfCs3vH6D/OI35JdgQx+gc5ZeSg3q4Wakt0MRdN1+YBz5STEo3K/B8bDEZ6vE=</HostId></Error>"
    at amis-49e3a89ddf3e3c78.js:1:21955
    at main-91d0a3db4a7ea45d.js:1:114622
    at Object.next (main-91d0a3db4a7ea45d.js:1:114727)
    at r (7376-2675ba396237942d.js:1:211585)
    at a (7376-2675ba396237942d.js:1:211788)
(anonymous) @ 76-308587666769544e.js:1
cbcfd327-a777f498df202798.js:1 [Notify] error 接口报错："<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Method>POST</Method><ResourceType>OBJECT</ResourceType><RequestId>9BFVHKYQ0X5ZBAKZ</RequestId><HostId>H/EF67DihwtY9ZXfCs3vH6D/OI35JdgQx+gc5ZeSg3q4Wakt0MRdN1+YBz5STEo3K/B8bDEZ6vE=</HostId></Error>"
notify @ cbcfd327-a777f498df202798.js:1
2AmisObjectTable.tsx:46 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'appId')
    at AmisObjectTable.tsx:46:43
    at tslib.es6.js:102:23
    at Object.next (tslib.es6.js:83:53)
    at tslib.es6.js:76:71
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:72:12)
    at Object.AmisObjectTable [as class] (AmisObjectTable.tsx:11:44)
    at amis-49e3a89ddf3e3c78.js:1:11428
    at ua (framework-4476b420910bf56f.js:1:84585)
    at Tu (framework-4476b420910bf56f.js:1:103474)
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/218420578-a3696ce6-a0b2-4328-953e-224ee1d34162.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/218420674-53f7f2cc-87ea-40bb-8179-36c7c3a9fdd1.png">

**Comment by hotlong** [comment]
有问题的时候，控制台的错误信息粘贴一下
