### ISSUE TITLE
设计器中列表视图选项最多只能看到三个列表视图，四个以上的情况就选不全了

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4297]
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/26241897/218423040-c0ce8734-6635-4f7c-b74a-429cac474cea.png">

**Comment by baozhoutao** [comment]
未能重现, 可选择的视图必须是 `共享视图到工作区`
![image](https://user-images.githubusercontent.com/6194462/223037545-a329e915-8c86-4a16-a5df-076f68a0b60b.png)
