### ISSUE TITLE
ObjectForm加载字段时，自动识别defaultValue属性

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4307]

**Comment by yinlianghui** [comment]
修正后只读字段默认值与之前2.3版本规则一样：
- 要求填写后台的公式字段公式，固定值也要求用引号括起来，比如`"aaaa"+"->1"`表示两个字符串相加。运行后值为`aaaa->1`
- 只读字段不会提交到服务端，其值由服务端触发器执行字段公式计算并更新字段值。
- 只读字段如果配置了默认值，在前台新建记录界面中会显示为公式表达式本身而不是运算后的结果（因为前端无法运算后台的字段公式表达式）。

#### 新建记录时只读字段显示为公式表达式本身效果
<img width="1040" alt="企业微信截图_7a869e45-0169-4b07-870b-6628993329fd" src="https://user-images.githubusercontent.com/6219465/220664117-d9cf9d68-2fcf-43ac-95c8-4b0f1035600d.png">

#### 新建记录后字段值会更新为字段公式运算结果
<img width="1160" alt="企业微信截图_08758040-0408-408f-8348-068525f2e936" src="https://user-images.githubusercontent.com/6219465/220664161-6e442f68-7286-4476-8eeb-bcd015b6fba5.png">
