### ISSUE TITLE
下拉框支持配置颜色，client端并显示

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#432]

**Comment by yinlianghui** [comment]
最后规则：
- 支持yml中配置选项颜色
- 支持零代码界面配置对象字段时输入选项内容时配置选项颜色
- 支持下拉框列表对象，即Picklist中自定义下拉框选项时配置选项颜色
- 零代码配置界面，新建、修改相关记录时，触发器会校验相关颜色值是否格式正确
- 颜色值只支持16进制颜色代码，前缀#号可省略
- 文档已更新
