### ISSUE TITLE
QHD项目中定制的审批王功能，迁移到标准版

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4323]
- [x] 催办按钮，https://github.com/steedos/steedos-project-hbport/issues/73
- [x] 历史步骤中显示通讯信息，https://github.com/steedos/steedos-project-hbport/issues/79
- [x] 批量取消传阅 https://github.com/steedos/steedos-project-hbport/issues/77
- [x] 领导批示后通知文书【测试未通过】 https://github.com/steedos/steedos-project-hbport/issues/75

以下任务只需测试
- [x] 批量取消分发 【确认无需开发】 https://github.com/steedos/steedos-project-hbport/issues/78
- [ ] 自动归档 【待确认】 https://github.com/steedos/steedos-project-hbport/issues/76

**Comment by marchtian** [comment]
42.46 测试，批量取消分发 ，确认无需开发

**Comment by marchtian** [comment]
42.46 测试，领导批示后通知文书 ，测试未通过，未在 push相应表中 生成记录

**Comment by sunhaolin** [comment]
更新用户手机号为验证通过，数据库脚本：
`db.users.update({}, { $set: { mobile_verified: true } }, { multi: true })`

**Comment by marchtian** [comment]
历史步骤中显示通讯信息，应只针对系统配置的少数用户，目前是所有用户都 显示出通讯信息了

**Comment by marchtian** [comment]
取消传阅，未出现待多选的传阅选项
![image](https://user-images.githubusercontent.com/7553007/224883426-a9599b32-6abf-4236-a568-64cddc8f4f0d.png)

**Comment by marchtian** [comment]
历史步骤中显示通讯信息，应只针对系统配置的少数用户，目前是所有用户都 显示出通讯信息了： 测试，已按配置显示了

**Comment by marchtian** [comment]
批量取消传阅：42.46测试OK
