### ISSUE TITLE
lookup关联对象为树对象，且配置为弹出模式时，未使用按节点动态加载数据模式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4329]
目前是一次性加载数据，且启用了翻页
- 应该不要翻页，比如请求时top设置为1000而不是20
- 应该按节点动态加载，默认只加载根节点，而不是一次性加载所有数据
- lookup为选部门字段时也有这个问题
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/6219465/220125813-136778cc-b6b0-4fc2-bd83-90e0019f31f3.png">

**Comment by hotlong** [comment]
相关任务 https://github.com/steedos/steedos-platform/issues/4330
