### ISSUE TITLE
内部系统->审批王,未提交的申请单会在待审核栏中显示，点击后无法打开，界面一直提示刷新

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#4335]
操作步骤： 
内部系统-》审批中心-》待审核

测试结果：
待审核中会有未提交的审批单，若此时点击此类申请单无法打开，界面一直提示刷新

预期结果：
未提交的申请单应保存在草稿栏中

![image](https://user-images.githubusercontent.com/92509428/220291683-6847ecd8-8b87-42ae-ba85-74b0794e2d0a.png)

**Comment by baozhoutao** [comment]
此问题是数据异常,需要通过脚本修正

**Comment by sunhaolin** [comment]
```js
db.getCollection('instance_tasks').remove({is_finished:false, instance_state:'draft', forward_from_instance: null, distribute_from_instance: null})
```
