### ISSUE TITLE
接口avatar/:userId 返回的头像地址不支持内外网

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#434]

**Comment by yinlianghui** [comment]
无法重现：
- 经测试fs那边外网之前是外网访问时头像显示不出来，现在正常了。
- 我本地跑服务，测试下来无论rootURL是否带后缀，内外网访问头像也是正常的。

**Comment by yinlianghui** [comment]
- 已处理，只要把rootUrl配置为127.0.0.1，使用其他电脑访问对应ip地址就能重现该问题。
- 把`Steedos.absoluteUrl`换成`Creator.getRelativeUrl`，打日志及PC上测试查看头像ip都正常了。
- 手机上需要打包后才能测试，不过从打出的日志来看应该没问题。
