### ISSUE TITLE
审批，分发操作，可选流程不对，不应为所有可以提交的流程

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4344]

**Comment by marchtian** [comment]
分发对象（选人）也不对，应从 流程的“分发设置” 取得

**Comment by sunhaolin** [comment]
> 分发对象（选人）也不对，应从 流程的“分发设置” 取得

待选人控件支持指定范围 https://github.com/steedos/steedos-platform/issues/4504

**Comment by sunhaolin** [comment]
> 



> 分发对象（选人）也不对，应从 流程的“分发设置” 取得

待选人控件支持，选择范围变化时自动清空已选项
