### ISSUE TITLE
审批，选人控件，无需显示隐藏的部门

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4352]
![image](https://user-images.githubusercontent.com/7553007/220841336-2513776a-781e-415f-b07e-0ae72c540d88.png)

**Comment by hotlong** [comment]
重复

**Comment by marchtian** [comment]
对象选人，已OK
审批王里选人，仍然会列出 隐藏的部门
![image](https://user-images.githubusercontent.com/7553007/235044103-c078233c-17d9-4e89-bc76-13725309f9bf.png)

**Comment by marchtian** [comment]
已OK
