### ISSUE TITLE
新建操作按钮时，显示位置属性下拉选项清单不应该显示左侧icon

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4371]
![image](https://user-images.githubusercontent.com/6219465/221397867-1927d1e8-3d4c-4829-a63f-5a6229b2940d.png)

**Comment by Flyingliao** [comment]
此图标代码中配置了，显示不出来是由于部分图标名称不存在了 且 显示icon的功能代码存在考虑不全。
