### ISSUE TITLE
增加amis微页面（九宫格）

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4378]
https://github.com/steedos/steedos-project-hbport/issues/90
可作为 手机上的第一个应用程序的选项卡，成为手机版登录后的页面

列出 “显示在手机菜单中的” 应用程序 。

**Comment by marchtian** [comment]
![QQ图片20230228111911](https://user-images.githubusercontent.com/7553007/221745042-db91b519-df27-4a74-938b-81cfa1f5a2f8.png)

**Comment by Flyingliao** [comment]
- [ ] 手机app报错
 
<img width="334" alt="image" src="https://user-images.githubusercontent.com/41402189/223331932-175f2b47-0b36-4a3a-a2a9-d9e429f7b781.png">

 - [ ] 控制左侧弹窗功能的左上角的图标失效了，点击不会弹出/隐藏弹窗。
 
<img width="328" alt="image" src="https://user-images.githubusercontent.com/41402189/223332271-13c78142-c27b-4529-a772-7b9316846a0f.png">
