### ISSUE TITLE
新建操作按钮时类型切到amis button时，下面的执行的脚本没有消失

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4397]
有可能最新代码的visibleOn功能坏了
![image](https://user-images.githubusercontent.com/6219465/222061329-90eca36b-a656-4a5f-b9fa-fe967b5ff48d.png)

**Comment by baozhoutao** [comment]
此问题由于上下文中的 `formData` 丢失导致

**Comment by yinlianghui** [comment]
已无此问题，默认选项也已改为amis button
