### ISSUE TITLE
操作按钮列表页不显示“显示位置”字段值

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4400]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/222062955-8262d9b8-80e5-42f0-80bd-215d72d432ce.png">

**Comment by Flyingliao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/41402189/ea40fe2f-8c21-4228-84ea-f3f32985567d)
