### ISSUE TITLE
工作流规则-时间触发器字段更新选项样式需要调整

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4418]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/222107448-fbf540f8-10e2-4b6b-aebf-c56db12dbd3c.png">

**Comment by Flyingliao** [comment]
amis相关格式已作调整：选项内容过长，内容会省略，鼠标停留几秒钟会有提示窗口显示选项内容。
<img width="1114" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/849049bc-5883-442e-9796-235ea0b8c9cf">

另外可以手动调整列宽，以便选择选项时查看具体选项内容。
<img width="1084" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/4fc17ed9-8e81-4f7d-82c1-f20f3b9f4078">

**Comment by Flyingliao** [comment]
<img width="274" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/82a371ce-3f40-492b-83f4-435254028417">
