### ISSUE TITLE
新增累计汇总字段时，要汇总的对象 字段选择项为空，实际有子表

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4421]
版本："@steedos/service-enterprise": "2.4.0-beta.36"

**Comment by yinlianghui** [comment]
暂时先改为列出所有对象了，后续在新任务中重新处理只列出子表对象的问题，见：新增累计汇总字段时，要汇总的对象字段选择项列出了所有选项，应该只列表子表对象 #4464
