### ISSUE TITLE
新建汇总类型的字段时，要汇总的对象下拉菜单未正常列出子表对象

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4427]
此问题是因为Creator.getObject函数重写了，应该是为了删除bootstrap接口改动
![image](https://user-images.githubusercontent.com/6219465/222763199-10531be0-63f8-408e-92eb-db0a0f21f9b0.png)

**Comment by hotlong** [comment]
重复。https://github.com/steedos/steedos-platform/issues/4421
