### ISSUE TITLE
API Key详细页 复制API Key 按钮点击无反应，不能复制

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4430]
![image](https://user-images.githubusercontent.com/6194896/222938904-cd48d154-f0aa-4b34-8c5a-d48639e13ae7.png)

正常点击后会提示 复制成功

版本： "@steedos/service-enterprise": "2.4.0-beta.36"

**Comment by Flyingliao** [comment]
最新版本无此问题

**Comment by hotlong** [comment]
复制 API Key 不能成功呀
