### ISSUE TITLE
前台显示的默认过滤字段没有根据列表视图配置的字段顺序进行展示

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4442]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26241897/223003089-c910d3bc-c55b-4983-b9dc-7eb41f7bbb40.png">

**Comment by baozhoutao** [comment]
此问题 需要和 https://github.com/steedos/steedos-platform/issues/4384 一起处理.
