### ISSUE TITLE
页面布局子表过滤条件未生效 

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4443]
```
内容为 console.log(this)
```

![image](https://user-images.githubusercontent.com/6194896/223014225-105f2663-8090-4f23-bada-83fd7cd95bf7.png)

![image](https://user-images.githubusercontent.com/6194896/223014261-188f84d5-4ad5-4c7e-86c5-243405b8cf64.png)

**Comment by Flyingliao** [comment]
目前不支持
![image](https://user-images.githubusercontent.com/41402189/223032537-b5d3357c-e66a-4868-b337-c01b0ecf4f9d.png)

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/223324484-43397ab0-dbeb-498b-bf3b-ea4f6df7093a.png)
