### ISSUE TITLE
列表视图的显示字段和过滤条件中无主分部和所属分部两个字段

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4447]
![image](https://user-images.githubusercontent.com/7665279/223056358-c27dd256-281f-4441-9a95-33ed2a703c5d.png)

**Comment by baozhoutao** [comment]
此问题需要将 分部字段、所属分部字段设置为可见后, 才可以选择. 
主分部、所属分部默认为 hidden = true
