### ISSUE TITLE
示例：ObjectQL 事务语法

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4455]
https://www.mongodb.com/docs/manual/core/transactions/

**Comment by hotlong** [comment]
objectql.getDataSource().adapter

**Comment by hotlong** [comment]
const driver = datasource.adapter;
await driver.connect();
await driver.collection(query.collection).find(filter, options).count();

**Comment by baozhoutao** [comment]
此问题需要考虑session的传递
