### ISSUE TITLE
查看审批单按钮，点击报“审批单已删除”

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4461]
HBPort项目新发
![image](https://user-images.githubusercontent.com/7553007/223373617-a3065af7-a10c-41ba-b31d-ade4f6219785.png)
https://github.com/steedos/steedos-project-hbport/issues/95

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4446

**Comment by marchtian** [comment]
测试已OK，注意可以因缓存导致仍报错、清缓存后即OK
