### ISSUE TITLE
对象字段列表页出现其他对象的字段

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4466]
- 不是相关表

![图片已粘贴至2023-3-8 10-34](https://user-images.githubusercontent.com/6194896/223615732-818c9c9f-b873-4bb5-aa77-370c063c2a54.png)

版本："@steedos/service-enterprise": "2.4.0-beta.39"

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/4467

**Comment by sujiahao66** [comment]
版本："@steedos/service-enterprise": "2.4.0-beta.38"中也存在这个问题
