### ISSUE TITLE
查看对象字段时，对象字段会显示所有与这个对象相关的对象的所有字段

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4467]
在对象字段的页面，页面会显示所有与这个对象有关系的对象（相关表、主子表）的所有字段
![image](https://user-images.githubusercontent.com/126655403/223616492-6a02009b-9da0-4eaf-832d-5a7742335f79.png)

**Comment by sunhaolin** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4466

**Comment by sunhaolin** [comment]
版本："@steedos/service-enterprise": "2.4.0-beta.39"
