### ISSUE TITLE
应用（apps）的属性，取消desktop与mobile的强制关联

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4472]
目前，如果mobile为true，则desktop会强制赋值为true
取消关联后，可设置3种应用：只出现在桌面、只出现在手机、同时出现

**Comment by marchtian** [comment]
(1)前台设置的情形
新建应用程序
![image](https://user-images.githubusercontent.com/7553007/223910444-56ed4579-d1a3-498b-aca4-76b8a5c67a04.png)

只勾选手机、不勾选桌面。
新建后，桌面 会被强制 赋值已选
![image](https://user-images.githubusercontent.com/7553007/223910310-091ebf6a-6f24-4a1a-bfe0-43418f8dc3f4.png)

**Comment by marchtian** [comment]
（2）代码的情形
![image](https://user-images.githubusercontent.com/7553007/223910681-4980d4ef-6f4d-498a-9d4f-98b22abd87c2.png)
设置desktop为false，结果，桌面端仍然会 显示此应用

**Comment by yinlianghui** [comment]
此问题是因为apps对象的is_creator和mobile这两个字段配置了默认值，新建时这两个默认值没生效造成的。
![Uploading image.png…]()
