### ISSUE TITLE
Amis Button弹出框中使用defaultData赋值，弹出框中的值不能正常显示

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4473]
在这个Amis的弹出框中可以读到defaultData中的值，但是不能把值从defaultData写入到弹出框，常量值可以正常写入。
![image](https://user-images.githubusercontent.com/126655403/223690894-3c649cfb-2419-49ab-a54d-bb402115f559.png)
![image](https://user-images.githubusercontent.com/126655403/223690930-31afbf5b-89ad-4e70-8a74-02223da15e64.png)
![image](https://user-images.githubusercontent.com/126655403/223690948-208801ed-5798-4898-a86f-7c055c64f22d.png)

**Comment by baozhoutao** [comment]
未能重现
