### ISSUE TITLE
使用amis重构流程记录详情页

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4483]

**Comment by lihailong220** [comment]
已同步为元数据 并新开空数据库进行测试通过

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/125853619/225839288-a85ce711-244c-4d86-a32c-0983c450ac7f.png">

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/125853619/225839358-f6d220d5-87cd-4448-97c5-9271f673ed77.png">
