### ISSUE TITLE
简档&权限集对象、设置>>>高级设置>>>审计日志的下载功能点击报错

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#4497]
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/126241326/224472014-e36e2570-e104-44f7-b47c-b147b84f4428.png">

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/126241326/224472130-ab2c2ca3-7a42-4151-9509-66ab2817886a.png">

**Comment by hotlong** [comment]
重复 对象增加开关，配置是否允许导出Excel #4506
