### ISSUE TITLE
【用户】对象的列表右上角，点击【预览】按钮会出现接口报错

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#4501]
点击用户对象的预览按钮后弹出的新窗口会报错
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/126241326/224475451-bc87eb2d-8d2d-4f24-bcac-35a20dfdf276.png">

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/126241326/224475075-7bdadffb-b7e1-4cb2-ab1c-f66d22ffe169.png">

**Comment by hotlong** [comment]
已隐藏此对象
