### ISSUE TITLE
前端订阅 steedos_keyvalues 的数据，有变化时broadcast amis event @data.changed.steedos_keyvalues

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4517]
待审核的刷新和应用的badge显示，均依赖此数据。

**Comment by yinlianghui** [comment]
> 以下示例为监听@data.changed.steedos_keyvalues事件显示badge数量：
> 
> ```
> {
>     "type": "service",
>     "body": [
>       {
>         "type": "tpl",
>         "tpl": "===${keyvalue}",
>         "inline": true,
>         "wrapperComponent": "",
>         "id": "u:65fb5cd89cdf"
>       }
>     ],
>     "onEvent": {
>       "@data.changed.steedos_keyvalues": {
>         "actions": [
>           {
>             "actionType": "toast",
>             "args": {
>               "msgType": "warning",
>               "msg": "==${event.data.keyvalue.value.workflow}",
>               "position": "top-right"
>             }
>           },
>           {
>             "actionType": "setValue",
>             "args": {
>               "value": {
>                 "keyvalue": "${event.data.keyvalue.value.workflow}"
>               }
>             }
>           }
>         ]
>       }
>     }
>   }
> ```

上面的方法有时会失效，改为下面这种从window全局变量中取数据，其中 "@data.changed.steedos_keyvalues"事件中的setValue这个action不可以少。

```
{
  "type": "service",
  "body": [
    {
      "type": "tpl",
      "tpl": "==getKeyvalues===${window:keyvalues.badge.value.workflow}",
      "inline": true,
      "wrapperComponent": "",
      "id": "u:69baefb6dd39"
    }
  ],
  "onEvent": {
    "@data.changed.steedos_keyvalues": {
      "actions": [
        {
          "actionType": "setValue",
          "args": {
            "value": {
              "keyvalue": "${event.data.keyvalue}"
            }
          }
        }
      ]
    }
  },
  "id": "u:10302d75080e"
}
```
