### ISSUE TITLE
新增操作并发会产生相同的编码，请及时处理

### ISSUE THREAD

**Issue by kevin-medsci** [steedos/steedos-platform#4519]
![image](https://user-images.githubusercontent.com/122590707/224877992-326784df-40ac-4086-998d-a7ef9347259f.png)

**Comment by kevin-medsci** [comment]
所有的新增操作，并发都会有该问题，无论是直接graphql的insert db，还是封装的新增commit操作

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/4518

**Comment by hotlong** [comment]
已处理，重复 自动编号并发多时，值会重复 #4518
