### ISSUE TITLE
审批，设置关联文件时，报错且标题未显示

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4525]
![image](https://user-images.githubusercontent.com/7553007/224919318-64ba95d0-1158-4d96-82b4-c396c5a6f0ac.png)

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/commit/cbea76020d6d54ef27cac10bce44109937b3eeaf

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/225561558-25454145-65df-4443-b10d-41065620cc52.png)
标题已显示，报错还有，待新版发布后再确认

**Comment by marchtian** [comment]
测试，已OK
