### ISSUE TITLE
列表视图amis重置功能作废，并删除@steedos-widgets/amis-lib包引用

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4532]
- 因为现在使用的是原生魔方组件
- 不是对象列表微页面，而是对象的列表视图自定义Schema
- 参考：新建表单类型微页面时, 自动生成的schema 使用 steedos-object-form 组件. #4529

**Comment by hotlong** [comment]
相关

**Comment by hotlong** [comment]
相关 列表视图启用“使用amis定义列表”后，进入设计器一片空白，控制台报错 #4556
