### ISSUE TITLE
3000服务数据导出报错“Unexpected token '<', "<!DOCTYPE "... is not valid JSON”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4535]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/225490222-1cfe918b-4f4a-4b93-9bcf-4b26d4462df5.png">

**Comment by yinlianghui** [comment]
重复： https://github.com/steedos/steedos-platform/issues/4491
