### ISSUE TITLE
台账记录详细界面右上角的查看审批单点开说单子被删除了，实际单子是在的

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4542]
看起来所有的台账记录都有这个问题。

![image](https://user-images.githubusercontent.com/6219465/225790140-eaba7623-57e1-4880-968f-015ba8b9a225.png)

**Comment by Flyingliao** [comment]
原因：当该对象开启了“发起审批”时，graphql中未返回需要的 instances 字段值。

拓展： 特定对象在开启了某些功能后，需要在返回的记录字段中额外返回对应的字段。

![image](https://user-images.githubusercontent.com/41402189/225880124-5106ade2-66a0-4ee1-abfe-6abbbe54c9bf.png)
