### ISSUE TITLE
删除微页面时界面没有跳转到微页面列表

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4544]
其他对象记录详细界面删除记录是正常的，未发现此问题。
报错：vconsole.min.js:10 There is no route for the path: /app/admin/pages/grid/?url=%2Fapp%2Fadmin%2Fpages%2Fgrid%2F
![image](https://user-images.githubusercontent.com/6219465/225793256-de6f33c8-d3de-4cb1-83b2-79bec4291405.png)

**Comment by hotlong** [comment]
未能重现
