### ISSUE TITLE
无法新增选项卡分组

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4561]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/26241897/226155946-7c888f7f-7eba-4913-8c46-f5155dbd1880.png">

**Comment by lizhenghotoa** [comment]
最新版本template项目还是存在这个问题

**Comment by yinlianghui** [comment]
当时因为这个问题固定sdk版本为2.7.2了，需要确认下2.9.0是否还有此问题。

**Comment by Flyingliao** [comment]
2.4/ 2.5最新版本正常
