### ISSUE TITLE
字段更新-选择对象后（回款记录），审批状态字段等系统字段都不能选择

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4566]
![image](https://user-images.githubusercontent.com/6194896/226235668-eae715ee-a80f-42ba-ba06-33ff3bb35618.png)

**Comment by huangyiirene** [comment]
出现了两个审批状态
![image](https://user-images.githubusercontent.com/7665279/227421052-3470ca4d-8479-4875-9b24-19aa4a97ec97.png)
