### ISSUE TITLE
新建/编辑对象记录时，弹出的lookup字段选择页，列表疑似不是 all视图

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4592]
![image](https://user-images.githubusercontent.com/7553007/226789627-a8a8b799-31bb-42e1-8ef2-2c1ae40a2dc6.png)

![image](https://user-images.githubusercontent.com/7553007/226789884-7e0cc94d-f7f5-4b19-a7f4-c99dd37fbe01.png)

另，这里的搜索的默认字段，是否也是 all视图里定义的？

**Comment by hotlong** [comment]
请按新issue格式，填写重现过程
