### ISSUE TITLE
支持使用 moleculer action 编写 Triggers 触发器

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4609]
参考： https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_triggers_context_variables.htm
支持 ctx.params 参数：

Variable | Usage
-- | --
isInsert | Returns true if this trigger was fired due to an insert operation, from the Salesforce user interface, Apex, or the API.
isUpdate | Returns true if this trigger was fired due to an update operation, from the Salesforce user interface, Apex, or the API.
isDelete | Returns true if this trigger was fired due to a delete operation, from the Salesforce user interface, Apex, or the API.
isBefore | Returns true if this trigger was fired before any record was saved.
isAfter | Returns true if this trigger was fired after all records were saved.
isUndelete | Returns true if this trigger was fired after a record is recovered from the Recycle Bin. This recovery can occur after an undelete operation from the Salesforce user interface, Apex, or the API.
id | 记录的唯一标识[string].
doc | 需要新增/修改的记录内容[json].
previousDoc | 修改/删除前的记录[json], after.update, after.delete时存在此属性.
size | The total number of records in a trigger invocation, both old and new.
userId | 当前用户唯一标识[string]
spaceId | 当前工作区[string]
objectName | 当前对象名称[string]
query | 查询数据相关参数[json], before.find时存在此属性
data | 查询结果, after.find时存在此属性
when |  当前操作，"before.find", "before.insert", "before.update", "before.delete", "after.find", "after.insert", "after.update", "after.delete"

```js
    // 在微服务中编写触发器, 开发中
    beforeSpaceUsersUpdate: {
      trigger: { 
        listenTo: 'space_users',
        when: ['before.insert', 'before.update']
      },
      async handler(ctx) {
      }
    },
```

**Comment by sunhaolin** [comment]
- [ ] when 值调整为驼峰格式， 如： ['beforeInsert', 'beforeUpdate']
