### ISSUE TITLE
相关记录的链接，不要弹出新窗口

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#461]

**Comment by yinlianghui** [comment]
详细界面左上角的返回按钮先去掉了，应该弹出窗口都改为直接打开会该按钮会乱跳，后续单独有任务处理研究要不要放开！
![image](https://user-images.githubusercontent.com/6219465/86081490-19f60300-bac8-11ea-868c-d38d31d21edb.png)

**Comment by yinlianghui** [comment]
已处理，返回按钮已经隐藏了，多测试了下，乱点操作没发现什么问题！
