### ISSUE TITLE
amis button弹框增加属性后必须重启服务后前台才能生效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4613]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/227416228-a4a2e61e-8264-437a-8ef7-73b4074c9eb5.png">

**Comment by sujiahao66** [comment]
配置字段的amis属性也是重启服务后才能生效。
![image](https://user-images.githubusercontent.com/126655403/227701205-e9cd44d7-2c64-4832-b54a-73864419206e.png)

**Comment by baozhoutao** [comment]
未能重现
