### ISSUE TITLE
字段更新--选择特定值后，页面无反应

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4614]
![image](https://user-images.githubusercontent.com/7665279/227421170-054c977a-b441-4f02-bf9f-5f823447b653.png)

**Comment by Flyingliao** [comment]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/41402189/227923585-cb3944fb-519c-4e9c-b6c9-18408ae587bd.png">
