### ISSUE TITLE
对象列表中，下拉箭头删除对象无效。

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4619]
![image](https://user-images.githubusercontent.com/126655403/227835644-4b4c070c-fd83-41b2-8096-6ed10954086d.png)

**Comment by Flyingliao** [comment]
原因：未获取到记录ID
![image](https://user-images.githubusercontent.com/41402189/227836042-5495f7e7-4ddc-41c0-82e7-c0d4ddf6a724.png)
