### ISSUE TITLE
SQL Server 数据源连接失败：Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#462]
![image](https://user-images.githubusercontent.com/50353452/85967396-ef874580-b9f4-11ea-889e-c7ebf647967d.png)

以下配置能不能写到内核中作为默认参数？
![image](https://user-images.githubusercontent.com/50353452/85967421-fada7100-b9f4-11ea-919c-8703369e305b.png)

**Comment by baozhoutao** [comment]
此问题需要先确认根本原因。encrypt参数不是必须的。

**Comment by hotlong** [comment]
![image](https://user-images.githubusercontent.com/50353452/85968823-a6d18b80-b9f8-11ea-82eb-45737056447d.png)

**Comment by baozhoutao** [comment]
2008r2 也有此问题，且配置 encrypt:false 后还是报此错误

**Comment by baozhoutao** [comment]
https://github.com/tediousjs/tedious/issues/914

**Comment by baozhoutao** [comment]
此问题解决方案：
安装sql server 1.2TLS补丁
启动命令添加向后兼容标识:  `--tls-min-v1.0` 。 比如： `node server --tls-min-v1.0`
连接选项添加配置： `encrypt: false`
