### ISSUE TITLE
配置时间触发器不生效

### ISSUE THREAD

**Issue by liuyjdev** [steedos/steedos-platform#4621]
配置了一个早于合同时间1小时触发的通知，没有生效
![企业微信截图_16798812396035](https://user-images.githubusercontent.com/44960306/227823792-291eb583-38dc-4834-86cb-812d0f708872.png)

![企业微信截图_16798813579154](https://user-images.githubusercontent.com/44960306/227823782-3542d8fb-fb06-4383-b263-fcc595ad7ca7.png)

![企业微信截图_16798812478972](https://user-images.githubusercontent.com/44960306/227823769-72b60a05-5d23-48d9-a0fc-290d8aaaca77.png)

**Comment by hotlong** [comment]
文档任务 https://github.com/steedos/steedos.com/issues/197
