### ISSUE TITLE
[Bug]: 自定义对象记录详情页，相关表 数量及新建按钮未显示

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4624]
### Description

![image](https://user-images.githubusercontent.com/6194896/228107430-a318393b-cd0e-4648-bc60-a9d1ac73996f.png)

### Steps To Reproduce 重现步骤

1. zyss 新建合同对象的对象表单微页面，拖入相关表组件（进项记录）
2. 进入合同详情页

### Version 版本

2.4.7

**Comment by Flyingliao** [comment]
提交的代码地址： https://github.com/steedos/steedos-widgets/commit/a8214b26ab835dab639f84ea0726d912916c399e
