### ISSUE TITLE
[Bug]: 流程信息同步到台账后，子表的创建时间和修改时间没有

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4626]
### Description

流程信息同步后自动显示进入台账的创建时间，修改时间第一次默认为创建时间

### Steps To Reproduce 重现步骤

![1679970375524](https://user-images.githubusercontent.com/7665279/228111307-454c0602-01ab-479c-84d2-e0bc00388c46.png)

### Version 版本

2.4.7

**Comment by sunhaolin** [comment]
2.4.12 已正常
