### ISSUE TITLE
[Feature]: 查看审批单等，点击弹框，显示“连接中”

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4630]
### Summary 摘要

显示“连接中”，可能会被误解为服务异常

### Why should this be worked on? 此需求的应用场景？

![image](https://user-images.githubusercontent.com/7553007/228161198-f1a4e137-e567-4d98-ac6f-5b186a1b633e.png)

**Comment by hotlong** [comment]
2.5 版本已作废此页面
