### ISSUE TITLE
[Bug]: 图标字段有些选项值没有图标

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4635]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/228411506-7c1f2a6b-2b72-4931-b411-4d07e939d8d3.png">

### Steps To Reproduce 重现步骤

1. 新建应用程序；
2. 填写图标字段，字段值下拉可以看到效果。

### Version 版本

2.4.8-beta.3

**Comment by hotlong** [comment]
图标的可选项清单哪里来的？/assets 下的文件应该版本对应。
