### ISSUE TITLE
对象流程，复制（单选新建）后，表单字段 丢了。

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#464]
![图片已粘贴至2020-6-29 13-33](https://user-images.githubusercontent.com/7553007/85976640-8bbd4680-ba0d-11ea-8105-b5c3aa1dc97f.png)
![图片已粘贴至2020-6-29 13-39](https://user-images.githubusercontent.com/7553007/85976900-1b62f500-ba0e-11ea-93c5-f62db2a0bd90.png)

![图片已粘贴至2020-6-29 13-33-2](https://user-images.githubusercontent.com/7553007/85976651-8fe96400-ba0d-11ea-891e-c4b6aac00cab.png)

**Comment by yinlianghui** [comment]
源码、108测试下来都正常的
