### ISSUE TITLE
[Feature]: moleculer actions 触发器，兼容运行旧触发器

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4647]
```js
    triggerSpaceUsers: {
      trigger: { 
           listenTo: 'space_users',
           when: ['beforeInsert'],
      },
      async handler(ctx) {
      }
    }
```
### 支持新触发器

- 修改 @steedos/service-metadata-triggers
- 监听 $services.changed 事件，扫描当前 service 下的 actions, 对于其中定义的 trigger 参数进行解析。
- 注入到 trigger 注册中心。

### 兼容旧触发器

- 调整 trigger.js 加载模式，在对应的软件包服务生成 trigger actions。
- 需要兼容旧的 trigger 参数

**Comment by sunhaolin** [comment]
兼容旧触发器 新建分支
