### ISSUE TITLE
[Feature]: SteedosUI.showModal(stores.ComponentRegistry.components.ObjectTable 允许增加一些自定义按钮

### ISSUE THREAD

**Issue by aundis** [steedos/steedos-platform#4659]
### Summary 摘要

SteedosUI.showModal(stores.ComponentRegistry.components.ObjectTable  允许增加一些自定义按钮

### Why should this be worked on? 此需求的应用场景？

比如选择的时候数据还没有创建, 就可以直接点击窗口上面的新建按钮, 快捷创建, 不需要退出来创建后再返回modal窗口中选择

**Comment by hotlong** [comment]
建议升级到 2.4 使用 amis 设计 自定义按钮
