### ISSUE TITLE
[Bug]: 任务详细页相关项(type: lookup, reference_to: !<tag:yaml.org,2002:js/function>)字段未显示

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4661]
### Description

![image](https://user-images.githubusercontent.com/6194896/229279738-b4413cbe-93bd-467c-97c8-5625d280c90c.png)

### Steps To Reproduce 重现步骤

1、办公模块新建任务

### Version 版本

2.4.8

**Comment by Flyingliao** [comment]
修改代码地址： https://github.com/steedos/steedos-platform/commit/c8bb715b106027d9cda8d7777c2ad8081a61b55f
