### ISSUE TITLE
[Bug]: 审批台账记录详细页面提请审批按钮未显示出来

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4667]
### Description

华炎内部系统加班申请台账上也没有显示这个按钮。

### Steps To Reproduce 重现步骤

1. 进入绑定了审批流程的对象列表，比如从考勤应用进入“加班”对象
2. 新建记录，右上角没有显示提请审批按钮

### Version 版本

2.4.9，本地platform和华炎内部系统都有问题

**Comment by Flyingliao** [comment]
普通用户看不到“发起审批”按钮。
原因：Creator.getRecordPermissions('attendance_used', '642a4e4401f345001f669243', Meteor.userId()) 获取的 allowEdit为false。
