### ISSUE TITLE
[Bug]: 选择框字段设置默认值后，前台新建数据保存后选择框字段为空

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4668]
### Description

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/26241897/229417184-b87960c7-c1e7-4d12-876c-09c44b882103.png">

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/26241897/229417123-e117d85d-ed21-4fd6-b54e-d9b5e1b077a1.png">

### Steps To Reproduce 重现步骤

1. 对象创建选择框字段，并配置默认值；
2. 创建对象数据，新建时选择框能带出默认值；
3. 保存数据后，记录中选择框字段显示为空。

### Version 版本

2.4.9

**Comment by Flyingliao** [comment]
最新代码未重现
