### ISSUE TITLE
[Bug]: 从台账已发起流程，但“发起审批”按钮还在

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4674]
### Description

从台账发起流程后，“发起审批”按钮应转化为“查看审批单”

### Steps To Reproduce 重现步骤

<img width="1345" alt="1680507047730" src="https://user-images.githubusercontent.com/7665279/229441169-58c94e9f-0caf-4caa-94ed-c476d4fcd807.png">

### Version 版本

2.4.9

**Comment by sunhaolin** [comment]
意向信息配置了页面布局，发起审批按钮显隐依赖 instances 字段，需要页面布局添加 审批单 字段
