### ISSUE TITLE
[Bug]: 翻译grid字段失败

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#4675]
### Description

![图片已粘贴至2023-4-3 15-37](https://user-images.githubusercontent.com/126241326/229443561-7ee86a02-25b0-4e41-927c-fd25998632db.png)

### Steps To Reproduce 重现步骤

1. 前往字段更新
2. 选择对象为`项目`和要更新的对象为`项目`(目前只发现项目对象中有)
3. 选择需要更新的字段，下拉框拉到下方即可

### Version 版本

2.4.9

**Comment by baozhoutao** [comment]
重现方式:  在数据库中扩展了软件包中的对象字段, 重启服务后, 对象从base部分继承的字段国际化异常.
