### ISSUE TITLE
[Bug]: 在对象的页面布局中调整含有分组字段的顺序无效

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#4677]
### Description

通过项目对象的页面布局调整含有分组的“待完成任务”和“待解决问题”字段顺序，不会保存和生效。
![image](https://user-images.githubusercontent.com/41402189/229457030-ad36eb10-cee8-4c07-ac4d-2c7ae8ace26e.png)
![image](https://user-images.githubusercontent.com/41402189/229457117-6d854383-25d1-4eb9-8312-2e7b5a304718.png)

### Steps To Reproduce 重现步骤

1、进入项目对象的默认页面布局
2、点击“自定义”按钮
3、调整含有分组字段的显示顺序

![image](https://user-images.githubusercontent.com/41402189/229458131-0218778b-41d4-4c5a-9bd3-292a348ff0ef.png)

![image](https://user-images.githubusercontent.com/41402189/229458294-8768a901-c655-4f06-a278-4005202898c4.png)

### Version 版本

2.4.9

**Comment by tujiajun** [comment]
分组的顺序可以在设置分组中调整
![image](https://user-images.githubusercontent.com/127007861/230580153-ec43ba14-6988-4951-beed-db4a7def6d9e.png)
但是设置分组中存在bug，显示的分组不全
