### ISSUE TITLE
creator源码新建任务时，选择相关项后保存会报错：相关项必须是一个对象

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#468]
![image](https://user-images.githubusercontent.com/6219465/86074048-b1068f00-bab7-11ea-9c90-0271bb7a2928.png)

- 108上是好的
- 应该是因为跑源码时所有对象的enable_tasks都是空的，这里其实应该相关项下拉列表也空着才对，不应该有选项让用户选择！

**Comment by yinlianghui** [comment]
等accounts改为系统对象后，放开其enable_tasks后，这个问题应该就不存在了！

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/469
