### ISSUE TITLE
[Bug]: amis设计器内无法在visibleOn中通过formFactor来判断是否在手机端显示

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#4681]
### Description

列表页面与应用程序页面都不行
![image](https://user-images.githubusercontent.com/127007861/230306966-57f2b96e-99da-4e29-a349-e9227fcb8e82.png)
![image](https://user-images.githubusercontent.com/127007861/230307135-fc4f056d-c104-46a9-b416-cb68dbe58ee1.png)

### Steps To Reproduce 重现步骤

拖拽一个支持visibleOn的组件，根据formFactor给他写属性，如"visibleOn":"${formFactor == 'SMALL'?'false':'true'}"

### Version 版本

2.4.9

**Comment by hotlong** [comment]
请补充重现步骤

**Comment by yinlianghui** [comment]
使用mobile可以实现相关需求，不需要支持visibleOn表达式中判断是否手机端：https://aisuda.bce.baidu.com/amis/zh-CN/docs/extend/mobile
