### ISSUE TITLE
[Bug]: 所有得新增弹窗，文本框输入后点击回车按键，直接触发insert事件，但没关闭弹窗，再次点击确认会重复插入数据

### ISSUE THREAD

**Issue by kevin-medsci** [steedos/steedos-platform#4694]
### Description

新增弹窗，文本框输入后点击回车按键，直接触发insert事件

### Steps To Reproduce 重现步骤

新增弹窗，文本框输入后点击回车按键，直接触发insert事件，但没关闭弹窗，再次点击确认会重复插入数据

### Version 版本

2.4.5

**Comment by hotlong** [comment]
编辑窗口也应该支持回车保存并自动关闭。

**Comment by baozhoutao** [comment]
bf7b70b2
