### ISSUE TITLE
[Feature]: 删除报错应显示服务端的报错信息

### ISSUE THREAD

**Issue by kevin-medsci** [steedos/steedos-platform#4695]
### Summary 摘要

删除提示语不支持动态获取，只能写死，不满足业务需求

### Why should this be worked on? 此需求的应用场景？

删除失败时会有各种逻辑判断，errors.message内容不同，用户需要知道失败得具体不同原因，而非统一一个文案，无法指导用户进行下一步排错操作

**Comment by hotlong** [comment]
2.4.10 已处理

**Comment by hotlong** [comment]
steedos-widgets
