### ISSUE TITLE
optionsFunction不支持select类型 

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4696]
### Description

字段类型是select类型时，optionsFunction不支持；如果使用optionsFunction，需要将字段类型设置为lookup。
![image](https://user-images.githubusercontent.com/126655403/230534641-4a64b69b-6129-4f7a-8057-1dc4e8e444ff.png)
![image](https://user-images.githubusercontent.com/126655403/230534598-fa7ddc03-73e1-4f95-9276-383491507d78.png)
![image](https://user-images.githubusercontent.com/126655403/230534885-e9912308-bf84-4f1f-b52e-c664f3c42c23.png)

### Steps To Reproduce 重现步骤

1、设置字段类型为select，可使用收款计划对象（系统对象，contract_receipts）中的款项名称字段。
2、在yml文件中添加optionsFunction

### Version 版本

2.4.10-beta.3

**Comment by hotlong** [comment]
optionsFunction 作废

**Comment by hotlong** [comment]
用 amis 属性 替代
