### ISSUE TITLE
[Bug]: 相关表的字段，配置映射关系后，数据未同步到审批单

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4697]
### Description

能配置映射关系的字段，应该都能进行数据传递

### Steps To Reproduce 重现步骤

![image](https://user-images.githubusercontent.com/7665279/230537143-515d1a96-f7bc-4419-8091-cf79f14fe9de.png)

![image](https://user-images.githubusercontent.com/7665279/230537194-d0b55f5b-ddf4-4a04-9f7c-5718a3d1ab44.png)

### Version 版本

2.4.10-beta.6

**Comment by sunhaolin** [comment]
相关表字段需要添加 relatedList:true 属性
