### ISSUE TITLE
[Feature]: 手机端新增扫一扫功能

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#4702]
### Summary 摘要

移动端增加二维码扫描入口，如果扫描二维码跳转到对应的应用界面。具体二维码编码规则可自定义，并且在电脑端有生成界面。

### Why should this be worked on? 此需求的应用场景？

使用移动端扫描条码跳转到详情界面

**Comment by hotlong** [comment]
可以使用 Tooljet 自定义微应用实现。 https://docs.tooljet.com/docs/widgets/qr-scanner
