### ISSUE TITLE
[Bug]: 通知对象(notifications)列表 相关记录 列显示异常

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4705]
### Description

![image](https://user-images.githubusercontent.com/6194896/230818626-597c7649-d1ab-41c6-ac43-2e3c96be3bb1.png)

### Steps To Reproduce 重现步骤

1. 发起批准过程后
2. 进入通知对象列表 /app/-/notifications/grid/all

### Version 版本

2.4.10

**Comment by baozhoutao** [comment]
d84be0d2e
