### ISSUE TITLE
[Bug]: 批准过程待办列表中的步骤名称需显示为设置的步骤名称，目前都显示为“已提交的批准请求”

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4706]
### Description

任务审批状态，都需批准过程中配置的步骤名

### Steps To Reproduce 重现步骤

![image](https://user-images.githubusercontent.com/7665279/230828161-9cba39d5-1829-4a17-917e-bd068b0d6a17.png)
![image](https://user-images.githubusercontent.com/7665279/230828385-a9597754-ae6b-45bf-a192-7a6ff58120d4.png)
![image](https://user-images.githubusercontent.com/7665279/230828419-87adcee1-6d1b-4c2a-915f-f561cba390ec.png)
任务审批状态，都需显示此步骤名称

### Version 版本

2.4.10

**Comment by baozhoutao** [comment]
重现方式: 自定义对象`process_instance_history`列表视图即可重现.
问题原因: process_instance_history查询必须要查询`step_node`字段. 默认的all视图配置了`extra_columns: ["step_node"]`, 所以正常.
解决方案: 在服务端beforeFind\beforeFindone 给查询的字段上追加上step_node字段
