### ISSUE TITLE
[Task]: 记录类型微页面Schema都要调整，在设计器中使用记录服务组件设计微页面

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4717]
### SubTasks 子任务

- [x] - 对象详细
- [x] - 流程详细
- [ ] - 批准过程

**Comment by hotlong** [comment]
这是 2.5 的需求吧？

**Comment by yinlianghui** [comment]
> 这是 2.5 的需求吧？

是的，刚标记了，我先把流程和对象处理好，这个很快。

**Comment by yinlianghui** [comment]
记录服务组件已改为可选，如果记录详细页面中有相关表组件则必须使用该组件。
