### ISSUE TITLE
[Bug]: 对象有附件字段，记录无附件，点编辑不报错。记录有附件，点编辑报错

### ISSUE THREAD

**Issue by xiaokedou5951** [steedos/steedos-platform#4722]
### Description

标准对象记录编辑报错。对象有附件字段，记录无附件，点编辑不报错。记录有附件，点编辑报错
![企业微信截图_16812025194794](https://user-images.githubusercontent.com/61674418/231107148-93fc8e94-3086-49e9-adfe-f6ab03fc3ea4.png)

### Steps To Reproduce 重现步骤

新建一个对象，添加一个附件字段。
预览新增记录，填写附件。
记录列表点编辑

### Version 版本

2.4.5

**Comment by hotlong** [comment]
对象缺少name字段，必须要定义的

**Comment by Flyingliao** [comment]
未重现
