### ISSUE TITLE
[Bug]: 对象-字段页面，点击新建按钮后，弹出的对话框空白

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#4723]
### Description

对象-字段页面，点击新建按钮后，弹出的对话框空白，要等待很久或者需要关闭后重试才能正常显示对话框内内容
![6539297e0594f209e4e535966d7dc18](https://user-images.githubusercontent.com/25192306/231128110-3aca4676-90f3-4ec8-876d-29777362706f.png)

### Steps To Reproduce 重现步骤

1、设置-->对象
2、新建对象
3、新建字段
![image](https://user-images.githubusercontent.com/25192306/231128382-ac2d3955-14c9-459f-b883-ad1f59d1ffda.png)
![6539297e0594f209e4e535966d7dc18](https://user-images.githubusercontent.com/25192306/231128110-3aca4676-90f3-4ec8-876d-29777362706f.png)

### Version 版本

platform 2.4.10

**Comment by hotlong** [comment]
未能重现，确认一下 ROOT_URL 配置是否正确。
