### ISSUE TITLE
[Feature]: 手机端支持在底部显示 tabs

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4724]
### Summary 摘要

- 参考 salesforce，默认显示第一个应用的前4个tab
- 第5个tab显示菜单，点击后全屏打开目前手机版的左侧菜单。

![3697F320-E9D6-4BCA-B40E-78C2C967129D](https://user-images.githubusercontent.com/50353452/231139723-8d20a87d-dabe-4bc0-be7b-dce302f1fe23.png)

### Why should this be worked on? 此需求的应用场景？

手机端

**Comment by tujiajun** [comment]
字小点，popup加箭头，上下间距尽量均衡
