### ISSUE TITLE
[Bug]:更新最新版本之后，amis的树形组件，选中之后没有高亮颜色

### ISSUE THREAD

**Issue by lijunjun2270249873** [steedos/steedos-platform#4727]
### Description

![Snipaste_2023-04-12_10-52-08](https://user-images.githubusercontent.com/109123143/231337644-43756518-8034-4a87-ab1d-b8e0ce8b6542.png)

### Steps To Reproduce 重现步骤

![Snipaste_2023-04-12_10-52-08](https://user-images.githubusercontent.com/109123143/231337724-bd972072-a9d8-4559-bfdc-f26c4569a876.png)

### Version 版本

2.4.5

**Comment by hotlong** [comment]
可以使用环境变量切换 amis 的版本号 

# 配置 Amis 当前引用的版本号
# STEEDOS_AMIS_VERSION=2.7.2

**Comment by hotlong** [comment]
amis 控件的样式问题，请在 amis 仓库提交issue
