### ISSUE TITLE
批量审核优化，如果非会签节点，后续是单一路径，并且指定了处理人，应该也支持批量审核

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#473]

**Comment by sunhaolin** [comment]
- [ ] 批量审批列表申请单信息显示与待审核列表显示信息一致
- [ ] 确认批量审批列表多条数据是是否有滚动条

**Comment by sunhaolin** [comment]
https://github.com/hotlong/steedos-web/commit/ed2153313bc2a9f1afa6af8df9553e69025ba7ec
