### ISSUE TITLE
[Bug]: 列表视图lookup字段无法按label排序，禁止对该类型字段排序

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#4730]
### Description

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/126241326/231403545-3f032232-58ff-4fa2-afda-a4217eeeaf28.png">
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/126241326/231404690-d43db738-eb5c-423b-af32-fdc27242f0ad.png">
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/126241326/231404204-ce90f847-a191-4e16-b14c-a894cd9bc3b0.png">

### Steps To Reproduce 重现步骤

1. 前往**设置**
2. 进入对象，选择**项目**
3. 点击列表视图，进入一个列表视图的**编辑**界面
4. 在排序中只选中**项目经理(正序)**
5. 前往刚刚选中的列表视图查看即可

### Version 版本

2.5.0-beta.5

**Comment by Flyingliao** [comment]
最终处理结果： image、file、lookup、master_detail、select 不参与排序
