### ISSUE TITLE
[Bug]: 列表视图搜索项目设置顺序不生效

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#4732]
### Description

![ae5b9af496aa87f2eda8116cebeec9a](https://user-images.githubusercontent.com/25192306/231426549-63129616-a070-43a7-afc3-dbfebf75235f.png)
![b435f28dc8eb9fe249f2e23f44b798e](https://user-images.githubusercontent.com/25192306/231426583-61b71201-0587-4b98-ab45-be70b699f64b.png)

### Steps To Reproduce 重现步骤

设置
对象
列表视图，编辑， 设置 搜索项

### Version 版本

platform 2.4.10

**Comment by yinlianghui** [comment]
已在任务 [Bug]: AmisObjectTable 组件显示太慢了, 需要1.5秒才能计算出schema #385 中处理。
