### ISSUE TITLE
[Bug]: 表单编辑器，在表格中连续添加字段，原已添加的字段被删除

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4735]
### Description

表单编辑器，在表格中连续添加字段，原已添加的字段被删除，非表格内字段不会自动删除

### Steps To Reproduce 重现步骤

https://user-images.githubusercontent.com/7665279/231643991-760ee3cd-ce84-46f4-a380-d8f4e20da59e.mp4

### Version 版本

2.4

**Comment by hotlong** [comment]
双击才会出问题
