### ISSUE TITLE
[Bug]: 记录详情页连续创建子表数据，创建完第二条数据后，必须手动刷新页面才能看到创建的数据

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4739]
### Description

<img width="1684" alt="image" src="https://user-images.githubusercontent.com/26241897/231919666-a833e413-769d-466d-adce-198811e65acf.png">

### Steps To Reproduce 重现步骤

1. 进入记录详情页，创建子表数据；
2. 创建第一条子表数据后，页面正常显示子表数据；
3. 再创建一条子表数据后，页面不显示创建的数据，需要刷新浏览器才能看到第二条子表数据。

### Version 版本

2.4.13

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4745

**Comment by Flyingliao** [comment]
排查结果：相关子表的刷新代码执行了，接口也返回正确的数据，接口的接收适配器中也返回了正确的数据。 

widgets1.1 存在这个问题， 1.2无此问题。

[#4758](https://github.com/steedos/steedos-platform/issues/4758) 处理后 此问题应该就不存在了。
