### ISSUE TITLE
[Bug]: 批准过程-下一步骤处理人为允许提交人手动选择批准人时，发起审批后页面应该自动出现选人字段

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4740]
### Description

目前点击提交后，系统才会提示用户选择下一步处理人
<img width="1703" alt="image" src="https://user-images.githubusercontent.com/26241897/231921126-4421165e-38d3-4b5f-84ac-f10dcff9e690.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/231921670-7c08256b-fd31-4117-8899-aa13a37720fb.png">

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/26241897/231921173-6d5f41b3-1679-491d-a185-b7a233008e21.png">

### Steps To Reproduce 重现步骤

1. 配置对象批准过程，并配置对应的审批步骤，同时审批步骤配置为“允许提交人手动选择批准人”；
2. 启用批准过程；
3. 前台创建记录，发起审批；
4. 填写意见后确认审批，此时提醒用户需要选择审批人。

### Version 版本

2.4.13

**Comment by sunhaolin** [comment]
经确认当初就是这样设计
