### ISSUE TITLE
[Bug]: 手机端首次登陆需要下载八千多个文件

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4741]
### Description

目前运行2.4.13项目，首次运行需要加载大概五分钟八千多个文件（苹果手机），安卓手机客户反馈下载完后闪退。
![7911681438092_ pic](https://user-images.githubusercontent.com/26241897/231923758-40a6c097-6fd6-4e59-a5ef-e6af72eaf4cf.jpg)

### Steps To Reproduce 重现步骤

1. 运行模版项目；
2. 下载手机版华炎魔方；
3. 手机客户端链接运行的模版项目。

### Version 版本

2.4.13

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/tree/master/creator/public/assets/icons/action

**Comment by hotlong** [comment]
小图标文件不要放到 public 下，只保留 *-sprite/svg
