### ISSUE TITLE
[Bug]: 新建相关表记录后，页面未刷新

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4745]
### Description

新建相关表类型记录后，页面未刷新。
![image](https://user-images.githubusercontent.com/126655403/231999131-bc6bd0d0-8dc7-4c49-a9a7-81ecb79e6cda.png)

### Steps To Reproduce 重现步骤

1、在包含相关表字段的对象中，新建相关表记录。
2、第2条记录之后，页面都不会自动刷新。

### Version 版本

2.4.13

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4739
