### ISSUE TITLE
[Bug]: 列表视图, 已选中的列, 在编辑的时候,未能自动选中.

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4747]
### Description

![image](https://user-images.githubusercontent.com/126655403/232021370-42992e54-321f-4cf6-80ce-6d04b79381e4.png)

### Steps To Reproduce 重现步骤

1、新建自定义对象同步为代码。
2、设置对象列表视图。

### Version 版本

2.4.13

**Comment by baozhoutao** [comment]
重现方式:  已选中的字段不存在的时候,会出现此问题

**Comment by baozhoutao** [comment]
此问题是amis bug .  临时方案是如果出现此情况, 请重新配置一次选中的列
