### ISSUE TITLE
[Bug]: 插件tabs 列表显示不全

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#4751]
### Description

插件的tabs列表显示不全

### Steps To Reproduce 重现步骤

![1681717753312](https://user-images.githubusercontent.com/25192306/232419913-5d359554-425b-4bce-b917-212320d714ca.jpg)

### Version 版本

platform 2.4.10

**Comment by lizhenghotoa** [comment]
同步插件中显示的tab只是在页面配置存在数据库中的数据，此外还会有yml代码定义的tab
