### ISSUE TITLE
[Bug]: 新建的人员（简档为管理员），登录后查看人员信息看不到简档

### ISSUE THREAD

**Issue by xiaokedou5951** [steedos/steedos-platform#4752]
### Description

新建的人员（简档为管理员），登录后查看人员信息看不到简档

### Steps To Reproduce 重现步骤

1、使用管理员新建简档为admin的人员
2、使用该人员登录
3、查看任何人员信息，发现页面无简档信息
![image](https://user-images.githubusercontent.com/61674418/232424695-8513235f-12ba-48e4-91a0-c437e0864351.png)

### Version 版本

2.4.5

**Comment by Flyingliao** [comment]
重启服务才会生效
