### ISSUE TITLE
[Bug]: 元数据配置的同步路径无效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4753]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/232434674-d98db595-56c1-428c-a84a-33be1825e3aa.png">

### Steps To Reproduce 重现步骤

1. gitpod环境env.local文件中配置同步路径；
2. 或者通过setDefaultPackagePath设置同步路径；
3. 同步路径设置完成后deploy元数据还是提示路径问题

### Version 版本

2.4.13

**Comment by baozhoutao** [comment]
steedos cli 需要升级. 

pod 的 image 需要升级到2.2.5

模板项目的pod image 已升级.  https://github.com/steedos/steedos-project-template/commit/3c48fa7c5a499ddd1cd6f8e0d2f31a2bd5284b49
