### ISSUE TITLE
[Feature]: 通知中心消息应支持实时自动刷新

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4754]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/232441306-dc5c47c0-2ed8-4725-857d-34b3fdc9cba4.png">

### Steps To Reproduce 重现步骤

1. 发起批准过程；
2. 页面不会刷新接收通知消息；
3. 刷新页面后点击收到的消息后，消息上的小红点也不会刷新消失

### Version 版本

2.4.13

**Comment by hotlong** [comment]
https://github.com/moleculerjs/moleculer-web/blob/master/examples/socket.io/index.js
