### ISSUE TITLE
[Bug]: 2.5 审批王填写表单时，有的下拉框点不开

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4755]
### Description

不知道是流程的问题还是平台的问题

### Steps To Reproduce 重现步骤

- 安装 flows-ee
- 出差申请流程
- 公司不能选择

### Version 版本

2.5.3

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/236970079-aa96a9d2-7b27-49b5-a179-a1cd261d9feb.png)
未重现
