### ISSUE TITLE
[Bug]: 当对象列表数据只有一条时，列表视图下拉框无法展示完整

### ISSUE THREAD

**Issue by xiaokedou5951** [steedos/steedos-platform#4757]
### Description

当对象列表数据只有一条时，列表视图下拉框无法展示完整
![image](https://user-images.githubusercontent.com/61674418/232656280-a9217566-850e-483c-95b7-cbc115119ec6.png)

### Steps To Reproduce 重现步骤

1、新建一个对象并新建多个视图
2、增加一条数据
3、选择切换视图时，显示不完整

### Version 版本

2.4.5

**Comment by Flyingliao** [comment]
最新2.4.14-beta.2正常。
![image](https://user-images.githubusercontent.com/41402189/232941560-40159563-b716-48e7-9c4e-cdd892aea853.png)

**Comment by yinlianghui** [comment]
2.5还是有此问题。

**Comment by yinlianghui** [comment]
原因是分栏视图功能中给列表视图添加了样式类overflow-hidden：
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/6219465/234037502-b94c1c05-461b-4aca-a01e-8cfd091bbd26.png">
