### ISSUE TITLE
[Bug]: 小米pad真机点击隐藏左侧菜单按钮不生效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4759]
### Description

浏览器控制台测试正常，真机有问题
<img width="793" alt="image" src="https://user-images.githubusercontent.com/26241897/232949209-cb987f23-79c7-45ec-a643-7f3d2cf9b589.png">

### Steps To Reproduce 重现步骤

1. 使用安卓pad真机；

### Version 版本

2.4.14

**Comment by tujiajun** [comment]
暂时无法重现
