### ISSUE TITLE
整理 space_users 表的权限，部门等字段应该禁止普通用户自己修改。

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#476]

**Comment by yinlianghui** [comment]
- 去掉了user权限集部门字段的编辑权限，其他的三个相关字段`主部门、所属分部、主分部`都是omit的，所以不需要配置权限。
- 另外organization_admin权限集的部门字段权限我没禁用，即改后：工作区管理员和单位管理员才有权限改部门字段。
