### ISSUE TITLE
[Bug]: 默认页面布局同步代码后，页面布局不生效

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4762]
### Description

创建对象的默认页面布局后，将页面布局同步为代码，并将页面布局从数据库中删除，此时对象页面布局不生效。修正页面布局名称后，页面布局生效。
![image](https://user-images.githubusercontent.com/126655403/232961827-ce65e83f-3571-49c4-8958-44e448d5243c.png)
![image](https://user-images.githubusercontent.com/126655403/232961916-3a0038f5-2ebb-473f-a38f-f0429fa2008a.png)
![image](https://user-images.githubusercontent.com/126655403/232962748-3c8c0516-7ec7-4589-99b9-d69d49225c54.png)

![image](https://user-images.githubusercontent.com/126655403/232961385-fb0cb5bf-6e41-467d-b352-c2be8b6cb822.png)

### Steps To Reproduce 重现步骤

1、创建对象默认页面布局并设置字段显示。
2、将页面布局同步为代码，并删除数据库中的页面布局。
3、重启服务，页面布局不生效。

### Version 版本

2.4.13

**Comment by baozhoutao** [comment]
2.5未能重现
