### ISSUE TITLE
[Bug]: 代码加载的角色元数据进入详情页报错“Cannot set properties of undefined (setting '__record')”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4766]
### Description

- 背景：审批中间节点需要指定人员审批，所以设置的角色，后面有同步成代码进行提交；
- 问题：开了新环境需要重新设置角色绑定的人员，发现不光没有写到库里的自定义按钮，页面还提示报错信息
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/26241897/233030976-8bba10eb-755e-41d6-bc59-3f1ca78acdfb.png">

### Steps To Reproduce 重现步骤

1. 参考[Steedos Project Laboratory](https://gitlab.steedos.cn/steedos/steedos-project-laboratory)项目；
2. 进入后台审批王—角色；
3. 能够看到“仪器室管理员”角色，进入详情页就能够看到错误信息

### Version 版本

2.4.13

**Comment by lizhenghotoa** [comment]
2.4.15-beta.10版本还是有这个问题

**Comment by baozhoutao** [comment]
代码已同步到2.4分支
