### ISSUE TITLE
[Bug]: 数据导入, 如果导入的excel文件太大, 导致系统奔溃

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4771]
### Description

数据导入使用大excel

### Steps To Reproduce 重现步骤

数据导入使用大excel

### Version 版本

2.4

**Comment by baozhoutao** [comment]
换个excel解析工具? `exceljs`

**Comment by lihailong220** [comment]
platform2.5项目文件   packages/data-import/src/objectImport.ts：  filetoRecords函数中的二重循环(850行)或许可以优化？
