### ISSUE TITLE
[Feature]: 平台发版本时，锁定到具体 的 steedos-widgets 版本

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4774]
### Summary 摘要

包括 2.2， 2.3， 2.4， 2.5

### Why should this be worked on? 此需求的应用场景？

防止 steedos-widgets 版本升级导致系统故障。

**Comment by yinlianghui** [comment]
### amis 版本

#### 2.5

识别环境变量STEEDOS_AMIS_VERSION，默认版本为2.9.0

#### 2.4

识别环境变量STEEDOS_AMIS_VERSION，默认版本为2.7.2

#### 2.3

不能识别环境变量STEEDOS_AMIS_VERSION，写死版本为2.7.2

#### 2.2

不能识别环境变量STEEDOS_AMIS_VERSION，没有独立的amis sdk.js请求，amis sdk编译到@steedos-ui/amis包（版本2.2.26）中了，
请求地址：https://unpkg.steedos.cn/@steedos-ui/amis@2.2.26/dist/amis-sdk.umd.min.js

### monaco-editor

- 2.4/2.5不再会有monaco-editor相关资源文件请求。
- 2.2和2.3会请求monaco-editor相关资源文件，且版本号始终是最新版本，目前为0.37.1，需要改为最初的固定版本0.33.0

**Comment by yinlianghui** [comment]
monaco-editor相关资源文件始终会请求最新的版本，调式下来应该是frontend中调用@steedos-builder/react包中的Builder.initMonaco函数在请求monaco-editor相关资源文件，且始终请求的是最新版本。
![image](https://user-images.githubusercontent.com/6219465/233616969-9c18f9a9-533b-4325-97fd-c84ac84b3eaf.png)

Frontend中调用Builder.initMonaco函数源码：
<img width="647" alt="image" src="https://user-images.githubusercontent.com/6219465/233617979-647ed6da-5805-4ac9-be10-5b464f93c309.png">

https://github.com/steedos/steedos-frontend/blob/2.2/packages/builder-object/src/valueTypes/code.tsx

Builder.initMonaco函数源码：
<img width="807" alt="image" src="https://user-images.githubusercontent.com/6219465/233618117-b2656743-4198-445a-8683-5bc0da7fb5fe.png">

https://github.com/steedos/steedos-builder/blob/main/packages/sdk/src/steedos-builder.class.ts#L293

**Comment by yinlianghui** [comment]
@steedos-builder/react包中的 Builder.initMonaco 函数已改为加载固定版本0.33.0，并发版本，2.2和2.3的platform已经引用了该版本实现了固定monaco-editor版本。
