### ISSUE TITLE
[Bug]: 记录详情页有时候右上角下拉框按钮点开时空的

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4782]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/233527137-6bbbae7c-7383-49ed-a49f-1ca1e19f5e61.png">

### Steps To Reproduce 重现步骤

1. 管理员进入后台设置-公司菜单下；
2. 点击右上角更多按钮；

### Version 版本

2.4.13

**Comment by hotlong** [comment]
最好是能隐藏下拉，如果不能隐藏，参考列表视图行下拉，为空时显示：“没有可用的操作”。
