### ISSUE TITLE
[Bug]: 分部无法直接删除，必须先删除部门再删除分部

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4783]
### Description

目前分部对象中，部分字段为必填，但是删除分部时提示用户清除部门数据后再删除；现在就导致没办法删除分部；
现在唯一的办法就是先删除部门以后再删除分部数据。
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/233528119-fd3239fb-131e-4f06-a3d1-44174dddecde.png">

### Steps To Reproduce 重现步骤

1. 管理员进入后台设置-分部；
2. 新建分部后，删除该分部。

### Version 版本

2.4.14

**Comment by hotlong** [comment]
需要讨论设计完整的规则再开发
