### ISSUE TITLE
[Bug]: 编辑分部对象关联部门字段，弹框显示部分数据多显示了序号列

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4784]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/233528801-8bba39ef-7f3e-44d0-9729-9db55f467c5b.png">

### Steps To Reproduce 重现步骤

1. 管理员进入后台设置——分部；
2. 编辑某一条分部记录，点击关联部门字段后，部门弹框数据。

### Version 版本

2.4.14

**Comment by Flyingliao** [comment]
2.5.15-beta.14版本无此问题。

<img width="1043" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/923bdc14-5ed4-4677-b9c9-eb4b58cd519d">
