### ISSUE TITLE
[Bug]: 点击权限集列表页的下载按钮报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4785]
### Description

接口报错：{
  "error": {
    "message": "Fail at 0",
    "code": 500,
    "error": 500
  }
}
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/233530694-92365b56-e6fe-4954-9d85-6482a121378a.png">

### Steps To Reproduce 重现步骤

1. 管理员进入后台公司设置-简档&权限集；
2. 点击列表页的下载按钮。

### Version 版本

2.4.14

**Comment by hexiapengCom** [comment]
相关任务 https://github.com/steedos/steedos-platform/issues/4506

**Comment by hexiapengCom** [comment]
报错原因：点击下载时下载请求时会把**对象的label**放到路径中，该对象label中包含`&`，在请求路径中`&`代表参数的间隔符。
解决方法：使用[encodeURIComponent](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#%E6%8F%8F%E8%BF%B0)
