### ISSUE TITLE
[Bug]: 进入简档 & 权限集对象的简档记录页面后，点击相关会退出服务

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#4789]
### Description

1. 进入**简档 & 权限集**对象
2. 进入一个**简档**记录
3. 点击**相关**

目前只能在我笔记本复现(芯片: apple m2, macOS: 13.0 (22A380))

### Steps To Reproduce 重现步骤

1. 前往**简档 & 权限集**对象的列表视图页面，点击进入一个**简档**的记录
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/126241326/233821083-d905b4bf-a69e-4411-9aa7-977422cc6e36.png">
2. 点击**相关**就会自动关闭服务
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/126241326/233821123-922e16d1-0d10-41d1-a406-cb0cee9ce9df.png">

- 第一个网络请求出错内容
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/126241326/233821251-6669e5ea-bf3f-48b9-8818-51c536ce983c.png">

``` 
query: 
"{rows:permission_objects(filters: [[\"permission_set_id\",\"=\",\"user\"]], top: 50000, skip: 0, sort: \"\"){_id,permission_set_id,object_name,allowCreate,allowDelete,allowEdit,allowRead,modifyAllRecords,viewAllRecords,modifyCompanyRecords,viewCompanyRecords,is_system,_display:_ui{permission_set_id,object_name,allowCreate,allowDelete,allowEdit,allowRead,modifyAllRecords,viewAllRecords,modifyCompanyRecords,viewCompanyRecords,is_system}},count:permission_objects__count(filters:[[\"permission_set_id\",\"=\",\"user\"]])}"
```  

- 控制台内容
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/126241326/233821378-732e82a5-bec3-411c-9acc-9dd6c70b072a.png">

- platform报错信息
<img width="613" alt="image" src="https://user-images.githubusercontent.com/126241326/233821134-7b563b62-1926-4aeb-8347-d1c1114da2c0.png">

### Version 版本

2.5.0-beta.12

**Comment by baozhoutao** [comment]
尝试 删除掉项目下的node modules , 重新安装依赖 `yarn`

**Comment by baozhoutao** [comment]
目前系统在 M2 处理器下 会自动挂掉. 原因和fibers版本有关.  需要升级到5.x . 目前是4.x.

**Comment by baozhoutao** [comment]
方案: 将fibers升级到5.0.3

**Comment by baozhoutao** [comment]
测试点:
1 测试在m1、普通cpu下系统是否正常
2 测试非内核对象CRUD是否正常
3 测试meteor collection对象CRUD是否正常
