### ISSUE TITLE
[Feature]: 手机端记录详细页面缺少返回上一页按钮

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4805]
### Summary 摘要

以下是之前2.2版本的效果，顶部左上角有一个返回按钮。
![image](https://user-images.githubusercontent.com/6219465/233920145-193dcb8e-2bc4-4937-8632-3404f5b81c9f.png)

### Why should this be worked on? 此需求的应用场景？

手机端统一需求

**Comment by hotlong** [comment]
重复
