### ISSUE TITLE
[Bug]: 新建对象，选择外部数据源（MySQL，已经测试连接成功），对象创建成功，但是数据库中无相关数据表。编辑列表视图操作报错

### ISSUE THREAD

**Issue by yijiebaiyi** [steedos/steedos-platform#4813]
### Description

新建对象，选择外部数据源（MySQL，已经测试连接成功），对象创建成功，但是数据库中无相关数据表。编辑列表视图操作报错
![8296ab7948ce0b84f54eae7efab43c1](https://user-images.githubusercontent.com/108124279/233992020-f0e19030-7af4-43ca-9278-28a98638bd16.png)

### Steps To Reproduce 重现步骤

1. 新建数据源为Mysql。测试连接显示连接成功。
2. 到系统设置对象模块创建对象。
3. 列表视图进行编辑操作
4. 报错

### Version 版本

steedos/steedos-enterprise:2.4

**Comment by hotlong** [comment]
目前的版本不会自动创建和维护数据表结构，需要手工在数据库中创建表。
