### ISSUE TITLE
[Bug]: 列表视图分栏模式下，点击数据行时，会造成详情页和左侧分栏的列表视图一起被刷新，闪烁

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#4814]
### Description
![image](https://user-images.githubusercontent.com/25192306/234155396-7af74bbd-9431-443c-bb28-a7f4e07af7c9.png)
![image](https://user-images.githubusercontent.com/25192306/234155418-763a7444-6517-40bb-8806-c42e1b6cdc5d.png)

### Steps To Reproduce 重现步骤

1、点击任意一个对象的列表视图
2、切换到分栏模式
3、点击列表明细行

### Version 版本

platform 2.4.10

**Comment by hotlong** [comment]
2.4 2.5 最新beta版已修正此问题，
