### ISSUE TITLE
[Bug]: 外接应用登录到魔方报错：Internal Server Error

### ISSUE THREAD

**Issue by yijiebaiyi** [steedos/steedos-platform#4817]
### Description

外接应用登录到魔方功能：
外接应用客户端请求服务端获取jwt接口。获取到token之后，跳转到魔方平台（GET），地址：
${PLATFORM_ROOT_URL}/accounts/jwt/login?t=${token}&redirect=${PLATFORM_ROOT_URL}
PLATFORM_ROOT_URL是魔方平台的服务器地址。
魔方平台返回 Internal Server Error

### Steps To Reproduce 重现步骤

![4d78196a24d64d145ecf87f072879a1](https://user-images.githubusercontent.com/108124279/234214711-fa3bdd6b-9f82-4361-8053-e0468ed0f4da.png)

### Version 版本

steedos/steedos-enterprise:2.4

**Comment by hotlong** [comment]
需要提供服务端的报错信息

**Comment by yijiebaiyi** [comment]
好的，原来是需要先在魔方创建用户
