### ISSUE TITLE
[bug]: 手机客户端，选中应用界面不能正确显示图标

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4822]
### Summary 摘要

![image](https://user-images.githubusercontent.com/50353452/234442066-3c11a3ef-9b61-40e0-8151-0b74a7db27e2.png)

应该调用大的svg图标文件

### Why should this be worked on? 此需求的应用场景？

手机app

**Comment by tujiajun** [comment]
重复#4854 [Bug]: 手机app，应用程序启动器中svg图标未显示出来
