### ISSUE TITLE
[Bug]: 分栏视图下，新建记录后，左侧列表不会更新新建的记录

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4831]
### Description

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/26241897/234486362-b094fb51-ec00-4aec-981e-d1fd686c253c.png">

### Steps To Reproduce 重现步骤

1. 列表切换为分栏视图；
2. 分栏视图下新建记录

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by Flyingliao** [comment]
最新版本（2.4.15-beta.15&1.2.6-beta.12）未重现, 2.5坏了。
