### ISSUE TITLE
[Bug]: 权限集不生效，接口查询可以查到该对象权限，但业务调用时graphql返回无权限

### ISSUE THREAD

**Issue by kevin-medsci** [steedos/steedos-platform#4832]
### Description

对应得权限集已配置对象权限，db中及接口查询均可以查到该对象权限，但业务调用时graphql返回无权限

### Steps To Reproduce 重现步骤

![image](https://user-images.githubusercontent.com/122590707/234486736-5202c61d-d529-40c1-8b4d-96ba823fb848.png)
![image](https://user-images.githubusercontent.com/122590707/234486919-f1eafc16-8f5a-46bc-adf3-a40d46b0664e.png)
![image](https://user-images.githubusercontent.com/122590707/234487107-fa3dd844-4fca-4121-9403-9098931c89bc.png)
![image](https://user-images.githubusercontent.com/122590707/234487183-9a196914-230e-4bc3-ac44-26d4a0c6167b.png)

### Version 版本

2.4.5

**Comment by hotlong** [comment]
会不会和 beforeFind 有关系？
