### ISSUE TITLE
[Bug]: 进入对象详情页相关tab页提示“data.items 必须是数组”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4833]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234490921-f3343e52-87a3-47d8-aa59-a6d2b6e0944c.png">

### Steps To Reproduce 重现步骤

1. 后台新建对象，启用除树开关外的其他功能开关；
2. 对象创建完成后，点击预览；
3. 新建记录后，进入记录详情页。

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by baozhoutao** [comment]
问题原因:  graphql 查询 filters 报错 `E4019`
```
<!--JavaScript-->
//Invalid filter expression
var filterExpression = [
    [ "name", "contains", "A"],
    "and",
    ["team", "=", "Accounting"],
    "or",
    ["team", "=", "Management"]
]


//Valid filter expression
var filterExpression = [
    [ "name", "contains", "A"],
    "and",
    [
        ["team", "=", "Accounting"],
        "or",
        ["team", "=", "Management"]
    ]
]
```

**Comment by baozhoutao** [comment]
[d5e2abee019429ac67876321f0065b65399455c4](https://github.com/steedos/steedos-widgets/commit/d5e2abee019429ac67876321f0065b65399455c4)
