### ISSUE TITLE
[Feature]: 网址-二维码类型字段前台支持显示为二维码

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4835]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234504523-226de34e-c636-4c7a-be56-df7672ce9794.png">

### Steps To Reproduce 重现步骤

1. 创建网址-二维码类型字段；
2. 前台创建记录。

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by Flyingliao** [comment]
amis中提的issue： [二维码、html能否支持label属性配置？](https://github.com/baidu/amis/issues/7040)
