### ISSUE TITLE
[Bug]: 点击关于后，页面是空白的

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4837]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234509401-1137fe79-2103-4a4f-8fda-79f5c6ba2244.png">

### Steps To Reproduce 重现步骤

点击系统右上角头像的“关于”菜单

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by hotlong** [comment]
关于的微页面要添加到2.4
