### ISSUE TITLE
[Bug]: amis-button中对象表单组件配置后无法使用

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4839]
### Description

在amis-button下配置对象表单组件；
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234518507-0aa44632-b79b-4f01-8b16-4448ee732b83.png">

预览效果
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234519411-449aba50-9e19-4495-838e-ffbe45986873.png">

### Steps To Reproduce 重现步骤

新建对象amis-button，在amis-button下配置对象表单组件

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by baozhoutao** [comment]
afa100705
