### ISSUE TITLE
[Bug]: amis微页面对象表单、列表视图组件无法使用

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4841]
### Description

- 列表视图组件一直加载中
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234536293-fb125558-2c4e-40d8-84e8-8213be035aec.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234536413-fc59e56a-d741-44f9-b9b4-87120c42e583.png">

- 对象表单组件只读状态前台报错“Cannot set properties of undefined (setting '__objectName')”
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234536805-73912a1d-9f6d-4298-a923-d85ae533b0e2.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234536881-2eac64d8-4e4e-49c9-a751-0dfb723d3ae1.png">

- 对象表单组件编辑状态，设计器页面组件显示内容加载不出，前台页面报错
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234537221-27b3dc1e-692c-4f92-b518-45463270beab.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234537159-08992e86-de4b-48e2-9a50-5040d6477621.png">

### Steps To Reproduce 重现步骤

1. 后台创建应用程序微页面；
2. 添加对象表单、列表视图组件进行测试

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by baozhoutao** [comment]
6ba9d5e0
