### ISSUE TITLE
[Task]: 优化amis schema render以简化api配置

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4845]
### SubTasks 子任务

- [ ] 配置的api地址是相对路径时, 则自动补全 root url
- [ ] api未配置 `Authorization` headers时, 自动补全 `Authorization` headers

### render 

- [ ] next js
- [ ] creator
- [ ] builder

**Comment by hotlong** [comment]
如果api是要调用第三方系统接口呢？

**Comment by hotlong** [comment]
重复
