### ISSUE TITLE
[Bug]: 新建人员时，用户名字段没有校验至少六位的规则

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4847]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234741617-32553746-3466-427f-9777-aecc905d970d.png">
目前编辑用户时会校验用户名规则
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234741666-979baa7a-64c8-4e8c-8b5f-feadde6bcf03.png">

### Steps To Reproduce 重现步骤

1. 新建人员，用户名填写少于六位的字母；
2. 编辑刚刚新建的用户会提示不满足规则

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by hotlong** [comment]
这个规则是在哪里定义的？

**Comment by sunhaolin** [comment]
> 

https://www.steedos.com/docs/deploy/steedos-config#%E8%B4%A6%E6%88%B7%E7%9B%B8%E5%85%B3

is_username_skip_minrequiredlength：是否跳过用户名最小位数限制，默认最小为6位。

**Comment by lizhenghotoa** [comment]
新建的时候没有去校验这个规则，但是编辑的时候是校验这个六位规则的
