### ISSUE TITLE
[Bug]: 列表记录勾选后，顶部选中数据样式需要优化

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4848]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234742737-3167255b-c11d-4a6c-a4fa-2eb441c8e556.png">

### Steps To Reproduce 重现步骤

列表视图勾选几条记录

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by hotlong** [comment]
表格背景改为灰色。包括下面的空白也是灰色。

**Comment by Flyingliao** [comment]
在此已经修改好了： https://github.com/steedos/steedos-widgets/commit/65214c65088f76c6146e8afdeb87456b4a05d230
