### ISSUE TITLE
[Bug]: 对象列表，设置搜索项，可选字段及选择后的显示逻辑有问题

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4850]
### Description

以合同为例
（1）可选的字段不是 所有的对象字段？
所有字段 57
![image](https://user-images.githubusercontent.com/7553007/234746626-dc79e2cb-db0c-448a-a5ad-6cfe6f1a0e2b.png)
可选字段40
![image](https://user-images.githubusercontent.com/7553007/234746755-1bbd8334-99e8-4ec8-b2ff-d88648807bc3.png)

（2）已选的字段数 与 实际显示出来供搜索的 字段数不符
已选24
![image](https://user-images.githubusercontent.com/7553007/234746842-0bbc4088-45fc-4446-b635-c0545c670f67.png)
实际显示16
![image](https://user-images.githubusercontent.com/7553007/234746954-d550e080-99f2-4a12-a2e8-f472228b9052.png)

以上，需明确 目标规则 及 系统实现

### Steps To Reproduce 重现步骤

以合同为例，步骤如上

### Version 版本

2.5.0-beta.14

**Comment by yinlianghui** [comment]
列表搜索栏中可搜索项字段列出的是当前对象下满足以下规则的所有字段：
- 在当前对象uiSchema接口中返回的字段范围内（该接口只会返回当前用户）
- 非隐藏字段（即hidden属性不为true的字段）
- 不属于以下字段类型：
```js
[
            "grid",
            "avatar",
            "image",
            "object",
            "[object]",
            "[Object]",
            "[grid]",
            "[text]",
            "audio",
            "file",
        ]
```

另外字段上配置了以下属性的情况下也在可选搜索字段范围，规则如下：
- 字段上配置了visible_on的话，该字段在搜索栏中会始终显示，即visible_on属性会被忽略。
- lookup字段上配置了depend_on的话，该字段在搜索栏中会始终显示，且其下拉选项范围会忽略filterFunction属性，depend_on属性也会被忽略。
