### ISSUE TITLE
[Bug]: 手机 app连最新2.5版本界面一片空白无法使用

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4851]
### Description

- 连 platform2.5分支最新代码（yarn start:ee 运行的服务）有问题
- 连 https://huayan.steedos.cn/ 也一样有问题

### Steps To Reproduce 重现步骤

- AppStore下载最新版本的华炎魔方客户端
- 输入魔方地址，连接需要测试的2.5版本魔方项目或platform平台的服务
- 能看到登录界面（好像大概要等个10秒的样子才能看到登录界面）
- 登录后会看到界面一片空白，等很久时间也是一片空白（貌似有较小的几率能成功进入平台主页，因为有人成功进去过，不过退出后再进入又会一片空白）

### Version 版本

2.5.x最新版本

**Comment by hotlong** [comment]
应该用 vconsole 调试。现在大概登录页面没有接入 vconsole

**Comment by baozhoutao** [comment]
已知受影响范围:  `<= ios 13.7`

**Comment by baozhoutao** [comment]
先简单处理 , 设置`window.DragEvent = {}`
