### ISSUE TITLE
[Bug]: 设置>人员或其他页面进入人员详情，相关里的岗位成员 不准

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4855]
### Description

![image](https://user-images.githubusercontent.com/7553007/234751814-5fc382e7-b3fe-4d5f-b950-15a5a3747334.png)
传入的过滤疑似有误

### Steps To Reproduce 重现步骤

设置》岗位，增加岗位并设置岗位成员
点击该成员，查看相关里的岗位成员

### Version 版本

2.5.0-beta.14

**Comment by sunhaolin** [comment]
2.5分支最新代码未能重现此问题

**Comment by marchtian** [comment]
系统管理员，查看人员，相关里的岗位成员可正常看到
普通用户，查看本人或其它人员，相关里的岗位成员显示为0 ( 因为没有权限、所以不能看到，这是正常的）
