### ISSUE TITLE
[Feature]: 对象搜索，lookup类型(含主子表)的字段，需适配手机端

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4857]
### Summary 摘要

- 手机端不考虑下拉或弹出，统一弹出。
- 弹出窗口支持搜索。
- 弹出窗口全屏。
- 弹出窗口显示样式为手机端列表样式。

### 问题
目前手机和PC是一样的，手机上选择不方便
例如合同，搜索项目
![image](https://user-images.githubusercontent.com/7553007/234754592-dda3f47c-8d27-4911-8378-5eefc4ffb616.png)

项目中搜索项目集
<img width="419" alt="企业微信截图_5c96d9e2-be96-418d-91b0-c6f86479e4b3" src="https://user-images.githubusercontent.com/50353452/234779227-9adb7171-dfad-4f5e-95e3-95b1c186e9e3.png">

**Comment by yinlianghui** [comment]
弹出窗口显示样式为手机端列表样式这个单独建issue了：[Feature]: 列表搜索栏lookup字段弹出的列表窗口应该使用手机上的非表格列表模式 #5350
