### ISSUE TITLE
[Bug]: 列表页面底部翻页样式需要优化

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4858]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234754785-eea3087b-8383-413a-a8af-38871bf5ef53.png">

### Steps To Reproduce 重现步骤

template项目设置-流程页面

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by hotlong** [comment]
重复
