### ISSUE TITLE
[Bug]: 日历视图/组件样式优化，背景色改为灰色

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4860]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234767145-50845596-7c06-4092-abd8-c214fe5c57b2.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234767192-11239742-5ebb-4193-a424-8e52c22e7652.png">

### Steps To Reproduce 重现步骤

1. 模版项目，进入办公应用下的日程菜单；
2. 或者通过微页面设计器添加日历组件。

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by hotlong** [comment]
1.2.6-beta.11 已修正
