### ISSUE TITLE
[Bug]: 应用中添加“审批任务”菜单后，显示异常

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4861]
### Description

- 页面显示怪（貌似是3000环境的审批王）
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234768693-888ffc64-e4f5-463a-aab3-47621c9e679f.png">

- 点击左侧卧的文件下菜单后，审批王的页面又是老版本的页面
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/234768930-1440ba13-21c0-496a-a278-3e95503c43bd.png">

### Steps To Reproduce 重现步骤

后台新建应用，添加审批任务菜单

### Version 版本

2.4.15-beta.5&1.2.6-beta.10

**Comment by hotlong** [comment]
2.4 不支持
