### ISSUE TITLE
[Bug]: 审批王，待审核中不可编辑字段，颜色不对

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4862]
### Description

<img width="810" alt="企业微信截图_3d725af2-d426-426e-af9b-eb8ad1c8478f" src="https://user-images.githubusercontent.com/50353452/234770933-6c0e84fe-e61c-48a1-9c62-c3c9d598ef43.png">

原因是html元素有 disable 属性

### Steps To Reproduce 重现步骤

1. 配置流程
2. 配置字段权限

### Version 版本

2.5

**Comment by baozhoutao** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4863
