### ISSUE TITLE
[Bug]: 普通用户，无法修改密码

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4871]
### Description

右上角进个人资料，无修改密码按钮
![image](https://user-images.githubusercontent.com/7553007/235046252-298dd3ca-33af-49b5-b97b-94378b6c2db7.png)
其他区域，也无修改密码机制

### Steps To Reproduce 重现步骤

普通用户登录系统

### Version 版本

2.5.0-beta.17

**Comment by baozhoutao** [comment]
![image](https://user-images.githubusercontent.com/6194462/236120000-0a713e2d-1566-4afe-858d-8da4e2768dfa.png)
未能重现

**Comment by marchtian** [comment]
已OK
