### ISSUE TITLE
[Bug]: 企业微信点击待办消息进入审批单，没有审批按钮

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#4874]
### Description

企业微信客户端点击待办进入审批单，没法审批

### Steps To Reproduce 重现步骤

1、企业微信客户端点击待办推送进入审批单
2、选不到审批按钮，也无法切换到待审核

### Version 版本

2.5.0-beta.17

**Comment by hotlong** [comment]
手机端应可以切换左侧导航菜单

**Comment by yinlianghui** [comment]
[Feature]: 手机记录详细页左上角增加返回按钮 #422

**Comment by sunhaolin** [comment]
方案： 提供统一接口(action) 在接口中生成申请单详细页地址后跳转

**Comment by tujiajun** [comment]
等待中转接口完成

**Comment by tujiajun** [comment]
#4956，点击推送消息也可以走中转接口

**Comment by sunhaolin** [comment]
> 等待中转接口完成

GET '/api/workflow/jumpto/:instanceId'

**Comment by yinlianghui** [comment]
此问题已经处理，需要更新到huayan.steedos.cn在手机APP中测试

**Comment by yinlianghui** [comment]
### 测试结果：
#### 流程未绑定应用的情况（即流程未配置流程分类或流程分类未绑定应用）
- 在huanyan.steedos.cn中新建一个对象和流程
- 配置好对象流程映射关系
- 在PC上，进入项目应用中某个对象列表，把浏览器地址栏中对象api名称改为上面新建对象的api名称进入对象列表
- 新建记录并发起审批
![企业微信截图_af4001bb-e044-44c4-8a49-260ac1ec44d0](https://github.com/steedos/steedos-platform/assets/6219465/b3218fe2-be6d-44ed-b76b-4dfc7eb426ef)
- 提交审批单到下一步骤，比如发给自己
- 然后在企业微信中可以收到审批通知，在企业微信中点开该通知
- 会发现进入的是`/app/workflow`这个应用（下面截图是把企业微信打开的页面url复制到浏览器窗口中，方便演示进入的网址是哪个）
![企业微信截图_59dde4fa-58e9-4fa9-b70d-4b59033c20da](https://github.com/steedos/steedos-platform/assets/6219465/e4c35b01-df6d-4364-9904-ed889a6b5d0e)

- 我进一步在PC浏览器上在之前的项目应用中把刚刚的审批单提交给廖同学
- 廖同学的企业微信（PC端）上点开审批通知界面即是正常的，不过他进入的地址是合同`/app/contracts`应用，而不是`/app/workflow`这个应用
- 廖同学的企业微信（PC端）上进入应用程序启动器切换到项目应用
- 然后再点开刚收到的审批通知，这次进入的地址是项目`/app/projects`应用，而不再是合同应用，说明规则是进入最后一次进入过的应用


#### 流程绑定应用的情况（即流程配置了流程分类且流程分类也绑定了应用）
按上面的步骤测试，结果在企业微信中点开的审批通知并没有进入到绑定的应用中，我进入的依然是`/app/workflow`这个应用，而廖学进入的也依然是他最后一次进入过的应用。
以上无论流程是否绑定应用，从企业微信中点到审批通知都并没有进入待审批单子，而是进了其他菜单箱，`/app/workflow/instances/view/xxx`或`/app/projects/instances/view/xxx`，路径中应该进入instance_tasks这个对象记录详情页面才对，而不是instances这个对象详情页面。

#### 之前的加班或请假审批单
- 点开之前在huayan平台上收到过的正式加班或请假审批单
- 我的企业微信（PC端），始终进的是`/app/workflow/instances/view/xxx`
- 廖同学的企业微信（PC端），始终进的是`/app/${最后一次进入过的应用}/instances/view/xxx`


### 现在审批相关的应用有三个，分别是
```
/app/oa 这是办公应用
/app/approve_workflow  这是新版本的审批中心
/app/workflow 这是老版本的审批王，应该要作废，用上面的新版本审批王代替
```
需要定一个规则，当流程未绑定到应用的时候应该跳转到哪里，感觉可以跳转到新版本审批中心，即`/app/approve_workflow`，目前是`/app/workflow`。


### 需要修正的问题
- 老的审批王应用申请单页面，即`/app/workflow/instances/view/xxx`地址进入的页面，顶部header栏空白【可以考虑不处理，只要以后不再会用这个地址即可】
- 审批单中转接口`/api/workflow/instance/xxx`应该识别下审批单绑定的应用，最后需要重定向到指定应用路由中，而不是最后一次进入的应用的路由
- 审批单中转接口`/api/workflow/instance/xxx`中识别到审批单未绑定应用时，不应该进老审批王应用（`/app/workflow`），而应该进入新版本的审批中心应用`/app/approve_workflow`
- 审批单中转接口`/api/workflow/instance/xxx`中应该始终重定向到待审批箱路径，而不是其他箱，即入instance_tasks这个对象记录详情页面才对，而不是instances这个对象详情页面。
