### ISSUE TITLE
[Bug]: 审批列表左侧菜单,未显示待审核数量

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4875]
### Description

![image](https://user-images.githubusercontent.com/6194462/235108957-57f86967-c225-4354-aaf0-261eaae1aaf6.png)

### Steps To Reproduce 重现步骤

如图

### Version 版本

2.5

**Comment by hotlong** [comment]
是不是amis版本的问题？

**Comment by baozhoutao** [comment]
sdk版本问题
