### ISSUE TITLE
[Bug]: 审批单分栏显示时，草稿箱新建或者删除申请单，流程列表不刷新

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#4877]
### Description

![image](https://user-images.githubusercontent.com/15027092/235115297-66a3c03f-ad60-402d-86a5-91c9011105f2.png)

![image](https://user-images.githubusercontent.com/15027092/235115433-04dd8e78-6543-4dcc-a88a-2f69c2a96d4c.png)

### Steps To Reproduce 重现步骤

1、进入草稿箱，切换视图为分栏显示
2、新建申请单或者删除申请单，流程列表没有刷新，必须要手动刷新才行

### Version 版本

2.5.0-beta.17

**Comment by baozhoutao** [comment]
方案: 使用 amis button 重写删除功能
