### ISSUE TITLE
新建的应用，引用的对象默认视图删除后，前台访问为空并报错

### ISSUE THREAD

**Issue by TroySu** [steedos/steedos-platform#488]
![image](https://user-images.githubusercontent.com/20942182/86336240-3047be80-bc82-11ea-97c4-24cf0db8f51e.png)

**Comment by TroySu** [comment]
http://192.168.0.108/
chenzhipei@hotoa.com
123456
分区为：华炎Hot

**Comment by hotlong** [comment]
编写触发器，禁止删除默认视图
