### ISSUE TITLE
[Bug]: 岗位成员编辑页面，设置成员，选择成员下拉框出现两个滚动条

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4881]
### Description

只需一个滚动条

### Steps To Reproduce 重现步骤

![image](https://user-images.githubusercontent.com/7665279/236097851-b52c6fdf-8045-4f16-8da9-16ff3f10fee3.png)

### Version 版本

2.4

**Comment by hotlong** [comment]
升级到 2.5 会改为弹出窗口选人
