### ISSUE TITLE
[Bug]: 选人控件，鼠标下拉到底部后，部分元素显示异常

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4882]
### Description

![image](https://user-images.githubusercontent.com/7553007/236098953-39dd8b7b-08a4-4ce6-a281-980f84b4ae3f.png)

### Steps To Reproduce 重现步骤

例如，设置》流程，编辑，选人

### Version 版本

2.5.0-beta.18

**Comment by marchtian** [comment]
![image](https://user-images.githubusercontent.com/7553007/236099979-b7cc233f-289c-4387-8b00-090389eaf484.png)
点击右上搜索图标 无反应、有报错
![image](https://user-images.githubusercontent.com/7553007/236100162-079f7690-7b3c-4ef8-9a25-0086d5e2e0d2.png)

**Comment by hotlong** [comment]
建议选人控件不要显示主部门

**Comment by marchtian** [comment]
已OK
