### ISSUE TITLE
[Bug]: 设置》人员，部分账号，修改后会报错

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4884]
### Description

![image](https://user-images.githubusercontent.com/7553007/236107916-3c452495-65ff-49d5-81ca-49bd67416cc0.png)

### Steps To Reproduce 重现步骤

原因暂不详，需在8443平台上调试确认

### Version 版本

2.5.0-beta.18

**Comment by hotlong** [comment]
@chenzhipei 查一下服务端的报错

**Comment by chenzhipei** [comment]
![image](https://user-images.githubusercontent.com/15027092/236116637-856b633d-0d53-42e5-96de-082dd3aed752.png)
