### ISSUE TITLE
[Feature]: 审批，查找增加默认选项

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4887]
### Summary 摘要

![image](https://user-images.githubusercontent.com/7553007/234449676-13d6f190-1fb1-4a2d-89b3-57ea0cd4e963.png)
审批，各列表视图，查找增加默认选项：流程、申请单状态、归档、文件标题、提交人姓名、提交人所属部门名称、提交日期

### Why should this be worked on? 此需求的应用场景？

进审批，左侧各链接，点搜索按钮

**Comment by chenzhipei** [comment]
[审批各列表视图的显示字段调整，添加默认搜索项](https://github.com/steedos/steedos-platform/commit/70b7c56feb84605f541fe2629136c83364b2093a) https://github.com/steedos/steedos-platform/issues/4888
