### ISSUE TITLE
[Bug]: 审批，新建，关联文件，输入文件标题关键字后搜索，列出的文件无变化

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4889]
### Description

和没搜索前 列出的内容一致

### Steps To Reproduce 重现步骤

审批，新建，关联文件，输入文件标题关键字后搜索，列出的文件无变化

### Version 版本

2.5.0-beta.12

**Comment by baozhoutao** [comment]
搜索条件未能拼接到查询条件上

**Comment by marchtian** [comment]
已能收到
