### ISSUE TITLE
[Bug]: 列表视图设置根据创建时间排序后，前台不生效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4890]
### Description

目前看下来，后台设置的日期、日期时间类型字段前台排序都不生效
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/236138233-9913e610-72b3-45c2-b65d-43aef03d36fa.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/236138277-c51158f8-1765-4a25-946d-f369364b49e3.png">

### Steps To Reproduce 重现步骤

后台创建对象后，设置列表视图增加创建时间字段，同时设置根据创建时间排序。

### Version 版本

2.4.14

**Comment by Flyingliao** [comment]
最新版本2.5-beta.25正常
