### ISSUE TITLE
[Bug]: 同步元数据错误，请问怎么解决这个问题

### ISSUE THREAD

**Issue by rttmoa** [steedos/steedos-platform#4895]
### Description

23:43:31.798 steedos source:retrieve -m CustomObject:wh_address_map__c
{"status":"error","message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined"}
23:43:32.686 steedos source:retrieve -m CustomObject:wh_address_map__c
 ended with exit code 0

### Steps To Reproduce 重现步骤

23:43:31.798 steedos source:retrieve -m CustomObject:wh_address_map__c
{"status":"error","message":"The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined"}
23:43:32.686 steedos source:retrieve -m CustomObject:wh_address_map__c
 ended with exit code 0

### Version 版本

"dependencies": {         "@steedos/service-community": "2.1.85"     },

**Comment by hotlong** [comment]
请描述重现步骤，谢谢

**Comment by rttmoa** [comment]
已解决  更改nodejs版本就可以啦
