### ISSUE TITLE
[Bug]: 批准过程页面，部分字段显示乱码

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4897]
### Description

需显示正常值

### Steps To Reproduce 重现步骤

![image](https://user-images.githubusercontent.com/7665279/236365451-b6bc291b-e436-4f9f-a09f-de7d8bfeb0cd.png)

<img width="1412" alt="a0909257a46ac74a9abc1f28e6ca6df" src="https://user-images.githubusercontent.com/7665279/236365492-d2348b52-6bc8-48db-ae06-60f3202d6336.png">

### Version 版本

2.4.14

**Comment by Flyingliao** [comment]
重复： https://github.com/steedos/steedos-platform/issues/4770
