### ISSUE TITLE
[Bug]: 审批中心的单据打印一直跳转循环页面，不能打印

### ISSUE THREAD

**Issue by carolym** [steedos/steedos-platform#4898]
### Description

点击打印一直循环跳出同样页面，不能执行打印
<img width="938" alt="image" src="https://user-images.githubusercontent.com/93764414/236373221-266f2fbc-6d92-40af-8c6b-42a11b3a65df.png">

### Steps To Reproduce 重现步骤

<img width="938" alt="image" src="https://user-images.githubusercontent.com/93764414/236373249-2b14fecb-e52a-47ba-ba8e-86c15219a209.png">

### Version 版本

2.5.0-beta.13

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/4899
