### ISSUE TITLE
[Bug]: 模板项目远程开发环境运行后报错，node版本不对

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#4901]
### Description

是客户发现的，应该是master分支，不过每个分支都应该确认下
<img width="823" alt="image" src="https://user-images.githubusercontent.com/6219465/236397819-3b2d9cf9-ad5b-4c90-9599-f9745fa5794b.png">

### Steps To Reproduce 重现步骤

- 进入 https://gitlab.steedos.cn/steedos/steedos-project-template 
- 选择要测试的分支
- 点击右上角的gitpod按钮开启远程开发环境
- 执行到yarn install的时候会报错，说是当前node版本低了

### Version 版本

2.4.x,2.5.x

**Comment by hotlong** [comment]
新开环境，使用docker+微服务方式运行未能重现
