### ISSUE TITLE
[Bug]: 审批王左侧菜单 待审核-流程名称 和 待办数量 重叠了

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4904]
### Description

![image](https://user-images.githubusercontent.com/6194462/236590143-81859f69-db6e-4a21-9356-cde961bc2af7.png)

### Steps To Reproduce 重现步骤

如图

### Version 版本

2.5

**Comment by hotlong** [comment]
感觉左侧还可以再宽一点
