### ISSUE TITLE
[Bug]: 前台新建列表视图后，报错

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4905]
### Description

![image](https://user-images.githubusercontent.com/7553007/236595272-30da2f23-f6af-407a-b190-bc481efa1859.png)
疑似是URL不对，不应为.../object_listviews/grid/... 而应是 对应的object的apiname

### Steps To Reproduce 重现步骤

对象列表，新建列表视图

### Version 版本

2.5.0-beta.19

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/4907 任务重复

**Comment by marchtian** [comment]
已OK
