### ISSUE TITLE
[Bug]: 列表视图切换未按设置的过滤条件生效

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4906]
### Description

列表视图的过滤提交未生效

### Steps To Reproduce 重现步骤

![image](https://user-images.githubusercontent.com/7665279/236599246-1a9edfec-eade-43eb-9268-140fad92e9c7.png)

![image](https://user-images.githubusercontent.com/7665279/236599234-b68fdca7-1fb5-4510-bf08-48d930286023.png)

### Version 版本

2.4

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-widgets/commit/7177ab30b327c9dd7274bd716cc953d2afb2d789
