### ISSUE TITLE
[Bug]: 左侧菜单栏，二级菜单字体比一级菜单字体大

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4911]
### Description

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/26241897/236611080-5304455a-e0a3-44e7-af62-e10d01ac25cb.png">

### Steps To Reproduce 重现步骤

见图片

### Version 版本

2.5.0-beta.19

**Comment by hotlong** [comment]
amis 的样式规则，不做调整。
