### ISSUE TITLE
[Bug]: 无法删除分部

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#4915]
### Description

删除分部要求删除关联组织，但关联组织是必填项，不能删除。

### Steps To Reproduce 重现步骤

1.删除分部时要求删除关联组织
![image](https://user-images.githubusercontent.com/7665279/236614172-0cc95d14-7586-49b2-a9af-0467eff6c28e.png)
2.编辑分部，关联组织是必填项，不能删除，导致分部也不能删除
![image](https://user-images.githubusercontent.com/7665279/236614228-d59d5137-17a2-4fc0-b742-b776b3fe698c.png)

### Version 版本

2.4

**Comment by hotlong** [comment]
意思是要先去组织里面删除当前分部关联的组织，才能删除分部。
