### ISSUE TITLE
[Bug]: menus 接口权限异常. 自定义简档用户登录系统后,能看到设置下的所有菜单

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4918]
### Description

![image](https://user-images.githubusercontent.com/6194462/236620838-c031e11f-a239-49ed-9440-6487d8584c09.png)

### Steps To Reproduce 重现步骤

1 自定义简档
2 新增用户并选择步骤1新建的简档
3 使用新用户登录系统

### Version 版本

2.5

**Comment by baozhoutao** [comment]
自定义简档案给选项卡授权: 查看所有

**Comment by baozhoutao** [comment]
配置
![image](https://user-images.githubusercontent.com/6194462/236716100-b9649569-6951-4628-bea8-2970e559a7ba.png)

**Comment by sunhaolin** [comment]
此问题是选项卡权限规则（根据选项卡权限的配置决定选项卡是否可见，默认可见，关闭的和隐藏的选项卡不可见）导致。
新建简档应通过复制简档功能实现，复制简档时会复制目标简档的所有选项卡权限(包括系统)。
