### ISSUE TITLE
[Feature]: 选人组件点击搜索后, 页面显示效果优化

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#4919]
### Description

![image](https://user-images.githubusercontent.com/6194462/236621710-a56fa5aa-43bb-4c43-9dd2-1f3664e103ad.png)

### Steps To Reproduce 重现步骤

如图

### Version 版本

1.2

**Comment by tujiajun** [comment]
组织树难以调整，是否可以在选人组件中，把搜索框撑满，页面显示效果感觉会相对好一些
![image](https://github.com/steedos/steedos-platform/assets/127007861/c251b2b1-6679-4413-8679-5c78ab0eb552)

**Comment by baozhoutao** [comment]
> 

左侧组织树不能往上顶吗?

**Comment by tujiajun** [comment]
这个组织树是来自crud的headertoolbar里的，通过绝对定位放到左侧，是依赖于crud的顶部位置而不是弹框顶部，没法根据上面多出来的搜索框自适应的向上顶
![image](https://github.com/steedos/steedos-platform/assets/127007861/44934f62-ab08-4084-9113-7e1d7fdc345f)

**Comment by hotlong** [comment]
> 组织树难以调整，是否可以在选人组件中，把搜索框撑满，页面显示效果感觉会相对好一些

这个方案可以
