### ISSUE TITLE
[Bug]: 手机端：第一个应用设置手机端显示后，所有应用都会显示，预期效果是只显示第一个。

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4926]
### Description

设置第一个应用在手机端显示后，所有的应用都会在手机端显示出来，预期效果是只显示第一个应用显示出来。如果第一个应用未设置手机端显示，手机端显示为空白。
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/126655403/236983076-e9521c28-e863-4f12-8539-045d553dfc8f.png">
![image](https://user-images.githubusercontent.com/126655403/236983100-1f372461-54d2-4b93-9a34-549af7392d42.png)

### Steps To Reproduce 重现步骤

1、调整应用的排序号，使应用显示在第一个。
2、设置该应用在手机端显示。
3、手机端打开项目，查看效果。

### Version 版本

2.4.15-beta.10

**Comment by hotlong** [comment]
确认一下 2.5 版本是否ok

**Comment by sujiahao66** [comment]
2.5版本正常，无法重现这个问题。
