### ISSUE TITLE
[Bug]: 设置左侧菜单后，页面滚动条消失

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4927]
### Description

应用设置tab左侧显示后，部分对象页面无法显示滚动条。原因可能是：添加内联样式时出了问题。缺少了height属性。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/126655403/237009704-c2ee3733-288d-46be-8f96-5fea47aa302f.png">

### Steps To Reproduce 重现步骤

不能确定具体哪个对象，可以确定在左侧菜单显示时，无法显示滚动条的页面中内联样式缺少height属性

### Version 版本

2.4.15-beta.10

**Comment by Flyingliao** [comment]
amis相关issue：[当crud返回的数据量少于分页配置的数量，配置的autoFillHeight: true的功能会失效](https://github.com/baidu/amis/issues/6850)
