### ISSUE TITLE
[Bug]: 上传附件-批准过程相关表选项卡中，上传附件时，前台请求的record_id传错

### ISSUE THREAD

**Issue by lihailong220** [steedos/steedos-platform#4932]
## 遇到的问题：在批准过程的相关表tab中，上传附件前台发送请求传入的record_id有误
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/125853619/237046629-22de65ed-27d1-4593-a162-d6ce0d0e702f.png">

### Steps To Reproduce 重现步骤

1. 配置批准过程 绑定对象（以合同为例）
2. 新建批准步骤并选择下一步给自己批准
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/125853619/237048157-eb5d18b7-eb87-4cf5-a5ed-7da6a1198b37.png">

3. 点合同对象预览 提请审批

4. 进入批准过程详情界面，点相关表-上传附件-即可重现
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/125853619/237048493-e3b2135c-be64-4683-8110-bef862505720.png">

5. 在network中的s3接口可查看错误请求
<img width="981" alt="image" src="https://user-images.githubusercontent.com/125853619/237040854-db9fc30d-9bd2-450c-9356-f28b952c9006.png">

### Version 版本

2.5

**Comment by baozhoutao** [comment]
不仅是附件表,相关表都有此问题.
