### ISSUE TITLE
[Bug]: 部分对象设置搜索项勾选创建时间会报错

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#4936]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/8b2e4ae3-2171-4b42-80de-a2dca3aa2261)
![image](https://github.com/steedos/steedos-platform/assets/127007861/8b1b8c25-12a5-4a97-9626-2aa75bcc9442)

### Steps To Reproduce 重现步骤

1.进入项目对象
2.设置搜索项
3.点击创建时间

### Version 版本

2.5

**Comment by yinlianghui** [comment]
重复： https://github.com/steedos/steedos-widgets/issues/438
