### ISSUE TITLE
[Feature]: 审批，接收到传阅件时，待办列表里标题后增加显示“(传阅)”

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4950]
### Summary 摘要

![image](https://github.com/steedos/steedos-platform/assets/7553007/fdfb1873-dfc4-4609-af6f-c281cc385e3c)

### Why should this be worked on? 此需求的应用场景？

根据标题里是否标记为传阅，便于用户对公文及其处理进行界定

**Comment by hotlong** [comment]
[](url)
