### ISSUE TITLE
[Bug]: 审批王缺少之前星标流程功能

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4961]
### Description

<img width="666" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/16f0a587-1766-4fb5-a58e-adb3af6d5352">

### Steps To Reproduce 重现步骤

审批王缺少之前星标流程功能

### Version 版本

2.5.0-beta.25

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4151
