### ISSUE TITLE
[Bug]: 数据导入列表导入模板列显示异常

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#4969]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194896/7abde8ce-2221-4597-9c0c-01f976098dbe)

### Steps To Reproduce 重现步骤

1. 新建数据导入

### Version 版本

2.5.0-beta.27

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/4731
