### ISSUE TITLE
[Bug]: 日历视图点新建，人员字段显示为代码

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4972]
### Description

<img width="1386" alt="企业微信截图_1dcea476-4f29-4eae-8b11-e71930fa80e8" src="https://github.com/steedos/steedos-platform/assets/50353452/72f46cd5-dd52-4d85-836b-ead9e7b5c8d8">

### Steps To Reproduce 重现步骤

huayan.steedos.cn

1. 选择应用 办公 - 日程
2. 新建

### Version 版本

2.5.0-beta.21

**Comment by yinlianghui** [comment]
是自定义字段，无需处理。
