### ISSUE TITLE
[Bug]: 对象记录，点击“查看审批单”弹出审批单的新窗口，后退箭头 点击报错

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4975]
### Description

![image](https://github.com/steedos/steedos-platform/assets/7553007/af74ac6e-9223-4d4c-9561-a4767d4cddcd)

![image](https://github.com/steedos/steedos-platform/assets/7553007/c38bb66b-15b4-4267-87d2-69850e0e7d70)

### Steps To Reproduce 重现步骤

（1）基于对象增加流程
（2）对象记录发起流程后，再点击“查看审批单”按钮

### Version 版本

2.5.0-beta.28

**Comment by tujiajun** [comment]
#4973，更换返回按钮
