### ISSUE TITLE
[Feature]: Lookup relationship 级联删除

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#4985]
### Summary 摘要

When you create a lookup relationship, you can set these options:

- Make the lookup field required for saving a record, requiring it on the corresponding page layout as well.
- If the lookup field is optional, you can specify one of three behaviors to occur if the lookup record is deleted:
  - Clear the value of this field: This is the default. Clearing the field is a good choice when the field doesn’t have to contain a value from the associated lookup record.
  - Don’t allow deletion of the lookup record that’s part of a lookup relationship: If you have dependencies built on the lookup relationship, such as a workflow rule, this option doesn’t allow the lookup record to be deleted.
  - Delete this record also: Available only if a custom object contains the lookup relationship, not if it’s contained by a standard object. However, the lookup object can be either standard or custom. Choose when the lookup field and its associated record are tightly coupled and you want to completely delete related data. For example, say that you have an expense report record with a lookup relationship to individual expense records. When you delete the report, you probably want to delete all the expense records, too.

### Why should this be worked on? 此需求的应用场景？

dev

**Comment by sunhaolin** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194896/e4bac1e9-2764-4a76-8268-fb1f9a0b49d6)

**Comment by baozhoutao** [comment]
https://help.salesforce.com/s/articleView?id=000382017&type=1

**Comment by baozhoutao** [comment]
如果级联的对象是`objects`则不会按 `Don’t allow deletion of the lookup record that’s part of a lookup relationship`. 否则会导致objects记录无法删除.  objects已有触发器来删除相关数据.
