### ISSUE TITLE
[Bug]: 手机端：新建记录完成后，弹出框未隐藏

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4990]
### Description

新建记录完成后，操作界面的弹出框需要隐藏。
![image](https://github.com/steedos/steedos-platform/assets/126655403/26b4d1e6-fbde-4e79-884d-9a353c8af109)

### Steps To Reproduce 重现步骤

1、手机端新建记录，填写数据点击保存即可重现问题。

### Version 版本

2.4.18-beta.3

**Comment by Flyingliao** [comment]
amis相关issue： [弹窗关闭问题](https://github.com/baidu/amis/issues/7060)

**Comment by Flyingliao** [comment]
重复： https://github.com/steedos/steedos-widgets/issues/430
