### ISSUE TITLE
[Bug]: 手机端：流程审批中审批流程图显示异常

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#4992]
### Description

审批流程图显示不全。
![image](https://github.com/steedos/steedos-platform/assets/126655403/cb8e7391-98b8-4979-b7a5-86934029aebe)

### Steps To Reproduce 重现步骤

1、新建流程 -> 发起审批 -> 查看流程图。

### Version 版本

2.4.18-beta.3

**Comment by Flyingliao** [comment]
测试结果：个别机型手机显示异常
<img width="330" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/4498e544-9f8d-4ff3-9dc3-8fa33ed0ccde">
