### ISSUE TITLE
[Bug]: 代码加载的应用程序自定义后，选项卡数据页面是空的

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#4999]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/60db858b-8a79-4bb3-aa32-9dce85e16766">

### Steps To Reproduce 重现步骤

1、template项目启动后，进入设置-应用程序-项目记录进入详情页，点击自定义；
2、自定义完成后，点击编辑，切换到“选项卡”tab页；可以看到页面是空的；
3、设置选项卡也选择不到本应该显示的项目应用的选项卡

### Version 版本

2.5.0-beta.29

**Comment by baozhoutao** [comment]
不处理
