### ISSUE TITLE
[Task]: 优化对象字段分组设置

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5002]
### SubTasks 子任务

![image](https://github.com/steedos/steedos-platform/assets/6219465/250217bd-02b9-4d94-b546-7cbe4b1d4a93)

**Comment by lizhenghotoa** [comment]
目前不同类型字段，配置属性顺序需要再调整一下：
- [ ] 选择框
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/16793700-f1d0-45f1-8984-3dad12920804">

- [ ] 相关表
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/9eea542b-b42d-4a86-ab42-ad7beb502a7d">

- [ ] 自动编号
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/acc2c8cd-4b05-4175-8800-962fb50d979d">

- [ ] 公式
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/6decf2cb-ce30-405d-8eb6-0cbb4e66b1e2">

- [ ] 累计汇总
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/80899ea9-e88a-4023-bf8c-c5e3567350bc">
