### ISSUE TITLE
[Bug]: 新版表单设计器创建的字段没有成功保存到库里

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5003]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/746b6017-4eb1-4082-8d09-7bbaf0363d53">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/6ebabfb3-d943-482f-9c4a-f882f7b73c48">

### Steps To Reproduce 重现步骤

1、新建流程时启用amis表单设计器；
2、使用amis设计器创建字段，保存后；
3、字段没有创建成功

### Version 版本

2.5.0-beta.30

**Comment by baozhoutao** [comment]
问题原因: 触发器未执行

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/eddbe49d-d440-45a4-8352-51ee8baccbfb)

触发器文件已加载. forms记录修改后, afterUpdate触发器未能执行
