### ISSUE TITLE
[Bug]: 审批，前台流程图显示需优化

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5005]
### Description

前台显示流程图，有时会这样
![image](https://github.com/steedos/steedos-platform/assets/7553007/be710069-4ca3-4ed4-b6cf-d9539f6b7bbe)
手机上更是没法看清
症结之一，在于，把 全部岗位成员都列出了，导致 节点非常宽
对比之前的版本
![image](https://github.com/steedos/steedos-platform/assets/7553007/97284985-b573-48e8-8cba-d3e83573983f)
显示的 是 岗位的名称 而非 全体姓名 。手机上也看得清。

### Steps To Reproduce 重现步骤

审批，某待办文件，流程图

### Version 版本

2.5.0-beta.29

**Comment by hotlong** [comment]
列出岗位成员时判断一下，最多三个，超过就 ...
