### ISSUE TITLE
[Bug]: 审批，待审核，针对传阅件，如果已过了传阅步骤，需去除正文、附件的修改权限

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5008]
### Description

在某步骤上传阅给某用户、此用户一直未处理，正常流转到其他步骤，这时，此用户进入待审核 时，应该不可 再修改正文、附件。
目前，是可以修改正文和附件的。

BTW，如果正常流转到结束，此用户进入待审核，正文、附件不可以修改。这个是对的。

### Steps To Reproduce 重现步骤

如上。

### Version 版本

2.5.0-beta.30

**Comment by hotlong** [comment]
这个应该是用脚本控制的吧？

**Comment by marchtian** [comment]
不是脚本控制的。目前，针对传阅件，如果已过了传阅步骤，菜单项、表单字段的修改权限、签署意见显示于表单等加有控制（不显示/封闭权限）了，只有 正文附件仍保留了修改权限。
