### ISSUE TITLE
[Bug]: 用户上传个人头像后，必须重新登陆才会生效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5010]
### Description

刷新页面无效，必须重新登陆
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/2ceed112-5066-4b92-9d3b-4dd269e75012">

### Steps To Reproduce 重现步骤

1. 点击头像-个人资料-编辑，上传头像后保存数据；
2. 刷新页面，头像不变；
3. 用户登出，再登陆系统后，头像才会变成新上传的用户头像

### Version 版本

 2.5.0-beta.30

**Comment by sunhaolin** [comment]
最新代码刷新页面后正常，请确认

**Comment by lizhenghotoa** [comment]
最新版本刷新后头像能够更新
