### ISSUE TITLE
[Bug]: 工作流规则公式校验规则不对

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5017]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/cff4da0e-0e83-46ec-8707-b27f7ec6dcc1">

### Steps To Reproduce 重现步骤

1、创建工作流规则，选择新建时，不填写公式，保存后，不会触发对应通知或字段更新；
2、修改工作流规则，选择新建时，填写公式，保存后，才会触发对应通知或字段更新。

### Version 版本

2.5.0

**Comment by sunhaolin** [comment]
公式字段放到 即时操作分组下；公式字段增加说明-满足以下公式时执行即时操作；过滤条件字段增加说明-满足以下过滤条件时执行依赖于时间的操作
