### ISSUE TITLE
[Bug]: 新建权限集标题显示“新建 简档 &amp; 权限集”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5018]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/67316319-e907-42de-8066-c4ce9f90bc0b">

### Steps To Reproduce 重现步骤

后台新建简档&权限集

### Version 版本

2.5.1

**Comment by hotlong** [comment]
重复

**Comment by marchtian** [comment]
https://github.com/steedos/steedos-platform/issues/4625
