### ISSUE TITLE
[Feature]: 系统字体偏小，增加大字体的个人可设置选项

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5026]
### Summary 摘要

旧版本，可以设置大/中/小字体，PC、手机随之适配字体大小
![image](https://github.com/steedos/steedos-platform/assets/7553007/eae6cf16-17db-4660-968c-c0b27349b97f)
目前的版本，默认字体也偏小一号

### Why should this be worked on? 此需求的应用场景？

中老年用户

**Comment by hotlong** [comment]
此功能不考虑，可以使用浏览器的字体放大，缩小功能。
