### ISSUE TITLE
[Feature]: 使用top限制 graphql、objectql find 返回的记录数. 否则查询记录可能会导致整个系统奔溃

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#5029]
### Summary 摘要

![image](https://github.com/steedos/steedos-platform/assets/6194462/8f000c17-ba43-4cda-94b3-4e1de0c19062)

cpu 使用达到了 100%

### Why should this be worked on? 此需求的应用场景？

instances中有 62w条记录的时候,使用graphql查询 申请单_id、name

```
{
  instances{
    _id,
    name
  }}
```

node 进程 cpu占用 `100%`、 内存占用 `3GB+`

**Comment by sunhaolin** [comment]
- [ ] graphql 添加默认top:5000
