### ISSUE TITLE
[Feature]: 审批，待审核/监控箱等，列表上增加流程过滤的快捷按钮

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5030]
### Summary 摘要

之前的版本，列表上就有个快捷按钮
![image](https://github.com/steedos/steedos-platform/assets/7553007/0360accb-3c38-4d7e-8972-2c8e48f39eb5)
![image](https://github.com/steedos/steedos-platform/assets/7553007/659885e2-e5da-46d3-9945-292033049f31)
点击，可选择流程过滤

### Why should this be worked on? 此需求的应用场景？

流程的管理员和观察员常用

**Comment by hotlong** [comment]
都在查找面板中实现吧，操作也就是多点一下。
