### ISSUE TITLE
[Feature]: 实现内核软件包的国际化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5032]
### Summary 摘要

- 软件包国际化，主要是设置界面和内核的标准对象。
- 前端控件国际化。

### Why should this be worked on? 此需求的应用场景？

英文

**Comment by hexiapengCom** [comment]
- [ ] 软件包
   - [ ] 翻译文件命名规范（去除__c）
   - [ ] 字段翻译（漏网之鱼）
   - [ ] 首页
- [ ] amis
   - [ ] toolbar
      - [ ] 按钮的lable，鼠标悬浮显示内容
      - [ ] 按钮弹出表单里面的内容
      - [ ] 左侧显示项目个数
   - [ ] 列表视图右上角的默认按钮
   - [ ] 列表视图的操作
- [ ] 设置界面
   - [ ] 左侧tabs
   - [ ] 点击头像出现的内容

**Comment by lizhenghotoa** [comment]
- [ ] 列表页按钮、记录页默认分组及按钮国际化没生效

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/72bdca80-23ab-415c-ba71-587b3ce7e172">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/fb35aab3-8003-4a8e-9e25-d85c72e5a9c0">

**Comment by tujiajun** [comment]
- [ ] 对象字段的object字段
![image](https://github.com/steedos/steedos-platform/assets/127007861/78492d9b-a9d4-45d1-bbcd-aa6687d4ebae)
 
- [ ]对象Object Action的on字段
![image](https://github.com/steedos/steedos-platform/assets/127007861/5c05cab0-36c0-49cd-bccf-1203e64e342f)
