### ISSUE TITLE
[Bug]: user 对象触发器异常.  导致users、space_users 的 locale 值未能同步

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#5034]
### Description

<img width="1469" alt="image" src="https://github.com/steedos/steedos-platform/assets/126241326/819e359a-fe7e-486a-8f95-d99f1f24130d">

### Steps To Reproduce 重现步骤

- 前往个人资料设置语言
- 打开控制台的网络

### Version 版本

2.5.3-beta.4

**Comment by sunhaolin** [comment]
platform最新代码正常
