### ISSUE TITLE
[Bug]: 目前一般用户（简档为用户）可通过点击头像下的个人资料进行用户信息资料修改，应不可修改

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5036]
### Description

一般用户不可修改除密码以外的其他所有个人信息

### Steps To Reproduce 重现步骤

<img width="1366" alt="1686036483605" src="https://github.com/steedos/steedos-platform/assets/7665279/3b1f7e7e-8112-419a-a9a5-cc08f8ccd5ea">

### Version 版本

2.4  2.5

**Comment by hotlong** [comment]
通过对象权限或字段权限处理。
