### ISSUE TITLE
[Bug]: 后台对象保存并新建功能创建多个列表视图，系统只保存最后一次提交的列表视图

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5038]
### Description

![保存并新建创建列表视图](https://github.com/steedos/steedos-platform/assets/26241897/a543dc47-84f6-4312-9f0a-f2d8d902f1e0)

### Steps To Reproduce 重现步骤

见描述截图

### Version 版本

 2.5.3-beta.2

**Comment by lizhenghotoa** [comment]
- [ ] 对象的页面布局保存并新建也是同样问题

**Comment by tujiajun** [comment]
人员对象的保存并新建按钮失效，目前看来是由于人员列表为微页面造成的页面跳转时自动关闭了dialog弹框，需要进一步分析原因

**Comment by yinlianghui** [comment]
> 人员对象的保存并新建按钮失效，目前看来是由于人员列表为微页面造成的页面跳转时自动关闭了dialog弹框，需要进一步分析原因
原因如下图所示：
解决方案是否可以定规则列表视图类型的微页面根节点不允许是page组件？
![image](https://github.com/steedos/steedos-platform/assets/6219465/e8386287-e4a6-4a3c-b6b0-0d2e0203256b)
