### ISSUE TITLE
[Bug]: 软件包中对象uiSchema接口没有返回正确的英文翻译

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#5039]
### Description

软件包中的对象是坏的，没有返回正确的英文翻译；内核对象是好的。

<img width="1458" alt="image" src="https://github.com/steedos/steedos-platform/assets/126241326/c01541e4-0d8d-4a92-897b-f7e918e8dff3">

### Steps To Reproduce 重现步骤

1. 个人资料-->设置语言：english
2. 控制台-->网络

### Version 版本

2.5.3-beta.6

**Comment by baozhoutao** [comment]
问题已确认, 是软件包未提供对于的国际化文件. 非程序bug
