### ISSUE TITLE
master_detail 类型字段的级联删除

### ISSUE THREAD

**Issue by steedos** [steedos/steedos-platform#505]
此功能待与回收站功能同步开发。

- 删除子表记录时会将其移入回收站，而将主记录保留原样；
- 删除主记录时还会删除相关的子表记录和次子表记录。
- 取消删除子表记录时会恢复该记录
- 而取消删除主记录时也会取消删除相关的子表记录和次子表记录。
- 但是，如果您删除一个子表记录，随后又单独删除其主记录，则不能取消删除该子表信息，因为它不再有关联的主记录。

**Comment by yinlianghui** [comment]
另外单独建，先不处理回收站功能
