### ISSUE TITLE
[Bug]: 手机端编辑按钮需点了后才能生效

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5050]
### Description

2.4版本手机端失效。2.5.2版本编辑列表需点了后才可以出现保存按钮。会误以为只读列表

### Steps To Reproduce 重现步骤

<img width="408" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/153f5c56-c2ca-44e0-a5d2-09b2916ea809">

### Version 版本

2.5.2

**Comment by yinlianghui** [comment]
方案：给手机端表单的字段控件加边框

#### 边框样式
```
           border: var(--Form-input-borderWidth) solid var(--Form-input-borderColor);
           border-radius: var(--Form-input-borderRadius);
```

#### 参考sf效果
![wecom-temp-164612-0b6082bc81d1192e5de26aa5a7ca3fd8](https://github.com/steedos/steedos-platform/assets/6219465/1f287110-d76b-484a-a78b-a41dcf0a6ed0)
