### ISSUE TITLE
[Bug]: 流程设计器报错无法进入

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5051]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/f021db8d-7ecc-47c4-8ed0-b73a002dd4a1)

### Steps To Reproduce 重现步骤

1.进入设置
2.进入流程
3.选择任意一条流程记录，进入记录详情页
4.点击流程设计器

### Version 版本

2.5

**Comment by hotlong** [comment]
类似的问题，要记录服务端报错。 @tujiajun
