### ISSUE TITLE
[Bug]: amis对象表格和对象表单组件字段设置配置项选不到字段

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5052]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/8b9a8669-7d3e-411d-97c6-879f6ccf6823">

### Steps To Reproduce 重现步骤

1、新建微页面，添加对象表单、对象表格；
2、设置“显示的字段”、“排除的字段”属性，选择不到字段值

### Version 版本

 2.5.3-beta.10

**Comment by Flyingliao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/41402189/809a15a4-3361-48e0-ad9f-b40b01e2af7a)
