### ISSUE TITLE
[Bug]: 审批王，驳回到开始，手机 APP上找不到处理人，电脑端正常

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5053]
### Description

正常找到处理人

### Steps To Reproduce 重现步骤

![45a7cecb8d42473e0eccfbf4ec83bce](https://github.com/steedos/steedos-platform/assets/7665279/36108f2b-620c-469a-83f0-6be5ae71f114)

### Version 版本

2.4  2.5

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/5020

**Comment by hotlong** [comment]
@baozhoutao 这个问题算是已处理了是吗
