### ISSUE TITLE
[Bug]: 手机端，搜索项占据太多区域，导致搜索结果显示区域太小

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5055]
### Description

可减小搜索项行高，或手机端只显示前3个搜索项

### Steps To Reproduce 重现步骤

![359023835d1503ab2545ec5b63508f3](https://github.com/steedos/steedos-platform/assets/7665279/b686c05c-d08f-4a1b-8eca-3a5a7146f3b4)

### Version 版本

2.4  2.5

**Comment by hotlong** [comment]
手机端点击搜索后，把搜索表单折叠起来。
