### ISSUE TITLE
[Bug]: 字段权限设置必填字段只读后，必填字段在编辑页面仍显示？

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5059]
### Description

字段权限设置必填字段只读后，必填字段在编辑页面不显示

### Steps To Reproduce 重现步骤

1. 新建对象，新建一个必填字段
2. 添加必填字段的字段权限为只读

### Version 版本

2.5.3-beta.9

**Comment by hotlong** [comment]
https://help.salesforce.com/s/articleView?id=sf.fields_universally_required_field_considerations.htm&type=5
