### ISSUE TITLE
[Feature]: amis 微页面支持使用自定义过滤器t函数进行国际化

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5067]
### Summary 摘要

在platform中自定义一个过滤器，过滤器内引用i18n的t函数，实现在amis内的国际化

### Why should this be worked on? 此需求的应用场景？

platform微页面

**Comment by tujiajun** [comment]
https://github.com/baidu/amis/issues/7140

**Comment by hexiapengCom** [comment]
t函数的使用：${xxx | t}
xxx：`String` 自定义国际化变量
