### ISSUE TITLE
[Bug]: 公告中发布对象只能选人无法勾选部门，且无法一次性选择所有人

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5072]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/aff7921f-617b-45e3-8371-e4dfe24dbdaa)

### Steps To Reproduce 重现步骤

1、新建公告
2、选择发布对象，只能选择人员，无法勾选部门
3、没有全选按钮，只能翻页选

### Version 版本

2.5.3-beta.11

**Comment by hotlong** [comment]
看看QHD以前的公告管理模块是怎么设计的

**Comment by sunhaolin** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194896/46443b84-9337-4e83-9c97-66a93ee65df7)

授权对象支持选择 授权人员、授权部门 两个字段

**Comment by sunhaolin** [comment]
交由 @yinlianghui 老师恢复cms相关功能
