### ISSUE TITLE
[Bug]: 对象详细界面左侧选项卡英文翻译过长部分被...代替

### ISSUE THREAD

**Issue by hexiapengCom** [steedos/steedos-platform#5082]
### Description

<img width="526" alt="image" src="https://github.com/steedos/steedos-platform/assets/126241326/0c9fbcd7-3db9-47be-9638-8dbf7d714e6d">

### Steps To Reproduce 重现步骤

1. 语言设置为简体中文
2. 管理员设置界面

### Version 版本

2.5.3-beta.23

**Comment by hotlong** [comment]
应该配置 --Tabs--vertical-width: 180px

**Comment by Flyingliao** [comment]
<img width="941" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/fd454ea4-126c-4f1c-aa21-2494d6ec5f16">

<img width="978" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/b98a9a2f-0ef6-40db-b8ba-197dae8bb710">
