### ISSUE TITLE
[Bug]: 数组类型lookup字段列表搜索字段加载慢，并且搜索功能是坏的

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5086]
### Description

- [ ] 值搜索不出。  【测试不准，这个是正常的】
<img width="1021" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/4bfa2e2b-8af1-4f17-bed8-0862d507e98c">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/01aa25f4-d2ab-46ef-8f83-47047db46979">

- [x] 样式优化，第一次进入搜索时，lookup字段加载很慢需要5s时间才会显示出来
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/18720c0e-9e30-459f-8631-dbaa0cbe83a3">

### Steps To Reproduce 重现步骤

可以看审计日志对象字段

### Version 版本

 2.5.3-beta.23

**Comment by Flyingliao** [comment]
表单中lookup字段reference_to为数组时，左侧的下拉选项弹窗不能根据左侧的className定位设置样式。
