### ISSUE TITLE
[Bug]: lookup树类型对象字段选值时样式不对

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5087]
### Description

这个对象开启了弹框展示，效果也不是弹框效果。
<img width="1259" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/9732751e-5d69-4ee3-89e1-b0d3ca0b0baf">
<img width="1098" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/9300544f-e30e-41f1-892e-d3c738c0d962">

### Steps To Reproduce 重现步骤

1、安装项目软件包@steedos-labs/project；

2、查看里程碑对象，新建里程碑记录。

### Version 版本

 2.5.2

**Comment by Flyingliao** [comment]
同理：也是由于配置不当属性导致的 https://github.com/steedos/steedos-platform/issues/5202

**Comment by Flyingliao** [comment]
引用的对象是tree对象、开启弹窗模式；该字段设置了depend_on属性。 ==> 该字段选项显示下拉tree模式。
