### ISSUE TITLE
[Bug]: 创建应用后，前台看不到对象选项卡

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5094]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/54377cbd-28b5-4656-b8e6-81d5f0cd715e">
前台只显示两个之前对象的选项卡
<img width="1915" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/568a9739-7cab-4057-9377-42fb5426a478">

### Steps To Reproduce 重现步骤

1、新建对象；
2、创建应用，添加刚刚创建的对象；
3、前台看不到添加的对象选项卡

### Version 版本

2.5.3-beta.26

**Comment by lizhenghotoa** [comment]
必须重启服务后前台才会正常显示菜单

**Comment by tujiajun** [comment]
[Bug]: 新建选项卡时会执行objectql.addTabConfig函数，但该函数并未定义，导致报错 #5112
待该bug修复后，再解决此issue
