### ISSUE TITLE
[Bug]: 对象添加新的相关表类型字段后，对象列表页刷新页面报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5096]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/19a9ed49-e243-4be5-94b4-cf2effd45bae">

sentry.min.js:2     POST https://5000-tomato-worm-v1lbnhz2.ws.vscode.steedos.cn/graphql 404
(anonymous) @ sentry.min.js:2
(anonymous) @ sentry.min.js:2
(anonymous) @ sdk.js:1264
amis.define.t.exports @ sdk.js:1264
amis.define.r.exports @ sdk.js:1272
amis.define.l.request @ sdk.js:1280
(anonymous) @ sdk.js:1234
(anonymous) @ sdk.js:4125
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:319
d @ sdk.js:319
fetcher @ sdk.js:4125
t @ sdk.js:2113
(anonymous) @ sdk.js:2119
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:1353
Ie @ sdk.js:1334
<unnamed action> @ sdk.js:1334
(anonymous) @ sdk.js:1353
q @ sdk.js:1353
u @ sdk.js:1353
c @ sdk.js:1353
o @ sdk.js:1353
Ie @ sdk.js:1334
o @ sdk.js:1334
(anonymous) @ sdk.js:1353
q @ sdk.js:1353
(anonymous) @ sdk.js:1353
n @ sdk.js:1353
Ie @ sdk.js:1334
bound n @ sdk.js:1334
(anonymous) @ sdk.js:1353
q @ sdk.js:1353
r @ sdk.js:1353
t.initFetch @ sdk.js:3903
(anonymous) @ sdk.js:3903
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:319
i @ sdk.js:319
(anonymous) @ df288db5b47b17493330fd216357dc23a292d471.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ df288db5b47b17493330fd216357dc23a292d471.js?meteor_js_resource=true:163
u @ sdk.js:319
(anonymous) @ sdk.js:319
d @ sdk.js:319
t.componentDidMount @ sdk.js:3903
lk @ sdk.js:1150
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sentry.min.js:2 Error: 接口报错："<!doctype html>\n\n\n<html lang=\"en\">\n\n<head>\n  <meta charset=\"utf-8\">\n  <meta name=\"viewport\"\n    content=\"user-scalable=0, initial-scale=1, minimum-scale=1, width=device-width, height=device-height\">\n  \n  <meta name=\"theme-color\" content=\"#000000\">\n  <link rel=\"manifest\" href=\"https://vscode.steedos.cn/manifest.webmanifest\">\n  <link rel=\"apple-touch-icon\" type=\"image/png\" href=\"https://vscode.steedos.cn/images/apple-touch-icon.png\" sizes=\"180x180\" />\n  <link rel=\"icon\" type=\"image/png\" href=\"https://vscode.steedos.cn/images/gitpod-196x196.png\" sizes=\"196x196\" />\n  <link rel=\"icon\" type=\"image/svg+xml\" href=\"https://vscode.steedos.cn/images/gitpod.svg\" sizes=\"any\" />\n  <title>Workspace Port Not Found - Gitpod</title>\n  <meta name=\"description\"\n    content=\"Describe your dev environment as code and get fully prebuilt, ready-to-code development environments for any GitLab, GitHub, and Bitbucket project.\">\n  <meta name=\"keywords\"\n    content=\"dev environment, development environment, devops, cloud ide, github ide, gitlab ide, javascript, online ide, web ide, code review\">\n</head>\n\n<body>\n  <noscript>\n    You need to enable JavaScript to run this app.\n  </noscript>\n  <style>\n    html {\n      box-sizing: border-box;\n      -webkit-font-smoothing: antialiased;\n      -moz-osx-font-smoothing: grayscale;\n    }\n\n    body {\n      font-family:\n        system-ui,\n        -apple-system,\n        'Segoe UI',\n        Roboto,\n        Helvetica,\n        Arial,\n        sans-serif,\n        'Apple Color Emoji',\n        'Segoe UI Emoji';\n    }\n\n    *,\n    *::before,\n    *::after {\n      box-sizing: inherit;\n    }\n\n    button {\n      border: none;\n      color: #78716C;\n      font-weight:600;\n      padding: 8px 16px;\n      font-size: 16px;\n      border-radius: 8px;\n      cursor: pointer;\n      background-color: #F5F5F4;\n      height: 40px;\n    }\n\n    button:hover {\n      background-color: #E5E5E4;\n    }\n\n    .title {\n      font-style: normal;\n      font-weight: bold;\n      font-size: 32px;\n      line-height: 40px;\n      text-align: center;\n      letter-spacing: -0.01em;\n      color: #78716C;\n      margin-block-start: 48px;\n      margin-block-end: 0;\n    }\n\n    .text {\n      font-style: normal;\n      font-weight: 500;\n      font-size: 18px;\n      line-height: 28px;\n      max-width: 500px;\n      margin-block-start: 8px;\n      margin-bottom: 32px;\n      text-align: center;\n      letter-spacing: 0.04em;\n      color: #A8A29E;\n    }\n\n  </style>\n  <div id=\"root\" style=\"display: flex; align-items: center; height: 100vh;\">\n    <div style=\"max-width: 64em; margin: auto; padding: 6em 2em; text-align: center;\">\n      <div class=\"sorry\">\n        <svg width=\"64\" height=\"64\" viewBox=\"0 0 64 64\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n          <path fill-rule=\"evenodd\" clip-rule=\"evenodd\"\n            d=\"M37.496 3.18719C39.2305 6.21936 38.176 10.082 35.1406 11.8147L16.2669 22.5882C15.7681 22.873 15.4601 23.4033 15.4601 23.9778V40.89C15.4601 41.4644 15.7681 41.9948 16.2669 42.2796L31.2068 50.8076C31.6984 51.0882 32.3016 51.0882 32.7932 50.8076L47.733 42.2796C48.2319 41.9948 48.5399 41.4644 48.5399 40.89V30.372L35.1106 37.9411C32.0658 39.6573 28.2049 38.5828 26.4869 35.5412C24.769 32.4997 25.8446 28.6428 28.8894 26.9267L48.1049 16.0963C53.958 12.7972 61.2 17.0218 61.2 23.7353V42.1741C61.2 46.4929 58.8834 50.4806 55.1297 52.6233L37.9772 62.4143C34.2734 64.5286 29.7265 64.5286 26.0227 62.4143L8.87028 52.6233C5.11656 50.4806 2.79999 46.4929 2.79999 42.1741V22.6937C2.79999 18.3749 5.11656 14.3872 8.87028 12.2445L28.8594 0.834231C31.8948 -0.898439 35.7615 0.155016 37.496 3.18719Z\"\n            fill=\"url(#paint0_linear)\" />\n          <defs>\n            <linearGradient id=\"paint0_linear\" x1=\"46.7553\" y1=\"9.67805\" x2=\"16.825\" y2=\"56.7825\"\n              gradientUnits=\"userSpaceOnUse\">\n              <stop stop-color=\"#FFB45B\" />\n              <stop offset=\"1\" stop-color=\"#FF8A00\" />\n            </linearGradient>\n          </defs>\n        </svg>\n        <h2 class=\"title\">Port <span id=\"port\"></span> Not Found</h2>\n        <p class=\"text\">Please make sure this port is exposed and your application is up and running.</p>\n        <button class=\"secondary\" id=\"refresh\" tabindex=\"0\" type=\"button\">\n          <span>Try Again</span>\n        </button>\n      </div>\n    </div>\n  </div>\n  <script>\n    let port = parseInt(window.location.hostname.split('-')[0], 10);\n    if (port) {\n      document.getElementById('port').textContent = port;\n    }\n    document.getElementById('refresh').addEventListener('click', function () {\n      window.location.reload(true);\n    });\n    window.setInterval('window.location.reload(true);', 5000);\n  </script>\n</body>\n\n</html>"
    at Object.<anonymous> (sdk.js:4125:3598)
    at sdk.js:319:4430
    at Object.next (sdk.js:319:4535)
    at i (sdk.js:319:3252)
    at df288db5b47b17493330fd216357dc23a292d471.js?meteor_js_resource=true:1:8262
(anonymous) @ sentry.min.js:2
(anonymous) @ sdk.js:2119
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:1353
Ie @ sdk.js:1334
<unnamed action> @ sdk.js:1334
(anonymous) @ sdk.js:1353
q @ sdk.js:1353
u @ sdk.js:1353
p @ sdk.js:1353
(anonymous) @ df288db5b47b17493330fd216357dc23a292d471.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ df288db5b47b17493330fd216357dc23a292d471.js?meteor_js_resource=true:163
l @ sdk.js:1353
c @ sdk.js:1353
o @ sdk.js:1353
Ie @ sdk.js:1334
o @ sdk.js:1334
(anonymous) @ sdk.js:1353
q @ sdk.js:1353
(anonymous) @ sdk.js:1353
n @ sdk.js:1353
Ie @ sdk.js:1334
bound n @ sdk.js:1334
(anonymous) @ sdk.js:1353
q @ sdk.js:1353
r @ sdk.js:1353
t.initFetch @ sdk.js:3903
(anonymous) @ sdk.js:3903
(anonymous) @ sdk.js:319
(anonymous) @ sdk.js:319
i @ sdk.js:319
(anonymous) @ df288db5b47b17493330fd216357dc23a292d471.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ df288db5b47b17493330fd216357dc23a292d471.js?meteor_js_resource=true:163
u @ sdk.js:319
(anonymous) @ sdk.js:319
d @ sdk.js:319
t.componentDidMount @ sdk.js:3903
lk @ sdk.js:1150
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <svg> attribute width: Expected length, "\\\"64\\\"".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <svg> attribute height: Expected length, "\\\"64\\\"".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <svg> attribute viewBox: Expected number, "\\\"0".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "\\\"M37.496".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <linearGradient> attribute x1: Expected length, "\\\"46.7553\\\"".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <linearGradient> attribute y1: Expected length, "\\\"9.67805\\\"".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <linearGradient> attribute x2: Expected length, "\\\"16.825\\\"".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <linearGradient> attribute y2: Expected length, "\\\"56.7825\\\"\\n".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <linearGradient> attribute gradientUnits: Unrecognized enumerated value, "\\\"userSpaceOnUse…".
t._render @ sdk.js:2730
t.htmlRef @ sdk.js:2730
Sj @ sdk.js:1133
lk @ sdk.js:1152
jk @ sdk.js:1149
ik @ sdk.js:1148
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Fk @ sdk.js:1162
jg @ sdk.js:1016
Xk @ sdk.js:1172
Qk @ sdk.js:1170
Hk @ sdk.js:1159
J @ sdk.js:862
R @ sdk.js:863
sdk.js:2730 Error: <stop> attribute offset: Expected number or percentage, "\\\"1\\\"".

### Steps To Reproduce 重现步骤

1、对象创建相关表类型字段关联“任务”对象；
2、前台列表页面刷新即可看到报错。

### Version 版本

2.5.3-beta.26

**Comment by lizhenghotoa** [comment]
修改列表视图显示字段，同时，name字段勾选“过滤器默认字段”属性后，刷新列表页也是会报错
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/57264fbc-c149-4b65-83cb-ebb24e90cb28">

**Comment by hotlong** [comment]
需要记录服务端对应时间点的报错

**Comment by baozhoutao** [comment]
此问题应该是服务卡住后,导致pod检测端口误认为服务不在线.

问题根本原因在于对象变化schema 结算慢,切会卡住服务导致. graphql schema 结算慢也导致了新建对象预览始终报错问题.
