### ISSUE TITLE
[Bug]: 新版本页面、数据加载很慢

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5097]
### Description

整体使用下来，目前几个页面加载比较慢
- 后台对象字段新建页面；
- 前台页面刷新；
- 前台对象记录新建，最夸张的一个新建记录的加载页面，需要等十几秒（可能这个对象相关表字段比较多）
<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/7cc2edcc-df52-4499-a833-1e755ab1eef0">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.5.3-beta.26

**Comment by baozhoutao** [comment]
问题1
graphql find 慢. 问题原因,  记录的 `_ui` 操作需要通过call action 调用. mo 的call action 是需要耗时的. 此部分目前无法优化.

**Comment by baozhoutao** [comment]
问题2
在页面上新建对象后, 导致系统卡顿. 系统接口会变慢

**Comment by hotlong** [comment]
相关 https://github.com/steedos/steedos-platform/issues/5135
