### ISSUE TITLE
[Bug]: 流程分类的名称与所属应用改为必填

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5098]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/24f30117-722a-4f3a-9f5f-6dabc56818d0">

### Steps To Reproduce 重现步骤

排查下来是因为审批中心中有一条待办流程的原因

### Version 版本

 2.5.3-beta.26

**Comment by hotlong** [comment]
应该是审批中新的应用名称，需要改成 workflow

**Comment by tujiajun** [comment]
![image](https://github.com/steedos/steedos-platform/assets/127007861/51c8b705-499e-45db-9184-40002997aa27)
应用程序启动器中审批中心应用无badge是由于流程分类无所属应用导致

**Comment by tujiajun** [comment]
- [ ] 名称与所属应用改为必填
- [ ] 项目上写数据库脚本将所有所属应用为空的流程分类的所属应用属性改为approve_workflow
