### ISSUE TITLE
[Bug]: 分栏视图模式，按钮较多或字数较多时，表格会被撑开

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5100]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/a43348a9-bbe5-4dad-83d1-bc34f6ba135c)
![image](https://github.com/steedos/steedos-platform/assets/127007861/10886f5f-23a0-44f8-b022-552b9da65e3f)

### Steps To Reproduce 重现步骤

1.进入设置
2.点击对象
3.进入分栏模式

### Version 版本

2.5

**Comment by tujiajun** [comment]
可能的解决方案：
判断是分栏模式时，按钮改为下拉折叠

**Comment by hotlong** [comment]
有没有可能分栏模式下，按钮也像手机一样显示为下拉

**Comment by hotlong** [comment]
但是需要考虑秦皇岛的需求，他们的新建按钮肯定不能下拉的。

**Comment by tujiajun** [comment]
![image](https://github.com/steedos/steedos-platform/assets/127007861/db3205f9-3f71-4858-bef4-837c0e40dbb3)
saleforce的分栏模式，按钮为下拉

**Comment by hotlong** [comment]
看看能不能改成，除了新建按钮以外的下拉
