### ISSUE TITLE
[Feature]: 知识模块实现左侧选择站点右侧列出选中站点文章

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5104]
### Summary 摘要

<img width="748" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/879f4a2a-b954-4e55-bcd4-35a1e19e3b57">

### Why should this be worked on? 此需求的应用场景？

目前只能通过搜索栏搜索实现过滤，不太直观和方便。

**Comment by hotlong** [comment]
重复
