### ISSUE TITLE
[Bug]: 微页面设计器内组件无法显示

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5117]
### Description

微页面设计器里面ui组件的schema无法显示
console内显示如下报错信息：
![148a19afc216fe8b9e204833b19fcfd](https://github.com/steedos/steedos-platform/assets/25192306/0e52f36c-16e0-4b0e-81c3-dd5e9a2d10ba)

### Steps To Reproduce 重现步骤

1、设置->流程->审批王
2、新建流程，勾选amis，保存
3、打开流程表单设计器
4、拖入自定义组件如对象表单
![4c434538ac90a362d262203b2825e15](https://github.com/steedos/steedos-platform/assets/25192306/4bff84d7-d852-4133-b72e-e625601d1ad9)

或者：
1、设置->微页面->新建微页面
2、类型选择 对象列表
3、打开流程表单设计器
![4c434538ac90a362d262203b2825e15](https://github.com/steedos/steedos-platform/assets/25192306/b16e830f-ad2c-4479-ac7d-b93cbc5e1483)

**只要涉及到自定义组件的，都无法显示**

### Version 版本

2.4  2.5

**Comment by yinlianghui** [comment]
此问题本地无法重现，是他们项目本地部署的域名不是https，而我们的资产包是https造成的。
