### ISSUE TITLE
[Bug]: image/file 的amis 字段receiver属性替换不生效

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5119]
### Description

通过image/file 类型的字段想要上传到一个自定义的处理地址上去，比如需要在保存s3之前进行OCR识别的场景，
修改对应字段的amis 属性， 添加
![06babe5a1045eb5a3be8582558710f3](https://github.com/steedos/steedos-platform/assets/25192306/2276434a-faf0-4372-95ce-483c1e9f1053)
不起作用，无法修改receiver的接口地址

使用对象表单的微页面，在重写字段属性中添加：
![image](https://github.com/steedos/steedos-platform/assets/25192306/3fc090f9-ac9e-41dd-9219-7d8c45cee42f)
也不生效，无法修改receiver的接口地址

### Steps To Reproduce 重现步骤

1、修改image类型的字段yml，添加amis属性值
![06babe5a1045eb5a3be8582558710f3](https://github.com/steedos/steedos-platform/assets/25192306/2276434a-faf0-4372-95ce-483c1e9f1053)
2、重启，预览效果，未生效,图片上传地址还是/s3/images

3、设置-》微页面-》新建
4、类型选择 对象表单，选择带有image类型字段的对象
5、在重写字段配置中填入：
![image](https://github.com/steedos/steedos-platform/assets/25192306/3fc090f9-ac9e-41dd-9219-7d8c45cee42f)
6、保存、发布
7、刷新页面，预览对象，未起作用，图片上传地址还是/s3/images

### Version 版本

2.4.12~2.5.4

**Comment by Flyingliao** [comment]
书写语法错误； 测试结果该功能正常。
