### ISSUE TITLE
[Bug]: 不弹框显示相关表字段，列表编辑功能无效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5120]
### Description

![不弹框相关表字段列表没办法编辑保存](https://github.com/steedos/steedos-platform/assets/26241897/7ce32cba-a273-4e72-96e8-f724ceb3b83d)

### Steps To Reproduce 重现步骤

1、对象创建相关表字段，关联一个未启用弹框显示的对象；
2、列表视图添加创建的相关表字段；
3、列表上编辑添加的相关表字段

### Version 版本

2.5.5-beta.1

**Comment by tujiajun** [comment]
[Bug]: 列表编辑lookup字段报错，无法选中 #5166
issue重复，已解决
