### ISSUE TITLE
[Feature]: html类型字段支持上传图片

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5124]
### Description

错误信息无法复制，请见截图
<img width="1436" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/4076a8ee-caec-4a43-803a-7da396c84ea8">

### Steps To Reproduce 重现步骤

1、创建html类型字段；
2、前台新建记录，html类型字段点击上传图片，选择本地图片上传后可以看到报错信息

### Version 版本

2.5.3-beta.11

**Comment by Flyingliao** [comment]
issue重复： https://github.com/steedos/steedos-platform/issues/5071
