### ISSUE TITLE
[Bug]: 设计微页面，服务端报错： Object amis-design is not found 

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5126]
### Description

ERROR 749a902006c3-47/API:    Request error! Error : Object amis-design is not found 
steedos_1       |  Error: Object amis-design is not found
steedos_1       |     at SteedosSchema.getObject (/app/node_modules/@steedos/objectql/src/types/schema.ts:134:23)
steedos_1       |     at getObject (/app/node_modules/@steedos/objectql/src/types/object.ts:2332:51)
steedos_1       |     at Service.handler (/app/node_modules/@steedos/service-objectql/package.service.js:91:29)
steedos_1       |     at /app/node_modules/moleculer/src/utils.js:212:22
steedos_1       |     at processCheckResponse (/app/node_modules/moleculer/src/validators/base.js:63:29)
steedos_1       |     at validateContextParams (/app/node_modules/moleculer/src/validators/base.js:88:15)
steedos_1       |     at ServiceBroker.timeoutMiddleware (/app/node_modules/moleculer/src/middlewares/timeout.js:31:14)
steedos_1       |     at ServiceBroker.fallbackMiddleware (/app/node_modules/moleculer/src/middlewares/fallback.js:31:11)
steedos_1       |     at ServiceBroker.errorHandlerMiddleware (/app/node_modules/moleculer/src/middlewares/error-handler.js:14:10)
steedos_1       |     at ServiceBroker.tracingLocalActionMiddleware (/app/node_modules/moleculer/src/middlewares/tracing.js:101:12)
steedos_1       |     at ServiceBroker.call (/app/node_modules/moleculer/src/service-broker.js:1215:31)
steedos_1       |     at Object.findOne (/app/node_modules/@steedos/service-object-mixin/package.service.js:75:50)
steedos_1       |     at Service.handler (/app/node_modules/@steedos/service-rest/package.service.js:503:34)
steedos_1       |     at Service.handler (/app/node_modules/@steedos/service-rest/package.service.js:286:40)
steedos_1       |     at /app/node_modules/moleculer/src/utils.js:212:22
steedos_1       |     at processCheckResponse (/app/node_modules/moleculer/src/validators/base.js:63:29)
steedos_1       |     at validateContextParams (/app/node_modules/moleculer/src/validators/base.js:88:15)
steedos_1       |     at ServiceBroker.timeoutMiddleware (/app/node_modules/moleculer/src/middlewares/timeout.js:31:14)
steedos_1       |     at ServiceBroker.fallbackMiddleware (/app/node_modules/moleculer/src/middlewares/fallback.js:31:11)
steedos_1       |     at ServiceBroker.errorHandlerMiddleware (/app/node_modules/moleculer/src/middlewares/error-handler.js:14:10)
steedos_1       |     at ServiceBroker.tracingLocalActionMiddleware (/app/node_modules/moleculer/src/middlewares/tracing.js:101:12)
steedos_1       |     at ServiceBroker.call (/app/node_modules/moleculer/src/service-broker.js:1215:31)
steedos_1       |     at Context.call (/app/node_modules/moleculer/src/context.js:286:23)
steedos_1       |     at Service.callAction (/app/node_modules/moleculer-web/src/index.js:644:26)
steedos_1       |     at Service.aliasHandler (/app/node_modules/moleculer-web/src/index.js:604:17)
steedos_1       |     at runMicrotasks (<anonymous>)
steedos_1       |     at runNextTicks (internal/process/task_queues.js:60:5)
steedos_1       |     at processImmediate (internal/timers.js:437:9)
steedos_1       |     at /app/node_modules/moleculer-web/src/index.js:469:22 

### Steps To Reproduce 重现步骤

1. 新建微页面
2. 设计微页面

### Version 版本

2.5.5

**Comment by sunhaolin** [comment]
2.5.5 新建时须选择 类型 为 记录页面 可还原此问题
2.5.6-beta.1 无此问题
