### ISSUE TITLE
[Feature]: markdown字段编辑时参照github编辑框样式

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5129]
### SubTasks 子任务

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/23f7d1ea-f95c-4576-8849-a72d716c40ec">

- 调整成github编辑框样式，顶部有编辑和预览按钮进行切换显示

<img width="875" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/a12ab214-abd6-4266-825b-a7a64c2bfe4a">

**Comment by Flyingliao** [comment]
未找到合适的处理方案，该issue暂不处理。

**Comment by hotlong** [comment]
如果不好处理，先把预览去掉。

**Comment by Flyingliao** [comment]
尝试用tab包含write、preview处理
