### ISSUE TITLE
配置在线预览服务，启用在线查看office文档

### ISSUE THREAD

**Issue by steedos** [steedos/steedos-platform#513]
如果配置了在线预览服务，对于 office 文档，附件的默认操作是在线查看，除非点击下载按钮才执行下载。

例如华炎云可使用微软云服务查看 Office 文档。

https://view.officeapps.live.com/op/view.aspx?src=http://....xlsx

**Comment by chenzhipei** [comment]
需配置public.webservices.officeOnline.url
