### ISSUE TITLE
[Bug]: 选人组件弹框显示左侧部分滚动条异常，并且可以选择已经停用的用户

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5131]
### Description

- [x] 部门滚动条异常
- [x] 可以选择停用的用户
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/0edb2c38-9ffc-469f-9f83-320028f1d30c">

### Steps To Reproduce 重现步骤

可以安装项目软件包，新建项目时，选择项目成员字段看效果

### Version 版本

2.5.5

**Comment by tujiajun** [comment]
禁止选择停用用户是否应当在对应字段的过滤器函数中去控制较为合理
![image](https://github.com/steedos/steedos-platform/assets/127007861/dd957fee-dc45-46a3-ab61-91725570ce7d)
