### ISSUE TITLE
[Bug]: 审批王表单设计器打开显示乱码

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5139]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/410fe592-7c13-42ee-b70d-729813a67eca">

### Steps To Reproduce 重现步骤

远程环境，创建流程后进入流程设计器

### Version 版本

2.5.5

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/d57e6e23-9a0a-46e8-9f2d-9c2ebb6e604d)
