### ISSUE TITLE
[Feature]: 服务端字段默认值支持解析amis公式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5155]
### Summary 摘要

- 这样只读字段和可编辑字段的默认值公式就统一了
- 原来已经写好的字段公式格式的公式不能受影响
- 如果默认值以`${`开头就识别为amis公式，否则按之前规则处理

### Why should this be worked on? 此需求的应用场景？

字段上配置默认值时需要支持公式配置

 - [x] 支持基础的amis公式写法，例如：${NOW}；  暂不支持 含有过滤器函数的写法，例如 ${xxx | json} 。

**Comment by yinlianghui** [comment]
可amis 公式引擎源码：
https://github.com/baidu/amis/tree/master/packages/amis-formula
https://github.com/baidu/amis/blob/master/packages/amis-formula/__tests__/fomula.test.ts

**Comment by hotlong** [comment]
需更新文档；需确认服务端不能执行js函数

**Comment by Flyingliao** [comment]
需要确认是否支持 amis旧写法： function函数写法。 【需要官网找下示例】
