### ISSUE TITLE
[Bug]: 注册账户后创建企业，服务端报错

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5156]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/3cbe6e3a-3958-4e87-aaae-63972a85abe1)
![image](https://github.com/steedos/steedos-platform/assets/15027092/ac51243d-f8ba-42fc-ac7a-06313e2fd6e8)

### Steps To Reproduce 重现步骤

1、服务连新库
2、使用steedos_id登录，注册新账户后，点击新建企业报错

### Version 版本

2.5.6

**Comment by baozhoutao** [comment]
未重现
