### ISSUE TITLE
[Bug]: 审批步骤使用岗位，未显示自建的岗位，只显示系统自带的岗位

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5165]
### Description

目前岗位设置时无主分部设置

### Steps To Reproduce 重现步骤

已建设的岗位
<img width="792" alt="1688975076044" src="https://github.com/steedos/steedos-platform/assets/7665279/6feb150c-b3fe-40e5-9d88-3a414ea3c799">
设置步骤岗位时，没有这些岗位
<img width="1013" alt="1688975124762" src="https://github.com/steedos/steedos-platform/assets/7665279/700c2fdd-6911-4cb8-9219-f2fbb7d06eb1">

### Version 版本

2.5.8

**Comment by sunhaolin** [comment]
- 导入的流程，分部字段没有值
