### ISSUE TITLE
[Bug]: 列表编辑lookup字段报错，无法选中

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5166]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/dbd5bd3a-2ce0-4c36-8f98-7c4d8713ae29">

### Steps To Reproduce 重现步骤

1、管理员进入后台设置-审批王-流程；
2、列表页点击记录的分类字段进行列表编辑，发现无法保存。

### Version 版本

2.5.8-beta.1

**Comment by hotlong** [comment]
如何不好处理，就禁用这个对象的列表编辑

**Comment by sunhaolin** [comment]
![图片已粘贴至2023-7-11 14-44](https://github.com/steedos/steedos-platform/assets/6194896/1eca96eb-f075-45e9-b031-d3849e1b475b)
