### ISSUE TITLE
[Bug]: 新建对象流程映射，对象--搜索功能找不到对象

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5167]
### Description

已建设的对象，无法找到

### Steps To Reproduce 重现步骤

<img width="1003" alt="1688976585829" src="https://github.com/steedos/steedos-platform/assets/7665279/574061e1-fc1c-4efb-abe7-9d945a86b8e1">
![image](https://github.com/steedos/steedos-platform/assets/7665279/48832b6d-85e3-44b3-9f20-5a8b3153edcf)

### Version 版本

2.5.8

**Comment by sunhaolin** [comment]
对象需勾选允许配置流程映射
