### ISSUE TITLE
[Bug]: 日期 (date) 字段配置默认值{{global.now}}在编辑时不显示

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#5168]
### Description

配置默认值： {{global.now}}后，新建记录时日期字段无值显示，保存后只读界面正常显示。

### Steps To Reproduce 重现步骤

1、配置： {{global.now}}。
2、点击新建记录按钮。

<img width="520" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/32b202d6-451f-4514-84b4-2af66a65ed04">

<img width="533" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/eb20c97d-c014-4cfe-bb89-fa05cc615678">

<img width="775" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/b58d8265-ac82-4a72-a239-aa51f49262ee">

### Version 版本

2.5

**Comment by hotlong** [comment]
这是 amis 的公式吗？

**Comment by Flyingliao** [comment]
应该按照对应的格式来设定默认值，示例：
日期          "date":        "2023-07-17T00:00:00.000Z"
日期时间  "datetime": "2023-07-17T02:10:10.000Z"
时间         "time":         "1970-01-01T10:10:00.000Z"
