### ISSUE TITLE
[Bug]: 系统loading页，有英文字样“LOADING_RELOAD_BUTTON_TITLE”

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5175]
### Description

![image](https://github.com/steedos/steedos-platform/assets/7553007/a395020d-4116-4b26-bcf8-876eb311623a)

### Steps To Reproduce 重现步骤

-

### Version 版本

2.5.8-beta.4

**Comment by hotlong** [comment]
写英文 Reload
