### ISSUE TITLE
[Bug]: 2.5版本defaultValue 日期时间失效

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5178]
### Description

在2.5.4版本中，设置字段为日期时间，defaultValue失效不起作用

### Steps To Reproduce 重现步骤

name: appointment_time__c
defaultValue: !!js/function |
      function () {
              var now, reValue;
              now = new Date();
              reValue = new Date(now.getTime() + 1 * 60 * 60 * 1000);
              reValue.setMinutes(0);
              reValue.setSeconds(0);
              return reValue;
            }
label: 预约时间
sort_no: 140
type: datetime

### Version 版本

2.5.4

**Comment by yinlianghui** [comment]
https://www.steedos.cn/docs/developer/form-formula
文档中提到的公式默认值写法说是也不生效了。
![image](https://github.com/steedos/steedos-platform/assets/6219465/b2f1e082-eef5-41b4-b152-e571a7c7df16)

**Comment by Flyingliao** [comment]
2.5.8-beta.5是支持 ``` defaultValue: !!js/function |   ``` 写法， 不支持  ``` defaultValue: |-  {{xxx}} ``` 写法
