### ISSUE TITLE
[Bug]: import元数据下载时插件报错“STEEDOS: Retrieve Source from Org failed to run ”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5182]
### Description

<img width="1276" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/6693d69a-1cc0-4ce9-9d2b-62cf44912e2d">

### Steps To Reproduce 重现步骤

1、同步import元数据会报错；
2、其他类型元数据同步正常

### Version 版本

2.5.8-beta.5

**Comment by baozhoutao** [comment]
需要升级下steedos cli:  由于未发正式版,所以安装的时候需要指定版本号
```
npm i -g steedos-cli@2.5.8-beta.5
```
