### ISSUE TITLE
[Feature]: 软件包启用时，支持选择是否安装demo数据

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#5183]
### Summary 摘要

软件包需要演示数据

### Why should this be worked on? 此需求的应用场景？

软件包需要演示数据

**Comment by baozhoutao** [comment]
方案1:
在 pakcage.service.js 中新增 `demoDataSchema` (amis schema)属性? 安装完成后,如果有demoDataSchema,则显示demoDataSchema.

具体方案待定

**Comment by hotlong** [comment]
设计起来有点复杂，暂时还是通过单独安装一个 demo 软件包的模式来安装示例数据。
