### ISSUE TITLE
[Bug]: 对象》相关，子表列表右侧的下拉选项（编辑、删除等） 不显示

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5190]
### Description

![image](https://github.com/steedos/steedos-platform/assets/7553007/1bb960f5-278b-4d54-9ef5-52b1b2841dd0)
系统管理员显示正常，普通用户未显示（有权限，进入后可见有 编辑等按钮）

### Steps To Reproduce 重现步骤

如上

### Version 版本

2.5.8

**Comment by Flyingliao** [comment]
原因： 
<img width="1227" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/9e4f18cb-f307-4d7e-b2c7-3b4c9ef48be5">

**Comment by hotlong** [comment]
@baozhoutao
