### ISSUE TITLE
[Bug]: 平台软件包中的.trigger.js触发器不生效

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5191]
### Description

contract软件包是平台软件包，软件包中的.trigger.js触发器未生效。
contract软件包在steedos-packages目录下，steedos-app下的.trigger.js触发器是有效的。
![image](https://github.com/steedos/steedos-platform/assets/126655403/ec9089ee-64fc-49cb-b422-09935908389d)
![image](https://github.com/steedos/steedos-platform/assets/126655403/ddaae01b-1d28-4224-9d48-32d4ab3e72a0)

### Steps To Reproduce 重现步骤

进入合同应用，点击合同tab栏，修改记录中“收付款类型”字段，即可重现。

### Version 版本

2.5.8-beta.5

**Comment by sunhaolin** [comment]
对象重复定义导致，可以删掉一个定义或者写extend
