### ISSUE TITLE
[Bug]: 前台无法获取ROOT_URL的值

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5192]
### Description

Builder.settings中获取不到
![image](https://github.com/steedos/steedos-platform/assets/127007861/8f70839a-1c23-43f1-8398-68b9cdcde6a4)
![image](https://github.com/steedos/steedos-platform/assets/127007861/23127a5a-0d5c-4633-b65c-95ecfed98645)

### Steps To Reproduce 重现步骤

1.打开控制台
2.输入Builder.settings
或
1.点击右上角关于

### Version 版本

2.5.8

**Comment by hotlong** [comment]
是不是服务端环境变量没配置？

**Comment by hotlong** [comment]
@baozhoutao

**Comment by tujiajun** [comment]
关于页面的root_url通过window.Meteor.absoluteUrl()获取显示
