### ISSUE TITLE
[内部系统-手机客户端]: 手机客户端填写审批单无法提交成功，处理人不会自动匹配显示为空白，也无法手动选择处理人

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#5193]
### Description

测试问题：
手机客户端填写审批单无法提交成功，处理人不会自动匹配显示为空白，也无法手动选择处理人。

预期结果：
能够自动匹配到对应的处理人，能够正常提交申请单

### Steps To Reproduce 重现步骤

前提：安装手机客户端

操作步骤：
手机端点击华炎魔方-》点九宫格-》审批中心-》新建-》请假申请（old）或付款申请（new）等申请单-》填写完点“提交”。

测试问题：
无法提交成功。处理人不会自动匹配显示为空白，也无法手动选择处理人。

问题截图：
![Screenshot_20230719_132000(1)](https://github.com/steedos/steedos-platform/assets/92509428/b7673edd-5682-473f-8f40-5ad88d6cff84)

### Version 版本

2.5.5

**Comment by hotlong** [comment]
应该是条件节点配置的不正确
