### ISSUE TITLE
[内部系统-手机客户端 ]:  华炎魔方手机客户端屏下方的“menu”所包含的菜单并不完整，建议改为“更多”

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#5195]
### Description

测试现象：
手机端点击华炎魔方选择任意应用进入，点击右下方的“menu”进入后所显示的菜单并不完整，它只是屏下方已显示菜单以外的补充

修改建议：
它只是屏下方已显示菜单的补充，建议将“menu”改为“更多”

### Steps To Reproduce 重现步骤

前提：安装手机客户端

操作步骤：
手机端点击华炎魔方-》点九宫格-》选择任意应用进入，比如选择“考勤”-》点击右下角“menu”

![131778a28919429bcc1232dd608bae6](https://github.com/steedos/steedos-platform/assets/92509428/f4b8466a-eea7-4944-a679-280e506b2249)

### Version 版本

2.5.5

**Comment by hotlong** [comment]
重复
