### ISSUE TITLE
[Bug]: 应用程序页面空白，应用程序设置标签权限页面空白

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5198]
### Description

1. 从数据库导出application配置后，清空数据库部署重启应用后， 打开应用，内容空白。
2. 怀疑权限没有配置好，点击admin的简挡，点击配置选项卡权限， 弹出框显示空白
![image](https://github.com/steedos/steedos-platform/assets/25192306/f7d35289-468f-431f-ba13-869d8a11867a)
![4f0209aef322bb05af6b44cf71d1bbb](https://github.com/steedos/steedos-platform/assets/25192306/c6699608-84c6-46b7-b3da-ada93c398c7c)

### Steps To Reproduce 重现步骤

1. 在界面上配置好 “应用程序”
2. 把数据库内容导出成yml配置
3. 清空数据库
4. 重启应用程序，重新初始化space
5. 登录后，点击之前配置的“应用程序”， 菜单空白
----

1. 点击admin简挡
2. 设置选项卡权限
3. 部分选项卡选项名称列是空白的

### Version 版本

2.5.8

**Comment by baozhoutao** [comment]
未能重现此问题. 请更新到2.5.9后重试.
