### ISSUE TITLE
[Bug]: 软件包升级按钮GET请求URI超长

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5199]
### Description

软件包内资源较多情况下，点击升级按钮，包URI超长，
![8c1683856f0c525fdae3256cd81ffa4](https://github.com/steedos/steedos-platform/assets/25192306/f94214b9-1a17-499d-8f54-a783dc5cb279)
![1689847130933](https://github.com/steedos/steedos-platform/assets/25192306/436509be-b913-44ef-a395-f9291418ffb0)

### Steps To Reproduce 重现步骤

1. 点击软件包
2. 点击升级

### Version 版本

2.5.8

**Comment by baozhoutao** [comment]
已处理. 69f6786c33
