### ISSUE TITLE
[Bug]: 树形相关表字段选值时样式异常

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5202]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/da357e62-e73e-4cd2-93b1-f3f2f1be8d28">

### Steps To Reproduce 重现步骤

可以创建树形对象，选择父对象字段

### Version 版本

 2.5.9

**Comment by Flyingliao** [comment]
当前对象的parent_field属性值配置不当导致，issue创建人已修改和调整相关软件包。
