### ISSUE TITLE
[Bug]: 对象表单在自定义的amis页面里面无法显示

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5205]
### Description

<img width="597" alt="6d09f20706c3c28084b6f5336847ac2" src="https://github.com/steedos/steedos-platform/assets/25192306/06ca2d1a-695f-478e-a075-3d1660bf0ae0">

自定义按钮弹框里面添加对象表单， 无法显示

### Steps To Reproduce 重现步骤

1.  新建一个自定义amis按钮
2. 按钮的事件触发 弹出确认窗口
3. 窗口内拖入一个 对象表单 组件
4. 选表单组件的对象， 选择编辑状态
5. 保存
6.测试按钮效果， 按钮有弹窗，但是没有出现对象表单

### Version 版本

2.5

**Comment by Flyingliao** [comment]
最新版本2.5.10-beta.2未重现。
稍微能重现的一个原因是 拖入 对象表单后 未点击设计器右上角的保存按钮。

**Comment by yinlianghui** [comment]
不支持"actionType": "confirmDialog"，不处理。请使用普通的dialog
