### ISSUE TITLE
[Bug]: 对象字段显示是没有滚动条，字段过多超过一屏后无法显示

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5206]
### Description

![image](https://github.com/steedos/steedos-platform/assets/25192306/f7da4a24-2560-4bfc-aa1c-c47a0b64089c)

### Steps To Reproduce 重现步骤

1. 设置-》对象-》新建对象
2. 添加字段， 40个以上+

### Version 版本

2.5

**Comment by tujiajun** [comment]
是否浏览器控制台有报错，我这边本地没有重现这个问题 @hwzero

**Comment by yinlianghui** [comment]
无法重现
