### ISSUE TITLE
[Bug]: 刷新页面时, 页面的loading效果异常. 有一个长方形横线在转圈圈.

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#5207]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194462/edd3963d-db0a-4269-88f1-9c7268b8fec7)

### Steps To Reproduce 重现步骤

刷新页面

### Version 版本

2.5.10-beta

**Comment by tujiajun** [comment]
无法重现
