### ISSUE TITLE
信息发布权限异常，发布的文章只能本人编辑，站点成员不能编辑

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#521]

**Comment by yinlianghui** [comment]
是因为这个Issue造成的，要兼容考虑：CMS字段级权限问题，[目前非站点成员没有编辑权限时，可以编辑单个字段 #1693](https://github.com/steedos/creator/issues/1693)

**Comment by yinlianghui** [comment]
已按简化方式处理：
- 站点成员以后不再可以编辑其他人的记录了，只有工作区管理员和文章owner可以编辑记录。
- 站点成员只有私有站点有用，功能也只是站点成员可见，而不是可编辑。
- 能看到站点就能发布，普通人只能修改自己发布的文章，管理员可以修改全部。
