### ISSUE TITLE
[Bug]: 流程对象映射数据审批过程中修改数据不能同步到台账

### ISSUE THREAD

**Issue by YANJIE122** [steedos/steedos-platform#5220]
### Description

流程对象映射数据审批过程中修改数据不能同步到台账

### Steps To Reproduce 重现步骤

流程对象映射数据审批过程中修改数据不能同步到台账

### Version 版本

 2.5.5

**Comment by hotlong** [comment]
最新版 2.5.10 是正常的，请描述一下具体的重现步骤，谢谢。
