### ISSUE TITLE
[Bug]: lookup 字段 reference_to 为数组时，只读模式时显示问题

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5223]
### Description

通过yml设置lookup类型字段的 refrence_to 为一个函数，实现类似tasks效果的关联表，即这个字段可以关联不通对象。 但是保存数据后，回显时空白，新增时可以正常动态选择关联表和关联的数据行， 修改时也能正常回显。 但是查看和列表视图页面上无法显示

### Steps To Reproduce 重现步骤

1. 通过yml设置lookup的refrence_to 是一个函数
![image](https://github.com/steedos/steedos-platform/assets/25192306/63e585eb-3938-4f06-a2f7-c82956e5f881)
2. 新建数据时：
![14233600dbc7caa4db35525f526f57b](https://github.com/steedos/steedos-platform/assets/25192306/19a380fd-c92c-48c3-979f-d1df432f02f9)
3.  修改数据时：
![239f7b4d4baf9d45ed667b1dda6b874](https://github.com/steedos/steedos-platform/assets/25192306/3ea48270-8527-4423-8b3b-e3e3bad26bca)
4. 查看详情时：
![630b67b7331b23a0c2d1111a28cad9f](https://github.com/steedos/steedos-platform/assets/25192306/096de150-5316-4b80-8cf2-2265fd99f656)

### Version 版本

2.5.9

**Comment by hotlong** [comment]
使用lookup实现后，不能自动显示到主表对象的相关标签页下

**Comment by hotlong** [comment]
相关 https://github.com/steedos/steedos-platform/issues/5221
