### ISSUE TITLE
[Bug]: 使用空库启动服务之后，注册并进入创建企业页面，点击提交没有任何反应

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5224]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/5db1b1e0-9185-4acb-baf1-d893fc3f6fc4)
![image](https://github.com/steedos/steedos-platform/assets/127007861/2f5fa588-418d-4bae-be12-da5a1989ea0c)

### Steps To Reproduce 重现步骤

1.使用空库启动服务
2.进入网站，通过steedosid登陆
3.输入企业并提交

### Version 版本

2.5.11-beta.3

**Comment by blood0708** [comment]
最后咋解决的啊？
