### ISSUE TITLE
[Bug]: ios17 beta版,手机端图标、按钮样式异常

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5234]
### Description

![image](https://github.com/steedos/steedos-platform/assets/26241897/f529d33a-b92e-46de-a0b0-6f56040d396a)
![image](https://github.com/steedos/steedos-platform/assets/26241897/0d5262b8-ac89-44da-8cba-2f67d9fee17a)

### Steps To Reproduce 重现步骤

ios17.0（21A5277j）版本手机列表页图标和按钮样式冲突，显示不正常

### Version 版本

 2.5.11-beta.6

**Comment by hotlong** [comment]
ios 正式版无此问题
