### ISSUE TITLE
[Bug]: 对象字段级别权限控制失效

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5236]
### Description

<img width="764" alt="387c1918c06166610825225a303cb3a" src="https://github.com/steedos/steedos-platform/assets/25192306/fd6aef87-ad15-4ed1-b269-3b6def85d1b6">

如图： 红框内字段的字段级别权限是 不可读，不可修改。 但是依旧能够在界面上正常展示

### Steps To Reproduce 重现步骤

<img width="764" alt="387c1918c06166610825225a303cb3a" src="https://github.com/steedos/steedos-platform/assets/25192306/fd6aef87-ad15-4ed1-b269-3b6def85d1b6">

如图： 红框内字段的字段级别权限是 不可读，不可修改。 但是依旧能够在界面上正常展示

### Version 版本

2.5.9

**Comment by baozhoutao** [comment]
如果在字段定义上设置了必填,则称为 “通用必填字段”
通用必填字段: 始终可见、可编辑
如果要设置字段是必填,且可控制显隐. 在字段上别设置必填, 通过页面布局来设置必填. 则可通过字段权限控制显隐.

**Comment by hotlong** [comment]
这个容易产生误会，我记得 salesforce 通用必填字段，设置权限的时候始终是必填和可见的状态。

**Comment by hotlong** [comment]
不行重新写个任务，处理字段权限的编辑界面。

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/5240
