### ISSUE TITLE
简档下的对象权限未生效

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#524]
- 新增简档
- 新增用户test，并设置为此简档
- 新增对象权限：任务
- test 登录系统看不到任务菜单。

继续
- 新增权限集，并选择test用户
- 在权限集中添加对象权限：任务
- test 登录系统可以看到任务菜单。

**Comment by baozhoutao** [comment]
此问题出现在自定义简档名称中(非admin、users、supplier、customer)
