### ISSUE TITLE
[Bug]: 设置中自定义页面布局后点击编辑没有反应

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5244]
### Description

编辑页面布局，前台没有反应，服务端也没有报错

### Steps To Reproduce 重现步骤

设置中自定义页面布局，点击编辑无反应

### Version 版本

2.5.11-beta.10

**Comment by yinlianghui** [comment]
重复 [Bug]: 页面布局详细界面编辑按钮点击没反应 #5247
