### ISSUE TITLE
[Bug]: 审批王-amis 表单 - 分组字段样式异常 & 分组字段下的字段权限异常

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#5252]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194462/b92752e8-9145-4c10-b3fa-82b220324146)

### Steps To Reproduce 重现步骤

如上图

### Version 版本

2.5

**Comment by hwzero** [comment]
![4b8ed5cc4764f86c5a43547c0d70634](https://github.com/steedos/steedos-platform/assets/25192306/ab428dd4-55d8-4574-aeaa-22fefed56571)

![e2ce86c6460686440b9e63d3b84257c](https://github.com/steedos/steedos-platform/assets/25192306/a869c1b2-4eda-4f67-9b79-d9912e51c8ad)

升级到2.5.11-beta.13 后问题依旧，只解决了样式问题

**Comment by baozhoutao** [comment]
> ![4b8ed5cc4764f86c5a43547c0d70634](https://user-images.githubusercontent.com/25192306/258369102-ab428dd4-55d8-4574-aeaa-22fefed56571.png)
> 
> ![e2ce86c6460686440b9e63d3b84257c](https://user-images.githubusercontent.com/25192306/258369268-a869c1b2-4eda-4f67-9b79-d9912e51c8ad.png)
> 
> 升级到2.5.11-beta.13 后问题依旧，只解决了样式问题
需要设置下字段分组的name. amis组件的分组字段无法设置name,所以需要通过修改schema来处理
