### ISSUE TITLE
[Bug]: 字段新增时，点保存并新建，排序号未递增

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5253]
### Description

字段新增时，点保存并新建，排序号未递增
<img width="1023" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/16339f54-f129-412c-8b13-9fcb005f1a0c">

### Steps To Reproduce 重现步骤

字段新增时，点保存并新建，排序号未递增
<img width="1023" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/16339f54-f129-412c-8b13-9fcb005f1a0c">

### Version 版本

2.5

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/5563
