### ISSUE TITLE
[Bug]: 树状结构的对象，没有选择弹出查找时，做相关表只能显示根节点的记录无法滚动选择子节点记录

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5254]
### Description

树状结构的对象，没有选择弹出查找时，做相关表只能显示根节点的记录无法滚动选择子节点记录
<img width="1241" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/da68a932-6511-45b4-be53-b41df695959a">

### Steps To Reproduce 重现步骤

树状结构的对象，没有选择弹出查找时，做相关表只能显示根节点的记录无法滚动选择子节点记录
<img width="1241" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/37298db1-e8d0-4414-8894-471f4e8f4635">

### Version 版本

2.5

**Comment by yinlianghui** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6219465/a16ab3d2-ee11-475a-8f9d-9a8105038fca)
请升级到最新的2.5.11试下，这边是好的。
