### ISSUE TITLE
[Bug]: 复制用户权限数据导入失效

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5255]
### Description

复制用户权限，有一个表的新增权限。
数据导入按钮会报没有history对象权限导致导入失败
<img width="1314" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/fbe2a1e2-1047-40ea-a62e-2335a7a1e7e1">

### Steps To Reproduce 重现步骤

复制用户权限，有一个表的新增权限。
数据导入按钮会报没有history对象权限导致导入失败

### Version 版本

2.5

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/5200 已修复
