### ISSUE TITLE
[Bug]: 流程对象映射，审批单状态更新有问题

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5257]
### Description

<img width="1885" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/3939304e-ddf3-4ec5-8a6e-f9c6860f78a0">

### Steps To Reproduce 重现步骤

1、审批完有时候不会更新审批单状态；
2、驳回时也不会更新状态

### Version 版本

2.5.11

**Comment by sunhaolin** [comment]
项目业务代码报错
