### ISSUE TITLE
[Feature]: 流程滑步功能，审批节点如果审批人之前步骤已经核准过，后续步骤自动核准

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5262]

**Comment by hotlong** [comment]
流程： 开始-部门副经理-部门经理-副总经理-人事部经理-总经理。

前提：研发部部门经理是张三，总经理也是张三

提交：研发部提交审批的时候，应该跳过部门经理审批这个步骤。

**Comment by sunhaolin** [comment]
方案二：
- [ ] 审批、会签、填写节点支持配置滑步规则，满足滑步规则时跳过此节点。
- [ ] 流程设计器中 审批、会签、填写 步骤增加 滑步规则 属性。
- [ ] 在审批时计算下一步骤和下一步骤处理人选项的接口中处理滑步。

**Comment by hotlong** [comment]
作废 的方案一
### Summary 摘要
开始-a审批-b审批-c审批-d审批-结束
a审批结束且意见为已核准
a、c处理人同一个
当前在b

-  [ ] 流程增加开关 enable_slide 是否启用滑步功能
-  [ ] 执行滑步的条件：
  - [ ] c步骤类型是审批、c处理人唯一、c后续步骤只有一条路径、c后续步骤(d)处理人唯一
  - [ ] 签核历程中最近一次的审批步骤、审批人为c的处理人、切意见为核准，如果a符合条件则滑过c提交给d审批
- [ ] 引擎中自动生成滑步的历史步骤，且意见与之前步骤一致，备注中增加显示 '滑步'

### Why should this be worked on? 此需求的应用场景？

同样步骤无需重复审批

**Comment by sunhaolin** [comment]
[执行步骤条件时step变量结构.json](https://github.com/steedos/steedos-platform/files/13421260/step.json)
