### ISSUE TITLE
[Bug]: 知识-知识编辑时候的预览和和显示不一样

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5264]
### Description

知识编辑时候的预览和和显示不一样

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/7665279/7d6a80a6-e0b6-4a56-9b62-f7f96c497a5d)
![image](https://github.com/steedos/steedos-platform/assets/7665279/124f5945-7e38-4d80-991a-3446667b34b8)

https://gitlab.steedos.cn/steedos/steedos-project-haitai/-/issues/142
### Version 版本

2.5.11

**Comment by hotlong** [comment]
应该是样式冲突
