### ISSUE TITLE
Urgent Action Required: Removal of License Key and Files from GitHub Repository!

### ISSUE THREAD

**Issue by SavinAndrew** [steedos/steedos-platform#5273]
### Description

Hello,  I am Andrew Savin, business manager of Stimulsoft. We have noted that there is an issue with the GitHub repository you have: https://github.com/steedos/steedos-platform  Regrettably, it has come to our attention that our Stimulsoft license key has been uploaded and is publicly accessible within the project, alongside our product files and libraries. This situation is in direct violation of our Developer License Agreement (DLA) and is strictly prohibited.  [Bug]: 

### Steps To Reproduce 重现步骤

We kindly request your immediate attention to rectify this matter. To resolve the issue, we urgently ask you to remove our license key and associated files from the mentioned project. We suggest that you provide a clear description within the repository, guiding users on how to access our files via our official website [stimulsoft.com](http://stimulsoft.com/). Please be advised that the distribution of our license key is permissible solely within your applications and must not be shared on public repositories.  We eagerly await your response and swift action to address this concern. Your cooperation in this regard is greatly appreciated.  Thank you for your prompt attention to this matter.

### Version 版本

no version

**Comment by baozhoutao** [comment]
已处理
