### ISSUE TITLE
[Bug]: 记录相关子表中需要显示勾选框；子表中的自定义按钮如何获得已选中的记录

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5274]
### Description

资产软件包中，生成确认单时需要选择相关的记录然后才能生成确认单，目前无法选择记录
![image](https://github.com/steedos/steedos-platform/assets/126655403/bdaf4ccc-ca5d-4bc4-a58e-7d6e3af67858)

### Steps To Reproduce 重现步骤

进入资产应用 ，填写入库单，点击生成确认单即可重现
assets软件包版本2.2.8

### Version 版本

2.5.11

**Comment by hotlong** [comment]
如果获得已选中的记录，也需要定规则

**Comment by Flyingliao** [comment]
自定义按钮中通过以下代码获取选中的记录
```
const uiSchema = event.data.uiSchema;
const listViewRef = event.context.scoped.getComponentById(`listview_${uiSchema.name}`);
const selectedItems = listViewRef.props.store.toJSON().selectedItems;
```

示例图：
<img width="747" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/a769ec3c-ccb7-45a6-b7f5-a4c37a89f999">
