### ISSUE TITLE
[Bug]: 审批中心中只需保留一个“审批任务”标签页，去除“审批单”标签页

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5275]
### Description

两个重复的页面，只需保留一个

### Steps To Reproduce 重现步骤

<img width="849" alt="1691552758242" src="https://github.com/steedos/steedos-platform/assets/7665279/d24903fa-4bb9-493e-9ae3-9a4b31f3d5b2">

### Version 版本

2.5.11

**Comment by lizhenghotoa** [comment]
steedos-labs/workflow请升级到最新的2.2.9-beta.3
