### ISSUE TITLE
[Feature]: Steedos Builder 以 docker 方式私有部署

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5276]
### Summary 摘要

https://github.com/steedos/steedos-builder

- 打包镜像
- 更新私有部署说明到 README.md

### Why should this be worked on? 此需求的应用场景？

部署

**Comment by hotlong** [comment]
目前部署在这里 https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#

**Comment by chenzhipei** [comment]
https://github.com/steedos/steedos-builder/commit/55c6ba0546c24039d2aae09689d904d40bc9d786
