### ISSUE TITLE
[Bug]: 快速编辑时若文本数据开头有空格，会自动清除开头空格，形成差异

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5277]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/4d58d75c-23f9-4fdc-863d-7cd1d5bbee6e)
![image](https://github.com/steedos/steedos-platform/assets/127007861/4addbcd0-2d8f-4a04-8440-593c274a2201)

### Steps To Reproduce 重现步骤

1.选择一条开头有空格的文本记录
2.点击快速编辑，不进行任何操作
3.点击确认

### Version 版本

2.5

**Comment by hotlong** [comment]
此规则合理，不处理
