### ISSUE TITLE
[Feature]: 对象搜索时，文本字段，支持 多个关键字+空格的模糊搜索

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5281]
### Summary 摘要

也可考虑 扩展到其他合适类型的字段

### Why should this be worked on? 此需求的应用场景？

审批王（公文），搜索标题，多关键字+空格，实现模糊搜索

**Comment by hotlong** [comment]
这个功能如果做成标准功能，搜索英文会很奇怪

**Comment by hotlong** [comment]
多关键词搜索通用搜索框中实现
https://github.com/steedos/steedos-platform/issues/5282
