### ISSUE TITLE
[Feature]: debug模式下打印推送消息日志

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5289]
### Summary 摘要

2.2版本发送推送消息时打印推送消息日志到服务端

### Why should this be worked on? 此需求的应用场景？

手机收不到推送消息时可以查看服务端日志

**Comment by sunhaolin** [comment]
- [ ] 确认是否已有开关，是否保留推送消息，如已有开关则增加环境变量控制是否开启开关
