### ISSUE TITLE
[Bug]: 子表配置depend_on后显示bug

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5294]
### Description

1.对象里配置主子表字段，该字段有depend_on字段。
<img width="971" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/9506c906-ef15-44b8-8064-18503b85ce8c">
2.在主表里面相关的子表新建，显示为id
<img width="1032" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/cc2b7dd4-1259-41b5-baa7-ea8fdf2f8807">
3.必须填写depend——on的字段后，才可以显示label
<img width="1011" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/23e287d6-883f-4943-b53c-f976c5b9292d">

### Steps To Reproduce 重现步骤

1.对象里配置主子表字段，该字段有depend_on字段。
<img width="971" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/9506c906-ef15-44b8-8064-18503b85ce8c">
2.在主表里面相关的子表新建，显示为id
<img width="1032" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/cc2b7dd4-1259-41b5-baa7-ea8fdf2f8807">
3.必须填写depend——on的字段后，才可以显示label
<img width="1011" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/23e287d6-883f-4943-b53c-f976c5b9292d">

### Version 版本

2.5

**Comment by baozhoutao** [comment]
显示为id是由于未能找到满足条件的数据.
此问题是由于字段的`filtersFunction` 编写的时候未考虑部门为空的情况.  
可以调整为`return values.contractorgan__c ? [['organization__c', '=', values.contractorgan__c ]] : filters`
