### ISSUE TITLE
[Feature]: 知识管理模块优化

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5298]
### Description

- 在页面中无法新建站点和栏目
- 且左侧无法显示已有栏目
- 并需点击站点后，页面右侧可显示站点下的文章
- [Bug]: 知识-被授权人员在进入知识后未查看到文章，但有小铃铛提示，点击提示后可查看到文章 #5302

原知识页面
![image](https://github.com/steedos/steedos-platform/assets/7665279/08e75f82-9aac-4d65-9d0c-d345c6cd4875)

### Steps To Reproduce 重现步骤

目前页面无法建设站点和栏目，并无站点树状展示
![image](https://github.com/steedos/steedos-platform/assets/7665279/7695aabd-c1b9-403a-9686-48782d6b3599)

### Version 版本

2.5.12

**Comment by Flyingliao** [comment]
大管理员：user.is_space_admin； 站点成员，admins.includes(userId)；当前用户 owner === userId。

站点新建按钮权限：是否是大管理员，是否是owner.
站点编辑按钮权限：是否是大管理员，站点成员，是否是owner.
站点删除按钮权限：是否是大管理员，站点成员，是否是owner.  如果站点下有栏目、知识不允许删除当前站点。

栏目新建按钮权限：是否是大管理员，站点成员，是否是owner.
栏目编辑按钮权限：是否是大管理员，站点成员，是否是owner.
栏目删除按钮权限：是否是大管理员，站点成员，是否是owner.  如果栏目下有知识不允许删除当前栏目。
