### ISSUE TITLE
[Bug]: 华为推送消息触发频控

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5299]
### Description

<img width="1161" alt="image" src="https://github.com/steedos/steedos-platform/assets/15027092/0a800f32-d6de-4225-85f0-b4c6d11f036b">

### Steps To Reproduce 重现步骤

华为推送数量管理规则：
https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/message-restriction-description-0000001361648361

消息分类标准：
https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/message-classification-0000001149358835#section1076611477914

应用适配开发：
https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/message-classification-0000001149358835#section1085395991513

### Version 版本

2.2、2.5

**Comment by chenzhipei** [comment]
- [ ] 管理界面需要手动激活一下
https://developer.huawei.com/consumer/cn/service/josp/agc/index.html#/myProject/9105163812218461504/9249519184595935885?appId=10277685

- [ ] 后台应用适配开发，推送消息传入category字段
<img width="957" alt="image" src="https://github.com/steedos/steedos-platform/assets/15027092/73cf3e59-afc2-4b36-b94c-199c3a21e6d0">

**Comment by sunhaolin** [comment]
https://developer.huawei.com/consumer/cn/doc/development/HMS-2-References/hmssdk_huaweipush_api_reference_agent_s2
现有发送接口已废弃

**Comment by sunhaolin** [comment]
- [ ] 使用最新接口发送
