### ISSUE TITLE
[Bug]: 对象记录新建/编辑时，点击用户字段，出来的选人控件，左侧的组织树没显示

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5300]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/32384fd0-2519-4f72-ad11-186a2bb9749a)

### Steps To Reproduce 重现步骤

例如 日程 里的 分派给

资产包:
https://unpkg.steedos.cn/@steedos-widgets/amis-object@1.2.39-beta.1/dist/assets.json

Amis版本3.2.0

### Version 版本

2.5.12-beta.4

**Comment by marchtian** [comment]
升级到2.5.12-beta.8，问题已无
