### ISSUE TITLE
[Bug]: 知识-被授权人员在进入知识后未查看到文章，但有小铃铛提示，点击提示后可查看到文章

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5302]
### Description

知识中的文章已授权用户查看，此用户并未查看到此文档，但小铃铛中有提示，，点击提示后可查看到文章。用户应可按授权进行文章查看

### Steps To Reproduce 重现步骤

1.新增文章，在授权查看-用户中选择用户
<img width="806" alt="1692154584786" src="https://github.com/steedos/steedos-platform/assets/7665279/e2ce8c79-cfc0-4363-aebd-8d6cd51ff5f7">

2.用户登陆后未能查看到文章
<img width="1368" alt="1692154413293" src="https://github.com/steedos/steedos-platform/assets/7665279/15a8cc53-f5e1-429d-99e8-9111f2a4fe1f">

### Version 版本

2.5.12

**Comment by baozhoutao** [comment]
https://gitlab.steedos.cn/steedos-labs/cms/-/commit/6e3f4cb440f5f1ebb911f98127c11c6cafa7bb19

**Comment by hotlong** [comment]
合并重复任务
