### ISSUE TITLE
[Bug]: 知识-授权部门，保存时报错，实际部门信息已存，但部门下人员看不到文章

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5303]
### Description

授权部门，保存时报错，实际部门信息已存，但部门下人员看不到文章

### Steps To Reproduce 重现步骤

1. 文章授权部门权限
![image](https://github.com/steedos/steedos-platform/assets/7665279/5ea6e903-611d-4ab2-8e79-dca33db3e812)
2.点击确认后报错
<img width="551" alt="1692156104611" src="https://github.com/steedos/steedos-platform/assets/7665279/cfeb2234-b2f6-4b78-9dbd-06b8e280f18f">
3.实际部门信息已保存,但部门下人员进入后查看不到文档，小铃铛也没提示
<img width="1361" alt="1692156486176" src="https://github.com/steedos/steedos-platform/assets/7665279/916a9808-683a-485a-a4c4-08ef4b92b2ca">

### Version 版本

2.5.12

**Comment by sunhaolin** [comment]
看不到文章由 https://github.com/steedos/steedos-platform/issues/5302 处理，这里解决新建报错
