### ISSUE TITLE
[Task]: Html字段-删除插入模板插件，目前点击也无法选择模版

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5304]
### Description

新增文章时，插入功能下有插入模板，但系统中没有设置模板的地方

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/7665279/9bada845-3505-4415-aa63-5b8504f29dc8)

### Version 版本

2.5.12

**Comment by tujiajun** [comment]
以下为富文本框内菜单中默认选项
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  menu: {
    file: { title: 'File', items: 'newdocument restoredraft | preview | export print | deleteallconversations' },
    edit: { title: 'Edit', items: 'undo redo | cut copy paste pastetext | selectall | searchreplace' },
    view: { title: 'View', items: 'code | visualaid visualchars visualblocks | spellchecker | preview fullscreen | showcomments' },
    insert: { title: 'Insert', items: 'image link media addcomment pageembed template codesample inserttable | charmap emoticons hr | pagebreak nonbreaking anchor tableofcontents | insertdatetime' },
    format: { title: 'Format', items: 'bold italic underline strikethrough superscript subscript codeformat | styles blocks fontfamily fontsize align lineheight | forecolor backcolor | language | removeformat' },
    tools: { title: 'Tools', items: 'spellchecker spellcheckerlanguage | a11ycheck code wordcount' },
    table: { title: 'Table', items: 'inserttable | cell row column | advtablesort | tableprops deletetable' },
    help: { title: 'Help', items: 'help' }
  }
});
