### ISSUE TITLE
[Feature]: 公告通知需可按部门设置权限，默认为一级部门

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5307]
### Summary 摘要

目前公告通知只可按人员授权查看，且每次发布公告都需要设置授权人员，大部分公告都是针对全体员工的，故需要针对部门设置权限，并默认为一级部门，所有员工可查看。
目前设置界面
![Uploading 1692169949005.png…]()

### Why should this be worked on? 此需求的应用场景？

发起公告通知，大部分公告都是针对全体员工

**Comment by yinlianghui** [comment]
不需要设置默认一级部门，已经可以配置人员和部门权限了。
