### ISSUE TITLE
[Bug]: 公文审批，监控箱等列表，搜索选择流程时， 不应该选中分类

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5308]
### Description

![image](https://github.com/steedos/steedos-platform/assets/7553007/b49bc8e0-b6c3-446e-87ba-90e6c6ffcd45)
勾选某流程分类后，虽然下拉框里改分类的流程已打钩，但是最上面 只有分类名，导致实际搜不出 这个分类下的流程的文件

### Steps To Reproduce 重现步骤

公文审批，监控箱等列表，搜索，流程里选择流程分类

### Version 版本

 2.5.12-beta.9

**Comment by hotlong** [comment]
![IMG_0375](https://github.com/steedos/steedos-platform/assets/50353452/8974389f-ac96-4197-b523-080134a20698)

应该配置为只包含子节点的值
