### ISSUE TITLE
[Bug]: 小铃铛提醒中通知时间显示了乱码

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5311]
### Description

通知时间显示错误，应是“xx分钟之前”
![image](https://github.com/steedos/steedos-platform/assets/126655403/403018a5-6116-4a6d-bef4-c623f10e66b6)

### Steps To Reproduce 重现步骤

1、设置工作流规则和工作流通知，查看通知即可重现。

### Version 版本

2.5.12-beta.10

**Comment by yinlianghui** [comment]
实测amis 2.9没有这个问题，3.2和3.3都有这个问题，有人报过issue了，估计是没发版本。https://github.com/baidu/amis/pull/6926

**Comment by hotlong** [comment]
官方 3.1 就说解决了。 https://github.com/baidu/amis/releases/tag/v3.1.0

**Comment by hotlong** [comment]
此问题是 moment 没有用 locale 初始化导致的。和官方修正的不是同一个问题。

可以在 amis 官网测试此 json
```json
{
  "data": {
    "created": "Mon Aug 21 2022 18:38:37 GMT+0800"
  },
  "type": "page",
  "body": [{
    "type": "tpl",
    "tpl": "<%=moment(data.created).format('yyyy-MM-DD')%>,"
  },
  {
    "type": "tpl",
    "tpl": "<%=moment(data.created).fromNow()%>,"
  },{
    "type": "tpl",
    "tpl": "<%=moment(data.created).locale('zh-CN').fromNow()%>,"
  }]
}
```
