### ISSUE TITLE
[Bug]: 设置，左侧菜单未显示出

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5312]
### Description

![image](https://github.com/steedos/steedos-platform/assets/7553007/4005f34f-ff81-43c9-8e09-c1c5bed30776)

### Steps To Reproduce 重现步骤

设置

hbp...项目中发现

疑似2.5.12-beta.11有问题、
2.5.12-beta.9没问题

### Version 版本

 2.5.12-beta.11

**Comment by hotlong** [comment]
是不是修改手机端设置导致的问题？

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/eb34da9b-a727-47bd-87cf-4125a3abaaa9)
服务端报错
