### ISSUE TITLE
[Bug]: 新建选择流程时，点击分类下没有流程的分类名称，报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5320]
### Description

“ Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'space')”

![image](https://github.com/steedos/steedos-platform/assets/26241897/b3369274-de48-48ec-aacf-865d42c96743)

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.5.12-beta.12

**Comment by tujiajun** [comment]
未重现，没有流程的分类显示与点击并未报错，另外看图片中红框的选项图标似乎应该是流程而非分类
![1692672858062](https://github.com/steedos/steedos-platform/assets/127007861/d0d7c808-2ac6-42ca-9d5c-c5864b7a27ee)
