### ISSUE TITLE
[Bug]: 审批中心点击新建之后若没有当前应用的流程分类，则会查找所有分类并返回

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5332]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/60a4bc39-184e-4fd4-80e7-41a42c78e4ee)
![image](https://github.com/steedos/steedos-platform/assets/127007861/ad5e69db-0e3d-49b0-b689-51a0e88d3868)

### Steps To Reproduce 重现步骤

1.设置流程分类为审批中心以外的其他所属应用
2.进入审批中心，点击新建会把所有流程分类都返回

### Version 版本

2.5

**Comment by hotlong** [comment]
既然是审批中心，所有分类返回也没有大问题

**Comment by tujiajun** [comment]
但是只要有一个分类所属应用是审批中心，就会只返回该分类了，其他都不返回了
