### ISSUE TITLE
[Bug]: 人员列表左侧组织树在部分账号中会变成只有一小块区域

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5333]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/90702ddd-1b11-40f9-9b0d-b4b24cea726a)

### Steps To Reproduce 重现步骤

暂时找不到规律，可能与数据有关

### Version 版本

2.5

**Comment by hotlong** [comment]
未重现
