### ISSUE TITLE
[Feature]: 华炎魔方内部的流程触发器，应支持用微服务的方式编写

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5335]
### Summary 摘要

目前页面配置的流程触发器支持同步元数据

- [ ] 没有办法同步成元数据；
- [ ] URL 无法配置；
<img width="1676" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/7c29d6b9-7e01-44cd-be00-8c2d7946e9fc">

### Why should this be worked on? 此需求的应用场景？

开发环境如果没有办法同步元数据的话，生产环境还要重复配置一次。

**Comment by hotlong** [comment]
标准软件包暂时不要用流程触发器

**Comment by hotlong** [comment]
换微服务方式编写流程触发器
