### ISSUE TITLE
[Bug]: 点击分发按钮的时候浏览器控制台报错ReferenceError: distribute_optional_users is not defined

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5349]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/9d4d77d0-db54-492a-a1ca-57ee71eed081)

### Steps To Reproduce 重现步骤

1.进入审批王应用
2.在待审批列表找一个可以分发的单子
3.点击分发按钮

### Version 版本

2.5.x

**Comment by baozhoutao** [comment]
无影响, 无需处理
