### ISSUE TITLE
[Bug]: iframe 类型选项卡未显示已选中的效果

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5358]
### Description

始终是未选中的状态

### Steps To Reproduce 重现步骤

1、配置两个iframe 选项卡
2、创建一个应用
3、查看应用

### Version 版本

2.5.12

**Comment by tujiajun** [comment]
1.点击应用进入第一个选项卡时，url路径为app/***,无法与各选项卡对应
2.进入应用后点击选项卡，选中效果正常
3.在对应选项卡刷新时，无选中效果是由于[Bug]: 通过amis的单页跳转进入iframe选项卡时，参数中的https://会被转化为https:/ #5363

**Comment by baozhoutao** [comment]
问题原因: nav的activeOn 未生效.

**Comment by baozhoutao** [comment]
activeOn的中使用变量且讲变量作为nav属性的方式仅试用2.9版本. 3.1不支持
