### ISSUE TITLE
[Bug]: 多选字段，在相关表列表中编辑时不应该设置为只读

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5359]
### Description

在人员中更换岗位成员无法进行，点击人员无反应
在审批王--岗位中进行人员更换，功能正常

### Steps To Reproduce 重现步骤

设置--人员--进入用户信息--相关--编辑岗位成员--点击人员无反应，报错
![image](https://github.com/steedos/steedos-platform/assets/7665279/374bb363-edf1-45f9-818f-55587be3ecc6)

### Version 版本

2.5.12-beta.43

**Comment by hotlong** [comment]
因为人员是多选字段，在相关表列表中编辑时不应该强制锁定。

**Comment by Flyingliao** [comment]
相关代码修改issue： https://github.com/steedos/steedos-platform/issues/4996
