### ISSUE TITLE
[Bug]: 通过amis的单页跳转进入iframe选项卡时，参数中的https://会被转化为https:/

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5363]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/8ad38a5b-618f-4904-9f63-53c0cf3e110b)
![image](https://github.com/steedos/steedos-platform/assets/127007861/a63b6f83-baa7-4725-92df-bc17191fad84)

### Steps To Reproduce 重现步骤

1.新建iframe选项卡
2.复制iframe选项卡的正确路径，并放到amis中的单页跳转内，比如button
3.点击跳转button

### Version 版本

2.5

**Comment by Flyingliao** [comment]
百度网址打不开是因为它不允许这样干，其它网址是可以的，比如官网地址：https://steedos.com。 

iframe中的url虽然少了一个 ' / '，但是不影响网址的正常打开，暂不处理。
