### ISSUE TITLE
[Bug]: 页面布局显示效果优化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5364]
### Description

1、 只读页面相关子表名称显示错误
<img width="1342" alt="企业微信截图_35163c6d-eb5b-4c8d-92db-dcbdd6a071b2" src="https://github.com/steedos/steedos-platform/assets/50353452/8ae5aa3a-f7c8-4794-92d4-8f4c663aeecd">

2、编辑界面的序号都不能正常显示，可以去掉。
<img width="1035" alt="企业微信截图_836f5283-6d0c-4b1e-bf11-f07b457b05f1" src="https://github.com/steedos/steedos-platform/assets/50353452/4d257b71-dc0c-460f-9e0c-3e088f2a9f70">

3、所有界面去掉选择字段的按钮，丑的很
<img width="208" alt="企业微信截图_aaaa7866-f1f4-4dc4-a5b5-fb07de9aa504" src="https://github.com/steedos/steedos-platform/assets/50353452/3d9b974f-463e-43e3-9ee7-1152f13764b6">

4、所有自定义编辑界面去掉外边框
<img width="1085" alt="企业微信截图_e3381ddc-9fd2-4804-b2b4-55bdb4ed8fe5" src="https://github.com/steedos/steedos-platform/assets/50353452/28365018-7521-466c-8a9e-72f00e60c185">

### Steps To Reproduce 重现步骤

1. 运行项目模版

### Version 版本

2.5.12

**Comment by tujiajun** [comment]
1.只读页面相关子表名称显示错误：相关子表情况特殊，目前只通过amis属性覆盖tpl的方式显示，但显示结果为数据库中保存数据而非对应中文名，可能需要通过自定义详细的方式进行优化
![image](https://github.com/steedos/steedos-platform/assets/127007861/2e314513-c6aa-40b9-9c1e-f53660b5823c)
