### ISSUE TITLE
[Feature]: grid字段中只读字段 checkbox 类型为 true 时，显示效果优化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5365]
### Summary 摘要

看能不能用 fa 的图标显示  <i class="fa-solid fa-check"></i>

https://fontawesome.com/icons/check?f=classic&s=solid

### Why should this be worked on? 此需求的应用场景？

只读界面

**Comment by hotlong** [comment]
graphql _ui 接口如果返回 html，前端要能正常渲染。

```
<i class="fa-solid fa-check"></i>
```

**Comment by yinlianghui** [comment]
- 重现方法：流程详细界面步骤栏中的开关属性值应该显示为图标而不是勾符号
<img width="719" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/dbf48c1d-fedc-47b6-bdd2-59f92ff90efe">

- 是grid字段中的boolean类型字段统一问题，已经改为主字段时boolean一样显示为svg图标，没有使用fa图标。
