### ISSUE TITLE
[Bug]: checkbox类型字段默认值 填写 false/true时报错

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5366]
### Description

![image](https://github.com/steedos/steedos-platform/assets/25192306/57e800a2-c658-4e81-a6a6-8c1a9aad35c2)

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/25192306/6faefbb9-5e20-4850-8db4-c104521dddbb)

### Version 版本

2.5.12

**Comment by hotlong** [comment]
2.6 处理的更复杂。https://github.com/steedos/steedos-platform/issues/4114 
2.5 建议对于布尔型字段在识别默认值的时候，尝试转换一下。
