### ISSUE TITLE
[Bug]: 审批王有些流程同步成代码后，加载到新环境后流程在审批中心中显示不出来

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5368]
### Description

审批中心中发起不了人事相关流程，但是后台流程列表中有相关人事流程
<img width="1165" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/92a9b4ca-56b3-418b-aeab-65bf1e7679d7">

### Steps To Reproduce 重现步骤

重新规则请联系我

### Version 版本

 2.5.12-beta.43

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/6d144526-ee21-4bf7-9b6d-497ccf7642bc)
原因是流程开启了 “审批王端禁止发起” 开关.  platform无需修改.

**Comment by baozhoutao** [comment]
在元数据中的可以看到`forbid_initiate_instance`属性值为`true`
