### ISSUE TITLE
[Bug]: gitlab环境steedos插件没有import类型元数据可以同步

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5389]
### Description

插件版本已安装到最新的2.3.4
<img width="433" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/4dd7f32a-ab00-44a0-bbc7-9180631a3de0">
<img width="1085" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/6f62a605-eeeb-4a30-a7b0-6767205181ec">

### Steps To Reproduce 重现步骤

gitlab远程环境会出现这个问题，本地环境可以正常同步导入元数据

### Version 版本

2.5.12-beta.40

**Comment by hotlong** [comment]
npm i steedos-cli --global

**Comment by lizhenghotoa** [comment]
重新执行 npm i steedos-cli --global 后也没用

**Comment by lizhenghotoa** [comment]
已修正
