### ISSUE TITLE
[Feature]: 优化 amis fetcher 函数，自动处理 api.url & api.headers.Authorization

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5399]
### Summary 摘要

目前需要手工编写 requestAdaptor
```
"requestAdaptor": "api.url = Builder.settings.rootUrl  + api.url; if(!api.headers){api.headers = {}};api.headers.Authorization='Bearer ' + Builder.settings.tenantId + ',' + Builder.settings.authToken  ;return api;",
```

### Why should this be worked on? 此需求的应用场景？

开发

**Comment by hotlong** [comment]
相关任务 https://github.com/steedos/steedos-platform/issues/5401

**Comment by baozhoutao** [comment]
如果是url是相对路径且是`Cordova`环境时, 将url转换为绝对路径(加root url);
如果是相对路径且没有配置`headers. Authorization` 则自动添加认证信息.

**Comment by baozhoutao** [comment]
改动平台:
- [ ] platform
- [ ] builder
