### ISSUE TITLE
[Bug]: 列表单元格编辑，throw new Error,没有Error弹框提示信息

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5400]
### Description

- 在列表视图中的单元格修改信息
- 通过beforeUpdate触发器，throw new Erro("xxxx")。
- error信息，只在后台控制台显示。前台没有error弹框提示。
- 
![image](https://github.com/steedos/steedos-platform/assets/129827462/71679024-bd70-4cc1-abe5-ec31cd59f647)

### Steps To Reproduce 重现步骤

- 在列表视图中的单元格修改信息
- 通过beforeUpdate触发器，throw new Erro("xxxx")。
- error信息，只在后台控制台显示。前台没有error弹框提示。

### Version 版本

2.5.13-beta.5

**Comment by Flyingliao** [comment]
cms项目中：当采用批量删除知识时，如果有报错信息，界面上不会提示出来； 采用单条记录删除时，如果有报错信息，界面上会提示报错信息。

<img width="937" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/b831ac78-a68f-49ec-8a59-84c7024c2023">
