### ISSUE TITLE
[Feature]: 增加接口查询流程对应的表单上配置的显示的列清单

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5404]
### Summary 摘要

需要返回列api名称和列显示名称
<img width="1137" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/9715db75-93ef-47cc-a328-7476fd93a977">

### Why should this be worked on? 此需求的应用场景？

审批列表需要支持根据选中流程后在右侧列表额外添加两个流程表单中的列，即任务：https://github.com/steedos/steedos-project-hbport/issues/382

**Comment by baozhoutao** [comment]
无需开发, 用graphql即可.
```
{
  forms__findOne(id: "156e024c602ebc00358e285d"){
    current
  }
}
```
![image](https://github.com/steedos/steedos-platform/assets/6194462/2808204a-1504-4c10-adfa-75fa4d446ad7)

**Comment by yinlianghui** [comment]
### 传入flowId获取表单字段集合GraphQL query
```
# Write your query or mutation here
{
    flow: flows__findOne(id:"65v3gMpMS22AH9t4R"){
    	name
      current,
    	form__expand{
        name,
        current
      }
    }
}
```

### 待审核传入instance_task id获取表单字段值GraphQL query
```
# Write your query or mutation here
{
    instance_tasks: instance_tasks__findOne(id:"3eeb2e3a665c1e7c6b28483d"){
    	flow_name,
    	instance_name,
    	step_name,
    	instance_state,
    	instance__expand{
        values
      }
    }
}
```

### 监控箱传入instance id获取表单字段值GraphQL query
```
# Write your query or mutation here
{
    instances: instances__findOne(id:"5XqEHfinL9GkuAfdE"){
    	flow_name,
    	name
    	values
    }
}
```
