### ISSUE TITLE
[Feature]: 显示子表记录时，应该自动删除主表记录对应的列

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5413]
### Summary 摘要

目前会显示，且列表链接点击没反应

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by hotlong** [comment]
目前配在页面布局中配置子表字段时，如果选中了主表列，会显示。例如项目表

**Comment by Flyingliao** [comment]
在此issue中已经处理了： https://github.com/steedos/steedos-platform/issues/5490
