### ISSUE TITLE
[Feature]: lookup 类型字段可配置是否显示新建按钮

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5422]
### Summary 摘要

如果 lookup 类型字段 配置了过滤条件，会导致新建出的记录无法显示，显示成一串 id。

1. 定义字段的时候，有一个 create 配置 ，应该识别此属性
```
create: false
```

2. 在编辑字段的时候，如果是 lookup 类型字段，应该显示此属性。

### Why should this be worked on? 此需求的应用场景？

业务人员

**Comment by Flyingliao** [comment]
lookup字段功能相关位置：
<img width="674" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/18a87cd5-fda2-41d8-b7ad-7713c6264ece">

**Comment by Flyingliao** [comment]
该字段属性配置如下：
create 属性类型是boolean,  属性 label 是“是否显示新建按钮”， 属性划分到“高级”分组。
<img width="537" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/256c5f87-8985-43a2-9cf0-d53a5a8e2a88">

最终控制显示 新建按钮的条件是： 当前用户有该lookup字段关联对象的创建权限 + 该字段的create为true。
