### ISSUE TITLE
[Feature]: 编辑字段时，隐藏 filtersFunction 函数，显示 filters 属性，并提供可视化编辑

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5423]
### Summary 摘要

filters 属性是一个数组，并且提供可视化编辑的界面

### Why should this be worked on? 此需求的应用场景？

开发

**Comment by baozhoutao** [comment]
需要与前端确认filters 是否有解决级联数据的能力.

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/6416
