### ISSUE TITLE
[Bug]: 审批王，修改审批意见会自动清空下一步处理人

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5426]
### Description

在审批界面上，审批意见会自动清空下一步处理人

### Steps To Reproduce 重现步骤

1. 发起审批
2. 选择下一步处理人
3. 填写审批意见，下一步处理人被清空
4. 选择下一步处理人
5. 清空审批意见，下一步处理人被清空

### Version 版本

2.5.13

**Comment by baozhoutao** [comment]
由此改动导致: https://github.com/steedos/steedos-platform/issues/1003
