### ISSUE TITLE
[Bug]: 服务启动时未校验.field.yml文件名与name属性不一致的情况

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5438]
### Description

如 aaa.filed.yml ：
```yml
name: bbb
```
启动服务后未校验，导致作为软件包安装时校验报错

### Steps To Reproduce 重现步骤

新增字段
aaa.filed.yml ：
```yml
name: bbb
```
启动服务

### Version 版本

2.5.13-beta.12

**Comment by baozhoutao** [comment]
1 检测到如果是dev环境,则输出警告级别日志
2 安装软件包的时候,如果是扫描元数据报错,不应该显示到前端,因为此错误并不影响软件包的启动和数据加载.
