### ISSUE TITLE
[Bug]: 分栏模式下列表的记录如果没有超过翻页数量，则不会显示滚动条，看不到底下的记录

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5444]
### Description

是在审批王列表页面看到的问题，但是这个问题是平台的列表界面标准的问题
![image](https://github.com/steedos/steedos-platform/assets/6219465/6d5625af-24ce-4a9c-8074-5cf3a6ab8226)

### Steps To Reproduce 重现步骤

1. PC上进入一个对象的列表界面
2. 通过新建记录让记录总数小于20条，且浏览器高度显示不下
3. 此时可以看到列表是有滚动条的
4. 如果把列表切换到分栏模式，就可以看到底部的记录被隐藏看不到了，因为没显示滚动条
5. 此时进一步新建几条记录，让记录总数大于20条，就可以看到滚动条正常显示了

### Version 版本

2.5.x

**Comment by Flyingliao** [comment]
amis相关建立的issue： https://github.com/baidu/amis/issues/6850。

原因：6850中已经描述清楚了。
amis官方在3.4.0中已经解决了。
基于当前项目暂不升级amis版本， 先采用 FooterToolbar中添加switch-per-page值进行折中处理该bug。
