### ISSUE TITLE
[Feature]: 可视化字段布局设计

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5447]
### Summary 摘要

基于 steedos-board 组件开发可视化页面布局设计功能

### Why should this be worked on? 此需求的应用场景？

定义对象

**Comment by tujiajun** [comment]
子任务: [Feature]: 新建页面布局时，将对象上的分组信息初始化到页面布局中 #5565

**Comment by tujiajun** [comment]
[Bug]: steedos-board组件value值未实时更新 #5570

**Comment by tujiajun** [comment]
- [ ] 增加新增字段按钮
- [ ] 弹出页面使用查看页面 /api/page/view/6535ed29e693a61392a499b0
- [ ] 保存按钮放到右上角
- [ ] 字段拖拽后，未实时更新 https://github.com/steedos/steedos-platform/issues/5570
