### ISSUE TITLE
[Bug]: 微页面-相关表组件“相关列表对象”属性应该可以选择到创建对象时启用功能表（如审批、审计日志等）

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5448]
### Description

<img width="1610" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/71be0d49-0b41-4046-84c3-9a4239939f0d">
<img width="1630" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/1738fa10-a6fa-4943-a044-05d38353abe4">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.5.13-beta.19

**Comment by hotlong** [comment]
应该是表被改为隐藏了
