### ISSUE TITLE
[Bug]: 列表视图列上配置wrap为true允许换行，但是出现连续的英文字符及数字的时候不会换行

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5458]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/c3ef1781-26f1-417b-8c2e-23d890bd958e)

### Steps To Reproduce 重现步骤

1. 列表上某一列配置为允许换行
2. 某条记录该列字段值设置为连续的英文字符或数字，中间不可以有空格，-_等字符
3. 可以看到列表上这列没有换行

### Version 版本

2.5.x

**Comment by hotlong** [comment]
这是 wrap 的规则，英文有空格才会换行
