### ISSUE TITLE
[Feature]: 适配国产数据库

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5469]
### Summary 摘要

通过外部数据源连上达梦数据库：

达梦数据库文档：https://eco.dameng.com/document/dm/zh-cn/start/index.html

项目地址：https://gitlab.steedos.cn/steedos-labs/dm-connector

### Why should this be worked on? 此需求的应用场景？

信创国产化适配

**Comment by hotlong** [comment]
达梦不支持标准的驱动，可以适配 tidb

**Comment by chenzhipei** [comment]
调整为使用Tidb
项目地址：https://gitlab.steedos.cn/steedos-labs/tidb-connector
Tidb文档：https://docs.pingcap.com/
