### ISSUE TITLE
[Feature]: 软件包列表改为card模式

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5473]
### Summary 摘要

软件包列表改为card模式

### Why should this be worked on? 此需求的应用场景？

开发

**Comment by yinlianghui** [comment]
给amis报bug了：crud card模式配置了headerToolbar时，无法通过headerToolbarClassName来为headerToolbar配置className https://github.com/baidu/amis/issues/8244
此bug造成toolbar样式不可以通过配置 `headerToolbarClassName: "px-4 py-2 border-gray-300 bg-gray-100 border-solid border-b"`，来实现toolbar的背景及边框线效果，只能用page的css定制实现一次上面的className对应的样式功能。
