### ISSUE TITLE
[Bug]: OIDC配置自己搭建的keycloak，每个账号登录授权后，都提示‘创建新企业’，不符合预期

### ISSUE THREAD

**Issue by millszhang1005** [steedos/steedos-platform#5492]
### Description

OIDC配置自己搭建的keycloak，keycloak中配置关联了LDAP用户数据，期望通过LDAP域账号能授权登录Steedos。
首次登录的用户，可创建企业，且自动成为管理员，但其他用户登录仍然提示‘创建新企业’，不会自动使用创建好的企业，不符合预期。
是否可以配置默认企业，达到LDAP的用户登录后，自动和默认企业关联？

### Steps To Reproduce 重现步骤

1.自己搭建keycloak服务，配置连接LDAP服务。
2.配置OIDC，配置如下
- STEEDOS_TENANT_ENABLE_PASSWORD_LOGIN=true
      - STEEDOS_IDENTITY_OIDC_ENABLED=true
      - STEEDOS_IDENTITY_OIDC_CONFIG_URL=http://172.17.7.149:8080/realms/master/.well-known/openid-configuration
      - STEEDOS_IDENTITY_OIDC_CLIENT_ID=steedos-oidc-public
      - STEEDOS_IDENTITY_OIDC_CLIENT_SECRET=none
      - STEEDOS_IDENTITY_OIDC_NAME=Steedos
      - STEEDOS_IDENTITY_OIDC_LABEL=使用域账号登录
 3.启动服务，点击‘使用域账号登录’按钮，跳转keycloak登录页面，输入域账号密码，登录后会跳转到‘创建新企业’界面(已经创建过企业，换了账号登录仍然会提示‘创建企业’)

### Version 版本

社区版2.5

**Comment by baozhoutao** [comment]
需要工作区管理员启用 `启用自助注册`
设置- 公司设置-公司 编辑, 勾选 `启用自助注册` 保存.

![image](https://github.com/steedos/steedos-platform/assets/6194462/1aa06f28-36c2-4ede-80c3-0ce26ca42ec2)

**Comment by baozhoutao** [comment]
@millszhang1005
