### ISSUE TITLE
[Bug]: 内网部署环境下，微页面设计器打不开

### ISSUE THREAD

**Issue by adou28** [steedos/steedos-platform#5494]
### Description

docker部署，因为内网没有互联网， 参考[steedos-unpkg](https://github.com/steedos/steedos-unpkg)，内网环境部署steedos-unpkg，steedos-platform配置env STEEDOS_UNPKG_URL，可以正常登录，CDN缓存可以能正常保存在 cache文件夹，但打开用户界面-微页面里，任意打开一个页面，打开设计器，无法打开，控制台提示：
![image](https://github.com/steedos/steedos-platform/assets/3335922/41f318e9-68bd-4164-96d3-abe941f6436f)
请问如何解决，谢谢

### Steps To Reproduce 重现步骤

1.设置
2.用户界面
3.微页面
4.点击任意页面
5.点击设计器

### Version 版本

Self Host 2.5.12

**Comment by adou28** [comment]
配置了STEEDOS_UNPKG_URL=http://192.168.5.55:9080

**Comment by hotlong** [comment]
目前微页面设计器没有开源，需要访问云端设计环境才能使用。
