### ISSUE TITLE
[Bug]: 页面删除创建的对象时，没有把字段权限数据同时删掉

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5495]
### Description

<img width="1683" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/97ed3ba9-0fb7-439a-b879-2abfe0bdb1f3">

### Steps To Reproduce 重现步骤

1、页面创建对象；
2、同步到代码；
3、页面删除对象

### Version 版本

2.4.15-beta.5

**Comment by baozhoutao** [comment]
根据截图可以看出显示的字段权限是代码定义的(系统列☑️),  通过页面操作是不可以直接操作硬盘文件的.
