### ISSUE TITLE
[Bug]: 同步软件包时 DEFAULT_PACKAGE_PATH 配置未生效，始终同步到 steedos-app

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5496]
### Description

配置 DEFAULT_PACKAGE_PATH=steedos-packages-pm/project 未生效

2.5.14-beta.5 正常
2.5.14-beta.11 错误

### Steps To Reproduce 重现步骤

- 运行 steedos-ee
- 配置 DEFAULT_PACKAGE_PATH=steedos-packages-pm/project
- 元数据未能同步到指定文件夹

### Version 版本

2.5.14-beta.11

**Comment by baozhoutao** [comment]
问题原因: steedos-cli 版本太旧导致. 
现有pod可以先卸载旧版安装新版:
```
npm remove steedos-cli -g
```
```
npm i -g  steedos-cli
```
