### ISSUE TITLE
[Bug]: 微页面相关表组件，列表上的相关表字段值显示不出

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5502]
### Description

列表的相关表字段配置了reference_to_field属性，具体配置如下：
name: mes_component_fields
create: false
filterable: false
generated: false
index: false
is_name: false
is_wide: false
label: 构件物料字段
multiple: true
primary: false
required: true
searchable: false
show_as_qr: false
sort_no: 130
sortable: false
type: lookup
write_requires_master_read: false
reference_to: object_fields
reference_to_field: name
filtersFunction: !<tag:yaml.org,2002:js/function> |-
  function (filters, values) {
    return ['object', '=', 'mes_component_detail']
  }

### Steps To Reproduce 重现步骤

<img width="1678" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/d64dec0d-83e9-4886-b9aa-97e4a96eb03e">
<img width="1901" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/1ff148ba-058f-4071-acec-722ee09c72d0">

### Version 版本

2.4.13

**Comment by Flyingliao** [comment]
代码提交地址：https://github.com/steedos/steedos-widgets/commit/14928dbbe5a8d3faf96685edfa3263f982b19b2e
