### ISSUE TITLE
设置-公司设置：点击左边公司后，第一次显示正常，再点击一次公司后，出现异常界面

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#551]
![image](https://user-images.githubusercontent.com/6194462/87009624-ff263b80-c1f7-11ea-94de-3cf0ee40b738.png)

**Comment by yinlianghui** [comment]
我这边platfrom的合同及creator源码都没重现

**Comment by yinlianghui** [comment]
要加rootURL后缀才能重现，已处理
