### ISSUE TITLE
[Bug]: ios 17，手机app，中文输入会导致闪退

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5517]
### Description

在任何文本框输入中文都会闪退。
手机浏览器没有此问题。
输入英文没有此问题。

### Steps To Reproduce 重现步骤

- 下载手机app
- 登录华炎魔方
- 输入文字

### Version 版本

2.5.14

**Comment by hotlong** [comment]
经测试，安装第三方输入法，例如 微信输入法、百度输入法，可以解决此问题。

**Comment by baozhoutao** [comment]
模拟器未能重现

**Comment by hotlong** [comment]
iOS 17.0.3 已修复
