### ISSUE TITLE
[Bug]: 手机端列表/详情页没有按钮也会显示下拉选择按钮的标志，容易产生误导

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5525]
### Description

![详情页按钮](https://github.com/steedos/steedos-platform/assets/26241897/066309e5-601b-4635-9442-2b285b84af5d)

### Steps To Reproduce 重现步骤

见图片

### Version 版本

2.5.15-beta.2

**Comment by Flyingliao** [comment]
延伸任务：https://github.com/steedos/steedos-platform/issues/5541
