### ISSUE TITLE
[Feature]: 列表底部翻页按钮看不出可以翻到下一页

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5526]
### Summary 摘要

会让人误以为只有一页数据
![列表翻页效果](https://github.com/steedos/steedos-platform/assets/26241897/522118c6-702d-4ad4-bae6-8ec469d64f08)

### Why should this be worked on? 此需求的应用场景？

实际使用中

**Comment by tujiajun** [comment]
该问题是由于amis更新了分页组件移动端造成的，可行的处理方式有两种，一是去除移动端样式，二是添加上记录数量
![image](https://github.com/steedos/steedos-platform/assets/127007861/746daa2a-d2d7-48fe-9666-d8997073b669)

**Comment by hotlong** [comment]
参考官网手机端样式，加上左侧显示。 https://aisuda.bce.baidu.com/amis/zh-CN/components/crud#%E5%A2%9E

<img width="373" alt="企业微信截图_f3422d78-5d99-4594-bcf4-7691885969b3" src="https://github.com/steedos/steedos-platform/assets/50353452/76116ece-e0aa-47d6-87b8-9434d5b17dd5">
