### ISSUE TITLE
[Bug]: 手机客户端 加载自定义amis设计的页面，调用接口渲染数据，页面提示报错

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5527]
### Description

手机客户端页面报错，但是浏览器打开这个页面不报错
![自定义详情页amis](https://github.com/steedos/steedos-platform/assets/26241897/fd05cb51-0edc-43be-bef1-42d572b9569c)

### Steps To Reproduce 重现步骤

请联系我

### Version 版本

2.5.15-beta.2

**Comment by hotlong** [comment]
这是接口没调用到。返回了网页
