### ISSUE TITLE
[Feature]: lookup (master/detail) 字段上支持配置填充规则

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5531]
### Summary 摘要

- 下图描述了简道云上为“关联数据”字段类型的字段配置填充规则的过程，可以作为参考
- 简道云在界面上只能为“关联数据”字段类型配置填充规则，按amis autoFill功能，其实是可以为任何字段类型配置填充规则的，见： https://aisuda.bce.baidu.com/amis/zh-CN/components/form/formitem#%E9%85%8D%E7%BD%AE%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85
- 可以先实现autoFill功能再提供在界面上为字段配置填充规则的能力
- 需要考虑表单初始化完成后也让填充规则生效，即配置了填充规则的字段有默认值时应该自动触发填充行为，比如子表上新建记录时自动把主表上的某个字段值填充到新建表单上的某个字段值中

![image](https://github.com/steedos/steedos-platform/assets/6219465/b8dfd28b-3a85-4de3-804d-aa34dc4dd11c)
![image](https://github.com/steedos/steedos-platform/assets/6219465/d891f161-c3a6-4d34-89b1-9c3c505b0427)
![image](https://github.com/steedos/steedos-platform/assets/6219465/8c35eaae-1a79-4b66-8bcc-b199569aefee)

### Why should this be worked on? 此需求的应用场景？

目前只能通过给字段配置amis属性来实现自动填充功能，不方便。
比如在字段上配置以下值为Amis属性表示自动把字段testx__c中的值填充到字段longtext__c中：
```
{
  "autoFill": {
    "longtext__c": "${testx__c}"
  }
}
```
上面testx__c变量值可以是表单上本身存在的字段值，也可以是lookup字段扩展出来子字段值（即配置了上面amis属性的字段为lookup字段时，此lookup字段请求接口时拿到的字段值）。
![image](https://github.com/steedos/steedos-platform/assets/6219465/965a0840-e21e-49d2-b9b7-ea9ec5fa9bf0)

**Comment by yinlianghui** [comment]
因为包括amis最新版本sdk在内，都不支持带api的autoFill在表单初始化时触发，所以本次没有用api的方式请求要填充的字段，已经给amis报issue了，此功能规则如下：

- 弹出模式时：
  - 在配置了填充规则的情况下，表单初始化时除了会加载all/lookup列表视图中配置的字段列，还会根据规则中配置的字段映射关系，补上填充规则中依赖的字段列
  - 在没配置填充规则的情况下，保持原规则不变，即表单初始化时会加载all/lookup列表视图中配置的字段列
- 下拉模式（还包括Tree下拉模式）时：
  - 在配置了填充规则的情况下，表单初始化时除了会加载label/value字段，还会根据规则中配置的字段映射关系，补上填充规则中依赖的字段
  - 在没配置填充规则的情况下，保持原规则不变，即表单初始化时只会加载label/value字段，不加载all/lookup视图中配置的字段列
- 选人选组字段：
  - 选人字段经确认没问题
  - 选组字段之前为了实现赖加载模式，自定义了lookup字段的api接口，所以目前不支持填充规则，以后有需求再说

**Comment by hotlong** [comment]
相关任务 https://github.com/steedos/steedos-platform/issues/5842
