### ISSUE TITLE
[Bug]: 软件包停用后状态为“启动中”，应该为“已停用”

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5537]
### Description

<img width="596" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/d4410e03-fa10-455d-b201-a103fed11bec">
<img width="1173" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/c83a5a57-a98c-44a6-a0bd-713c97455ea0">

### Steps To Reproduce 重现步骤

停用软件包即可

### Version 版本

2.5.15-beta.7

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/3e931533-d91a-4d85-bb14-9f1434a0244f)
未能重现,请提供pod
