### ISSUE TITLE
[Bug]: 应用编辑时进入选项卡页面加载很慢，大概需要等待五秒

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5539]
### Description

<img width="1340" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/fe2b2da4-5b98-4c26-9f00-ce9085a2e8eb">

### Steps To Reproduce 重现步骤

编辑应用

### Version 版本

2.5.15-beta.7

**Comment by yinlianghui** [comment]
慢的原因应该是网络问题，我本地并不能重现慢的现象，后续需要再观察还会不会有此问题，接口情况：
- 点击编辑按钮弹出窗口会发出5个请求（即uiSchema接口和一个lookup字段的请求除外有5个请求）
- 经过优化，减少了2个请求（都是返回所有对象选项清单的请求），目前还有3个请求会发出，无法进一步缩减。
