### ISSUE TITLE
[Bug]: 设置应用选项卡分组时，选项卡数据会一直跳到最底下

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5540]
### Description

然后会导致选项卡的顺序乱掉了，还要进入到选项卡设置中，重新拖拽设置选项卡的顺序
<img width="1232" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/e572ba8c-5bfc-4fea-8ac5-4fe86c3e2c65">

### Steps To Reproduce 重现步骤

设置应用选项卡的分组

### Version 版本

2.5.15-beta.7

**Comment by yinlianghui** [comment]
这是规则，有选项卡分组的就会排序放到最后面
