### ISSUE TITLE
[Bug]: 界面上自定义按钮的问题

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#5541]
### Description

1、界面上新建的按钮最外层的visibleOn始终为"true".
```
{
    "type": "steedos-object-button",
    "name": "record_button",
    "objectName": "tasks",
    "visibleOn": "true",
    "className": "button_record_button"
}
```
可能造成的影响：visibleOn始终为"true"，虽然amis按钮内部可以设置显示隐藏的条件，但是当记录页没有其它按钮且该按钮设置为隐藏时，该按钮如果存在于“更多”下拉菜单中时，点击“更多”下拉菜单时，显示空内容，没有按钮。

### Steps To Reproduce 重现步骤

1、在记录页新建一个显示位置在“显示在记录查看页右上角的“更多”下拉菜单中”选项的按钮。
2、进入设计器设置该按钮："hidden": true。
3、把“更多”下拉菜单中的其它按钮全部通过权限隐藏掉。
4、在记录页查看效果。

<img width="837" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/9f3d2722-8f58-4c9f-9a7e-2ccfea3d2a9e">

### Version 版本

2.5.15-beta.7

**Comment by hotlong** [comment]
没看懂，你和 @baozhoutao 讨论一下

**Comment by Flyingliao** [comment]
<img width="474" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/a6172630-9035-4e48-982e-daf08c145c66">
