### ISSUE TITLE
[Bug]: 列表选择框背景色样式看起来怪怪的

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5542]
### Description

<img width="1020" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/97060034-8809-44d0-9840-45b483f7abd6">

之前的效果：
<img width="519" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/0901163c-8441-4f77-8ec7-fde0edfcc7d4">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.5.15-beta.10

**Comment by hotlong** [comment]
背景色设置的深一点，字体就会是白色

**Comment by hotlong** [comment]
不处理
