### ISSUE TITLE
[Bug]: amis微页面设计器中没有moment变量，导致点击手机预览查看时如果有日期等相关字段就会报错，不能正常预览。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#5547]
### Description

讨论的大致解决方案：改设计器, 设计器把amisRequire放出来. 【widgets中单独引用moment可能需要全部改成amisRequire("moment")】

<img width="874" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/0ee59649-10cd-41cc-a694-1f1d435f6898">

### Steps To Reproduce 重现步骤

1、对象中新建日期、日期时间等时间字段
2、修改记录微页面
3、在amis设计器中，表单recordId定个死值，然后点击手机预览。

### Version 版本

2.5.15-beta.12

**Comment by Flyingliao** [comment]
相关issue： https://github.com/steedos/steedos-widgets/issues/489

**Comment by baozhoutao** [comment]
amisRequire是 js运行模式下才有的函数. 方案调整为: 给window下添加moment变量. 修改资产包中amisRequire('moment') 为 window.moment

**Comment by baozhoutao** [comment]
需要更新builder
