### ISSUE TITLE
[Bug]: 对象后台设置页面，有两个“流程映射”tab页

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5548]
### Description

<img width="669" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/6f57196e-cc69-4748-b201-54eb4517d948">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.5.15-beta.12

**Comment by lizheng-steedos** [comment]
最新版2.5.20-beta.15还是有这个问题
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/2d29e44e-bdfd-4235-8557-bb7d0d2a7aba">
