### ISSUE TITLE
[Bug]: 新建部门时，上级部门字段没有必填标识

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5549]
### Description

![image](https://github.com/steedos/steedos-platform/assets/26241897/e066912f-8f76-483e-b05b-fdb3b072d8b1)

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.4.13

**Comment by hotlong** [comment]
不能字段上配置必填，否则初始化数据保存不成功。
