### ISSUE TITLE
[Bug]: 在连接外部数据源时，无法显示表数据

### ISSUE THREAD

**Issue by mjf9999** [steedos/steedos-platform#5551]
## 问题

- 外部数据源在显示指定字段时报错 ER_BAD_FIELD_ERROR: Unknown column 'tp_test._ui' in 'field list'

## 截图例子

<img width="1531" alt="截屏2023-10-09 17 36 52" src="https://github.com/steedos/steedos-platform/assets/52985072/1cb0b347-603e-4d1f-a456-014fca0fe190">

## 预期

- 期望能正常对外部数据源完成 增删改查功能

### Steps To Reproduce 重现步骤

1，添加mysql外部数据源
2，添加外部数据源一个test表对象
3，点击列表视图
4，点击所有视图->编辑
5，添加任意2个字段
6，保存后->点击预览
7，按F12查看

### Version 版本

2.5

**Comment by mjf9999** [comment]
<img width="2065" alt="截屏2023-10-11 14 05 19" src="https://github.com/steedos/steedos-platform/assets/52985072/810692c6-9aa7-4af6-bc9c-e9f8e6d07f0f">

@baozhoutao 您好，当点击编辑行时，还是有相同的问题。感谢您的跟进，谢谢🙏

**Comment by hotlong** [comment]
你用的新发布的 2.5.15 版本吗

**Comment by baozhoutao** [comment]
> <img alt="截屏2023-10-11 14 05 19" width="2000" src="https://user-images.githubusercontent.com/52985072/274158863-810692c6-9aa7-4af6-bc9c-e9f8e6d07f0f.png">
> @baozhoutao 您好，当点击编辑行时，还是有相同的问题。感谢您的跟进，谢谢🙏

@mjf9999 版本还未发布, 预计本周5
