### ISSUE TITLE
[Bug]: 审批王选择框类型字段配置了默认值，前台发起流程时默认值不生效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5554]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/1f9f0c70-74cd-4e09-9184-fbb507515525">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.5.15-beta.12

**Comment by baozhoutao** [comment]
点击详细页面的 表单设计器 ,通过表达设计器来设置默认值.  

老版本的 下拉框选项不支持 label与value不一致的情况.

**Comment by lizhenghotoa** [comment]
表单设计器中已经配置了默认值，但是界面还是不显示
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/11b76e22-9692-446f-92dc-6f0bf291d99d">
<img width="1397" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/9c3aa50d-ea6d-447e-aeaa-9bc8b6f7895e">

**Comment by baozhoutao** [comment]
改表单设计器
