### ISSUE TITLE
[Bug]: 日期字段配置 defaultValue: '{now}' 无效

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5555]
### Description

<img width="256" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/21ec0ffa-00a4-46ce-9226-c9e279205078">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.5.15-beta.12

**Comment by hotlong** [comment]
这是什么语法？参考的哪个文档？

**Comment by Flyingliao** [comment]
测试结果：新建记录的时候 type:date 的字段不会显示默认值，因为格式不对；但是它能正常保存到数据库中。新建记录后只读状态也是正常的，能显示默认值。 编辑状态显示不了值。

<img width="1232" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/78cdedc3-de4c-4890-b01b-ea907ee9034f">

**Comment by Flyingliao** [comment]
日期（type: date）字段默认值正确的配置方法：
```
    defaultValue: !<tag:yaml.org,2002:js/function> |-
      function () {
        var date = window.moment().utc();
        date.set("hours",0);
        date.set("minutes",0);
        date.set("seconds",0);
        date = date.toDate();
        return date;
      }
```

**Comment by hotlong** [comment]
这个写法太复杂了，有没有简单的，或者说能不能特殊处理一下，支持 {now}

**Comment by hotlong** [comment]
还有 如果 global.now 是假的，就去掉

**Comment by yinlianghui** [comment]
已改为以下规则：
- 执行前端公式表达式时，现算global.now属性的值
- 增加日期类型字段默认值中配置global.today的功能，表示今天，也是执行公式时现算
- 为兼容老代码中给日期类型配置的的公式值为`{now}`或`{global.now}`的情况，强制把日期类型的字段默认值中的`{now}`或`{global.now}`转换成`{global.today}`计算了。

**Comment by yinlianghui** [comment]
> 已改为以下规则：
> 
> * 执行前端公式表达式时，现算global.now属性的值
> * 增加日期类型字段默认值中配置global.today的功能，表示今天，也是执行公式时现算
> * 为兼容老代码中给日期类型配置的的公式值为`{now}`或`{global.now}`的情况，强制把日期类型的字段默认值中的`{now}`或`{global.now}`转换成`{global.today}`计算了。


now是以下脚本的简写：
```
defaultValue: !<tag:yaml.org,2002:js/function> |-
  function () {
    var date = new Date(); //不是一定要写成：var date = window.moment().utc().toDate();
    return date;
  }
```
today是以下脚本的简写（日期类型字段，不是日期时间类型字段）：
```
defaultValue: !<tag:yaml.org,2002:js/function> |-
  function () {
    var date = window.moment().utc();
    date.set("hours",0);
    date.set("minutes",0);
    date.set("seconds",0);
    date = date.toDate();
    return date;
  }
```

**Comment by Flyingliao** [comment]
最新支持的{today}有bug：取的是gloabl.today. 
实际上的示例：
```
global: {
    "today":Fri, Nov 3, 2023, 08:00 AM
}
```
表单上取值：(date_today__c是字段API名称)
```
"date_today__c":"2023-11-03T00:00:00.857Z"
```
bug：出现了毫秒 => 875 

日期字段如果格式不对编辑状态不会显示值。

**Comment by yinlianghui** [comment]
> 最新支持的{today}有bug：取的是gloabl.today. 实际上的示例：
> 
> ```
> global: {
>     "today":Fri, Nov 3, 2023, 08:00 AM
> }
> ```
> 
> 表单上取值：(date_today__c是字段API名称)
> 
> ```
> "date_today__c":"2023-11-03T00:00:00.857Z"
> ```
> 
> bug：出现了毫秒 => 875
> 
> 日期字段如果格式不对编辑状态不会显示值。

已把毫秒设置为0了，实测修改后正常。
