### ISSUE TITLE
[Feature]: 软件包中定义的amis按钮，支持自定义修改

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5561]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/a2f7fb96-599b-41e3-ba9e-938fa64c4244">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.5.5-beta12

**Comment by hotlong** [comment]
如果改动不大可以在2.5 开发，否则就等2.6。
