### ISSUE TITLE
[Bug]: 对象字段新建页面排序号不能自增

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#5563]
### Description

当新建一个对象字段以后，点击保存并新建按钮后，字段的排序号无变化。

### Steps To Reproduce 重现步骤

当新建一个对象字段以后，点击保存并新建按钮后，字段的排序号无变化。

### Version 版本

2.5.15

**Comment by baozhoutao** [comment]
重置表单,无法执行初始化脚本.  amis 表单保存接口的responseData也无法覆盖form data. 
字段默认值支持动态默认值, 需要使用 表单公式 , 但未找到 表单公式 相关文档, 不清楚如何编写.

**Comment by baozhoutao** [comment]
字段动态默认值也不支持 保存并新建.

**Comment by baozhoutao** [comment]
对象字段正在开发设计器,此问题在设计器上解决.
