### ISSUE TITLE
[Feature]: 外部数据源，oceanbase 兼容性测试

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5566]
### Summary 摘要

https://github.com/oceanbase/oceanbase

### Why should this be worked on? 此需求的应用场景？

国产化

**Comment by hotlong** [comment]
https://medium.com/oceanbase-database/use-oceanbase-in-node-js-build-a-crm-with-sequelize-and-express-fd4a3f2e8d87

**Comment by hotlong** [comment]
放到 https://github.com/steedos/steedos-examples/with-db-oceanbase

**Comment by chenzhipei** [comment]
- [ ] 预览对象数据时报错：
![image](https://github.com/steedos/steedos-platform/assets/15027092/ba5de283-60ec-46e0-b4af-7a522567efbb)
服务端报错：
![image](https://github.com/steedos/steedos-platform/assets/15027092/d3bf4df9-720c-4a5d-a4ae-43d0aea669b2)


- [ ] 新建对象数据时报错：
![image](https://github.com/steedos/steedos-platform/assets/15027092/5d22d604-418d-49f1-9dba-f017cff4e0d3)

服务端报错
![image](https://github.com/steedos/steedos-platform/assets/15027092/a6a202c2-8b55-4b85-8b86-1e5a560d4de4)

**Comment by chenzhipei** [comment]
使用2.5.17版本没有报错
