### ISSUE TITLE
[Bug]: 数据导入完成后，上传excel导入数据的窗口不会自动刷新消失

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5567]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/5057e7e5-e078-4f05-8f70-e349469d9fa1">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.5.15-beta.12

**Comment by sunhaolin** [comment]
[Bug]: 导入完成后应刷新界面 #5305

**Comment by yinlianghui** [comment]
是因为把amis sdk版本降级到2.9造成的，3.2没有这个问题。
因为2.9不支持form的stopAutoRefreshWhen值为false时自动重新触发form的inited事件，而导入成功后刷新数据及关闭窗口都是写在form的inited事件中的。

**Comment by yinlianghui** [comment]
> 是因为把amis sdk版本降级到2.9造成的，3.2没有这个问题。 因为2.9不支持form的stopAutoRefreshWhen值为false时自动重新触发form的inited事件，而导入成功后刷新数据及关闭窗口都是写在form的inited事件中的。

把解决方案换成amis form的asyncApiFinished属性来配置导入完成后关闭窗口功能，一样只能在amis sdk 3.2下才生效，2.9还是不行。
