### ISSUE TITLE
[Feature]: 关于考虑js默认数值计算不准问题，提供标准的语法和文档

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5575]
### Summary 摘要

如 0.1 + 0.2 = 0.30000000000000004

### Why should this be worked on? 此需求的应用场景？

金额计算等对数值准确性要求高的场景

**Comment by hotlong** [comment]
+(0.1 + 0.2).toFixed(10); 
+(0.1 * 0.2).toFixed(10); 
+(0.3 - 0.2).toFixed(10);

**Comment by hotlong** [comment]
```
// 使用 decimal.js
Decimal.add(0.1, 0.2).toNumber(); // 结果为0.3
```
