### ISSUE TITLE
[Feature]: 百分比类型字段填写优化

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5580]
### Summary 摘要

如果填写50%，目前需要输入0.5，期望应该是输入50

### Why should this be worked on? 此需求的应用场景？

如果填写50%，目前需要输入0.5，期望应该是输入50

**Comment by hotlong** [comment]
1. amis 数值型字段支持加入后缀 %
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-number#%E5%89%8D%E5%90%8E%E7%BC%80-%E5%8D%83%E5%88%86%E5%88%86%E9%9A%94

2. 使用 pipeIn 和 pipeOut 函数，对值进行处理，输入时 *100，保存时 /100
