### ISSUE TITLE
[Feature]: 支持禁用列表视图

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5582]
### Summary 摘要

多个软件包中重写了A对象，并在软件包添加了对象的列表视图。添加软件包后，实际上不需要使用此软件包扩展出的A对象的列表视图。

### Why should this be worked on? 此需求的应用场景？

多个软件包中重写了A对象，并在软件包添加了对象的列表视图。添加软件包后，实际上不需要使用此软件包扩展出的A对象的列表视图。

**Comment by baozhoutao** [comment]
添加启用属性
