### ISSUE TITLE
[Bug]: 自定义简档的审批中心无法显示左侧待办、已办列表，无法显示 “审批单” 标签页

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5585]
### Description

![065ac6d91caaaeb3656e1411921c810](https://github.com/steedos/steedos-platform/assets/25192306/1cd57584-0cd1-406f-8597-400144a305b3)

### Steps To Reproduce 重现步骤

1. 设置->简档&权限集
2. 点击customer简档->查看
3. 点击复制按钮，复制得到 mer_mgr 简档
4. 导出mer_mgr简档为 yml配置文件
5. 将mer_mgr简档的mer_mgr.profile.yml 部署到生产环境
6. 在生产环境上配置 “mer_mgr”简档添加  审批任务对象的 查看所有 权限
7. 新建一个  mer_mgr 简档的人员 abc
8. 以abc人员账号登录生产系统
9. 点击 审批中心 ， 显示效果如描述图，功能显示不全

### Version 版本

self hosted 2.5.13

**Comment by sunhaolin** [comment]
配置 审批(instance_tasks)和审批单(instances) 对象权限即可
