### ISSUE TITLE
[Bug]: 钉钉对接安卓无法显示

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5587]
### Description

底座版本2.5
问题描述： 推送正常，电脑，苹果正常。安卓端打开微应用后白屏。
苹果端手机测试版本（均正常）：
IOS10.1，iOS16.1

安卓端手机版本（白屏）：12，13
华为手机版本（白屏）：鸿蒙3.0，鸿蒙4.0
### Steps To Reproduce 重现步骤

1.设置钉钉相关信息：
<img width="951" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/cb2075f0-38df-4e74-b2ce-e7a6ba91ac86">
钉钉开放平台提示系统繁忙。
后端报错如图：
![25481697176370_ pic](https://github.com/steedos/steedos-platform/assets/34770813/927deb0b-33ea-4e8b-90d0-b5a6208c482c)
后续找到原因：
<img width="1152" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/3eeddd07-32b0-42b3-9d99-22ae68ec229f">
exports.spaceGet方法中，红色框框部分返回的是list而不是对象。在.env里配置STEEDOS_CLOUD_SPACE_ID使其不走该方法可以解决。

2.电脑端和苹果端正常跳转。安卓端点击白屏，报以下错误：
<img width="1350" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/407ca04b-871e-4c9d-b2de-837a4562445a">

其中，steedosSchema is not defined错误，打开qywx.router.js修改396和399行可以解决。修改完如下：
<img width="778" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/d36da2ce-7d58-40e5-8b13-8d8593cf4850">

但是还是一直报
rror: Invalid Session
steedos_1       |     at AccountsServer.<anonymous> (/app/node_modules/@steedos/accounts/src/server/accounts-server.ts:589:13)
steedos_1       |     at step (/app/node_modules/tslib/tslib.js:195:27)
steedos_1       |     at Object.next (/app/node_modules/tslib/tslib.js:176:57)
steedos_1       |     at fulfilled (/app/node_modules/tslib/tslib.js:166:62)
steedos_1       |     at /app/node_modules/meteor-promise/fiber_pool.js:43:39
安卓打开白屏

### Version 版本

2.5

**Comment by chenzhipei** [comment]
华炎魔方版本：2.5.17-beta.7
本地测试安卓13和鸿蒙2.0
1、可以正常单点登录钉钉华炎魔方服务
2、点击待办通知，也可以正常单点登录到审批单
