### ISSUE TITLE
[Bug]: lookup类型字段设置过滤条件后，填写表单时创建不符合lookup类型字段的值时，显示记录id

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5596]
### Description

见关联任务：
- https://github.com/steedos/steedos-ee/issues/423

### Steps To Reproduce 重现步骤

1、新建对象记录；
2、新建lookup字段记录；

### Version 版本

2.5.5-beta.15

**Comment by yinlianghui** [comment]
这个任务已在 [[Feature]: lookup字段配置了filters或filtersFunction时，强制把弹出窗口的新建按钮去掉 #499](https://github.com/steedos/steedos-widgets/issues/499) 中处理了，方案是直接不显示新建按钮。
