### ISSUE TITLE
[Bug]: 列表视图新建，勾选共享视图到工作区，点第一次没反应，需点两次。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5599]
### Description

关联任务：
- https://github.com/steedos/steedos-ee/issues/439

![image](https://github.com/steedos/steedos-platform/assets/50353452/0201f117-e416-45c4-941b-88b143170318)

### Steps To Reproduce 重现步骤

见关联任务

### Version 版本

2.5.5-beta.15

**Comment by Flyingliao** [comment]
排查结果：并不只是复选框需要点两次才能选中，先在其它地方点击一下，再回去点击复选框就能一次选中。
