### ISSUE TITLE
[Bug]: 【审批中心】相关文件页面显示样式错误，且无法查看台账信息

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5600]
### Description

![image](https://github.com/steedos/steedos-platform/assets/50353452/23718b01-39a4-428f-8216-d3e7dbb0e671)

关联任务：
- https://github.com/steedos/steedos-ee/issues/440

### Steps To Reproduce 重现步骤

见关联任务

### Version 版本

2.55-beta.15

**Comment by baozhoutao** [comment]
样式问题和huayan pod 有关, 可以使用本地或者gitpod确认
