### ISSUE TITLE
[Bug]: 审批王，iPad 效果显示异常，文件标题太窄

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5604]
### Description

<img width="1135" alt="企业微信截图_a5a66209-753b-421e-8692-537ce8d2c3ac" src="https://github.com/steedos/steedos-platform/assets/50353452/46072548-fafd-4673-a2b6-f281d626a2ab">

### Steps To Reproduce 重现步骤

1. 运行 steedos-ee
2. 进入审批中心

### Version 版本

2.5.15

**Comment by tujiajun** [comment]
文件标题未配置宽度且为换行时，不会自动撑开，需要配置一个宽度，目前配置为200px,效果如下图
![image](https://github.com/steedos/steedos-platform/assets/127007861/0e20ca58-9b4d-450b-918c-90d221bde16e)
