### ISSUE TITLE
[Bug]: 审批王会签多选节点windows电脑，在选人时，点击勾选方框，第一次发送时提交失败

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5612]
### Description

关联任务：
- https://github.com/steedos/steedos-ee/issues/461

### Steps To Reproduce 重现步骤

<img width="1023" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/50e7c328-b3d1-4a99-b045-f7b8447ec35a">

### Version 版本

 2.5.17-beta.7

**Comment by baozhoutao** [comment]
win 10  + edge 118 未重现
win 10 + chrome 116 未重现. 

请提供浏览器信息.

**Comment by chenzhipei** [comment]
win 10 + chrome 118

**Comment by baozhoutao** [comment]
此问题与选人组件无关.
问题原因: 选完人后, 输入意见再点击发送就能重现.
