### ISSUE TITLE
[Bug]: 选择部门时会多显示一列“隐藏”列，建议去掉

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5613]
### Description

![image](https://github.com/steedos/steedos-platform/assets/26241897/5ed6fdc4-dc04-4ba0-85ea-c5ce2e947b5c)

### Steps To Reproduce 重现步骤

见图

### Version 版本

2.5.17-beta.7

**Comment by yinlianghui** [comment]
通过给部门对象的增加一个API名为lookup的的列表视图，在那个视图是维护lookup弹出窗口时显示哪些列，不要配置“隐藏”列即可。

**Comment by yinlianghui** [comment]
> 通过给部门对象的增加一个API名为lookup的的列表视图，在那个视图是维护lookup弹出窗口时显示哪些列，不要配置“隐藏”列即可。

就按这个方案处理，另外给部门对象增加一个叫“有效部门”的列表视图，只显示不隐藏的部门记录，同时把隐藏列去掉。
