### ISSUE TITLE
[Bug]: space_users选项卡无法配置给非管理员用户使用，点击自定义按钮显示找不到此记录

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#5616]
### Description

对于部分系统定义的对象和选项卡，无法通过权限配置开放给非管理员用户使用

### Steps To Reproduce 重现步骤

1.管理员进入设置界面
2.进入用户界面/选项卡
3.选项卡权限位置点击用户，进入详情页面
4.点击自定义，报错：已在权限集/简档user下配置过选项卡admin_space_users的权限，无需重复配置。
![748c9bb7d447928b584b0c8d0dd98ba](https://github.com/steedos/steedos-platform/assets/62589030/93ea9747-c8de-4ab4-aef4-54c5d50be669)
经测试在2.5.15中点击自定义按钮显示找不到此记录

### Version 版本

2.3.5

**Comment by baozhoutao** [comment]
v2.5.18无法重现此问题
