### ISSUE TITLE
英文版菜单换行错误，应该去掉 word-break css

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5621]
- 目前字体是 15px, 可以调整为 14px
- 去掉 `word-break`
<img width="750" alt="企业微信截图_48c26876-c6e6-4bd0-b06d-49aa814db0ea" src="https://github.com/steedos/steedos-platform/assets/50353452/89a9ea1f-7e48-4f1d-a568-087baf239263">

**Comment by yinlianghui** [comment]
https://github.com/steedos/steedos-widgets/commit/1f3333ef52b39bb0cf4224ac5a4336df6d13862b
