### ISSUE TITLE
[Bug]: 分栏视图下，软件包列表软件包图标不显示自定义的图标，考虑禁用分栏视图

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5624]
### Description

当前显示的都是默认图标
![image](https://github.com/steedos/steedos-platform/assets/26241897/eef95981-61a9-4d84-a073-9ec26e76199f)
![image](https://github.com/steedos/steedos-platform/assets/26241897/25e0901b-240e-40d7-94be-0e134da7ca98)

### Steps To Reproduce 重现步骤

设置-软件包列表

### Version 版本

 2.5.17-beta.7

**Comment by hotlong** [comment]
不好处理的话，可以禁用分栏模式
