### ISSUE TITLE
[Bug]:  对象上的附件、图片类型字段上传附件后, cfs.files.filerecord、cfs.images.filerecord表中的metadata数据异常.

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#5627]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194462/ca76909b-dbe5-45cf-b631-3d8ab8aa6e1e)
![image](https://github.com/steedos/steedos-platform/assets/6194462/fbe00662-580a-4391-979e-7cc8f67245fa)

### Steps To Reproduce 重现步骤

新建对象,添加图片、附件类型字段, 预览对象, 新建记录上传附件
图片.

### Version 版本

2.5

**Comment by Flyingliao** [comment]
2.2版本中保存的值：
<img width="1122" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/cf7736ba-bf8d-4cb1-9714-ad22a2e1c8a7">
