### ISSUE TITLE
[Bug]: 火狐浏览器登陆后无法进入主页

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#5628]
### Description

火狐浏览器登录以后，进入主页时报错（谷歌浏览器正常）。
![25e8b8bd576fa577b51a8ca2575803b](https://github.com/steedos/steedos-platform/assets/62589030/36ce33ab-a982-4cf1-b953-5e649c3c458c)

### Steps To Reproduce 重现步骤

如上，火狐浏览器版本：119.0 

### Version 版本

2.5.16

**Comment by hotlong** [comment]
火狐浏览器目前还没有开始启动测试，建议先使用最新版本的chrome。
