### ISSUE TITLE
[Bug]: 无法新增人员，报错禁止修改

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#5629]
### Description

进入系统尝试添加人员，在人员应用页面添加人员，提交后显示禁止修改。
![image](https://github.com/steedos/steedos-platform/assets/62589030/48961fa9-5150-4801-99e2-1037e92954ac)
注释代码后恢复正常，请评估代码作用。
![image](https://github.com/steedos/steedos-platform/assets/62589030/434dbf2b-c963-44c2-b39a-b70e07ad41b4)

### Steps To Reproduce 重现步骤

如上

### Version 版本

2.5.16

**Comment by sunhaolin** [comment]
请提供终端输出的完整的报错信息

**Comment by CarlWhite2020** [comment]
![image](https://github.com/steedos/steedos-platform/assets/62589030/61848782-0b0e-4f8b-b4a9-1bf3c14e47b0)
完整报错信息如图所示。@sunhaolin
