### ISSUE TITLE
[Bug]: 人员(users)作为相关表时，数据导入时无法关联数据

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#5630]
### Description

当某个对象的某个字段为相关表，且相关表对象为users时，通过数据导入批量导入数据时，无法导入该字段。
查看源码发现数据导入时，会通过space字段查找对应的数据，而新建用户时，只会在space_users表中保存space字段，users表不会保存space字段，导致导入users表数据时，查询记录为空，进而导入数据时，users相关字段导不进数据。
![image](https://github.com/steedos/steedos-platform/assets/62589030/8d1826bd-93e2-4d7e-93f6-2ec9cd640c91)
本人的临时解决措施是在新建人员后，通过触发器给users对象添加space字段信息。
![image](https://github.com/steedos/steedos-platform/assets/62589030/2b133392-fbac-485a-a2ce-b985e54d1eed)

### Steps To Reproduce 重现步骤

如上，建议整合。原本写在beforeInsert里面，但是明明spaces_invited数组有值，确无法获取到。不知道什么原因，改在after以后就正常了

### Version 版本

2.5.16

**Comment by sunhaolin** [comment]
未能还原此问题，请提供导入时终端输出的报错信息及数据导入的配置

**Comment by CarlWhite2020** [comment]
经测试，本人亦未能复现问题，关闭此issue。
