### ISSUE TITLE
[Bug]: 主表/子表字段权限控制问题

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#5632]
### Description

用户对主表只有读取权限时，子表新建记录，选择主表记录后保存时报错：
**缺少当前子对象workorder__c的主对象”asset__c“的“编辑权限”，不能选择主表记录： “GAE-BDC”。 [400]**
该错误显示在设置字段时需要勾选-当用户对主表记录有读取权限时对子表记录可以增删改-选项
但是一旦勾选，用户在选择主表记录时，不止有读取权限，还有了编辑权限。不适用与用户只能选择记录，不给编辑的场景。
![image](https://github.com/steedos/steedos-platform/assets/62589030/a56453fd-8ec0-41af-a1ac-99e494178753)

### Steps To Reproduce 重现步骤

1.对象workorder__c是asset__c的子表，用户对workorder__c有新建、读取、编辑权限，对asset__c有读取权限。
2.用户新建workorder__c记录，选择asset__c的相关记录后保存时报错，报错信息如上

### Version 版本

2.5.16

**Comment by sunhaolin** [comment]
默认子表增删改时需要对主表也有增删改权限，这个开关的的意思是对子表增删改时只需要对主表有只读权限即可，并不表示对主表有编辑权限。
