### ISSUE TITLE
[Feature]: 列表视图表单改为使用ObjectForm显示表单内容

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5638]
### Summary 摘要

![image](https://github.com/steedos/steedos-platform/assets/6219465/54c34a5f-cdc0-4180-bc7c-0e67e919e36a)

### Why should this be worked on? 此需求的应用场景？

新建编辑列表视图时国际化翻译有问题

**Comment by Flyingliao** [comment]
- [ ] 使用表单组件替换自定义表单
 - [ ] 审查各个字段功能是否正常， 太多了，具体调试时自主详细检查
 - [ ] pc和手机端各自审查下，详细点。
