### ISSUE TITLE
[Task]: 对象设置页面的设计字段布局功能中各种bug清单

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5643]

**Comment by endlesstravel** [comment]
bug： 分组添加后不显示
![test](https://github.com/steedos/steedos-platform/assets/10757838/3916b158-a35e-47ae-9c8c-0eea2a547a32)

**Comment by endlesstravel** [comment]
bug：触发分组显示bug后，新建字段不展示，如下gif
![test](https://github.com/steedos/steedos-platform/assets/10757838/6912dcc1-a34d-4ca7-9ff5-84fdd545160f)

**Comment by endlesstravel** [comment]
样式bug： 字段名称过长，导致控件溢出
![test](https://github.com/steedos/steedos-platform/assets/10757838/f0496a05-e129-4df2-911a-1d4205b56406)

**Comment by endlesstravel** [comment]
bug：分组排序无法保存
![test](https://github.com/steedos/steedos-platform/assets/10757838/b2e2b5bd-c6e4-4390-b863-c650a1f0f6b0)

**Comment by endlesstravel** [comment]
动画预览显示 bug：拖拽的预览位置和实际落下位置不符合，可以观察到如果 preview 的位置在左侧，那么将会一直在左侧

![test](https://github.com/steedos/steedos-platform/assets/10757838/c69e0b79-36f0-4803-aaac-f36d3ef11e2e)

**Comment by endlesstravel** [comment]
bug：字段排序保存 **有时** 不生效
宽字段，触发概率更高
![test](https://github.com/steedos/steedos-platform/assets/10757838/8efa6ecf-08c1-426c-bfdf-2ebee96f798a)
普通字段，触发概率低
![test](https://github.com/steedos/steedos-platform/assets/10757838/2bfdbdb4-63aa-48d0-b805-b319d13607ae)

**Comment by endlesstravel** [comment]
bug：分组间移动bug，下面3个问题可能是相关联的

① 字段无法移动到新建的空白分组中

![test](https://github.com/steedos/steedos-platform/assets/10757838/927497c4-20ca-4f65-a7ef-35269cc83e72)

② 移动2个字段：出现1个字段移动过去，1个字段没有移动过去
![test](https://github.com/steedos/steedos-platform/assets/10757838/c8d0b983-2d84-401c-8d17-4de0caf2e8e9)


③ 移动3个字段：出现2个字段移动过去，1个字段没有移动过去
![test](https://github.com/steedos/steedos-platform/assets/10757838/0c02da95-3c29-4063-831f-dd43bcd55e20)

**Comment by tujiajun** [comment]
>bug： 分组添加后不显示，保存刷新后才显示

该bug未重现，测试正常

Uploading 屏幕录制2023-10-31 12.15.16.mov…

**Comment by tujiajun** [comment]
>bug：触发分组显示bug后，新建字段不展示，如下gif

未重现，测试正常
![291891492291361822023-10-31-12-26-20](https://github.com/steedos/steedos-platform/assets/127007861/079228f1-8a24-466c-a414-fedcae51240d)

**Comment by tujiajun** [comment]
>bug：分组排序无法保存

未重现，测试正常

**Comment by tujiajun** [comment]
>动画预览显示 bug：拖拽的预览位置和实际落下位置不符合，可以观察到如果 preview 的位置在左侧，那么将会一直在左侧

组件问题，若不影响使用，考虑后期优化

**Comment by tujiajun** [comment]
>bug：字段排序保存 有时 不生效

未重现，测试正常

**Comment by tujiajun** [comment]
>bug：分组间移动bug，下面3个问题可能是相关联的

未重现，测试正常

**Comment by tujiajun** [comment]
1、拖拽字段后，新增字段失效
2、拖拽后，新增分组后会使之前的拖拽失效
