### ISSUE TITLE
[Bug]: steedos-ee项目中对系统微页面进行自定义操作，设计器中相关代码都丢失了。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#5648]
### Description

<img width="791" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/c4444920-e774-4d5b-a5e0-e81b43509e5c">

### Steps To Reproduce 重现步骤

1、在系统设置界面下的用户界面菜单栏中 找一个系统微页面。
2、点击右上角的“自定义”按钮。
3、点击右上角“设计器”按钮。
4、进入设计器界面，会看到空白，相关内容代码都没了。

### Version 版本

2.5.17-beta.9

**Comment by baozhoutao** [comment]
此问题是由于ee gitpod的 root url 异常导致
![image](https://github.com/steedos/steedos-platform/assets/6194462/f0f87671-d563-4359-99f8-3b58839cd6fc)

**Comment by baozhoutao** [comment]
ee gitpod 的 .env.local 缺失配置.
![image](https://github.com/steedos/steedos-platform/assets/6194462/e10ba71a-f679-428c-bbdd-228e8e5e433c)
