### ISSUE TITLE
jsreport报表类型，确认下代码定义的报表加载到内存后显示不出来

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#565]
关联任务：报表列表中显示代码中定义的系统报表 #515

[db.report.txt](https://github.com/steedos/steedos-platform/files/4906573/db.report.txt)

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/566

**Comment by baozhoutao** [comment]
此问题不是代码中定义的报表， 是db中的数据
