### ISSUE TITLE
[Bug]: objectql 使用directInsert 调用传递usersession参数后，报没有find 权限，而使用insert 就正常

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#5652]
### Description

![cb1644ff578a086f5059deb96b6030f](https://github.com/steedos/steedos-platform/assets/25192306/d02a78d8-382b-47cc-87be-213a7d48252a)
![4772c22c44d7aa757ce94c35eb8902b](https://github.com/steedos/steedos-platform/assets/25192306/c721ae8f-be91-432b-b814-f24ab29a1eb4)

### Steps To Reproduce 重现步骤

![cb1644ff578a086f5059deb96b6030f](https://github.com/steedos/steedos-platform/assets/25192306/d02a78d8-382b-47cc-87be-213a7d48252a)
![4772c22c44d7aa757ce94c35eb8902b](https://github.com/steedos/steedos-platform/assets/25192306/c721ae8f-be91-432b-b814-f24ab29a1eb4)

### Version 版本

2.2~ 2.5

**Comment by hotlong** [comment]
我理解的 directInsert 应该不会计算 userSession吧？
