### ISSUE TITLE
[Bug]: 自定义应用程序后，应用程序中tab未按照设置显示

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5655]
### Description

自定义应用程序后，未按照设置的tab显示，而是把自定义前和自定义后的tab都显示了。
<img width="1184" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/1baab3f6-5e59-4f8c-9e26-be1076dbda44">
<img width="1160" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/53f5026c-364d-4b7e-8df3-41d7eff466af">
<img width="1439" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/0bd0ddde-e720-400d-8cfe-054d90e5821a">

### Steps To Reproduce 重现步骤

应用程序-> oa -> 自定义 -> 设置选项卡。

### Version 版本

2.5.17

**Comment by hotlong** [comment]
是因为以前可以在其他中选择对象，最新版去掉了对应的字段，但是代码还在加载。

**Comment by yinlianghui** [comment]
已还原 464b74ef506caa9f0c3155abffc4806e42adbdad
