### ISSUE TITLE
[Bug]: 内网运行打不开，并且我看有issue说微页面是不开源的，我想问下内网能用的东西到底有哪些，以及怎么用

### ISSUE THREAD

**Issue by hengyanqwe** [steedos/steedos-platform#5657]
### Description

内网运行打不开，并且我看有issue说微页面是不开源的，我想问下内网能用的东西到底有哪些，以及怎么用

### Steps To Reproduce 重现步骤

内网运行打不开，并且我看有issue说微页面是不开源的，我想问下内网能用的东西到底有哪些，以及怎么用

### Version 版本

2.4.3

**Comment by hotlong** [comment]
华炎魔方微页面体系依赖 CDN，可以使用我们提供的cdn服务，也可以自己部署 https://github.com/steedos/steedos-unpkg
