### ISSUE TITLE
[Bug]: 从台账发起审批，审批单中的主子表字段值没有带过去

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5660]
### Description

项目中引用的2.5.17版本没有这个问题，platform最新代码有这个问题
![image](https://github.com/steedos/steedos-platform/assets/6219465/c602e4e8-96ff-4108-9db1-be846e520381)

### Steps To Reproduce 重现步骤

1. 新建一个主表对象，再新建一个子表对象，子表对象中有一个字段关联到主表记录，假设名称为“主记录”
2. 子表对象配置为“允许配置对象流程”
3. 新建子表记录，子表记录的“主记录”字段填充上某个值，然后在子表记录详细页面点击右上角的“发起审批”按钮
4. 可以看到弹出的申请单页面上“主记录”值为空

### Version 版本

2.5.18

**Comment by Flyingliao** [comment]
2.5.19-beta.1 正常
<img width="868" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/83ea12d4-0ca3-4d32-a648-cf3fcd6d7d5e">
