### ISSUE TITLE
[Bug]: crud的card模式的时候按钮如果配置为disabled，鼠标放上去时不应该显示为蓝色文字

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5663]
### Description

这个是amis card组件的统一样式bug，普通的button及button-group组件没有这个问题，只有card组件下的按钮才有问题。

![image](https://github.com/steedos/steedos-platform/assets/6219465/6169f10a-c15c-4745-ad0f-0f03e6b886bc)

应该显示为全灰，可以参考amis官网button的disabled设置为true的效果：
![image](https://github.com/steedos/steedos-platform/assets/6219465/e1a9726a-2d77-4934-b5c3-36581ed2c4e6)
最好同时加上`cursor: not-allowed;`样式。

### Steps To Reproduce 重现步骤

软件包列表启用/停用按钮，如果是禁用状态，鼠标放上去。

### Version 版本

2.5.x

**Comment by yinlianghui** [comment]
因为是修正amis统一样式，所以请把代码写到此文件中：https://github.com/steedos/steedos-widgets/blob/1.3/packages/@steedos-widgets/amis-object/src/styles/amis.css

**Comment by Flyingliao** [comment]
已经给amis提了issue，建议让他们改全局的样式： https://github.com/baidu/amis/issues/8643
