### ISSUE TITLE
[Bug]: 人员对象列表按钮可视化函数bug

### ISSUE THREAD

**Issue by CarlWhite2020** [steedos/steedos-platform#5664]
### Description

人员列表按钮可视化函数中，判断用户所在权限集拥有权限（例如编辑），还会进一步判断是否拥有管理员简档和分部管理员权限。导致只配置权限集后，按钮仍然不可见。
![image](https://github.com/steedos/steedos-platform/assets/62589030/d127b921-631c-4501-a352-113ed5f19ffd)

### Steps To Reproduce 重现步骤

如上

### Version 版本

2.3.5-2.5.17

**Comment by sunhaolin** [comment]
平台规则是这样的，这三种情况才允许编辑：
1、用户自己（个人资料页）
2、系统管理员
3、分部管理员
