### ISSUE TITLE
[Feature]: 参考sf，对象权限设置时应该在前端界面支持联动，比如取消勾选编辑的时候应该也取消勾选修改全部

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5666]
### Summary 摘要

![image](https://github.com/steedos/steedos-platform/assets/6219465/cd57eed7-66e2-419a-9ff8-868f5eadac7a)

### Why should this be worked on? 此需求的应用场景？

- 社区群有用户对各种权限勾选框的联动不理解
- 我们的对象权限设置界面没有相关联动效果，但是保存后会对关联属性自动在后台计算联动值
- 比如勾选了修改本分部，会把允许编辑勾选框在后台保存接口中重新设置为勾选，用户会以为是bug，认为去不掉允许编辑勾选框。
![image](https://github.com/steedos/steedos-platform/assets/6219465/37761eae-0443-4ddd-a20f-99ccbdd26782)

**Comment by tujiajun** [comment]
# 前台权限联动规则
## 允许查看
- **允许查看**为false时，**允许创建、允许编辑、允许删除、查看所有记录、修改所有记录、查看本分部、修改本分部**设为false

## 允许创建
- **允许创建**为true时，**允许查看**设为true

## 允许编辑
- **允许编辑**为true时，**允许查看**设为true
- **允许编辑**为false时，**修改所有记录、修改本分部、允许删除**设为false

## 允许删除
- **允许删除**为true时，**允许编辑、允许查看**设为true

## 查看所有记录
- **查看所有记录**为true时，**允许查看**设为true
- **查看所有记录**为false时，**修改所有记录**设为false

## 修改所有记录
- **修改所有记录**为true时，**允许查看、允许编辑、允许删除、查看所有记录**设为true

## 查看本分部
- **查看本分部**为true时，**允许查看**设为true
- **查看本分部**为false时，**修改本分部、查看所有记录、修改所有记录**设为false

## 修改本分部
- **修改本分部**为true时，**允许查看、允许编辑、允许删除、查看本分部**设为true
- **修改本分部**为false时，**修改所有记录**设为false

## 允许查看附件
- **允许查看附件**为false时，**修改所有附件、查看所有附件、允许创建附件、允许删除附件、允许修改附件**设为false

## 允许创建附件
- **允许创建附件**为true时，**允许查看附件**设为true

## 允许修改附件
- **允许修改附件**为true时，**允许查看附件**设为true
- **允许修改附件**为false时，**修改所有附件、允许删除附件**设为false

## 允许删除附件
- **允许删除附件**为true时，**允许查看附件、允许修改附件**设为true

## 查看所有附件
- **查看所有附件**为true时，**允许查看附件**设为true
- **查看所有附件**为false时，**修改所有附件**设为false

## 修改所有附件
- **修改所有附件**为true时，**允许查看附件、允许删除附件、允许修改附件、查看所有附件**设为true
