### ISSUE TITLE
[Bug]: 工作流规则中只有显示出来的工作流通知勾选上会有小铃铛通知，搜索出来的工作流通知勾选上没有小铃铛通知

### ISSUE THREAD

**Issue by yangwei-o** [steedos/steedos-platform#5668]
### Description

-工作流规则中只有显示出来的工作流通知勾选上会有小铃铛通知，
-搜索出来的工作流通知勾选上没有小铃铛通知，
-更新到2.5.18-beta.2还是不行。

### Steps To Reproduce 重现步骤
1.工作流规则中搜索添加工作流通知
2.没有小铃铛通知
3.工作流规则中直接添加工作流通知
4.有小铃铛通知
<img width="1059" alt="image" src="https://github.com/steedos/steedos-platform/assets/143991894/fc5cd247-9382-4649-84e4-9a5501eedc55">

### Version 版本

2.5.18-beta.2

**Comment by yinlianghui** [comment]
工作流通知上的人员字段配置了optionsFunction，有可能跟这个有关系：
![image](https://github.com/steedos/steedos-platform/assets/6219465/ddeb3add-ad76-4f70-bbea-a80a99fd7af2)
