### ISSUE TITLE
[Bug]: 批量编辑未判断行权限

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5669]
### Description

前台未判断行权限不影响功能使用，只是在修改时不会提醒
若需要判断行记录权限，考虑在点击修改时，将所有选中行批量判断，需要一个可批量判断行权限的接口，原接口一次只能判断一条

### Steps To Reproduce 重现步骤

1.普通用户登录
2.普通用户批量修改数据

### Version 版本

2.5

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/f4fd2146-b40f-45f2-91bf-77e8691ce571)
使用graphql的find查询, 属性为 `_permissions.allowEdit`
