### ISSUE TITLE
[Bug]: 流程设计器没有“表单”tab页了

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5671]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/d389d8a5-2be6-48c2-b831-9086925af5e0">

### Steps To Reproduce 重现步骤

进入流程设计器
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/c7d0c520-d2c5-48c8-aaac-24219665dc25">

### Version 版本

 2.5.18-beta.2

**Comment by hotlong** [comment]
未能重现，应该是浏览器缓存
