### ISSUE TITLE
[Bug]:流程导出报错，如果有auto_number({另一字段})默认值的字段

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#5672]
### Description

![Uploading image.png…]()

### Steps To Reproduce 重现步骤

流程里的某字段，默认值类似于 auto_number({交易类型})
也基于 交易类型（下拉框类型字段）的可选项 新建了 流程编号
设置》流程》某流程》流程导出，报错

### Version 版本

 2.5.17-beta.6

**Comment by sunhaolin** [comment]
- 复制流程也报错
