### ISSUE TITLE
[Bug]: 业务应用下绑定的流程分类下没有可发起的流程时，建议不显示审批的“新建”按钮

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5697]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/eb07bc3e-4800-4be7-8ed1-657a3dc011fd">

### Steps To Reproduce 重现步骤

1、流程分类绑定当前应用，并且分类下的流程应用全部都配置“禁止审批王发起流程”；
2、应用中配置审批菜单；
3、进入应用后点击“审批”菜单，点击审批页面右上角“新建”按钮，弹框出来空的页面。

### Version 版本

2.5.18

**Comment by hotlong** [comment]
需要在显示页面时调用接口判断，增加系统压力
