### ISSUE TITLE
[Bug]: 新增用户只写姓名，不写用户名然后编辑用户名报小于6位

### ISSUE THREAD

**Issue by willsonli** [steedos/steedos-platform#5701]
### Description

新增用户只写姓名，不写用户名然后编辑用户名报小于6位
一般系统登录都是用用户名，但是这边又能为空然后去写小于6位又不行这个又一些不合理,用户名是可能小于6 is_username_skip_minrequiredlength 这个参数是在哪里设置的?

### Steps To Reproduce 重现步骤

新创建用户然后编辑

### Version 版本

2.5.16

**Comment by hotlong** [comment]
用户名相关的规则校验支持用环境变量配置？

**Comment by baozhoutao** [comment]
> 用户名相关的规则校验支持用环境变量配置？

新增环境变量:
```
STEEDOS_ACCOUNT_USERNAME_MIN_LENGTH=
STEEDOS_ACCOUNT_NAME_VALIDATION=
```

**Comment by hotlong** [comment]
作废 is_username_skip_minrequiredlength，改为以下配置

# 用户名最小长度，默认为6
STEEDOS_ACCOUNT_USERNAME_MIN_LENGTH=
# 姓名验证规则
STEEDOS_ACCOUNT_NAME_VALIDATION=
