### ISSUE TITLE
[Bug]: markdown类型字段显示有问题

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5702]
### Description

<img width="622" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/c24592c1-f504-47c0-8ec2-5feeb53a8f0e">
<img width="467" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/ac7869da-20b3-4d9a-9768-a0757cb87499">
<img width="703" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/9a29e64c-c34a-480f-b59d-50f56ecd8552">

### Steps To Reproduce 重现步骤

见描述

### Version 版本

2.5.18-beta.2

**Comment by hotlong** [comment]
这个语法不是 markdown 标准语法，只有 github 支持
