### ISSUE TITLE
[Bug]: 列表页操作列，中英文都去掉标题上的文字，显示空白即可

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5703]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/cf416e6d-0415-4d64-9e8e-c7b44dae8ef7">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.5.18

**Comment by Flyingliao** [comment]
经讨论不去掉标题文字， 让其自适应宽度即可。

**Comment by hotlong** [comment]
任务的要求是去掉标题，不是自适应宽度。设计变更请和我讨论！
