### ISSUE TITLE
[Bug]: 项目启动后出现白屏

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5704]
### Description

项目启动后，控制台和服务端均未出现报错，切换数据库可以解决这个问题，但是重启后还是会出现这个情况。
![image](https://github.com/steedos/steedos-platform/assets/126655403/bf55450a-2beb-4de0-80e0-770cb2cf8cb8)

### Steps To Reproduce 重现步骤

项目启动后，控制台和服务端均未出现报错，切换数据库可以解决这个问题，但是重启后还是会出现这个情况。

### Version 版本

2.5.18

**Comment by sujiahao66** [comment]
移除steedos-app下的analytics.baidu.client.js文件可以解决。

**Comment by baozhoutao** [comment]
项目依赖项配置异常导致, 已在项目下处理.
