### ISSUE TITLE
[Bug]: 批准过程发起报错"n is not defined"

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5705]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/bf7ccac8-5934-45b9-9db5-18b2b2465c82">

### Steps To Reproduce 重现步骤

1、新建一个对象最简单的批准过程，不用绑定通知或自动更新，启用即可。
2、创建记录并“提请审批”。

### Version 版本

2.5.18

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/5698
