### ISSUE TITLE
[Bug]: 审批王附件字段上传图片后，待审核中显示正常，已审核、监控箱、进行中、已完成中显示异常

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5712]
### Description

审批王附件字段上传图片后，待审核列表中可以正常显示
<img width="1223" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/b59468a4-a500-4046-b909-877ab169d1bf">
<img width="1234" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/f4cac995-e549-49f1-94fe-3946aaa3afc4">
已审核、进行中、已完成中也是同样的问题，显示异常

### Steps To Reproduce 重现步骤

1、新建流程、流程中包含附件字段。
2、上传图片后发起审批，查看监控箱、已完成等列表即可重现

### Version 版本

2.5.18

**Comment by hotlong** [comment]
照片左侧的空白是否有点多？感觉和上面的文字对齐会比较好。
还有要测试一下手机版的显示效果。

**Comment by sujiahao66** [comment]
左图是待审核，右图是监控箱
<img width="213" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/9e4ceca0-a264-4c3d-b1c9-eabfdb592cb7">
<img width="205" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/8fc2bba5-0de9-4cd6-beab-3b5fd22494be">

**Comment by hotlong** [comment]
手机端图片也靠左对齐吧

**Comment by baozhoutao** [comment]
单选
