### ISSUE TITLE
[Bug]: 对象流程映射中新增字段时响应速度很慢、响应后选中的字段无法显示

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5713]
### Description

对象流程映射中新增字段时，选择对象字段时响应速度很慢，网络请求中没看到耗时很长的请求，但是控制台中有一个耗时40s的输出
目前看到的现象是流程绑定的对象字段越多，相关表字段越多响应的越慢
选中响应后的字段，在对象流程映射中无法显示
<img width="1126" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/62bbd2c4-bb2e-4efd-a154-0d87b150c3b5">
<img width="1431" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/fd71fce2-fe2e-458b-8e19-9044ecebe603">
<img width="1396" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/82f3507e-222d-4fbd-91e5-5c7d8efd9245">

### Steps To Reproduce 重现步骤

1、新建流程并绑定“业务伙伴”或“合同”等字段多的对象
2、编辑对象流程映射，新增字段即可重现。

### Version 版本

2.5.18

**Comment by Flyingliao** [comment]
- [ ] 如果没有关联字段的对象，会直接报错。处理方案：把相关软件包补充完整。
 - [ ] 对象字段打开为空。 原因：最开始是下拉模式，而且接口不支持弹窗模式。 处理方案：给相关字段添加 enable_enhanced_lookup: false 属性。
 - [ ] 响应速度慢。之前已经调整缓存为1分钟，是否提升到2分钟？ 需要讨论。

**Comment by Flyingliao** [comment]
重复： https://github.com/steedos/steedos-platform/issues/5739
