### ISSUE TITLE
[Bug]: 后台新建对象时，出现添加明细行不知道干啥的

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5714]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/d25ca14e-0ed4-4d84-a3cc-91c3416edd77">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.5.18-beta.2

**Comment by yinlianghui** [comment]
请升级到2.5.19-beta.4
