### ISSUE TITLE
[Bug]: 累计汇总日期、日期时间字段显示异常

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5717]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194896/2a43ff53-0d0c-49d8-b30f-27b70c5ddbc4)

### Steps To Reproduce 重现步骤

1. 子表添加日期、日期时间字段
2. 主表添加 累计汇总字段，汇总对象选择子表，汇总类型选择MIN，要聚合的字段选择 日期、日期时间 字段

### Version 版本

2.5.19-beta.4

**Comment by Flyingliao** [comment]
排查到是接口返回中 _display.累计汇总字段  值的异常，已经和孙老师讨论好了：他接手处理。
