### ISSUE TITLE
[Feature]: 流程分类中设置的应用配置项，无法同步成元数据

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5722]
### Summary 摘要

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/9118bc71-d23c-49fa-99ee-ba77d74f46c7">

### Why should this be worked on? 此需求的应用场景？

在做ee公文模块时遇到需要在应用中配置审批后只显示该分类下的审批流程

**Comment by hotlong** [comment]
需要讨论一下如何实现。

**Comment by sunhaolin** [comment]
- [ ] service-objectql 新增 action getPrimarySpaceId 获取私有部署工作区ID(非saas环境)
