### ISSUE TITLE
[Bug]: 新版表单设计器没有办法修改“流程表单”名称

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5723]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/bb38d777-92d7-4cc2-b303-ff4363fed53e">

### Steps To Reproduce 重现步骤

见描述

### Version 版本

2.5.19-beta.4

**Comment by hotlong** [comment]
编辑流程时自动更新表单名称？
