### ISSUE TITLE
[Bug]: 手机端台账“发起审批”后未能弹出审批单

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5726]
### Description

https://github.com/steedos/steedos-platform/assets/26241897/62b71539-e132-45fe-8cce-46c861bbb10c

### Steps To Reproduce 重现步骤

见视频，目前只能通过再次点击台账上的“查看审批单“按钮，找到当时的草稿状态的审批单，提交后续审批。

### Version 版本

2.5.19-beta.4

**Comment by hotlong** [comment]
应该是手机端 不支持目前的弹出窗口语法导致的
