### ISSUE TITLE
[Bug]: 对象相关表类型字段配置reference_to_field属性后，审批王lookup字段显示错误

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5727]
### Description

对象相关表类型字段配置reference_to_field属性，发起审批后在审批单中此字段未显示name，而是显示为reference_to_field指向的字段
<img width="493" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/3710cd2e-a552-47ab-99de-e50a3e880a84">
![image](https://github.com/steedos/steedos-platform/assets/126655403/34b30ee1-1466-4859-b2fd-729f3dfa06c3)
![image](https://github.com/steedos/steedos-platform/assets/126655403/672ba193-7809-4173-b874-43ed91687f56)

### Steps To Reproduce 重现步骤

对象新建lookup类型字段并配置reference_to_field属性，发起审批，查看审批单即可重现。

### Version 版本

2.5.19-beta.2

**Comment by baozhoutao** [comment]
只读模式

**Comment by baozhoutao** [comment]
form 可以编辑, lookup字段只读时, 可以重现.
