### ISSUE TITLE
[Bug]: amis表单设计器“相关表”组件配置完成后，设计器页面/预览页面看不到相关表数据

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5735]
### Description

<img width="1614" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/29645541-24e2-47af-9586-c8c4d623d01c">
<img width="1460" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/27ed95be-ba45-402b-a96b-5ae0e19326d3">

### Steps To Reproduce 重现步骤

远程开发环境

<img width="836" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/d9e7de79-2f6a-4c73-a7cf-4dc3a31382ad">

### Version 版本

2.5.19-beta.4

**Comment by Flyingliao** [comment]
- [ ] 显示相关表组件
 - [ ] 显示相关表数据

**Comment by Flyingliao** [comment]
显示相关子表数据的 修改代码：https://github.com/steedos/steedos-widgets/commit/e8bc7a17ecf7b3600a122f4853001702683a8abb

**Comment by Flyingliao** [comment]
相关子表数量显示不出来 新建一个issue处理：https://github.com/steedos/steedos-platform/issues/5768
