### ISSUE TITLE
[Feature]: boolean类型字段默认值支持配置 undefined

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5736]
### Summary 摘要

目前现状：
新建记录时，boolean类型字段会默认被设置为false，即使字段配置为`visible_on: "{{false}}"`，也会被设置默认值false，除非直接配置字段`hidden:true`。

关联issue：
- [Feature]: checkbox 设成必填的时候，允许不点击勾选框校验通过 #5384
- [Bug]: 新建lookup字段时，字段的enable_enhanced_lookup属性值会被默认保存为false，且新建字段的界面上并不能设置此属性 #5730

需要探讨的点：
现状这种规则是否会带来不好的影响，即所有的boolean类型字段的默认值为false而不是undefined是否合理，还是说应该只为必填的boolean字段设置默认值。

### Why should this be worked on? 此需求的应用场景？

boolean类型字段未设置必填时是否需要有默认值false。

**Comment by hotlong** [comment]
```
{
  "type": "page",
  "body": {
    "type": "form",
    "title": "水平模式",
    "mode": "horizontal",
    "horizontal": {
      "left": 2,
      "right": 10,
      "offset": 2
    },
    "debug": true,
    "debugConfig": {
      "enableClipboard": true,
      "displayDataTypes": true
    },
    "body": [
      {
        "type": "input-email",
        "name": "email",
        "label": "邮箱",
        "required": true
      },
      {
        "type": "input-password",
        "name": "password",
        "label": "密码"
      },
      {
        "type": "checkbox",
        "name": "rememberMe",
        "label": "记住登录",
        "visibleOn": "{{false}}"
      }
    ]
  }
}
```

amis 官网执行这个 json 是没问题的， 记住登录字段没有显示，也没有设置表单值

**Comment by yinlianghui** [comment]
待任务 【新建字段时，根据不同的字段类型，切换不同的默认值输入框 #4114】 合并到2.5再处理，拟为boolean类型字段配置默认值时提供三个选项：true/false/undefined，如果用户未配置为true/false的话，必填字段还是会提示必填错误。

**Comment by yinlianghui** [comment]
项目暂时没用到不优先，后续处理前参考下简道云是如何配置默认值的。

**Comment by yinlianghui** [comment]
简道云没有boolean类型的字段可以设置
![image](https://github.com/steedos/steedos-platform/assets/6219465/02086c80-adc9-404b-9b3d-c12d09835e81)

salseforce和 amis设计器中boolean类型字段默认值设置没有提供undefeind值选项。
![image](https://github.com/steedos/steedos-platform/assets/6219465/0a69f048-d774-4f69-aa59-fd4a9c79f65d)

![image](https://github.com/steedos/steedos-platform/assets/6219465/d69d167b-5ddd-42b0-ab80-7e22805687f0)
