### ISSUE TITLE
[Bug]: 对象验证规则同步成源代码。切换新的数据库，验证规则不生效，同时前端也不加载相应规则。

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5738]
### Description

配置对象验证规则之后，（未换库之前）
![image](https://github.com/steedos/steedos-platform/assets/129827462/9c481291-25df-4148-82ee-e842ed48f12a)

这个时候，对象验证规则是生效的。

换新库之后：
![image](https://github.com/steedos/steedos-platform/assets/129827462/56da848f-7a72-461c-8726-0d930893f571)

这个时候，对象验证规则也失效了。但是代码里面有相关对象验证规则中的代码。

### Steps To Reproduce 重现步骤

1、新建对象验证规则
2、同步成源代码
3、切换新的数据库
4、测试：创建或者修改步骤1中的关联的对象。（验证规则失效）

### Version 版本

2.5.19-beta.5

**Comment by hotlong** [comment]
相关 https://github.com/steedos/steedos-platform/issues/5738
