### ISSUE TITLE
[Bug]: 用户前台自定义列表视图后，“过滤设置”中选不到字段

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5744]
### Description

<img width="1700" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/cc652f92-b7f7-4f78-ae4e-5e9862165455">

### Steps To Reproduce 重现步骤

前台用户创建新的列表视图，并添加过滤条件

### Version 版本

2.5.19-beta.5

**Comment by lizhenghotoa** [comment]
后台管理员设置列表视图的过滤条件，也是选择不到字段

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/ca539a54-e5f0-43c8-9981-f3f8f06ee970)

提供下pod信息.

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/4b44ba4b-5df7-4f1b-b9db-ac32ed150f76)
`steedos-enterprise` image 使用的是npm 安装的依赖包, 导致安装的underscore太旧

**Comment by baozhoutao** [comment]
使用此版本的image `steedos-enterprise:2.5.20-beta.6`
