### ISSUE TITLE
[Bug]: 数据导入模版，配置映射关系“导入对象的字段”值选择的不对

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5746]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/af97a272-a8a6-4558-a6fc-80deb7334bcc">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/6fbcaf0a-ffad-495a-9a65-14a41b420006">

### Steps To Reproduce 重现步骤

管理员进入后台-设置-高级-数据导入创建导入模板。
<img width="649" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/70cad039-e6fd-4ab1-84cf-eff9bccf4d24">

### Version 版本

 2.5.19-beta.5

**Comment by baozhoutao** [comment]
前台组件问题
