### ISSUE TITLE
[Bug]: 数据展示列表滑动最底下的滚动条时最右侧按钮组错位

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5754]
### Description

未滑动滚动条之前：
![image](https://github.com/steedos/steedos-platform/assets/129827462/f43ebee8-1952-44d0-8365-a2946faebe45)
滑动滚动条之后：
![image](https://github.com/steedos/steedos-platform/assets/129827462/75b91086-42b0-4149-872e-23696cfcc50f)

### Steps To Reproduce 重现步骤

1、展示的字段过多时，最底下会出现滚动条。
2、滑动滚动条时，最右侧按钮组错位。

### Version 版本

2.5.19

**Comment by Flyingliao** [comment]
这里统一处理了： https://github.com/steedos/steedos-platform/issues/5798
