### ISSUE TITLE
[Bug]: 新建自定义对象相关问题

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5755]
### Description

- [x] owner 字段编辑后不能保存
- [ ] name 字段编辑时应该只能选择文本或自动编号类型: 暂不处理
- [ ] #5779

### Steps To Reproduce 重现步骤

1. 创建自定义对象

### Version 版本

2.5.20

**Comment by baozhoutao** [comment]
owner 字段编辑后不能保存: 放开修改 `如果相关表记录被删除怎么办？`

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/9dea91d2-8eb6-4afd-bf47-b3e24378cf03)
点击预览，如没有记录，列表界面标题丢失: 表格快速编辑功能导致此问题.

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-platform/issues/5778
