### ISSUE TITLE
[Feature]: 设计字段布局：支持快速配置字段属性，包括必填、字段只读、字段显示规则、宽字段

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5756]
### Summary 摘要

- 字段布局右侧增加属性面板
- 选择字段时，右侧属性面板显示字段布局相关的属性，包括字段必填、字段只读、字段隐藏、字段显示规则、宽字段，并可修改保存
- 左侧布局面板，必填字段显示红色星号，只读字段显示为灰色背景

### Why should this be worked on? 此需求的应用场景？

数据建模

**Comment by tujiajun** [comment]
[Feature]: 设计字段布局界面优化 #6189
