### ISSUE TITLE
[Bug]: 单元格编辑可多选的lookup字段时，删除字段值显示错误

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5758]
### Description

通过单元格编辑多选的lookup字段（窗口模式）时，删除多选字段的部分值，编辑后在为提交界面显示错误，提交后正确显示。
但是如果重新编辑此字段，显示错误，需要刷新浏览器后才能正确显示。
<img width="1138" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/7099f454-94fb-47da-83b4-72cdf4822fdb">
![image](https://github.com/steedos/steedos-platform/assets/126655403/8c6a4797-27b0-4146-8596-05b311bbd751)
![image](https://github.com/steedos/steedos-platform/assets/126655403/e66abea6-bf02-4177-ac85-65a385f6f837)
![image](https://github.com/steedos/steedos-platform/assets/126655403/2ba10d5e-c9b2-417e-aa4c-632de4cc3d30)
<img width="1223" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/b48bab22-54fd-454e-81e9-57d195eb5cfc">

### Steps To Reproduce 重现步骤

使用单元格编辑可多选的lookup字段，且该lookup字段引用的对象启用了窗口模式时，可以重现这个问题。重现步骤如上述图片顺序

### Version 版本

2.5.20-beta.4

**Comment by hotlong** [comment]
没看懂重现过程。

**Comment by tujiajun** [comment]
https://github.com/steedos/steedos-widgets/issues/461，
amis2.9存在该问题，3.2已修复
