### ISSUE TITLE
[Feature]: 流程选择组件steedos-select-flow支持作为表单中字段项时配置的submitOnChange

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5759]
### Summary 摘要

目前给表单中的选择流程字段配置submitOnChange属性并没有生效，这是amis form item的标准功能，见：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/formitem#%E5%B1%9E%E6%80%A7%E8%A1%A8

### Why should this be worked on? 此需求的应用场景？

审批王应用中的审批列表需要支持搜索项中流程字段变更时立即触发请求搜索，目前其他字段类型都是好的，只有流程选择字段异常。
![image](https://github.com/steedos/steedos-platform/assets/6219465/ada306bb-78a6-4fcc-8daa-e8f8e31cd253)

上图中已经把流程选择组件usage从renderer改为formitem后问题依然存在。

**Comment by yinlianghui** [comment]
已经测试到普通的input-tree下拉字段不会有这个问题，应该是因为流程选择字段是单独开发的amis组件造成未能支持字段上配置的submitOnChange属性相关功能。
后续可能的方案：
- 流程选择组件调式，让其支持字段上配置的submitOnChange属性相关功能
- 把流程选择字段改为非自定义组件方式，参考目前选人字段，实现字段内直接生成schema，也可以像选人组件一样弹出选择窗口，在弹出窗口中左侧显示流程分类右侧显示流程列表

**Comment by hotlong** [comment]
不能直接换 input-tree 吗？写一个api返回 tree 的内容
