### ISSUE TITLE
[Bug]:数据导入时，选择导入对象字段只能选到数据库中字段 

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5761]
### Description

数据导入时存在一下问题：
1、选择导入对象后、选择字段时只能选到库中的字段。
2、没有根据选择的对象过滤字段。
<img width="1124" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/a5804aac-7d3d-4441-8f4a-4c39a52acfde">
<img width="1438" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/b1746a06-631f-48fa-a224-e22c9eb143a5">

### Steps To Reproduce 重现步骤

新建数据导入时即可重现。

### Version 版本

2.5.20-beta.4

**Comment by Flyingliao** [comment]
重复的issue： https://github.com/steedos/steedos-platform/issues/5746
