### ISSUE TITLE
【考勤】: 考勤菜单图标左上角有个数字“8”显示，无实际意义。

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#5765]
### Description

ee项目：
主菜单界面，考勤菜单图标左上角有个数字“8”显示，实际进入菜单查看无通知、待办等事件。

### Steps To Reproduce 重现步骤

操作步骤：
主菜单界面

![image](https://github.com/steedos/steedos-platform/assets/92509428/794c77cb-f844-4207-9404-481a4bac20b2)
![image](https://github.com/steedos/steedos-platform/assets/92509428/0ce274f1-55df-45b8-b434-e5253fe74e21)

### Version 版本

2.5.20-beta.4

**Comment by hotlong** [comment]
重复
