### ISSUE TITLE
[Bug]: 审批王表单设计器添加字段时报错

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5769]
### Description

审批王使用“添加字段”按钮添加字段时报错，添加以下字段时，会出现报错，目前无法确认具体的报错规则。
<img width="1134" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/59689ed3-9efc-47eb-96e5-beb03795330d">
<img width="1307" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/13234216-9815-4d31-a990-bb823a5c65cc">
<img width="1439" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/4e2681cf-9d3a-482d-9ba5-989d5d735919">

### Steps To Reproduce 重现步骤

目前无法确认具体的报错规则。

### Version 版本

2.5.20-beta.4

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/3bd4e375-3728-4acc-ad04-44ac5c23bdf0)

**Comment by baozhoutao** [comment]
问题原因: 其他接口慢导致了pod认为 5000端口下限返回了404.
![image](https://github.com/steedos/steedos-platform/assets/6194462/5e3befda-c546-4ff9-aad3-c72451023118)

**Comment by sujiahao66** [comment]
此接口响应之前点击保存，一定会出现上述报错情况。接口响应之后点击保存则无上述错误。
gitpod上此接口响应时间约为6s左右，本地环境运行时接口响应时间3s左右
