### ISSUE TITLE
[Bug]: 审批王流程中自动编号字段配置，在生成flow元数据时没有生成

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5777]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/81490f3d-f56d-44b7-8fbc-7db5e67dfafd">

### Steps To Reproduce 重现步骤

导致新环境中自动编号字段提示用户还需要再配置流程编号规则

### Version 版本

 2.5.20-beta.6

**Comment by sunhaolin** [comment]
steedos retrieve:source 命令未同步instance_number_rules
