### ISSUE TITLE
后台设置的界面在编辑界面不生效

### ISSUE THREAD

**Issue by zhuxin2020** [steedos/steedos-platform#578]
![image](https://user-images.githubusercontent.com/68270100/87398017-dcc16300-c5e7-11ea-90e7-28a6c154859a.png)
![image](https://user-images.githubusercontent.com/68270100/87398532-91f41b00-c5e8-11ea-99f4-e66a5e6cfa81.png)

**Comment by baozhoutao** [comment]
测试正常

**Comment by baozhoutao** [comment]
现有的对象字段，如果有排序问题，需要重新编辑一次。
