### ISSUE TITLE
[Feature]: 审批王lookup类型字段支持获取其引用对象的其他字段值

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5780]
### Summary 摘要

目前审批王表单保存后，lookup类型字段存的值是id，无法获取lookup字段引用对象的其他字段值，需要根据其他字段值作为条件节点的条件。
<img width="1295" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/eb14be7a-d7e9-4cd0-8dd5-fba137587681">

### Why should this be worked on? 此需求的应用场景？

需要根据lookup字段引用对象中其他字段的值（比如name，code等）作为条件节点的判断条件

**Comment by hotlong** [comment]
此需求无法实现，只能在表单中配置额外的字段

**Comment by hotlong** [comment]
可行的方案
1. 新增字段
2. 在对象中填写记录，使用 amis 或 公式字段带出相关字段的值
3. 发起审批

**Comment by sujiahao66** [comment]
考虑该lookup字段添加reference_to_field属性，坏处就是后续查询lookup的引用对象时，只能是使用find，不能使用findOne
