### ISSUE TITLE
[Bug]: 新建用户时，用户名不填写内容，保存时报错说用户名已存在

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5782]
### Description

![企业微信截图_86961412-986f-45b8-a848-f7e629066314](https://github.com/steedos/steedos-platform/assets/6219465/a09fc3b1-7e7b-46f1-9b5d-ac48835495a2)

### Steps To Reproduce 重现步骤

在用户列表页面新建用户就能看到

### Version 版本

2.5.20

**Comment by hotlong** [comment]
![wecom-temp-16813-d2b4f8850ee1766b6e8096da4f08b456](https://github.com/steedos/steedos-platform/assets/50353452/e3ec93fa-efe0-4ca2-b89c-090db4e5763e)

**Comment by baozhoutao** [comment]
此问题是由于

> ![wecom-temp-16813-d2b4f8850ee1766b6e8096da4f08b456](https://user-images.githubusercontent.com/50353452/283637241-e3ec93fa-efe0-4ca2-b89c-090db4e5763e.png)

索引问题, 已单独处理

**Comment by baozhoutao** [comment]
> ### Description
> ![企业微信截图_86961412-986f-45b8-a848-f7e629066314](https://user-images.githubusercontent.com/6219465/283636608-a09fc3b1-7e7b-46f1-9b5d-ac48835495a2.png)
> 
> ### Steps To Reproduce 重现步骤
> 在用户列表页面新建用户就能看到
> 
> ### Version 版本
> 2.5.20

此报错与用户名无关, 是邮箱重复了.

**Comment by baozhoutao** [comment]
方案:  邮件校验工作区中是否已存在此用户. 优化消息提醒
