### ISSUE TITLE
[Bug]: 列表编辑字段清空值保存不生效

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5789]
### Description

列表编辑字段清空值保存不生效

### Steps To Reproduce 重现步骤

![Nov-17-2023 12-12-59](https://github.com/steedos/steedos-platform/assets/6194896/324efb2d-a2aa-4177-bcd0-7741e90eefd9)

### Version 版本

2.5.19

**Comment by tujiajun** [comment]
amis3.2环境下出现失效，猜测可能是批量编辑造成的
