### ISSUE TITLE
[Bug]: 应用提醒了审批待办数量，但是进入应用看不到审批待办的入口

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5793]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/7c3aeada-339f-4922-bc03-a0fa0ee73824">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/4e03faaf-f9e7-4c3d-8f94-494a3b996fe1">

### Steps To Reproduce 重现步骤

原因是：
“财务管理”流程分类绑定了这个应用；并且“财务管理”下的“个人还款审批”流程有待办。
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/a562bd24-0cd1-4bee-a097-4f9f442fbca5">

### Version 版本

2.5.20-beta.6

**Comment by hotlong** [comment]
这是审批王目前的规则，如果流程分类绑定到应用，就会在应用下提醒。所以我们对应用需要有规划，提醒的应用下应该有审批的入口

**Comment by hotlong** [comment]
另，财务应用建议删除。对应的流程分类迁移

**Comment by lizheng-steedos** [comment]
EE所有需要审批的应用中已经单独添加审批菜单。
