### ISSUE TITLE
[Bug]: 选择字段组件，文字过长时会文字重叠

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5794]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/26241897/27fd261e-b42a-4072-b314-475e3df88388">

### Steps To Reproduce 重现步骤

审批王添加字段功能

### Version 版本

2.5.20-beta.6

**Comment by hotlong** [comment]
窗口调大 & 太长用省略号
