### ISSUE TITLE
[Bug]: 台账直接生成的流程，lookup类型字段值带不出

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/steedos-platform#5795]
### Description

https://github.com/steedos/steedos-ee/issues/546

### Steps To Reproduce 重现步骤

关联任务：
- https://github.com/steedos/steedos-ee/issues/546

### Version 版本

2.5.20-beta.6

**Comment by baozhoutao** [comment]
此问题与https://github.com/steedos/steedos-platform/issues/5797 是同一个原因.
