### ISSUE TITLE
[Bug]: 列表页操作按钮列显示错位 

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5798]
### Description

之前显示的`操作`文字直接删除了，应该改成 `&nbsp;`

<img width="1103" alt="企业微信截图_59b2bbd7-52dd-4100-9deb-cbb6c8d8324b" src="https://github.com/steedos/steedos-platform/assets/50353452/35fa7c52-b8a7-4530-a857-3878d65aee60">

### Steps To Reproduce 重现步骤

运行 steedos-ee

### Version 版本

2.5.20-beta.10

**Comment by Flyingliao** [comment]
pc端 ：
列表视图、对象表格
<img width="702" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/2634c49a-018a-4115-9e5f-e16184ff3e8b">

<img width="444" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/66a993c0-229b-45f1-9d51-dce00c9e48c2">

<img width="763" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/953c4da0-7737-4413-bdb8-1035a6e103de">

<img width="495" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/ae5f6479-0044-4d18-9f9a-8db3cb8d4b79">

  记录页下的列表视图、对象表格
<img width="768" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/e33d0999-bc09-49f0-83ed-65cc51723906">

手机端：
列表视图、对象表格
<img width="247" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/6c9f128e-580b-4a37-89a5-71701c69dcc4">

<img width="285" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/a97a2626-7c04-4bb5-8131-1138c27af438">

<img width="227" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/b53ae25b-46a0-4516-9fc6-c7902ea5d28a">
