### ISSUE TITLE
[Feature]: 分类绑定应用后，分类下所有流程禁止在审批王端发起情况下，隐掉应用下审批菜单的“新建”按钮

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5805]
### Summary 摘要

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/37e38f02-e81e-4a07-8d65-c1d309b44032">

### Why should this be worked on? 此需求的应用场景？

应用下的审批菜单只作为一个审批流程的入口

**Comment by hotlong** [comment]
这个会影响系统性能，暂不考虑。
