### ISSUE TITLE
[Feature]: 按钮添加显隐字段. 按钮上配置的覆盖amis button中的属性.

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5809]
### Summary 摘要

比如`导出`按钮，目前虽然启用的，但是不显示。需要配置页面布局才能用。

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by baozhoutao** [comment]
导出按钮没显示可以通过配置对象权限来处理.
![image](https://github.com/steedos/steedos-platform/assets/6194462/bcc335a6-f0d4-4a0b-bde8-eb32124c3fef)

**Comment by baozhoutao** [comment]
按钮添加显隐字段. 按钮上配置的覆盖amis button中的属性.

**Comment by baozhoutao** [comment]
- [ ] visible
- [ ] visibleOn

**Comment by baozhoutao** [comment]
考虑内核如何自定义?

**Comment by baozhoutao** [comment]
考虑默认按钮如何自定义?
- 将默认按钮注册成amis事件动作
- 默认按钮添加自定义

**Comment by baozhoutao** [comment]
方案:
- 去掉按钮上的visibleOn
- 修正默认按钮的visible属性
