### ISSUE TITLE
[Bug]: 所有的下拉框单选应该支持清空字段值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5814]
### Description

amis是支持的，只要配置clearable属性即可。
![image](https://github.com/steedos/steedos-platform/assets/6219465/650c52ba-6c4a-4d7a-93f8-390c4f330148)

### Steps To Reproduce 重现步骤

新建编辑记录时，单选的下拉框字段无法清除字段值

### Version 版本

2.5.x

**Comment by Flyingliao** [comment]
所有的下拉框单选早就支持清空字段值，当前表单是新建按钮弹窗中自定义原生的表单微页面。
