### ISSUE TITLE
[Bug]: 新建字段更新弹出窗口边距样式不对，而且只有一个分组时也不应该显示分组

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5816]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/6362732c-d6ac-482c-9d6e-fe6f1441e255)

### Steps To Reproduce 重现步骤

新建字段更新

### Version 版本

2.5.20.beta.x

**Comment by CarlWhite2020** [comment]
新建字段更新的对象字段下拉并不会加载所有对象列表数据，查看源代码发现是这里在查询数据的时候，只查询了部分数据，建议处理方式如下：
方案一：去掉top参数，直接加载全部数据
方案二：下拉列表方式修改为弹出窗模式，以实现分页查询的目的
![image](https://github.com/steedos/steedos-platform/assets/62589030/8d4f27e5-5895-47ee-a75c-b47d58d3234d)

**Comment by hotlong** [comment]
表单边框可以去掉
