### ISSUE TITLE
[Bug]: 系统对象编辑字段并保存时报错

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5817]
### Description

保存报错，并且多生成了一个一样的字段
![image](https://github.com/steedos/steedos-platform/assets/127007861/f5636159-5518-43ae-8932-ffa7638aca40)
![image](https://github.com/steedos/steedos-platform/assets/127007861/87c651cb-bab4-425e-835c-cd1a398a2305)

### Steps To Reproduce 重现步骤

1、点击进入任意系统对象
2、编辑字段并保存

### Version 版本

2.5

**Comment by baozhoutao** [comment]
重现方式修改的对象不是meteor collection下的对象.
