### ISSUE TITLE
[Bug]页面新建对象之后，新建流程绑定对象，选不中所新建的对象

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5818]
### Description

1、此问题出现在华炎内部平台，版本：2.5.19，ee项目：使用2.5.19版本，未重现。
2、对象已绑定允许配置对象流程。
![image](https://github.com/steedos/steedos-platform/assets/129827462/bdf8ad47-8ce1-4624-8824-d6ee9281ec3a)
3、查看网络，发现是由graphQL请求，top导致的。
--top属性等于10时（当前graphQL请求top为10），查询不到新建的对象。查询总条数为86条，实际数量小于86条。
![image](https://github.com/steedos/steedos-platform/assets/129827462/824da8c5-9096-43af-bdba-17a20cdb0d77)

--top属性等于100时，能查询到刚刚所新建的对象，查询总条数为86条，实际数量也为86条。
![image](https://github.com/steedos/steedos-platform/assets/129827462/f9f540bc-cfca-4af9-aca2-a2d1345d294c)

关联任务：https://github.com/steedos/steedos-ee/issues/495

### Steps To Reproduce 重现步骤

1、页面新建对象,勾选允许配置对象流程。
2、新建流程绑定所创建的对象。

### Version 版本

2.5.19

**Comment by lizheng-steedos** [comment]
估计是库里的页面配置的对象超过十个，页面查数据有问题
