### ISSUE TITLE
[Bug]: 在字段设置界面修改下拉框字段的选项label后需要重启服务才能生效

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5822]
### Description

- 只是选项label变更才需要重启才生效，变更选项颜色或新增加的选项都不需要重启就能生效，所以可能是因为label值涉及到国际化才需要重启服务。
- 修改下拉框字段时，如果同时修改已有选项的label和增加新选项可以看到前端业务记录新建编辑界面中该字段新加的选项，但是之前已有选项的label却还是保持修改前的值
- 实测重启服务端服务后下拉框字段的选项label就会生效。

![image](https://github.com/steedos/steedos-platform/assets/6219465/f8fbb92a-2401-4007-849f-76eb9daee1fb)
![image](https://github.com/steedos/steedos-platform/assets/6219465/7cbb4a13-83ce-4334-974d-b507bcb4e083)

### Steps To Reproduce 重现步骤

1. 在对象设置页面找到下拉框字段，变更选项的label和颜色值，也可以再增加一个新的选项
2. 进入该对象的列表页面，点击右上角的新建按钮新建记录，在弹出的表单中可以看到该下拉框字段并没有显示变更选项label，不过新增加的选项是可以看到的
3. 此时查看uiSchema接口可以看到该字段返回的label是变更前的值，但是里面的颜色值却是变更后的，也返回了新增加的选项
4. 重启服务后再新建记录可以看到此下拉框字段显示了变更后的label，说明是此问题是服务端缓存问题

### Version 版本

2.5.20.beta.x

**Comment by baozhoutao** [comment]
重现方式:
下拉选项配置颜色后会导致label修改异常.

**Comment by baozhoutao** [comment]
刷新浏览器即可, 无需重启服务.   
未能重现.

**Comment by baozhoutao** [comment]
![Uploading select field.gif…]()

**Comment by baozhoutao** [comment]
![select field](https://github.com/steedos/steedos-platform/assets/6194462/0f31b9d6-aba1-4e38-aaad-5f66f4ef3ff0)
