### ISSUE TITLE
[Feature]:  流程分类字段搜索时，下拉框只显示十条记录，应该显示所有记录

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5830]
### Summary 摘要

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/28f11134-fe3e-4864-8034-d3e0e6bafff8">

### Why should this be worked on? 此需求的应用场景？

具体开发方案和庄总确认

**Comment by hotlong** [comment]
为什么不能弹出选择

**Comment by baozhoutao** [comment]
select 下拉选择, 最大显示数量也调大点?

**Comment by baozhoutao** [comment]
方案: select 显示数量调整到 200
