### ISSUE TITLE
[Bug]: 【审批中心】查看审批单的流程图界面放大和缩小按钮的功能错误

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5835]
### Description

关联任务：
- https://github.com/steedos/steedos-ee/issues/536

### Steps To Reproduce 重现步骤

见任务

### Version 版本

 2.5.20-beta.16

**Comment by hotlong** [comment]
如果不好处理，就直接删除放大缩小按钮
