### ISSUE TITLE
[Bug]: 列表视图字段配了宽度后，显示不全数据，且拖动无效

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5840]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a3b02d68-f47b-42e4-9e02-21f4ea98b883">

### Steps To Reproduce 重现步骤

关联任务：
- https://github.com/steedos/steedos-ee/issues/552

### Version 版本

2.5.20-beta.16

**Comment by tujiajun** [comment]
拖动无效是因为每个字段的宽度加起来已撑满列表
