### ISSUE TITLE
在编辑页面, 选择供应商后, 需要联动显示应供商的等级, 且不允许用户修改但是值需要提交

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5842]
### Description

对象字段设置字段权限，字段权限设置为“允许查看，不允许编辑”。
此时在编辑界面不显示此字段。理想情况应为编辑界面显示出字段，但是不允许修改（类似于readonly效果，如果使用readonly,需要考虑字段权限和字段联动同时使用时，字段值能否正确带出）。
<img width="1185" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/6eb57ad2-7b7b-4b09-95f0-c274b547484f">
<img width="1393" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/1633c498-8166-40a0-b407-d35ae3bd8643">
<img width="1270" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/66f14a51-2290-47c9-b991-8e2b0f64ecc6">

### Steps To Reproduce 重现步骤

1、新建字段权限、设置为“允许查看，不允许编辑”
2、编辑对象字段即可重现，

### Version 版本

2.5.20-beta.16

**Comment by hotlong** [comment]
这个很复杂，需要探讨。

**Comment by baozhoutao** [comment]
在编辑页面, 选择供应商后,显示供应商相关字段(只读)

**Comment by baozhoutao** [comment]
在编辑页面, 选择供应商后, 需要显示应供商的等级, 且不用许用户修改但是值需要提交.

**Comment by hotlong** [comment]
相关任务已开发 https://github.com/steedos/steedos-platform/issues/5531

**Comment by hotlong** [comment]
重复
