### ISSUE TITLE
[Bug]: 相关文件页面表格样式需要优化，右侧背景有点乱

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5848]
### Description

相关文件打开后页面样式需要调整
![WechatIMG131](https://github.com/steedos/steedos-platform/assets/126655403/26bd5893-35fa-40a7-aa82-b94c3165a0f5)
<img width="1105" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/f3db1840-9664-46d9-91d3-d198878b103d">

### Steps To Reproduce 重现步骤

1.添加相关文件
2.点击打开

### Version 版本

2.5.19

**Comment by sujiahao66** [comment]
#5720

**Comment by Flyingliao** [comment]
<img width="879" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/f13e9c69-ad28-4ff4-b4d9-9b39815936d2">
