### ISSUE TITLE
[Feature]: 微页面使用对象表格配置待办流程时配不出来

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5853]
### Summary 摘要

对象表格设置“审批”/“审批单”对象后，列表能够显示记录，但是点进去是进监控箱，而不是进到待办里进行审批
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/6657d5af-605b-4d2e-bb2e-e7c3f7246261">

### Why should this be worked on? 此需求的应用场景？

微页面配置待审批列表场景

**Comment by Flyingliao** [comment]
<img width="1151" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/a75379bd-4314-4a4f-b4f8-0376f89bd659">

   审批 - instance_tasks  对应  inbox
   审批单 - instances  对应  monitor

**Comment by lizheng-steedos** [comment]
单独配置属性及过滤条件：
```
  "data": {
    "listName": "inbox"
  },
```
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e03af616-a4bb-44f5-b221-c206312ffcc8">
