### ISSUE TITLE
多选字段为空时，随流程发起审批同步之后，多选字段等于空字符串，导致列表详情页报错

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5854]
### Description

多选字段为空，发起审批同步之后，应该为[]或者null。

![image](https://github.com/steedos/steedos-platform/assets/129827462/4a312af3-77bd-41d6-bd9e-237b3c8e803a)

报错信息：
![image](https://github.com/steedos/steedos-platform/assets/129827462/bf44a3ae-c135-4f30-bb03-f7613b39b574)

关联任务：
- https://github.com/steedos/steedos-ee/issues/549

### Steps To Reproduce 重现步骤

1、需要一个含多选的字段的对象。
2、流程绑定该对象。
3、多选字段为空，发起审批（审批王与台账双向同步）。
4、审批完成之后，列表详情页报错

### Version 版本

 2.5.20-beta.16

**Comment by sunhaolin** [comment]
steedos retrieve:source 命令的问题

**Comment by sunhaolin** [comment]
- [ ] 合并分支导致，需讨论方案
