### ISSUE TITLE
[Bug]: 审批-在流程列表页，单选流程或多选流程导出报错

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#5855]
### Description

可导出

### Steps To Reproduce 重现步骤

1.在流程列表页，点击单个流程旁的箭头，选择导出流程，或选择多个流程，点击“导出流程”按钮
2.报错
<img width="1208" alt="1700815132209" src="https://github.com/steedos/steedos-platform/assets/7665279/974f265f-550b-4fbf-858d-a0217ae9fbdd">
<img width="1350" alt="1700816595741" src="https://github.com/steedos/steedos-platform/assets/7665279/3cb7974f-11f5-4c57-b91e-062bc5e8ac83">

### Version 版本

 2.5.20-beta.16

**Comment by hotlong** [comment]
如果不好处理，就停用此按钮
