### ISSUE TITLE
[Bug]: 微页面中给page组件配置的css和cssVars属性会影响全局样式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5856]
### Description

如下图这样配置css或cssVars属性。
<img width="506" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/3825e3d0-0081-4e39-b143-3e85dbd97809">
会影响全局样式，比如下图所示，标准的新建记录弹出窗口背影色变成了上面微页面中加的弹出窗口背影色。
<img width="1120" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/49250813-0c82-493a-8e33-e887f0227393">

### Steps To Reproduce 重现步骤

1. 新建一个微页面，给page组件添加css或cssVars属性增加自定义样式，比如给antd-Modal-content样式类添加背景色
2. 在前台访问这个微页面
3. 切换到某个对象列表页面，新建记录
4. 可以看到弹出窗口表单背景色变成了上面微页面中配置的背景色了

### Version 版本

2.5.20.beta.x

**Comment by yinlianghui** [comment]
自定义css可以通过给微页面page组件添加className，并把此className加到所有自定义样式类的前缀来防止全局样式污染问题，但是自定义cssVars也会污染全局样式的问题好像没好办法。

**Comment by baozhoutao** [comment]
自定义css、cssVars 是通过 style标签来实现了, 使用时需要遵循css规范, 如果需要修改特定的组件样式, 可以先给组件添加className后,再依据自定义的className设置css改写其样式.

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/82252c0e-9344-422e-a9dc-d9920f2418ac)
