### ISSUE TITLE
[Bug]: 修改流程名称后，若待审核内有修改前后的两种流程，则会显示两个相同的流程名

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5860]
### Description

<img width="209" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/c55962bd-d274-41a6-ae09-fbd2d46f8643">
<img width="980" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/8566797e-3f7d-42ef-8632-bb6b9ff52502">
<img width="363" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/0c53c495-f18f-4f1d-9f3f-2ca5fac0de25">

### Steps To Reproduce 重现步骤

1、选一个流程新建一个审批单发给自己
2、修改这个流程的名字
3、再通过改完名字后的流程建一个审批发给自己

### Version 版本

2.5

**Comment by hotlong** [comment]
左边分组的时候，不应该区分不同的流程版本？

**Comment by baozhoutao** [comment]
按现在的左侧菜单数据算法, 流程分类修改名称也会带来类似问题.

**Comment by baozhoutao** [comment]
程序目前是按instance_tasks中的flow_name、category_name 进行group后显示的.  
处理方案需要讨论.  
- 左侧通过flow、category分组, 并查询数据库获取最新的流程名称、分类名称?
- 列表上的流程名称是否需要处理, 可能会和左侧分组不一致.

**Comment by hotlong** [comment]
既然比较复杂，就不处理
