### ISSUE TITLE
[Feature]: 审批王表单支持百分比类型字段显示为百分比

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5862]
### Summary 摘要

字段配置为百分比类型字段之后，台账界面显示为百分比，审批单界面显示为小数。
![image](https://github.com/steedos/steedos-platform/assets/126655403/5016ab58-4e6d-4902-8405-f32b3efe75ee)

### Why should this be worked on? 此需求的应用场景？

审批单界面显示

**Comment by baozhoutao** [comment]
目前台账和审批单 百分比字段显示单位不统一.

**Comment by sunhaolin** [comment]
- [ ] 表单数值字段增加属性 '显示为百分比'(is_percent，boolean类型)
- [ ] 流程详情页 '添加字段' 逻辑调整：当对象字段类型为百分比时流程表单数值字段需赋值is_percent:true
- [ ] 申请单显示
    - [ ] 只读
    - [ ] 编辑
- [ ] 申请单打印
