### ISSUE TITLE
[Bug]: 代码加载的对象，在页面新增字段后，列表视图、新建记录等地方都看不到这个字段

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5864]
### Description

重启服务也是没用的

### Steps To Reproduce 重现步骤

1、EE项目启动；
2、项目任务对象新增字段；
3、修改列表视图选不到新增的字段；
4、重启服务后，也是选不到字段

### Version 版本

 2.5.20-beta.19

**Comment by lizheng-steedos** [comment]
字段权限中也有类似问题：
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a913bfa2-566d-475c-aaba-ed89f985e673">

**Comment by baozhoutao** [comment]
只有db中的对象才可以 显示字段的新建按钮和 对象的字段布局按钮
