### ISSUE TITLE
[Bug]: 工作流规则中时间触发器-工作流通知只读不显示（实际有值），编辑界面显示。

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5865]
### Description

![image](https://github.com/steedos/steedos-platform/assets/129827462/8d068446-a00d-4528-b4ee-adbfe5f14773)
![image](https://github.com/steedos/steedos-platform/assets/129827462/a50c08c9-ba9a-4f4f-8c57-1963c1b12bf7)

### Steps To Reproduce 重现步骤

1、在设置中新建消息提醒
2、新建工作流规则，在时间触发器中绑定新建的消息提醒。

### Version 版本

2.5.20-beta.19

**Comment by yinlianghui** [comment]
这个问题是因为GraphQL接口返回grid类型字段的_display时有bug，未正确返回库里面多选的lookup字段值。
![image](https://github.com/steedos/steedos-platform/assets/6219465/053bb53e-4db3-4455-a648-ad73d40a8664)

**Comment by yinlianghui** [comment]
实测页面布局的“相关字段”字段的field_names也有这个问题，_display中返回的值中会无故少返回数组中的元素值。
![image](https://github.com/steedos/steedos-platform/assets/6219465/cfc03b96-a2ec-4258-9325-a69bdfcee966)
