### ISSUE TITLE
[Bug]: 后台页面配置对象按钮后，前台按钮显示不出来

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5868]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/870c80a3-bf70-42ae-99eb-88aa284f0ff8">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/f7248624-78b5-4aae-95d6-bc4f8c3d210b">

### Steps To Reproduce 重现步骤

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/53e3400d-4224-49df-80c0-8a1a6e2249f6">

### Version 版本

2.5.20-beta.19

**Comment by lizheng-steedos** [comment]
是因为进入设计器保存太快，按钮加载前保存了

**Comment by baozhoutao** [comment]
修改设计器, 在amis 设计器未渲染完成前不现实保存按钮?
