### ISSUE TITLE
[Feature]: 替换微页面中普通的input-table组件，改为使用steedos-input-table

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5876]
### Summary 摘要

- [x] 页面布局表单内的input-table
- [x] 设计字段布局内的input-table
- [x] 列表视图表单内的input-table【要先完成关联issue： [Feature]: 列表视图表单改为使用ObjectForm显示表单内容 #5638】

### Why should this be worked on? 此需求的应用场景？

设置分组

**Comment by yinlianghui** [comment]
对象字段上有些字段也要改为新子表组件，这个单独建issue了：[Feature]: 替换平台中比较重要的几个grid子表对象字段，类型改为table，使用steedos-input-table组件 #5882
