### ISSUE TITLE
新增节假日表

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#588]
- 每天一条记录。包括周末假日、法定公休日，以及其他管理员输入的休息日。
- 列表页做一个按钮，自动生成指定年份的周末假日。
- 管理员可以修改，删除某个假日或是新增假日。

字段
- name 假日名称，普通周末自动生成为年月日，例如 2020-02-12
- 日期

**Comment by sunhaolin** [comment]
- [ ] 还要考虑改审批王的内核。计算超时时间的部分。
