### ISSUE TITLE
[Feature]: 替换平台中比较重要的几个grid子表对象字段，类型改为table，使用steedos-input-table组件

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5882]
### Summary 摘要

可以参考工作流规则对象的“时间触发器”字段从grid改为table的变更代码：https://github.com/steedos/steedos-platform/commit/65bc7572567eccd6765764f25bc66d14c8aa2096

以下是几个重要清单：

- [x] 对象流程映射中的两个“字段映射关系”字段【可以改善目前卡的问题】
![image](https://github.com/steedos/steedos-platform/assets/6219465/158606ba-1429-4799-a27c-1649b34aec11)

- [x] 数据导入对象中的“字段映射”字段
![image](https://github.com/steedos/steedos-platform/assets/6219465/376cf9d4-d9ad-4c48-a359-58594b63207b)

- [ ] 流程详细页面中的步骤和两个字段instance_fields/instance_table_fields【是微页面】
![image](https://github.com/steedos/steedos-platform/assets/6219465/e4225614-d390-4807-8e7f-ab9e21c980e5)

- [x] 对象字段设置界面中下拉框字段的options属性配置【其中颜色可以使用颜色选择控件，见：[Feature]: steedos-field 支持颜色选择字段类型 #5820】
![image](https://github.com/steedos/steedos-platform/assets/6219465/8d827f30-83a7-4641-800d-5add3489b97d)

### Why should this be worked on? 此需求的应用场景？

优化平台子表效果

**Comment by Flyingliao** [comment]
流程对象中的grid字段替换为table [#5949](https://github.com/steedos/steedos-platform/issues/5949)
