### ISSUE TITLE
[Bug]: Saas环境，开新的工作区流程数据没有初始化

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5883]
### Description

目前的情况是，第一开的工作区是有流程数据的，后面开的所有工作区都没流程数据
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/0ac897d4-446d-4e2a-820e-beb6499c7dd3">

### Steps To Reproduce 重现步骤

https://expense.steedos.cn环境注册一个新工作区就可以看到后台没有流程

### Version 版本

 2.5.20-beta.20

**Comment by sunhaolin** [comment]
- [ ] 测试 页面流程升级、导入、批量导入
