### ISSUE TITLE
[Feature]: 在微服务模式下，支持加载工作流规则、对象验证规则元数据

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5885]
### Description

不是以微服务模式启动的项目，是好的。
未切换库之前：
![image](https://github.com/steedos/steedos-platform/assets/129827462/ce8558d7-c159-4168-af23-f3eef19cdd50)
切换库之后：
![image](https://github.com/steedos/steedos-platform/assets/129827462/99c6f8ad-3de3-4440-b45f-9702f5dd28a3)

关联任务：
- https://github.com/steedos/steedos-platform/issues/5738
### Steps To Reproduce 重现步骤

1、新建工作流规则同步成源代码
2、切换数据库
3、测试

### Version 版本

2.5.20-beta.19

**Comment by baozhoutao** [comment]
- [ ] validationRule
- [ ] role
- [ ] flowRole
- [ ] approvalProcess
- [ ] workflow
