### ISSUE TITLE
[Feature]: 对象启用树状结构显示时，默认展开第一层

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5886]
### Summary 摘要

目前树状结构默认不展开，选择“部门”等树状结构显示的对象记录时不方便，需要支持默认展开。

### Why should this be worked on? 此需求的应用场景？

目前树状结构默认不展开，选择“部门”等树状结构显示的对象记录时不方便，需要支持默认展开。

**Comment by hotlong** [comment]
listview 支持配置amis 属性集成吗？

**Comment by yinlianghui** [comment]
> listview 支持配置amis 属性集成吗？

微页面上可以通过crudDataFilter属性来实现，他们的需求是默认展开第一层就行了，不需要额外配置。
