### ISSUE TITLE
[Bug]: 前台自定义“发起审批”按钮后，设计器中按钮代码缺失

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5888]
### Description

设计器中只包含以下代码
<img width="1155" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/18a71347-35d5-4440-a370-40363ea9d558">

### Steps To Reproduce 重现步骤

任意对象下自定义“发起审批”按钮，即可重现。

### Version 版本

2.5.20-beta.19

**Comment by hotlong** [comment]
重复
