### ISSUE TITLE
[Bug]: 使用“添加字段”按钮添加审批王表单子表后，从台账发起审批子表数据未从台账带入审批单

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5890]
### Description

使用“添加字段”按钮添加审批王表单子表后，从前台界面查看，对应关系正确，从台账发起审批子表数据未从台账带入审批单（两个子表，一个能带出，一个带出不），目前无法确认原因。
<img width="1275" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/39349215-0146-4b95-a0f5-f7b279524c88">
<img width="965" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/56e8e906-37b7-4147-841e-321be60294c1">

### Steps To Reproduce 重现步骤

无法确认具体规则

### Version 版本

2.5.20-beta.19

**Comment by sujiahao66** [comment]
测试发现：如果子表关联主表的字段是master_detail时数据可以正确带出；如果关联字段类型是lookup是则不能。

**Comment by sunhaolin** [comment]
是规则，会同步自表(master_detail)
