### ISSUE TITLE
[Bug]: 数据分析：仪表盘的筛选器无效

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5896]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/1b856b21-0819-4b36-aae9-ec8c4712ae0e">

### Steps To Reproduce 重现步骤

仪表盘添加筛选条件后，并不会根据设置的条件进行数据筛选

### Version 版本

 2.5.20-beta.22

**Comment by baozhoutao** [comment]
目前ID过滤不支持.  文本关联搜索不支持
