### ISSUE TITLE
[Bug]: 手机端，选择框多选类型字段选不了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5905]
### Description

![image](https://github.com/steedos/steedos-platform/assets/151509384/e1e2245b-ab0f-4dfc-a9f0-7452d6306bec)

### Steps To Reproduce 重现步骤

手机端

### Version 版本

2.5.20-beta.24/ 3.2.0

**Comment by Flyingliao** [comment]
原因：menuTpl 和 multiple: true 配合使用导致的。amis官网这样使用时也是坏的。
