### ISSUE TITLE
[Bug]: 对象流程同步不支持通过开启对象功能开关显示的子表

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5915]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/3ab3017e-1fc7-40a0-bd59-4a45b9f407c6">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/67fed27e-d56f-4d49-a687-34e71aae7bc1">

### Steps To Reproduce 重现步骤

对象生成流程后，添加字段把对象关联的内核子表也添加到流程上

### Version 版本

2.5.20-beta.24/ 3.2.0

**Comment by sunhaolin** [comment]
目前对象流程同步不支持通过开启对象功能开关显示的子表，包括 允许添加任务、允许添加备注、允许添加事件、允许查看申请单

即reference_to为function的字段：
```js
  related_to:
    label: Related to
    type: lookup
    index: true
    reference_to: !<tag:yaml.org,2002:js/function> |-
      function () {
            try{
              let objects = [];
              var queryResult = Steedos.authRequest(`/graphql`, {
                  type: 'POST', async: false, 
                  data: JSON.stringify({
                    query: `{ objects(filters: ["enable_tasks","=",true]){ name,space,enable_tasks } }`
                  })
              });
              objects = queryResult && queryResult.data && queryResult.data.objects;
              return _.map(objects, 'name') ;
            }catch(e){
              return []
            }
      }
```
