### ISSUE TITLE
[Feature]: 绑定了对象的流程需要显示表单设计器

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5916]
### Summary 摘要

目前绑定了对象的流程不会显示表单设计器，无法配置审批单lookup类型字段过滤。

### Why should this be worked on? 此需求的应用场景？

审批单lookup类型字段无法过滤，如果用户在审批单上修改字段值，可能会导致数据错误，进而导致业务逻辑错误。

**Comment by baozhoutao** [comment]
换实现方式
