### ISSUE TITLE
[Bug]: 前台新建列表视图时表单显示错误

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#5921]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/421bdac6-9f01-4fb9-a313-7db78c005a80)

### Steps To Reproduce 重现步骤

1、进入任意对象列表
2、点击新建 视图

### Version 版本

2.5.20-beta.24

**Comment by yinlianghui** [comment]
前台列表中列表视图所有功能都要测试下，比如复制列表视图功能就是坏的，正确的应该是这样的：
![image](https://github.com/steedos/steedos-platform/assets/6219465/3a608d46-e79c-4b55-ad56-e65b17b6c877)
目前显示的样子是错的：
![image](https://github.com/steedos/steedos-platform/assets/6219465/d08fbfd5-01f6-4d97-b39a-53aa9259e518)
这个操作清单的功能都要对下：
![image](https://github.com/steedos/steedos-platform/assets/6219465/944945c6-1399-4090-9355-158e93be0bf3)
