### ISSUE TITLE
[Bug]: 任务对象的对象权限记录中，“禁用列表视图”字段有值时，只读状态显示空白。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#5934]
### Description

禁止普通用户查看“最近查看”列表视图。
<img width="1097" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/9bd444e1-b91a-4210-9448-707b3636cc9f">

<img width="875" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/c4f7f7a2-c691-47cc-a547-d239090535a3">

### Steps To Reproduce 重现步骤

编辑 用户 权限记录，“禁用列表视图”字段选择一个视图选项，保存后在记录页查看。
<img width="1085" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/16c0f552-423a-47ea-9d5a-3af1710227bd">

### Version 版本

2.5.20-beta.25

**Comment by Flyingliao** [comment]
排查到的原因：字段值保存的值为 "undefined.recent"。  不仅仅是任务对象、还有业务伙伴对象。

当下解决办法：
用filtersFunction属性 替换该字段的 optionsFunction 属性:
```
filtersFunction: !<tag:yaml.org,2002:js/function> |-
      function(filters, values){
        return [['object_name', '=', values.object_name],["name","!=","default"],["shared","!=",false]];
      }
```
<img width="587" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/2aec96f1-3bfa-4e56-b020-8596854ac0dd">

除了代码的替换，还涉及到功能上的bug，需要fix uiSchema 中列表视图_id 为 undefined.xxx的bug。
<img width="840" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/c087110d-db0d-4eb4-b4e8-139dd90cb616">

**Comment by yinlianghui** [comment]
> 存的值为 "undefined.recent"

意思是目前uiSchema接口是坏的，需要先修正uiScehma接口中的问题

**Comment by hotlong** [comment]
关联任务 https://github.com/steedos/steedos-platform/issues/5929
