### ISSUE TITLE
[Bug]: 对象直接生成的审批王流程，相关表类型字段如果带了filtersFunction，对象带条件的相关表字段值不会带到表单对应字段

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5958]
### Description

<img width="697" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/bd798805-fad0-4fab-aede-96700cd03811">
<img width="898" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/c595d74a-ea2d-4e72-a48a-98b15b4167e9">

### Steps To Reproduce 重现步骤

ee环境，可以先创建可借款记录，进行审批，审批完成后再发起还款流程，关联刚刚审批结束的借款流程后，发起审批，可以看到审批单上的借款但字段没有值也没办法编辑。

### Version 版本

2.6.2-beta.10

**Comment by sunhaolin** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194896/a737f036-3284-4295-87e0-9170f7072984)
