### ISSUE TITLE
[Bug]: 统计分析-问题添加到看板上就坏了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5959]
### Description

<img width="1147" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e4e95664-17d9-4c92-b61c-bb556e3ae8ff">
<img width="1129" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/553c418a-ab48-4942-b79f-bfb1fbee707c">

### Steps To Reproduce 重现步骤

问题单独看都是好的，但是添加到看板上就坏掉了
https://teal-parrot-ln3xbf67.ws.vscode.steedos.cn/

### Version 版本

2.6.2-beta.10

**Comment by baozhoutao** [comment]
此问题是由于一个统计卡住了服务导致pod以为服务挂掉了返回了html 异常页面.

**Comment by baozhoutao** [comment]
此问题是由于微服务网关存在bug导致接口一直未返回数据,让pod误以为服务挂掉了.
