### ISSUE TITLE
[Bug]: 审批王设置了传阅对象，后退回。被传阅的人 ，流程还在但无法点开

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#5962]
### Description

审批王设置了传阅对象，后退回。被传阅的人 ，流程还在但无法点开详细流程。

### Steps To Reproduce 重现步骤

1.设置传阅对象
2.退回
<img width="738" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/856fefdf-3e28-4134-8c4b-f20d4f1cf879">

3.被传阅对象有记录但无法点开
<img width="1363" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/917a787b-f24a-49f5-a98b-d945f8dc3f34">

### Version 版本

2.5.19

**Comment by sunhaolin** [comment]
待观察
