### ISSUE TITLE
[Bug]: 设计字段布局，新增分组没有效果

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5974]
### Description

![image](https://github.com/steedos/steedos-platform/assets/129827462/affd5c92-8b02-45af-b87f-a5f6bb5c6473)
新增一个为名称为“主表”的分组
![image](https://github.com/steedos/steedos-platform/assets/129827462/5f186129-a98e-4a88-a21f-68691f1b0e3b)
点击确认之后，展示页没有新增的分组
![image](https://github.com/steedos/steedos-platform/assets/129827462/9fd37ce5-56f3-44b6-b8d3-cd144a6242b4)

### Steps To Reproduce 重现步骤

1、随便找一个对象，点击设置字段布局
2、点击设置分组，新增分组
3、点击确认之后，没有刚新增的分组

### Version 版本

 2.6.2-beta.12

**Comment by yinlianghui** [comment]
此问题原因是amis有一个规则：service组件里面放formItem组件，再把service组件直接放到dialog组件弹出窗口，用户在修改formItem组件值后点击确认关闭窗口后，其字段值不会自动提交到上级表单中。

而为了让子表有翻页能力，子表组件返回的根层是一个service组件，所以出现了该issue提及的问题，解决方案是以后所有使用子表组件的地方，如果是放到dialog窗口中，必须外包一层form组件，把子表放到form组件内，否则需要手动处理表单提交过程。
