### ISSUE TITLE
[Bug]: 使用设计字段布局调整字段排序，对象同步为代码后，字段缺失必要属性

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5976]
### Description

使用设计字段布局调整字段排序后，将对象同步为代码，字段属性只包含以下图片内容，字段缺失了必要属性，此时服务端会报错。
目前发现缺少data_type、formula、formula_blank_value属性，
<img width="978" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/aa6a262c-63a8-4cdb-824e-b124c8be094a">

### Steps To Reproduce 重现步骤

1、系统对象使用设计页面布局调整字段排序。
2、将此对象同步为代码，重启服务，服务端会出现图片报错。

### Version 版本

2.6.2-beta.10

**Comment by sujiahao66** [comment]
红色部分是缺失的属性
<img width="570" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/fd21ab6e-f1a7-414d-a70f-d6ee5cf12cfb">

**Comment by yinlianghui** [comment]
此现象是大bug，需要确认2.5有没有问题，如果也有问题需要在2.5也改掉

**Comment by baozhoutao** [comment]
如果是1开,  需要先放对象、字段定义deploy后,再在页面修改数据.
如果是2开, 可在页面直接修改字段属性, 同步到本地后的源代码会被标记 extend

**Comment by baozhoutao** [comment]
此问题暂时不做修改.
