### ISSUE TITLE
[Bug]: 记录详情页，只读和可编辑字段在同一行时，横线不在同一行

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#5978]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a97d244a-db04-43f2-9aa1-3249badb2877">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.6.2-beta.13

**Comment by Flyingliao** [comment]
具体原因：样式冲突
```
.antd-Form-item:last-child {
    margin-bottom: 0;
}
```
<img width="1116" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/c48d13e2-1e33-466c-b92c-f5ce0668801f">
