### ISSUE TITLE
[Bug]: npx create-steedos-app my-project 报错Cannot find module 'chalk'

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#5979]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/76f5b003-9a25-484e-86bf-12a0703c52da)
![image](https://github.com/steedos/steedos-platform/assets/15027092/ff553873-6365-41db-a118-e2e4a24e72d1)

### Steps To Reproduce 重现步骤

1、运行环境：win10专业版
2、node：14.21.3
3、执行npx create-steedos-app my-project报错

### Version 版本

2.5

**Comment by baozhoutao** [comment]
此问题和操作系统无关
