### ISSUE TITLE
[Bug]: 在字段yml中设置默认值，新建时，在前端清空该字段的默认值，点击保存报错

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5989]
### Description

1、点击新建，此时，页面内背景色有默认值
![image](https://github.com/steedos/steedos-platform/assets/129827462/12859cf2-b6dc-44c0-aa8f-a16f9fc2c111)
2、将默认值清空，点击保存报错
![image](https://github.com/steedos/steedos-platform/assets/129827462/c42d975f-450b-4b55-b451-88bfb9ca88cc)

不止颜色字段类型默认值有问题，其他字段类型默认值如上面操作同样报错

### Steps To Reproduce 重现步骤

1、找一个有默认值的对象
2、点击新建、将默认值去掉
3、点击保存，报错

### Version 版本

2.6.2-beta.14

**Comment by Flyingliao** [comment]
联动的字段含有默认值时还是会报错，需要继续排查处理。
