### ISSUE TITLE
odata接口中的插入/查询视乎没有校验

### ISSUE THREAD

**Issue by diaodiaop** [steedos/steedos-platform#599]
在官方文档中说.

http://192.168.3.147:6060/api/odata/v4/{spaceid}/space_users

这个地址用于查询或者添加.

其中spaceid理论上 应该是存在的.. 或者使用login登陆后返回的.

但是实际我在spaceid设置任意文本,,都能查询出来.

比如我访问了

http://192.168.3.147:6060/api/odata/v4/1/space_users

就可以看到所有的用户.应该提示spaceid 不存在吧?

**Comment by sunhaolin** [comment]
已使用新规范，https://www.steedos.com/developer/api/odata_query/
