### ISSUE TITLE
[Bug]: 流程列表行下拉操作菜单中“表单设计器”菜单点击后会报错，应该去掉

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5990]
### Description

流程记录详细界面右上角已经没有这个按钮了。
![wecom-temp-115105-6ea829b49e80519594ea12f03f429b51](https://github.com/steedos/steedos-platform/assets/6219465/524382a0-ed3c-4d3f-b633-5902f90c56ec)
<img width="436" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/e6b94577-2192-4e6c-aa5c-fedaf29c1ca3">

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.2.beta.x

**Comment by hotlong** [comment]
去掉对应的按钮

**Comment by baozhoutao** [comment]
由此改动导致: https://github.com/steedos/steedos-platform/commit/ba8d82b59a83580bc172da3f98eb99c3a37367e5

**Comment by baozhoutao** [comment]
> 由此改动导致: [ba8d82b](https://github.com/steedos/steedos-platform/commit/ba8d82b59a83580bc172da3f98eb99c3a37367e5)

造成此问题的原因是由于上述改动未支持按钮在列表上的显示效果.

**Comment by baozhoutao** [comment]
如果只是绑定对象的流程去掉表单设计器 , 流程未绑定对象的时,点击表单设计器还是会报错.
