### ISSUE TITLE
[Bug]: 按钮设计器中弹出框中增加对象表单组件后，弹出表单有边框，应去掉

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5993]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194896/c1552005-22d1-47b5-bc80-da13733d01d5)

### Steps To Reproduce 重现步骤

新增按钮
进入设计器
弹框增加 对象表单 组件 

### Version 版本

 2.6.2-beta.14

**Comment by hotlong** [comment]
对象表单组件默认是带边框的，可以通过组件修改样式去掉边框。
