### ISSUE TITLE
[Bug]: 当列表字段都配置了宽度，而页面宽度大于字段宽度总和，列表视图显示异常，字段内容宽度未自动撑满。

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#5997]
### Description

当字段宽度小于页面自动分配的宽度，内容未自适应撑满。
图一：
<img width="1132" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/b55de247-5c51-469b-af94-541afeb06d33">

### Steps To Reproduce 重现步骤

1、给列表视图的字段设置宽度，尽量设置得小一些。
2、在列表视图界面查看。

在界面上设置或者在yml文件中设置：
<img width="388" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/9d0b81cf-3647-4755-a217-1b537fc7042e">

### Version 版本

2.6.2-beta.14

**Comment by Flyingliao** [comment]
排查结果：
amis 3.2.0版本下，当给列字段设置 width 时，会出现 图一 中 的异常， 新增三个内联样式，新增两个div元素。

**Comment by hotlong** [comment]
这个问题要严格测试，确认所有情况都正常再提交修改

**Comment by hotlong** [comment]
这个最新版重新确认一下

**Comment by tujiajun** [comment]
按照issue描述配置了两个字段的宽度，总体宽度小于页面宽度，并未出现如图描述的问题，而是自适应的给每一列分配宽度，经排查，amis3.6.3给columns内设置width后，会使用colgroup控制列宽，不会在td内再生成div了
![image](https://github.com/steedos/steedos-platform/assets/127007861/35598518-e4e1-4cd3-9739-bb4445c3128a)
![image](https://github.com/steedos/steedos-platform/assets/127007861/86643047-47ad-478e-8562-f3897f27b741)
![image](https://github.com/steedos/steedos-platform/assets/127007861/dfde89d9-02fb-4a33-831d-319eb8071b46)
![image](https://github.com/steedos/steedos-platform/assets/127007861/37807019-3633-4b22-a900-d77e693236b1)
