### ISSUE TITLE
[Bug]:启动软件包时，流程导入报错field_map_back.0 is not allowed by the schema

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5999]
### Description

![image](https://github.com/steedos/steedos-platform/assets/129827462/d5db8b06-6fba-47bb-ab83-995148d8a764)

将版本切换到2.6.2-beta.13 是好的

### Steps To Reproduce 重现步骤

ee项目：https://gitlab.steedos.cn/steedos/steedos-ee
1、启动steedos平台
2、启动软件包时，在platform控制台报错
关联任务： 
- https://github.com/steedos/steedos-platform/issues/5994

### Version 版本

2.6.2-beta.14

**Comment by sunhaolin** [comment]
关联issue https://github.com/steedos/steedos-platform/issues/5994
