### ISSUE TITLE
[Bug]: 2.6版本 keycloak插件未生效

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6001]
### Description

启用keycloak插件，服务登录页没有自动跳转到id.steedos.cn

### Steps To Reproduce 重现步骤

1、platform版本为2.6.2-beta.15
2、steedos-ee docker版本2.6.0

### Version 版本

2.6

**Comment by baozhoutao** [comment]
@steedos/service-enterprise 升级到 2.5.20
