### ISSUE TITLE
[Bug]: 使用directUpdate更新记录时，部分字段值更新失败，切换数据库后正常

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6015]
### Description

代码如下：
```js
let updateDoc = { 'is_qualified': true, 'is_supplier': true};  // 字段值符合要求
await this.getObject('accounts').directUpdate(doc._id, updateDoc);
```
使用以上代码更新记录时，“is_qualified”字段更新失败，"is_supplier"字段更新成功。
is_qualified字段不在数据库中，且在对象字段页面中可以正确加载此字段。
切换数据库后使用directUpdate更新成功，不切换数据库，使用update替换directUpdate更新记录也能更新成功。

### Steps To Reproduce 重现步骤

无法确认具体的重现规则。

### Version 版本

2.6.2-beta.15

**Comment by sunhaolin** [comment]
字段未加载至simplechema
