### ISSUE TITLE
[Bug]: 切换English时，表头不是英文

### ISSUE THREAD

**Issue by rttmoa** [steedos/steedos-platform#6021]
### Description

我贴图片，
<img width="838" alt="Snipaste_2023-12-24_15-25-10" src="https://github.com/steedos/steedos-platform/assets/105489435/aac5be6c-3c92-4297-b3ab-b3e10b214c4d">

### Steps To Reproduce 重现步骤

2.1.85 版本还要更新这个问题吗

### Version 版本

"dependencies": {         "@steedos/service-community": "2.1.85"     },

**Comment by hotlong** [comment]
2.1 已经停止开发了。此问题已修复，需要升级到最新版。
