### ISSUE TITLE
[Feature]: 自动编号字段，增加开关配置，可在填单时点击按钮获取编号

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6022]
### Summary 摘要

<img width="1169" alt="企业微信截图_80c6aad3-39f1-4544-9f6c-786e4e812932" src="https://github.com/steedos/steedos-platform/assets/50353452/237f71fb-f663-4f92-b5a6-8d203c8b3e01">

### Why should this be worked on? 此需求的应用场景？

简化业务

**Comment by hotlong** [comment]
服务端需要新增一个接口，返回下一个编号。@sunhaolin 支持一下。

**Comment by sunhaolin** [comment]
> 服务端需要新增一个接口，返回下一个编号。@sunhaolin 支持一下。

好的

**Comment by sunhaolin** [comment]
> > 服务端需要新增一个接口，返回下一个编号。@sunhaolin 支持一下。
> 
> 好的
[生成自动编号接口.md](https://github.com/steedos/steedos-platform/files/14048758/default.md)

**Comment by tujiajun** [comment]
增加开关后效果
<img width="1099" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/b2ae0ed0-a536-49fa-b07d-bdb87f19bc42">
<img width="680" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/c3d579fd-0e55-4c5e-919e-de064bb2bb5d">

**Comment by lizheng-steedos** [comment]
配置流水号规则为“YY-{0000}”时，获取编号失败
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/b0aa48fc-5142-4006-b367-320de72424fd">
