### ISSUE TITLE
[Feature]: 选项卡需要根据字段状态显示或隐藏

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6029]
### Summary 摘要

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/6e35827c-422d-45fb-8835-3222d66eaaab">

### Why should this be worked on? 此需求的应用场景？

比如记录在审批中时不显示“报销”和“预支款”选项卡，审批通过后才显示这两个选项卡

**Comment by hotlong** [comment]
amis 不支持
