### ISSUE TITLE
[Bug]: 选择框类型字段颜色配置在手机上不显示

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6034]
### Description

移动端不显示选择框类型字段配置的颜色背景

### Steps To Reproduce 重现步骤

选择框类型字段配置颜色，前台手机端页面看不到效果

### Version 版本

2.6.2-beta.22

**Comment by Flyingliao** [comment]
版本：2.6.2-beta.24 正常。
<img width="327" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/a1e6c17d-4ebe-49cb-8ec2-e0c42092d667">
