### ISSUE TITLE
[Bug]: 合同列表筛选设置我方责任人后，再次筛选时，用户列表为空，无法选择其他用户

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6035]
### Description

第一次筛选后：
![image](https://github.com/steedos/steedos-platform/assets/15027092/886e3701-e66e-416f-82dc-7295de26b0c5)

再次筛选时，用户列表为空，无法选择其他用户
![image](https://github.com/steedos/steedos-platform/assets/15027092/c6c39513-dd04-462e-9ea0-a116f56cfb44)

### Steps To Reproduce 重现步骤

1、合同列表，通过我方责任人进行筛选出符合条件的合同
2、再次点击我方责任人，此时人员列表为空

### Version 版本

2.6

**Comment by yinlianghui** [comment]
同：https://github.com/steedos/steedos-platform/issues/6043
