### ISSUE TITLE
[Task]: steedos-field组件static只读模式下各种字段类型属性过一遍，参考convertSFieldToAmisField函数中编辑模式代码

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6036]
### SubTasks 子任务

理论上steedos-field组件static只读模式返回的字段amis schema应该就是convertSFieldToAmisField函数返回的编辑状态下的字段schema加上属性`static:true`。
目前我们是在steedos-field组件中单独写了一遍各种字段类型只读模式的要返回的amis schema逻辑，有可能各种情况功能不全，比如之前遇到number字段类型的bug，没把小数点属性scale转为amis的精度属性precision，见：#6033

开始此任务前请先找我一起评估下直接调用convertSFieldToAmisField函数来自动生成static只读模式下要返回的amis schema的可能性。

**Comment by hotlong** [comment]
测试出bug单独写任务

**Comment by tujiajun** [comment]
未处理字段清单：
- Boolean，该字段效果正常，与平台仅有小样式差异，无需仿照objectform
- password，该字段只读时无法把显隐按钮隐藏#6556
- lookup与master_detail，这两个字段只读时没有显示为连接#5991
- url，该字段只读时无法显示为二维码#6557
- avatar，该字段无法直接通过前台创建，暂不处理
- file，该字段暂时只支持存在_display的情况
- code，该字段使用的是amis的code组件，而平台内核使用的editor组件
- grid,object,location字段暂不支持
