### ISSUE TITLE
[Feature]: 企业微信上线第三方应用费控王

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6037]
### Summary 摘要

客户通在应用中搜索关键字费用报销可以搜出费控王

### Why should this be worked on? 此需求的应用场景？

企业微信、钉钉

**Comment by chenzhipei** [comment]
企业微信接入第三方应用开发配置：
![image](https://github.com/steedos/steedos-platform/assets/15027092/068f68b1-d745-4b2d-8395-909624bc7488)

**Comment by chenzhipei** [comment]
企业微信第三方应用：
- [ ] 新用户直接创建账号登录并绑定企业微信账号；
- [ ] 旧用户根据企业微信账号单点登录；
- [ ] 组织用户同步；
- [ ] 审批通知接口；

钉钉第三方应用：
- [ ] 新用户直接创建账号登录并绑定钉钉账号；
- [ ] 旧用户根据钉钉账号单点登录；
- [ ] 组织用户同步；
- [ ] 审批通知接口；

**Comment by sunhaolin** [comment]
- [ ] 钉钉：先确认现有功能正常

**Comment by chenzhipei** [comment]
合并代码后发包测试，storeSuiteTicket函数未生效
