### ISSUE TITLE
RTL & LTR Layout

### ISSUE THREAD

**Issue by mimcomp** [steedos/steedos-platform#604]
我如何通过管理员设置使用RTL布局添加新语言

**Comment by hotlong** [comment]
目前华炎魔方只支持英文和中文，请问你希望添加什么语言？

**Comment by mimcomp** [comment]
Arabic and Persian

**Comment by hotlong** [comment]
我们可以提供定制服务，请扫描链接中的二维码具体讨论。https://www.steedos.com/company/contact-us
