### ISSUE TITLE
[Bug]: lookup字段弹出列表窗口中点击新建按钮，点击保存报错，比如指向项目集的lookup字段。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6044]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/f06c43a6-7d62-45ca-8cc2-eac3ebb9f86f)

### Steps To Reproduce 重现步骤

如题，此问题实测amis 3.2也有问题，跟amis 3.6没关系

### Version 版本

2.6.2.x

**Comment by Flyingliao** [comment]
最新软件包未重现
