### ISSUE TITLE
[Bug]: 页面宽度自定义后,列表视图无法横行滚动，

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6047]
### Description

1、全屏时效果
![image](https://github.com/steedos/steedos-platform/assets/129827462/e6d78d8a-3ab6-4854-9ff3-5846a3850861)
2、自定义页面宽度之后，
![image](https://github.com/steedos/steedos-platform/assets/129827462/2a7d0847-6a63-4132-9c0e-8e237e976696)

### Steps To Reproduce 重现步骤

1、随便找个列表视图
2、自定义页面宽度之后，无法横行拖动滚动条

### Version 版本

 2.6.2-beta.23

**Comment by hotlong** [comment]
最新版费控项目，未能重现。
