### ISSUE TITLE
[Bug]: 前端样式显示错误

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6049]
### Description

箭头图标和文字重叠了
<img width="1354" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/d929c454-c782-433c-a2b4-6ca77e44985b">
<img width="1433" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/22645ae1-0378-488b-890d-d59597652e3e">

### Steps To Reproduce 重现步骤

使用最新版本即可重现。

### Version 版本

2.6.2-beta.24

**Comment by tujiajun** [comment]
树列表目前已无该现象；badge为正常效果
![image](https://github.com/steedos/steedos-platform/assets/127007861/a34adf79-992f-4a6b-a9f0-0593fc20c54f)
