### ISSUE TITLE
[Task]:  标准对象中的 accounts, contacts 分拆到单独的软件包 @steedos/standard-accounts

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6054]
现在在业务上自定义这两个对象很麻烦。

- [x] 迁移到单独的软件包 @steedos/standard-accounts
- [x] 转换为分文件夹的对象格式
- [x] 可以通过环境变量STEEDOS_ENABLE_STANDARD_ACCOUNTS来控制是否加载此软件包（(只有值为"true"时才加载)）。

https://github.com/steedos/steedos-platform/tree/master/packages/standard-objects/community-users

**Comment by baozhoutao** [comment]
启用@steedos/standard-accounts软件包需要配置环境变量:   `STEEDOS_ENABLE_STANDARD_ACCOUNTS=true`
