### ISSUE TITLE
[Bug]: 显示对象列表时，每一行都会执行一个查询

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6056]
### Description

https://5000-moccasin-slug-8ilsmqjo.ws.vscode.steedos.cn/api/v4/objects/order?%24select=is_deleted

### Steps To Reproduce 重现步骤

设置-对象

### Version 版本

2.6

**Comment by baozhoutao** [comment]
每行执行了2次请求.  前端组件问题. widgets已修改

https://github.com/steedos/steedos-widgets/commit/b58374a383de2a2478acae2ba541b68ffd6dd2f5
