### ISSUE TITLE
[Bug]: lookup字段指向树对象，比如选部门字段，选中值在树的第三层及以下的子层的话，在编辑状态会显示为undefined

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6057]
### Description

- 只读是好的
- 选中值在第一层第二层也是好的
- amis 3.2和3.6都有这个问题

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.2.beta.x

**Comment by Flyingliao** [comment]
tree层级多时，children下为null 就会造成 undefined, 为空时改成 空数组 [] 就正常了。

或许可以给amis提issue，支持 children:null。

<img width="758" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/6c56473d-d9f7-4b51-b1f2-b002c27a46ba">
<img width="736" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/696df84d-fd04-4f73-9173-8b69e8a3a0aa">

**Comment by Flyingliao** [comment]
amis相关issue： picker 中 tree的层级超过两层且存在某个节点的 "children": null时，当选中了该节点，编辑状态下 该节点显示 undefined [#9314](https://github.com/baidu/amis/issues/9314)

**Comment by Flyingliao** [comment]
最终讨论处理结果：接收适配器中 移除节点的parent、children属性。
