### ISSUE TITLE
[Bug]: amis3.6  “数据导入”时上传文件后，点击提交后报错

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6058]
### Description

导入数据时，上传文件后点击提交报错，报错后组件在一直刷新
![image](https://github.com/steedos/steedos-platform/assets/126655403/a019a7d3-9d85-4e98-8e86-f1e950ab0eff)

### Steps To Reproduce 重现步骤

引用amis版本3.6.3，使用数据导入功能测试上传文件即可重现

### Version 版本

2.6.2-beta.24

**Comment by baozhoutao** [comment]
已 不能重现.

**Comment by baozhoutao** [comment]
https://[github.com/steedos/steedos-widgets/commit/ac8e3cf2165915875f3f0aa4bd0cd4b1b99fae00](https://github.com/steedos/steedos-widgets/commit/ac8e3cf2165915875f3f0aa4bd0cd4b1b99fae00)
