### ISSUE TITLE
[Feature]: 对象列表视图/搜索项配置中应该不显示隐藏的字段

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6062]
### Summary 摘要

- [ ] 列表视图-字段列（包括前台设置列表视图）
- [ ] 列表视图-排序（包括前台设置列表视图）
- [ ] 列表视图-过滤（包括前台设置列表视图）
- [ ] 列表视图-搜索项（包括前台设置列表视图）
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/afe8dd23-a805-4b18-92ee-c3bc54512299">

### Why should this be worked on? 此需求的应用场景？

功能优化

**Comment by tujiajun** [comment]
该需求已实现
