### ISSUE TITLE
[Bug]: 对象没有自定义时，“设计字段布局”按钮，设计报错“No permission”

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6063]
### Description

调整“申请单审批状态”字段到其他分组后保存报错
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/df9e941d-e28e-45c8-89c3-13bfc7bb9fbc">

### Steps To Reproduce 重现步骤

代码加载的对象直接点击字段布局进行编辑

### Version 版本

2.6.2-beta.24

**Comment by Flyingliao** [comment]
有关联的issue：系统对象点击“自定义”按钮后“系统”字段的值没有改变 #6247

**Comment by Flyingliao** [comment]
最新版本 2.6.4-beta.6 正常，不会报错，进而不继续处理“设计字段布局”按钮。

**Comment by hotlong** [comment]
只有修改代码中的对象会有此错误。
