### ISSUE TITLE
[Bug]: 统计分析中仪表盘页面问题偶发性显示不出来

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6068]
### Description

![2](https://github.com/steedos/steedos-platform/assets/151509384/47dd3b9e-a3a5-406c-9013-be3dbd48c8ce)
![1](https://github.com/steedos/steedos-platform/assets/151509384/22ce84e7-2eb8-43e8-bdfc-0c16d9f7ae57)

### Steps To Reproduce 重现步骤

expense项目

### Version 版本

 2.6.2-beta.24

**Comment by baozhoutao** [comment]
报错原因是报表中依赖了`expense_advance_payment` 对象的 count字段. 但是对象定义上找不到.
![image](https://github.com/steedos/steedos-platform/assets/6194462/9da7cc92-f690-48de-bec2-e8f54bea9797)

**Comment by lizheng-steedos** [comment]
这个count是问题上配置的行数而不是对象定义的字段；
<img width="926" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/7ba01834-85d3-46be-8883-16c61fd55d7e">
