### ISSUE TITLE
[Feature]: 统计分析问题支持添加和显示自定义列

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6069]
目前可以添加但不能显示自定义列
### Description

![支付金额](https://github.com/steedos/steedos-platform/assets/151509384/2c5bbfe7-b2ba-4765-8375-6f560062b357)

### Steps To Reproduce 重现步骤

见图片

### Version 版本

0.1.1

**Comment by hotlong** [comment]
目前不支持自定义列

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/5926
