### ISSUE TITLE
[Bug]: 编辑记录表单中变更主子表字段值，会自动把多行文本类型字段值清空

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6075]
### Description

- amis 3.2和3.6都有此问题
- 如果是变更lookup字段类型没有这个问题

![image](https://github.com/steedos/steedos-platform/assets/6219465/3ab0572a-ee00-4300-a53b-7403ea57f03e)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.2.beta.x

**Comment by Flyingliao** [comment]
原因：主-子表字段配置了autofill。 不是bug。
<img width="400" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/f11ef815-9197-4edf-b1f3-08d4786630e6">
