### ISSUE TITLE
[Bug]: amis 3.6 页面布局设置界面的字段列表显示了两个滚动条

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6081]
### Description

amis 3.2没有这个问题
![image](https://github.com/steedos/steedos-platform/assets/6219465/0f9ed1df-1155-4537-a3ff-d8d9e0b47cdd)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.2.beta.x

**Comment by hotlong** [comment]
这个控件还没换吧？
