### ISSUE TITLE
[Bug]: 字段权限列表页乱了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6083]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/83be83d2-752e-4c18-9fdf-2cc506922b10">

### Steps To Reproduce 重现步骤

amis 3.6

### Version 版本

amis 3.6

**Comment by Flyingliao** [comment]
platform版本： 2.6.2-beta.32
<img width="759" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/0762e07d-ad1f-4df7-b740-b514fb5342ce">
