### ISSUE TITLE
[Feature]: steedos cli插件支持对象验证规则类型元数据同步

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6088]
### Summary 摘要

<img width="541" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/aca4c7fa-02d5-4716-8100-2a5308b53ed0">

### Why should this be worked on? 此需求的应用场景？

业务需要，页面配置对象验证规则后，没有办法同步到代码

**Comment by baozhoutao** [comment]
对象验证规则在对象文件夹下, 同步对象即可.
![image](https://github.com/steedos/steedos-platform/assets/6194462/9e9d21ff-fcb0-4787-9898-e0a4e098f6a3)
