### ISSUE TITLE
[Bug]: 树形结构列表视图自动展开功能效果失效了

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#6098]
### Description

相关issue改动：
1、[对象启用树状结构显示时，默认展开第一层](https://github.com/steedos/steedos-platform/issues/5886)
2、[只有树没展开的时候才需要默认展开，否则刷新按钮点击后可能让树折叠起来](https://github.com/steedos/steedos-platform/issues/5920)

### Steps To Reproduce 重现步骤

设置 => 部门

<img width="491" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/948b2e1e-dba0-48da-bc24-55d4ffc2832b">

### Version 版本

2.6.2-beta.28

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/39eeb929-a0f3-4b50-be2c-5ac26d7e37c1)
