### ISSUE TITLE
[Bug]: 数据导入：导入多选字段时出错

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6101]
### Description

数据导入多选字段报错。数据字段。
<img width="1141" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/a59824d1-f5fc-4abb-bbef-1c9b3f6bb6e5">

### Steps To Reproduce 重现步骤

1、新建对象字段、对象字段设置为多选。
2、excel中数据格式如图。多选字段值使用，隔开
<img width="738" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/60fa3a2b-3aa1-458b-9d56-58ba09cbeee2">

### Version 版本

2.6.2-beta.26

**Comment by sujiahao66** [comment]
导入后消息提示错误：导入21条，成功20条、0条
![image](https://github.com/steedos/steedos-platform/assets/126655403/6a57aadb-32ad-472f-9248-7692b843d088)

**Comment by sujiahao66** [comment]
建议优化错误信息显示。错误信息很难查看。
<img width="831" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/e71dc14c-9236-4989-ad13-dc4afd33f092">

**Comment by sunhaolin** [comment]
选项使用分号(;)隔开
