### ISSUE TITLE
[Bug]: amis 3.6应用程序-设置选项卡列表列高太低导致文字重叠

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6102]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/b7761cdf-9882-4694-9585-af79976dc2f1">

### Steps To Reproduce 重现步骤

后台应用程序-设置选项卡

### Version 版本

2.6.2-beta.28/amis3.6

**Comment by tujiajun** [comment]
该bug未重现(2.6.2-beta.31)
![image](https://github.com/steedos/steedos-platform/assets/127007861/20128db4-4e8f-492a-a9a9-517982d510cf)
