### ISSUE TITLE
[Bug]: amis 3.6应用程序设置完选项卡后，列表上选项卡的值不显示

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6103]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/b20e8ae8-ff75-496b-9180-4ee78618ba22">

### Steps To Reproduce 重现步骤

见图片

### Version 版本

2.6.2-beta.28/amis3.6

**Comment by Flyingliao** [comment]
遗留问题：新建分组后不能立马给选项卡设置新建的分组。 原因：input-table单行编辑作用域中的值是旧的，暂时没有好的解决办法。
