### ISSUE TITLE
[Feature]: lookup类型的列表视图中配置了过滤条件，目前没有生效

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6114]
### Summary 摘要

1、用户自建了api为lookup的列表视图，并配置了过滤条件
![565145856be75b9ac0968989278e846](https://github.com/steedos/steedos-platform/assets/15027092/5c81f185-b315-40bd-82a0-2f42aaf59857)

![ab14b9688fee033e92a6f4bc6f02164](https://github.com/steedos/steedos-platform/assets/15027092/90c9b6c5-7d83-4113-b729-65c36a69cfa2)

2、过滤条件并没有生效
![image](https://github.com/steedos/steedos-platform/assets/15027092/01ff79ca-3450-4fc0-808e-7affb306c176)

### Why should this be worked on? 此需求的应用场景？

实现在弹窗页面，按条件过滤显示数据

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/6239
