### ISSUE TITLE
[Bug]: 控制台中私有部署 复制激活参数按钮没有反应

### ISSUE THREAD

**Issue by rttmoa** [steedos/steedos-platform#6121]
### Description

![81b0f8ba9931c74c31c63e647a3584e](https://github.com/steedos/steedos-platform/assets/105489435/264189d7-f85a-40c0-9b4f-eb04864b3b68)

### Steps To Reproduce 重现步骤

console.steedos.cn 网站中控制台中私有部署 复制激活参数按钮没有反应  

### Version 版本

console.steedos.cn

**Comment by rttmoa** [comment]
![image](https://github.com/steedos/steedos-platform/assets/105489435/cb230d8a-586d-4db8-bab9-6eb6aa7d0a1b)
点击按钮请求失败

**Comment by rttmoa** [comment]
@hotlong  点击按钮报这个错误：Uncaught TypeError: First argument must be a String, HTMLElement, HTMLCollection, or NodeList， 请问修复这个问题需要多久呀

**Comment by rttmoa** [comment]
@hotlong  你好！点击按钮报这个错误：Uncaught TypeError: First argument must be a String, HTMLElement, HTMLCollection, or NodeList， 请问修复这个问题需要多久呀

**Comment by rttmoa** [comment]
@hotlong    使用 clipboard 插件 出现错误，原因是svg 不属于HTMLElement  无法传入 cliboard实例中
解决 ：给设置  pointer-events: none; 静止该元素接受鼠标事件, 之后点击图标不在获取svg  而是获取 它的上一层

**Comment by hotlong** [comment]
2.5版本开始，不需要控制台复制激活参数。

**Comment by rttmoa** [comment]
那这个问题还解决吗

**Comment by rttmoa** [comment]
@hotlong  打扰一下，2.5版本开始，不需要控制台复制激活参数。 对于2.5版本以前的项目，如果需要重新部署项目，没有激活参数是无法部署的，这对老用户不太友好的！
