### ISSUE TITLE
[Bug]: 点击按钮dialog弹框对象表格，对象表格自动收缩高度

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6125]
### Description

初始点击
![image](https://github.com/steedos/steedos-platform/assets/129827462/7cd371ad-55cd-4402-9ce5-9387fe2460b2)
每隔一秒，对象表格高度逐渐变小
![image](https://github.com/steedos/steedos-platform/assets/129827462/330c474b-364c-4645-acb3-2cf9e6248007)
最后高度变成0
![image](https://github.com/steedos/steedos-platform/assets/129827462/9203f829-6ef1-47b6-bedb-8ea1971e56ce)

### Steps To Reproduce 重现步骤

1、新建按钮添加点击事件为弹窗
2、弹框内容为对象表格
- amis 版本
![image](https://github.com/steedos/steedos-platform/assets/129827462/7aff5214-daee-498a-aacb-0765fdce5283)
- widget版本
![image](https://github.com/steedos/steedos-platform/assets/129827462/9e8b076d-bc58-4265-b1f2-153dac5e5d20)

### Version 版本

 2.6.2-beta.30

**Comment by yinlianghui** [comment]
人员列表高度也会自动收起来，应该是一样的问题

**Comment by tujiajun** [comment]
dialog内的对象表格需要配置
```
"crud": {
  "autoFillHeight": false
}
```
