### ISSUE TITLE
[Bug]: 审批单：搜索中无法显示“审批王端禁止发起审批”的流程 

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6126]
### Description

![image](https://github.com/steedos/steedos-platform/assets/126655403/96197366-ed20-43cd-81a0-aa7c24853008)

### Steps To Reproduce 重现步骤

 审批单中无法显示“审批王端禁止发起审批”的流程

### Version 版本

2.6.2-beta.26

**Comment by hotlong** [comment]
审批王中无法发起，可以在台账中发起流程，这里应该可以搜索

**Comment by hotlong** [comment]
相关任务 https://github.com/steedos/steedos-platform/issues/5850
