### ISSUE TITLE
[Bug]: 流程管理员在监控箱选择流程后需有审批单导出功能

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6127]
### Description

目前版本没有审批单导出功能。
审批单导出后excel如图三。
<img width="1193" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/d10e5143-52cc-44e1-97bd-07ed789decd6">
<img width="1096" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/081a8291-b87d-4024-b209-5c16dbeaa784">
![image](https://github.com/steedos/steedos-platform/assets/126655403/9ff40ccf-bcfd-4c9e-b36d-f0ce18bc1cc8)

### Steps To Reproduce 重现步骤

目前版本没有审批单导出功能。

### Version 版本

2.6.2-beta.26

**Comment by hotlong** [comment]
申请单可以放开导出功能吗？会不会有权限问题。
