### ISSUE TITLE
[Task]: 应支持重写 admin.app.yml, 例如saas版，部分菜单应隐藏

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6139]
### SubTasks 子任务

- 开发
- 批准过程
- 审批王

**Comment by hotlong** [comment]
目前微服务方式运行不支持，插件方式运行支持。

**Comment by hotlong** [comment]
QHD项目支持，应该是直接把 admin.app.yml 打包到平台中了

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/d57d8eae-217c-43c1-b39c-6d1781ff9015)

使用元数据合并规则即可实现.

将tab_items 下的 特定项 设置为 `null` 即可隐藏菜单.

无需开发且支持多节点.

**Comment by hotlong** [comment]
这个方案不是最好，暂时可以用。
改一下费控王 ，隐藏相关菜单。

**Comment by hotlong** [comment]
按照这个任务，继承选项卡，并配置为 hidden ，是不是更好。
https://github.com/steedos/steedos-platform/issues/6248

**Comment by hotlong** [comment]
可以在 费控王的 saas 软件包中开发
