### ISSUE TITLE
改善 docker 运行模式，提供官方docker版本供pull

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#614]
并完善文档以及可直接运行的 docker-compose.yml 文件。

具体参考：https://github.com/RocketChat/Rocket.Chat#docker

**Comment by sunhaolin** [comment]
文档： https://github.com/steedos/steedos-website/blob/85d21009e15a21a746790bee81f584b77071d388/docs/developer/deploy_docker.md
docker-compose.yml: https://github.com/steedos/steedos-project-oa/blob/master/docker-compose.yml
