### ISSUE TITLE
[Feature]: 字段分组支持配置默认折叠

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6140]
### Summary 摘要

- 后台配置时支持配置默认折叠
- 前台显示时默认折叠
- 系统信息分组默认折叠

### Why should this be worked on? 此需求的应用场景？

系统信息等分组默认可以折叠

**Comment by tujiajun** [comment]
[Bug]: 新建页面布局与字段设计布局中设置分组时系统信息分组的默认折叠属性未选中 #6458
