### ISSUE TITLE
[Bug]: lookup字段配置过滤规则时，弹出选择时应该隐藏“新建按钮”

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6143]
-  lookup字段配置过滤规则时，新建不符合过滤规则的记录，显示异常

### Description

![image](https://github.com/steedos/steedos-platform/assets/129827462/07028d1d-b855-4cbc-a796-a6d3122fd40e)

- 新建一个审批状态不为已核准的记录，点击确认
![image](https://github.com/steedos/steedos-platform/assets/129827462/4fc3a633-81cc-4122-bfac-4a7ad29acf03)
![image](https://github.com/steedos/steedos-platform/assets/129827462/bf104851-e40e-4bec-937c-17d3ed750939)

- 预期的效果
 新建的记录，若不符合过滤规则，也不在新建或编辑页显示该记录

- 关联任务
 https://github.com/steedos-labs/feikongwang/issues/46

### Steps To Reproduce 重现步骤

1. 对象lookup字段，设置过滤规则
2. 新建或编辑该对象
3. looup字段新建不符合过滤规则的记录
4. 点击确认

### Version 版本

 2.6.2-beta.30

**Comment by Flyingliao** [comment]
lookup字段配置了filters或filtersFunction时，强制把弹出窗口的新建按钮去掉 https://github.com/steedos/steedos-widgets/issues/499
