### ISSUE TITLE
[Bug]: 新建页面布局时，按钮字段出现异常

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#6145]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/ef2ef63e-214d-42ea-8b6b-4576f3d04241)

### Steps To Reproduce 重现步骤

1、进入任意对象详细页
2、点击新建页面布局

### Version 版本

2.6.2-beta.33

**Comment by hotlong** [comment]
grid换新版table控件
