### ISSUE TITLE
[Feature]: 使用开关控制是否显示千分位分隔符

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6146]
### Summary 摘要

例如现在一个年份的字段，也显示 2,024

简道云
<img width="176" alt="企业微信截图_56a49b81-7a59-4086-af2f-daae8e3bcdaa" src="https://github.com/steedos/steedos-platform/assets/50353452/5803c61d-d2e2-40ba-8f84-8eff0ba83c97">

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by tujiajun** [comment]
增加属性 disable_thousands，勾选为true，可实现不显示千分位分隔符

**Comment by tujiajun** [comment]
数值，金额，百分比三个字段类型存在该开关
当前需要等待默认值问题解决后，将该属性改为显示千分位分隔符
