### ISSUE TITLE
[Bug]: Amis 3.6 对象列表加载很慢

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6147]
### Description

54个对象，刷新后卡住15秒左右才出列表
![image](https://github.com/steedos/steedos-platform/assets/15027092/f4478809-2758-4e96-9571-c5b476aa078d)

### Steps To Reproduce 重现步骤

新开feikongwang测试环境，后台进入对象列表，刷新就能还原

### Version 版本

2.6.2-beta.32

**Comment by hotlong** [comment]
我记得这个问题解决了

**Comment by chenzhipei** [comment]
项目中环境变量默认指定了amis版本，注释掉后使用默认的amis版本，对象加载快很多
