### ISSUE TITLE
[Feature]: 手机端支持配置字段的amis属性上的classname

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6151]
### Summary 摘要

目前name字段上配置的className只会在PC上的名称列上生效，手机端不生效的话，要实现相关功能要单独写接收适配器不方便。
![image](https://github.com/steedos/steedos-platform/assets/6219465/d50d3736-4edb-4410-9e87-7362968172de)

### Why should this be worked on? 此需求的应用场景？

审批王手机端显示“紧急”等状态颜色

**Comment by tujiajun** [comment]
从这个issue之后，字段的amis属性上配置的classname会同时影响手机，如果希望只影响pc，在写样式时需要自行做判断，同时pc与手机端的classname都将采用合并的方式
