### ISSUE TITLE
[Bug]: 数据导入界面显示错误

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6152]
### Description

<img width="1305" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/abfdad4b-00c7-4403-b37a-1d5157ef1782">

### Steps To Reproduce 重现步骤

查看数据导入即可重现。

### Version 版本

2.6.2-beta.34

**Comment by Flyingliao** [comment]
重复：新建页面布局时，按钮字段出现异常 #6145
