### ISSUE TITLE
[Bug]: 审批中心-申请单列表页标题没有换行

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6153]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/8f16ced9-16cf-4b81-be35-cbd1abdcf37c)

### Steps To Reproduce 重现步骤

审批中心-文件标题过长的申请单

### Version 版本

2.6

**Comment by Flyingliao** [comment]
当字段上配置了className,会覆盖列表视图上系统默认配置的className。
如果想保持系统默认配置的className，那就在字段上补充className。
<img width="367" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/6d890a24-8ffe-443a-b578-f45dd5da090a">

<img width="567" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/c351cdf8-738e-4d74-8de5-7ad82a5d1fc1">
