### ISSUE TITLE
[Bug]: 列表数据多的时候有翻页，点击翻页后滚动条没有复位

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6158]
### Description

如题，比如审批列表

### Steps To Reproduce 重现步骤

- 进入审批列表
- 滚动条滚动到底部
- 点击底部翻页页码（翻到的页面数据要多，要能显示滚动条），发现滚动条没有复位，而是保持在底部

### Version 版本

2.6.2.beta.x

**Comment by Flyingliao** [comment]
amis相关issue： crud 的 autoJumpToTopOnPagerChange 属性 和 autoFillHeight 属性一起使用设置为true 时， autoJumpToTopOnPagerChange 属性功能不生效，这个能否支持下？ [#9388](https://github.com/baidu/amis/issues/9388)
