### ISSUE TITLE
[Bug]: 累计汇总金额类型字段，审批单该字段显示%

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6161]
### Description

![image](https://github.com/steedos/steedos-platform/assets/129827462/e4c04f09-77d6-419e-b423-bae4ddbd10e6)
以发票金额为例
- 发票金额字段设置
![image](https://github.com/steedos/steedos-platform/assets/129827462/358f9a8f-6f42-40bd-a3bd-7537b0ed1fc2)
- 要汇总的对象字段
![image](https://github.com/steedos/steedos-platform/assets/129827462/8117f2a0-a027-4b5b-bbc7-d61bf4bde3ff)
- 数据库展示
![image](https://github.com/steedos/steedos-platform/assets/129827462/27470429-27d7-43fe-b4ee-d7506689109b)

### Steps To Reproduce 重现步骤

1. 配置如图两个对象字段
2. 新建流程
3. 发起审批

### Version 版本

 2.6.2-beta.35

**Comment by wangyanwa** [comment]
2.6.4-beta.7 版本验证报销模块中问题仍然存在，reopen
![image](https://github.com/steedos/steedos-platform/assets/92509428/9f712a94-093c-462b-a413-8118906f8eb7)
