### ISSUE TITLE
[Bug]: 列表视图，某字段配置宽度没有生效

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6162]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/d2d7f0f5-0bfa-4ef6-938b-e476517ab9ca)

![image](https://github.com/steedos/steedos-platform/assets/15027092/50503249-43c7-447b-906e-eb2ba4ba6b8b)

### Steps To Reproduce 重现步骤

新部署的feikongwang项目
1、选择差旅申请对象
2、自定义all列表视图
3、配置业务目的宽度并设置换行，没有生效，去掉换行按钮后，宽度也没有生效

### Version 版本

2.6.2-beta.35

**Comment by tujiajun** [comment]
未重现该问题
![image](https://github.com/steedos/steedos-platform/assets/127007861/bc6ea30e-77f8-4bda-bd8a-612fe935813d)
![image](https://github.com/steedos/steedos-platform/assets/127007861/bbb2e7e8-cdf0-4c70-879f-e53e9f982437)

**Comment by tujiajun** [comment]
[Bug]: 对象表格上的单元格配置不换行时，宽度超出显示省略号的样式失效 #6193
