### ISSUE TITLE
[Bug]: 手机端：审批单下拉框实现分组显示和功能

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6163]
### Description

审批单是之前老的审批单，相关表字段是之前的Odata类型字段。
目前电脑端可以搜索，手机端无法搜索。
![image](https://github.com/steedos/steedos-platform/assets/126655403/9c6812d1-14b2-45b3-9cb8-970ab06995aa)
![image](https://github.com/steedos/steedos-platform/assets/126655403/4a1654cf-6a77-4ef9-9c86-a6ffc4a1d1bb)

### Steps To Reproduce 重现步骤

重现过程如上

### Version 版本

2.6.2-beta.34

**Comment by hotlong** [comment]
审批单中的odata有可能换 lookup 字段吗？换起来方便吗？

**Comment by sujiahao66** [comment]
用lookup字段没有分组效果

**Comment by hotlong** [comment]
把车辆分组配置成默认的搜索条件

**Comment by hotlong** [comment]
如果用 amis 重写这个字段的定义，实现下拉分组的效果不知道行不行。 
https://aisuda.bce.baidu.com/amis/zh-CN/components/form/select#%E5%88%86%E7%BB%84%E5%B1%95%E7%A4%BA%E6%A8%A1%E5%BC%8F
