### ISSUE TITLE
[Bug]: 统计分析-问题上设置的样式添加到仪表盘后不生效

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6167]
### Description

![问题样式设置](https://github.com/steedos/steedos-platform/assets/151509384/ecfdb9f4-4e4a-4929-a5e8-136b7e189365)

### Steps To Reproduce 重现步骤

现在的问题在于设置完一些内容后，添加到看板不生效。在看板上单独对这个组件设置，但是有些属性看板上又设置不了

- 创建问题，设置样式
- 添加到仪表盘，仪表盘中看不到对应的样式。

### Version 版本

2.6.2-beta.35

**Comment by hotlong** [comment]
这应该是 metabase 的限制，暂时不处理
