### ISSUE TITLE
[Bug]: 编辑选项卡，删除指定选项卡，显示还是存在，点击确认后，实际已删除

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6170]
### Description

指定删除发票选项卡
![image](https://github.com/steedos/steedos-platform/assets/15027092/35de32fd-617c-4b36-9d60-929e0b66fbbb)

点击删除后，还是显示发票选项卡
![image](https://github.com/steedos/steedos-platform/assets/15027092/d3e36d3b-33ad-43f6-80c5-962f86338ae1)

实际已经删除，保存后再次编辑显示是正常的
![image](https://github.com/steedos/steedos-platform/assets/15027092/d9b6a602-042e-4656-89e0-5019a3ac2253)

### Steps To Reproduce 重现步骤

1、编辑选项卡，执行删除“发票”
2、前台显示的是删除了最后一个选项卡
3、点击确认后实际已经删除指定的选项卡

### Version 版本

2.6.2-beta.35

**Comment by hotlong** [comment]
直接换 table 控件调试

**Comment by tujiajun** [comment]
未重现，点击删除后正常删除
