### ISSUE TITLE
[Bug]: “申请单审批状态”字段，不应该直接修改该字段的值，内核应该配置为 readonly

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#6172]
现在在记录详情页控制了隐藏，但是在列表页如果加上此字段可以快速编辑。

### Description

![image](https://github.com/steedos/steedos-platform/assets/7553007/e96a75cc-1694-4194-9d9f-f8908afeb05e)
该值应由  审批流程自动修改、不应允许手动修改

### Steps To Reproduce 重现步骤

列表视图增加显示字段“申请单审批状态”（instance_state）；
列表视图显示时，即可修改此字段

### Version 版本

2.6.2-beta.32

**Comment by hotlong** [comment]
需要将此字段配置为只读
