### ISSUE TITLE
[Bug]: 关闭saas，关闭steedos id登陆后，登陆地址一直跳来跳去

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6176]
### Description

- STEEDOS_TENANT_PAGE_LOGIN=/api/global/auth/oidc/config
- STEEDOS_TENANT_PAGE_LOGOUT=/api/global/auth/oidc/logout

这两个参数应该是STEEDOS_IDENTITY_OIDC_ENABLED=true才会生效；
目前解决办法是去掉跳转地址的两个参数后，页面可正常登陆
![登陆问题](https://github.com/steedos/steedos-platform/assets/151509384/650f31b5-abd5-4878-9733-40db96e3962a)

### Steps To Reproduce 重现步骤

feikngwang项目，关闭steedos id登陆功能，重启服务后，无痕窗口登陆

### Version 版本

 2.6.2-beta.35

**Comment by hotlong** [comment]
这两个参数就是为了saas 设计的
