### ISSUE TITLE
[Bug]: 仪表盘-微页面模式下，用户页面鼠标移动到数据上看不到详情数据

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6182]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e9abac5b-4da0-4daa-8620-571b902c774b">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e5f486ef-7b13-43dd-bf24-4dd12df163c1">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.6.2-beta.36

**Comment by hotlong** [comment]
替换为 embed url：/analytics/embed/dashboard/659dff7e58bef705bed40b25
