### ISSUE TITLE
[Bug]: 代码加载的微页面，点击“自定义”写到库里，页面一直加载且报错

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6183]
### Description

webpack-f87b3bddad51e126.js:1 
        
        
       GET https://builder.steedos.cn/_next/static/chunks/ec4f813d.a856a76d0d9bada8.js net::ERR_ABORTED 504 (Gateway Timeout)

webpack-f87b3bddad51e126.js:1 Uncaught (in promise) ChunkLoadError: Loading chunk 6632 failed.
(error: https://builder.steedos.cn/_next/static/chunks/ec4f813d.a856a76d0d9bada8.js)
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/22760cf2-e2e3-42d4-a52c-2f56f7c4d6d9">

### Steps To Reproduce 重现步骤

feikongwang项目

### Version 版本

2.6.2-beta.36

**Comment by hotlong** [comment]
这个确实像是网络问题，关掉智能上网试试

**Comment by chenzhipei** [comment]
已配置缓存为一周
