### ISSUE TITLE
[Bug]: 流程分类列表编辑序号字段后，保存报错“Uncaught (in promise) Error: custom 动作执行失败，原因：categories is not defined”

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6184]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/ee674ea3-16cc-45e6-b5db-f2a3635b7b30">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.6.2-beta.36

**Comment by tujiajun** [comment]
该问题在最新版已解决
[Bug]: 列表页使用批量编辑功能，控制台报错 #6185
