### ISSUE TITLE
[Bug]: 流程转发报错“分发失败”

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6190]
### Description

审批单界面上点击转发按钮后报错
![image](https://github.com/steedos/steedos-platform/assets/126655403/b12f0045-c763-4bc1-9241-1791ef1a313b)

### Steps To Reproduce 重现步骤

审批单界面上点击转发按钮后报错

### Version 版本

2.6.2-beta.34

**Comment by sunhaolin** [comment]
- [ ] 分发
- [ ] 转发
