### ISSUE TITLE
[Bug]: 审批王的审批过程中，下一节点为条件判断时，仍需指定处理人

### ISSUE THREAD

**Issue by YohanWangyb** [steedos/steedos-platform#6192]
### Description

审批王的审批过程中，下一节点为条件判断时，当前的审核操作仍需指定处理人，但无法选择人员，流程被阻断。

### Steps To Reproduce 重现步骤

配置条件节点，设定完成条件后，工单流转至”审批“时，可驳回但无法选择处理进行后一步。

![1704877815466](https://github.com/steedos/steedos-platform/assets/105541752/213f453d-c508-404e-90bb-8bad50cef2a2)

![1704877775550](https://github.com/steedos/steedos-platform/assets/105541752/ca3646e8-64cd-44a6-8ee7-731b91d060e3)

![image](https://github.com/steedos/steedos-platform/assets/105541752/3e456bc2-8ae8-4ff2-8ccb-d92fd36a4daa)

### Version 版本

2.6.3

**Comment by hotlong** [comment]
应该是流程条件配置的有问题，选择下一步处理人之前，应该先选择下一步，界面上看下一步选项为空，应该是没有找到符合条件判断的下一步。
