### ISSUE TITLE
[Bug]: 列表页单条记录编辑报错

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6196]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/f202973f-998c-4cfd-aee3-5cf55624ef64">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.6.3

**Comment by tujiajun** [comment]
重复，该问题在最新版已解决
[Bug]: 列表页使用批量编辑功能，控制台报错 #6185
