### ISSUE TITLE
[Bug]: 列表字段宽度没办法手动拖动

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6197]
### Description

列表视图字段没有配置宽度属性

### Steps To Reproduce 重现步骤

可以平台页面创建一个新的对象、字段、列表视图预览查看

### Version 版本

2.6.3

**Comment by tujiajun** [comment]
经过排查，是由于隐藏的_display列造成，需要考虑新方案：考虑在_index列中将name更改为_display，而tpl更改为"${_index}"，这样可以实现通过setvalue更改_display的同时，不影响序号列的显示，需要注意的是树结构列表由于没有序号列，可能需要重新放入序号列，这可能会导致树结构列表显示一列空白列，是否采用或者更好的方案还需要经过讨论
