### ISSUE TITLE
[Bug]: 转发流程，提交时提示“分发失败”

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6198]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/69a8625a-7616-41bb-a597-94a744b51156">

### Steps To Reproduce 重现步骤

关联任务：
- https://github.com/steedos-labs/feikongwang/issues/87

### Version 版本

 2.6.3

**Comment by hotlong** [comment]
重复https://github.com/steedos/steedos-platform/issues/6190
