### ISSUE TITLE
[Bug]: 日期时间类型字段存储时多了毫秒数

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6199]
### Description

- 选择年-月-日 时：分
![image](https://github.com/steedos/steedos-platform/assets/129827462/41eb54e6-a7a1-405a-9f10-3402250ace8a)

- 服务端接收时间（自带了秒、毫秒），而且每一次秒数都不一样
- 正常效果时，选择年-月-日 时：分。秒、毫秒应该默认为00
![image](https://github.com/steedos/steedos-platform/assets/129827462/ab93fa00-abd9-4f2d-b111-c5846799eca5)

### Steps To Reproduce 重现步骤

1、日期时间类型字段
2、选择时间
3、查看数据库存储该字段的日期

### Version 版本

 2.6.2-beta.30

**Comment by Flyingliao** [comment]
"format": "YYYY-MM-DDTHH:mm:00:00.000Z" 格式不支持，
"format": "YYYY-MM-DDTHH:mm:00.000Z" 格式支持。
