### ISSUE TITLE
示例项目代码合并

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#620]
目前销售管理和合同管理模块分散在 platform，saas，oa，等很多项目中，统一把最新的代码合并到销售管理，并发布为插件，在其他项目中引用。

CRM 销售管理
steedos/steedos-app-sales

CRM 合同管理
steedos/steedos-contracts-app

**Comment by sunhaolin** [comment]
CRM 销售管理  steedos/steedos-app-sales， npm包：@steedos/steedos-crm-app@1.2.0开始发布为插件
CRM 合同管理 steedos/steedos-contracts-app，npm包：@steedos/app-contracts@1.22.0开始发布为插件
