### ISSUE TITLE
[Bug]: 台账界面点击编辑按钮，autofill填充出的表单字段值缺失。

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6200]
### Description

“地块名称”字段配置了autofill，填充“总项目名称”字段，新建时，autofill失败不会填充“总项目名称”，编辑时“总项目名称”字段为空。
widgets版本@3.6.0-beta.9是好的，@3.6.0-beta.10之后是坏的。
<img width="1187" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/d3fec9ac-2d44-4756-9982-dd13e014c5a9">

### Steps To Reproduce 重现步骤

lookup字段配置autofill属性即可重现。配置了autofill的lookup字段和autofill填充的字段都启用窗口模式，lookup字段reference_to的对象是树结构。
<img width="1128" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/3baf248b-2dd4-4e79-b1b9-b2982e4f575c">

### Version 版本

2.6.4-beta.1

**Comment by yinlianghui** [comment]
项目中还原版本号识别到beta.9是好的，beta.10是坏的
<img width="1221" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/d951fff4-8aa4-4913-845b-f471c6dbbc1b">
