### ISSUE TITLE
[Bug]: 新建记录进入记录详情页，未能立刻显示“发起审批按钮”，需要刷新才显示

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6204]
### Description

如题

### Steps To Reproduce 重现步骤

费控王
差旅申请
新建

### Version 版本

2.6.3

**Comment by hotlong** [comment]
有时候能遇到，有时候是好的

**Comment by lizheng-steedos** [comment]
2.6.4-beta.13版本
- 刷新前后：
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/1b5cdd06-ae35-4940-bff8-30182e921d52">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/99a9478d-dfac-40e0-bbcf-5ffafc776d9b">

**Comment by baozhoutao** [comment]
问题原因: 新建完工作区后, 初始化数据还未导入完成, 已经进入了系统, 此时`object_workflows`是进入系统的时候就加载的,此时数据是不全的. 刷新即可.
