### ISSUE TITLE
[Bug]: 列表视图配置的排序字段，如果不在列表视图的字段清单中，未能生效

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6208]
### Description

比如创建时间，不希望显示在列表视图上，又要排序

### Steps To Reproduce 重现步骤

创建列表视图，
设置按创建时间倒序排列

### Version 版本

2.6.3

**Comment by Flyingliao** [comment]
amis: 2.6.4-beta.4.  版本正常
