### ISSUE TITLE
[Feature]: lookup弹框页面，如果对应字段有配置“提示文本”，增加小标题显示

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6210]
### Summary 摘要

![image](https://github.com/steedos/steedos-platform/assets/151509384/2bc9c173-9715-4ef2-b5dd-39b9bf02412b)

### Why should this be worked on? 此需求的应用场景？

业务需要

**Comment by Flyingliao** [comment]
lookup.js 代码中添加 pickerSchema.title = field.inlineHelpText; 
<img width="1099" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/681c2fa6-bc11-4055-84ae-d67f7a766606">
