### ISSUE TITLE
[Bug]: 台账相关表中的lookup字段在列表页显示id

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6216]
### Description

lookup字段在列表页显示为了id，详情页和列表页快速编辑时是正确的
![image](https://github.com/steedos/steedos-platform/assets/126655403/7381d855-fa43-43fe-81e5-4382bec2e672)
<img width="1313" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/72c31c86-b345-4e60-8bce-fb307628aa82">

### Steps To Reproduce 重现步骤

不确定具体重现规则，目前发现只有“相对方联系人”字段显示为了id

### Version 版本

2.6.4-beta.2

**Comment by Flyingliao** [comment]
原因：该字段是lookup字段，且配置了 is_name: true。 规则不支持。
<img width="1105" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/07b1b91b-0002-4a50-8135-d1846bef126e">
