### ISSUE TITLE
[Bug]: keyvalues的数值在流程修改绑定app时会出现错误

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#6219]
### Description

项目应用上有badge，但是总数上没有，并且项目应用上无法清除
![image](https://github.com/steedos/steedos-platform/assets/127007861/311fd831-639e-4175-9ed1-cacfb29f76cc)

### Steps To Reproduce 重现步骤

1、新建流程分类，所属应用可以选择项目
2、新建流程，并绑定对象为项目
3、在项目对象中从一条记录中发起审批，可以发给自己
4、将流程分类的所属应用清空或选择其他应用
5、将刚刚那条审批处理掉即可发现项目应用上的badge始终存在

### Version 版本

2.6.4-beta.1

**Comment by hotlong** [comment]
这种开发类的问题暂时不处理

**Comment by hotlong** [comment]
这个通常是开发阶段的问题，不处理
