### ISSUE TITLE
[Bug]: lookup字段(L1)使用autoFill给其他lookup字段(L2)赋值后, 修改L2字段值后,再次打开编辑窗口L2字段值被重置（amis已修复）

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6221]
### Description

如题

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6

**Comment by yinlianghui** [comment]
关联amis issue: https://github.com/baidu/amis/issues/9391

**Comment by hotlong** [comment]
amis 已经修正了

**Comment by yinlianghui** [comment]
已把以下amis官方相关提交抄到我们steedos amis项目中了：
- 把 https://github.com/2betop/amis/commit/8acdeb0dcca4e31a7d8af13a3fa31036ca7ac0b1 抄写到项目中了，提交见：https://github.com/steedos/steedos-amis/commit/3d6acb7e3bcab4c7964d45c960039cdc974e5a8d  关联amis issue: https://github.com/baidu/amis/issues/9391
- 把 https://github.com/baidu/amis/pull/9547/commits/8acdeb0dcca4e31a7d8af13a3fa31036ca7ac0b1 抄写到项目中了，提交见： https://github.com/steedos/steedos-amis/commit/884e6c069e007eb338f565541a56ad6306e4bcb7 关联amis issue: https://github.com/baidu/amis/issues/9631

但是最后把sdk引用到platform后，相关功能还是坏的，经调式是amis还没改干净，另外给amis官网建了bug：https://github.com/baidu/amis/issues/9733 

等他们修正后再跟进此问题。

**Comment by yinlianghui** [comment]
关于抄 amis issue: https://github.com/baidu/amis/issues/9391 是抄的合并前的PR提交，即
https://github.com/2betop/amis/commit/c03f026fb20bef3d40075970df61d94b8c80acbe
他们后来把这个PR合并到主分支了，即：
https://github.com/baidu/amis/commit/09fa406ca024d3bebb012ddf5957f933603376fd
后续应该按该issue中提交合并到他们主分支后的提交再改一次，以防止后续我们从他们主分支代码同步代码时会冲突。

**Comment by yinlianghui** [comment]
又新发现lookup字段配置为下拉模式的时候，autoFill还是有此问题，也另外给官网报过bug了：https://github.com/baidu/amis/issues/9742

昨天给他们报的bug他们也还没有修正：https://github.com/baidu/amis/issues/9733 

等他们把这两个bug都修正后再跟进此问题。

**Comment by yinlianghui** [comment]
> 关于抄 amis issue: [baidu/amis#9631](https://github.com/baidu/amis/issues/9631) 是抄的合并前的PR提交，即 [2betop/amis@c03f026](https://github.com/2betop/amis/commit/c03f026fb20bef3d40075970df61d94b8c80acbe) 他们后来把这个PR合并到主分支了，即： [baidu/amis@09fa406](https://github.com/baidu/amis/commit/09fa406ca024d3bebb012ddf5957f933603376fd) 后续应该按该issue中提交合并到他们主分支后的提交再改一次，以防止后续我们从他们主分支代码同步代码时会冲突（对比了下，两次提交区别只有前面几行，其它的是一样的）。

这个非常重要，PR和合并到主分支后的代码还是有区别的，后续其他autoFill功能相关issue依赖了这次合并到主分支提交的代码，如果不进一步抄下合并后的代码而直接抄后续issue上的提交会出问题。已处理，提交见：如果不进一步抄下合并后的代码，
