### ISSUE TITLE
[Bug]: 任意用户可以使用X-Space-id和X-Auth-Token登录漏洞（高危）

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6224]
### Description

1、初次登录首页后url会直接拼接相关认证凭证X-Space-id和X-Auth-Token，利用此url可在任意地方进行登录且无需账号密码认证。

### Steps To Reproduce 重现步骤

1、用户首次登录平台，（没有网站cookie情况下）使用用户名、密码登录
2、登录成功后，系统进入首页时，中奖会弹出下图带有 X-Space-Id，X-Auth-Token，X-User-Id的url

![image](https://github.com/steedos/steedos-platform/assets/25192306/e7a12130-184a-45ac-b093-38c32ea05dd9)

3、获取到此链接地址后，任意人可以在其他浏览器、其他电脑上直接以 步骤1的用户身份进入系统

### Version 版本

2.5.*

**Comment by hotlong** [comment]
具体和韩老师沟通一下，需要的话通过环境变量控制是否开启全局SSO

**Comment by baozhoutao** [comment]
- [ ] 登录后跳转的url上不要自动加x-认证参数
- [ ] url上的x-认证参数也不要识别: 通过环境变量控制 `STEEDOS_ENABLE_QUERY_AUTH`

**Comment by baozhoutao** [comment]
STEEDOS_ENABLE_QUERY_AUTH 默认值为 false
