### ISSUE TITLE
[Bug]: 审批单转发时未勾选‘将原表单存储为附件’生成的新草稿仍生成了原表单附件

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#6226]
### Description

转发的‘将原表单存储为附件’开关未生效

### Steps To Reproduce 重现步骤

1. 审批单转发

### Version 版本

2.6.4-beta.3

**Comment by hotlong** [comment]
估计是这么设计的？这个开关的含义只是把表单存成附件？

**Comment by sunhaolin** [comment]
> 估计是这么设计的？这个开关的含义只是把表单存成附件？

勾选之后会将原表单存成html文件作为新草稿的附件
![image](https://github.com/steedos/steedos-platform/assets/6194896/f83a343e-c899-43ec-ab77-4ca113dfe7b9)
