### ISSUE TITLE
[Bug]: 编辑流程时，无法编辑流程脚本

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6231]
### Description

编辑流程时，编辑界面没有“脚本”这个选项，在只读界面显示了脚本选项。
![image](https://github.com/steedos/steedos-platform/assets/126655403/b6df6708-85cb-4c0f-b4fb-947077619cb7)
![image](https://github.com/steedos/steedos-platform/assets/126655403/122ffba6-8fe9-4609-af22-26decaf11f1a)

### Steps To Reproduce 重现步骤

在任意流程详情页点击编辑即可重现。

### Version 版本

2.6.4-beta.2

**Comment by hotlong** [comment]
可能被隐藏的，新增一个 开发的选项卡，加上流程脚本的编辑吧。
