### ISSUE TITLE
[Feature]: 主子表lock属性的联动锁定功能 

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6235]
### Summary 摘要

需求：主表在审批过程中禁止子表数据新增或修改；
方案调整：主表对象上增加开关控制“锁定子表enable_lock_detail”，当主表锁定时，所有子表只读;
效果：流程审批中、完成后，lock属性为true，相关配置的主子表/相关表不可新建，不能编辑记录。

### Why should this be worked on? 此需求的应用场景？

业务需要

**Comment by sunhaolin** [comment]
locked属性影响不了新建，待重新讨论

**Comment by sunhaolin** [comment]
开发方案： 
- [ ] 对象新增开关 “锁定子表enable_lock_detail” boolean类型，默认false
- [ ] 主表对象enable_lock_detail为true时，主表记录与子表(master_detail)记录的locked值始终保持一致(true/false)
- [ ] 在相关页，且主表对象enable_lock_detail为true，且主表记录已锁定(locked=true)时不显示子表新增按钮
