### ISSUE TITLE
[Bug]: 点击自定义的amis页面后，切换到其他页面，页面上显示竖线

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6240]
### Description

点击自定义的amis页面后，切换到其他页面（图片中切换到了流程页面上），页面上显示竖线，可能是此微页面中包含表格导致。
<img width="1224" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/852d3124-c5d1-407c-9e5c-c21f103335af">
<img width="1257" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/0ef0043b-6b65-4f6f-9092-14649eff8c90">

### Steps To Reproduce 重现步骤

1、新建微页面，微页面完成后，给微页面生成选项卡，并把选项卡显示在应用中。
2、点击此微页面选项卡后，切换到其他选项卡即可重现。

### Version 版本

2.6.4-beta.5

**Comment by hotlong** [comment]
应该是微页面中写了自定义样式，覆盖了全局样式

**Comment by hotlong** [comment]
微页面中的全局样式会互相干扰，不应该写全局样式
