### ISSUE TITLE
[Feature]: 微页面、选项卡元数据支持hidden属性

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6248]
### Summary 摘要

-  在列表页隐藏
- 选项卡不返回到前端，不会显示在应用程序启动器和应用菜单中。

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by hotlong** [comment]
判断只有 NODE_ENV=development 时隐藏

**Comment by sunhaolin** [comment]
- [ ] 保证改动不影响apiname唯一性校验
