### ISSUE TITLE
[Bug]: 列表编辑字段列宽问题导致高度一直跳来跳去

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6255]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/fcaa6d69-49c8-46e8-ab43-53cce45434d2">

### Steps To Reproduce 重现步骤

feikongwang项目报销单列表数据可以查看效果

### Version 版本

2.6.4-beta.7

**Comment by hotlong** [comment]
我调整过编辑按钮的位置，靠右对齐，可能是这个原因导致的。

**Comment by tujiajun** [comment]
amis3.6.3的columns配置宽度后td下不会再生成div，因此td下就直接为内容div与快速编辑的div了，而td的display为table-cell，不可设置flex，因此就更改不了元素的左右布局，而float：right无法使元素始终对齐
<img width="359" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/39de0b38-c1a3-43fb-830e-f727398950d9">
<img width="939" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/ee3c7c4c-6ae5-491a-9081-9ad7994575e3">
