### ISSUE TITLE
[Bug]: 详细页面样式异常: 标题吸顶异常

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6256]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194462/77d1f441-06b1-46e8-a106-0d21100bee88)

### Steps To Reproduce 重现步骤

记录详细页面

### Version 版本

2.6

**Comment by hotlong** [comment]
边距丢失, 子表左右边框线条丢失，是我在改
