### ISSUE TITLE
[Bug]: 禁用列表视图功能异常

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6258]
### Description

accounts对象存在一般供应商 、工程供应商、客户三个列表视图（均不是all视图）。
用户A有两个权限集（user和“禁止查看一般供应商“权限集），其中”禁止查看一般供应商“权限集中设置了禁止列表视图，禁用了“一般供应商”和“客户”视图，user权限集没有做其他特殊限制。
实际效果：用户A看到了所有的三个视图。理想效果：用户A只能看到“工程供应商”视图，看不到“一般供应商”视图和“客户”视图。
<img width="1064" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/971f5639-eb9a-4995-808f-dd0a8ce0a8d8">
<img width="1204" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/8a14d600-a6bd-41c1-9326-866724de87b1">
<img width="1252" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/c137f318-46b3-4e6c-a764-628cc1a67ebd">

### Steps To Reproduce 重现步骤

如上，多个权限集叠加时，禁用列表视图功能异常

### Version 版本

2.6.4-beta.2

**Comment by hotlong** [comment]
此功能即将作废，替换为 [Feature]: 编辑列表视图时，支持配置列表视图权限，例如共享给指定部门 #6150
