### ISSUE TITLE
[Bug]: 对象字段页面样式显示错误

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6271]
### Description

第一行少了横线
<img width="1406" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/8b85bbb1-27bc-4f63-9b82-b81daefd84ed">

### Steps To Reproduce 重现步骤

查看对象字段页面即可重现

### Version 版本

2.6.4-beta.10

**Comment by sujiahao66** [comment]
<img width="1417" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/72166c3b-95f8-46f2-b477-cb392ec4f6cb">

**Comment by hotlong** [comment]
新的相关表样式就是这样
