### ISSUE TITLE
[Bug]: 新建列表视图，配置过滤的列时，字段联动错误

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6272]
### Description

配置过滤的列时，修改过滤字段后，对应的选项值未修改
<img width="1193" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/d2145b9e-29f9-4392-8c8b-9429e93bf648">
<img width="809" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/213a1d34-a51b-4997-bfaf-032dba2e6210">

### Steps To Reproduce 重现步骤

1、新建列表视图，配置“过滤设置”。
2、设置过滤字段，并设置字段选项值。
3、修改过滤字段即可重现

### Version 版本

2.6.4-beta.10

**Comment by Flyingliao** [comment]
amis 在线编辑器中重现了该bug，已经提了issue了： https://github.com/baidu/amis/issues/9478

**Comment by hotlong** [comment]
等amis处理完更新我们的amis

**Comment by baozhoutao** [comment]
`3.6.3-patch.6`
