### ISSUE TITLE
[Feature] 附件预览功能：图片格式、PDF格式

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#6274]
### Description

测试问题：
附件上传pdf格式文件后无法预览

### Steps To Reproduce 重现步骤

操作步骤：
应付-》付款单-》附件-》选择pdf格式文件-》预览
![image](https://github.com/steedos/steedos-platform/assets/92509428/4b811e1b-0c10-483a-b8a9-1fbdea9af6cc)

### Version 版本

 2.6.4-beta.10

**Comment by Flyingliao** [comment]
<img width="846" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/ea8fb2ad-94d1-4b24-9088-b57ff08cd534">

<img width="729" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/4834ac50-3597-4158-ba50-c7d2aa525df7">
