### ISSUE TITLE
[Bug]: 列表视图上配置换行无效

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6275]
### Description

列表视图上字段配置了换行属性，前端显示仍未换行
<img width="1101" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/9d7c2e14-ae35-4236-af29-c19e03bff4ac">
![image](https://github.com/steedos/steedos-platform/assets/126655403/389a2d05-2a57-4f81-ba90-4bb23cd9bd74)

### Steps To Reproduce 重现步骤

列表视图上给字段配置换行（wrap：true）即可重现

### Version 版本

2.6.4-beta.10

**Comment by tujiajun** [comment]
该问题为视图在前台点击过自定义，列表优先认数据库中数据造成，属于规则
