### ISSUE TITLE
[Bug]: 附件详情中的描述无法编辑

### ISSUE THREAD

**Issue by wangyanwa** [steedos/steedos-platform#6277]
### Description

测试问题：
附件详情中的描述无法编辑

### Steps To Reproduce 重现步骤

操作步骤（以付款单为例）：
应付-》付款单-》附件-》详细

![image](https://github.com/steedos-labs/feikongwang/assets/92509428/740807b0-c3d2-4d13-b01c-8d862bd770d3)

### Version 版本

 2.6.4-beta.10

**Comment by hotlong** [comment]
不方便处理
