### ISSUE TITLE
[Bug]: 分栏模式下偶发，记录顶部被档住了。

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6278]
### Description

我感觉是 amis 的列表在重算高度的时候导致的问题。普通的列表视图刚进去的时候也会抖动一下。

<img width="1721" alt="企业微信截图_ee279720-32a3-4682-8240-a7fa25422a21" src="https://github.com/steedos/steedos-platform/assets/50353452/82ba5c2c-4a12-4089-866f-51bf2f2554aa">

### Steps To Reproduce 重现步骤

运行费控王
偶发

### Version 版本

2.6.4

**Comment by baozhoutao** [comment]
6.0 sdk 已修复此问题

**Comment by baozhoutao** [comment]
问题原因是3.6 的sdk 中table 的updateAutoFillHeight 算法有漏洞.  分栏模式下 导致在计算表格高度的时候, 会减掉右侧详细页面高度. 导致表格高度计算出的是 负数.
解决方案: 依赖updateAutoFillHeight中的兜底变量parent, 使其不能计算到详细页面元素层.
