### ISSUE TITLE
[Bug]: 流程-字段页面，设置字段按钮样式需要调整

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6286]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/d256191b-3b53-49b1-a281-72a9cfe63153">

### Steps To Reproduce 重现步骤

按钮直接连在列表上了

### Version 版本

2.6.4-beta.10

**Comment by tujiajun** [comment]
调整后效果
<img width="1025" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/845ee3ad-911e-4a9e-8ade-56f3aa73b9b6">
