### ISSUE TITLE
[Bug]: 流程启用amis表单后，部分字段显示在子表下边

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6290]
### Description

部分审批单字段显示在了表单下，可能和此对象配置了页面布局有关
<img width="1295" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/dc55d65f-18d9-4ec1-a281-2d91b84ecd94">

### Steps To Reproduce 重现步骤

不能确认重现规则。

### Version 版本

2.6.4-beta.10

**Comment by baozhoutao** [comment]
优先级最高的是分组顺序.   表格只是在当前分组的最后显示.
