### ISSUE TITLE
[Task]: 页面右上角设置增加快速进入对象设置按钮

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6292]
### SubTasks 子任务

之前老版本有这个功能
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4af36aca-4f66-4320-b459-809c392ef4ee">

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/6321
