### ISSUE TITLE
[Bug]: 统计分析-仪表盘设置时间条件后，保存提示保存失败

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6296]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4019b3ea-61e1-44c9-9f78-643a3a7d2d64">

### Steps To Reproduce 重现步骤

1、其中的某一个组件设置了系列对比
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/9c82215e-10ab-46e5-ba39-d4e78c287427">
2、所以在设置时间条件绑定搜索字段时，保存数据提示保存失败

### Version 版本

2.6.4-beta.10

**Comment by lizheng-steedos** [comment]
是因为组件添加了系列设置
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a1338931-f183-4bc2-a0d2-d479d710a246">

**Comment by lizheng-steedos** [comment]
保存失败后，同步元数据还会把失败的组件之间删除。

比如，有个添加系列的对别展示数据的组件，提示保存失败后，虽然页面还是会显示这个组件，但是同步到元数据后 发现这个组件被删掉了

**Comment by baozhoutao** [comment]
问题原因:  mongodb不支持 key上有符号点`.`
![image](https://github.com/steedos/steedos-platform/assets/6194462/3d8cf4c0-2eb1-4d1b-b29a-a4f35219cb5f)
