### ISSUE TITLE
[Bug]: 统计分析-仪表盘中组件设置系列后，横坐标消失了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6297]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/1dbb4796-11f5-4b3f-b843-81ad981fe476">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4ae52245-4f92-41b9-a85a-900c92f91181">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.6.4-beta.10

**Comment by lizheng-steedos** [comment]
不能解决

**Comment by baozhoutao** [comment]
此问题仅在编辑的时候出现, 退出编辑模式后即可正常(点击右上角的保存、取消后会正常显示)
![image](https://github.com/steedos/steedos-platform/assets/6194462/433427aa-244b-431c-8c15-0c4af8147cdd)
