### ISSUE TITLE
[Bug]: 审批单中未填写的数值字段，回传到台账时变为空字符串，导致记录报错

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6298]
### Description

审批单提交后，如果数据未填写，会传到台账时，数值字段别写成字符串，导致台账显示错误。
查看数据库，发现未填写的数字字段值被写为“”，如图三
HT目前使用版本（2.6.4-beta.2）中没有此问题
<img width="1214" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/f47d793e-ce85-4f70-9894-3c417b4858ec">
<img width="1408" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/afba013b-6f9f-40bd-b9bc-e61d74eb4e3e">
<img width="1030" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/71464101-d04d-4709-869b-928dc719317f">

### Steps To Reproduce 重现步骤

1、新建流程（绑定对象）、流程审批单中包含数字字段。
2、新建审批单，新建时数字字段不填写并提交审批单。
3、查看对应的台账信息，即可重现。

### Version 版本

2.6.4-beta.10

**Comment by sunhaolin** [comment]
同 https://github.com/steedos/steedos-platform/issues/5854
