### ISSUE TITLE
[Bug]: 表单切换为水平模式后，存在部分样式问题

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#6302]
### Description

- [x] 无label时，左边会有个边距
<img width="1132" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/f532cae1-c4de-4dc3-b478-ca78406243b3">

- [x] input-table的footertoolbar中的按钮位置偏移
<img width="1099" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/7cba9f87-213e-43fb-ba4a-6b8324c5c217">

### Steps To Reproduce 重现步骤

进入新建列表视图

### Version 版本

最新版

**Comment by hotlong** [comment]
相关页面改为非水平模式？
