### ISSUE TITLE
[Bug]: 应用程序页对象表格无法切换分栏，但却存在分栏按钮

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#6303]
### Description

<img width="1437" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/a7fa40c4-7fc9-47c6-8cca-1e1dcdeec771">

### Steps To Reproduce 重现步骤

1、新建微页面
2、拖入一个对象表格

### Version 版本

最新版

**Comment by hotlong** [comment]
为什么无法切换分栏

**Comment by hotlong** [comment]
应用程序页面应该是无法切换分栏的，确实不应该显示分栏按钮

**Comment by hotlong** [comment]
设计器中增加一个属性开关？

**Comment by tujiajun** [comment]
修改为仅在列表视图组件中显示视图相关按钮
