### ISSUE TITLE
[Bug]: 审批单表格表头应该是黑色的线

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6304]
### Description

现在是灰色
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/aa5e1478-4c15-44ae-91f7-3c318a3faaa8">

### Steps To Reproduce 重现步骤

见图片

### Version 版本

2.6.4-beta.13

**Comment by hotlong** [comment]
应该是我统一修改表格样式导致的。需要对审批王特殊处理一下。
