### ISSUE TITLE
[Bug]: 流程偶发出现 已审批的流程还在待审核列表中

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6306]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/cb147ef4-0b7c-4a34-85b6-f4177afc35d0">

### Steps To Reproduce 重现步骤

偶发出现

### Version 版本

2.6.4-beta.13

**Comment by hotlong** [comment]
应该是前一个流程服务器还没执行完。
