### ISSUE TITLE
[Bug]: 统计分析-根据日期分组查询报错

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6309]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/1887de56-4a8b-40a0-901a-ea246c5750ec">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/ad9db7a1-3416-400b-b0bc-0b5d6e6b26b9">

### Steps To Reproduce 重现步骤

feikongwang项目，根据应收合同的收款日期进行查询

### Version 版本

2.6.4-beta.13

**Comment by sunhaolin** [comment]
最新环境正常
