### ISSUE TITLE
[Bug]: 新拖入的对象表格在设计器中显示不出来

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6313]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/775534ba-87fe-4fd5-8b5e-874f1ab8eab9">

### Steps To Reproduce 重现步骤

无法配置对象表格属性

### Version 版本

 2.6.4-beta.13

**Comment by hotlong** [comment]
左侧树可以选中控件

**Comment by lizheng-steedos** [comment]
左侧可以选中，但是选中设计器中也是显示不出的
