### ISSUE TITLE
[Bug]: chrome列表视图字段列宽自适应算的宽度还是有问题

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6314]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/87a48cb8-7683-4976-92bf-26bd200500fd">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/2072bae8-a7a2-4c84-9a1f-ccf9a057fb2c">

### Steps To Reproduce 重现步骤

合同列

### Version 版本

 2.6.4-beta.13

**Comment by hotlong** [comment]
原则上不要给列配任何宽度

**Comment by lizheng-steedos** [comment]
没有配宽度 完全是自适应@hotlong

**Comment by tujiajun** [comment]
目前版本存在规则：宽字段若未配置换行属性，则默认换行
该规则目前看来若无width配合，在显示上会存在一些问题

**Comment by tujiajun** [comment]
处理方案：
1、去除宽字段默认换行规则
2、给宽字段增加默认宽度来维护“宽字段默认换行”规则，此外还需将前台列表视图表单的换行勾选更改为select
