### ISSUE TITLE
[Bug]: 台账发起审批，审批单相关子表中的累积汇总字段双向同步错误

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6317]
### Description

- 问题描述
1. 在流程的相关表字段设置中未添加该累积汇总字段
![image](https://github.com/steedos/steedos-platform/assets/129827462/4e64f8d7-6b2d-4ff5-8edc-1e5341a0726a)
2.新建台账发起审批之后，该累积汇总字段同步成了数值0
 - 发起审批之前
![image](https://github.com/steedos/steedos-platform/assets/129827462/c2a70192-d462-4e00-9f94-c64f10e5dbca)
- 审批完成之后
![image](https://github.com/steedos/steedos-platform/assets/129827462/bede126e-45e6-4a16-a437-7d5cf5026f64)

### Steps To Reproduce 重现步骤

如上描述

### Version 版本

 2.6.4-beta.13

**Comment by sunhaolin** [comment]
业务代码导致
