### ISSUE TITLE
[Bug]: platform启动后，安装@steedos/contract软件包后，无法启动成功

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6323]
### Description

软件包详细页面右上角也缺少升级按钮
![image](https://github.com/steedos/steedos-platform/assets/6219465/efe8a2ff-60d2-4ed4-80d8-76b98a0f2be8)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.2.beta.x

**Comment by hotlong** [comment]
steedos-ee 运行源码即可
