### ISSUE TITLE
[Feature]: 发起审批时，需要前端执行一段脚本做数据校验

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6328]
### Summary 摘要

例如
- 子表必填
- 附件必填
- 请假天数必须大于1

### Why should this be worked on? 此需求的应用场景？

费控王

**Comment by hotlong** [comment]
或者把现有发起审批的逻辑改为 action，允许项目自定义发起审批按钮。

**Comment by baozhoutao** [comment]
方案:
1 给amis 注册 发起审批 action `steedos_actions_standard_approve`
2 用户可按需重写对象的发起审批按钮并重新编排发起审批按钮的actions: 对象详细-按钮-standar_approve 进入详细后点击`自定义`

![image](https://github.com/steedos/steedos-platform/assets/6194462/78d107a4-81b7-4e81-bacd-38b3c9e85853)

**Comment by hotlong** [comment]
ok
