### ISSUE TITLE
[Bug]: 对象记录页使用微页面调整后，相关表偶发性显示不出

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6335]
### Description

其他对象的子表也会出现这种情况，重启后这个对象显示正常但是其他对象又会显示不正常
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/8bb89367-9fb2-4cf1-83d0-37cf35c52d08">

### Steps To Reproduce 重现步骤

feikongwang项目应收应用下，所有对象点击进入详情页

### Version 版本

2.6.4-beta.15

**Comment by lizheng-steedos** [comment]
2.6.5还是显示不出来
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/588cff5a-318f-47e9-a3b8-016cd682e19d">

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/7374fdab-eb01-45c3-9be3-915dc8684eaa)

此问题是组件问题,2.6.5的资产包不是最新的. 请使用最新的platform版本测试. 已知 `2.6.6-beta.3` 是正常的.
