### ISSUE TITLE
[Bug]: 数据导入界面显示空白

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6340]
### Description

数据导入界面显示空白
<img width="1360" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/6021409e-4168-4c24-96c3-b17f2b38eb21">
<img width="1284" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/3a04f1d5-25fe-4466-bdd9-82a25d49ff54">

### Steps To Reproduce 重现步骤

新建数据导入时，对象列表页导入数据时即可重现

### Version 版本

2.6.4-beta.15

**Comment by Flyingliao** [comment]
editFormInited 变量控制是否显示表单内容。
以下代码看起来也存在问题，有些矛盾。
<img width="747" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/1d2d82eb-341e-42da-a0c5-ccb412f1c85c">
