### ISSUE TITLE
[Bug]: 审批王流程设置-字段列表样式坏了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6344]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/5c7c4338-673d-4c91-8159-3e743fb7401a">

### Steps To Reproduce 重现步骤

进入审批王-字段设置列表页；

### Version 版本

 2.6.4-beta.17

**Comment by hotlong** [comment]
重复
