### ISSUE TITLE
[Bug]: 统计分析看板页面加载不出来了，提示“发生了一个错误”

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6347]
### Description
steedos_1  | steedos stdout | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
steedos_1  | steedos stdout | SyntaxError: Unexpected token o in JSON at position 1
steedos_1  | steedos stdout |     at JSON.parse (<anonymous>)
steedos_1  | steedos stdout |     at /app/node_modules/@steedos-labs/analytics/dist/index.js:1:218302
steedos_1  | steedos stdout |     at arrayMap (/app/node_modules/lodash/lodash.js:653:23)
steedos_1  | steedos stdout |     at Function.map (/app/node_modules/lodash/lodash.js:9622:14)
steedos_1  | steedos stdout |     at transformSeriesData (/app/node_modules/@steedos-labs/analytics/dist/index.js:1:218234)
steedos_1  | steedos stdout |     at Service.handler (/app/node_modules/@steedos-labs/analytics/dist/index.js:1:14595)
steedos_1  | steedos stdout |     at Service.callAction (/app/node_modules/moleculer-web/src/index.js:645:16)
steedos_1  | steedos stdout | 
steedos_1  | steedos stdout | (node:1606) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 58)
steedos_1  | steedos stdout | 
steedos_1  | steedos stdout | Sentry Logger [log]: Not capturing exception because it's already been captured.
steedos_1  | steedos stdout | 
steedos_1  | steedos stdout | This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
steedos_1  | steedos stdout | 

<img width="1548" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a6612e0c-2fff-492a-9bf1-2abe528e7a35">

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/5af8233d-a853-4c9f-9e03-cc025976c5c2">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/b84ce7ee-c709-4d9f-949d-c3da7a927fb6">

### Steps To Reproduce 重现步骤

feikongwang项目，应收、应付首页

### Version 版本

2.6.4-beta.17/0.1.9

**Comment by hotlong** [comment]
费控没有加系列 就是好的，另外两个加了就是坏掉了
