### ISSUE TITLE
[Bug]: 下拉框字段在列表页编辑时，如果屏幕较小，无法搜索

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6348]
### Description

在列表页批量编辑记录时，下拉框类型字段在笔记本上显示样式（浏览器已全屏显示）如图一，此时无法显示顶部数据，且无法搜索；在扩展屏幕上显示为图二（屏幕较大），显示正确
<img width="1439" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/91d6b5fc-1d2c-44e8-8605-1e2016c15939">
![image](https://github.com/steedos/steedos-platform/assets/126655403/9130aa8d-22dd-43a1-a1d8-d4967e9aaf89)

### Steps To Reproduce 重现步骤

列表页编辑下拉框字段，屏幕较小的时候即可重现。

### Version 版本

2.6.4-beta.17

**Comment by hotlong** [comment]
这个问题有点复杂，先研究一下可行的解决方案，然后拉个会
