### ISSUE TITLE
[Bug]: user在审批中心“待审批”中新建视图后，再次进入“审批中心”报错：Cannot read properties of null (reading 'filter')

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6351]
### Description

普通用户新建instance_tasks的视图后，再次进入“审批中心”报错
需讨论能否默认去除user对instance_tasks对象的创建视图权限
<img width="1432" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/e1788591-e9a5-474d-acef-30c26e292896">
<img width="1427" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/29188550-ecf7-4828-8e5c-c4e7dd631f7f">
<img width="1420" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/44620265-2ff2-46dd-983a-648bcc7d25ff">

### Steps To Reproduce 重现步骤

在待审批中新建视图后，再次点击审批中心即可重现。

### Version 版本

2.6.4-beta.17

**Comment by hotlong** [comment]
审批中心应该禁止新建视图
