### ISSUE TITLE
[Feature]: 调整”附件版本”对象列表视图显示

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6352]
### Summary 摘要

目前只显示了上传时间
![image](https://github.com/steedos/steedos-platform/assets/126655403/7abd027a-e083-4fbe-82ad-55de7238e81d)

### Why should this be worked on? 此需求的应用场景？

优化列表视图显示。

**Comment by Flyingliao** [comment]
原因：type: object 的字段在列表视图上未显示出来
<img width="1161" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/6b2449ab-d4b4-4ea1-a5e6-55e65eb7be80">
