### ISSUE TITLE
[Bug]: 已经发起的流程，在审批过程中其他人员可以删除相关文件

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6353]
### Description

审批过程中的其他人员可以删除提交人的关联文件
![image](https://github.com/steedos/steedos-platform/assets/126655403/e1fe9fdf-e7e8-4862-9682-e5e888117650)

### Steps To Reproduce 重现步骤

审批单上使用“关联文件”按钮添加关联文件。审批单提交后，在后续人员审批界面即可重现此问题。

### Version 版本

2.6.4-beta.17

**Comment by sunhaolin** [comment]
- [ ] 新规则：发起关联的人才可以删除

**Comment by hotlong** [comment]
目前数据库中没有记录谁关联的文件，暂停
