### ISSUE TITLE
[Feature]: 前台显示的选项卡设置链接添加的仪表盘页面，页面需要隐藏标题头

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6356]
### Summary 摘要

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/96e688b4-b533-4b1f-a138-41f9f0f89dd4">
<img width="1476" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/92e3d513-f2fd-4fc8-95fa-7e6dfae5bac8">

### Why should this be worked on? 此需求的应用场景？

业务需要

**Comment by baozhoutao** [comment]
嵌入的url后面添加 `#titled=false`即可.

**Comment by baozhoutao** [comment]
需要转译, url后面添加 `%23titled=false`

**Comment by baozhoutao** [comment]
去掉边框线, url后添加 `%23titled=false%2526bordered=false` .  & 符号需要2次转译.
