### ISSUE TITLE
[Bug]: 审批单列表视图文件标题配置了宽度和换行，前台都没生效

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6359]
### Description

配置了宽度和换行
```
- field: name
    width: 400
    wrap: true
```

### Steps To Reproduce 重现步骤

重写monitor.listview.yml视图文件，配置name字段宽度和换行

### Version 版本

2.6

**Comment by Flyingliao** [comment]
Safari浏览器目前不换行：这个 issue 定的 --- safari浏览器上部分列表会出现抖动现象 #6334。
