### ISSUE TITLE
[Bug]: 使用日期段进行对象记录筛选，系统选取的日期时间段有误

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6362]
### Description

使用日期进行筛选，目前如开始日期和结束日期都选择1月1日，系统选取的时间段并非1月1日0点-23点59分，而是1月1日的0点-0点

### Steps To Reproduce 重现步骤

1.对象筛选，创建时间开始日期和结束日期选择同一天
2.找不到，此天的任何记录，系统选取时间段有误

### Version 版本

 2.6.5

**Comment by yinlianghui** [comment]
- 日期字段没有问题，因为填写日期字段值时保存的就是utc 0点0分0秒，所以查的时候不区别小时分钟秒。
![image](https://github.com/steedos/steedos-platform/assets/6219465/8a68a36d-ad48-4da9-b3be-2fa552477a92)


- 日期时间字段有bug，已经改为以下效果：
![image](https://github.com/steedos/steedos-platform/assets/6219465/01e78504-8865-4e31-bc59-ebe93acfcab0)
