### ISSUE TITLE
[Bug]: oem配置后流程设计器的tab图标没有变

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6363]
### Description

<img width="1920" alt="89b3735eb3785d2f543fc83679260a7" src="https://github.com/steedos/steedos-platform/assets/15027092/c838ec4f-3cac-441c-9c40-1325d62328b9">

### Steps To Reproduce 重现步骤

1、许可证配置oem
2、点击流程设计器

### Version 版本

2.6

**Comment by hotlong** [comment]
删除网页中的favicon应该就可以。
