### ISSUE TITLE
[Bug]: 手动安装打印软件包报错

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6369]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/8537bb59-f066-4d36-add8-1f1e1c9cedea">

### Steps To Reproduce 重现步骤

手动安装软件包“@steedos/print-template”

### Version 版本

2.6.5

**Comment by hotlong** [comment]
https://github.com/steedos/steedos-platform/issues/6370 重复
