### ISSUE TITLE
[Bug]: 打印模版软件包安装好后启用报错

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6370]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/47e9596e-f8e9-4362-86eb-5bf75dc2e993">

### Steps To Reproduce 重现步骤

安装成功后启用

### Version 版本

2.6.4

**Comment by hotlong** [comment]
应该企业版自带打印模版，自动启动
