### ISSUE TITLE
[Bug]: 去掉系统内核中的合同管理员权限集

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6375]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/9c5e4276-3f1b-4292-85c4-ddb04202b381">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.6.6-beta.5

**Comment by hotlong** [comment]
修改之后要确认一下现有平台
