### ISSUE TITLE
[Bug]: 自定义base发起审批按钮，在设计器重新编排发起审批按钮的actions，点击保存。action不生效。

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6376]
### Description

- 查看schema，按钮的actions代码还是自定义之前的代码
1.重新编排发起审批按钮的actions
![image](https://github.com/steedos/steedos-platform/assets/129827462/29ef0ddf-a643-4375-8b62-7ab05e0454d8)
2.发起审批按钮的schema
![image](https://github.com/steedos/steedos-platform/assets/129827462/27162725-2116-40d6-88e6-a0ce29e400f3)

### Steps To Reproduce 重现步骤

1、对象设置
2、自定义发起审批按钮
3、在设计器里重新编排actions，点击保存

### Version 版本

 2.6.6-beta.2

**Comment by ysc1234** [comment]
其他自定义的按钮同样也存在这个问题，不止base按钮，
1、在一个环境新建自定义按钮，在设计器里添加点击事件，同步成源代码。
2、换一数据库，再重新自定义该按钮，修改该按钮的点击事件，点击保存。
3、点击按钮还是自定义之前的点击事件。
4、必须将自定义之后的按钮同步成源代码，才可以

**Comment by baozhoutao** [comment]
platform  2.6.6-beta.6 会修复此问题, 等发版本后,重新确认.
