### ISSUE TITLE
[Bug]: window 对象详情页，出现双滚动条

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6377]
### Description

mac 正常

![image](https://github.com/steedos/steedos-platform/assets/50353452/f3254b6a-2677-4ed7-8830-b4f499dba67d)

### Steps To Reproduce 重现步骤

联系黄老师.

### Version 版本

2.6.6-beta.5

**Comment by Flyingliao** [comment]
2.6.7-beta.5 是正常的。
