### ISSUE TITLE
字段公式

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#638]
第一类：当前表数值、日期类型的加减

第二类：相关表相关字段的引用。例如采购订单选择供应商，带出供应商的网址、税务登记号等信息。

**Comment by baozhoutao** [comment]
大致方案：
1 新增字段类型：公式
2 需配置公式返回类型：boolean,  数值，文本
3 定义公式：可以使用 当前对象的基本类型字段及引用类型字段(跨对象公式)，具体可使用哪些字段根据公式类型字段值类型确定
4 引用类型公式(跨对象公式) ：引用的记录变化时， 此字段值也跟着变
5 公式变化时：现有数据也自动更新
6 服务端运行公式：需控制可访问的变量

待讨论： 
1 公式编写方式：细化方案3 ；
2 公式计算规则：什么时候计算，什么时候更新，主要针对4、5
