### ISSUE TITLE
[Bug]: 手机端（手机浏览器），审批中附件打开后显示乱码

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6380]
### Description

无论格式，所有附件显示正常

### Steps To Reproduce 重现步骤

环境UC浏览器或华为自带浏览器
1.发起审批，添加附件 txt和docx
2.发送文件，审批人打开附件
3.txt附件乱码
![0ef5062a7ed8294dc7e16c392c56e65](https://github.com/steedos/steedos-platform/assets/7665279/ba879bbc-4cca-4a18-8140-9e6454673bc9)
4.docx 标题乱码
![0530ab45e35c931217bff0e0cf7dbef](https://github.com/steedos/steedos-platform/assets/7665279/54b9b530-e955-4bfb-be57-e1dbb9b83023)

### Version 版本

 2.6.6-beta.5

**Comment by sujiahao66** [comment]
从审批中心查看审批单附件显示为乱码（图一）；从台帐的附件子表中查看附件，下载附件时文件标题显示为id

**Comment by hotlong** [comment]
在企业微信中点击审批王的附件，企业微信会弹出浏览器。
台账的附件不会弹出，会正常显示。但是下载的时候文件名不对，是id

**Comment by sunhaolin** [comment]
手机端 edge、chrome浏览器正常

**Comment by sunhaolin** [comment]
华为自带浏览器有此问题
