### ISSUE TITLE
[Bug]: 表单编辑器打不开

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6382]
### Description

无法编辑表单

### Steps To Reproduce 重现步骤

<img width="1355" alt="1706512875460" src="https://github.com/steedos/steedos-platform/assets/7665279/78a8a3e9-6194-4785-b758-bbcf372d7d40">

### Version 版本

2.6.6-beta.5

**Comment by baozhoutao** [comment]
问题原因: /server/bundle/**/node_modules/@steedos/form-builder/dist 下的文件在.gitignore 中忽略掉了
