### ISSUE TITLE
[Bug]: 主表记录“已核准”后，新建子表记录，子表“审批状态”字段在列表视图上显示为“已核准”，但在详情页没有值

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6383]
### Description

在“已核准”的合同下相关页中新建付款单，新建完成后，在付款单列表视图上“审批状态”显示为“已核准”，但是付款单详情页中“审批状态”字段没有值
<img width="1432" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/8d93b522-3b92-4e22-b1ee-71d5a8d66862">
<img width="1439" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/9d21a14f-16f5-4998-b140-e1a23252d50b">
<img width="1419" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/65fd4d12-258c-403e-a577-afcb82dc30f1">

### Steps To Reproduce 重现步骤

1、新建主表记录，并且主表记录“审批状态”字段值为“已核准”。
2、在主表记录相关中新建子表，子表“审批状态”字段需要设置在列表视图上显示。
3、新建子表记录即可重现此问题。

### Version 版本

2.6.6-beta.5

**Comment by yinlianghui** [comment]
此问题是因为批量编辑功能把列的type加了static-前缀：
![image](https://github.com/steedos/steedos-platform/assets/6219465/a08efe64-1225-413b-97e8-1b42ed8ed93f)

而static-前缀的列会有bug，已经给amis提issue了：https://github.com/baidu/amis/issues/9556

此问题修正后测试过单元格编辑功能正常。
