### ISSUE TITLE
[Bug]: 管理员重定位审批单后，点击“查看审批单”按钮后：Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6384]
### Description

重地位审批单之后，点击“查看审批单”按钮查看审批单，无法查看。其他管理员点击“查看审批单”按钮可以看到
<img width="1439" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/eb0a4b5b-1314-4e40-9500-db5208f1a54f">
<img width="987" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/5fd297b0-f971-4972-9d8f-47219f0631e6">

### Steps To Reproduce 重现步骤

管理员重定位审批单后，点击“查看审批单”查看审批单即可重现。

### Version 版本

2.6.6-beta.5

**Comment by sunhaolin** [comment]
2.6.6-beta.6 解决
