### ISSUE TITLE
[Bug]: 纯内网环境下，部分资产包还是会走外网地址获取

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6387]
### Description

资产包：https://unpkg.steedos.cn/@steedos-labs/analytics-frontend@0.46.6-beta.31/dist/assets.json
已配置环境变量STEEDOS_UNPKG_URL指向/unpkg/
![69163ddba99179424480702b827b207](https://github.com/steedos/steedos-platform/assets/15027092/260720c7-d50f-4f1a-8e34-fc891efce00f)

### Steps To Reproduce 重现步骤

1、启用steedos-community:2.6镜像
2、配置STEEDOS_UNPKG_URL=/unpkg/
3、浏览器访问，analytics-frontend没有走环境变量配置的地址

### Version 版本

2.6

**Comment by baozhoutao** [comment]
请重新确认运行环境及参数配置:
1 社区版是无法运行analytics软件包的.
2 2.6最新代码测试未发现问题.
