### ISSUE TITLE
[Bug]: 安装统计分析软件包后, 系统部分按钮出现了 红色边框线

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6388]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194462/bb3a62a2-a2b4-4e07-8e7e-0d50c26a650e)

### Steps To Reproduce 重现步骤

直接运行费控王

### Version 版本

2.6

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/5dd0ff2e-b632-4311-83b2-42cb5eae7497)
名称列 字体颜色异常. 应该是蓝色字体

**Comment by hotlong** [comment]
运行费控王，我的对象列表是好的。

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/25dd98c2-aaf5-42de-af3a-e49f52c121de)

本地unpkg错乱导致
