### ISSUE TITLE
节假日和工作时间

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#639]
- 参考salesforce优化现有的节假日表
- 新增工作时间表

![image](https://user-images.githubusercontent.com/50353452/88901415-55c8e780-d283-11ea-85ea-76d38f4e6797.png)

![image](https://user-images.githubusercontent.com/50353452/88905249-aa229600-d288-11ea-8447-8ab3bdedb119.png)

**Comment by hotlong** [comment]
之前处理了一半的任务 https://github.com/steedos/steedos-platform/issues/588

**Comment by yinlianghui** [comment]
已完成，规则：
- 在`steedos.config.ym`中配置了参数enable_holidays时，相关计算才排除节假日
- 未配置工作时间时，按enable_holidays未配置处理
- 导出主要函数：`getTimeoutDateWithoutHolidays = async (start: Date, timeoutHours: number, spaceId: string, digitsForHours: number = 2)`
