### ISSUE TITLE
[Bug]: 子表组件中数值类型字段无法正常输入

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6390]
### Description

子表组件中实际输入的数字是50,子表中显示是00
<img width="1434" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/ed3f7d41-6bf6-4bf0-bb21-c4ad07e3ff2c">

### Steps To Reproduce 重现步骤

在子表中编辑数值类型字段即可重现。

### Version 版本

2.6.6

**Comment by tujiajun** [comment]
该问题为steedos-field，config属性配置错误导致，已更改
