### ISSUE TITLE
[Bug]: 审批王多行文本框，显示时作废markdown转换

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#6391]
### Description

审批王里 长文本1*111*1 的文本框 两个*就不显示 然后转成斜体字了
<img width="790" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/1771345d-fd6f-4f2d-bed4-e2729121b6d2">

### Steps To Reproduce 重现步骤

1.设置长文本框
2.输出1 * 1111 * 1。
<img width="83" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/0d15563e-50eb-4125-81a8-7e87d3484999">
中间1111变成斜体并不显示*

### Version 版本

2.5

**Comment by hotlong** [comment]
审批王长文本目前默认是 markdown 格式

**Comment by RussellMao** [comment]
该怎么处理，要显示**怎么弄。使用表单模版可以解决么

**Comment by hotlong** [comment]
我们改内核。
