### ISSUE TITLE
[Feature]: 记录详情页支持配置相关表，显示对应的审批任务清单

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6392]
### Summary 摘要

目前可以配置审批单

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by hotlong** [comment]
能配置出一个例子就好

**Comment by yinlianghui** [comment]
审批子表右上角的新建按钮可以通过在项目中extend审批对象并修改按钮的显隐规则来处理：
![image](https://github.com/steedos/steedos-platform/assets/6219465/7372f814-4f53-44ee-982b-5e3b743f1b5f)

**Comment by yinlianghui** [comment]
> 审批子表右上角的新建按钮可以通过在项目中extend审批对象并修改按钮的显隐规则来处理： ![image](https://private-user-images.githubusercontent.com/6219465/303346104-7372f814-4f53-44ee-982b-5e3b743f1b5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDAxMjgsIm5iZiI6MTcwNzM5OTgyOCwicGF0aCI6Ii82MjE5NDY1LzMwMzM0NjEwNC03MzcyZjgxNC00ZjUzLTQ0ZWUtOTgyYi01ZTNiNzQzZjFiNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMTM0MzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQzYjAwZTQ0Y2M0ZDZmNWUzMGUzYzEzNDI1MWE4ODRmMWYwOTJlOGRlMjZmYTU5YWY2MjBmZTI0M2E0ZmQ2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5emDZawjRtgzi2WDh95jzwJ3pfGJpQscsWTjUuP2KGI)

已经不用配置了，因为内核已经加上这段代码了，默认规则变成只要审批任务作为子表列表右上角就隐藏新建按钮。
