### ISSUE TITLE
[Bug]: lookup多选字段为空时，记录详情页字段样式坏了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6394]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/9abd0ad9-07f5-453c-a9f7-27fcd94cb783">

### Steps To Reproduce 重现步骤

1、记录详情页只读页面；
2、字段值为空时

### Version 版本

2.6.6

**Comment by tujiajun** [comment]
未重现该问题
<img width="1208" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/9f281b0d-8698-4a7a-8b31-57cdb66d5cd7">

**Comment by hotlong** [comment]
是不是因为宽字段？

**Comment by tujiajun** [comment]
该问题已消失，无需处理
