### ISSUE TITLE
[Bug]: 仪表盘加到前台页面后，页面一直跳来跳去

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6395]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/14a7ac45-26bf-462d-9aec-4ba10986c144">

### Steps To Reproduce 重现步骤

feikongwang项目应收模块

### Version 版本

2.6.7-beta.2

**Comment by hotlong** [comment]
我的电脑未能重现
