### ISSUE TITLE
[Bug]: 通过微页面初始化的记录详情页，样式丢掉了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6398]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/3e1d9e11-2f31-4da8-9cbf-48c0dd8bc34d">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/871f0167-2c38-46d8-b636-a910fddd062c">

### Steps To Reproduce 重现步骤

对象新建 记录页类型微页面
进入设计器后直接保存发布，前台就可以看到效果

### Version 版本

2.6.6

**Comment by yinlianghui** [comment]
这个好像@涂最近改过

**Comment by tujiajun** [comment]
该问题已修复
