### ISSUE TITLE
[Bug]: 手机端：审批单中多行文本未换行

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6399]
### Description

手机端审批单中的多行文本未换行，电脑端显示正确
<img width="1201" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/bcc6ba4b-80e4-43ac-ac8b-ce285e36110c">
![image](https://github.com/steedos/steedos-platform/assets/126655403/ac5c6d6a-ff91-4e26-9c51-7f7fb157c012)

### Steps To Reproduce 重现步骤

审批单中添加多行文本后，输入换行文本后在手机端查看即可重现。

### Version 版本

2.6.7-beta.3

**Comment by hotlong** [comment]
应该是去掉 markdown 导致的
