### ISSUE TITLE
地盆名称用了默认的name字段，在新建记录的时候，默认出来自动填充人的功能（safari浏览器）

### ISSUE THREAD

**Issue by steedosyun** [steedos/steedos-platform#640]
![地盆名称](https://user-images.githubusercontent.com/69024640/88994124-3df07280-d31a-11ea-8c99-7275195871a9.png)
能否取消这个自动功能？

**Comment by yinlianghui** [comment]
改safari浏览器可以关掉整个浏览器功能。
![image](https://user-images.githubusercontent.com/6219465/89878138-ba753200-dbf3-11ea-9527-a884b0e3fc4f.png)

**Comment by yinlianghui** [comment]
> 改safari浏览器可以关掉整个浏览器功能。
> ![image](https://user-images.githubusercontent.com/6219465/89878138-ba753200-dbf3-11ea-9527-a884b0e3fc4f.png)

没找到彻底的解决办法，加了段css把自动填充按钮去掉了。
