### ISSUE TITLE
[Bug]: 手机端：企业微信中打开附件后需增加返回按钮（请同时排除app和网页效果）

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6402]
### Description

目前只有企业微信中的返回，会返回到企业微信的工作台，还需再次点击进入系统，操作繁杂，需通过系统返回按钮，返回到前一界面

### Steps To Reproduce 重现步骤

1.打开附件，在原有界面上显示附件，无返回按钮
2.如点击企业微信的返回箭头，则回到了工作台界面
![22e6ca7592f4e2843272ef088e450d7](https://github.com/steedos/steedos-platform/assets/7665279/2483eee9-11f0-4e6c-bfa0-3abff570d8cb)

### Version 版本

2.6.7-beta.4

**Comment by hotlong** [comment]
要看一下企业微信应用市场中的其他软件是怎么处理附件的。

**Comment by chenzhipei** [comment]
经测试最新版打开附件可以通过返回按钮返回附加列表页
