### ISSUE TITLE
[Bug]: 审批王手机端，只读字段样式没有边框

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6403]
### Description

如题

### Steps To Reproduce 重现步骤

注意只读字段，可编辑字段是正常的

### Version 版本

2.6.7

**Comment by yinlianghui** [comment]
huayan平台绑定对象的非amis表单发现的问题：
<img width="386" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/5b672611-f6d2-47dd-a9b1-84254c791210">
正常的应该是像华炎平台目前加班申请的效果：
![image](https://github.com/steedos/steedos-platform/assets/6219465/e77984da-fcef-4529-b5b7-64ae18c5954c)

**Comment by yinlianghui** [comment]
最新代码，待审批有部分字段类型的只读模式（绑定对象的非amis流程）也没有加边距样式：
![image](https://github.com/steedos/steedos-platform/assets/6219465/29fb4523-608a-44e4-b05c-82407ac2d0c9)
