### ISSUE TITLE
[Feature]: lookup, master/detail 字段，支持在界面上配置过滤条件

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6416]
### Summary 摘要

- 可以使用列表视图的可视化过滤条件编辑器
- 字段值支持使用公式引用当前表单上的其他字段值
- 编辑字段时显示 filtersFunction

### Why should this be worked on? 此需求的应用场景？

联动选择

**Comment by tujiajun** [comment]
[Feature]: 对象字段表单的filters字段使用amis支持的公式编辑器 #6578

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/9fdccd85-27c5-45d5-aaff-1fcfa2e2e7bc)
编辑字段报错.

**Comment by tujiajun** [comment]
https://github.com/baidu/amis/issues/9870
目前暂时不支持公式编辑器，等待amis修复bug
