### ISSUE TITLE
[Bug]: 知识-站点的可见行设置为公开-所有用户可见，但一般用户看不到此站点

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6418]
### Description

按设置的权限进行查看

### Steps To Reproduce 重现步骤

1.站点可见性设置为公开-所有用户可见，发布文章
2.一般用户账号进入系统，进入知识后，看不到站点

### Version 版本

 2.6.7-beta.5

**Comment by Flyingliao** [comment]
@steedos-labs/oa 软件包要发个新版本。之前改好的都没发新版本。
<img width="419" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/067e8bd1-9672-44fe-a81d-fd8a8edadbcd">
