### ISSUE TITLE
[Bug]: 未使用80端口时，微页面设计器强制使用了80端口

### ISSUE THREAD

**Issue by forcemeter** [steedos/steedos-platform#6423]
### Description

![image](https://github.com/steedos/steedos-platform/assets/56063441/b3782f14-73ab-4293-9bc8-8cc142b5a908)

### Steps To Reproduce 重现步骤

1. 部署端口为 http://127.0.0.1:3880/api/pageDesign
2. 微页面设计器的保存请求地址为 http://127.0.0.1/service/api/page/pageVersion

### Version 版本

2.6.6
steedos/steedos-community:latest

**Comment by hotlong** [comment]
应该是ROOT_URL设置不对

**Comment by forcemeter** [comment]
已解决，感谢提醒，修改 docker-compose 中的 ROOT_URL 配置

目前是按 docker 部署文档进行操作的。
