### ISSUE TITLE
编号字段设定了“自动编号”，但是新建记录后根本没编号

### ISSUE THREAD

**Issue by steedosyun** [steedos/steedos-platform#643]
![没自动编号](https://user-images.githubusercontent.com/69024640/88994765-ac820000-d31b-11ea-8888-fd87c877b0ff.png)

**Comment by hotlong** [comment]
对于自动编号类型的字段，如果公式为空，可以自动填上。

**Comment by baozhoutao** [comment]
默认值{0000}
