### ISSUE TITLE
[Bug]: beta.11 版本, 资产包地址加载错误

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6438]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/2632275f-948d-4214-b5f3-10debff78beb">

### Steps To Reproduce 重现步骤

feikongwang项目升级到2.6.7-beta.11版本后，启动服务

### Version 版本

2.6.7-beta.11

**Comment by lizheng-steedos** [comment]
浏览器控制台报错
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/32f9ffc9-7f2b-4ccb-b835-b96db9d4fe74">

**Comment by hotlong** [comment]
/unpkg/@steedos-widgets/amis-object@v3.6.3-beta.1/dist/assets.json

被重定位到 

/@steedos-widgets/amis-object@v3.6.3-beta.1/dist/assets.json

**Comment by hotlong** [comment]
应该是docker的问题，配置环境变量后正常。

STEEDOS_UNPKG_URL=https://unpkg.steedos.cn

**Comment by chenzhipei** [comment]
此问题会影响某些有内外网需求的客户服务，例如配置的STEEDOS_UNPKG_URL=/unpkg/，登录首页为白屏
