### ISSUE TITLE
[Bug]: 设置-简档 & 权限集 中 选择 简档视图后 点击新建按钮不应选中简档分类

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#6439]
### Description

应选中权限集或者不显示新建按钮

### Steps To Reproduce 重现步骤

设置-简档 & 权限集 中 选择 简档视图后 点击新建按钮

### Version 版本

2.6.7-beta.11

**Comment by tujiajun** [comment]
目前该问题未发现
<img width="738" alt="image" src="https://github.com/user-attachments/assets/ff665f77-636d-4f05-9b0c-a716ec3939f0">

<img width="931" alt="image" src="https://github.com/user-attachments/assets/45cc4587-b6fc-4475-973f-4ff46cfb0e28">
