### ISSUE TITLE
[Bug]: 新建对象会出现不合适的提醒

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6441]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/f486c63c-0e26-4418-864e-a38d0f7b93fe">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/fc9a1100-5e65-4ad0-87c7-8dc5e9d7d6c7">

### Steps To Reproduce 重现步骤

新建对象、字段等其他操作也会显示这个提示，但是其实也没并不需要刷新，提示有些多余

### Version 版本

 2.6.7-beta.11

**Comment by hotlong** [comment]
不刷新有些场景下会有问题的。
