### ISSUE TITLE
[Bug]: 对象开启“锁定子表”功能、并且设置记录页微页面，记录锁定时，子表依然可以编辑

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6444]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/07ee31e6-fce5-4782-bbd9-bf71d9db4de8">

现在的在对象上的配置会有问题：子表可以分为内核子表和自定义子表，现在统一将所有子表对象全部锁定可能限制的太死；

### Steps To Reproduce 重现步骤

1、对象设置上开启“锁定子表”功能；
2、对象生成相应审批流程；
3、创建记录，并且创建子表记录；
4、将创建的记录发起审批，就能看到效果了

### Version 版本

 2.6.7-beta.11

**Comment by sunhaolin** [comment]
锁定记录对管理员不生效

**Comment by lizheng-steedos** [comment]
feikongwang项目“开票”对象，启用锁定记录功能后，“合同开票明细”和“开票明细”子表测试情况如下：
<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/26121781-c49f-4161-875c-9eda8fcdda07">

- 用户
  - 合同开票明细可以查看、新建、编辑、删除（有问题）；
  - 开票明细只可以查看（正确）；
 
- 管理员（疑问管理员是尽管锁定也可以增删改查吗？）
  - 合同开票明细可以查看、新建、编辑、删除；
  - 开票明细只可以查看编辑、删除、少了新建；

问题原因（推断）
- 开票对象记录详情页使用的微页面；
- 并且开票明细子表配置了显示条件；
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/85e6895d-f918-4af1-9f12-782809a4f216">

**Comment by sunhaolin** [comment]
开票审批通过后记录会锁定，合同开票明细的新建按钮显示 是因为代码中重写了新建按钮导致
