### ISSUE TITLE
[Bug]: 系统对象自定义前禁止编辑字段，自定义后禁止对象删除

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6451]
### Description

- [x] 对象没有自定义前，对象字段就可以编辑；
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/eba35044-944b-4f17-987b-8b9af9ceab51">

- [ ] #6492
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/14414e57-9216-421a-861d-3984b979b2eb">

-  [x] 系统对象自定义后，禁止删除。未来可以考虑开发一个重置的按钮。

相关 https://github.com/steedos/steedos-platform/issues/6454

### Steps To Reproduce 重现步骤

代码加载的对象即可

### Version 版本

 2.6.7-beta.11

**Comment by hotlong** [comment]
相关 https://github.com/steedos/steedos-platform/issues/6454
