### ISSUE TITLE
[Bug]: 界面上新建的字段，最终保存的内容中会多出很多与当前字段类型无关的属性

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6453]
### Description

比如下图是一个百分比类型的字段，多出了lookup、地理位置、url等类型的字段才有的属性。
![image](https://github.com/steedos/steedos-platform/assets/6219465/2b5129f2-61e4-4857-b842-83348fb8abe5)

### Steps To Reproduce 重现步骤

新建字段，然后从此对象的uiSchema接口或数据库记录中就能看到上面的问题

### Version 版本

2.6.x

**Comment by Flyingliao** [comment]
类似的issue： https://github.com/steedos/steedos-platform/issues/5954。
排查不同类型字段属性默认值。
