### ISSUE TITLE
[bug]: 主子表lock属性的联动锁定（enable_lock_detail）时，记录子表查看页也不应该显示“新建”按钮

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#6455]
### Summary 摘要

https://github.com/steedos/steedos-platform/issues/6235

![image](https://github.com/steedos/steedos-platform/assets/7553007/d64beecf-da16-4cc6-8f71-7d9384af8d44)
这里点进去后
![image](https://github.com/steedos/steedos-platform/assets/7553007/4f491081-101b-49f3-8323-8372e42cbcb1)
新建按钮也应不显示

### Why should this be worked on? 此需求的应用场景？

主表在审批过程中禁止子表数据新增或修改

**Comment by hotlong** [comment]
实现这个功能，子表记录列表页也需要加载记录服务

**Comment by yinlianghui** [comment]
此问题并不需要外面包一层加载记录服务组件，因为原来就包了一层service组件在抓取父记录数据了，出问题的原因是没有抓取父记录的locked属性。
