### ISSUE TITLE
[Bug]: 数据分析看板普通用户无查看所有记录权限时，看板显示异常

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6456]
### Description

![图片已粘贴至2024-2-19 11-26](https://github.com/steedos/steedos-platform/assets/129827462/c4d2b5bd-9186-4f96-bb87-3b66f1789a82)
现象：
 管理员看板正常
![图片已粘贴至2024-2-19 11-31](https://github.com/steedos/steedos-platform/assets/129827462/ba9d7a5e-d6d0-4acd-9bde-1e940939b3bf)

 普通用户看板显示异常，（无查看所有记录权限时，应显示暂无数据，而不是感叹号）
![image](https://github.com/steedos/steedos-platform/assets/129827462/0519ffe8-6ba7-4e58-b0a7-1cbe2ae76bae)

![image](https://github.com/steedos/steedos-platform/assets/129827462/ff541542-d711-4bdf-8e1d-8699a3dd0754)

### Steps To Reproduce 重现步骤

普通用户登录

### Version 版本

2.6

**Comment by sunhaolin** [comment]
请升级至2.6.7-beta.15
