### ISSUE TITLE
记录的详细页面，浏览器标签页上显示了记录id,应该显示名称字段的值

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#646]
比如：https://aaron.trial.steedos.com:8443/app/admin/baojia__c/view/DPz6LtST7d3MN3Cf9

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/89865588-9825e900-dbe0-11ea-983b-eb9d9ff5c1f2.png)
规则：
- 地盘编号取名number，设置为is_name字段了
- 地盘名称取名name，未设置为is_name字段，它是一个主表/子表类型
bug总结：浏览器标签页上的标题取错name字段了，应该取number这种设置了is_name的字段

**Comment by yinlianghui** [comment]
已处理，https://aaron.trial.steedos.com:8443/ 用的是1.21版本，该bug在1.22上不存在，已经在1.21中按1.22的代码修正了该问题。
