### ISSUE TITLE
[Bug]: 应用程序选择选项卡页面样式错误

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6461]
### Description

应用程序选择选项卡页面选择项显示文字只显示了一半

![image](https://github.com/steedos/steedos-platform/assets/6194462/71deccc8-06b3-4f01-b2d2-00413e49bd10)

### Steps To Reproduce 重现步骤

编辑应用程序-选项卡-设置选项卡

### Version 版本

2.6

**Comment by hotlong** [comment]
未能重现 
<img width="1117" alt="企业微信截图_d6414a92-7365-4273-999d-0484e709ad6b" src="https://github.com/steedos/steedos-platform/assets/50353452/d4b67089-da05-4f48-ad47-1797b0a750ae">

**Comment by hotlong** [comment]
运行平台源码才有此问题

**Comment by hotlong** [comment]
运行费控王也重现了。

**Comment by tujiajun** [comment]
该问题是由于amis开启虚拟渲染后，选项默认高度为32导致的，已向amis提交issue，https://github.com/baidu/amis/issues/9671，若在项目中遇到该问题，可通过给穿梭器组件配置"itemHeight": 40解决
