### ISSUE TITLE
[Bug]: 数据导入时数值类型精度缺失

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#6462]
### Description

对象字段设置为文本类型，excel设置为文本。数字仍然有精度缺失情况。

### Steps To Reproduce 重现步骤

1.对象设置
<img width="933" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/045e4ef9-4a3d-4020-a56b-5325eac6297c">

2.数据导入
<img width="573" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/e4bf9230-a9bf-405a-8a98-a3c48cae753d">
3.导入excel设置为文本
<img width="533" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/7d8335bc-325e-4890-a8e0-9d3da582dd1a">
4.精度缺失
<img width="107" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/bc356352-5ebb-4589-9bae-a96e71b85502">

### Version 版本

2.5.13

**Comment by sunhaolin** [comment]
excel中分列选择文本才能将数值真的转为文本，设置单元格格式没有用
