### ISSUE TITLE
[Bug]: 子表组件新增disabledOn属性，识别table字段上配置的amis.disabledOn表达式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6473]
### Description

- 目前的问题是：子表(table)字段类型的字段上配置amis.disabledOn属性未生效
- 有任务依赖了此特性：[Feature]: lookup (master/detail) 字段上支持配置填充规则 #5531
![image](https://github.com/steedos/steedos-platform/assets/6219465/b4d0255d-dd57-435f-8065-b2a336c55e07)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.x

**Comment by tujiajun** [comment]
子表组件新增了disabledOn,disable,visibleOn,visible,hiddenOn,hidden等属性
