### ISSUE TITLE
[Bug]: 工作流规则-删除时间触发器中记录时，删除确认框被遮住了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6475]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/d6b84e0a-3e96-4218-9dca-a8a199a6ff86">

### Steps To Reproduce 重现步骤

管理员进入后台设置页面，工作流规则中，先建一条时间触发器记录，再删除

### Version 版本

 2.6.7

**Comment by yinlianghui** [comment]
下拉框字段的新建界面更容易重现此问题：
![image](https://github.com/steedos/steedos-platform/assets/6219465/9060d97d-a3e3-461b-963a-de218a43a753)

**Comment by tujiajun** [comment]
重复
#6502
