### ISSUE TITLE
[Bug]: saas模式下，对象权限用户查看所有记录，但是普通用户登陆后对象看不到任何记录

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6478]
### Description

saas模式下对象权限有问题

### Steps To Reproduce 重现步骤

1、对象A设置的对象权限为用户查看所有记录；
2、对象A在系统初始化好是有数据的，管理员账号可以看到；
3、但是普通用户查看对象A却看不到记录

### Version 版本

2.6.7

**Comment by baozhoutao** [comment]
是历史数据的问题.
