### ISSUE TITLE
[Task]: 设置 - 统计分析 & API Key 菜单权限限制为给管理员

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6479]
### SubTasks 子任务

<img width="305" alt="企业微信截图_37a03a11-54fa-4a10-9653-63c286880029" src="https://github.com/steedos/steedos-platform/assets/50353452/3711b49e-0183-4e7c-9f2c-2beec9aa564c">

**Comment by hotlong** [comment]
数据分析平台应该要发版本

**Comment by baozhoutao** [comment]
d7375da2f7
