### ISSUE TITLE
页面上根据排序号分布字段和字段组，而非字段组默认在最下方。

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#648]
若同字段组中各字段的排序号不同，则以排序号最小的字段为准。

**Comment by yinlianghui** [comment]
目前现状：
1.非分组字段之间变更字段次序或者用sort_no都可以实现先后显示次序的排版。
2.分组字段之间，也可以变更其内各字段的次序或者用sort_no指定排序次序来实现分组字段之间的先后显示次序（若同字段组中各字段的排序号不同，则以排序号最小的字段为准）。
3.分组字段始终显示在非分组字段后面，即显示在最底部。

**Comment by yinlianghui** [comment]
> 目前现状：
> 1.非分组字段之间变更字段次序或者用sort_no都可以实现先后显示次序的排版。
> 2.分组字段之间，也可以变更其内各字段的次序或者用sort_no指定排序次序来实现分组字段之间的先后显示次序（若同字段组中各字段的排序号不同，则以排序号最小的字段为准）。
> 3.分组字段始终显示在非分组字段后面，即显示在最底部。

4.未设置sort_no的字段会排在设置过sort_no的字段的前面，即可以只设置希望排在最前面的几个字段的sort_no属性，其他字段会自动排在后面。
