### ISSUE TITLE
[Bug]: required字段为表达式时，无法进入字段详情

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#6483]
### Description

 required字段为表达式时，无法进入字段详情

### Steps To Reproduce 重现步骤

1.配置字段
required: "{{formData.is_invoice__c === true ?  true : false}}"
2.实测生效 但是无法再前端页面打开字段详情 提示
<img width="1214" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/37b42b39-8f79-435b-a0b3-e97ed9382cbf">

### Version 版本

2.6

**Comment by RussellMao** [comment]
测试amis的required属性，只支持true或false。不支持随着表单其他值变化而变化

**Comment by hotlong** [comment]
amis 支持 requiredOn	[表达式](https://aisuda.bce.baidu.com/amis/docs/concepts/expression) , 我们也应该提供类似的支持
