### ISSUE TITLE
[Bug]: saas软件包tab元数据重写偶发性生效

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6491]
### Description

feikongwang项目saas软件包重新定义菜单tab选项卡，设置隐藏选项卡，重启服务后选项卡有时正常隐藏选项卡，有时不隐藏选项卡

### Steps To Reproduce 重现步骤

见问题描述

### Version 版本

2.6.8-beta.3

**Comment by baozhoutao** [comment]
6eb1b30cfa
