### ISSUE TITLE
[Bug]: 相关表关系（lookup）字段设置中“外键字段”弹窗里的提示显示不全，被遮住了

### ISSUE THREAD

**Issue by Flyingliao** [steedos/steedos-platform#6495]
### Description

<img width="1107" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/92bf3b5d-bd2d-41a2-895a-7f98b877f92c">
<img width="1087" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/ccd3fc04-21be-4a20-96e6-b3b11ef92dba">
<img width="1091" alt="image" src="https://github.com/steedos/steedos-platform/assets/41402189/adb0ed70-62d1-42b7-93e8-414e26a63cd9">

### Steps To Reproduce 重现步骤

1、进入 编辑lookup类型对象字段设置中
2、点击 高级 一栏
3、点击 外键字段 的弹出选项窗口

### Version 版本

2.6.8-beta.3

**Comment by hotlong** [comment]
最简单的改法，是把相关的提示信息改短一点。

**Comment by tujiajun** [comment]
修改css,自动向下撑开
<img width="1121" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/a9a32e50-bc1e-4e7e-99b5-1ec3fd85fefa">
