### ISSUE TITLE
[Task]: 界面上配置字段置填充规则时，要填充到的字段(to)选项清单应该根据选中的from字段的字段类型过滤

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6496]
### SubTasks 子任务

- 原任务：[Feature]: lookup (master/detail) 字段上支持配置填充规则 #5531
- 比如from设置为日期类型字段时，to字段的可选项就应该只包括日期字段类型，目前是始终列出当前对象中的所有字段类型。
![image](https://github.com/steedos/steedos-platform/assets/6219465/614d5ea5-1bbf-429c-b1bd-fda7610e99eb)

**Comment by tujiajun** [comment]
该规则可能限制太大，考虑按照字段类型给予不同的过滤限制

- 文本，长文本 -> 文本，长文本
- 复选框，开关 -> 复选框 , 开关
- 数值，金额 ->数值，金额
- 相关表关系，主/子表关系 -> 相关表关系，主/子表关系（要额外判断refrence_to,refrence_to_field相同 或者 直接不判断）
- 自动编号 ->自动编号，文本，长文本，富文本
- 网址 ->网址，文本，长文本，富文本
- 邮件地址->邮件地址，文本，长文本，富文本
- 选择框与公式,累计汇总直接认data_type
- 其余字段依旧按照目前规则，只能选择类型相同的字段
