### ISSUE TITLE
[Bug]: 删除累计汇总过滤条件字段配置时，删除确认框被遮住了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6497]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/3ea858b1-390e-4434-a02a-38025caf570f">

### Steps To Reproduce 重现步骤

1、新建累计汇总字段并且设置一条过滤条件；
2、点击过滤条件行记录的删除按钮

### Version 版本

2.6.8-beta.4

**Comment by tujiajun** [comment]
重复
#6502
