### ISSUE TITLE
[Bug]: 页面布局-字段tab页下设置字段分组时，分组下拉框被遮住了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6498]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/624fd5dd-9ab4-497e-a9c1-46edda382193">

### Steps To Reproduce 重现步骤

1、管理员进入后台对象-页面布局；
2、字段tab页下设置字段分组时，分组下拉框被遮住了

### Version 版本

2.6.8-beta.4

**Comment by lizheng-steedos** [comment]
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/29819740-c467-4e50-8be8-767cb3b203ff">

**Comment by tujiajun** [comment]
主要考虑通过popOverContainerSelector属性解决，该属性可修改下拉框的选择项的dom位置，解决弹框遮挡问题
方案：
- 统一挂载位置为body，但若是想在dialog内显示，需要增加z-index，而下拉框内的新增按钮会导致选择项浮在弹框上方，目前暂不会受到影响，因为内核暂未支持下拉框内的新增
<img width="717" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/4816ab7e-8049-4138-b4b5-1e05f1e36741">

-  只处理steedos-input-table组件内的下拉框字段，在steedos-input-table中始终不支持下拉框内的新增按钮

-  仿照之前的过滤字段的处理方式，给外层dialog增加类名，使用dialog外的滚轮，缺点是影响较大，几乎所有的dialog都需要如此
<img width="1296" alt="image" src="https://github.com/steedos/steedos-platform/assets/127007861/a28049e1-9005-4330-bdce-fbf4cbd418cf">

**Comment by tujiajun** [comment]
获取到当前input-table所处的popOverContainer（可能是modal-dialog中），给所有的下拉框字段配置popOverContainerSelector，使下拉框组件的弹出框挂载到当前dialog上，防止被dialog遮挡
