### ISSUE TITLE
[Bug]: 修改选择框字段名称后，选择项显示名称也变成字段名称了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6500]
### Description

修改之前：
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/0f419aa1-d7b4-4bad-99d4-7ab6647ad156">
修改之后：
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/01b84ce3-f726-41c8-acef-0f740e078add">

### Steps To Reproduce 重现步骤

1、管理员后台创建选择框类型字段后保存；
2、编辑刚刚创建的选择框类型字段，修改字段显示名称，就可以看到效果

### Version 版本

2.6.8-beta.4

**Comment by tujiajun** [comment]
https://github.com/baidu/amis/issues/9653

**Comment by yinlianghui** [comment]
流程设置详细页面的字段设置功能中右上角设置字段按钮弹出窗口申请单子表“显示的字段”列重写了子表列的amis属性，所以不可以使用上面字段名加前缀的方案。
换了方案，单元格不使用quickEdit属性即可避开此amis bug了。
<img width="866" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/1e49f362-8adf-42ed-b350-5a327dc6c1e5">
