### ISSUE TITLE
[Bug]: 字段设置界面切换字段类型时，应清空默认值属性值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6508]
### Description

比如字段类型最开始时日期，而且配置了默认值，此时如果切换到文本类型的话，默认值未清除
<img width="1123" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/2f671297-68c8-4331-87ea-f2823d0114df">

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.x

**Comment by hotlong** [comment]
类似需求不好处理，可以考虑禁止切换字段类型
