### ISSUE TITLE
[Bug]: 时间字段默认值配置为公式NOW()时保存的字段值，日期部分不应该为当天

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6509]
### Description

如图，默认值公式配置为`${NOW()}`
<img width="822" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/507ff5fb-1f23-4ce4-a5ac-f266bcec0a45">
但是保存的结果为并不符合魔方平台对time类型的规范，如图：
虽然界面上看到的保存后的时候值是对的，但是它保存到服务端的值并不符全time类型`1970-01-01 hh:MM:ss`的规范，而且值中带时区了（即差8小时）。
<img width="1008" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/86bb21b0-a4ff-4411-8b9d-8251ab9e4abf">

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.x

**Comment by yinlianghui** [comment]
如果不使用上面的NOW公式，而是使用amis的time控件输入静态值的话，就没有上面的问题。
<img width="555" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/a3e09c6d-ff26-4f3f-923c-f2c5ae8320e2">

<img width="490" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/f8f02d9c-902b-4a3b-b738-aabca23f3229">

**Comment by hotlong** [comment]
时间类型字段，加上 valueOut 格式化？

**Comment by yinlianghui** [comment]
测试失败，并没有进新加的默认值debugger断点，且新建记录后字段值依然带上了小时分秒值：
![image](https://github.com/steedos/steedos-platform/assets/6219465/5e4b4413-1fa0-4748-a536-bd8eda781af3)

**Comment by yinlianghui** [comment]
是因为没完全build整个前端项目，经测试包括时区在内都是完全没问题的。
