### ISSUE TITLE
字段修改历史只记录原始值与新值不同的记录

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#651]
比如编辑了一条记录，只修改了一个字段，出来5页，原始值和新值全是空白，因为没改。

重现了，“收到标书”表和“批价问题”表是相关表的关系，我在编辑“收到标书”的记录时，新增了一条批价问题，然后字段修改记录里面，就把所有的字段都列出来了

**Comment by sunhaolin** [comment]
重现方法： 刚新建的记录立马编辑什么都不改然后保存
