### ISSUE TITLE
[Bug]: 日期类型字段，配置默认值使用公式TODAY()，保存的值多了时间部分

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6512]
### Description

公式配置界面及记录中该字段值保存结果，如图：
并没有按魔方平台日期字段的规范把小时分保存为utc0点。
<img width="444" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/cadeca91-95c9-4240-a17e-1c14e1abb871">
<img width="1007" alt="企业微信截图_9f7e0088-3626-4d07-bc19-c944e02b520a" src="https://github.com/steedos/steedos-platform/assets/6219465/6776c568-1cb4-45f4-b140-a89327351d28">

日期控件设置出来的静态值保存的结果是符合魔方平台规范的，它把小时分秒都保存为utc 0点了，如图：

<img width="670" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/956169bb-430b-405c-9f1b-82ae1a26ca5c">

<img width="1139" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/ea012b7e-a629-441c-83f9-4369002f3886">

### Steps To Reproduce 重现步骤

如题，此问题只在日期类型字段有问题，日期时间是正常的，时间类型的问题也有类似问题，见：[Bug]: 时间字段默认值配置为公式NOW()时保存的字段值不符合魔方平台中的time类型规范 #6509

### Version 版本

2.6.x

**Comment by hotlong** [comment]
日期类型字段，加上 valueOut 格式化？

**Comment by yinlianghui** [comment]
测试失败，并没有进新加的默认值debugger断点，且新建记录后字段值依然带上了小时分秒值：
![image](https://github.com/steedos/steedos-platform/assets/6219465/5e4b4413-1fa0-4748-a536-bd8eda781af3)

**Comment by yinlianghui** [comment]
是因为没完全build整个前端项目，经测试包括时区在内都是完全没问题的。
