### ISSUE TITLE
[Feature]: 服务端执行默认值公式时，忽略amis前端公式格式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6514]
### Summary 摘要

当字段只读时并设置了默认值的话，会不提交到服务端，此时字段上配置的默认值会在服务端按公式执行，而公式有两种：
- amis 公式
- 服务端字段公式

目前现状：
- 识别到`${`开头的就按amis公式来执行，其中静态默认值不需要用引号括起来，比如`abc`不应该写为`"abc"`
- 否则按服务端字段公式来执行，其中静态默认值必须用引号括起来，比如`abc`，应该写为`"abc"`

改为：服务端不要识别amis公式，即始终按服务端字段公式来执行，也就是说其中静态默认值必须写为`"abc"`这种带引号的格式。

#### 如果字段是纯只读的，即所有用户对该字段的编辑权限一样时
可以有两种方式配置字段默认值：
- 默认值写为服务端字段公式格式，它只在服务端生效，字段配置为readonly，此时静态默认值必须写为`"abc"`这种带引号的格式。
- 默认值写为amis字段公式，它只在前端生效，字段必须配置为static，且readonly必须为false，此时静态默认值不需要用引号括起来，比如`abc`不应该写为`"abc"`

#### 如果字段是纯可编辑的时
应该把默认值配置为amis公式，它只在前端生效，此时静态默认值不需要用引号括起来，比如`abc`不应该写为`"abc"`。

#### 如果字段是有权限规则，即不同的用户对该字段编辑权限不一样时
_**【暂时没解决方案，以后遇到再说】**_
此时把默认值配置为amis公式，字段必须配置为static，让它始终只在前端生效也不能解决问题，因为权限上的只读是前端uiSchema接口都不返回此字段的字义，所以无法解决。

### Why should this be worked on? 此需求的应用场景？

简化字段默认值规则。

**Comment by hotlong** [comment]
我理解只需要删除掉新增的服务端 amis 默认值计算，其他都维持原状。

**Comment by yinlianghui** [comment]
57d325ce35a7a37d584075ca5c5c18294227d92e

**Comment by yinlianghui** [comment]
忽略的方式是，识别到默认值公式中包含`${`时就认定为是amis公式，此时直接忽略不执行此公式同时不设置字段默认值。
