### ISSUE TITLE
[Bug]: 字段配置 hidden 属性未生效

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6515]
### Description

- [ ] 配置 字段 hidden 时，前端不应该显示此字段。（修改 uiSchema?)
- [ ] 设计字段布局时，对于隐藏分组的字段，应该同时设置 hidden = true，非隐藏分组的字段，设置 hidden = false

### Steps To Reproduce 重现步骤

- 配置系统字段 hidden
- 预览对象，还是能看到此字段

### Version 版本

2.6.8

**Comment by tujiajun** [comment]
- [ ] 在对象表单中，若勾选了必填，则去除隐藏属性的勾选；若勾选了隐藏属性，则去除必填属性的勾选
- [ ] 在设计字段布局中，隐藏分组规则参考#5917

**Comment by hotlong** [comment]
出问题是因为数据库中有字段权限
