### ISSUE TITLE
[Feature]: 作废 defaultValue 在服务端计算，只在前端计算

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6530]
### Summary 摘要

目前版本，新增记录时，对于前端的只读字段不会提交到服务端，服务端在保存时，会在服务端计算 defaultValue
内核和项目相关代码要集中排查。

### Why should this be worked on? 此需求的应用场景？

开发

**Comment by yinlianghui** [comment]
换成任务：https://github.com/steedos/steedos-platform/issues/6657
