### ISSUE TITLE
[Feature]: 对象新增自定义属性；新增重置按钮

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6537]
### Description

- [ ] 对象上的系统字段属性依然为true，按道理自定义后写到库里，这个属性应该为false吧
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/c2b285d9-28e1-4897-bacd-ddf7a898ac11">

- [ ] 自定义后，不能删除同步到数据的数据:  **对象添加重置按钮, 重置对象时,将字段也重置. 重置:将db中的当前对象信息字段星系全部清理掉.**
- [ ] <img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/0533e1aa-2346-47cd-b074-8dfb908353b6">

- [x] 还有个问题是尽管自定义过对象，但是object.yml上新增的分组配置还是会优先加载代码的配置

### Steps To Reproduce 重现步骤

代码的对象通过页面自定义到库里

### Version 版本

2.6.8-beta.6

**Comment by baozhoutao** [comment]
1 元数据deploy时 , 如果源文件中没有extend属性, 则清空extend属性.
2 元数据retiveve时, 如果源文件中没有extend属性, 但db中有extend属性, 则抛错 「 对象不能被标记为扩展(extend), 请先deploy后, 再进行操作 」

3 对象添加只读 extend 字段, 并显示, 其值在 对象是db中定义的, 且extend = true 时 ,才显示为true. 其他情况均显示为 false

**Comment by baozhoutao** [comment]
方案:
- 对象、对象字段添加 自定义属性, 并在列表显示,  retiveve 时, 不给文件中写入自定义属性. deploy 时 ,将自定义设置为true
