### ISSUE TITLE
[Bug]: 修改 steedos-packages/webapp-accounts/webapp/src/i18n/ 目录下的语言包未生效

### ISSUE THREAD

**Issue by forcemeter** [steedos/steedos-platform#6545]
### Description

修改语言包以后执行 `yarn run build`，页面未生效，目前定位是指定的文件没有构建。

![image](https://github.com/steedos/steedos-platform/assets/56063441/88efba09-5117-4251-b498-2fc5e1cf3efe)

### Steps To Reproduce 重现步骤

1. 修改 steedos-packages/webapp-accounts/webapp/src/i18n/ 
2. 执行构建 yarn run build
3. 观察steedos-packages/webapp-accounts/public/static/js/main.2e5d7808.js 未变化

### Version 版本

CE:2.6

**Comment by hotlong** [comment]
<img width="1188" alt="企业微信截图_1bf96c7c-399b-4db4-92f8-fa6bff81861b" src="https://github.com/steedos/steedos-platform/assets/50353452/b6a1b4b0-6c07-40a1-b53e-b435ff44a2b9">

**Comment by forcemeter** [comment]
确认，mac 下正常。
