### ISSUE TITLE
[Bug]: 台账记录中右上角查看审批单按钮点开后的页面顶部显示为空白了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6549]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/a9ff4ff0-0182-41fe-a8c6-636f95b5776c)

### Steps To Reproduce 重现步骤

如题

### Version 版本

v2.6.8-beta.13

**Comment by hotlong** [comment]
是 steedos-ee 项目的问题吧？ approve_workflow 这个应用有吗？

**Comment by yinlianghui** [comment]
> 是 steedos-ee 项目的问题吧？ approve_workflow 这个应用有吗？

跑的platform安装合同应用，自定义应用中没这个问题。
![image](https://github.com/steedos/steedos-platform/assets/6219465/bceb7e60-d3bf-4e54-a4cb-b0c47273cb11)
