### ISSUE TITLE
[Bug]: saas模式应用下的审批菜单监控箱问题

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6550]
### Description

工作区管理员：
- 能看到监控箱菜单和对应流程分类和流程；
- 点监控箱菜单能看到所有流程（正常）
- 但是点流程分类以及流程右侧不会展示对应流程，这个有问题

普通管理员：
- 完全看不到监控箱菜单

### Steps To Reproduce 重现步骤

流程分类分类绑定应用A，并且A应用放出审批菜单，同时对应流程分类有流程数据

### Version 版本

 2.6.8-beta.13

**Comment by baozhoutao** [comment]
<img width="1314" alt="image" src="https://github.com/steedos/steedos-platform/assets/6194462/76dad8e8-36d9-4086-90ac-2e91a8a2fd50">
未能重现.

**Comment by baozhoutao** [comment]
普通管理员: 简档是admin的用户.

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/ee18013a-d3d0-45af-9705-42343d8dca02)


简档是admin的用户 监控箱菜单也正常.
