### ISSUE TITLE
[Bug]: 对象表单initapi失效

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#6551]
### Description

1、将版本从2.5.13更新到2.6.6.
2、新建对象表单界面并在对象表单中设置initApi属性。
3、请求init接口成功之后，对象表单界面无法显示对象字段。
![image](https://github.com/steedos/steedos-platform/assets/34770813/3784a126-68b8-4a85-be4d-30702d215015)

![image](https://github.com/steedos/steedos-platform/assets/34770813/ee5d8a0a-a971-4e9b-8bd1-299668af0a61)

### Steps To Reproduce 重现步骤

{
  "type": "service",
  "body": [
    {
      "type": "steedos-object-form",
      "label": "对象表单",
      "objectApiName": "work_data__c",
      "recordId": "${recordId}",
      "className": "",
      "id": "u:b3d626885b90",
      "enableTabs": true,
      "mode": "edit",
      "layout": "normal",
      "actions": [
        {
          "label": "获取当前位置",
          "type": "button",
          "actionType": "drawer",
          "drawer": {
            "position": "bottom",
            "body": {
              "type": "iframe",
              "onEvent": {
                "detail": {
                  "actions": [
                    {
                      "actionType": "setValue",
                      "componentId": "form_work_data__c",
                      "args": {
                        "value": {
                          "sign_address__c": "${sign_address}",
                          "longitude__c": "${longitude}",
                          "latitude__c": "${latitude}"
                        }
                      }
                    }
                  ]
                }
              },
              "src": "/map.html"
            }
          },
          "level": "info",
          "id": "u:74f463ee42e5"
        },
        {
          "type": "button",
          "label": "保存",
          "actionType": "submit",
          "level": "info",
          "id": "u:4b385487e8e2"
        }
      ],
      "onEvent": {
        "submitSucc": {
          "actions": [
            {
              "actionType": "drawer",
              "drawer": {
                "position": "top",
                "body": {
                  "type": "spinner",
                  "show": true,
                  "size": "lg",
                  "tip": "提交成功，正在返回首页...",
                  "className": "absolute inset-0 text-white font-extrabold text-2xl flex items-center justify-center"
                },
                "actions": []
              }
            },
            {
              "actionType": "custom",
              "script": "function redirectIndex() {\n  //返回首页\n  const url = event.data.context.rootUrl +'/app/home' \n  window.location.replace(url)\n}\nsetTimeout(redirectIndex, 3000);"
            }
          ]
        }
      },
      "tabsMode": "tiled",
      "initApi": "/api/form/initData"
    }
  ],
  "data": {
    "objectName": "work_data__c",
    "context": {
      "initialValues": {},
      "rootUrl": "http://127.0.0.1:5000",
      "tenantId": "659def0640f2871df4d868da",
      "userId": "659deefe40f2871df4d868d8",
      "authToken": "db6bf19895c503548aa56831a1d326de3006ebaf08298fd7c25963147ca8322fa0393e2c55ec74e90238e3"
    }
  },
  "name": "page_work_data__c_form",
  "id": "u:3817d1d4ac65",
  "asideResizor": true,
  "pullRefresh": {
    "disabled": true
  },
  "asideSticky": false,
  "style": {
    "background": "#ffffff"
  },
  "asideMinWidth": 160,
  "asideMaxWidth": 350,
  "onEvent": {
    "init": {
      "weight": 0,
      "actions": []
    }
  },
  "css": {
    "@media (max-width: 767px)": {
      ".antd-Number-input": {
        "border": "var(--Form-input-borderwidth) solid var(--Form-input-borderColor)",
        "border-radius": "var(--Form-input-borderRadius)"
      }
    }
  },
  "@media (max-width: 767px)": "@media (max-width: 767px)-3817d1d4ac65"
}

### Version 版本

2.6.6

**Comment by yinlianghui** [comment]
### 原因：
#### 魔方2.5版本
ObjectForm的内置的数据初始化请求记录接口是放在最终生成的amis form的上层service的api属性中，而amis form的 initApi 属性值是空值，给ObjectForm组件上配置initApi属性是拼接到amis form中的（而不是内置初始化接口所有的上层service中），关键在于ObjectForm组件在初始化接口中会维护editFormInited属性（用于标记初始化接口请求完成），在editFormInited为true时，表单内的字段才会显示出来。
#### 魔方2.6版本
ObjectForm的内置的数据初始化请求记录接口是放在最终生成的amis form本身的initApi属性中，不再放到上层的service组件的api属性中，当为ObjectForm组件上配置initApi属性时，就会重写组件内置生成到amis form的initApi属性，关于在于初始化接口中维护的editFormInited属性一起从上层service组件迁移到amis form本身了，所以需要自行处理维持组件的editFormInited属性值。
#### 相关源码
https://github.com/steedos/steedos-widgets/blob/3.6/packages/@steedos-widgets/amis-lib/src/lib/converter/amis/index.js#L519


### 基于当前魔方2.6版本处理方法
#### 方案一：直接设置editFormInited初始值为true，不再让初始化接口请求完成后才显示表单字段
注意从魔方2.6开始要重写ObjectForm生成的amis form中任何属性不再建议直接写在组件本身，而是用一个名为form的属性包一层，以下是此方案的关键代码。
```
{
  "type": "steedos-object-form",
  ...
  ...
  "form": {
    "initApi": "${context.rootUrl}/api/v1/sum_test__c/6543051eadf8d9d27b66badd?fields=[%22name%22]",
    "data": {
      "editFormInited": true
    }
  }
}
```

#### 方案二：initApi不写为url，而是对象格式，并参考上面提到的ObjectForm源码配置发送适配器和接收适配器属性
方案一的好处是简单，但是因不再维护editFormInited属性，所以不再有初始接口请求完成后才显示表单内字段的能力，如果没有发现其它bug的话，可以用方案一。
以下是方案二的关键代码示例：
```
{
  "type": "steedos-object-form",
  ...
  ...
  "form": {
    "initApi": {
      "method": "get",
      "url": "${context.rootUrl}/api/v1/sum_test__c/6543051eadf8d9d27b66badd",
      "data": null,
      "requestAdaptor":"return api;",
      "adaptor": "return payload;"
    }
  }
}
```

#### 方案三：使用ObjectForm新功能formDataFilter使用js脚本定制最终生成的amis form
设置器中选中对象表单组件，右侧属性`高级-Form`中编写的就是formDataFilter属性。
![image](https://github.com/steedos/steedos-platform/assets/6219465/cc68b3a8-04ee-4ec9-8d95-5a1bb55ed056)
