### ISSUE TITLE
[Bug]: 新建字段时字段类型选择项下拉框没有搜索功能了，之前是有的

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6552]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/016aa1ae-d7b7-4d1e-a43d-79c97ff38498)

### Steps To Reproduce 重现步骤

如题

### Version 版本

v2.6.8-beta.13

**Comment by tujiajun** [comment]
对象字段表单在微页面中对type的amis属性进行了扩展，会覆盖yml文件中配置的amis属性，因此要在表单微页面加上yml文件中的配置
![image](https://github.com/steedos/steedos-platform/assets/127007861/aedb5d57-83fe-4225-8cd7-6d1c7fc5f8e0)
![image](https://github.com/steedos/steedos-platform/assets/127007861/d71f07ca-2643-4dd9-8472-966c97372b81)
