### ISSUE TITLE
[Feature]: password字段，显示时固定显示6个星号

### ISSUE THREAD

**Issue by tujiajun** [steedos/steedos-platform#6556]
### Description

![image](https://github.com/steedos/steedos-platform/assets/127007861/c635e276-2500-4922-bbc7-55b3d5bda231)

### Steps To Reproduce 重现步骤

1、新建一个子表组件
2、给子表组件的fields配置一个password字段，比如
```
{
"type": "password",
"name": "mima"
}
```
3、查看该子表组件的只读状态

### Version 版本

2.6.8-beta.15

**Comment by tujiajun** [comment]
原因是amis的input-password组件在静态模式时，revealPassword属性不生效
![image](https://github.com/steedos/steedos-platform/assets/127007861/6bbf009e-2ac0-467f-9022-154db17b79bb)

**Comment by hotlong** [comment]
对于密码字段，静态模式时，不要传入真实的密码，固定的传入几个*号。
