### ISSUE TITLE
[Bug]: object-from 不支持重写字段的 readonly & static 属性

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6563]
### Description
字段配置readonly为true时，在object-from编辑状态重写字段readonly为false时，填值保存，无法将值写入数据库

现象：
![image](https://github.com/steedos/steedos-platform/assets/129827462/db3c5b66-7396-45b9-be64-1d9364513986)
填值，点击确认按钮
![image](https://github.com/steedos/steedos-platform/assets/129827462/efafbe60-517c-4945-b512-1fc7c806af7b)
无法将值写人数据库
![image](https://github.com/steedos/steedos-platform/assets/129827462/3d9951a9-ddee-46d7-b6ce-e8a0c6114022)
![image](https://github.com/steedos/steedos-platform/assets/129827462/5ebf96d4-2754-4a37-9ff6-5aa470357627)

### Steps To Reproduce 重现步骤

1、对象存在readonly为true的字段，
2、在对象表单组件中，重写readonly属性为false，
3、填值，点击确认按钮

### Version 版本

 2.6.8-beta.15

**Comment by hotlong** [comment]
我理解 readonly 字段不应该在 object-form 中重写。

**Comment by yinlianghui** [comment]
此需求需要先确认下，在字段上配置`visible_on: "{{global.mode ==='read' ? true : false}}"`和`static:true`是否能解决问题，原则上不应该在object-form在重写字段的readonly属性

**Comment by ysc1234** [comment]
https://github.com/steedos/steedos-platform/issues/6568
