### ISSUE TITLE
[Bug]: 自动打包脚本，版本一致停留在beta.16没有更新

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6564]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/061f37eb-3db3-4bd8-8c37-17fb1f992e2b)
![image](https://github.com/steedos/steedos-platform/assets/15027092/ea7107ef-39ed-4152-a5b2-0019ee80dee2)

### Steps To Reproduce 重现步骤

打tag后自动发包可见

### Version 版本

2.6

**Comment by baozhoutao** [comment]
先在2.6分支编译docker
