### ISSUE TITLE
[Bug]:  列表视图翻页异常, 在非第1页时刷新浏览器后, 无法直接翻到第1页.

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6576]
### Description

如题

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by yinlianghui** [comment]
在列表上先跳转到第二页，然后点击某条记录记录详细页面，再点左上角返回按钮返回列表后，此时按需求正常保持在第二页，但是一样会出现如题所示的翻不回第一页的情况。
结合issue: [Bug]: amis 3.6列表视图界面点击翻页页码偶发翻不过去的情况 #6173 一起分析下解决方案

**Comment by yinlianghui** [comment]
此问题是因为crud的defaultParams属性有bug，当时是为了设置列表的perPage值，直接换成用perPage属性即可。
