### ISSUE TITLE
[Bug]: 客户端点击相关文件中的附件，报错"Accounts is not defined"

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6577]
### Description

![image](https://github.com/steedos/steedos-platform/assets/15027092/74fc5556-ca1a-4260-a162-4fa36acd5a90)

### Steps To Reproduce 重现步骤

1、客户端访问公文处理，
2、点击相关文件，点击弹出的窗口中点击附件，报错

### Version 版本

2.6

**Comment by hotlong** [comment]
这个改动如果需要重新发客户端的话，那尽量还是兼容以前的代码
