### ISSUE TITLE
[Feature]: 选项卡，外部链接配置为相对地址时，手机App打开显示白屏

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6580]
### Summary 摘要

费控王集成数据分析平台的方式是配置 url 类型的选项卡，指向 `/analytics/embed/dashboard/65ab3adf4bab3305be0caa8c%23titled=false&bordered=false`

### Why should this be worked on? 此需求的应用场景？

手机app，连接费控王

**Comment by baozhoutao** [comment]
此问题不可以使用gitpod环境进行测试.
![image](https://github.com/steedos/steedos-platform/assets/6194462/f9451a83-94df-4d75-874c-d5f27af659d8)

**Comment by baozhoutao** [comment]
真机效果
<img width="327" alt="image" src="https://github.com/steedos/steedos-platform/assets/6194462/a3ff3833-6ebf-442f-8fcd-809a8d20a57f">
