### ISSUE TITLE
[Feature]: 对象新增开关，支持跨租户共享对象数据

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6604]
### Summary 摘要

- [x] 对象新增开关，支持跨租户查询数据
- [x] 查询数据时，可返回所有租户的数据

### Why should this be worked on? 此需求的应用场景？

saas

**Comment by baozhoutao** [comment]
- 需要单独搭建一个平台来维护共享对象的数据.
- 目前可以通过自定义对象权限开启 对象的写入权限.  可临时将对象设置为hidden true, 不让其选择到此对象, 但是还存在通过接口的方式重写共享对象权限.

**Comment by baozhoutao** [comment]
对象添加属性: `enable_space_global`
