### ISSUE TITLE
[Bug]: 手机端列表没有操作权限时应该隐藏下拉菜单按钮

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6605]
### Description

![image](https://github.com/steedos/steedos-platform/assets/151509384/d46c5f87-ef6e-4401-b77c-670b3faff365)

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.7.0-beta.6

**Comment by hotlong** [comment]
每个按钮的显隐是单独控制的，没有办法在显示列表时统一判断
