### ISSUE TITLE
[Feature]: 公式和累计汇总字段被触发计算后，自动触发该公式字段所属对象的触发器及工作流规则

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6609]
### Summary 摘要

要考虑的点：
- 此需求是希望在子表新建编辑记录时，触发了主表上的公式和累计汇总字段后，能进一步触发主表记录的对象的触发器及工作流规则
- 要考虑触发次数，避免不必要的重复触发，比如直接更新主表记录时本身就会触发主表对象的触发器及工作流规则，如果再因为公式及累计汇总重复触发就多余了
- 是否要在公式和累计汇总字段上增加开关来控制是否触发，就像字段重新上的开关一样，如图

![image](https://github.com/steedos/steedos-platform/assets/6219465/3a6a45aa-b8ca-4d88-9ff8-01cd0e5fe2d8)

### Why should this be worked on? 此需求的应用场景？

项目上的原始需求：在某个记录详细页面新建编辑子表记录后，会触发当前主表记录的累计汇总及公式字段重算，但是并不会触发主表对象的工作流规则（比如工作流通知）及对象触发器

**Comment by hotlong** [comment]
重复 https://github.com/steedos/steedos-platform/issues/6609
