### ISSUE TITLE
[Feature]: 列表页loading时会先模糊一阵、然后再清晰，希望改掉

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#6614]
### Summary 摘要

例如审批的监控箱里，比较明显
有用户提出，希望改掉、无需先模糊
https://github.com/steedos/steedos-project-hbport/issues/635

### Why should this be worked on? 此需求的应用场景？

有用户，审批王里使用体验后提出

**Comment by tujiajun** [comment]
暂时在项目内实现，平台改动待定
