### ISSUE TITLE
[Bug]: 审批单中附件字段，未校验是否必填

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6618]
### Description

设置必填后需填写，并提示

### Steps To Reproduce 重现步骤

1.审批单增加附件类型字段，设置为必填
2.发起审批，此字段未填，也可提交
3.大众燃气 供应商准入流程--“未被处罚证明”字段

### Version 版本

2.6

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/b3082485-f9a4-4fe8-91a0-3140e83054ec)
未能重现.

**Comment by baozhoutao** [comment]
问题原因: 表单字段名称为 `file` 时,导致
