### ISSUE TITLE
【零代码】新建字段、操作、相关表时， 如果是saas平台，则禁止添加、修改、删除

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#662]
-108上测试到的
-经查数据库确认会保存
-提示报错时弹出的新建字段窗口也没有自动关掉
![image](https://user-images.githubusercontent.com/6219465/89368089-43c8c800-d70d-11ea-9a0c-61ae89e9ad9b.png)

**Comment by baozhoutao** [comment]
此问题重现方式：
1 先将配置文件中的tenant.saas 设置为false， 在界面添加自定义对象、字段、操作、相关表
2 将tenant.saas 设置为true， 在界面上添加、修改、删除 自定义对象的字段、操作、相关表
