### ISSUE TITLE
[Bug]: 对象记录详情页的打印按钮出不来

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6621]
### Description

已经配置打印模版，并且打印按钮也自定义过，进设计器也重新保存了。

### Steps To Reproduce 重现步骤

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/1546d36a-8010-49ea-b144-9316adc76b30">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/12385e40-b51e-4b98-9f27-8b6eeac2518d">
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/b88bb814-e108-4789-961f-c37588a07a94">

### Version 版本

 2.7.0-beta.6

**Comment by sunhaolin** [comment]
2.7.0-beta.32
