### ISSUE TITLE
[Bug]: 对象权限编辑时，禁用列表视图没有生效，设置后，禁用视图还是可以访问。

### ISSUE THREAD

**Issue by YANJIE122** [steedos/steedos-platform#6628]
### Description

![Uploading 列表827.png…]()

### Steps To Reproduce 重现步骤

对象权限编辑时，禁用列表视图没有生效，设置后，禁用视图还是可以访问。

### Version 版本

2.6.8 2.6.7

**Comment by hotlong** [comment]
对象权限中的列表视图禁用功能在多个权限级合并时会有算法缺陷。下一步考虑作废。
目前建议使用列表视图的共享功能。创建列表视图时可以选择共享给制定组织。
