### ISSUE TITLE
[Feature]: 共享规则支持配置可读写

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6638]
### Summary 摘要

<img width="963" alt="企业微信截图_42b60f27-baf4-4600-9db8-56a578b88e0f" src="https://github.com/steedos/steedos-platform/assets/50353452/de33c203-2cf4-42d7-9e11-22427c7161f4">

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/be142d00-f40c-4013-a736-68020ce1e58a)
