### ISSUE TITLE
[Bug]: 代码加载的限制规则页面自定义调整后，页面就看不到这条记录了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6642]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/372df746-0cf0-4397-ae61-a8118efb871d">

### Steps To Reproduce 重现步骤

1、代码加载到页面的限制规则在页面进行自定义写入到库中；
2、编辑对应显示规则再保存；
3、发现限制规则找不到刚刚的记录了

### Version 版本

 2.7.0-beta.6

**Comment by baozhoutao** [comment]
已无法重现.
