### ISSUE TITLE
[Bug]: 分部绑定部门后，应允许删除

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6643]
### Description

删除分部时提示绑定部门，删除部门时提示绑定分部，就是一个死循环，导致部门和分部都删除不了

### Steps To Reproduce 重现步骤

1、新建分部，绑定一个部门后保存；
2、删除对应分部，提示报错信息；
3、删除绑定的部门，提示报错信息；

### Version 版本

 2.7.0-beta.6

### 解决方案

删除分部后，应该更新对应组织的分部ID

**Comment by hotlong** [comment]
需要确定一下规则

**Comment by yinlianghui** [comment]
- 出现此问题的原因是有任务把分部的关联部门字段改为必填造成的，见： https://github.com/steedos/steedos-platform/issues/2662
- 关联部门字段改为必填前，是要求用户删除前手动设置关联部门字段值为空，本次改动是删除分部时，自动设置关联部门字段值为空，但是不自动更新关联组织的company_id等属性，原因见下一条。
- 按之前的设计，修改分部关联部门值时，需要手动操作一次“更新组织”按钮，所以删除组织也是一样的，要操作一次“更新组织”按钮。
![image](https://github.com/steedos/steedos-platform/assets/6219465/0615b5a3-4daf-4aa8-844d-d5594554e635)
