### ISSUE TITLE
[Bug]: saas环境下用户创建列表视图过滤设置，人员可以选到其他工作区的用户

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6644]
### Description

<img width="1389" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/2c995384-20f3-44da-934e-0e761ab10004">

### Steps To Reproduce 重现步骤

1、普通用户先在前台创建一个列表视图；
2、设置列表视图过滤条件，选择创建人字段后，发现选人可以选到所有工作区的用户数据

### Version 版本

 2.7.0-beta.11

**Comment by hotlong** [comment]
应该是对应的api接口有问题
