### ISSUE TITLE
[Bug]: 人员数据页面导入时，部门（多选）字段导入失败

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6648]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/d2bc36a9-1995-4985-9eff-a94c453753ab">

### Steps To Reproduce 重现步骤

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/05631783-9377-45b9-9bdf-d33fa4a5c7cb">
<img width="1340" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e56b19a9-7b88-4af9-87cf-acbf22e896f1">

### Version 版本

 2.7.0-beta.11

**Comment by sunhaolin** [comment]
这个原因可能是excel列与表头未对应导致，试一下将 excel中 部门(多选) 改为 部门（多选）
