### ISSUE TITLE
[Bug]: 点击头像的展开框，邮件过长时样式乱了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6650]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/99aaa876-3bbc-4a99-a917-2b6e4f470b91">

### Steps To Reproduce 重现步骤

用户邮件设置admin-a@steedos.com试下

### Version 版本

 2.7.0-beta.11

**Comment by hotlong** [comment]
这个是因为邮箱中包含“-”
