### ISSUE TITLE
[Bug]: 代码中的字段页面自定义后通过设计字段布局调整后，同步回代码，相关字段属性都丢了

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6654]
### Description

比如选择框类型字段，下拉值的属性都没了
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/c04d2584-4846-4467-a2a2-4b69ac4fe252">

### Steps To Reproduce 重现步骤

1、代码加载的对象页面自定义；
2、设计字段布局调整字段位置后保存；
3、远程vscode环境同步字段；

### Version 版本

 2.7.0-beta.11

**Comment by baozhoutao** [comment]
如果是要修改本地的软件包对象、字段数据,  请先deploy后修改.
