### ISSUE TITLE
[Feature]: 默认值计算前后端改用amis公式，及计算规则优化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6657]
原则： 

- 字段配置的默认值只在新增数据时生效，编辑时不生效。
- 支持静态默认值和使用amis表达式编写默认值。amis表达式中可以引用 global.user 变量，不可引用当前记录中的字段。
- 新建记录时，如果表单中的字段配置了默认值，自动赋值。
- 新建记录时，如果字段有默认值且未传入数据（主要指只读和隐藏字段），在服务端计算默认值。
- 服务端计算默认值时，作废 salesforce 公式引擎，只使用 amis 公式引擎
- 前后端公式兼容替换 {now}, {userId}, {spaceId} 旧的语法
- 前后端公式兼容替换'"xxxx"'类似的旧版字符串格式。

### 服务端

- [x] 支持静态默认值，如果是bool, 数值，数组类型，直接取值，不计算。
- [x] 如果是function，服务端始终不执行。
- [x] （兼容）如果是字符串类型，删掉前后的双引号再计算，以兼容原来服务端sf公式静态默认值写法。【只处理了服务端，因为前端不存在兼容需求】
- [x] （可选）如果是字符串类型，如果包含 ${}包裹的文本 ， 则认定为amis公式，调用amis公式引擎，否则直接返回字符串。
- [x] 服务端计算默认值时，作废 salesforce 公式引擎，只使用 amis 公式引擎
- [x] 前后端默认值公式引擎中只支持 global.user.xxxx 变量，不支持表单上的字段。
- [x] 在 objectql.insert 函数中判断，如果字段未赋值，则计算默认值。
- [x] 兼容替换 {now}, {userId}, {spaceId} 旧的语法

### 前端

- [x] 默认值公式编辑器中支持选择 global.user 变量
- [x] 前端默认值计算时，amis表达式中可以引用 global.user 变量，不可引用当前记录中的字段。

**Comment by yinlianghui** [comment]
尝试前端运行公式报错时提示错误信息，没找到方案（这点之前一直是这样的，先不管，问题在于没找到catch错误的地方），后台已做到出错时抛错提示错误信息并中止执行新建记录。

**Comment by yinlianghui** [comment]
除了”支持公式编辑器选择 global.user 变量“之外，其它都改的platform，核心代码如图：
<img width="874" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/b73bc66f-3d50-4825-84c1-71091d74d3ef">

**Comment by tujiajun** [comment]
未将所有$加上\\转义
![image](https://github.com/steedos/steedos-platform/assets/127007861/621afc99-76a3-4be1-a522-7671ce3bce3d)
![image](https://github.com/steedos/steedos-platform/assets/127007861/e58673e1-f8c3-4681-bd7e-69069cba8304)
![image](https://github.com/steedos/steedos-platform/assets/127007861/dc4a8444-cedc-4416-98e1-8b2b610af325)

**Comment by yinlianghui** [comment]
> 未将所有$加上\转义 ![image](https://private-user-images.githubusercontent.com/127007861/318190431-621afc99-76a3-4be1-a522-7671ce3bce3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzkwNzQsIm5iZiI6MTcxMjQ3ODc3NCwicGF0aCI6Ii8xMjcwMDc4NjEvMzE4MTkwNDMxLTYyMWFmYzk5LTc2YTMtNGJlMS1hNTIyLTc2NzFjZTNiY2UzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODMyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2JiY2VhNjliODg0YzNiNjQxOGViYTFlNGI0ZjVjODUyNmNkODYyMWUzMjkzM2M3YzkyMDYyYmRiYTdiNGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x_v_VZN2yMS0VPAzpsOTwlb2ljfb3rJP06HGZ9r1uGE) ![image](https://private-user-images.githubusercontent.com/127007861/318190439-e58673e1-f8c3-4681-bd7e-69069cba8304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzkwNzQsIm5iZiI6MTcxMjQ3ODc3NCwicGF0aCI6Ii8xMjcwMDc4NjEvMzE4MTkwNDM5LWU1ODY3M2UxLWY4YzMtNDY4MS1iZDdlLTY5MDY5Y2JhODMwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODMyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjQ3MmNlOTY2ZmQwZjJkZTFjOThlNzE0MTJhNDU1ZjViNDkxYjYxZDM3MDI5MWEzOTU0YTE1NjVmMjZkMDRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v_5eRuUEpdpncffABQn3fnXHBUerMaVo7oBWmowrcrI) ![image](https://private-user-images.githubusercontent.com/127007861/318190449-dc4a8444-cedc-4416-98e1-8b2b610af325.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzkwNzQsIm5iZiI6MTcxMjQ3ODc3NCwicGF0aCI6Ii8xMjcwMDc4NjEvMzE4MTkwNDQ5LWRjNGE4NDQ0LWNlZGMtNDQxNi05OGUxLThiMmI2MTBhZjMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwODMyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjkwZTgzYjNkNjU1ZjdhNzZlOTg1MzIzNWY3ZjkwMTJkY2EyNGYyMGRlODhmNzljNTc5YWJhYTA1Yzg3MmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CqB2GPtvHv9mKMaATqhk9s6Nydu3VA7KX_yMWkl9BTY)

此问题已经另建issue: [Bug]: 为字段设置的默认值公式，其中有多个${}时，在对象字段详细页中的会被解析出来 #6691
