### ISSUE TITLE
[Bug]: 对象列表删除对象会弹出警告提示，关闭警告窗口可以看到对象已经删除掉了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6663]
### Description

刚新建的对象，再返回列表删除这个对象也有问题。
![image](https://github.com/steedos/steedos-platform/assets/6219465/6de6162f-dac4-45ae-8c3d-05ab186589ef)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by baozhoutao** [comment]
去掉对象列表上的批量删除按钮?
