### ISSUE TITLE
[Bug]: 对象的字段分组，第一个会无故折叠

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6679]
### Description

![image](https://github.com/steedos/steedos-platform/assets/25192306/1f2a5fdb-b7eb-446f-8d79-cb5a8fb3a001)

页面上直接创建对象， 第一个分组没有折叠，正常。
但是当把对象 导出成 yml配置文件后，删除数据库中的对象定义，以软件包运行，出现第一个分组折叠的问题

### Steps To Reproduce 重现步骤

1、创建对象
2、配置字段布局，创建分组，拖拽字段布局
3、使用DX 工具导出对象定义
4、页面上删除对象定义
5、重启平台，以软件包方式加载对象的定义
6、访问对象 详情页面、编辑页面， 出现第一个分组被折叠的问题

### Version 版本

2.6

**Comment by hotlong** [comment]
分组上有一个配置，是否折叠。

**Comment by tujiajun** [comment]
此issue之后的版本，会有如下改动：
1、系统对象的“系统信息”分组将不会再默认折叠（若在代码内配置了，不受影响）
2、新建自定义对象时，会增加配置为默认折叠的“系统信息”分组
3、如果需要修改字段分组，可以在设计字段布局内进行修改
