### ISSUE TITLE
[Feature]: 渲染编辑表单时，显示字段的描述字段

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6713]
### Summary 摘要

需要同时考虑横版竖版的表单

### Why should this be worked on? 此需求的应用场景？

开发

**Comment by yinlianghui** [comment]
- 原来字段上的inlineHelpText功能保持不变，显示为鼠标放上去提示。
- 新加一种提示：识别字段上配置的description属性，显示在字段的底部，效果：
![image](https://github.com/steedos/steedos-platform/assets/6219465/4deced0b-b526-4f3c-a511-7ab391605573)

**Comment by yinlianghui** [comment]
竖版效果：
![image](https://github.com/steedos/steedos-platform/assets/6219465/4698aef3-85a2-400a-8176-9b4202db0cc3)
