### ISSUE TITLE
[Feature]: 当 lookup 字段被配置为is_name字段时，点击列表显示的链接，进入记录详情页

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6715]
### Summary 摘要

不要进入 lookup 对象的记录详情页

### Why should this be worked on? 此需求的应用场景？

用户体验

**Comment by tujiajun** [comment]
文本、长文本、自动编号、日期、日期时间、时间、公式、相关表等字段支持配置为is_name字段
