### ISSUE TITLE
[Bug]: 无法删除分部

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6716]
### Description

删除分部，报错，需要先清除关联的 部门。 点开编辑按钮，关联部门是必输项，无法清除。
尝试直接删除对应的 部门， 报错需要先删除关联的 division （分部）

闭环死循环

### Steps To Reproduce 重现步骤

删除分部，报错，需要先清除关联的 部门。 点开编辑按钮，关联部门是必输项，无法清除。
尝试直接删除对应的 部门， 报错需要先删除关联的 division （分部）

闭环死循环

### Version 版本

2.6

**Comment by yinlianghui** [comment]
- 是因为把分部的关联部门字段改为必填造成的，见： https://github.com/steedos/steedos-platform/issues/2662
- 之前报过类似issue，未处理：https://github.com/steedos/steedos-platform/issues/4783

**Comment by hotlong** [comment]
有相关任务，已安排优先 https://github.com/steedos/steedos-platform/issues/6643
