### ISSUE TITLE
[Bug]: 对象权限集，设置单个字段权限的编辑等权限未生效

### ISSUE THREAD

**Issue by YANJIE122** [steedos/steedos-platform#6723]
### Description

想要的达到的效果：同一张表，A权限集用户只能编辑123字段，B权限集用户只能编辑456字段。
问题：配置了A权限集和B权限集用户的不同字段权限的编辑权限，未生效。所有字段都可以进行编辑。

### Steps To Reproduce 重现步骤

1.进入建设清单表对象
2.点击对象权限
3.点击A权限集用户和B权限集用户详情页，点击相关按钮。
4.配置不同字段的编辑权限。
![1](https://github.com/steedos/steedos-platform/assets/54983772/e55f9150-36db-47b1-ad3a-6a4d97754eed)
![2](https://github.com/steedos/steedos-platform/assets/54983772/e27901aa-d328-4dad-b7a0-8c6349b65b73)
![3](https://github.com/steedos/steedos-platform/assets/54983772/9e7e0bd7-da13-4412-b857-0c4f50596a2c)

### Version 版本

版本：2.6.7

**Comment by lizheng-steedos** [comment]
应该是设置的问题 A权限集用户和B权限集用户都是属于user简档的用户，user的对象权限中的字段权限应该是可编辑这几个字段的，所以应该先把user上的字段权限去掉
