### ISSUE TITLE
[Bug]: 对象页面布局的字段显示条件未生效

### ISSUE THREAD

**Issue by YANJIE122** [steedos/steedos-platform#6724]
### Description

配置了页面布局字段显示条件，点击完成后，显示条件有回显，但是点击确认按钮后，配置的显示条件未生效，配置的相关内容也为空值了。

### Steps To Reproduce 重现步骤

配置了页面布局字段显示条件，点击完成后，显示条件有回显，但是点击确认按钮后，配置的显示条件未生效，配置的相关内容也为空值了。

### Version 版本

版本：2.6.7

**Comment by lizheng-steedos** [comment]
最新版2.7.0-beta.27未重现，页面布局字段显示公式配置正常
