### ISSUE TITLE
[Feature]: 系统设置元数据 settings 、keyvalue

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6727]
## settings:  企业级参数配置
字段
- key
- value
- is_public:  如果为true,则可以从前端获取到.

### 按key写入数据: 
- POST `/api/settings/set/:key`
- req.body 中所有数据会被写入value中
- *如果key是以`public_`开头,会自动将is_public设置为true*

### 按key获取数据: 
- GET `/api/settings/get/:key`

## keyvalue: 用户级参数配置
字段
 - key
 - value
 
### 按key写入数据: 
- POST `/api/keyvalue/set/:key`
- req.body 中所有数据会被写入value中

### 按key获取数据: 
- GET `/api/keyvalue/get/:key`

**Comment by hotlong** [comment]
例如设置 key: email 
settings.email.from.server

**Comment by baozhoutao** [comment]
微服务 actions中使用方式:
```
const settings = await this.getSettings(ctx.meta.spaceId);
```

**Comment by baozhoutao** [comment]
前端使用方式:
```
Steedos.settings
```

**Comment by baozhoutao** [comment]
服务端 `require` 
```
const { getSettings } = require('@steedos/utils');
const settings = await getSettings(spaceId);
```
