### ISSUE TITLE
[Feature]: 对象新增属性enable_form_tabs

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6728]
### Summary 摘要

即表单显示为选项卡模式

### Why should this be worked on? 此需求的应用场景？

直接在界面上配置选项卡模式

**Comment by tujiajun** [comment]
- 目前该功能只影响编辑页面，并且会优先识别组件上的enableTabs，若不存在，则识别对象上的该属性
- 若影响只读页面，则会出现如下图的问题
<img width="1213" alt="企业微信截图_b59be514-2338-41db-bebe-99020a57ff9c" src="https://github.com/steedos/steedos-platform/assets/127007861/298b6e65-9400-47ba-9c11-bdecbec24393">
解决方案是将内部的选项卡展示模式更改为如下图
<img width="1227" alt="企业微信截图_164d8455-9856-47f2-88ba-12467b108b7f" src="https://github.com/steedos/steedos-platform/assets/127007861/a74dc5a9-22d9-4517-a77e-e8947646225d">
