### ISSUE TITLE
[Feature]: 支持多选的lookup字段自动填充功能

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6732]
### Summary 摘要

- 目前字段设置界面勾选多选后，自动填充功能就不能配置了
- 改为支持多选的情况：如果配置了多选，比如合同，自动填充合同名称到其它字段，就自动填充多个合同名称值用逗号分隔填充进去
- amis 官网有autoFill功能支持多选情况的示例，理论上下拉和picker模式的lookup字段都可以支持：https://aisuda.bce.baidu.com/amis/zh-CN/components/form/options#%E8%87%AA%E5%8A%A8%E5%A1%AB%E5%85%85-autofill

![image](https://github.com/steedos/steedos-platform/assets/6219465/5608d06d-2c24-4db1-98d1-774627a2e80e)

### Why should this be worked on? 此需求的应用场景？

自动填充功能支持多选

**Comment by tujiajun** [comment]
### 当前字段是多选时
- from可选择的lookup、master_detail、select类型的字段必须为单选，同时to必须为多选；
- 若from是文本等类型，to也必须是文本等类型，并且通过逗号分隔多个选中项值
### 当前字段是单选时
- 若from为多选的lookup、master_detail、select，则to也必须是多选；
- 若from为单选的lookup、master_detail、select，则to也必须是单选；
