### ISSUE TITLE
[Bug]: 累计汇总报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6741]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194462/7def4080-5a2d-4471-8e99-d1d2214ae066)

### Steps To Reproduce 重现步骤

-

### Version 版本

2.7

**Comment by baozhoutao** [comment]
此问题导致提交申请单后, instances_task 未产生记录

**Comment by baozhoutao** [comment]
相关问题: https://github.com/steedos/steedos-platform/issues/6744

**Comment by yinlianghui** [comment]
此问题原因：计算汇总字段时，从doc中拿当前修改了哪些字段名的时候未从当前对象fields中过滤一次，doc中有些字段并不在当前对象中有字段定义，所以需要过滤，只取有对象字段定义的字段名。
