### ISSUE TITLE
[Bug]: 审批王待审核列表丢了需要审批的流程数据

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6744]
### Description

这些我本人待审批的进行中的流程在流程待办列表中都没有
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/5bac2009-4412-4ab5-b2b1-8b57909943cf">

### Steps To Reproduce 重现步骤

1、feikongwang项目
2、差旅台账创建记录并发起流程，选择自己审批

### Version 版本

2.7.0-beta.28

**Comment by baozhoutao** [comment]
累计汇总报错导致, 已修复.
