### ISSUE TITLE
[Bug]: lookup字段配置过滤条件数组中引用了amis公式时存在问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6745]
### Description

问题1：判断是否有amis公式不应该用是否包含$，而应该是用正则判断${}包裹的表达式
![image](https://github.com/steedos/steedos-platform/assets/6219465/37c86933-5532-44f1-9c9a-fb498c9fb79d)

问题2：如果公式运算结果正好是一个字符串数组的话，请求中的过滤条件会把数组转为逗号分隔的字符串
配置方法（遇到此问题的实际项目中不是配置为静态数组，而是一个值为_ids集合的变量）：
<img width="298" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/e33616e8-c47d-4eba-aac3-32de1f00674b">

请求中的filters效果：
<img width="929" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/0480d856-06e4-4e55-b840-7329b7daa391">

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by tujiajun** [comment]
等待版本更新后，若是使用变量引用数组，需要按照${array | toJson}的方式
