### ISSUE TITLE
[Bug]:自定义内核对象后，编辑字段自动填充属性保存后报错提示“字段名不能重复 [supplier]”

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6747]
### Description

虽然保存的时候报错了，但是在进入这个字段详情页已经保存了刚刚提交的配置；但是前台页面也没自动带出的效果（服务重启也没用）
<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/52e4818f-04a8-460f-83b2-aee5bc484fdd">

### Steps To Reproduce 重现步骤

1、feikongwang项目；
2、管理员后台自定义应付合同对象，编辑供应商字段，添加自动填充规则，保存记录会有报错信息

### Version 版本

 2.7.0-beta.29

**Comment by yinlianghui** [comment]
这个问题跟自动填充属性设置功能没关系，是元数据自定义后字段名重复问题：
![image](https://github.com/steedos/steedos-platform/assets/6219465/a71ad117-3553-4837-8851-7d7608c6b66f)
