### ISSUE TITLE
[Bug]: 微页面-相关表组件现在少了调整显示样式的入口

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6752]
### Description

<img width="1440" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e9b3355e-9d34-410b-bc50-0a3b2e011964">

### Steps To Reproduce 重现步骤

feikongwang项目，进入微页面设计器，增加相关表组件

### Version 版本

 2.7.0-beta.30

**Comment by hotlong** [comment]
可能是升级设计器导致的
