### ISSUE TITLE
[Task]: 公文，处理掉待办文件后的返回列表页，作优化

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#6763]
### SubTasks 子任务

- [x] 公文，左侧点击某流程分类，处理完1条改流程分类下的待办文件（为传阅件）后，仍然跳回到 刚才的流程分类的待办列表 （目前，正常处理件会返回刚才的列表；而传阅件会调到整个模块的待办列表）
- [x] 承上，如果返回的列表页 为0条记录，则跳转到整个模块的待办列表

https://github.com/steedos/steedos-project-hbport/issues/686

**Comment by tujiajun** [comment]
该issue在平台与qhd都进行了修改
- 传阅件在处理完之后也会返回到进入详细页之前的列表
- 若列表页在左侧树的流程或分类下为0条记录，且列表上无任何搜索条件时，会自动返回到左侧树的待审核中
