### ISSUE TITLE
[Feature]: 使用 amis 实现附件预览功能 ( 图片、pdf、docx、xlsx）

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6770]
### Summary 摘要

之前只有桌面客户端和配置了预览服务器时支持预览，本地增加默认支持预览。

- [x] 图片
- [x] pdf
- [x] docx
- [x] xlsx

效果
- [ ] 审批王附件、历史版本
- [ ] 华炎魔方附件、历史版本
- [ ] 附件类型字段
- [ ] 桌面端、手机端

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by chenzhipei** [comment]
https://github.com/steedos/steedos-platform/issues/6840

**Comment by chenzhipei** [comment]
已完成：

- [ ] 审批王附件
- [ ] 华炎魔方附件
- [ ] 附件类型字段
- [ ] 浏览器端、手机端
