### ISSUE TITLE
[Bug]: 对象--相关中审批单上的按钮，除“流程图”外，其他点击后都是无效

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6775]
### Description

无用的按钮可隐藏，保障所有按钮点击有效

### Steps To Reproduce 重现步骤

<img width="1349" alt="1713866842071" src="https://github.com/steedos/steedos-platform/assets/7665279/04420c60-8701-448d-b0ae-34add0baee55">

打印：
<img width="557" alt="1713866907529" src="https://github.com/steedos/steedos-platform/assets/7665279/c1789ab3-c2b0-46d5-ab0b-ab20162f74e7">

转发：
![image](https://github.com/steedos/steedos-platform/assets/7665279/ac489786-c317-4cc3-bf40-cb47883bbff4)

### Version 版本

2.7.0-beta.34

**Comment by tujiajun** [comment]
按钮样式问题与改issue有关，审批详细页按钮需单独处理样式#4933
