### ISSUE TITLE
[Bug]: select字段类型通过amis.type重写为radios类型后，记录详细页面只读表单中该字段值显示为option.value了，应该显示为option.label

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6780]
### Description

在微页面中通过fieldsExtend属性重写字段type，一样的配置是正常的，只是在yml文件中配置的有bug

![image](https://github.com/steedos/steedos-platform/assets/6219465/43a59e0b-5004-44cb-a4e3-20d5a652b80e)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by tujiajun** [comment]
只读的下拉框类型是用的static-mapping，若直接更改type，schema会存在问题
若遇到类似问题，可以修改表单微页面
