### ISSUE TITLE
[Bug]: 仪表盘页面手机app上没办法页面滑动

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6782]
### Description

![image](https://github.com/steedos/steedos-platform/assets/151509384/55bfade3-98f7-440e-938b-e396b3281e29)

### Steps To Reproduce 重现步骤

feikongwang项目应收、应付首页，手机真机app端，仪表盘页面

### Version 版本

 2.7.0-beta.31

**Comment by hotlong** [comment]
相关 https://github.com/steedos/steedos-platform/issues/6794

**Comment by baozhoutao** [comment]
iphone 真机

17.4版本
