### ISSUE TITLE
[Bug]: 使用$inc更新记录时未触发相关公式和累计汇总字段重算

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#6791]
### Description

语句：
```js
await oliObj.update(oliId, {
    $inc: {
        overtime_hours: hours
    }
})
```
关联：https://github.com/steedos/steedos-platform/issues/6696

### Steps To Reproduce 重现步骤

如描述

### Version 版本

2.7.1-beta.5

**Comment by yinlianghui** [comment]
考虑了以下update请求中操作类型时公式和累计汇总字段重算功能：
```
'$inc','$min','$max','$mul'
```

测试要点：
- object.update语句中使用$inc等更新操作，如果$inc中影响的字段，正好被当前对象中其它公式字段引用的话，应该正确重算当前对象上相关公式字段值。
- object.update语句中使用$inc等更新操作，如果$inc中影响的字段，正好被其它对象（即跨对象引用）中公式字段引用的话，应该正确重算其它对象上的相关公式字段值。
- object.update语句中使用$inc等更新操作，如果$inc中影响的字段，正好被主表对象中的汇总字段引用的话，应该正确重算相关汇总字段值。
