### ISSUE TITLE
[Bug]: 仪表盘页面通过选项卡链接添加到应用后，仪表盘页面高度超过屏幕高度时，页面显示本身的底纹

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6794]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/995f3a5f-e056-4b4e-844f-8d3fafff1629">

### Steps To Reproduce 重现步骤

feikongwang项目应收应用下的首页菜单

### Version 版本

 2.7.0-beta.31

**Comment by hotlong** [comment]
把原来的背景阴影隐藏就好
