### ISSUE TITLE
[Bug]: amis pdf-viewer 组件预览pdf文件报错

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6796]
### Description

设计器里预览是好的，发布后，前台点击按钮报错
![image](https://github.com/steedos/steedos-platform/assets/15027092/48b669f4-5010-4c3e-8b5f-55c3660a6cdb)

### Steps To Reproduce 重现步骤

1、自定义amis按钮，选择pdf viewer组件
2、设计器里预览是好的
3、发布后，前台点击按钮预览时报错“Failed to load PDF file.”

### Version 版本

2.7

**Comment by baozhoutao** [comment]
原因:  前端在Array原型上扩展的`sortByName, getProperty, remove, filterProperty, findPropertyByPK, getEach, contains, uniq, uniqById`导致`react-pdf`内核报错.

"Error: The `Array.prototype` contains unexpected enumerable properties: sortByName, getProperty, remove, filterProperty, findPropertyByPK, getEach, contains, uniq, uniqById; thus breaking e.g. `for...in` iteration of `Array`s."
