### ISSUE TITLE
[Bug]: 公式字段的公式属性支持 amis 公式，并启用编辑器

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6808]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4e0836d6-d644-4f54-8e0c-2205e8597741">

### Steps To Reproduce 重现步骤

管理员后台进入对象，创建公式类型字段

### Version 版本

2.7.1-beta.7

**Comment by baozhoutao** [comment]
amis公式支持`lookup.field`不支持多层引用
