### ISSUE TITLE
申请单选择关联文件-关联文件弹出框-按流程过滤搜索框输入不了文字

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#681]
![图片已粘贴至2020-8-10 09-47](https://user-images.githubusercontent.com/6194896/89747122-d7284180-daef-11ea-8691-795632cfdc5e.png)

**Comment by baozhoutao** [comment]
解决方案：关联文件窗口禁止通过esc关闭modal，并删除tabIndex 属性，此属性在多modal情况下会导致esc先关闭第一层modal，且导致第二次modal的input无法获取光标
