### ISSUE TITLE
[Bug]: 报表过滤条件设置，不为空情况下查出的数据错误

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6819]
### Description

<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/6ac9a9e9-bcab-48fe-883c-ac5379ad2d7a">

### Steps To Reproduce 重现步骤

1、报表过滤条件设置选择框值不为空，发现查出来的数据不准备，过滤条件没有生效

### Version 版本

 2.7.1-beta.8

**Comment by sunhaolin** [comment]
2.7.1-beta.15
