### ISSUE TITLE
[Feature]: 权限集，除可以设置成员外，增加选择多个组织机构为用户范围

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#6827]
### Summary 摘要

创建新用户后，还需再加到权限集。

而且实例中，如果将某个权限集 设置2000+的成员后，列表显示 就有异常，每条记录的 人员均无法正常显示姓名 ：
![image](https://github.com/steedos/steedos-platform/assets/7553007/b2875abd-3694-4311-a520-b51fa10e4098)

### Why should this be worked on? 此需求的应用场景？

控制 应用可访问的 账户范围

**Comment by hotlong** [comment]
- salesforce 的权限集也必须指定用户。
- 涉及性能问题。
- 如果确实有很多用户需要批量加入权限集，chatgpt给的建议是使用自动化脚本。最终还是把对应的用户一个一个加入权限集
