### ISSUE TITLE
[Bug]: 手机端，点击编辑或者新建按钮之后，原先弹出按钮菜单不会自动关闭

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6830]
### Description

编辑或者新建完成之后，点击确认，原先弹出按钮菜单不会自动关闭，需再次点击空白地方或者右上角的x才能关闭
![image](https://github.com/steedos/steedos-platform/assets/129827462/5005dd5e-b0ac-4077-a185-f7238757e569)

### Steps To Reproduce 重现步骤

手机端对象新建或者编辑记录

### Version 版本

 2.7.1-beta.8

**Comment by tujiajun** [comment]
https://github.com/steedos/steedos-widgets/blob/master/packages/%40steedos-widgets/amis-lib/src/schema/standard_new.amis.js
