### ISSUE TITLE
[Feature]: 系统设置中的内核对象，没有名称对象时，点击第一个字段进入详情页

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6832]
### Summary 摘要

相关 https://github.com/steedos/steedos-platform/issues/6715

### Why should this be worked on? 此需求的应用场景？

业务

**Comment by lizheng-steedos** [comment]
- [ ] 流程委托
<img width="1254" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a0b84b28-f3f4-4a6a-a4d6-8dc964643026">

**Comment by ysc1234** [comment]
审批岗位成员,效率统计对象视图第一个字段为master_detail类型，存在bug，待任务修复后再改
-相关任务: 
 #6876
