### ISSUE TITLE
[Bug]: 设计字段布局保存报错

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6835]
### Description

设计字段布局不能保存

### Steps To Reproduce 重现步骤

点击保存按钮
![image](https://github.com/steedos/steedos-platform/assets/7665279/c827b52d-744d-4943-a798-3a6f439563ac)

### Version 版本

2.7.1-beta.4

**Comment by baozhoutao** [comment]
未能重现
