### ISSUE TITLE
[Bug]: 字段未配置inlineHelpText属性，只在国际化翻译中配置help属性时未能显示字段帮助提示

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6837]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/3d0afe58-d804-4a98-a280-f51fea82795f)
<img width="358" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/c4dfd640-089f-4748-8562-5247e60c83ee">

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by baozhoutao** [comment]
![image](https://github.com/steedos/steedos-platform/assets/6194462/e782002d-f75b-4e9e-87b0-d522b5b7a62d)
未能重现

**Comment by hotlong** [comment]
他说的是yml 中定义的对象，如果没有定义 help 属性，直接修改翻译文件中的help属性

**Comment by yinlianghui** [comment]
我试过了，确实又无法重现了，可能最新版本好了吧，之前是给应用增加新字段visible_on，没给它配置inlineHelpText，但是翻译文件配置了help属性时，没显示帮助提示，刚我特意又加一个新字段测试了下，没有问题了。

**Comment by baozhoutao** [comment]
> 他说的是yml 中定义的对象，如果没有定义 help 属性，直接修改翻译文件中的help属性

上图中的示例就是字段未定义`inlineHelpText`, 通过修改翻译文件中的help属性, 实际效果是生效的
