### ISSUE TITLE
[Bug]: android10低版本的手机小铃铛里面的消息通知内容自动移动

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6839]
### Description

屏幕大小：720*1440
安卓手机客户端
- 视频展示：
https://gitlab.steedos.cn/steedos/steedos-project-dfdt/uploads/eb49a85b06ad5c9cb8388198b458b3c0/46bb9f3cc38a7d281f805d24b62c1209.mp4

### Steps To Reproduce 重现步骤

关联任务：
-https://gitlab.steedos.cn/steedos/steedos-project-dfdt/-/issues/116

### Version 版本

2.7.1-beta.10

**Comment by baozhoutao** [comment]
在项目下按需处理:
添加样式
```
/* 安卓10浏览器不支持 flex 下的 column-gap 属性 */
.steedos-global-header-toolbar {
    column-gap: 0rem !important;
}

.steedos-global-header-toolbar .slds-icon-waffle{
    background: #ffffff !important;
}

.steedos-global-header-toolbar > div{
    margin-left: 0.75rem !important;
}
```
