### ISSUE TITLE
[Bug]: 点击相关表记录名称，右侧弹出的页面没有识别为该对象配置的记录类型微页面

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6840]
### Description

自定义了微页面记录页，发布后，点击相关表记录名称，右侧弹出的页面没有生效

### Steps To Reproduce 重现步骤

1、自定义记录微页面并发布
2、浏览器重新载入后点击公告中的附件名称，右侧弹出页未生效

### Version 版本

2.7

**Comment by chenzhipei** [comment]
关联目标issue: https://github.com/steedos/steedos-platform/issues/6770

**Comment by yinlianghui** [comment]
**测试要点：**

- [ ] 台账对象，非分栏模式下记录详细页面相关子表名称字段点击后弹出的drawer窗口要识别对象上配置的记录类型微页面
- [ ] 台账对象，分栏模式下记录详细页面相关子表名称字段点击后弹出的drawer窗口要识别对象上配置的记录类型微页面
- [ ] 台账对象，非分栏模式下记录详细页面只读表单中的Lookup（包括单选和多选）字段点击后弹出的drawer窗口要识别对象上配置的记录类型微页面
- [ ] 台账对象，分栏模式下记录详细页面只读表单中的Lookup（包括单选和多选）字段点击后弹出的drawer窗口要识别对象上配置的记录类型微页面
- [ ] 审批王审批单，审批详细页面只读表单中的Lookup（包括单选和多选）字段点击后弹出的drawer窗口要识别对象上配置的记录类型微页面
