### ISSUE TITLE
[Bug]: 对象运行树状结构显示，打开列表视图就报错

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6844]
### Description

![image](https://github.com/steedos/steedos-platform/assets/25192306/e038e800-e60a-4565-a3a6-6b61e214d5b1)

### Steps To Reproduce 重现步骤

1、新建对象
2、功能开关tab页勾选 “启用树状结构显示记录”
![image](https://github.com/steedos/steedos-platform/assets/25192306/fd2346e1-286d-4cb4-ae2b-d869d8808209)
3、保存
4、预览，报错

### Version 版本

2.6.6

**Comment by yinlianghui** [comment]
实测最新版本2.6无此问题。
![image](https://github.com/steedos/steedos-platform/assets/6219465/cde1084e-c383-423d-9fb3-d758d9f907e4)
