### ISSUE TITLE
[Bug]: 流程绑定到的台账对象中有的master_detail字段时，审批单会报错，不能正常显示该类型字段

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6851]
### Description
如果审批中不需要支持master_detail字段，在流程设置中就应该过滤掉这种字段类型，见下面图2：
![image](https://github.com/steedos/steedos-platform/assets/6219465/23d261bf-ef12-440b-8890-b64347a80ac1)

<img width="1049" alt="image" src="https://github.com/steedos/steedos-platform/assets/6219465/d12bc5b6-b69d-4fe3-8e56-980b10459dbf">

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by baozhoutao** [comment]
修正bug, 支持master_detail类型字段
