### ISSUE TITLE
[Bug]: 当公式字段中引用的字段值在before触发器中赋值时会导致公式计算不准

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#6860]
### Description

如题

关联：https://github.com/steedos/steedos-platform/issues/6611

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7.1-beta.7

**Comment by yinlianghui** [comment]
修改后，在新增和修改触发器中把字段值修改后，实测公式字段中引用触发器中修改过的字段值能正常运算公式值了。
![image](https://github.com/steedos/steedos-platform/assets/6219465/334e2a8f-f9bd-45bf-8ca7-a631712757f8)

![image](https://github.com/steedos/steedos-platform/assets/6219465/fa3f5488-4854-43a7-a70e-52a291a98c83)
