### ISSUE TITLE
[Task]: 平台内核对象，增加必要的的搜索项和快速搜索字段

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6863]
### SubTasks 子任务

- 调整对象的搜索字段，字段顺序按照截图顺序即可
- 有些对象需要同步调整一下列表视图字段

- [x] 流程委托
<img width="1701" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/6bd7ad27-4191-4c7e-bf46-a53f90f9493e">

- [x] 分部
<img width="1708" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/9bdb9f13-6888-4e67-ac40-0f21954a83fe">

- [x] 组织机构
<img width="1703" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/31188ae2-a518-4946-9317-96bcaaa32585">

- [x] 人员
<img width="1498" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4de77b83-7c0c-4114-a772-6bae37fdee69">

- [x] 简档
<img width="1695" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/2fb6f527-64b2-466e-90e7-102271052138">

- [x] 许可证
<img width="1704" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4dd8f063-65f3-4849-a6ac-314067275fd2">

- [x] 应用程序
<img width="1695" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/0c1624ba-fa2f-4410-9f56-56e53bf64e64">

- [x] 对象
<img width="1692" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/0ba4e196-74c6-4edd-be03-90d200db78e8">

- [x] 微页面
<img width="1920" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/d63b71f8-f4ae-4384-888f-d927a5508a73">

- [x] 选项卡
<img width="1690" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/eeed95f8-e265-4fa4-8a6c-505abdd6ee80">

- [x] 数据导入
<img width="1699" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e3761aa0-bf35-4dea-a2f9-7334308ba60a">

- [ ] 打印模板
<img width="1714" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/037d0d39-235d-4beb-95ac-2c04ff21d387">

- [x] 外部数据源
<img width="1707" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/c91ce1c5-3426-4f63-8329-3b88a4f5a194">

- [x] 报表
<img width="1704" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/c5eb1ced-5fa2-4714-b4b9-bceab9d79f83">

- [x] 仪表盘
<img width="1654" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a5b4e14a-9070-4889-8e1e-16f871ee07a4">

- [x] 软件包
<img width="1698" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/882e8d1f-07c6-4bf9-a3e0-f11b6c734716">

- [x] 对象触发器
<img width="1694" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/eaf2a2d3-25df-4725-b4e6-2577bd9ed72f">

- [x] webhooks
<img width="1709" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/3ec8e55e-0674-4be2-adc8-820da56fe5dd">

- [x] API Key
<img width="1706" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/fc25aefa-7e8f-4bf0-8ca3-c049439fa8ad">

- [x] 批准过程
<img width="1696" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/a6ca6648-c178-4425-a3f7-4da0acdf0d3d">

- [x] 工作流规则
<img width="1690" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/1164aaef-9500-4630-8951-8a7b30cb2270">

- [x] 对象验证规则
<img width="1703" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/c62681f6-298e-4105-b515-2c99ef6c05e7">

- [x] 字段更新
<img width="1700" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/b646314e-b0ea-457a-9055-da01aeb867f0">

- [x] 消息提醒
<img width="1686" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/f0d7c16c-f655-417f-93c3-cb5abf31ba4c">

- [x] 出站消息
<img width="1707" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/47f11cae-53e9-4e1f-b2bf-acd762c9fdbb">

- [x] 流程
<img width="1706" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/61bd9311-d5d9-4059-b0ee-7cb67f8b4cfc">

- [x] 角色
<img width="1699" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/8c1dc840-17a4-48af-a541-63c96febe452">

- [x] 审批岗位
<img width="1066" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/ac62befd-b087-455c-9af4-689473683abc">

- [x] 流程分类
<img width="1299" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/bc56b8d4-6de8-4552-b6c1-b9ef7e0510e2">

- [x] 流程编号
<img width="1664" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4c04249d-ddc1-498d-8c00-4130e620c3d2">

- [x] 效率统计
<img width="1694" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/cf1ef8d4-67a0-4723-88c7-026deacf4220">

- [x] 流程触发器
<img width="1715" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/26eeaa08-b555-47be-81ec-e8acac967573">

- [x] 流程对象映射
<img width="1699" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/791a9c1f-6ce9-40e3-a1c2-659c33bf2d5f">

- [x] 登陆会话
<img width="1686" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/de88c06e-234b-475a-a0fa-41021681d55b">

- [x] 自动编号
<img width="1332" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/c6c5275a-917c-4ff5-9bb0-773d8d0f7077">

- [x] 节假日
<img width="1650" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e58826ca-4094-4a9a-8f3a-9399bde54364">

- [x] 工作时间
<img width="1436" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/0d0788b6-765f-483d-bd21-4c609db07103">

- [x] 系统日志
<img width="1429" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/e040baf8-0a51-4a5b-9652-5be6adecba58">

- [x] 安全日志
<img width="1695" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/04619137-e2a4-4a48-ac89-92e24d83969a">

**Comment by lizheng-steedos** [comment]
- [ ] 流程委托
<img width="1701" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/6bd7ad27-4191-4c7e-bf46-a53f90f9493e">

- [ ] 分部
<img width="1708" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/9bdb9f13-6888-4e67-ac40-0f21954a83fe">

- [ ] 组织机构
<img width="1703" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/31188ae2-a518-4946-9317-96bcaaa32585">

- [ ] 人员
<img width="1498" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4de77b83-7c0c-4114-a772-6bae37fdee69">

- [ ] 简档
<img width="1695" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/2fb6f527-64b2-466e-90e7-102271052138">

- [ ] 许可证
<img width="1704" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/4dd8f063-65f3-4849-a6ac-314067275fd2">
