### ISSUE TITLE
[Bug]: 列表视图上有图片类型字段时，行高计算出错

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6869]
### Description

<img width="1709" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/510abf1f-bd4c-4874-b09d-243dfae87619">

### Steps To Reproduce 重现步骤

管理员进入后台设置中的图片签名对象

### Version 版本

2.7.1-beta.12

**Comment by tujiajun** [comment]
![image](https://github.com/user-attachments/assets/5c0ef961-a04d-4788-b1a1-a44d7c82fe59)
已修复
