### ISSUE TITLE
[Bug]: “数据导入历史”对象列表视图上“导入对象”字段是空的

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6872]
### Description

建议列表上直接去掉这一列
<img width="1674" alt="image" src="https://github.com/steedos/steedos-platform/assets/151509384/8bb7d1cf-5fa9-4e6d-867b-995744aa0795">

### Steps To Reproduce 重现步骤

管理员后台设置对象数据导入后，页面需要在相应对象导入数据后，可以看到对应导入历史对象记录

### Version 版本

2.7.1

**Comment by ysc1234** [comment]
在列表视图上去掉导入对象字段
