### ISSUE TITLE
[Bug]: 在右侧弹出框中修改子表信息，点击“编辑”后，弹出框自动回缩，无法编辑

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6875]
### Description

应弹出页面，并可编辑

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/7665279/33319224-7bfb-4e14-b6ae-39bcab54edfe)

### Version 版本

2.7.1-beta.14

**Comment by yinlianghui** [comment]
解决方案：dropdown button如果是在弹出drawer中，统一配置其container为drawer本身而不是默认放body内
![image](https://github.com/steedos/steedos-platform/assets/6219465/564d90ee-2f99-45a8-b458-32febf9042dd)
