### ISSUE TITLE
[Bug]: 小铃铛通知中标记全部已读后，数字不会变

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6888]
### Description

PC、手机端都有这个问题，只是PC上可刷新，刷新后数字会更新，手机上没办法刷新，所以数字一直不会更新

https://github.com/steedos/steedos-platform/assets/151509384/fe9baa1a-758f-485d-bbf8-f51bc4ad466e

### Steps To Reproduce 重现步骤

小铃铛通知，标记全部已读功能，见视频

### Version 版本

v2.7.1-beta.21

**Comment by yinlianghui** [comment]
PC和手机都有问题，而且有时有问题有时没问题，看起来是有明确的重现规则：
1.让右上角显示苦于未读通知数值。
2.刷新浏览器，或退出手机app重新进app（这步不可以少，除非未读通知在第一次进入页面时就已经存在，而不是新加的通知）
3.点开右上角通知清单
4.点选未读通知或者点击底部“全部标记为已读”
5.此时可以看到右上角通知数量未更新
