### ISSUE TITLE
[Bug]: 手机上先点过右上角小铃铛通知按钮再点九宫格应用程序启动器按钮弹出的应用列表界面没背景色了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6893]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/71c32364-963e-4310-a56a-32ab6459d8ed)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by tujiajun** [comment]
https://github.com/baidu/amis/issues/10338

**Comment by tujiajun** [comment]
该问题是由于amisbug造成的，暂时通过初始化事件添加classname的方式绕过该bug
