### ISSUE TITLE
[Bug]: 为代码级别的对象lookup字段，配置自动填充规则并同步为代码后，代码中的sort_no属性被自动删除掉了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6898]
### Description

代码中的sort_no本来就一直在，期间并没有操作过字段设计布局，也没做其它任何操作，就是简单的为字段配置了自动填充规则。

![image](https://github.com/steedos/steedos-platform/assets/6219465/2a12bd3a-35d3-488e-9643-29052a96d152)

![image](https://github.com/steedos/steedos-platform/assets/6219465/dd888fa6-f7b2-49a9-a8af-7f9fde26e13b)

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7

**Comment by baozhoutao** [comment]
此问题应该是操作不当导致,  丢失的sort_no是不是没有deploy到db.
