### ISSUE TITLE
[Bug]: space_users开启 name和 mobile加密后，保存的时候，@steedos/standard-space/main/default/triggers/space_users.trigger.js报错

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6901]
### Description

![image](https://github.com/steedos/steedos-platform/assets/25192306/64afbba0-a449-41ce-b737-36c693a811c1)

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/25192306/bb9c6dc5-b377-4a94-a033-dc7ba0bf0d34)

### Version 版本

2.6

**Comment by hotlong** [comment]
可以去掉 meteor 中 name 必须为 string 的限制

**Comment by hotlong** [comment]
当 space_user 变化时，企图更新其他工作区的 space_user 记录，导致报错
