### ISSUE TITLE
[Bug]: lookup字段配置了 相关表过滤条件 后, 在详细、列表页显示的值是 id

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6904]
### Description

-

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/6194462/9d5fea86-ef85-40a5-be15-3bd65fe5e966)
![image](https://github.com/steedos/steedos-platform/assets/6194462/842e7a3f-f0f9-4ffc-b4cd-3bfd48fd6191)
![image](https://github.com/steedos/steedos-platform/assets/6194462/06db4ea1-b56d-4a1b-b11e-edeef9c3ae8d)
![image](https://github.com/steedos/steedos-platform/assets/6194462/80d648ad-1d15-4ef0-b21e-242059685ca8)

### Version 版本

2.7

**Comment by tujiajun** [comment]
未重现
![image](https://github.com/steedos/steedos-platform/assets/127007861/ada4f0bd-448a-473b-9d72-304e684e6bd6)
![image](https://github.com/steedos/steedos-platform/assets/127007861/262a69d0-6fbb-46c2-be10-1c8d6d2be0ba)
