### ISSUE TITLE
[Bug]: 对象 deploy , retrieve 之后，再次 deploy报错： Field[ instance_state ](b6_projects)中，下列字段未填写:options

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6916]
### Description

如题

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.7.1

**Comment by hotlong** [comment]
删除此字段可以解决

**Comment by sunhaolin** [comment]
instance_state字段是select类型，options是必填属性，属于正常报错，原因是没有options属性导致。
删除掉instance_state的options属性后执行deploy可还原此提示。
