### ISSUE TITLE
[Bug]: 微页面对象记录详细页面,点击“相关”后报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6920]
### Description

-

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/6194462/f4853a47-ac19-4984-8f75-bef7c061ad59)

### Version 版本

2.7.1-beta.26

**Comment by tujiajun** [comment]
- 按操作步骤未重现该问题，为避免该问题发生，在生成schema的地方执行
```
body.columns = _.compact(body.columns);
```

- 经过调试发现，widgets内部代码只会实行一次，并且在进入amis官网查看代码后发现，执行多次sdk代码是amis内部实行的，因此并无性能问题
