### ISSUE TITLE
[Bug]: 管理员修改其他人员信息时，会报 “禁止修改用户邀请状态” 错误

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6921]
### Description

![1717726436614](https://github.com/steedos/steedos-platform/assets/25192306/87f3dfb6-52fb-4651-a2c8-a9a0c164d553)
管理员修改其他人员信息时，会报 “禁止修改用户邀请状态” 错误，如图

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/25192306/08f0032e-35c7-4e6d-adca-e5279e879b93)
这个地方的判断有问题，如图，修改人员信息时， “邀请状态” 字段都没显示，压根前端就不存在改动，但是保存时，还是会触发这里的校验。 
问题原因： 用户已经是  通过邀请 的状态， 需要改动一下其他字段信息，这里触发器判断逻辑不正确，导致无法进行后续修改

### Version 版本

2.6.16

**Comment by sunhaolin** [comment]
请升级至2.6.18
