### ISSUE TITLE
[Bug]: table 下的 file 类型字段上传文件报错

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#6926]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194462/4b62c334-9d9b-4612-ad99-105cd2e780a2)

### Steps To Reproduce 重现步骤

-

### Version 版本

2.7

**Comment by yinlianghui** [comment]
- steedos field组件附件字段上传报错问题已处理
- steedos field组件附件字段只读功能就没处理过，只处理过图片字段，附件字段需要单独处理下，关键代码如图

![image](https://github.com/steedos/steedos-platform/assets/6219465/89620f9b-6242-4894-8bdd-f72805bd6a6d)
