### ISSUE TITLE
[Bug]: table字段附件字段只读时显示为空白了，应该显示为附件链接

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6928]
### Description

- 包括单选和多选都要处理
- 这是因为steedos field组件附件字段只读功能就没处理过，只处理过图片字段，附件字段需要单独处理下，关键代码如图

![image](https://github.com/steedos/steedos-platform/assets/6219465/89620f9b-6242-4894-8bdd-f72805bd6a6d)

### Steps To Reproduce 重现步骤

- 对象字段yml文件中给某个子表(table)类型字段中添加附件字段
- 在记录详细页面为table字段中新增或编辑行窗口中上传附件保存后看只读效果

目前只读效果是显示为空白了：
![企业微信截图_c300d10b-e6f4-46ba-90cc-35572580cfcd](https://github.com/steedos/steedos-platform/assets/6219465/f74531ba-4777-4508-a100-e5e76b17a77d)

### Version 版本

2.7

**Comment by tujiajun** [comment]
![image](https://github.com/user-attachments/assets/2adcb203-a281-4357-97bf-28079689eed0)
表单详细页样式异常，file字段显示不出
