### ISSUE TITLE
[Bug]: 在对象详情页创建微页面，不能选择对象名

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6931]
### Description

<img width="1355" alt="企业微信截图_96c4603d-12a2-4716-bf46-607b1f6d63b3" src="https://github.com/steedos/steedos-platform/assets/50353452/589a050e-0a4b-496f-aee5-8bd65bd07bd1">

### Steps To Reproduce 重现步骤

如图

### Version 版本

2.7.1

**Comment by tujiajun** [comment]
在对象详细页内创建微页面时，对象名默认为当前对象且不允许修改
https://github.com/steedos/steedos-platform/issues/6207
代码逻辑参考上述issue
