### ISSUE TITLE
[Bug]: 时间范围控件错乱

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6932]
### Description

![test](https://github.com/steedos/steedos-platform/assets/25192306/457d398b-2027-4e21-a041-5bfb39594b73)
如图，选择开始时间，点击日期后，自动失去焦点，然后造成选择时间跳到后面一个框里面去了，建议恢复成amis官方效果，只显示一个日历框， 分别选择 开始 和 结束 日期跳出来选择

### Steps To Reproduce 重现步骤

![test](https://github.com/steedos/steedos-platform/assets/25192306/457d398b-2027-4e21-a041-5bfb39594b73)
如图，选择开始时间，点击日期后，自动失去焦点，然后造成选择时间跳到后面一个框里面去了，建议恢复成amis官方效果，只显示一个日历框， 分别选择 开始 和 结束 日期跳出来选择

### Version 版本

2.6

**Comment by yinlianghui** [comment]
类似问题：https://github.com/steedos/steedos-platform/issues/6922

**Comment by hotlong** [comment]
升级 amis 可以解决
