### ISSUE TITLE
[Bug]: 选择框类型字段 数据类型是 布尔， 编辑时和搜索时显示不一致

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#6934]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194896/2601b32e-bb5f-47e3-9ffb-8e5ed307154c)

### Steps To Reproduce 重现步骤

如图

### Version 版本

2.7

**Comment by tujiajun** [comment]
修改编辑时字段，统一使用boolean字段组件
