### ISSUE TITLE
[Bug]:  objectql insert 后不返回 _id 对象， comany 触发器里面， afterInsert 自动创建 orgnazation部分，新增完了之后不返回orgId

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6935]
### Description

![image](https://github.com/steedos/steedos-platform/assets/25192306/8f19219a-b18d-4a8b-9b7f-6db644ba726c)

### Steps To Reproduce 重现步骤
1、中控台创建 “我的魔方”过程中出现，错误位置 saas_space__c的trigger中会自动创建company
2、可以手工模拟测试，objectql.getObject('company').insert({....}); 创建时orgnazation自动不提供任何值，会触发自动创建orgnazation
debug时报错截图：
![image](https://github.com/steedos/steedos-platform/assets/25192306/8f19219a-b18d-4a8b-9b7f-6db644ba726c)
3、问题很奇怪，断点设置在108行，在还没执行108 行函数的情况下，如图无论是debug获取orgId，还是109行执行后异常日志中显示，orgId值都是{}。 但只要修复109行 ognazation的赋值为 orgId._id ，上方108行orgId值为{}的问题会自己消失恢复。同样断点在108行未执行的情况下，debug获取orgId的值正常为 {_id: 'xxxx',name: 'xxxxxx', ....} 字段内容完整

### Version 版本

2.6

**Comment by hotlong** [comment]
orgId 改为 orgId._id

**Comment by baozhoutao** [comment]
objectql 的 object.insert 函数return的是 `Promise<Doc>` 并不是 Promise<DocId>
