### ISSUE TITLE
[Bug]: 安全问题X-Acess-Token为jwt格式，含用户信息，存在敏感信息泄露风险

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6946]
### Description

X-Acess-Token 作为用户登录的一个凭证，采用jwt格式没有问题，但是jwt的第二部分base64 解码后可以直接得到用户信息，即使此token已经过期失效，但是仍然可以直接通过通过对此token解码获取到用户的 手机号、邮箱 等完整信息

修复建议： 第二部分不要存放个人信息，只放一个唯一hash值就行了。 或者一定要放，建议加密后再进行jwt 签名打包
### Steps To Reproduce 重现步骤

1. 正常登录
2. 查看cookies中的X-Acess-Token信息
3. 使用base64对第二部分内容解码

### Version 版本

2.5~2.7

**Comment by hotlong** [comment]
可以通过函数定义 jwt 内容
