### ISSUE TITLE
[Bug]: 安全问题：graphql操作保存对象数据时，未校验数据信息，存在XSS漏洞

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6947]
### Description

安全问题：graphql操作保存对象数据时，未校验数据信息，存在XSS漏洞

修复建议：
1. ApiGateway统一对请求信息进行过滤，对容易引发XSS的内容的字符进行转义处理
2. 对于cookies这种重要内容，下发时设置secure 属性和 httpOnly属性，防止XSS代码直接访问其中的敏感信息

### Steps To Reproduce 重现步骤

举例：
1. 公告->编辑
4. 对标题进行修改，填写 <img src=q onerror=prompt(8)>
![image](https://github.com/steedos/steedos-platform/assets/25192306/c84f1746-d6fb-484b-931a-a880e5e46577)
5. 保存后查看
6. 图片标签加载失败触发 onerror部分的回调函数
![image](https://github.com/steedos/steedos-platform/assets/25192306/72050342-8b24-4782-b15b-20065a640313)

### Version 版本

2.5~2.7

**Comment by hwzero** [comment]
可以使用  sanitize-html  对输入数据库前 /或者  输出到网页渲染前 对内容进行过滤

**Comment by hotlong** [comment]
可能需要开通配置入口。 https://github.com/apostrophecms/sanitize-html

**Comment by baozhoutao** [comment]
方案是insert\update时,对数据进行清理.
- 通过环境变量`STEEDOS_ENABLE_SANITIZE_HTML=true`启用清理HTML
- 可以通过在`steedos.config.js`中重写`sanitizeHtml`函数. 例如
```
// steedos.config.js

module.exports = {
    settings: {
         sanitizeHtml: (doc)=>{
              // 自定义清理逻辑
             return 处理后的doc;
         }
    }
}
```

**Comment by baozhoutao** [comment]
cookies 已经是httpOnly的.
