### ISSUE TITLE
[Bug]: 安全问题： 平台没有对cors进行限制，易造成敏感信息泄露

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#6948]
### Description

平台没有对cors进行限制，攻击者修改请求报文的 Origin：值比如www.baidu.com后，平台响应Access-Control-Allow-Origin跟着变成www.baidu.com ，并且Access-Control-Allow-Credentials： 为true ，容易引起用户cookies内敏感信息泄露

修复建议： 
1. 增加平台可以cors访问的白名单配置项 
### Steps To Reproduce 重现步骤

1. 攻击者修改请求报文的 Origin：值比如www.baidu.com后，请求平台正常页面或接口
![image](https://github.com/steedos/steedos-platform/assets/25192306/8cf48cf8-42cc-403c-9d78-12331aa80aff)
3. 平台响应Access-Control-Allow-Origin跟着变成www.baidu.com ，并且Access-Control-Allow-Credentials： 为true ，
![image](https://github.com/steedos/steedos-platform/assets/25192306/613b95d2-71c9-463a-9170-a2f92ea350fe)
4. 攻击者可以在构造微页面，在微页面中访问baidu网站，由于cors头部已允许访问baidu.com 并且Access-Control-Allow-Credentials： 为true， 这个请求会把用户cookies信息一起带上发送给baidu.com ，造成用户敏感信息泄露
5. cookies中包含X-Access-Token ，攻击者还能通过此信息在其他地方直接登录系统，造成进一步的信息泄露

### Version 版本

2.5~2.7

**Comment by hotlong** [comment]
通过环境变量配置 origin 白名单

**Comment by baozhoutao** [comment]
环境变量名: `STEEDOS_CORS_ORIGIN`  默认值 `false`

# 1. 布尔值示例
# 允许反映请求的原始来源
`STEEDOS_CORS_ORIGIN=true`

# 2. 字符串示例
# 仅允许来自特定域的请求
`STEEDOS_CORS_ORIGIN="http://example.com"`

# 3. 正则表达式示例
# 允许所有以 .example.com 结尾的域
`STEEDOS_CORS_ORIGIN="/\.example\.com$/"`

# 4. 数组示例
# 允许来自多个特定域或子域的请求
`STEEDOS_CORS_ORIGIN='["http://example1.com", /\.example2\.com$/]'`
