### ISSUE TITLE
[Bug]: npm start failed【macpro 10.15 catalina】

### ISSUE THREAD

**Issue by robin-fei** [steedos/steedos-platform#6950]
### Description

after npm install dependency, i run npm start command, stdout error info is: 
➜  steedos-platform2 git:(master) ✗ npm start

> steedos-platform@ start /Users/xxx/code/steedos-platform2
> steedos start --config steedos.config.js

[Runner] Cannot find module 'dotenv-flow'
Require stack:
- /Users/xxx/code/steedos-platform2/steedos.config.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/commands/start.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/plugin.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/config.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/index.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/command.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/index.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/bin/run Error: Cannot find module 'dotenv-flow'
Require stack:
- /Users/xxx/code/steedos-platform2/steedos.config.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/commands/start.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/plugin.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/config.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/index.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/command.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/index.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/xxx/code/steedos-platform2/steedos.config.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xxx/code/steedos-platform2/steedos.config.js',
    '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/commands/start.js',
    '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/plugin.js',
    '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/config.js',
    '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/index.js',
    '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/command.js',
    '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/index.js',
    '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/bin/run'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steedos-platform@ start: `steedos start --config steedos.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steedos-platform@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2024-06-23T09_28_09_861Z-debug.log

after i run npm install dotenv-flow and npm start , then another error output:
➜  steedos-platform2 git:(master) ✗ npm start

> steedos-platform@ start /Users/xxx/code/steedos-platform2
> steedos start --config steedos.config.js

[2024-06-23T09:28:42.510Z] WARN  steedos-primary/BROKER: Clear all cache entries on startup.
[2024-06-23T09:28:42.512Z] FATAL steedos-primary/BROKER: Unable to create ServiceBroker. Error: Cannot find module '@steedos/objectql'
Require stack:
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/default.steedos.config.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/start/index.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/commands/start.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/plugin.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/config.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/index.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/command.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/index.js
- /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.resolve (internal/modules/cjs/helpers.js:113:19)
    at Object.created (/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/default.steedos.config.js:319:36)
    at new ServiceBroker (/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/moleculer/src/service-broker.js:322:61)
    at StartCommand.startBroker (/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/commands/start.js:322:23)
    at /Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/commands/start.js:339:30
    at async StartCommand._run (/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/main.js:28:9)
    at async Main._run (/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/command.js:43:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/default.steedos.config.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/start/index.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/dist/commands/start.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/plugin.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/config.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/config/lib/index.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/command.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/node_modules/@oclif/command/lib/index.js', '/Users/xxx/.nvm/versions/node/v14.21.3/lib/node_modules/steedos-cli/bin/run' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! steedos-platform@ start: `steedos start --config steedos.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steedos-platform@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2024-06-23T09_28_42_530Z-debug.log

how to resolve the problem?
i find steedos-platform’s develop docs is too simple，as developer cannot work it step by step!

### Steps To Reproduce 重现步骤

1.npm install --legacy-peer-deps
2. npm start
3. npm install dotenv-flow
4. npm start

### Version 版本

Self hosted -- 2.6 and 2.7.1

**Comment by sunhaolin** [comment]
请尝试按顺序执行：

1. yarn install
2. yarn build
3. yarn start
@robin-fei
