### ISSUE TITLE
[Bug]: 对象列表页面点击新建报401【macpro 10.15 catalina】

### ISSUE THREAD

**Issue by robin-fei** [steedos/steedos-platform#6951]
### Description

curl如下：
curl 'http://127.0.0.1:5000/graphql?reload=&objectName=objects' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6' \
  -H 'Authorization: Bearer ,' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: ivan=s%3ACvR7J5MjPL8nf-MDZpSUC8_M17uqkqga.f86Wsi4WI5b1twyvBFrmeUkRo5itinopcmSG2mQj8u0; X-User-Id=6677f1b746cacd673921db4d; X-Auth-Token=11e448ff03889f8e4e4aec9eac9e81424330e14bb7cca015515891bfa5f1e6f1c20ab82fe1986d0fbb7d15; X-Access-Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlzSW1wZXJzb25hdGVkIjpmYWxzZSwidXNlcklkIjoiNjY3N2YxYjc0NmNhY2Q2NzM5MjFkYjRkIiwibmFtZSI6ImZlaWhhaW1pbmciLCJlbWFpbCI6ImZobWRmc3cxMkAxMjYuY29tIn0sImlhdCI6MTcxOTE5NDIyNSwiZXhwIjoxNzI2OTcwMjI1fQ.tNMidbRExwLBcY-qPdOxCJCPyXXak-297guY21eOEFQ; X-Space-Id=6677f1bb46cacd673921db4f' \
  -H 'Origin: http://127.0.0.1:5000' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://127.0.0.1:5000/app/admin/objects/grid/all' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0' \
  -H 'sec-ch-ua: "Not/A)Brand";v="8", "Chromium";v="126", "Microsoft Edge";v="126"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"query":"{data:objects(filters: [\"_id\",\"=\",null], top: 1){_id}}"}'

截图如附件
![1](https://github.com/steedos/steedos-platform/assets/7486514/47a59bc7-e321-4f54-b919-8ea45273149e)

npm start 运行起来了后，点击的新建，请问这个原因是什么？

### Steps To Reproduce 重现步骤

1. npm start
2. 访问http://127.0.0.1:5000/app/admin/objects/grid/all，点击新建

### Version 版本

Self hosted -- 2.6

**Comment by smachs** [comment]
Same issue

**Comment by sunhaolin** [comment]
已在2.7.2-beta.2解决
