### ISSUE TITLE
[Bug]: 对象打印按钮报错+关闭按钮重新开启后崩溃

### ISSUE THREAD

**Issue by zhaitongkun** [steedos/steedos-platform#6953]
### Description

遇到的问题：
1. 对象打印按钮使用报错
2. 关闭按钮重新开启后选项卡崩溃

期望的效果：
可以将某条数据的详情打印或者将导出成某种格式（excel or pdf）
有没有可能批量选择并打印？

### Steps To Reproduce 重现步骤

1. 创建对象后，打印按钮默认打开，点击自定义
![1](https://github.com/steedos/steedos-platform/assets/66982855/8b0b7684-b2c2-49f7-a112-cc1880f82329)
2. 到选项卡页面进入详情，打印按钮显示出来但是报错
![image](https://github.com/steedos/steedos-platform/assets/66982855/40aff1a0-078f-4a79-a47f-2ac1ffc52783)
3. 编辑打印按钮关闭启动，选项卡恢复，重新打开启动后，选项卡崩溃
![image](https://github.com/steedos/steedos-platform/assets/66982855/76218d1a-2a43-49ac-bf66-d4bb1b3314c2)
4. 整个过程中后台看不到日志

### Version 版本

2.6.10

**Comment by zhaitongkun** [comment]
2.6.10

**Comment by baozhoutao** [comment]
此功能需要使用企业版许可证
