### ISSUE TITLE
[Bug]: 累计汇总金额有误

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6955]
### Description

汇总数据有误

### Steps To Reproduce 重现步骤

![image](https://github.com/steedos/steedos-platform/assets/7665279/0e1aa93c-ac22-49f9-b2cb-01fb7d2129ea)
![image](https://github.com/steedos/steedos-platform/assets/7665279/0aba6b7a-5b5d-439f-920c-fe02b1aa9b09)
发票总金额为累计汇总发票金额

### Version 版本

2.7.、

**Comment by sunhaolin** [comment]
1883.81 + 2015.34
