### ISSUE TITLE
[Bug]: 新建权限集配置人员的修改权限未生效

### ISSUE THREAD

**Issue by RussellMao** [steedos/steedos-platform#6959]
### Description

除管理员admin外，无论怎么设置权限集或监督。均其他用户没有人员的修改权限

### Steps To Reproduce 重现步骤

1.配置自定义权限集，赋予人员和用户所有的编辑权限
<img width="1139" alt="image" src="https://github.com/steedos/steedos-platform/assets/34770813/8fe0131a-c7a5-4647-9b8d-873e93eb7d50">

2.配置分部管理员权限集，给对应的人。

3.无论以上步骤1，2.均无法修改其他人员的基础信息

### Version 版本

2.6.16

**Comment by baozhoutao** [comment]
只有`工作区管理员`或者`组织管理员`才有人员对象的管理权限.
