### ISSUE TITLE
[Bug]: 审批单上的“相关台账信息“链接，不应取rootURL（内网访问时会跳转到外网网址、要求登录）

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#6960]
### Description

不应取rootURL，而应取 当前路径

https://github.com/steedos/steedos-project-hbport/issues/757

### Steps To Reproduce 重现步骤

同时可用 内网和外网访问系统，rootURL配置为外网
用内网访问系统，点“相关台账信息”，会出登录页面，得输用户名密码才能进到相应的页面

### Version 版本

2.5.0-beta.39

**Comment by hotlong** [comment]
需要考虑手机app

**Comment by sunhaolin** [comment]
可通过在service.config.js中配置实现：
```js
    settings: {
        public: {
            webservices: {
                creator: {
                    url: "/"
                }
            }
        }
    }
 ```
