### ISSUE TITLE
[Bug]: image类型的字段在手机端多选状态下无法上传图片

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6961]
### Description

东方低碳项目
https://github.com/user-attachments/assets/bfea42a7-468b-4534-8f67-c7c8ca0b0dbe
关联任务：
 https://github.com/steedos/steedos-project-dfdt/issues/36

### Steps To Reproduce 重现步骤

1、image类型字段，设置多选
2、点击多选状态下上传图片（像微信朋友圈一样，可上传多张图片或一张图片）

### Version 版本

2.7.1-beta.27

**Comment by tujiajun** [comment]
该问题仅在手机端app上可重现，浏览器正常，考虑可能为app导致
