### ISSUE TITLE
[Bug]: sockjs/info 请求中Access-Control-Allow-Origin为*，存在安全隐患

### ISSUE THREAD

**Issue by chenzhipei** [steedos/steedos-platform#6964]
### Description

客户漏扫报告反馈：CORS(跨站资源共享)原始验证失败
经检查，发现sockjs/info请求存在此问题
版本：2.6

### Steps To Reproduce 重现步骤

访问2.6服务，查看请求sockjs/info，response_headers中 Access-Control-Allow-Origin为*

### Version 版本

2.6

**Comment by sunhaolin** [comment]
ff3716b5435f36644aa77f696f878d48faf1f906

**Comment by sunhaolin** [comment]
meteor依赖的npm包sockjs始终返回Access-Control-Allow-Origin为*，故通过nginx配置解决
