### ISSUE TITLE
[Bug]: 文件拟写，标题等字段的值有时会丢失

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#6965]
### Description

https://github.com/steedos/steedos-project-hbport/issues/761
新建，有时自动保存机制会失灵
新建后编辑，基本都OK

### Steps To Reproduce 重现步骤

审批，左侧新建审批，选择流程后、输入内容不保存、点击到其他链接后，返回看草稿箱记录，有时字段值会丢

### Version 版本

 2.6.8-beta.11

**Comment by sunhaolin** [comment]
需要测试编辑表单后离开页面是否暂存，包括 草稿箱和待审核箱
