### ISSUE TITLE
[Bug]: 编辑用户后部门（含上级）计算不准确

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6968]
### Description

父部门没有计算出来，不是每个用户都如此

### Steps To Reproduce 重现步骤

<img width="992" alt="1721889502407" src="https://github.com/user-attachments/assets/d4de798d-1dd7-43aa-87d7-df293dca9d48">

### Version 版本

 2.6.10-beta.5

**Comment by sunhaolin** [comment]
https://github.com/steedos/steedos-platform/issues/6646
