### ISSUE TITLE
[Bug]: 仪表板变为元数据后显示报错“发生了一个错误”

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#6970]
### Description

仪表板变为元数据后显示报错“发生了一个错误”

### Steps To Reproduce 重现步骤

”“发生了一个错误

### Version 版本

2.6.22

**Comment by sunhaolin** [comment]
![image](https://github.com/user-attachments/assets/c23195c4-5feb-44cf-97b0-f17d76b019d4)
报表同步为元数据文件也报错
