### ISSUE TITLE
[Feature] 新增非受管软件包，安装时自动deploy元数据

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#6986]
### Summary 摘要

- 定义软件包时，标记为非受管。
- 软件包启动时，调用现有元数据deploy的接口？

### Why should this be worked on? 此需求的应用场景？

demo 应用

**Comment by sunhaolin** [comment]
- 支持环境变量初始化工作区 https://github.com/steedos/steedos-platform/issues/3606
- 在服务启动完成（steedos-server.started）后执行initSpace。 文档提示用户初始用户名密码
- 当前软件包启动后执行deploy，使用loadFileToJson和jsonToDb

**Comment by baozhoutao** [comment]
软件包package.service.js中添加`settings.packageInfo.isUnmanaged` 为true

**Comment by lizheng-steedos** [comment]
template项目，contract-demo分支，已升级到最新的2.7.10-beta.10版本，并且已经添加对应配置参数
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/7aad134b-3442-46ae-abbc-516893a26ddb">
新开的环境数据还是没有到数据库里，还需要自己手动自定义
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/fa1bfd65-d1cf-4beb-995c-3c4f464f6773">

**Comment by baozhoutao** [comment]
![image](https://github.com/user-attachments/assets/1aab9b3d-9933-4380-8d27-feee877d7ea8)
空库注册企业后, 控制台报错. 页面空白.
