### ISSUE TITLE
[Bug]: lookup类型字段描述文字/提示文本，前台记录页面未显示

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#6993]
### Description

<img width="1663" alt="image" src="https://github.com/user-attachments/assets/5f77bcbd-7fba-4c92-a611-ed3c059a6adc">
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/0306fc20-07e3-496b-8e9e-090e9e98ea1e">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

2.7.7

**Comment by baozhoutao** [comment]
重复: https://github.com/steedos/steedos-platform/issues/7005
