### ISSUE TITLE
[Bug]: 对象后台自定义按钮后，前台显示不出来

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#7008]
### Description

- 后台配置详情页更多下拉菜单时显示不出；
<img width="1513" alt="image" src="https://github.com/user-attachments/assets/291066be-217a-4b63-951a-85c6b1baf5ad">
<img width="1917" alt="image" src="https://github.com/user-attachments/assets/90ff0d53-a9ec-45ef-9b50-e74aca5234e7">

- 后台配置详情页右上角显示，前台就可以正常显示；
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/36f62034-c04f-467e-b26a-a253eddd79c9">
<img width="1685" alt="image" src="https://github.com/user-attachments/assets/6df3c0f1-2978-41aa-9e1e-0f90ff872f5a">

### Steps To Reproduce 重现步骤

见描述

### Version 版本

 2.7.9-beta.1

**Comment by baozhoutao** [comment]
如果按钮是在more中显示,则只能使用js表达式.
https://github.com/steedos/steedos-platform/issues/5541

**Comment by baozhoutao** [comment]
将```
"visibleOn": "${record.status== 'prograss' && record.instance_state== 'approved'}"
```
修改为
```
 "visibleOn": "data.record.status== 'prograss' && data.record.instance_state== 'approved'"
```
