### ISSUE TITLE
[Bug]: 公式字段计算不准确

### ISSUE THREAD

**Issue by huangyiirene** [steedos/steedos-platform#7026]
### Description

计算准备

### Steps To Reproduce 重现步骤

<img width="688" alt="1728523569008" src="https://github.com/user-attachments/assets/627c000d-84fa-494f-91f4-6cbf2595c5e0">
 
数据库显示金额正确，但实际有误，需使用数据库编辑工具再次保存后才起效

### Version 版本

2.7

**Comment by hotlong** [comment]
服务端触发器在判断这个字段的值时错了

**Comment by baozhoutao** [comment]
字段公式需要设置精度
`ROUND(amount - paid_actual_amount - approving_paid_amount, 3)`
