### ISSUE TITLE
[Bug]:报表设置行数限制属性后，实际统计数据少一条

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#7038]
### Description

<img width="910" alt="image" src="https://github.com/user-attachments/assets/3bdb88f5-7f9a-498d-b7c8-95c484d54216">

### Steps To Reproduce 重现步骤

见截图

### Version 版本

 2.7.10-beta.10

**Comment by baozhoutao** [comment]
重复 https://github.com/steedos/steedos-platform/issues/7039
