### ISSUE TITLE
[Bug]: 审批单向对象表单同步，子表数据不同步丢失

### ISSUE THREAD

**Issue by hwzero** [steedos/steedos-platform#7040]
### Description

审批王审批结束后，子表数据没有同步到对象表单， 只同步了主表的数据

### Steps To Reproduce 重现步骤

1. 配置带有子表结构的对象 和 对应的审批王审批流程
2. 配置流程对象映射
2.1.  同步方向： 审批单至对象
2.2.   表单至对象同步模式：结束节点同步
3.  发起流程审批并走完
4.  清空对象侧所有数据
5.  修改instances对象数据的 “record_ids”字段
6.  手工点击 “同步历史申请单”

==============================================
debugger分析原因：
当同步子表逻辑走到  bjectInsert 处，由于数据data 部分，多出了 _table 结构, 造成插入失败
![90aa8a7d83a57c5b15732f031efcfc0](https://github.com/user-attachments/assets/1e05277d-306e-45fa-9f89-6a97aba7eae4)

### Version 版本

2.6.27

**Comment by baozhoutao** [comment]
amis表单中, 子表需要添加事件自动处理input table的数据结构. 自动添加_id
```
"change": {
      "weight": 0,
      "actions": [
        {
          "ignoreError": false,
          "actionType": "custom",
          "script": "_.each(event.data.value, (item) => {\n  if (!item._id) {\n    item._id = Amis.uuidv4()\n  }\n})",
          "args": {}
        }
      ]
    }
```
