### ISSUE TITLE
[Feature]: 选择框类型字段增加属性，支持radio展示效果

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#7063]
### Summary 摘要

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/f34575cc-3211-48bd-b2ad-282bd322ba7e">

### Why should this be worked on? 此需求的应用场景？

业务搭建

**Comment by baozhoutao** [comment]
方案: 对象设计器字段属性的 表单下添加输入类型选项. 通过指定此类型实现需求.

**Comment by lizheng-steedos** [comment]
- [ ] 前台保存后，点选框现实的是选项值，而不是选项名称，并且选项背景颜色也没显示

<img width="1694" alt="image" src="https://github.com/user-attachments/assets/acc89e26-e4d8-4b0a-88ab-976774d7681d">
