### ISSUE TITLE
[Bug]: 公式计算出前台显示NAN

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#7069]
### Description

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/408e2367-06d2-4a3d-a99c-d5ddc32d03ba">

### Steps To Reproduce 重现步骤

公式写法如下：
<img width="1587" alt="image" src="https://github.com/user-attachments/assets/cd730055-e855-4f18-8a90-ece0ee16756f">

### Version 版本

2.4.13

**Comment by lizheng-steedos** [comment]
- [ ] 

<img width="1428" alt="image" src="https://github.com/user-attachments/assets/896661e7-8ad6-4dcf-809e-798e8dba9eca">

**Comment by baozhoutao** [comment]
公式应该为: ${合同金额 - 待付款金额}
