### ISSUE TITLE
[Bug]: 下载按钮不起作用

### ISSUE THREAD

**Issue by itants1978** [steedos/steedos-platform#7085]
### Description

升级到到2.7.10版本之后，在相关中的附件列表点下拉列表中点下拉键 选择下载，不能下载
点击附件文件，显示预览界面，在预览界面点击界面上面的下载不能下载，可以在相关中点击历史版本进行下载

### Steps To Reproduce 重现步骤

1、升级到到2.7.10版本之后
2、选择一个带有附件的合同信息列表，点击相关
3、选择要下载的附件，点击列表中的下拉箭头，点击下载，出现network error 
4、选择附件，打开预览界面，预览界面点击界面上面点击下载，出现netowrk error
![微信图片_20241113094929](https://github.com/user-attachments/assets/e6e60c21-1260-4212-9407-b86e7a165599)

### Version 版本

2.7.10

**Comment by lizheng-steedos** [comment]
已确认功能正常，请检查root_url等环境变量是否配置正确。
