### ISSUE TITLE
界面自定义

### ISSUE THREAD

**Issue by canyuegongzi** [steedos/steedos-platform#709]
这个能够高度自定义界面的样式吗

**Comment by hotlong** [comment]
可以在项目中引入css，适当改变现有界面的样式。

**Comment by hotlong** [comment]
项目模版中应该加入自定义css的入口。 @yinlianghui

**Comment by yinlianghui** [comment]
> 项目模版中应该加入自定义css的入口。 @yinlianghui

恩，现在只能写.client.js手动把css内容引用，有入口才好用。

**Comment by hotlong** [comment]
目前只能改动界面上现有控件的css样式，如果要高度调整排版和风格，目前还不支持。

**Comment by canyuegongzi** [comment]
> 目前只能改动界面上现有控件的css样式，如果要高度调整排版和风格，目前还不支持。

嗯嗯，有后续关于这个的迭代的计划吗?

**Comment by hotlong** [comment]
我们有计划提供react组件，比如记录创建、记录列表、记录查看等，帮助客户重写界面。目前还没有排上开发日程。
