### ISSUE TITLE
[Bug]: 选择框类型字段启用radio效果后，表单只读模式显示的是选项的value

### ISSUE THREAD

**Issue by lizheng-steedos** [steedos/steedos-platform#7097]
### Description

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/42b7a823-57ea-4a2c-a00d-0e3f4f88c5ed">

### Steps To Reproduce 重现步骤

编辑页面字段正常，显示页面数据显示的不对

### Version 版本

 2.7.11-beta.2

**Comment by baozhoutao** [comment]
https://github.com/steedos/steedos-widgets/commit/d2d624e23594708d18359bf5976b91302e54b1ec
