### ISSUE TITLE
当记录以tab的方式打开后，删除此记录，tab未自动关闭

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#725]

**Comment by yinlianghui** [comment]
测试要点：
1.以tab的方式打开记录后直接删除该记录时应该把tab也关掉。
2.在对象主列表删除某条记录时，如果该记录之前已经有tab了，应该把该tab也关掉。
3.在对象主列表删除某条记录时，如果该记录之前没有tab，功能应该正常，比如应该保持在当前列表界面不应该发生跳转。
4.在记录详细界面中删除某条记录时，按第2、3点再测试下。
5.其他删除的情况。
