### ISSUE TITLE
标准对象包中accounts对象的纳税人识别号为空时编辑会报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#729]
-是不是应该把纳税人识别号字段设置为必填！
-看报错信息是说字段值重复了
![image](https://user-images.githubusercontent.com/6219465/90709317-7d353200-e2ce-11ea-94f3-44f3c87efede.png)

**Comment by hotlong** [comment]
唯一校验去掉 @sunhaolin

**Comment by sunhaolin** [comment]
```js
db.accounts.dropIndex('c2_credit_code');
```

**Comment by yinlianghui** [comment]
我本地库的问题，执行脚本就好了
