### ISSUE TITLE
 .object.yml 中配置object layout

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#758]

**Comment by hotlong** [comment]
需要考虑，只有简档才能配置页面布局。需要的话可以用.profile.yml配置文件。

**Comment by hotlong** [comment]
具体可以参考一下salesforce

**Comment by hotlong** [comment]
考虑到下一步数据库和代码的双向同步。可能会慢慢朝着小的配置文件方向发展，就是每个配置文件只配置一个功能，甚至一个字段。
