### ISSUE TITLE
手机端签批历程中，用户链接弹出框中间出现错误提示

### ISSUE THREAD

**Issue by TroySu** [steedos/steedos-platform#761]

**Comment by hotlong** [comment]
https://messenger.steedos.cn/api/v4/files/exa3up5a8tg9p8cfug3uexqtjo?download=1

**Comment by hotlong** [comment]
这个问题我感觉跳转有问题，没有调用手机本地的服务，而是跳转到 ROOT_URL 了

**Comment by TroySu** [comment]
![Screenrecording_20200826_150742](https://user-images.githubusercontent.com/20942182/91276226-d3fda880-e7b3-11ea-88ba-4e259cd082a8.gif)

**Comment by yinlianghui** [comment]
已处理。该问题的规则是：
- 第一次点击某个用户链接时会有404提示界面一闪而过
- 跟手机端没关系，PC上也一样有问题
- 原因是订阅space_users数据还没下来就提示了404
