### ISSUE TITLE
会签节点规则变更为默认选中所有用户

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#803]

**Comment by yinlianghui** [comment]
已处理：
- 增加了开关量Meteor.settings.public?.workflow?.autoPickNextStepUsersAtCounterSignStep，默认值true，即除非设置为false，否则默认选中所有用户
- 流程设计器中随机设置了几种处理人类型测试下来功能正常
- 关联任务： [trqgw:步骤人员选择为指定部门和岗位时时（会签节点），默认将部门内所有人员或所有岗位成员都选中，希望改为不选人员，让用户自己选择](https://github.com/steedos/steedos-project-trqgw/issues/88)

> 请相关项目负责人对下是否需要配置autoPickNextStepUsersAtCounterSignStep变量，以避免升级后出问题。

**Comment by yinlianghui** [comment]
> 已处理：
> 
> * 增加了开关量Meteor.settings.public?.workflow?.autoPickNextStepUsersAtCounterSignStep，默认值true，即除非设置为false，否则默认选中所有用户
> * 流程设计�器中随机设置了几种处理人类型测试下来功能正常
> * 关联任务： [trqgw:步骤人员选择为指定部门和岗位时时（会签节点），默认将部门内所有人员或所有岗位成员都选中，希望改为不选人员，让用户自己选择](https://github.com/steedos/steedos-project-trqgw/issues/88)
> 
> > 请相关项目负责人对下是否需要配置autoPickNextStepUsersAtCounterSignStep变量，以避免升级后出问题。

已同步更新到1.22和1.23了
