### ISSUE TITLE
如果应用中没有定义 plugin.config.yml，把这个应用作为插件，会导致主项目启动失败。

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#811]
还需要 index.js，以及在package.json 中定义main

关键报错也不相关：
error: TypeError: Cannot read property '_ensureIndex' of undefined
W20200911-14:46:00.025(8)? (STDERR)     at Object.<anonymous> (/Users/steedos/Documents/GitHub/object-server/packages/standard-objects/steedos_keyvalue.object.js:36:26)

**Comment by baozhoutao** [comment]
此问题应该是由于 require plugin 导致

**Comment by baozhoutao** [comment]
未能重现

**Comment by baozhoutao** [comment]
如果没有配置index.js 或者package.json 中没有指定main 时， 错误信息为：`Plugin not found in project, please execute: yarn add @steedos/steedos-plugin-schema-builder`
