### ISSUE TITLE
新版 accounts 遗留问题

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#828]
- [ ] 客户端登录时，自动生成 localStorage meteor login token
- [x] 注销 session 时，服务端应该同时清理 meteor session token
- [x] 注销时，client端清理localStorage  meteor session token 目前此部分处理是在creator代码中实现
- [x] /steedos/logout 路由变更为 /accounts/a/#/logout
- [ ] 客户端注销时，清理 localStorage meteor login token 在accounts中实现
- [x] 验证码验证没有记录使用日期，使用过的验证码可能还能继续登录。
- [x] 验证码目前没有实现10分钟内不重新生成，而是每次都生成新的。
- [ ] 删除之前开发的作废接口
- [ ] @steedos/auth 中的接口迁移到 accounts
- [ ] 迁移接口 /api/v4/users/login 到 accounts
- [x] 邀请注册后自动加入工作区，需要给注册接口传新的函数并实现保存数据库的逻辑。
- [ ] 邀请注册的界面需要显示工作区的logo
- [x] 强制绑定手机号界面
- [x] 强制绑定邮箱界面
- [x] 密码过期强制修改界面
- [x] 账户已注册，且未加入任何工作区的情况下， 此账户不能再注册， 也不能登录
- [x] 未加入任何工作区时，登录后页面空白

**Comment by hotlong** [comment]
邀请注册后自动加入工作区，需要给注册接口传新的函数并实现保存数据库的逻辑。

**Comment by hotlong** [comment]
还缺三个界面，但是不急，不影响发版本。

-  强制绑定手机号界面
-  强制绑定邮箱界面
-  密码过期强制修改界面
-

**Comment by baozhoutao** [comment]
账户已注册，且为加入任何工作区的情况下， 此账户不能再注册， 也不能登录

**Comment by baozhoutao** [comment]
未加入任何工作区时，登录后页面空白

**Comment by hotlong** [comment]
未加入任何工作区时，开发环境应该是会自动跳转到选择工作区的界面
