### ISSUE TITLE
系统对象隐藏

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#886]
需要隐藏
- 新建应用程序选择对象的时候
- 业务对象列表
- 新建报表选择对象的时候
- 新建流程对象映射关系的时候
- 新建批准过程的时候
- 新建共享规则的时候
- 在线表单

需要放开
- 开始菜单显示的是所有非 hidden 的对象，目前只显示应用中配置了的对象。

其他
- base 对象也要隐藏
- 在线表单当时专门开了一个开关，可以把开关去掉，合并到统一的规则。

**Comment by baozhoutao** [comment]
去掉enable_web_forms 属性，非hidden 的对象都可以创建在线表单
