### ISSUE TITLE
老客户端打开最新版本creator登录界面没对齐，窗口放大到全屏也是坏的

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#895]
是在1.22分支上跑最新的源码发现的。
![image](https://user-images.githubusercontent.com/6219465/94218221-87be9900-ff16-11ea-8e20-a9f34c899b67.png)

**Comment by baozhoutao** [comment]
此问题是由于样式兼容问题， nwjs 升级到0.19 + 即可。 chromium内核为50+

**Comment by baozhoutao** [comment]
nwjs 0.19 不支持 xp系统
