### ISSUE TITLE
百分比 percent 类型字段

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#897]
sf规则是：允许用户输入百分比数字（例如，"10"），并自动向数字添加百分号。

**Comment by yinlianghui** [comment]
已处理：
- 输入时按小数来，比如输入0.2表示20%，数据库中最终存入的是0.2
- 配置字段小数位数时，表示的是最终加%符号显示时的小数位数，比如`scale: 1`表示显示时像`20.8%`这样按一位小数来显示，输入时可以输入像`0.208`这样的三位小数值。

**Comment by yinlianghui** [comment]
![image](https://user-images.githubusercontent.com/6219465/95805546-414fa380-0d38-11eb-8ff7-199db8d5d59a.png)
