### ISSUE TITLE
creator 报错

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#907]
W20200927-17:21:02.706(8)? (STDERR) TypeError: Cannot read property 'name' of undefined
W20200927-17:21:02.708(8)? (STDERR)     at packages/steedos_object-database/server/routes/api_creator_objects.coffee:110:92
W20200927-17:21:02.708(8)? (STDERR)     at packages/simple:json-routes/json-routes.js:88:9

**Comment by yinlianghui** [comment]
未重现
