### ISSUE TITLE
批准过程，已经禁用或者已提交审批完成的，考虑放开新增修改批准步骤

### ISSUE THREAD

**Issue by TroySu** [steedos/steedos-platform#913]
![image](https://user-images.githubusercontent.com/20942182/94395658-bcd71f80-0192-11eb-994c-e44bc563c20a.png)

**Comment by hotlong** [comment]
1、重点要考虑如果放开的话会有哪些问题。
2、如果不能放开，要解决复制批准过程的问题。

**Comment by baozhoutao** [comment]
批准过程添加复制功能：https://github.com/steedos/steedos-platform/issues/935
