### ISSUE TITLE
零代码定义业务对象的字段时，列表显示、显示、编辑几处的API名称不一致

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#919]
![image](https://user-images.githubusercontent.com/7553007/94421624-6aa8f500-01b8-11eb-9c93-81fcbe5684df.png)
![image](https://user-images.githubusercontent.com/7553007/94421673-7c8a9800-01b8-11eb-8697-023ffffc8821.png)
![image](https://user-images.githubusercontent.com/7553007/94421710-87ddc380-01b8-11eb-8540-81d87d643bad.png)

**Comment by hotlong** [comment]
![image](https://user-images.githubusercontent.com/50353452/94421956-e99e2d80-01b8-11eb-8289-d1668389ea96.png)

Salesforce 字段标签、字段名、字段API名称是分开的
