### ISSUE TITLE
lookup下拉框，图标背景色错误

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#945]
![image](https://user-images.githubusercontent.com/50353452/95548770-5bd40500-0a38-11eb-8666-33d4e0ab736d.png)

**Comment by hotlong** [comment]
以上截图，+ 位置有点偏，应该是引入 tailwind 导致的，也要调整一下。

**Comment by yinlianghui** [comment]
已处理，lookup控件中+ 位置有点偏和包括多选控件在内各种图标背景色问题都修正了。
