### ISSUE TITLE
ios 14, 手机客户端待审核文件日期控件显示故障

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#991]
![image](https://user-images.githubusercontent.com/50353452/96391926-01336980-11ed-11eb-858b-e99127bf4b91.png)

手机端待审核有问题、监控箱正常。
电脑端正常
ios 13.7 正常

**Comment by yinlianghui** [comment]
已完成，1.21处理的，1.22已同步相关代码。

**Comment by yinlianghui** [comment]
测试要点：
- android、ios手机、PC上creator/workflow的日期、日期时间控件功能是否正常
- 包括时区会不会差8小时也要测试

**Comment by yinlianghui** [comment]
修改前后以下现象保持不变：
### 暂存时数据库中保存的值
- date类型： string，类似`2020-09-28`格式
- datetime类型: date，存的是utc时间值
### 提交后数据库中最终保存的值
- date类型： string，类似`2020-09-28`格式
- datetime类型: string，类似`2020-10-16T09:33:00.000Z`格式，存的是utc时间值
### 前端控件台InstanceManager.getInstanceValuesByAutoForm()函数获取到的值
- date类型： string，类似`2020-09-28`格式，暂存/提交前后一样
- datetime类型: date，utc时间值，暂存/提交前后一样
