### ISSUE TITLE
业务对象 -> 列表视图 -> 编辑 -> 过滤器 配置问题

### ISSUE THREAD

**Issue by zyx204** [steedos/steedos-platform#994]
业务对象 -> 列表视图 -> 编辑 -> 过滤器

选择的字段为数值类型，只有范围作为条件，无论值填什么都报错

选择的字段为文本类型，只有包含作为条件，无论填什么都查询所有

**Comment by yinlianghui** [comment]
- 选择的字段为数值类型，只有范围作为条件，无论值填什么都报错 => 这个确实有问题，在对应的列表视图查询时会报错
- 选择的字段为文本类型，只有包含作为条件，无论填什么都查询所有 => 这个没有问题，实测下来只要输入字符会按字符条件搜索
- 至于过滤条件只有“范围”或“包含”这个是规则，跟列表视图右侧的过滤器规则是一样
- 1.21与1.22上该问题表现是一样的
![image](https://user-images.githubusercontent.com/6219465/96952076-86d25480-1520-11eb-810d-571537684b4f.png)

**Comment by yinlianghui** [comment]
请移步到前端列表视图界面，右侧有视图过滤器，在零代码管理界面不再支持编辑过滤条件。
![image](https://user-images.githubusercontent.com/6219465/96994431-4ba34600-155f-11eb-8491-dd365c05fe9d.png)
